### ISSUE TITLE
by_induction_on fails for lemmas with two arguments

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#100]
F* cannot prove this lemma using automatic induction:
```
val append_length :
  l1:list 'a -> l2:list 'a ->
  Lemma
    (requires True)
    (ensures (length (append l1 l2) = length l1 + length l2))
let rec append_length l1 l2 = by_induction_on l1 append_length
```

**Comment by catalin-hritcu** [comment]
I think the right way to solve this is to drop using_induction_hyp altogether and implement #51 instead.

**Comment by catalin-hritcu** [comment]
Syntax got changed to `by_induction_on l1 append_length`, but the problem is still here.

**Comment by catalin-hritcu** [comment]
`by_induction_on` is gone for good. It never really worked very well, and Nik would prefer to figure out something properly via a tactic language. Closing as wontfix.
