### ISSUE TITLE
Syntactically identical types are not equal

### ISSUE THREAD

**Issue by csgordon** [FStarLang/FStar#101]
The following produces a cryptic error message:

    module Fail
    
    type Any (a:Type) : a -> Type = fun (x:a) -> True
    assume type t (a:Type) (p:(a -> Type)) : Type
    
    type node (a:Type) : Type =
      | Node : v: (t (node a) (Any (node a))) -> node a
    
    val nodev : node 'a ->  (t (node 'a) (Any (node 'a)) )
    let nodev n = match n with | Node v -> v

The error message is:

    fail.fst(10,39-10,40) : Error
    Expected expression of type "(t (node 'a) (Any (node 'a)))";
    got expression "v" of type "(t (node 'a) (Any (node 'a)))"

I would expect these two types to be equal.

**Comment by nikswamy** [comment]
Thanks for the report, Colin. I'm in the process of revising the implementation of type relations, including subtyping and convertibility. Will address this as I bring that online.
