### ISSUE TITLE
Dependent tuple projectors unimplemented in prims.ml

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1012]
I believed dependent pairs were extracted as pairs and so we didn't need to implement projectors for dependent pairs, but when extracting `M.fst` below I get an `M.ml` that mentions an unimplemented `Prims.dfst`:
- `M.fst`
```F#
module M
let x : (a:bool & b:bool{a == b}) = (| true , true |)
let a = dfst x
```
- `M.ml`
```OCaml
open Prims
let x : (Prims.bool,Prims.bool) Prims.dtuple2 = Prims.Mkdtuple2 (true, true) 
let a : Prims.bool = Prims.dfst x 
```

**Comment by kyoDralliam** [comment]
I guess implementing them is enough, isn't it ? `dtupleN` are still not implemented in the ocaml version for N > 4 though.

**Comment by s-zanella** [comment]
Thanks! That should be more than enough for now.
