### ISSUE TITLE
Discrepancy in the representation of integers in F# vs OCaml builds of F*

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1020]
The implementations of `ensure_decimal` in `src/basic/util.fs` and `src/basic/ml/FStar.Util.ml` do not match.

In F#:

```
> ensure_decimal "0xb8";;
val it : string = "-72"
```

In OCaml:

```
# Z.to_string (Z.of_string "0xb8");;
- : string = "184"
```

cf. 385e9e809eaf35f316491ddd02f532acf03d9aab

**Comment by nikswamy** [comment]
http://stackoverflow.com/questions/2983706/biginteger-parse-on-hexadecimal-number-gives-negative-numbers

"
To make sure that a hexadecimal string is correctly interpreted as a positive number, the first digit in value must have a value of zero. For example, the method interprets 0x80 as a negative value, but it interprets either 0x080 or 0x0080 as a positive value.
"

Seems that we should precede it with a zero. `ensure_decimal "0x0b8"` returns `184`

**Comment by msprotz** [comment]
Thanks for the investigation, fix pushed.
