### ISSUE TITLE
Too many open files?

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1027]
After working for a while, I commonly get a crash with something along the lines of:

```
[F* error] Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
   [F* error] Too many open files
   F*: subprocess exited.
```

Have others run into this too?

**Comment by catalin-hritcu** [comment]
To see whether this is the same problem as in https://github.com/FStarLang/FStar/issues/1023#issuecomment-299912236 please confirm that
- this only happens with the F# version on Mono
- you can make the problem go away by setting a large enough `ulimit -n`

**Comment by cpitclaudel** [comment]
I'll try. It usually takes some time though (1h?).

**Comment by cpitclaudel** [comment]
The error seems different in OCaml:

```
[F* error] Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
[F* error] Unix.Unix_error(Unix.ENOMEM, "fork", "")
F*: subprocess exited.
```

**Comment by mtzguido** [comment]
Haven't seen this in a while.. and looking at open FDs of a long running F* process, I don't see a big amount indicating a leak. Closing..
