### ISSUE TITLE
Encoding of SMT lemmas involving recursive functions introduce matching loops

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1028]
```F#
module MatchingLoops

let rec fact (n:nat) : nat = 
  if n = 0 then 1
  else n `op_Multiply` (fact (n - 1))

val lem_fact (n:nat) : Lemma
  (ensures (fact n >= 0))
  [SMTPat (fact n)]
let lem_fact n = ()  

#reset-options "--log_queries --max_fuel 1 --initial_fuel 1"
let test (n:nat) = assert (fact 3 = 6)
```

This program verifies when it should not. 

The proof of `fact 3 = 6` requires 4 unrollings of `fact`, whereas the proof is supposed to be restricted to use at most 1 unit of fuel.

The trouble is that `lem_fact` when introduced to the SMT solver provides a way to circumvent the fuel instrumentation. Roughly, its encoding to SMT looks like

``` F#
forall (n:nat). {:pattern (fact ZFuel n)} fact MAX_FUEL n >= 0
```

So, given a term `fact ZFuel n` that cannot be unfolded anymore, this quantified formula allows to turn it back into a term with MAX_FUEL which can then be unfolded further.

I have a fix in my branch which I'm testing out today.

**Comment by nikswamy** [comment]
Hmm. Trying to change this behavior leads to some rather counterintuitive results. 

In my branch, I implemented a restriction where all recursively defined symbols in the the body of an SMT lemma are instrumented with `ZFuel`, meaning such occurrences cannot contribute further to unfolding recursive definitions. For instance, in the case of `lem_fact` above, the encoding produces

```forall (n:nat). {:pattern (fact (SFuel ZFuel) n)} fact ZFuel n >= 0```

However, this results in the following kinds of changes to existing proofs.

```
val count: #a:eqtype -> a -> list a -> Tot nat
let rec count #a x = function
  | hd::tl -> (if hd = x then 1 else 0) + count x tl
  | [] -> 0

type is_permutation (a:eqtype) (l:list a) (m:list a) =
  forall x. count x l = count x m

val append_count: #a:eqtype -> l:list a -> m:list a -> x:a ->
  Lemma (requires True)
        (ensures (count x (l @ m) = (count x l + count x m)))
  [SMTPat (count x (l @ m))]
let rec append_count #a l m x =
  match l with
  | [] -> ()
  | hd::tl -> append_count tl m x

let permutation_app_lemma (#a:eqtype) (hd:a) (tl:list a)
                          (l1:list a) (l2:list a)
   : Lemma (requires (is_permutation a tl (l1 @ l2)))
           (ensures (is_permutation a (hd::tl) (l1 @ (hd::l2))))
   = //NS: 05/15
     //This proof required an interesting change following issue #1028
     //From append_count, we can automatically prove what the assert below says
     //However, what we get from append_count is
     //    count' ZFuel x (l1 @ (hd :: l2)) = count' ZFuel x l1 + count' ZFuel x (hd :: l2))
     //where count' is the fuel-instrumented variant of count
     //But, this variant prevents further progress, since we can't unfold the last term in the sum
     //By assertion the equality, we explicitly introduce `count x (hd::l2)` 
     //which can then be unfolded as needed.
     //This is arguably rather counterintuitive ... 
     assert (forall x. count x (l1 @ (hd :: l2)) = count x l1 + count x (hd :: l2))
```

This is arguably counterintuitive ... but then so is being able to prove `fact 3 = 6 ` with 1 unit of fuel. 
Puzzled.

**Comment by nikswamy** [comment]
Another instance of a proof needing to be spelled out more in examples/algorithms/Unification.fst, `key_lemma`

**Comment by aseemr** [comment]
Could we make the fuel a parameter of the lemma's smt encoding? e.g. the ensures clause of the lemma `lem_fact` above is encoded as:

```
(>= (BoxInt_proj_0 (Test.fact @x0))
				   (BoxInt_proj_0 (BoxInt 0)))
			       )
```

instead can we encode it as:

```
(>= (BoxInt_proj_0 (Test.fact.fuel_instrumented @u0 @x0))
				   (BoxInt_proj_0 (BoxInt 0)))
			       )
```

where `u0` is the forall quantified fuel parameter.

Then, when the solver instantiates this lemma, it gets back a term with the same fuel?

**Comment by aseemr** [comment]
We change the pattern also to mention the fuel. But not sure if that's how the solver would work.

**Comment by aseemr** [comment]
Just thinking out aloud, this is how the first example should fail to verify (writing `nF` for `n` units of fuel, and `fact'` for fuel instrumented version of `fact`):

we start with `fact' 1F 3`, then with one unfolding we get: `fact' 0F 2`, with the new lemma encoding, `u0` will be instantiated with `0F`, and so applying the lemma would give `fact' 0F 2 > 0`, which does not enable further unrolling.

**Comment by nikswamy** [comment]
Thanks for the discussion, Aseem. 

I considered making the fuel parameter an argument of the lemma, but I rejected it because:

a. Adding a fuel parameter to every recursive function in the encoding of the lemma makes for a difficult technical problem, since now every term may have an additional free (fuel) variable. This would require closing over this additional variable in the generated SMT lemma (relatively easy) and also in any auxiliary definition that may be generated while encoding this SMT lemma (very hard, in the current code).

b. I don't think this the addition of this fuel parameter adds an expressiveness benefit. We already emit axioms telling us that the fuel parameter is irrelevant semantically. So, given `g (S f) x` we already derive that it's equal to `g Z x`. So, peeling off one unit of fuel on each SMT lemma instantiation doesn't really seem that useful to me ... but maybe I'm missing something. What problem do you think your proposal will solve? There will always be the case where the occurrence of the term in the lemma has zero fuel and so is not eligible for further unfolding (by design).

Overnight, I think my perspective on this issue has evolved. Here's my current thinking which I will experiment with today:

1. We should not attempt to automatically prevent matching loops in lemmas decorated with SMTPat. The user wrote the pattern and it's the user's responsibility to chose a proper pattern to prevent matching loops. 

2. Given a well-chosen SMTPat, the encoding should not inadvertently introduce matching loops that break the fuel instrumentation of a recursive function. 

With this in mind, I think the encoding of `lem_fact` should be:

```forall (n:nat).{:pattern (fact' 0F n)} fact' 0F n >= 0```

Notice that the trigger uses `0F` as does the occurrence of `fact'` within the lemma. As such, firing the lemma cannot introduce further unfolding of recursive functions (my point 2).

On the other hand, this encoding does not try to automatically prevent the matching loops within the lemma itself. And that's also a a good thing. For instance, the encoding of `append_count` would be something like

```forall a l m x. {:pattern count' 0F x (l @ m)} count' 0F x (l @ m) = count' 0F x l + count' 0f x m```

Now, if this lemma is instantiated with with `m = m0 @ m1` then, the occurrence of `count' 0F x m` is eligible to fire the quantifier again, which is good, since the user-provided pattern is sufficiently discriminating. i.e., this is a instance of my point (1) above.

**Comment by aseemr** [comment]
W.r.t. (a), I agree it requires closing over the additional fuel variable `u0` (easy as you say), but I don't see why would this require any change in the auxiliary definitions. I was thinking of adding this fuel parameter only to the lemma encoding, and then using the fuel instrumented version of the recursive function (`Test.fact.fuel_instrumented @u0 @x0`) in the encoding of lemma *ensures*, rather than the non fuel instrumented version (`Test.fact`).

W.r.t. (b), I did not mean to decrease the fuel during the lemma instantiation, that would be incorrect, I think. I only mean that since the fuel parameter is now part of the variables that the solver would instantiate, the returned fact would mention the recursive function with the same fuel, hence avoiding the problem of producing the symbol with max fuel or zero fuel. Perhaps I did not explain the example well. Here is what I mean. Suppose we start with `fact' 1F 3`. If the solver, decided to fire the lemma at this point, it will get `fact' 1F 3` only, thereby the unrolling still restricted to `1F`. On the other hand, the solver might unroll the definition of `fact` to get `fact' 0F 2`. And now, if the solver fires the lemma, it's going to get `fact' 0F 2` itself.

**Comment by nikswamy** [comment]
Discussed this offline with Aseem. We agreed that instrumenting SMT lemmas that mention recursive functions with zero fuel seems a good balance of tradeoffs.

**Comment by nikswamy** [comment]
Here's an example proof from hacl-star that was succeeding only because of these matching loops. In fact, it seems to require at least 8 unfoldings to succeed.

```
val load_uint32: len:UInt32.t { v len <= 4 } -> buf:lbuffer (v len) -> ST UInt32.t
    (requires (fun h0 -> live h0 buf))
    (ensures (fun h0 n h1 ->
      h0 == h1 /\ live h0 buf /\
      UInt32.v n == little_endian (sel_bytes h1 len buf)))

let rec load_uint32 len buf =
  if len = 0ul then 0ul
  else
    let h = ST.get () in 
    let len = len -^ 1ul in
    let m = load_uint32 len (sub buf 1ul len) in
    lemma_little_endian_is_bounded (sel_bytes h len (sub buf 1ul len));
    assert (UInt32.v len <= 3);
    assert (UInt32.v m < pow2 (8 * (UInt32.v len)));
    (* FStar.Math.Lemmas.pow2_le_compat (8 * 3) (8 * (UInt32.v len)); *) //now this lemma invocation is needed
    assert (pow2 (8 * (UInt32.v len)) <= pow2 (8 * 3)); 
    (* FStar.Math.Lemmas.pow2_plus 8 (8 * 3); *) //now this lemma invocation is needed
    assert (pow2 8 * pow2 (8 * 3) = UInt.max_int 32 + 1);
    assert (UInt32.v m * pow2 8 <= UInt.max_int 32);
    let b = buf.(0ul) in
    assert_norm (pow2 8 == 256);
    FStar.UInt32.(uint8_to_uint32 b +^ 256ul *^ m)
```

The proofs of things like `    assert (pow2 (8 * (UInt32.v len)) <= pow2 (8 * 3)); ` were only succeeding because SMT lemmas about `pow2` were allowing it to be unfolded indefinitely.

Now, explicit lemma invocations are needed, which is more predictable and more inline with the other proofs in hacl-star.
