### ISSUE TITLE
Tutorial Ex04d mismatch?

### ISSUE THREAD

**Issue by manojo** [FStarLang/FStar#1031]
In the tutorial, we are asked to prove that reverse in [injective](https://github.com/FStarLang/FStar/blob/fe09a9dbe2dce098c35be650287b61298376ecb2/doc/tutorial/tutorial.mdk#L1259). Yet the given lemma is for [snoc_injective](https://github.com/FStarLang/FStar/blob/fe09a9dbe2dce098c35be650287b61298376ecb2/doc/tutorial/code/exercises/Ex04d.fst#L28), despite the solution itself giving a proof for [reverse_injective](https://github.com/FStarLang/FStar/blob/fe09a9dbe2dce098c35be650287b61298376ecb2/doc/tutorial/code/solutions/Ex04d.fst#L37). Shouldn't the question be changed to reflect this?

**Comment by catalin-hritcu** [comment]
Well spotted, should be fixed now.
