### ISSUE TITLE
Breaking transluscent abstractions

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1032]
```F#
module A
open FStar.Ghost
let ff (a:Type) (x:erased a) : Tot a = 
    assert (reveal x == x); x
```

that's very worrying

seems to be a combination of effect downgrading (Ghost unit to Pure unit); allowing the SMT solver to deduce equations about type variables; and retaining in SMT the definitions of functions manipulating abstract types

with @tahina-pro

**Comment by nikswamy** [comment]
Actually, this is less worrying that I hurriedly concluded earlier. 

A few points: 

First off, we need to change FStar.Ghost for sure, e.g., by marking reveal abstract. But, perhaps better doing what follows. 

Now for why this is less worrying as a general problem. 

1. The definitive way to enforce abstractions in F* is to use an interface. With an .fsti, the definition of the symbol you're trying to protect simply isn't present, so you can't really inadvertently break abstraction. 

2. The `abstract` qualifier on a definition `f` in a .fst simply removes the definition of `f` from the context of a client module. This is as per https://github.com/FStarLang/FStar/wiki/Qualifiers-for-definitions-and-declarations#abstract. Nevertheless, this does not guarantee that a client is parametric in `f`. For example, nothing prevents a module from intentionally leaking the abstraction, e.g., we routinely include things like

```
abstract type secret i = bytes
let leak #i (s:secret i) : ST bytes (requires (fun h -> compromised h i)) (ensures (fun h _ h' -> h=h'))
```

Or even more simply:

```
abstract type secret = int
let reveal (): Lemma (secret = int) = ()
```

As usual, an ADT only enforces those abstractions maintained by its interface.

So, I don't think we need to change anything in the type checker. We just need to revise FStar.Ghost.

And, if you're trying to enforce abstractions using `abstract` qualifiers in an `.fst`, think carefully about it and consider using an .fsti since it provides safer defaults.

**Comment by aseemr** [comment]
Regarding your point 1 above, this holds true currently since we drop the `.fst` when type checking the client, but given this new feature coming up for type checking the clients with the interleaving, we need a way to mark things `abstract` when using `.fsti` and `.fst`. This is currently not possible, as far as I understand (we don't allow `val` in `.fsti` to be marked `abstract`).

**Comment by aseemr** [comment]
Also, even with an interface one can write:

```
val t :Type0

val lemma: unit -> Lemma (t == int)
```
So, whether using `abstract` or interfaces, one needs to careful about such leaks.
