### ISSUE TITLE
Subtyping and lists

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1039]
The following bit of code fails:

```
assume val p: int -> bool
assume val f: list int -> int
assume val l: list (z: int{p z})
let g = f l
```

Is there a way to make it work, short of the following (which has a computational cost)?

```
assume val p: int -> bool
assume val f: list int -> int
assume val l: list (z: int{p z})
let g = f (List.Tot.map (fun (x: int{p x}) -> x <: int) l)
```

(I think this was discussed before, but I couldn't find a pointer).  One of the difficulties is that this kind of subtyping doesn't play well with mutation.

**Comment by catalin-hritcu** [comment]
This was indeed discussed many times before and is tracked in #65 (one of our oldest issues at this point).

@nikswamy @kyoDralliam @aseemr  At some point last fall-winter there was some hope that we can make polarities work ... but I'm not sure that's still the case now.
