### ISSUE TITLE
Mistaking `==>` for `->` yields hard-to-diagnose errors

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1041]
An error I kept making when I started out was to write `->` instead of `==>`; for example:

```
module Test

// Works
let f x : Lemma (True ==> x == x) = ()

// Fails
let f x : Lemma (True -> x == x) = ()
```

Is there a way, short of hard-coding, to give a better error message here? (This is a soft issue — it might be better suited for the mailing list, and there may not be an obvious way to improve this)

**Comment by catalin-hritcu** [comment]
Just for the record, the error message here is `could not prove post-condition`, which is indeed horrible.

A good solution for preventing such nonsense logical formulas using the type-checker not the SMT solver is to define our logical connectives in `prop` (now tracked as #1048). Could return to this together this summer if you wish.

**Comment by aseemr** [comment]
I agree with Catalin, the proper fix is to have proper support for `prop`. I added a comment in #1048 for this, closing this issue.
