### ISSUE TITLE
Some cases where Extraction produces invalid OCaml

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#1050]
While trying to extract the whole standard library, I stumbled on some corner case of the extraction that should be fixed at some point.

- [x] extracting names to ocaml kewords (for example a variable called `sig`)
- [ ] extracting an empty datatype to an empty datatype (which is not accepted in ocaml, we should make it abstract)

**Comment by msprotz** [comment]
I'm surprised the first bit is not caught by https://github.com/FStarLang/FStar/blob/master/src/extraction/FStar.Extraction.ML.Syntax.fs#L42 ... ?

**Comment by kyoDralliam** [comment]
If I'm not mistaken the first part was fixed by @victor-dumitrescu  and @mtzguido

**Comment by mtzguido** [comment]
The first bit was indeed kinda fixed by several bandaid patches, and then definitely fixed by Nik for #310. I'm trying a fix for the the second point now.
