### ISSUE TITLE
Trailing space on set-options confuses F# build.

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1051]
The following fails, but only in the F# build

```
module A
// ./A.fst(3,0-3,31): (Error) Failed to process pragma: wrong argument given to option 'max_ifuel'
#reset-options "--max_ifuel 0 "

let x = 2
```

Note the trailing space after `0`. Removing that makes it work. The OCaml build works for both. (should we add an `f#-vs-ocaml` label?)

I suspect some subtle difference in the respective getopt files, but a quick look didn't reveal anything.

**Comment by catalin-hritcu** [comment]
At this point I have a metaissue for this (#746), but I agree that given the large number of issues we're having a tag might be more appropriate so feel free to change.

**Comment by mtzguido** [comment]
Ah, I had forgotten about that one! Thanks for linking it to this one.

Made a label and tagged the issues I could find. If anyone feels the label just adds noise let me know.

I'll take a look at this particular issue too.

**Comment by mtzguido** [comment]
There were two problems here:

1- F#'s split will return empty strings
```
> "  a   b   c  ".Split[|' '|];;
val it : string [] = [|""; ""; "a"; ""; ""; "b"; ""; ""; "c"; ""; ""|]
```
So, I now filter them out to have the same behaviour as OCaml's String.split.

2- The error was bogus, the exception was being thrown at the default handler (called with `""`) and not at the processing for `max_ifuel`.

Should be fixed now.
