### ISSUE TITLE
Online editor fails on `open FStar.All`

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1052]
Serdar Tasiran reports by email that he has troubles with the online editor with a file containing only this:
```
module Bug
open FStar.All
```
The error message is
```
/var/fstar/ulib/FStar.ST.fst(26,13-26,21) : (Error) Identifier not found: [st_pre_h]
```
I could reproduce this with the online editor, but things work fine from the command line:
```
[hritcu@resurrected bug-reports]$ fstar.exe bug.fst
Verified module: Bug (17 milliseconds)
All verification conditions discharged successfully
```
@ad-l You know the code for invoking F*, any ideas what could cause this?

**Comment by catalin-hritcu** [comment]
This problem affects for instance exercise 10a from Section 10.1.Stateful access control.

**Comment by stasiran** [comment]
The same simple module 

module Bug
open FStar.All

now gives the following error:

/var/fstar/ulib/FStar.Heap.fsti(46,52-46,66) : (Error) Identifier not found: [Prims.tuple2]
Module Prims resolved into Prims, definition tuple2 not found

**Comment by aseemr** [comment]
Is online editor using explicit deps? The last error is because I moved the tuple2 to Pervasives.

**Comment by catalin-hritcu** [comment]
You can see / change how the online editor invokes F* in `<fstar-priv>/website/run.php`. I don't see any explicit deps there, but maybe I'm missing something.
```
 passthru("timeout 40 /var/fstar/bin/fstar.exe --fstar_home /var/fstar $hh --include /var/fstar/doc/tutorial/code/solutions --include /var/fstar/ucontrib/Platform/fst --include /var/fstar/ucontrib/CoreCrypto/fst --smt /var/fstar/bin/z3 ".implode(' ', $mods)." 2>&1");
```

**Comment by catalin-hritcu** [comment]
@aseemr @ad-l Any progress on this? still getting the `definition tuple2 not found` error

**Comment by catalin-hritcu** [comment]
The problem for me is that without more information about what's happening on the server I can't reproduce this problem locally. Tried running a local equivalent of the `passthru` command above, but that just works for me:
```
fstar.exe --fstar_home /home/hritcu/Projects/fstar/pub --include doc/tutorial/code/solutions --include ucontrib/Platform/fst --include ucontrib/CoreCrypto/fst --smt /home/hritcu/Apps/z3-4.5.0-x64-ubuntu-14.04/bin/z3 blah.fst
Verified module: Blah (5 milliseconds)
All verification conditions discharged successfully
```

**Comment by catalin-hritcu** [comment]
The online editor saga continues
```
module Bug
open FStar.List.Tot.Base
```
causes
```
/var/fstar/ulib/FStar.Classical.fst(4,34-4,51) : (Error) Unexpected number of universe instantiations
```

**Comment by catalin-hritcu** [comment]
Even the first tutorial example fails because of the last error, even when simplified to this:
```
module Ex01a
open FStar.All
```
```
/var/fstar/ulib/FStar.Classical.fst(4,34-4,51) : (Error) Unexpected number of universe instantiations
```

**Comment by markulf** [comment]
If I recall correctly, this was fixed by @ad-l, the main reasons for the different bugs reported being that the tutorial server did not update the `fstar` binary due to a build failure that went unnoticed.

**Comment by markulf** [comment]
Should we open a separate issue for implementing some kind of notification service to prevent similar issues in the future?

**Comment by catalin-hritcu** [comment]
I think what @msprotz proposed would be the best: running a normal (dirty) build and if that fails purging the whole repo and trying again. This way if master builds cleanly there should be no problems reproducing that.

**Comment by mtzguido** [comment]
AFAIK the update process for the F* binary for the tutorial works well now (at least we haven't seen it fail in a long time). However, our tutorial is still not under CI. Should we have an explicit issue for that? (I think we can close this one.)

**Comment by nikswamy** [comment]
New tutorial is under CI and @tahina-pro recently updated the container running the website to use recent F* binaries. So, these issues should be resolved
