### ISSUE TITLE
F# build of F* still uses bounded machine integers for ints

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1054]
This is biting us back now in the compiler code (#1053), so time to have at least a separate issue for this unsoundness.

**Comment by nikswamy** [comment]
I'm happy to consider this at a high priority. But, genuine question: What's our official stance on the compatibility of F# vs OCaml builds.

We have so many discrepancies already ... I'd love to resolve them all some day, but is it the highest priority?

**Comment by catalin-hritcu** [comment]
Not sure about global priorities, but many people seem to be interested in helping with this (Christoph especially, but others too) and we have been making great progress recently at identifying and fixing such discrepancies. Just for indication, half of the issues in #746 are now fixed, and we are only ~3 problems away from having our whole test suite working with the F# version (#1023). So I'm quite optimistic :)

**Comment by A-Manning** [comment]
Fixed in #1283

**Comment by catalin-hritcu** [comment]
The PR was merged on Oct 25, 2017
