### ISSUE TITLE
Feature request: A "fail" keyword to mark and accept expected failures

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1057]
The idea is to be able to write things like `fail let a: nat = true`, and F* would print an info message instead of an error (and ignore that line.  Conversely, writing `fail let b : nat = 1` would raise an error, because that command doesn't fail.

This feature exists in Coq, and it's really convenient for regression testing (to check that expected failures still fail), but also (more importantly) for writing tutorials. For example, where one currently writes 

> (* assert false // Uncomment this to see the error *)

one would write this instead:

> fail assert false

**Comment by catalin-hritcu** [comment]
We discussed this before and I made a proposal for this #231 which doesn't just checks that something fails (that's too easy, you can fail because of parsing or whatever other crap), but it fails for the right reason.

**Comment by cpitclaudel** [comment]
Looks good, though I think your proposal is mostly about the regression testing aspect, right?
The fail keyword that I'm suggesting would also let you continue processing the file, which is nice in e.g. a tutorial.

**Comment by catalin-hritcu** [comment]
I don't think the two use cases you mention are in any way incompatible. Even for regression testing it would be great to continue processing the file.

**Comment by cpitclaudel** [comment]
Good point. Maybe we should close this, then :)
