### ISSUE TITLE
Factorial function in tutorial doesn't typecheck

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1058]
The problem is the `*` (this seems to be a reoccurrence from https://github.com/FStarLang/FStar/issues/598 ?)

```
val factorial: x:int{x>=0} -> Tot int
let rec factorial n =
  if n = 0 then 1 else n * (factorial (n - 1))
```

```
(Error) Expected expression of type "Type"; got expression "n" of type "(x#6:int{(b2t (op_GreaterThanOrEqual x@0 0))})" 
```

**Comment by cpitclaudel** [comment]
(The example that can be loaded in the editor later works fine (it opens `FStar.mul`), but the first mention of factorial doesn't).

**Comment by markulf** [comment]
I am adding a remark to the tutorial pointing out this oddity of F*. Not sure what the most gentle way of doing this is. What do other proof-oriented programming languages do about this? Is there already an issue discussing alternatives?

**Comment by markulf** [comment]
https://github.com/FStarLang/FStar/issues/614#issuecomment-243146985

**Comment by cpitclaudel** [comment]
> What do other proof-oriented programming languages do about this? Is there already an issue discussing alternatives?

Coq has notation contexts (you write `(1 * 3)%nat`)

**Comment by s-zanella** [comment]
Not as convenient, but you can write `FStar.Mul.(n * (factorial (n - 1)))`. The inconvenience comes from the fact that you must already have `FStar.Mul` as a dependency when you write this in interactive mode.

**Comment by nikswamy** [comment]
There's a remark explaining FStar.Mul at the first occurrence of factorial in the tutorial now. Closing.
