### ISSUE TITLE
Support for opening standard modules in Tutorial examples

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#106]
Heap, Set, ST, List, Array are what stops us from having loadable examples for Section 8 (State) and 9 (Crypto).

E.g. in 9.3 ex2a-can-read-write-types(8,13-8,16) : Error Identifier not found: [seq]

On the server the examples are at the moment run without any libraries other than prims.fst, and seq is defined in lib/array.fst.

**Comment by markulf** [comment]
Its probably easy for Antoine to give us the libraries we need, but how to make sure these are all the libraries we need so we don't have to go back and forth. Best to make it configurable?

**Comment by catalin-hritcu** [comment]
As a short term solution I'm trying to bring back these files in the editor script (run.php). Longer term something more configurable would be better, although editing run.php could also be called "configurable" ... it's in <fstar-priv>/website/run.php and we can all edit it, just that I don't know how to make the server take over the changes.

**Comment by ad-l** [comment]
I can arrange either options easily. Let's talk about it tomorrow.

**Comment by catalin-hritcu** [comment]
@ad-l Cedric can say for sure, but I don't think this can wait until tomorrow. How do I make the server take over my changes to `run.php`?

**Comment by ad-l** [comment]
By pushing them on fstar-priv

**Comment by catalin-hritcu** [comment]
Done that but nothing happened. My change was this:
 passthru("timeout 40 mono /var/fstar/bin/fstar.exe --fstar_home /var/fstar --smt /var/fstar/bin/z3 --verify /var/fstar/lib/string.fst /var/fstar/lib/partialmap.fst /var/fstar/lib/list.fst /var/fstar/lib/st.fst $tmp 2>&1");
Is that the proper way to do it?

**Comment by ad-l** [comment]
I would be in favor of detecting the use of "open <ModName>" in the input and only add the corresponding file to the command line if necessary (otherwise, it can slow down the compilation of simple examples)

**Comment by catalin-hritcu** [comment]
Fair enough, can you make this change? I still don't understand how this works (e.g. why my change was ignored).

**Comment by ad-l** [comment]
I don't think it was ignored. Running F* on Fibonacci now outputs:
Verified module: String
Verified module: Set
Verified module: Map
Verified module: Heap
Verified module: Array
Verified module: List
Verified module: ST

**Comment by catalin-hritcu** [comment]
I see it was taken over now, it took ~30 minutes though. Is that normal?

Anyway, my change should be enough for what Cedric and Markulf need at the moment. Up to you if you want to do the more elegant fix.

**Comment by ad-l** [comment]
Alright, now the file is only parsed if the module is opened.
To see the status of the lastest website update you can download https://www.fstar-lang.org/UPDATE

**Comment by markulf** [comment]
Was wondering whether that's a related bug:

/var/fstar/lib/prims.fst(18,5-18,9) : Error
Duplicate top-level names Prims.Unop

Try for instance Exercise 6e: Insertion sort.

**Comment by ad-l** [comment]
Yes, right

**Comment by ad-l** [comment]
By the way you should add "open ST" to 9a

**Comment by markulf** [comment]
Yes, done
