### ISSUE TITLE
Refinements on function types confuse the arguments count checker

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1060]
F* rejects this:

```
val id : #a: Type -> f:(list a -> Tot (list a)){True}
let rec id #a = (fun l -> l)
```

> From its type Prims.Tot ((f:(uu___936906:Prims.list a -> Prims.Tot (Prims.list a)){ Prims.l_True })), the definition of `let rec id` expects a function with 1 argument, but 2 arguments were found

but accepts this:

```
val id : #a: Type -> f:(list a -> Tot (list a)){True}
let id #a = let id' l = l in id'
```

Is that expected?

**Comment by nikswamy** [comment]
In general, it would be good to allow function definitions/lambda terms to be given refined types directly. 

Currently, this requires an annoying indirection. One has to write

```
let f : (t -> t') = fun x -> e
let f' : (f:(t -> t'){phi}) = f
```

**Comment by mtzguido** [comment]
This should now work since `arrow_formals_comp` descends into refinements.
