### ISSUE TITLE
Normalizer: interference between joined branches in `match`

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1062]
It seems there's a bug in the reduction for matches when two branches are joined. The following code should verify, since `f (B 5 3)` should evaluate to 3, but it evaluates (apparently) to `-1`, indicating that the `A` pattern is interfering since its names are backwards.

```
type t =
    | A : int -> int -> t
    | B : int -> int -> t
    | C : int -> int -> t

let f (x : t) : int =
    match x with
    | A j i
    | B i j ->
        (i - j) + 1
    | C i j ->
        i + 1

let _ = assert_norm(f (B 5 3) == 3)
```

If one splits the `A` pattern from the `B` pattern (defining the `A` one in whatever way, it's not relevant), the file verifies. It also verifies if one uses `assert` instead of `assert_norm`.

**Comment by mtzguido** [comment]
Also there is something wrong when the amount of wildcard patterns differ between two joined branches. In this example:

```
type t =
    | S : t -> t -> t
    | C : int -> t

let f (x : t) : int =
    match x with
    | S (S (C i) _) j
    | S (C i)       j ->
        i
    | _ -> 42

let _ = assert_norm (f (S (C 8) (C 9)) == 8)
```

The equality should hold (and does without `norm`), but somehow `f (S (C 8) (C 9))` reduces to `S (C 8) (C 9)` instead of `8`, which is **ill-typed!**. From the SMT query:

```
(assert (! (not
;; def=/home/guido/fstar/bin/../ulib/prims.fst(183,37-183,74); use=./A.fst(14,8-14,19)
(or label_13

;; def=/home/guido/fstar/bin/../ulib/prims.fst(183,37-183,74); use=./A.fst(14,8-14,19)
(= (A.S (A.C (BoxInt 8))
(A.C (BoxInt 9)))
(BoxInt 8))
)
)
:named @query))
```

**Comment by nikswamy** [comment]
This is super ugly. I'm trying to fix it ASAP. Clearly, it is a soundness bug. 

In most places in the compiler we work with pattern matching after opening the terms and using a named representation. So, in the SMT encoding for instance, this is handled correctly. The normalizer is trying to be smart (ha) and stay in de Bruijn representation and I screwed it up here.
