### ISSUE TITLE
Wrong code generation with inline_for_extraction and erased

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1064]
When marking a type definition using `FStar.Ghost.erased` as `inline_for_extraction`, F* generates OCaml code that correctly erases the type definition, translating it as `unit`, but in functions that use the type the original type definition is unfolded, breaking the extracted code.

This used to work until not so long ago (e.g., in 2716a3cd720dbdfa2dd008e6e653274721c8f199). The issue manifests itself when extracting code from HACL*, namely `Hacl.Impl.Poly1305.64`, breaking CI for miTLS and blocking the Everest nightly upgrade.

```
module M

open FStar.ST
open FStar.Ghost

inline_for_extraction let t = erased int

val f: t -> Stack unit
  (requires (fun _ -> True))
  (ensures  (fun _ _ _ -> True))
let f log = ()
```

```
bin/fstar.exe --codegen OCaml --include ~/everest/FStar/ulib M.fst && cat M.ml
...
Extracted module M
Verified module: M (513 milliseconds)
All verification conditions discharged successfully
open Prims
type log_t = Prims.unit
let f : Prims.int FStar_Ghost.erased -> Prims.unit = fun log  -> () 
```

The workaround is not to mark such definitions as `inline_for_extraction`.

**Comment by nikswamy** [comment]
I don't see the problem here any more.

Given this definition of `FStar_Ghost.erased`, this extracted code should still be type-correct:
https://github.com/FStarLang/FStar/blob/master/ulib/ml/FStar_Ghost.ml#L1

@s-zanella: can you confirm the issue and close if appropriate, please?

**Comment by s-zanella** [comment]
We didn't have an implementation of `FStar_Ghost.erased` at the time this issue was filed.
We do have one since 78d69c8062dec661d04cd876a5a484a6bf8e613a and it solves this issue.
