### ISSUE TITLE
Missing universe instantiation when using let binding as type of an inductive

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1078]
F* fails on the following code:

```
module Missing_universe_instantiation

let language = string -> GTot Type

noeq type star (l: string -> GTot Type) : language =
  | Star_nil : star l ""
  | Star_append : s1:string -> s2:string ->
      l s1 -> star l s2 -> star l s1
```

```
$ fstar.exe missing_universe_instantiation.fst
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: missing universe instantiation on language")
```

Note that the annotated type of `star` has an effect. In retrospect this doesn't make that much sense, but inlining the definition of language above causes F* to accept the type `star`.

**Comment by aseemr** [comment]
This is no longer a universe error. Rather, error comes because the annotation `:language` is not unfolded and we get an error that it is not a `Type`. Manually unfolding it works. I will try to fix it.

**Comment by aseemr** [comment]
Definitions marked as `unfold` are now unfolded in the inductive type. I wasn't sure if unfolding more is a good idea (e.g. what about `abstract` definitions?). So, the testcase as referenced in the commit above works now. Closing.
