### ISSUE TITLE
Syntax proposal - "it" keyword

### ISSUE THREAD

**Issue by Jake456** [FStarLang/FStar#108]
Why not use the "it" keyword as an identifier for the refined value?
This will work for both function parameters & return values:

    val foo : int{it > 42} -> Tot int{bar it < 0}

This will reduce the need for the Lemma keyword.

(Xtend uses the same approach when allowing you to omit the arguments section in lambda expressions with a single argument, using the "it" identifier in the body:
```
textField.addActionListener([
   textField.text = "The command '" + it.actionCommand + "' happened!"
])
```
)

**Comment by markulf** [comment]
Am I missing something or could you write?

    val foo : int{it > 42} -> Tot int{bar it < 0}

**Comment by Jake456** [comment]
You're write, the x param name is unnecessarily (I'll edit my message).
In any case, the "it" discussion still applies.

**Comment by nikswamy** [comment]
This syntax works for the special case in which you have non-dependent functions. How will you write

```
x:int -> y:int -> z:int{z = x + y}
```

The best you can do is 

```
x:int -> y:int -> int{it = x + y}
```

**Comment by Jake456** [comment]
It works for every case, for the _redined_ value.
```it``` only identifies the refined value; nothing else.

The nice thing about it, is that the type & its refinement are a self-contained expression.

Say you wanted to support Generics in some form in a future version of the language (is it supported currently?);

With the "it" keyword, one could define 
```val d:Dictionary<int{it > 0}, List<int{foo it>42}>>``` 

(borrowing C#'s generics syntax here; the actual syntax doesn't really matter for the conversation).

Without "it", you'd need to write:
````type t = Dictionary<a:int{a > 0}, List<i:int{foo i>42}>>```

The explicit identifier here seems really confusing.

**Comment by nikswamy** [comment]
Yes, we support generics. More generally, we have higher-rank polymorphism. 

Regarding `it`: The current syntax with explicit binders is more general. I agree that, in certain special cases, the `it` notation is more compact, but I'm not convinced that it is necessarily clearer. No promises about supporting it ... perhaps.

**Comment by Jake456** [comment]
"perhaps" is not a bad start :)

**Comment by catalin-hritcu** [comment]
I agree with Nik, our current syntax is more general and uniform. For more even uniformity we should solve #84 and #59.
