### ISSUE TITLE
Broken online tutorial

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#1080]
Apparently the online tutorial fails with this error:
```/var/fstar/ulib/FStar.Classical.fst(4,34-4,51) : (Error) Unexpected number of universe instantiations```
when writing a simple
```
module M
open FStar.List.Tot
```

**Comment by beurdouche** [comment]
Apparently it is worse, seems to be on most module openings...

**Comment by catalin-hritcu** [comment]
Also discussed this in #1052

**Comment by markulf** [comment]
Closing as I strongly suspect this was fixed.

**Comment by catalin-hritcu** [comment]
fixed indeed
