### ISSUE TITLE
Function call in type checker seemed to be irrelevant

### ISSUE THREAD

**Issue by shaolintl** [FStarLang/FStar#1083]
When type checking a top level let rec (`TcTerm.check_top_level_let_rec`), there is a call to `Subst.open_let_rec`. In the call, it opens the let_rec only if it is not a top level one. So it seems that the call there is meaningless since it happens only for top level ones as far as I can see.

Checking of letrecs applies guards to make sure the values on the bound variables are decreasing. How does it relate to opening the let rec? It is supposed also to open universe variables, should this happen anyway? What is the difference between a top level one and a nested one?

Is the definition is_top_level dynamic? I.e. does it change during type checking?

@nikswamy Should I remove this line from `TcTerm.check_top_level_let_rec`?

**Comment by nikswamy** [comment]
This is fixed here (we actually still need to open the universe variables):

https://github.com/FStarLang/FStar/blob/c_fstar-build_two_phase_checker/src/syntax/FStar.Syntax.Subst.fs#L544

Closing.
