### ISSUE TITLE
let definition cannot be the last item of an interface

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/FStar#1088]
Can I have a let definition as the last item of an interface? It seems not.

Indeed, consider the following interface file `X.fsti`:
```
module X
val x: int
let y: int = x + 1
```
and the corresponding implementation file `X.fst`:
```
module X
let x = 1
```
Then, `fstar.exe X.fst` fails with the following error:
```
./X.fst(1,7-1,8): (Error) Some interface elements were not implemented by module X:
	let y
1 error was reported (see above)
```
This error disappears if I add another declaration after `y` in `X.fsti` (and implement it accordingly in `X.fst`)

**Comment by tchajed** [comment]
This just bit me - it turns out it applies to all the let definitions at the end of an interface, not just the final one.
