### ISSUE TITLE
Only implicit types at the start of a function are erased

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1095]
When a function with several implicit arguments is extracted, only implicit types at the start of the arguments are erased.
```
val fail: #a:Type -> a -> #b:Type -> b -> #c:Type -> (a-> b -> c) -> c
let fail #a x #b y #c f = f x y
```
Extracts to (in F# and OCaml Respectively)
```
let fail = (fun ( x  :  'Aa ) ( b  :  Prims.unit ) ( y  :  obj ) ( c  :  Prims.unit ) ( f  :  'Aa  ->  obj  ->  obj ) -> (f x y))

let fail x b y c f = f x y 
```
Changing the function to place the implicit types at the start works : 
```
val pass: #a:Type -> #b:Type -> #c:Type -> a -> b -> (a-> b -> c) -> c
let pass #a #b #c x y f = f x y
```
Extracts to
```
let pass = (fun ( x  :  'Aa ) ( y  :  'Ab ) ( f  :  'Aa  ->  'Ab  ->  'Ac ) -> (f x y))

let pass x y f = f x y 
```
This does not work when implicits that are not Type are present; A function with
```
val fail2 : #a:Type -> #n:nat -> #b:Type -> ....
```
Will extract to
```
let fail2 = (fun ( n  :  Prims.nat ) ( b  :  Prims.unit ) ...

let fail2 n b ... 
```

**Comment by nikswamy** [comment]
Implicit arguments cannot, in general, be removed. 

F* will try to extract some polymorphic functions to ML-polymorphic functions in OCaml/F#. But it cannot extract all F* functions in this way. In particular, your example uses a kind of higher-rank polymophism.

Closing this issue.
