### ISSUE TITLE
Pattern matching on functions? And default effects on top-level pure/ghost terms

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1097]
Despite the surprising title, we're not sure this is actually a bug.

The following code works just fine.
```
let m (f : int -> int) : Tot int =
    match f with
    | x -> 0
```
This is because F* can prove (via z3!) that the match is total, since there is a single catch-all pattern. This also actually *extracts* correctly, since the match is optimized away.

This is a consequence of matching being very semantic in F*, but struck me and @nikswamy as very odd anyway.

I tried to get a contradiction from this, but couldn't, as really the only possible patterns one can provide for are wildcards and variables (or none). Here are some more examples, the first one being something that might desirable.

```
let m2 (a:Type) (_ : a == int) (x : a) =
    match x with
    | 0 -> 0
    | _ -> 1

let f (x:int) = x
let m3 =
    match f with
```

The last one (I believe..) has a non-sat WP (so no proof of false), although I wonder what's the inferred type for it...

Also, inlining the definition of `f` in `m3` will complain with
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Ill-typed term: cannot pattern match an abstraction
```
meaning there are some don't-pattern-match-a-lambda checks in place.

So, putting this out here for comments. Is this just fine? Should we be aggresive in forbidding matches on function types? What to do in cases like `m2`, then?

**Comment by nikswamy** [comment]
Wow, this is super unintuitive. Even aside from the surprise of allowing to write these degenerate matches for function-typed terms, I had a couple of surprises. 

1. I didn't expect `m3` to typecheck. This variant rightly fails to typecheck

```
let m4 (f:(int -> int)) = match f with
```
2. `m3` above typechecks, but it actually has a type with a precondition that is unsatisfiable. After generalization, its inferred type seems to be equivalent to:
`#a:Type -> PURE a (fun post -> False)`

So, if you try, say `let test = m3 #unit` then this fails to typecheck (correctly).

I would have expected the top-level default effect rule to kick in and reject `m3` because its type is not `Tot`. But, somehow its getting generalized with a `False` wp.

If you instead write:

```
assume val d : unit -> Dv unit
let m3 = d(); ((match f with) <: unit)
```
Then you get a "patterns are incomplete" error on the match. So, the presence of the `Dv` effect prevents this unexpected form of generalization from kicking in.

So, yes, no unsoundness here (yet?), but it seems very weird indeed. I'm marking it as a bug, since we should at least prevent the generalization of the type of `m3` and get it to behave like `m4`.

**Comment by aseemr** [comment]
Yes, seems to be an issue with generalization, because this also fails:

```
let foo = ((match f with) <: unit)
```

**Comment by aseemr** [comment]
@mtzguido, i am missing the connection with `m2`? even if we forbid pattern matching on functions, `m2` should still work, because F* will try to prove `a <: int`, with `a == int` in gamma, so should work out?

**Comment by mtzguido** [comment]
Yes, `m2` works out and we probably want it to.

My thinking was that if the SMT is invoked to see if we can match on something, we can match on functions (and anything) when in a inconsistent environment. (Although I'm not sure that's bad)

However, if we want to strictly forbid matching on functions, we need to somehow make a cut that allows for `m2` but not the other examples, which might not be doable?

**Comment by aseemr** [comment]
A similar issue, should this verify?

```
val foo: Type0 -> Tot int
let foo a = match a with
  | int -> 0
  | bool -> 1
  | _ -> 2
```

It's extraction is also strange:

```
open Prims
let foo = Prims.parse_int "0"
```

**Comment by mtzguido** [comment]
I think I remember an example similar to that, and it's just that `int` is being taken as a variable pattern, without any relation to the `int` type.

**Comment by nikswamy** [comment]
Your `int` here is just a variable, so you're not really case analyzing `a`

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by aseemr** [comment]
Ack!

**Comment by kyoDralliam** [comment]
Should we really forbid matching on lambda-abstractions ? As long as we cannot do anything with the match it should be innocuous.


 A little off topic, there are also interesting languages which allows matching on functions to reveal the intensional structure of the term. Not sure that we want to go to that world though.

**Comment by cpitclaudel** [comment]
Right, the question is what `match` means. Does it mean syntactic sugar for a collection of (possibly) destructuring bindings, or is it syntactic sugar for eliminators of inductives?  In the first case, it seems fine to allow (necessarily pointless) matches.  In the second case, you might restrict it to exclude function types.

F*'s matches are semantic, so it seems fine to allow it. And in fact even systems that seem more firmly in the second camp, like OCaml and Coq, do:

```
# match (fun x -> x) with y -> y;;
- : 'a -> 'a = <fun>
```

```
Coq < Definition a: (nat -> nat) := match (fun x => x) with y => y end.
a is defined

Coq < Print a.
a = fun x : nat => x
     : nat -> nat
```

(Coq reduces it away, apparently)

**Comment by nikswamy** [comment]
Ok, the only issue left here, as far as I can tell, is an issue of related to default effects. cf. (#623, #705, etc.)

We should ensure that top-level, values whose effect is in PURE/GHOST, are forced to be in effect `Tot/GTot`. 

This is what happens for functions whose bodies happen to have `PURE/GHOST` effect. I see no reason to treat nullary functions any differently.

FYI, @fournet experienced a different manifestation of the same default effect issue (ik.fst)

**Comment by mtzguido** [comment]
There's a `failwith` in the normalizer for matches over a lambda, should we remove that? Otherwise:

This typechecks but explodes on trying to evaluate `y` (in the IDE)
```F#
let f x = x
let y = match f with
        | ff -> ff 0
```

This just explodes:
```F#
let y = match (fun x -> x) with | ff -> ff 0
(* Failure("Ill-typed term: cannot pattern match an abstraction") *)
```

**Comment by mtzguido** [comment]
I removed that `failwith`, btw.

**Comment by nikswamy** [comment]
Can we close this now? Especially also given the revised treatment of default effects at the top-level. @mtzguido @aseemr

**Comment by mtzguido** [comment]
`m2` seems to have regressed and doesn't verify now:
```fstar
// 114: type of pattern does not match scrutinee
// this used to succeed via SMT at some point
[@(expect_failure [114])]
let m2 (a:Type) (_ : a == int) (x : a) =
    match x with
    | 0 -> 0
    | _ -> 1

// but we can manually coerce
let coerce (#a:Type) (#b:Type{a==b}) (x:a) : b = x

let m2' (a:Type) (_ : a == int) (x : a) =
    match coerce x with
    | 0 -> 0
    | _ -> 1
```

I don't really mind that the original fails. I'm adding the current tests to regressions.

If you guys also think it's fine then let's close!

**Comment by aseemr** [comment]
Closing this issue per the latest discussion on it.
