### ISSUE TITLE
Sharing annotations among arguments

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#11]
It would be nice if one could write

```
let rec mult (n m : nat) : nat = ...
```

instead of

```
let rec mult (n : nat) (m : nat) : nat = ...
```

**Comment by catalin-hritcu** [comment]
Fixed by Kenji's new parser

**Comment by mtzguido** [comment]
Should this be supported in `val` declarations as well? It seems it's not

@kyoDralliam

**Comment by nikswamy** [comment]
I believe it is supported. You should be able to write

```
val f (x y :int) : int
```

**Comment by mtzguido** [comment]
Ah, my mistake. It is on types where it's not allowed. This fails:
```
val sum : (x y : int) -> int
```
I ran into it with `Type` arguments, where I could just the tick notation, but wondering whether this makes sense

**Comment by kyoDralliam** [comment]
It may be nice to extend the syntax to account for that (that would help with inductives in particular). Does anyone have a strong feeling on that particular point ?

**Comment by kyoDralliam** [comment]
I just had a look at the possibility of extending and an obstruction comes from the fact that `x:t` is a valid expression so that `(x:t)` is both a multi-binder binding only one variable and the expression `x:t` which has been parenthesized.

**Comment by nikswamy** [comment]
I'm surprised that it's a valid expression. I thought ascriptions were `e <: t`

**Comment by kyoDralliam** [comment]
it's not an ascription it is a refinement type with a bound variable (`x:t{phi}` but the formula `phi` is optional)
