### ISSUE TITLE
Desugaring phase not recognizing the PURE monad.

### ISSUE THREAD

**Issue by aseemr** [FStarLang/FStar#111]
Here is a small program that fails to type check:

module Test
kind Post (a:Type) = a -> Type
assume type Recv: a:Type -> (a -> Type) -> Type
assume val recv: unit -> PURE 'a (fun (p:Post 'a) -> Recv 'a p) (fun (p:Post 'a) -> Recv 'a p)

test.fst(4,25-4,94) : Error
Kinds "Effect" and "Type" are incompatible

**Comment by nikswamy** [comment]
fixed
