### ISSUE TITLE
Failure("machine integers should be desugared")

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1130]
```
val bug: FStar.UInt8.byte -> bool
let bug = function
    | 0uy -> true
    | _ -> false
```

**Comment by catalin-hritcu** [comment]
This seems indeed related to #1130, but that bug report is not very informative.

Can @msprotz or some other expert please explain to @A-Manning what's happening with pattern machining machine integers? Here is his question from Slack:

> I'd like to get pattern matching on machine integers working (#790, #1130), and I'm not sure what the "machine integers should be desugared" error message is about - what should they be desugared to? Encoding machine integers as unbounded integers to SMT _seems_ to work - should they be encoded as bitvectors instead? Could someone please explain the current status of machine integers - what needs to be done, what I should know about, etc? (edited)

**Comment by msprotz** [comment]
Machine integers are desugared to `FStar.{U,}Int{8,16,32,64}.of_int "<the-literal>"` meaning that you can't pattern-match on them (you can't pattern-match on a function application). The only solution here is to do a series of cascading if-then-else's.

Thanks,

Jonathan

**Comment by A-Manning** [comment]
Thanks for your answer. The issue is that pattern matching on machine integers is a desirable feature, and I'm interested in what can be done to the F* sources to make this possible.

**Comment by ad-l** [comment]
Bumping priority - this issue is currently blocking the merge of FStar.Bytes in TLS

**Comment by A-Manning** [comment]
If it won't compromise soundness, my fork using unboxed integers seems to be working ok, and I can make a PR - I just wanted to know whether there was some kind of deeper problem, since the 'fix' was very simple.

**Comment by ad-l** [comment]
We do not think that exposing unboxed machine integers to the SMT is sound

**Comment by nikswamy** [comment]
Should be fixed now in master. 

Required some non-trivial revision of the F* top-level interface. @cpitclaudel,  you may be curious to review this part, especially (FStar.Universal.fs and FStar.Interactive.IDE.fs).

**Comment by cpitclaudel** [comment]
Can you point me to the commit ? I can't find it :/

**Comment by ad-l** [comment]
Note that there is a workaround in mitls2c that needs to be rolled back and replaced with your fix

**Comment by A-Manning** [comment]
F* seems to accept pattern matching on machine integers now, but fails on extraction.

`Bug.fst`
```ocaml
module Bug

val bug: FStar.UInt8.byte -> bool
let bug = function
    | 0uy -> true
    | _ -> false
```

`$ fstar.exe Bug.fst`
```
Verified module: Bug (441 milliseconds)
All verification conditions discharged successfully
```
`$ fstar.exe Bug.fst --codegen OCaml`
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("machine integers should be desugared")
```

**Comment by cpitclaudel** [comment]
> Required some non-trivial revision of the F* top-level interface. @cpitclaudel, you may be curious to review this part, especially (FStar.Universal.fs and FStar.Interactive.IDE.fs).

I found the commit.  It's going be a significant headache to merge this into 912 :/ Let's sync better next time :)
