### ISSUE TITLE
Interfaces in F*

### ISSUE THREAD

**Issue by nickgian** [FStarLang/FStar#1144]
It would be nice if we had more fine-grained control over what is imported when we open a module (say M1).
For example an often used pattern is that we have two modules, M1_definitions and M1_properties.
M1_properties needs to open M1_definitions transparently to make the proofs, but a client (say M2) may only need to open M1_definitions and M1_properties in an opaque way because it only needs to use the names and lemmas defined in these files. This is currently not possible as transparency of a module is defined by its unique interface which is the same to all other modules.

For a concrete example: In Vale, we need some definitions from FStar.UInt such as logand, logor, etc. but we do not care about their complicated implementation, hence we would like to avoid opening the module transparently and getting a bunch of useless definitions (e.g. FStar.BitVector and FStar.Seq which are used to implement these functions) which slows down verification time. On the other hand, for FStar.BV (another bitvector library) we need to open FStar.UInt transparently because it is used for some proofs. However, FStar.BV should only export FStar.UInt opaquely as the underlying implementation of FStar.UInt should not concern the clients of FStar.BV.

One idea is to have a new command such as "open abstract M" which opens M according to an automatically inferred interface (whenever that is possible). This essentially allows you to move between whatever interface is currently defined (if any) or a fully opaque interface. It could work for what I described above, but it may be better to consider more general solutions.
Anyone interested in discussing this problem more?

**Comment by jkzinzindohoue** [comment]
There is already a way to do that, which is splitting the .fst into a .fsti and a .fst and, depending on the module you wish to typecheck, you can either pass only the .fsti (to make it opaque), or both the .fst and .fsti on the command line to make it transparent.

I.e: 
fstar.exe A.fsti A.fst B.fst -> B.fst can rely on the content of A.fst
fstar.exe A.fsti B.fst -> B.fst only see the content of A.fsti, A.fst is hidden

I am not quite sure how this works in the interactive mode.

**Comment by msprotz** [comment]
When editing `foo.fst`, you set your fstar-subp-prover-args to `foo.fsti --verify_module foo`

Perhaps this trick should be on the wiki

**Comment by nikswamy** [comment]
Yes, except that the trick Jonathan mentions is not actually necessary. 

Loading `foo.fst` in the interactive mode will automatically pick up `foo.fsti`.

Closing.
