### ISSUE TITLE
Editing the compiler's sources in F* mode

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1146]
What kind of flags should I pass to `fstar.exe` to edit the compiler's sources (anything in `src/`) in interactive mode? I'd like to see how usable `fstar-mode` is to hack on the compiler itself (Emacs' fsharp-mode isn't perfect)

**Comment by catalin-hritcu** [comment]
Looking at `src/Makefile` it seems to be this:
```
# This is the way in which we invoke F* for boostrapping
#   -- we use automatic dependence analysis based on files in ulib, u_boot_fsts and boot_fstis
#   -- eager_inference, MLish, lax: all tune type-inference for use with unverified ML programs
#   -- fs_typ_app parses list<foo> as valid syntax, for overlap with F# syntax
FSTARBOOT=$(FSTAR) $(OTHERFLAGS) --eager_inference --lax --MLish --no_location_info \
		   --odir u_ocaml-output --codegen OCaml --include ../ulib --include u_boot_fsts --include boot_fstis
```

**Comment by cpitclaudel** [comment]
Neat! Thanks.

**Comment by cpitclaudel** [comment]
Reopening, since there's a bit more that's needed for this to work well.

- [x] Change the file extension check to allow `fs` and `fsi`
- [x] Teach fstar-mode how to pass the right `--include`s to F* (`fstar-subp-prover-args-for-compiler-hacking`)
- [ ] Change the build process:
  - [ ] Leave the .fs files in place instead of copying them
  - [ ] Teach F* to use them
  - [ ] Update the Makefile and fstar-mode to include these .fs folders instead of `u_boot_fsts` and `boot_fstis`
- [ ] Make sure things work

**Comment by cpitclaudel** [comment]
I've made progress on this: updating fstar-mode and F* should be enough to be able to edit most of F*'s sources in fstar-mode.  I haven't touched the Makefile (any takers?)

**Comment by cpitclaudel** [comment]
Done with @kyoDralliam :champagne:
