### ISSUE TITLE
`( [] )` is accepted as an operator in `let`s, but not `val`s

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1147]
`let ([]) : int -> int -> int = (+)` is accepted, but 
`val ( [] ): int -> int -> int` gives a syntax error.

it seems that this definition does not work as an operator though, since 
`let a = ([]) 3 4` gives the error
```Too many arguments to function of type Prims.Tot (Prims.list a)```

`::` also gets resolved to list concatenation, regardless of the definition in scope.

**Comment by cpitclaudel** [comment]
This should be rejected; I think it's subsumed by https://github.com/FStarLang/FStar/issues/1228 ; please reopen if I'm misunderstanding though (can you reopen issues? If not, ping me)
