### ISSUE TITLE
CheckNoUvars from interactive mode's lax check following an error

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1149]
I don't have a solid reproducible example of this, but I'm seeing;

```
[F* error] Failure("(<input>(301,42-301,55)) CheckNoUvars: Unexpected unification variable remains: uu___unification_ 85")
F*: subprocess exited.
```

with F* dying in interactive mode. Here's what I think is an example: https://github.com/FStarLang/FStar/blob/tchajed_fstar_crash/examples/struct/keyvalue.pos/crash.transcript.txt. The file Serializer.fst triggers this bug fairly reliably while hanging out just before `ser_u16_array`; suddenly a lax check query from `fstar-mode.el` will crash F*.

**Comment by tchajed** [comment]
Can now reproduce reliably based on a transcript of the above. In the directory https://github.com/FStarLang/FStar/tree/tchajed_fstar_crash/examples/struct/keyvalue.pos, run `cat transcript.in | fstar.exe --ide Serializer.fst`. The error comes from running a lax check with `#peek` (`#push` + `#pop`), getting an error, and then re-running that query. Some universe variable must be leftover by the `#pop`.

**Comment by nikswamy** [comment]
It has to do with the new, functional unionfind and how we blow away the graph from time to time. 

I workaround this by disabling flycheck-mode in emacs.

A definitive repro independent of emacs would be awesome

**Comment by cpitclaudel** [comment]
Related to https://github.com/FStarLang/FStar/issues/949, apparently?
