### ISSUE TITLE
Strange timing effects in StlcCbvDbPntSubstLists

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#115]
I was looking at Aseem's proof in `stlcdb.fst`, trying to understand where the verification time bottleneck is (it currently causes the build to fail on my machine, because it needs a higher Z3 timeout). The bottleneck seems to be in `subst_lem`, but when trying to narrow this down even further I've noticed a strange effect: admitting the `EAbs` case _increases_ the verification time from 28s to 73s. I find this hard to explain.

**Comment by catalin-hritcu** [comment]
I'm also getting strange timing effects in `lambda_omega.fst` now.

**Comment by catalin-hritcu** [comment]
It's hard to draw conclusions from one-off experiments without proper profiling (#220).

**Comment by vkanne-msft** [comment]
@catalin-hritcu can you help look into this again ?

**Comment by catalin-hritcu** [comment]
Tried to bring `StlcCbvDbPntSubstLists` to universes, but so far without so much success:
```
/home/hritcu/Projects/fstar/pub/bin/fstar.exe  StlcCbvDbPntSubstLists.fst --z3timeout 20
./StlcCbvDbPntSubstLists.fst(154,153-162,62): could not prove post-condition
./StlcCbvDbPntSubstLists.fst(154,153-162,62): could not prove post-condition
./StlcCbvDbPntSubstLists.fst(154,153-162,62): could not prove post-condition
./StlcCbvDbPntSubstLists.fst(178,21-178,22): Subtyping check failed; expected type (k#19093:Prims.nat{(Prims.b2t (Prims.is_Some (StlcCbvDbPntSubstLists.lookup (FStar.List.Tot.append g' g) k@0)))}); got type Prims.nat
./StlcCbvDbPntSubstLists.fst(223,56-223,57): Subtyping check failed; expected type (k#19093:Prims.nat{(Prims.b2t (Prims.is_Some (StlcCbvDbPntSubstLists.lookup (FStar.List.Tot.append g' g) k@0)))}); got type Prims.nat
Error: 5 errors were reported (see above)
make: *** [Makefile:27: StlcCbvDbPntSubstLists] Error 1
```
@aseemr-msr Any idea what's happening here?

More generally, this file is indeed quite flaky and takes indeed really long to verify. Is is worth doing something about that?

**Comment by nikswamy** [comment]
I was unable to verify this file today. Even with a high rlimit and smt.qi.eager_threshold

**Comment by nikswamy** [comment]
Marking this issue obsolete and closing. The example has no obvious owner and it isn't clear to me when, if ever, this code was verifying. Meanwhile, we have other clean and stable examples of STLC, even documented in the tutorial
