### ISSUE TITLE
Compilation for tacticals

### ISSUE THREAD

**Issue by victor-dumitrescu** [FStarLang/FStar#1154]
The current implementation of native tactics works by extracting tactics to OCaml and compiling them using ocamlopt into a `.cmxs`. This can then be dynamically loaded and the compiled tactic can be run instead of running it on the F* normalizer.

As part of tactics extraction, apart from the tactic itself, a call to `FStar_Tactics_Native.register_tactic` is also generated, which is used to register the native tactic as a primitive step in the tactics interpreter. This function requires embedding and unembedding functions on the arguments and result of the tactic. For example, for a unary tactic of type `'a -> tac<'b>`, we need to provide an embedding for `'b -> term` and and unembedding `term -> 'a`, where `tac` is a type representing tactics inside the compiler.

Many of these embedding functions are implemented in `FStar.Syntax.Embeddings`, but for the type `tactic` (the type in which user tactics are written) it's a bit trickier. In the tactics interpreter, an `unembed_tactic_0` function is implemented, which produces terms of type `tac`. With some massaging, it can be used as an unembedding for type `tactic`, but there is a mismatch between the terms it produces for this type and what the tactics interpreter expects.

As a very small example, let's say we have a user tactic defined in a module `H`:
`let app (t: tactic unit): tactic unit = seq idtac t`

which is used to solve a trivial goal in a separate module:
`let a = assert_by_tactic (H.app trivial) True`

We can extract module `H`, but the call to `register_tactic` won't be automatically generated. I've written one manually, which does typecheck:
<pre>
open Prims
let app:
  Prims.unit FStar_Tactics_Effect.tactic ->
    Prims.unit FStar_Tactics_Effect.tactic
  = fun t  -> FStar_Tactics_Builtins.seq FStar_Tactics_Derived.idtac t
let _ =
  FStar_Tactics_Native.register_tactic "H.__app" 2
    (fun ps  ->
       fun args  ->
         FStar_Tactics_Interpreter.mk_tactic_interpretation_1 ps
           (FStar_Tactics_Native.from_tactic_1 app)
           <b>(fun x -> fun () -> (FStar_Tactics_Builtins.from_tac_0 (FStar_Tactics_Interpreter.unembed_tactic_0
            FStar_Syntax_Embeddings.unembed_unit x)))</b>
           FStar_Syntax_Embeddings.embed_unit FStar_Syntax_Syntax.t_unit
           (FStar_Ident.lid_of_str "H.__app") args)
</pre>

However, when trying to verify the module from before using the native tactic compiled from this OCaml code, we hit an error:
`Failure("Not an embedded result: FStar.Tactics.Effect.TAC?.reflect FStar.Tactics.Builtins.__trivial")`

The exact invocation I use for compiling is `ocamlfind ocamlopt -shared -I ../FStar/src/ocaml-output/_build/src/tactics/ml -I ../FStar/src/ocaml-output/_build/ulib/ml -I ../FStar/src/ocaml-output/_build/src/ocaml-output/ -linkpkg -package zarith -o H.cmxs H.ml`, where `H.ml` is the extracted tactic.

**Comment by mtzguido** [comment]
I believe this is simply missing a `reify` in between. Does this make sense ?

```
guido@wolf:~/r/fstar/examples/bug-reports(guido_tactics)$ git diff
diff --git a/examples/bug-reports/Bug1154_tactic.ml b/examples/bug-reports/Bug1154_tactic.ml
index e425b698d..b5297e50e 100644
--- a/examples/bug-reports/Bug1154_tactic.ml
+++ b/examples/bug-reports/Bug1154_tactic.ml
@@ -10,6 +10,6 @@ let _ =
          FStar_Tactics_Interpreter.mk_tactic_interpretation_1 ps
            (FStar_Tactics_Native.from_tactic_1 app)
            (fun x -> fun () -> (FStar_Tactics_Builtins.from_tac_0 (FStar_Tactics_Interpreter.unembed_tactic_0
-            FStar_Syntax_Embeddings.unembed_unit x)))
+            FStar_Syntax_Embeddings.unembed_unit (FStar_Tactics_Interpreter.reify_tactic x))))
            FStar_Syntax_Embeddings.embed_unit FStar_Syntax_Syntax.t_unit
            (FStar_Ident.lid_of_str "Bug1154_tactic.__app") args)
\ No newline at end of file


guido@wolf:~/r/fstar/examples/bug-reports(guido_tactics)$ make bug1154 
/home/guido/r/fstar/bin/fstar.exe  --use_hints Bug1154.fst
Verified module: Bug1154 (4 milliseconds)
All verification conditions discharged successfully
Warning: Unable to open hints file: /home/guido/r/fstar/examples/bug-reports/Bug1154.fst.hints; ran without hints
ocamlfind ocamlopt -shared -I ../../src/ocaml-output/_build/src/tactics/ml -I ../../src/ocaml-output/_build/ulib/ml -I ../../src/ocaml-output/_build/src/ocaml-output/ -linkpkg -package zarith -o Bug1154_tactic.cmxs Bug1154_tactic.ml
/home/guido/r/fstar/bin/fstar.exe  --use_hints --load Bug1154_tactic.cmxs Bug1154.fst
Registered tactic Bug1154_tactic.__app
Dynlinked Bug1154_tactic.cmxs
Registered primitive step Bug1154_tactic.__app
In compiled code
Registered primitive step Bug1154_tactic.__app
Verified module: Bug1154 (4 milliseconds)
All verification conditions discharged successfully
Warning: Unable to open hints file: /home/guido/r/fstar/examples/bug-reports/Bug1154.fst.hints; ran without hints
```

**Comment by victor-dumitrescu** [comment]
I think you're right, this makes sense and it seems to do the trick. Thanks!
