### ISSUE TITLE
Failure("wrong composed operator format") caused by `/\` parsed as `op_Slash_UNKNOWN`

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1155]
Defining an operator like `/$` , which is parsed as `op_Slash_UNKNOWN`, can cause failure in code that seemingly does not use the operator, since `/\` is also parsed as  `op_Slash_UNKNOWN`.
```
val (  /~ ) : unit -> bool -> unit
let ( /$ )  _ _ = ()

val fail: u:unit{(u = ()) /\ true} -> unit
let fail _ = ()
```
```Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("wrong composed operator format")
```

**Comment by mtzguido** [comment]
Thanks for reporting this. Surprised that both `\` and `~` were resolving to UNKNOWN. I just fixed this by preventing UNKNOWN operators and adding a name for these two characters. Closing this and the other issue, but let me know if you find any rough edge.

**Comment by A-Manning** [comment]
`$` is also missing - although it does appear in the [wiki](https://github.com/FStarLang/FStar/wiki/Parsing-and-operator-precedence), and occasionally in code.

**Comment by mtzguido** [comment]
Ah, thanks! Adding it...
