### ISSUE TITLE
'Unrecognized mutual type definition' should be an error, not a crash

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1164]
The following crashes F* (`Failure("Unrecognized mutual type definition")`)
```
type a
and r = { x : int }
```

This should just be a regular error.  I ended up writing one of these by mistake in an interface (hiding the type definition for `a` and not changing the `and` into a `type`

**Comment by theolaurent** [comment]
Hit the same crash when checking partial development. Why should it be an error ?
```
type a
type r = { x : a }
```
is accepted
```
type a = unit
and r = { x : a }
```
too.
I don't see how this case differ.

**Comment by cpitclaudel** [comment]
F* doesn't have support for mutually recursive records.  Try this instead:

```
type a = unit
and r = | MakeR : x : a -> r
```

**Comment by theolaurent** [comment]
Sorry that wasn't clear @cpitclaudel. It's not about the record.
I don't get why
```
type foo =
  | Foo : foo
and bar
```
Should be an error instead of juste the same as
```
type bar
type foo =
  | Foo : foo
```

**Comment by theolaurent** [comment]
Ahhh. Got it. Don't mix axioms and definitions. Thanks!

**Comment by aseemr** [comment]
All the ill-defined examples above are now errors and not crashes. Closing.
