### ISSUE TITLE
Feature request: subtyping for type indices

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1167]
It would be nice if F* would infer that a type index is covariant and check subtyping later on based on that fact. Note that this doesn't work for every type index (some types will require contravariance or invariance), but there should be some algorithm to at least figure out when subtyping is covariant.

```fstar
module Covariance

(* note that identity is covariant in t *)
type identity (t:Type) =
  | Identity : v:t -> identity t

let bind (#t:Type) (#t':Type)
  (x: identity t) (f: t -> identity t') : identity t' =
  f (Identity?.v x)

let foo : identity nat = Identity () `bind` (fun _ -> Identity 1)
(* Subtyping check failed; expected type Covariance.identity Prims.nat; got type Covariance.identity Prims.int *)
```

Currently you can get around this with an explicit type annotation, for example:

```fstar
let foo' : identity nat = Identity () `bind` (fun _ -> Identity #nat 1)
```

**Comment by cpitclaudel** [comment]
Related to (duplicate of?) https://github.com/FStarLang/FStar/issues/1039 and https://github.com/FStarLang/FStar/issues/65 ?

**Comment by tchajed** [comment]
I figured this would be a much-discussed issue already, and it is indeed #65. While `forget` also comes up in my use cases, it's more common that I want to return a refined type, which is currently more awkward to express.

**Comment by A-Manning** [comment]
@tchajed you can write the functions `refine_in` and `refine_out`, like so
```
val refine_in(#a: Type):
    p:(a -> Type)
    -> id:identity a{p (Identity?.v id)}
    -> identity (v:a{p v})
let refine_in #_ _ (Identity v) = Identity v

val refine_out(#a: Type):
    p:(a -> Type)
    -> identity (v:a{p v})
    -> id:identity a{p (Identity?.v id)}
let refine_out #_ _ (Identity v) = Identity v

let ( |> ) x f = f x

let foo : identity nat = 
    Identity () `bind` (fun _ -> Identity 1)
    |> refine_in (fun x -> x >= 0)
```
