### ISSUE TITLE
Impossible: missing universe instantiation on l_Forall

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1169]
```
type boom =
| B : forall (x: int). boom
```

```
Failure("Impossible: missing universe instantiation on l_Forall")
```

**Comment by cpitclaudel** [comment]
Anything wrong with the tag? I think we have a range of this type of bugs (a `failwith "impossible"` in a case that's not impossible), so I thought it'd be useful to tag them consistently. Or do you think this is a more serious bug than the usual case in which an "impossible" case should be changed to produce a better, non-fatal error?

**Comment by kyoDralliam** [comment]
As it is written it does not mean anything in F*, does it ? I am surprised that we are not checking that each branch of the inductive definition are not of the form ` ?u -> boom` (or maybe that's where we have such an error)

**Comment by cpitclaudel** [comment]
Right, it doesn't mean anything.  I typed it out of habit from Coq, and F* exploded.

**Comment by cpitclaudel** [comment]
Ran into this again today.  Is it a tricky fix?

**Comment by aseemr** [comment]
This seemed like a bug in normalizing the data constructor type. We call it before typechecking the type, and then normalizer fails with inconsistent universe on `forall`. I made it so that we don't check for universes in that normalization request. Closing.
