### ISSUE TITLE
Failure("Something paranormal occurred")

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1172]
```
module Paranormal

open FStar.Tactics
assume val f : term -> int

let _: int =
  synth_by_tactic
    (tm <-- quote (fun x -> x + 1);
     exact (f tm))
```

```
[F* error] Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
[F* error] Failure("Something paranormal occurred")
[F* error] <input>(10,11-10,17): (Error) Expected type "FStar.Tactics.Effect.tactic FStar.Reflection.Types.term"; but "Paranormal.f tm" has type "Prims.int"
[F* error] 1 error was reported (see above)
F*: subprocess exited.
```

**Comment by mtzguido** [comment]
Thanks for finding this. Both these and previous issue are ill-typed tactics running. They are subtyping errors (`int </: tactic unit` and `tactic term </: term`). The errors are being recorded and displayed, but the F* typechecker will just go ahead with the rest of file in the presence of one of these. (c.f. [here](https://github.com/FStarLang/FStar/blob/master/src/typechecker/FStar.TypeChecker.Util.fs#L867)).

We can't detect this from the outside now, but a fix could be that in the typechecking of terms in tactic position we forbid this. Trying it in a minute...

As for the message, it's about a failed cast from a `Meta_alien` node embedded in a term. Arguably, the message should be something more serious :)

**Comment by mtzguido** [comment]
Fixed in my branch, and hopefully for good. We now fail hard when type-checking a tactic (for this particular error at least --- need to check for all of them). We also now typecheck the tactics again *just before* running them, so we should be on the safe side too.

**Comment by cpitclaudel** [comment]
Nice!

> We also now typecheck the tactics again just before running them, so we should be on the safe side too.

Can you give an intuition of why we need this part?
