### ISSUE TITLE
How can F* prove deBruijn substitution terminating without any annotation?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#118]
How can F* prove deBruijn substitution terminating without any annotation?
```
val substitute: e:exp -> j:nat -> e':exp -> Tot exp
let rec substitute e j e' = match e with
  | EVar k       -> if j = k then e' else EVar k
  | EAbs t e1    -> EAbs t (substitute e1 (j + 1) (shift e' 0 1))
  | EApp e1 e2   -> EApp (substitute e1 j e') (substitute e2 j e')
```
I would expect this to be shown terminating using the size of `e` as the decreasing clause and the fact that `shift e' 0 1` preserves sizes. But without this ... what is going on here?

**Comment by ckeller** [comment]
It is a simple induction on e, there is no need to prove that shift preserves anything.

**Comment by catalin-hritcu** [comment]
Sorry for the noise, I was horribly confused. The problem I was talking about only appears in Autosubst.
