### ISSUE TITLE
Can't compile FStar with OCaml 4.05.0

### ISSUE THREAD

**Issue by franziskuskiefer** [FStarLang/FStar#1180]
Batteries doesn't compile with the current OCaml release 4.05.0, which breaks compilation of FStar. See https://github.com/ocaml-batteries-team/batteries-included/issues/764 for the batteries issue.

**Comment by beurdouche** [comment]
That is an unfortunate fact that we have to rely on batteries.
Like all projects relying on it, we are stuck with OCaml 4.04.3 until there is support from it.
The patch is trivial on our side.

**Comment by beurdouche** [comment]
@nikswamy @protz @kyoDralliam Is there a way we could get rid of batteries altogether in F* ?

**Comment by msprotz** [comment]
There is a substantial amount of code in F* that relies on batteries, I think it's just too much work to switch right now. The rationale is that with OPAM these days, it's relatively easy to juggle between OCaml versions.

**Comment by beurdouche** [comment]
https://github.com/FStarLang/FStar/pull/1201
