### ISSUE TITLE
--using_facts_from is not properly reset

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1181]
While tracking a recent regression in hacl-star, I found that a `--using_facts_from` option that was set in a dependency wasn't properly reset and caused some subsequent queries to fail:

```
module M
type t = | T: n:int -> t
#reset-options "--using_facts_from Prims" // Works if this line is commented out
#reset-options "--z3refresh"
let x : v:t{T?.n v == 0} = T 0
```

**Comment by tchajed** [comment]
I did some digging; didn't solve the problem, but hopefully this helps the next person.

First of all, the option is definitely correctly set back to its default value (you can easily check with `M-x fstar-list-options`).

There are only two references to the option: https://github.com/FStarLang/FStar/blob/master/src/typechecker/FStar.TypeChecker.Env.fs#L183-L185 and https://github.com/FStarLang/FStar/blob/master/src/typechecker/FStar.TypeChecker.Tc.fs#L1464. The former looks more suspicious than the latter.

**Comment by tchajed** [comment]
Actually that call looks fine (and it's only referenced in one place).

It's also curious that this bug manifests even if you backtrack over the `#reset-options "--using_facts_from Prims"` and then comment it out, so whatever state is getting messed up is backtracked.

**Comment by s-zanella** [comment]
Thanks @mtzguido for the fix!
I found a workaround in the meantime: use `#set-options` instead of `#reset-options` to set `--using_facts_from`.

**Comment by mtzguido** [comment]
Sorry, this was my bad. The weird handling you see there is because while `using_facts_from` is not just an option, but a part of the environment which needs to be updated. When using `#reset-options`, we need to take its new value explicitly and inject it into the environment. I had simply forgotten to check that if the option is is not present, we should reset the current set of facts from the current environment.

**Comment by mtzguido** [comment]
> I found a workaround in the meantime: use #set-options instead of #reset-options to set --using_facts_from.

I believe `#set-options` wasn't taking `using_facts_from` into account as it should have :(... just fixed that too. Pushing to master when CI allows.

**Comment by mtzguido** [comment]
Fix now in master.

@tchajed: I tried to trigger an error in the interactive mode by backtracking over the `#reset-options`, but couldn't find anything wrong (after the fix, of course). Could you check if something is wrong and reopen if so?

**Comment by tchajed** [comment]
I don't think there's anything wrong, it just surprised me in my debugging that backtracking over the `#reset-options` worked; given the fix this isn't surprising, since the old `Env.env` is part of the state that's restored. The bug was actually with how the state is manipulated (specifically, how an unset `using_facts_from` list is handled), not in backtracking.

**Comment by tchajed** [comment]
Incidentally this bug would have been prevented if we didn't use `Unset` to represent `List []` for the `using_facts_from` option - maybe we should do that?

**Comment by mtzguido** [comment]
Ah, I misread, I thought you meant backtracking wasn't working properly. Thanks!

**Comment by mtzguido** [comment]
No strong preference for me, but note that it requires a small change in `Tc.fs`, since when the option is present we append a `([], false)` which represents "and nothing else".

**Comment by cpitclaudel** [comment]
@mtzguido @tchajed This would be a nice change; AFAICT, this is the only option that behaves this way (have a special `Unset` state that means something different from `[]`)

Something like this?

```diff
diff --git a/src/basic/FStar.Options.fs b/src/basic/FStar.Options.fs
index dc260aa..8e0f4f0 100644
--- a/src/basic/FStar.Options.fs
+++ b/src/basic/FStar.Options.fs
@@ -186,7 +186,7 @@ let defaults =
       ("use_native_tactics"           , Unset);
       ("use_eq_at_higher_order"       , Bool false);
       ("use_hints"                    , Bool false);
-      ("using_facts_from"             , Unset);
+      ("using_facts_from"             , List []);
       ("verify"                       , Bool true);
       ("verify_all"                   , Bool false);
       ("verify_module"                , List []);
@@ -290,7 +290,7 @@ let get_use_eq_at_higher_order  ()      = lookup_opt "use_eq_at_higher_order"
 let get_use_hints               ()      = lookup_opt "use_hints"                as_bool
 let get_use_native_tactics      ()      = lookup_opt "use_native_tactics"       (as_option as_string)
 let get_use_tactics             ()      = not (lookup_opt "no_tactics"          as_bool)
-let get_using_facts_from        ()      = lookup_opt "using_facts_from"         (as_option (as_list as_string))
+let get_using_facts_from        ()      = lookup_opt "using_facts_from"         (as_list as_string)
 let get_verify_all              ()      = lookup_opt "verify_all"               as_bool
 let get_verify_module           ()      = lookup_opt "verify_module"            (as_list as_string)
 let get___temp_no_proj          ()      = lookup_opt "__temp_no_proj"           (as_list as_string)
diff --git a/src/typechecker/FStar.TypeChecker.Env.fs b/src/typechecker/FStar.TypeChecker.Env.fs
index 4ec701f..15b674f 100644
--- a/src/typechecker/FStar.TypeChecker.Env.fs
+++ b/src/typechecker/FStar.TypeChecker.Env.fs
@@ -190,8 +190,8 @@ let initial_env type_of universe_of solver module_lid =
     use_bv_sorts=false;
     qname_and_index=None;
     proof_ns = (match Options.using_facts_from () with
-               | Some ns -> [(List.map (fun s -> (Ident.path_of_text s, true)) ns)@[([], false)]]
-               | None -> [[]]);
+               | [] -> [[]]
+               | ns -> [(List.map (fun s -> (Ident.path_of_text s, true)) ns)@[([], false)]]);
     synth = (fun e g tau -> failwith "no synthesizer available");
     is_native_tactic = (fun _ -> false);
     identifier_info=BU.mk_ref FStar.TypeChecker.Common.id_info_table_empty;
diff --git a/src/typechecker/FStar.TypeChecker.Tc.fs b/src/typechecker/FStar.TypeChecker.Tc.fs
index 885ee4d..c9d6a07 100644
--- a/src/typechecker/FStar.TypeChecker.Tc.fs
+++ b/src/typechecker/FStar.TypeChecker.Tc.fs
@@ -1492,11 +1492,11 @@ let add_sigelt_to_env (env:Env.env) (se:sigelt) :Env.env =
      | ResetOptions _ ->
         // `using_facts_from` requires some special handling..
         begin match Options.using_facts_from () with
-        | Some ns ->
+        | [] ->
+            { env with proof_ns = [[]] }
+        | ns ->
             let proof_ns = [(List.map (fun s -> (Ident.path_of_text s, true)) ns)@[([], false)]] in
             { env with proof_ns = proof_ns }
-        | None ->
-            { env with proof_ns = [[]] }
         end
      | _ -> env)
   | Sig_new_effect_for_free _ -> env
```
