### ISSUE TITLE
Dependent records

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1184]
The current record desugaring code mangles field names to prevent inter-field dependencies.  The code says:

```
(* it is necessary to mangle field names to avoid capture as they are turned into the formal parameters of the data constructor *)
```

Why do we want to avoid capture? 

Note that the capture-avoidance was recently broken by a change of mangling convention (instead of `^fname^` we use `__fname__`), making it possible to do this:

```
noeq type monad_typeclass =
  { m: Type -> Type;
    return: #a: Type -> aa: a -> __fname__m a;
    bind: #a: Type -> #b: Type -> __fname__m a -> (a -> __fname__m b) -> __fname__m b;
    bind_return_l: forall #a #b (aa: a) (f: a -> __fname__m b).
                   __fname__bind (__fname__return aa) f == f aa }
```

It's not clear what's wrong with it, though.  There could be a backwards compatibility issue, but it should be easy to check for that.

**Comment by A-Manning** [comment]
Possibly related to #321 ?

**Comment by cpitclaudel** [comment]
We had a brief chat with @nikswamy about this at ICFP. Can we actually remove the mangling and allow dependent records?

**Comment by catalin-hritcu** [comment]
Yes, we decided today to try to allow dependent records.

This is a long standing issue: https://github.com/FStarLang/FStar/issues/801

**Comment by catalin-hritcu** [comment]
As an aside, we haven't yet converged on whether to allow `with` or even record construction syntax for 1-constructor inductives. Someone (Nik?) pointed out that records typed cannot be indexed by their arguments, but 1-constructor inductives can, which could potentially cause complications.

**Comment by mtzguido** [comment]
This is trickier than it seems. Removing the mangling and enabling dependency is easy (see `guido_mangling`), but we need to be very careful to avoid captures. The reason for that is that we desugar records into one-constructor inductives. Each of the arguments of the inductive is annotated with the (mangled or not) field name, and they are in-scope for the codomain (the record type), which can mess things up if any names are repeated.

Look at this for instance, failing in `master`:
```
$ cat A.fst 
module A
type x (a:Type) = { a : int }

$ ./bin/fstar.exe A.fst 
A.fst(3,0-3,29): (Error 276) Unexpected output from Z3: (error "line 93119 column 33: invalid declaration, function 'A.Mkx_a' (with the given signature) already declared")
(error "line 93245 column 7: named expression already defined")
(error "line 93463 column 33: invalid declaration, function 'A.Mkx_a' (with the given signature) already declared")
(error "line 93589 column 7: named expression already defined")

Verified module: A (328 milliseconds)
1 error was reported (see above)
```
Or:
```
$ cat B.fst
module B
type __fname__x = { x : int }

$ ./bin/fstar.exe B.fst 
B.fst(3,0-3,29): (Error 234) The type of __fname__x is Prims.int, but since this is the result type of a constructor its type should be Type
1 error was reported (see above)
```
The second one can be avoided by a non-user-denotable mangling (as it was before I messed it up :) ), but the first one will stand. We can actually just trigger the first one like this:
```
type t a = | Mk : a:int -> t a
```
```B.fst(5,0-5,30): (Error 276) Unexpected output from Z3: (error "line 93119 column 32: invalid declaration, function 'B.Mk_a' (with the given signature) already declared")
(error "line 93245 column 7: named expression already defined")
(error "line 93463 column 32: invalid declaration, function 'B.Mk_a' (with the given signature) already declared")
(error "line 93589 column 7: named expression already defined")

B.fst(5,13-5,15): (Error 114) Type of pattern (B.t _) does not match type of scrutinee (B.t a); parameter _ <> parameter a
2 errors were reported (see above)
```
Although even changing the name fails?
```
type t b = | Mk : a:int -> t a
```
```
B.fst(5,13-5,15): (Error 114) Type of pattern (B.t _) does not match type of scrutinee (B.t b); parameter _ <> parameter b
1 error was reported (see above)
```
(Also, red flag: these last two should be equivalent by alpha-renaming, but they are not.)

Removing the mangling will possibly give more failures. And will, unless we maybe fully-qualify the type in the codomain, prevent having a field with the same name as the type (exactly as in the second example here).

**Comment by mtzguido** [comment]
I missed the fact that those errors were actually from bad parameters, now fixed by #1534. My current feeling is that avoiding capture is not possible (or very annoying to do) if we translate record types to *syntax* for one-constructor inductives, and instead we should write custom desugaring for them.

Consider these guys:
```
noeq type job (a:Type) = {
    job:unit -> a;
    callback: a -> unit
}

noeq type myrec (x:Type) = {
  t : Type;
  x : t;
}
```
The first one desugars to:
```
noeq type job (a:Type) =
    | Mkjob : job:(unit -> a) -> callback:(a -> unit) -> job a
```
which fails since the `job` on the RHS is not the type, but the argument to `Mkjob`. This could be fixed by allowing self-annotations and writing `CurrentModule.job`. But consider the second one:
```
noeq type noeq type myrec (x:Type) =
  | Mkmyrec : t:Type -> x:t -> myrec x
```
This *syntax* simply has no way of working without changing either name, which is unsatisfactory since they are visible to users when, e.g., printing the type of `myrec` and `Mkmyrec` in the interactive mode. (Not to mention the name of the `.x` projector.)

So, I'll try to actually desugar records into internal syntax, where we should be able to disambiguate easily.

**Comment by mtzguido** [comment]
I banged my head against the desugarer for a while to do that but couldn't get it to work. Instead I implemented a stopgap of checking if the capture will occur and raise an error if so. Suboptimal, but we could probably live with it for now.

My status is in `guido_deprecords`. I would be in favor of merging it, if we agree.

Another issue (also present for inductives) is that, when dependency is involved, typechecking the projectors involves an SMT query.
```
module ASD

#set-options "--print_effect_args --no_smt"

// From:
// noeq type dep1 : Type = {
//   x : int;
//   y : unit -> squash (x == 2);
// }

noeq type dep1 : Type =
    | Mkdep1 : x:int -> y:(unit -> squash (x == 2)) -> dep1
```
```
ASD.fst(12,24-12,25): (Error 298) Q = forall (b: Prims.int) (b: (_: Prims.unit -> Prims.Tot (Prims.squash (b == 2)))).
  projectee == ASD.Mkdep1 b b ==>
  (forall (_: Prims.unit) (x: Prims.unit). b == 2 ==> Mkdep1?.x projectee == 2)
A query could not be solved internally, and --no_smt was given
Verified module: ASD (15 milliseconds)
1 error was reported (see above)
```
In this case the query would suceed, but it may not in more complicated cases. At least, it happens in `examples/typeclasses/Monad.fst`, in the commented-out variant of the definition.

**Comment by mtzguido** [comment]
We decided that restriction is well worth it, so I merged my changes and we now have dependent records.
