### ISSUE TITLE
Dependent pairs are printed incorrectly

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1188]
```fsharp
module Test

let a = (| 1, 2 |)
(* …prints as [let Test.a = (| Prims.int, (fun uu___123659 -> Prims.int), 1, 2 |)] *)

let aa = (| Prims.int, (fun uu___123659 -> Prims.int), 1, 2 |)
(* …prints as [let Test.aa  = FStar.Pervasives.Mkdtuple4 Prims.int (fun uu___123659 -> Prims.int) 1 2] *)
```

**Comment by mtzguido** [comment]
Still present (with `--print_implicits`), and also for simple pairs and tuples. Seems to be same issue as for most operations with implicits, e.g. `x == y`, which we guard against in resugaring by checking for `Options.print_implicits ()` and falling back to an "uglier" printing if so (`eq2 #t x y`). I can take a look at some point.
