### ISSUE TITLE
Every branch of an SMTPatOr should be checked for mentioning all bound variables

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1196]
In the following example, the first branch in the `prove_p` pattern doesn't actually work in z3:

```fstar
module Incomplete_pattern

assume val p : nat -> Type0

assume val prove_p : n:nat -> Lemma (p n)
  [SMTPatOr [
    [SMTPat (p 1)];
    [SMTPat (p n)] ]]

let use_prove_p (n:nat) : Lemma (p n) = ()
```

The incomplete pattern is allowed by F* and then z3 reports a warning `WARNING: (40398,38): pattern does not contain any variable.`. Note that that pattern is useless; it won't even help solve `p 1`.

I think F* should instead give its warning "Pattern misses at least one bound variable" by expanding that check to cover all the branches when the pattern is an `smt_pat_or`.

**Comment by aseemr** [comment]
This is fixed in master. Closing.
