### ISSUE TITLE
Type checking fails for Int32 operators

### ISSUE THREAD

**Issue by jroesch** [FStarLang/FStar#1200]
```
module NoTcInt32

open FStar.Int32

let add_mod' = FStar.Int.add_mod #32

let add_mod (i j : Int32.t) : Int32.t =
  (add_mod' (i <: FStar.Int.int_t 32) (j <: FStar.Int.int_t 32)) <: Int32.t

let add_mod (i j : Int32.t) : Int32.t =
(FStar.Int.add_mod i j) <: Int32.t
```

I was encountering this error yesterday on the `c_mitls2c` branch, and I was able to reproduce it on `master`. 

Both of the bottom definitions fail, the one using the explicitly applied implicit argument `#32` provides a better error message, it looks to that the type checker won't solve `FStar.Int.int_t 32 <: FStar.Int32.t`.

Upon further examination it seems that the code *shoud not* type check. If one looks in `FStar.Int32.fst` they would find the exposed integer type to be defined as:

```
private type t' = | Mk: v:int_t n -> t'
type t = t'
```

Many operations including `add`, `sub`, `mul`, and `div` are lifted on to this new type, but not operations such as `add_mod` (the one I was having trouble with). This means that they are being resolved to operations defined in `FStar.Int.fst`. 

It may be the case that I'm forgetting about a coercion that is intended to make this work, but either way this seems like a confusing UX and `FStar.In32` should define these operations for clarity's sake.

In order to rectify this, I propose we modify `mk_int.sh` to output  wrappers for operations defined in the integer modules.

**Comment by tchajed** [comment]
There is intentionally no signed `add_mod` since it doesn't have an easy C implementation due to C's undefined behavior for overflow of signed numbers. You can do this with unsigned numbers easily. If you need it for signed numbers you'll have to implement it (and then we can probably add it to the standard library).

There is an `op_Plus_Percent_Hat` in `FStar.IntN.fstp`, which is a confusing alias of the `Int` operation on bounded nats that shouldn't be there.

**Comment by jroesch** [comment]
@tchajed yeah I just read your commits before you commented, I now see what you were doing. Should we remove these aliases?

**Comment by tchajed** [comment]
Which aliases? The `op_Plus_Percent_Hat`s should definitely go.

**Comment by jroesch** [comment]
Aren't all the `*_mod` operations now invalid? it looks like there are others defined in that file:
see https://github.com/FStarLang/FStar/blob/master/ulib/FStar.IntN.fstp#L100.

**Comment by tchajed** [comment]
I merged a fix for this into master: https://github.com/FStarLang/FStar/commit/3f6b8a3f6d657e7f7ee97b6ba1c0d8f3975ac715

I was a little concerned about making this change without a PR or wider testing, but I think it'll be ok. The earlier removal of the `*_mod` operations already would have broken other code; this just removes some operators that had the wrong types anyway, as you ran into in this issue.
