### ISSUE TITLE
Failure not an embedded list when using Prims.norm

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1205]
The following example raises `Failure("(Tm_name: y) Not an embedded list: y")`:

```
module Norm_unit

let foo (_:unit) : unit = norm [zeta] ()
```

The argument and return type annotations are necessary. Having some reduction step is needed, but it doesn't seem to matter which one.

**Comment by aseemr** [comment]
The workaround is to define the steps at the top-level, i.e.:

```
module Norm_unit

let steps = [zeta]

let foo (_:unit) : unit = norm steps ()
```

**Comment by mtzguido** [comment]
Error is now slightly different
```
/home/guido/r/fstar/bin/../ulib/prims.fst(149,30-149,31): (Warning) Not an embedded list: y (see also /home/guido/r/fstar/bin/../ulib/prims.fst(149,13-149,14))
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Empty option")
```
This is caused by the let binding in the encoding. The formula we're normalizing contains roughly `y == [zeta] ==> norm y ()`, and then `y` is not a list of steps definitionally, causing the unembedding failure.

**Comment by aseemr** [comment]
This works with F* master. I remember @nikswamy fixed this sometime back. Closing the issue.
