### ISSUE TITLE
(How) do triggers work?

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1208]
The follwing file shows a collection of 10 examples that @kyoDralliam and I don't understand about triggers. I'm not sure if they are bugs.

```fsharp
module Test

assume val p: int -> prop
assume val q: int -> prop

/// First part: weird errors in requires
/// ====================================

/// 1. What is this error? Is the location wrong? It says ‘assertion failed’ on ‘p x’
// let p_1 () : Lemma (requires (forall x . {:pattern q x} p x))
//                    (ensures (q 0 ==> p 0)) =
//  ()

/// 2. Here's a copy of that same error:
// let p_2 () : Lemma (requires (forall x . {:pattern q x} p x /\ q x)) =
//   admit ()

/// 3. Why does removing the trigger remove the error?
// This is disabled because leaving it breaks the rest of the file
// let p_3 () : Lemma (requires (forall x . p x /\ q x)) =
//   admit ()

/// 4. But the admit is needed ?!
// let p_4 () : Lemma (requires (forall x . p x /\ q x)) = ()

/// 5. Here's another trick to solve the error without removing the trigger (adding an assert) (This one doesn't work in batch mode?!)
// let p_5 () : Lemma (requires (forall x . {:pattern q x} (p x /\ q x))) =
//   assert ((q 0 /\ p 0) ==> (p 0 /\ q 0));
//   admit ()

/// 6. Spot the difference! This one fails
// let p_6 () : Lemma (requires (forall x . {:pattern q x} (p x /\ q x))) =
//   assert ((p 0 /\ q 0) ==> (p 0 /\ q 0));
//   admit ()

/// 7. We thought this might be due to ‘prop’, but it fails with ‘Type0’ too:

// assume val p': int -> Type0
// assume val q': int -> Type0

// let p_7 () : Lemma (requires (forall x . {:pattern q' x} (p' x /\ q' x)))
//                     (ensures True) =
//   admit ()

/// 8. Here's a comparison with Dafny:

// let p_8 () : Lemma (requires (forall x . {:pattern q x} p x /\ q x))
//                    (ensures (q 0 ==> p 0)) =
//  assert (q 0 ==> p 0)

// This works in Dafny
// predicate P(i: int)
// predicate Q(i: int)
//
// lemma P_0 ()
//   requires (forall x: int {:trigger Q(x)} :: P(x))
//   ensures (Q(0) ==> P(0)) {
// }

/// 9. This failure is expected (there's nothing to trigger on)
// let p_9 () : Lemma (requires (forall x . {:pattern q x} p x /\ q x))
//                    (ensures (p 0)) =
//  ()

/// 10. But then why does this work?
// let p_10 () : Lemma (p 0) =
//  assume (forall x . {:pattern q x} p x /\ q x);
//  ()

/// 11. Using SMT axioms works exactly as expected:

assume P_AND_Q : (forall x . {:pattern q x} p x /\ q x)

// This fails as expected (no trigger)
// let p_11 () : Lemma (p 0) =
//  ()

// This succeeds as expected
// let p_12 () : Lemma (p 0) =
//  assert (q 0 == q 0);
//  ()
```

**Comment by cpitclaudel** [comment]
CC @nikswamy

**Comment by nikswamy** [comment]
A lot of what seems to be going wrong here is due to bugs in desugaring, rather than anything to do with triggers.

Notably, `Lemma (requires p)` is actually treated as `Lemma p` which is treated as ... `Lemma (ensures p)`. :P 

There also seem to be discrepancies between the way `val p : .. -> Lemma ...` is handled vs. `let p .. : Lemma = e` is handled.  If you switch to writing `val` and `let` separately then I think the strange behavior you observed  goes away.

So, how about this for a plan:

1. I will work on fixing the desugaring issues for `Lemma (requires p)` instead desugaring it to `Lemma (requires p) (ensures True)` which is your intention, I think. (easy)

2. I will investigate why we get different SMT queries for `val`+`let` vs an annotated `let` only. These discrepancies seem to be a recurring issue ...

Meanwhile, it would be great if you could try out your examples using `val + let` and without using `Lemma (requires p)`. I'll be curious to know if you still have unexplained behavior.

**Comment by nikswamy** [comment]
FYI, looking at the desugaring code for Lemma, I think it makes more sense to forbid questionable uses of the Lemma sugar. So, `Lemma (requires p)` will be forbidden. Are you okay with that?


```
             let expected_one_of = ["Lemma post";
                                    "Lemma (ensures post)";
                                    "Lemma (requires pre) (ensures post)";
                                    "Lemma (ensures post) [SMTPat ...]";
                                    "Lemma (ensures post) (decreases d)";
                                    "Lemma (ensures post) (decreases d) [SMTPat ...]";
                                    "Lemma (requires pre) (ensures post) (decreases d)";
                                    "Lemma (requires pre) (ensures post) [SMTPat ...]";
                                    "Lemma (requires pre) (ensures post) (decreases d) [SMTPat ...]"] in
             let msg = String.concat "\n\t" expected_one_of in
             raise (Error("Invalid combination of arguments to 'Lemma'; expected one of\n\t" ^ msg, t.range))
```

**Comment by nikswamy** [comment]
As for my point (2), it seems that the problem is partly described by my commit above https://github.com/FStarLang/FStar/commit/3520036bbc11b79ce174edcb2280c3affcdadc54

Take the first example : When checking
```
Lemma (requires (forall x . {:pattern q x} p x))
             (ensures (q 0 ==> p 0))
<:
Lemma (requires (forall x . {:pattern q x} p x))
             (ensures (q 0 ==> p 0))
```

We were correctly generating the SMT query:

```
forall (uu___156851:Prims.unit).
  (*could not prove post-condition*)
  forall (p:Prims.pure_post Prims.unit).
    (forall (x:Prims.int). {:pattern  Issue1208.q x } Issue1208.p x) /\
    (forall (x:Prims.unit). Issue1208.q 0 ==> Issue1208.p 0 ==> p x) ==>
    (forall (y:Prims.unit). y == () ==> p y) /\
(** THIS NEXT BIT IS THE INTERESTING YET REDUNDANT PART **)  
(*could not prove post-condition*)
  forall (p:Prims.pure_post Prims.unit).
    (forall (x:Prims.int). {:pattern  Issue1208.q x } Issue1208.p x) /\
    (forall (x:Prims.unit). Issue1208.q 0 ==> Issue1208.p 0 ==> p x) ==>
    (forall (x:Prims.int). {:pattern  Issue1208.q x } Issue1208.p x (* <-- THIS PART *) ) /\
    (forall (x:Prims.unit). Issue1208.q 0 ==> Issue1208.p 0 ==> p x)
```

Now, notice that second part of that VC is indeed not provable precisely because the trigger provided in the `:pattern` annotation is makes it impossible to prove THIS PART of the formula.

I've now removed this redundant check as described in the commit message.

This will hopefully reduce the surprise factor in examples such as the one you report.

And also reduce some of the redundancy in the VCs that we're generating.

**Comment by cpitclaudel** [comment]
Thanks. It makes a sense. Question though:

In the first part, how does z3 succeed?

```
forall (uu___156851:Prims.unit).
  (*could not prove post-condition*)
  forall (p:Prims.pure_post Prims.unit).
    (forall (x:Prims.int). {:pattern  Issue1208.q x } Issue1208.p x) /\
    (forall (x:Prims.unit). Issue1208.q 0 ==> Issue1208.p 0 ==> p x) ==>
    (forall (y:Prims.unit). y == () ==> p y) /\
```

I'd expect it to not  get an instance of `Issue1208.q 0` until it instantiates the second quantifier, which shouldn't really happen, since there's nothing to trigger on.

**Comment by cpitclaudel** [comment]
> FYI, looking at the desugaring code for Lemma, I think it makes more sense to forbid questionable uses of the Lemma sugar. So, Lemma (requires p) will be forbidden. Are you okay with that?

That sounds OK; hopefully the error message can give guidance about adding the missing elements (it feels a bit counterintuitive to allow some keywords on their own, but not all).  WOuld it be tricky to support `requires` alone as well?

**Comment by cpitclaudel** [comment]
Trying with `val`s and proper `Lemma` annotations works much better :)

I have only two issues left:

```fsharp
assume P_AND_Q : (forall x . {:pattern q x} p x /\ q x)

// This works as expected
let p_12 () : Lemma (p 0) =
 assert (q 0 == q 0);
 ()

// Why does this fail?
val p_13 : unit -> Lemma (p 0)
let p_13 () =
 assert (q 0 == q 0);
 ()
```

```fsharp
// Why does this work? There's nothing to trigger on, is there?
val p_10 : unit -> Lemma (requires True) (ensures p 0)
let p_10 () =
 assume (forall x . {:pattern q x} p x /\ q x);
 ()
```

**Comment by nikswamy** [comment]
Regarding this part

> In the first part, how does z3 succeed?
> 
> forall (uu___156851:Prims.unit).
> (*could not prove post-condition*)
>  forall (p:Prims.pure_post Prims.unit).
>   (forall (x:Prims.int). {:pattern  Issue1208.q x } Issue1208.p x) /\
>   (** THIS QUANTIFIER **) (forall (x:Prims.unit). Issue1208.q 0 ==> Issue1208.p 0 ==> p x) ==>
>    (forall (y:Prims.unit). y == () ==> p y) /\
> I'd expect it to not get an instance of Issue1208.q 0 until it instantiates the second quantifier, which 
> shouldn't really happen, since there's nothing to trigger on.

The lack of explicit pattern on a quantifier should not be interpreted as "nothing to trigger on". Instead, it means that Z3+F*'s SMT encoding is free to choose a trigger as it sees fit.

In this particular case, F* chooses the pattern on the THIS QUANTIFIER to be `p x`. In other cases, F* will not choose a pattern and let Z3's trigger selection do the job.

**Comment by nikswamy** [comment]
About this one:

```
assume P_AND_Q : (forall x . {:pattern q x} p x /\ q x)

// This works as expected
let p_12 () : Lemma (p 0) =
 assert (q 0 == q 0);
 ()

// Why does this fail?
val p_13 : unit -> Lemma (p 0)
let p_13 () =
 assert (q 0 == q 0);
 ()
```

This is because in the second example `q 0 == q 0` happens to be simplified away to `True` by F* before SMT encoding. For obscure reasons (in particular, additional monadic binds that get inserted along the way), in the first example, this simplification doesn't take place and `q 0` is still left in the SMT query.

**Comment by nikswamy** [comment]
Finally, this one is quite interesting. Heads up @mtzguido and @Chris-Hawblitzel (who noticed this issue in another context). Would be useful to get your feedback on this.

```
// Why does this work? There's nothing to trigger on, is there?
val p_10 : unit -> Lemma (requires True) (ensures p 0)
let p_10 () =
 assume (forall x . {:pattern q x} p x /\ q x);
 ()
```

What's happening here is that the `assume (forall x. ...)` shows up in the SMT encoding in two forms:

1. As a Z3 forall, correctly guarded by the pattern. (this is fine)

2. But, we also encode the `assume (forall x. ...)` as a term in Z3 of the form `(Prims._assume (Prims.l_Forall Prims.int Tm_abs_xxx))`, which is the underlying encoding of the `forall` term in F*. 

This leads to a problem when combined with some work we did this past summer. With @mtzguido, we added the following assertion to the background axioms in F*'s Z3 encoding. 

```
;;;;;;;;;;;;;;;;forall interpretation
;;; Fact-ids: Name Prims.l_Forall; Namespace Prims
(assert (! (forall ((@x0 Term) (@x1 Term))
                   (! (iff (forall ((@x2 Term))
                                   (! (implies (HasTypeZ @x2
                                                         @x0)
                                               (Valid (ApplyTT @x1
                                                               @x2)))
                                      

                                      :pattern ((HasTypeZ @x2
                                                          @x0))
                                      :qid forall-interp.1))
                           (Valid (Prims.l_Forall @x0
                                                  @x1)))
                      

                      :pattern ((Prims.l_Forall @x0
                                                @x1))
                      :qid forall-interp))
           :named forall-interp))
```

This axiom interprets the `l_Forall` as a Z3 `(forall ... )`, but, in doing so, it drops the pattern on the quantifier that was present in the source program.

So, now the Z3 instantiates the quantifier as it pleases and is able to prove the post-condition.

**Comment by nikswamy** [comment]
I'm inclined to remove this `forall-interp` and its counterpart `exists-interp` from the background axioms, since they lead to this kind of unpredictable behavior.

WDYT?

```
;;;;;;;;;;;;;;;;exists interpretation
;;; Fact-ids: Name Prims.l_Exists; Namespace Prims
(assert (! (forall ((@x0 Term) (@x1 Term))
                   (! (iff (exists ((@x2 Term))
                                   (! (implies (HasTypeZ @x2
                                                         @x0)
                                               (Valid (ApplyTT @x1
                                                               @x2)))
                                      

                                      :pattern ((HasTypeZ @x2
                                                          @x0))
                                      :qid exists-interp.1))
                           (Valid (Prims.l_Exists @x0
                                                  @x1)))
                      

                      :pattern ((Prims.l_Exists @x0
                                                @x1))
                      :qid exists-interp))
           :named exists-interp))```

**Comment by cpitclaudel** [comment]
> The lack of explicit pattern on a quantifier should not be interpreted as "nothing to trigger on". Instead, it means that Z3+F*'s SMT encoding is free to choose a trigger as it sees fit.

Yes, of course; but where does the instance of `p` (the VC `p` taking a `unit` come from?)

> This is because in the second example q 0 == q 0 happens to be simplified away to True by F* before SMT encoding. For obscure reasons (in particular, additional monadic binds that get inserted along the way), in the first example, this simplification doesn't take place and q 0 is still left in the SMT query.

Fascinating, thanks!

> I'm inclined to remove this forall-interp and its counterpart exists-interp from the background axioms, since they lead to this kind of unpredictable behavior.

Does that break anything? O:)

**Comment by nikswamy** [comment]
>> The lack of explicit pattern on a quantifier should not be interpreted as "nothing to trigger on". Instead, 
>> it means that Z3+F*'s SMT encoding is free to choose a trigger as it sees fit.

> Yes, of course; but where does the instance of p (the VC p taking a unit come from?)

The last forall is in positive position (and the whole formula is negated for the SMT solver), so it gets skolemized, producing a `p y`.

**Comment by nikswamy** [comment]
>> I'm inclined to remove this forall-interp and its counterpart exists-interp from the background axioms, 
>> since they lead to this kind of unpredictable behavior.

> Does that break anything? O:)

It was added recently to enable some kinds of proofs that were showing up as we were working on tactics. I forget the examples that really needed them, though. Certainly the bulk of our examples do not need this axiom. Guido may recall the specifics better than I do.

In any case, removing this axiom will only require more explicit proofs occasionally, which I find preferable to introducing unpredictability more commonly.

FYI, @Chris-Hawblitzel produced this example which illustrates a particularly bad case of this problem:

>  Here's a simple example of how this can cause a matching loop:

 ```assume val s : int -> int
assume val f : int -> int

let l () : Lemma
  (requires forall i.{:pattern (f (s i))} f i <= f (s i))
  (ensures  f 0 <= f (s (s 0)))
  =
  assert (forall i.{:pattern (f (s i))} f i <= f (s i));
  assert (f (s 0) <= f 0); // should fail quickly
  ()
```


> With the pattern, the last assertion should fail quickly.  But when the pattern gets dropped, there's a matching loop (using --z3cliopt smt.QI.EAGER_THRESHOLD=10000 makes the matching loop noticeable, and causes Z3 to take a long time).

**Comment by mtzguido** [comment]
I think the interpretation of l_Forall and l_Exists has been in place for quite a long time. For tactics we just made a slight change to the trigger, turning it from `Valid (l_Forall t p)` to `l_Forall t p`, which is partially the cause for this last example (i.e., changing it back causes `p_10` to fail).

That change wasn't strictly related to tactics, or not anymore at least. We had the problem that unfolding logical connectives would change the encoding and make certain queries fail, but we worked around that in tactics by preventing the unfolding instead of trying to make the unfolded queries succeed.

Removing the interpretations altogether causes many failures (~70) across the regression suite. Changing the trigger back to the way it was has some impact but it seems much smaller (still running it).

**Comment by nikswamy** [comment]
Thanks Guido ... it's coming back now.

Where are those ~70 failures coming from? If it's just in core libraries like FStar.Squash and FStar.Classical etc., perhaps we can revise them to make use of this axiom more explicitly.

I also wonder if we should revise the encoding so that rather than a global axiom for l_Forall and l_Exists (for which I don't see a way to encode the user's triggers), we emit axioms on a per-occurrence basis while preserving the triggering behavior requested by the user.

**Comment by nikswamy** [comment]
FYI, @chris-hawblitzel's example of a matching loop via forall_interp is now partially solved (or at least side-stepped). We no longer emit equalities in the VC among unit-typed terms. 

This makes Chris' program fail very quickly, as was the intention.

The reason is that with the patch, there is no longer an `l_Forall` term introduced in the VC for the assertion. 

```
module Test
assume val f : int -> int
assume val s : int -> int

let l () : Lemma
 (requires forall i.{:pattern (f (s i))} f i <= f (s i))
 (ensures  f 0 <= f (s (s 0)))
 =
 assert (forall i.{:pattern (f (s i))} f i <= f (s i));
 assert (f (s 0) <= f 0); // should fail quickly
 ()
```

**Comment by nikswamy** [comment]
However, it's still only a partial solution, since you can still write a program like this:

```
let l () : Pure Type0
 (requires forall i.{:pattern (f (s i))} f i <= f (s i))
 (ensures  f 0 <= f (s (s 0)))
 =
 assert (forall i.{:pattern (f (s i))} f i <= f (s i));
 let tmp = (forall i.{:pattern (f (s i))} f i <= f (s i)) in
 assert (f (s 0) <= f 0); // should fail quickly
 tmp
```

The `tmp` is still encoded to the solver as an `l_Forall` which triggers the same problematic, unguarded axiom. This invocation still takes ages.

```
$ fstar --z3cliopt smt.QI.EAGER_THRESHOLD=10000  test.fst
```

**Comment by nikswamy** [comment]
FYI, the relevant commits that remove equalities on unit-typed terms are
4030ed84f718e7116caafec818e56913cd9920b4
and
254ce7a2c5e4d6ea01b5a63398fae3790babb202

**Comment by nikswamy** [comment]
The generic `forall-interp` and `exists-interp` are now gone, in favor of specific instantiations produced on an as-needed basis by the encoding.

Take this program:

```
module Bug1208
assume val f : int -> int
assume val s : int -> int

let q =
  let _ = () in
  (forall i.{:pattern (f (s i))} f i <= f (s i))

let l () : Lemma (f 0 <= f (s (s 0)))
 =
 assume q;
 assert (f (s 0) <= f 0) // should fail quickly
```

It fails quickly in F* master, e.g., version 885a773b94b063325aca4f371e34bfd959bb1357

Although, before this change, say, with version, 68161f469a5f3b32184bed665134b0f665227d36, this enters a matching loop in Z3. 
```fstar bug1208.fst --z3cliopt smt.qi.eager_threshold=10000 --max_fuel 0 --max_ifuel 0``` doesn't return for a long while (i had to kill it).
