### ISSUE TITLE
Contextual behaviour of triggers (and --z3refresh)

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#1211]
This issue is closely related to #1208.
The following code has the weird behaviour that the toplevel definition `p_5` only verify if `p_2` is defined beforehand.

```F#
module Mini

assume val p: int -> prop
assume val q: int -> prop

let p_2 () : Lemma (requires (forall x . p x /\ q x)) =
  admit ()

let p_5 () : Lemma (requires (forall x . {:pattern q x} (p x /\ q x))) =
  assert ((p 0 /\ q 0) ==> (p 0 /\ q 0));
  admit ()
```

Moreover, using `z3 4.5.0`, `p_5` verifies the first time it is checked in interactive mode but not the second as is shown by the following transcript :
```
{"query-id":"1","query":"push","args":{"kind":"full","code":"module Mini\n","line":1,"column":0}}
{"query-id":"2","query":"push","args":{"kind":"full","code":"\nassume val p: int -> prop\nassume val q: int -> prop\n","line":2,"column":0}}
{"query-id":"3","query":"push","args":{"kind":"full","code":"\nlet p_2 () : Lemma (requires (forall x . p x /\\ q x)) =\n  admit ()\n","line":5,"column":0}}
{"query-id":"4","query":"push","args":{"kind":"full","code":"\nlet p_5 () : Lemma (requires (forall x . {:pattern q x} (p x /\\ q x))) =\n  assert ((p 0 /\\ q 0) ==> (p 0 /\\ q 0));\n  admit ()\n","line":8,"column":0}}
{"query-id":"5","query":"pop","args":{"dummy":null}}
{"query-id":"6","query":"push","args":{"kind":"full","code":"\nlet p_5 () : Lemma (requires (forall x . {:pattern q x} (p x /\\ q x))) =\n  assert ((p 0 /\\ q 0) ==> (p 0 /\\ q 0));\n  admit ()\n","line":8,"column":0}}
```

This behaviour is not present in `z3 4.5.1`, and the code always verifies. Any idea where this could come up from @wintersteiger ? 

Another weirdness is created by the option `--z3refresh` which makes the verificationof `p_5` always fail with both versions of z3.

**Comment by wintersteiger** [comment]
On the Z3 side, the short answer is that the search goes down a different path, due to various changes since 4.5.0 (and indeed your changes to the order of constraints). One problem that has always existed in Z3 is that quantifier instances are not kept during backtracking, so after swapping the order of decisions, it ends up with a different set of instances that may or may not be sufficient to prove the goal. 

(The main reason for this is that Z3 doesn't track the dependencies of quantifier instances, which, incidentally, is also the main reason for hints not replaying. There's a quick and dirty fix, but it kills the performance; I'm working on fixes for this and related problems, but no ETA at this point in time.)

**Comment by cpitclaudel** [comment]
Thanks Christoph. But does that that also explain why things verify once, then fail on the second attempt in 4.5.0? And does it explain why things always fail with --z3refresh?

**Comment by wintersteiger** [comment]
Probably. I didn't look into this particular one yet, but in incremental mode it's very well possible that it will behave differently in the second run (e.g. the first push/pop that Z3 encounters, makes it switch from a non-incremental solver to an incremental one, which is frequently a source of confusion for our users).

--z3refresh changes the way the queries look, so yes, it can make it behave differently than non-z3refresh ones. There is no guarantee that Z3 will exhibit "similar" behavior on "similar" queries, this is an inherent property of search-based algorithms, and taking any amount of unpredictability out of the process usually incurs a significant performance penalty, so it's a fine line to walk.

**Comment by cpitclaudel** [comment]
The problem here was that `Lemma (requires x)` was parsed as `Lemma (ensures x)`

**Comment by cpitclaudel** [comment]
(That issue was fixed by @nikswamy recently; the error message is much better now)
