### ISSUE TITLE
"Empty token" error for lonely @author annotation in fsdoc

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1216]
For example:

```
(** Behold, a module!
@author Me **)
module A
```

```
[F* error] /build/fstar/master/A.b.test.CCcCcC.d.fst(4,0-4,0): (Error) Syntax error: Failure("lexing: empty token")
[F* error] 1 error was reported (see above)
```

**Comment by cpitclaudel** [comment]
The error message is slightly different now that @ad-l 's changes are in:

```
(** AAA BBB CCC
@author Me **)
module Test
```

```
[F* error] /tmp/test.fst(4,0-4,0): (Error) Syntax error: FStar_Ulexing.Error
[F* error] 1 error was reported (see above)
```

**Comment by cpitclaudel** [comment]
I think @msprotz mentioned that he has pending changes for this part of the parser. Maybe they fix this bug as a side effect :)

**Comment by msprotz** [comment]
that's still an error but I can fix it tomorrow since I've looked at this part of the code recently

**Comment by msprotz** [comment]
@jroesch has a pull request about to land for this, I believe

**Comment by jroesch** [comment]
I got distracted last week trying to get the rest of the mitls2c finished, will follow up this week 😄

**Comment by jroesch** [comment]
Update: trying to debug some strange issue that has cropped up since I last touched this branch where F* consumes crazy amount of memory (60gb of virtual memory) when it should report and error.

**Comment by nikswamy** [comment]
fsdoc is gone in favor of fstardoc. See PR #1939. Closing.
