### ISSUE TITLE
"Universe variable not found" when normalizing

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1218]
Evaluating the following and then running `C-c C-s C-e` on `test` crashes F* with "universe variable not found".

```
let test (o: 'a) : int = 0
```

I think that's probably a bug in my evaluation code, but I'd welcome tips or suggestions on how to debug this :)

**Comment by cpitclaudel** [comment]
Added `FStar.TypeChecker.Normalize.AllowUnboundUniverses` to the list of reduction steps fixes the issue

Is that reasonable?

**Comment by kyoDralliam** [comment]
It seems that the normalizer is expecting that all universe variables are instanciated :
```test 5 ↓βδιζ 0 <: Prims.int```
```test ↓βδιζ Failure("Universe variable not found")```
```test u#0 ↓βδιζ fun  -> fun o -> 0 <: Prims.int```
(Btw the interactive mode only prints `test u` in the last case which is a little funny and the `fun  ->` is also strange)

**Comment by cpitclaudel** [comment]
Thanks for the sleuthing work! Sounds like the `AllowUnboundedUniverses` solution is OK, then, right?

The `fun  -> fun o -> 0 <: Prims.int` is returned directly by F*; I'm not sure why it gets printed like this.

**Comment by kyoDralliam** [comment]
I would argue against using the `AllowUnboundedUniverses` since we do have some other solution...

**Comment by cpitclaudel** [comment]
I see. So we should special case top-level terms ?

**Comment by kyoDralliam** [comment]
Yes in the sense that they *do* provide and need some specific treatment for universe variable.

**Comment by cpitclaudel** [comment]
OK, understood. 
I don't want to waste your time, but: do you know what API I could use for that? Do I need to descend through the whole term, find uses of top-level definitions in there, and instantiate them? It sounds pretty tricky :/ (or am I misunderstanding? I'm extrapolating from the fact that `(fun () -> test)` fails to reduce as well)

**Comment by cpitclaudel** [comment]
@kyoDralliam looked at the code and spotted a failure to open universes. All set :) Will push soon.
