### ISSUE TITLE
Bogus "Patterns are incomplete" error for if-then-else

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#122]
The following code
```
assume val bar : p:Type -> Tot bool
val foo : unit -> Tot bool
let foo _ = (if bar False then true else false)
```
raises a bogus "Patterns are incomplete" error:
```
Error bug121.fst(7,0-8,0): The following problems were found:
	Patterns are incomplete (bug121.fst(7,12-7,47))
```

**Comment by nikswamy** [comment]
The encoding fails to prove that False:Type. 

This is because we have `logic type False` in the prelude and the encoding has been omitting kind information for logic types. 

If you wrote (if bar int then true else false) then it goes through.

I'll restore kind information for logic types too.

**Comment by catalin-hritcu** [comment]
I'm getting this problem again in `lambda_omega`.

**Comment by catalin-hritcu** [comment]
Nik's latest changes also fixed this.
