### ISSUE TITLE
The link in the readme for the Slack channel is broken

### ISSUE THREAD

**Issue by Nonius** [FStarLang/FStar#1224]
The link in the readme for the Slack channel is broken

**Comment by s-zanella** [comment]
fpchat.com seems down.
You can join from https://fpchat-invite.herokuapp.com/

**Comment by Nonius** [comment]
Entered a valid email, pressed invite, and I see please wait for minutes...

**Comment by beurdouche** [comment]
This is not ours BTW, it is a community driven slack and it has automatic approval...

**Comment by mtzguido** [comment]
Fixed by 76b72fecabcf52b469ed8c86dcc7cd171ae0b7b8
