### ISSUE TITLE
[Tutorial] Explain block building

### ISSUE THREAD

**Issue by ShalokShalom** [FStarLang/FStar#1227]
How does F* block building? Indentation?

**Comment by A-Manning** [comment]
F* is not very whitespace sensitive - it uses a syntax similar to OCaml, or F#'s "non-light"/"verbose" syntax. Delimiting is done through the `in`, `begin`, and `end`  keywords, as well as parenthesis. 

For example, the following is perfectly valid (although unreadable) F* - 
```
let f = 
        let   x 
    =
        2
+

 3                                  in
                        x +
                    2
```

**Comment by ShalokShalom** [comment]
Thanks a lot.

**Comment by beurdouche** [comment]
Thanks @A-Manning

**Comment by ShalokShalom** [comment]
You might want to include this into your tutorial.
