### ISSUE TITLE
Embedding not defined for type Type

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1235]
```
module Kremlin_tactic

open FStar.Tactics

noextract
let noop (t:Type) : tactic unit = fun _ -> ()
```

per FStarLang/kremlin#54 and since #1221 is not the right fix: the problem above send F*'s extraction off the rails

@kyoDralliam @victor-dumitrescu @mtzguido any clue why we get this error? 

This is currently blocking the merge that @jroesch is trying to perform...

Thanks,

Jonathan

**Comment by victor-dumitrescu** [comment]
As discussed, when extracting a tactic for which a binding cannot be generated automatically, the process no longer quits with a fatal error. Instead, the user is warned that the tactic won't be run natively and extraction continues.
