### ISSUE TITLE
Disturbing error message if one loads FStar.ST before FStar.Heap

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#1239]
Hi

The following code raises an error message whereas it works fine if I load FStar.Heap first. I tried on the online version of FStar.

```
module Foo

open FStar.ST
open FStar.Heap

val foo : i:ref int -> ST unit (requires fun h0 -> contains h0 i)
                               (ensures fun _ _ h1 -> sel h1 i = 0)
let foo i = i := 0
```

Error message:
`Foo(8,12-8,13): (Error) Subtyping check failed; expected type FStar.ST.mref Prims.int (FStar.Heap.trivial_preorder Prims.int); got type FStar.Heap.ref Prims.int (see also /var/fstar/ulib/FStar.ST.fst(73,57-73,84))`

**Comment by kyoDralliam** [comment]
`FStar.Heap` and `FStar.ST` both define the type ref (the second being a refinement of the first) whereas the update operation `:=` is only defined in `ST` and requires the latter. It's an annoying recurring problem...
Maybe we could have a better situation by putting the definition of ref in Heap in a submodule Heap.Ref...

**Comment by ckeller** [comment]
That's what I figured out after 5-10min...

**Comment by s-zanella** [comment]
This shadowing of `ref`, `mref` is annoying. 
The refinement is provable in this case:
```F#
val foo : i:ref int -> ST unit
  (requires fun h0 -> contains h0 i)
  (ensures fun _ _ h1 -> sel h1 i = 0)
let foo i =
  gst_witness (contains_pred i);
  i := 0
```

**Comment by aseemr** [comment]
Agree that this is annoying. Just FYI, there is also `FStar.Ref.fst` that you can use (instead of `ST` and `Heap`) if you are working with refs with default preorder. This module also obviates the need of some manual annotations when using `alloc`.

**Comment by aseemr** [comment]
What would be the fix here? The current names were chosen to keep the changes in the rest of the code minimal. But we can rename the refs in heap to `heap_ref` or something, and then fix other libraries using it (mostly `HyperHeap` and `HyperStack`).

**Comment by kyoDralliam** [comment]
Lean has an elegant solution based on a `protected` keyword which forces you to explicitly  qualify a definition even when the containing namespace is open. This would be an entire RFC but it would solve nicely this problem.

@tahina-pro Do you think it would be feasible wrt to the current module/name export mechanism ?

**Comment by cpitclaudel** [comment]
Should we close this issue and discuss @kyoDralliam's proposal in a separate issue?

**Comment by aseemr** [comment]
I am actually not sure if we should call the normalizer before typechecking the term. It should be possible to avoid it (we do it for the inductive type itself), I will look into that some time.

**Comment by aseemr** [comment]
This requires a significant redesign of the libraries (renaming `ref` types etc.) or some other mechanism like what Kenji is proposing. Closing it as wontfix for now, should revisit.
