### ISSUE TITLE
Simple linear arithmetic operations do not go through automatically

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#124]
I am working on arithmetic operations and F* is not proving automatically some very simple properties, like 

    val test: a:int -> Lemma (requires (True))
                             (ensures (a - a + a = a)) 
    let test a = ()

returns

    Error (...): The following problems were found: post-condition at (...)

Is it normal ? Could it be improved ? I assumed Z3 would be able to do something like that.
I am also experiencing issues with the parenthesizing  : for instance 
    
    val test: a:int -> Lemma (requires (True))
                             (ensures ( a - a + a = (a - a) + a ))
    let test a = ()

does not go through either.

Is there a way to automatize all that instead of axiomatizing everything ?

Best,

Jean Karim

**Comment by aseemr** [comment]
This is happening because of parsing. a - a + a is being parsed as a - (a + a), which makes the postcondition not true. If I parenthesize it explicitly as (a - a) + a, then it works fine.

**Comment by nikswamy** [comment]
Ugh ... thanks for the report and for reducing this to a parser bug.

**Comment by catalin-hritcu** [comment]
This is still broken.

**Comment by nikswamy** [comment]
Closing for now ... would be great if someone can confirm that we have the expected precedence for all operators.

**Comment by ad-l** [comment]
We can't close this until assert(1-2-3=2) fails
