### ISSUE TITLE
Array literals are broken

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1243]
```ocaml
let a = [|1|]
```
```
(Error) Identifier not found: [FStar.Array.mk_array]
Module FStar.Array resolved into FStar.Array, definition mk_array not found
```

This is caused by a bug in `FStar.Parser.Const.fs`
```fsharp
let array_mk_array_lid = p2l ["FStar"; "Array"; "mk_array"]
```
The issue is that `FStar.Array.mk_array` does not exist.

**Comment by cpitclaudel** [comment]
Good point :) Just made a PR.
But note that array constants aren't that useful, because using them is an effectful operation.

**Comment by A-Manning** [comment]
I agree, perhaps it would be better to allow user-defined bracketing operators, and pass the semicolon seperated list as an argument, rather than hard-code array syntax(and a particular array model) into F*? There are a variety of enumerable types that people may wish to use, like vectors, different array models, sequences, enumerated trees, etc. - it would be nice to have syntax support for this.
It seems like it wouldn't be too much of a change to make in the parser. 
eg. 
```ocaml
let (  [|...|]  ) : list 'a -> array 'a = FStar.Array.mk_arrray

let arr: array int = [| 1; 2; 3; 4 |]
```

**Comment by cpitclaudel** [comment]
Yes, that sounds good.

Plus, we almost have it already, since we have access and assignment.

```
let op_Array_Access ls idx = List.Tot.nth ls idx

let op_Array_Assignment ls (idx: nat{idx <= List.Tot.length ls}) v =
  let before, after = List.Tot.Base.splitAt idx ls in
  before @ v :: after

let xx =
  ([1;4;3].(1) <- 2).(1)
```

@kyoDralliam, WDYT of having an `op_Array_Literal` or something similar?
