### ISSUE TITLE
Directly store file names in FStar.Range

### ISSUE THREAD

**Issue by ad-l** [FStarLang/FStar#1244]
Error reporting is broken with binary cached modules, since the file index to file name table is not preserved. Furthermore, currently the OCaml lexer interprets __SOURCE_FILE__ incorrectly (uses the file index rather than name).

We agreed on the F* meeting to store filenames in range directly.

**Comment by nikswamy** [comment]
@ad-l any updates on this? If you're busy with other stuff, I'd be happy to take this off your plate.

**Comment by cpitclaudel** [comment]
@nikswamy Looks like you fixed it, should this be closed?
