### ISSUE TITLE
Unicode arrows accepted by the Unicode lexer

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1249]
The new unicode lexer lets you use unicode arrows and symbols instead of keywords.

Do we expect these to be used? (In that case, I need to adjust the Emacs mode to recognize them too.)

One thing I'm worried is this part of the mapping:

```
==>  ⇒
<==> ⇔
```

The Emacs mode has been prettifying these as long arrows for a while:

```
==>  ⟹
<==> ⟺
=>   ⇒
```

I'm happy to change the Emacs mode to use short arrows if these are what we want (though I have a preference for the long ones :)

cc @ad-l

**Comment by ad-l** [comment]
It's a valid point, since nobody is currently using the unicode literal yet I'm willing to change them

**Comment by ad-l** [comment]
While I'm at it I can probably add the other ligatures in emacs-mode
What do you use for `~>` and `<--`? (I guess `↝` and `⟵`?)
Do you support `×` for op_Multiply?
Do you have literals for some types like `nat` and `int` (ℕ,ℤ, what else?)

**Comment by cpitclaudel** [comment]
Here's the full list:

```elisp
(pcase-dolist (`(,from . ,to) fstar-symbols-alist) (princ (format "%s → %c\n" from to)))
```

```
exists → ∃
forall → ∀
fun → λ
nat → ℕ
int → ℤ
True → ⊤
False → ⊥
* → ×
:= → ≔
:: → ⸬
<= → ≤
>= → ≥
<> → ≠
/\ → ∧
\/ → ∨
~ → ¬
|| → ‖
<==> → ⟺
==> → ⟹
-> → →
~> → ↝
=> → ⇒
<- → ←
<-- → ⟵
--> → ⟶
<< → ≪
<| → ◃
|> → ▹
'a → α
'b → β
'c → γ
'd → δ
'e → ε
'f → φ
'g → χ
'h → η
'i → ι
'k → κ
'm → μ
'n → ν
'p → π
'q → θ
'r → ρ
's → σ
't → τ
'u → ψ
'w → ω
'x → ξ
'z → ζ
```

**Comment by cpitclaudel** [comment]
I think most of these would make sense in the lexer as well — I'm unsure about the greek ones, though.

**Comment by cpitclaudel** [comment]
Somewhat related thought: there's a subtle trade-off here

OTOH, I think it's good to make sure that `==>` and `⟹` mean the same thing, because they look the same with prettification on.
OTOH, letting programmers use the unicode version of these symbols makes it it much harder to turn off prettification for those who don't want it.

**Comment by cpitclaudel** [comment]
Another questionable one is the prettification of `*`, since I've heard calls in the past to distinguish `*` and `×`.

**Comment by ad-l** [comment]
I like `×` being for `op_Multiply` rather than `*`. I think you should use `∗` as a nicer `*`, and `×` for `op_Multiply`

As to whether unicode literal should be saved by emacs by default, I think the answer is no. It can be convenient to accept these literals (to typecheck pretty code from example/tutorial, and to directly copy from emacs) but for maximal portability and compatibility we should stick to the vanilla ASCII art in the standard library.

**Comment by ad-l** [comment]
See PR #1251

**Comment by cpitclaudel** [comment]
> As  to whether unicode literal should be saved by emacs by default, I think  the answer is no. It can be convenient to accept these literals (to  typecheck pretty code from example/tutorial, and to directly copy from  emacs) but for maximal portability and compatibility we should stick to  the vanilla ASCII art in the standard library.

OK, this makes sense to me. (As a side note, copying from Emacs gives you the prettified version only if you're copying from a terminal)
