### ISSUE TITLE
Missing "requires" clause in Lemma with SMTPat induces a bug

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#125]
In a Lemma with a SMT pattern attached, if the <code>requires (True)</code> clause is left implicit, an error is returned. For instance,

```
val test: a:int -> Lemma (* ( requires (True) ) *)
                         (ensures ( a * a >= 0 ))
                         [SMTPat ( a * a ) ]
let test a = ()
```

returns 

```
Error
Expected type "bool"; 
got type "(list (U4848 a))"
```

while if the requires clause is explicit everything is fine.

**Comment by catalin-hritcu** [comment]
Agreed, this is annoying. Hope that this will go away at least when #57 is fixed.

**Comment by nikswamy** [comment]
Yes ... annoying. Need more shorthands for Lemma, including defaulting to a trivial pre-condition when it is omitted.
