### ISSUE TITLE
Possible improvement : assuming "asserts" later in the code

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#126]
If I am correct currently the <code>assert (...);</code> are proven and then discarded by F*.

I think it would be very useful to assume them later in the code and hand them to the SMT solver like what happens when a lemma is manually instantiated.
It would give a flexible and efficient way to find what the prover needs to make the verification go through.

**Comment by catalin-hritcu** [comment]
Agreed, `assert` should first prove the assert and then assume it in the rest of the code. That's the semantics of `assert` in any other verification system I know.

**Comment by aseemr** [comment]
I thought the F* type checker would feed to Z3 a single formula consisting of conjunction of the assert and VC for rest of the code ? If so, Z3 should have the assert in its context when proving VC for rest of the code (if Z3 proves conjunction a /\ b in the order of a then b) ?

**Comment by nikswamy** [comment]
Prims.cut does what you want

**Comment by catalin-hritcu** [comment]
I think it would be good to make assert do the same as cut.

**Comment by hungvq00390** [comment]
module COUNT100

type nat = i:int{0 <= i}

val countTo100: n:int{0 <= n /\ n <= 100} -> x:int{x=100} 
let rec countTo100 n = 
    if n < 100 then countTo100 (n + 1)
    else n
let test1 = assert((countTo100 20) = 100)

**Comment by hungvq00390** [comment]
@catalin-hritcu How can i use assert in F*.

**Comment by ad-l** [comment]
@hungvq00390 Your code is fine except that you need to prove that it terminates

```
module COUNT100

val countTo100: n:int{0 <= n /\ n <= 100} -> Tot (x:int{x=100}) (decreases %[100-n])
let rec countTo100 n =
  if n < 100 then countTo100 (n + 1)
  else n
  
let test1 = assert((countTo100 20) = 100)
```

**Comment by catalin-hritcu** [comment]
Seems we're left with both `assert` and `cut`, and `cut` now actually works (#180). Closing.
