### ISSUE TITLE
Lax+MLish-mode exhaustiveness checking

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1268]
We don't check exhaustiveness of any matches while running in `--lax` mode.  The F# compiler does it for us, but it would be nice to do it ourselves — especially because it could save us a whole call to Z3.

A tactic might do… but I'd love it if there was a way to use it on the compiler too.

**Comment by catalin-hritcu** [comment]
How exactly would this work? The exhaustiveness check in F\* is semantic, using the SMT solver. Are you proposing that the following code should fail lax checking?
```
let f (xs:list int{Cons? xs}) =
  match xs with
  Cons x xs -> x
```
It would correctly succeed without lax mode though, so a lax error here would be spurious.

**Comment by cpitclaudel** [comment]
> The exhaustiveness check in F* is semantic

Yes, of course :)

> Are you proposing that the following code should fail lax checking?

Only with `--MLish`; with just `--lax`, it should go through.

**Comment by cpitclaudel** [comment]
Thanks, the title is better like this.

**Comment by nikswamy** [comment]
I don't think this is sufficiently high priority to fix. --lax and --MLish are internal options and we do not expect to add specific enhancements to support these unsound usages.
