### ISSUE TITLE
verify_all: should F* support it or should we leave it to the build system?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1281]
The `--verify_all` flag causes order of magnitude slowdown for simple stateful examples. I have at least 3 examples of this in my course, but the worst is the stateful factorial example that takes a **34x** hit:
```
module FactorialST

open FStar.Heap
open FStar.ST
open FStar.Mul

val factorial_tot : nat -> Tot nat
let rec factorial_tot x = if x = 0 then 1 else x * factorial_tot (x - 1)

val factorial : r1:ref nat -> r2:ref nat -> ST unit
      (requires (fun h0 -> addr_of r1 <> addr_of r2))
      (ensures (fun h0 _ h1 -> sel h1 r2 = factorial_tot (sel h0 r1) /\
                               sel h1 r1 = 0 /\
                               modifies !{r1,r2} h0 h1))
let rec factorial r1 r2 =
  let x1 = !r1 in
  if x1 = 0
  then r2 := 1
  else 
    (r1 := x1 - 1;
     factorial r1 r2;
     r2 := !r2 * x1)
```
Without `--verify_all` this takes 0.9 seconds.
```
[hritcu@resurrected sol]$ fstar.exe FactorialST.fst
Verified module: FactorialST (894 milliseconds)
All verification conditions discharged successfully
```
With `--verify_all` this takes 30 seconds and needs `--z3rlimit_factor 6` to not just time out:
```
[hritcu@resurrected sol]$ fstar.exe --verify_all --z3rlimit_factor 6 FactorialST.fst
Verified module: FStar.Pervasives.Native (1150 milliseconds)
Verified module: FStar.Pervasives (1058 milliseconds)
Verified module: FStar.Squash (318 milliseconds)
Verified module: FStar.Classical (1008 milliseconds)
Verified module: FStar.FunctionalExtensionality (14 milliseconds)
Verified module: FStar.Set (603 milliseconds)
Verified module: FStar.Mul (5 milliseconds)
Verified module: FStar.Preorder (10 milliseconds)
Verified module: FStar.Ghost (637 milliseconds)
Verified module: FStar.ErasedLogic (285 milliseconds)
Verified module: FStar.StrongExcludedMiddle (261 milliseconds)
Verified module: FStar.PropositionalExtensionality (291 milliseconds)
Verified module: FStar.PredicateExtensionality (352 milliseconds)
Verified module: FStar.TSet (929 milliseconds)
Verified module: FStar.Monotonic.Heap (7987 milliseconds)
Verified module: FStar.Heap (405 milliseconds)
Verified module: FStar.ST (1220 milliseconds)
Verified module: FactorialST (30063 milliseconds)
All verification conditions discharged successfully
```
@nikswamy @aseemr @wintersteiger Any thoughts about why this is happening?

**Comment by nikswamy** [comment]
I don't agree that this is a bug.

Based on another feature request from @jkzinzindohoue  and @protz , --verify_all ends up using both .fst and .fsti for every module in the dependence graph.

This means that the abstraction that you get in the SMT encoding may be lost. That was perhaps an unintended side effect of that feature, which was not anticipated, or at least not documented.

If you say: `fstar FStar.Monotonic.Heap.fsti FStar.Monotonic.Heap.fst FactorialST.fst` you can reproduce this behavior without using `--verify_all`. Basically, the implementation of `FStar.Monotonic.Heap.fst` is available to the SMT encoding, which, expectedly, can cause the SMT solver to search many more paths.

**Comment by nikswamy** [comment]
I have advocated elsewhere that we should just remove --verify_all

**Comment by mtzguido** [comment]
Would it be too hard to keep `--verify_all` while retaining abstraction between modules? Earlier today I found it convenient to do `fstar.exe --verify_all ulib/FStar.Tactics.fst` to make sure that everything was consistent after a big change.

While I agree that any decent build system should not be using it, it seems useful to have it for user interaction.

**Comment by msprotz** [comment]
This would require reverting to the previous behavior, where we would drop the fst/fsti interleaving, to replace it with the fsti only, upon encountering a fst+fsti combo in the dependency graph. But, this conflicted with a pattern that JK strongly advocated for, and which we wanted to support.

I would argue that this is the responsibility of your build system: do `fstar --dep` to figure out all the dependencies, then verify everything.

**Comment by mtzguido** [comment]
Right, if it interferes with other features, then I'm in favor of just nuking it.

Maybe what I really want is a `--recursive` flag, where F* will fork itself for each module. That should bring no extra pain. Does that sound sane / should I try to do that..?

**Comment by msprotz** [comment]
That seems like the job of a Makefile, doesn't it?

I'm just weary of adding build logic into F*... if we had `fstar --dep` and `fstar --dep --all` to traverse or not fstis, then we could easily do this with 10 lines of Makefile, I think?

**Comment by mtzguido** [comment]
We definitely could given `--dep` and `make`. I'm just thinking of the times when one cannot be bothered to write a Makefile or even a new rule for the subset one wishes to verify. I'm selfishly thinking of tactics, but it might apply elsewhere.

GHC does something similar with the `--make` flag, but afaik they have no `--dep`, which sucks.

In any case, no strong feeling about this.

**Comment by catalin-hritcu** [comment]
`--verify_all` is gone and now we have checked files and whatnot
