### ISSUE TITLE
Not a protected embedded term: …

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1282]
I just got this message; repro on https://github.com/FStarLang/FStar/tree/cpitclaudel_not_and_embedded_term:

```
ASSERTION FAILURE: Not a protected embedded term: (FStar.Tactics.Builtins.__embed #_ PatternMatching.var <: FStar.Reflection.Types.term)
<:
Prims.PURE FStar.Reflection.Types.term
F* may be in an inconsistent state.
```

**Comment by cpitclaudel** [comment]
Could it be a problem with ascriptions?

**Comment by cpitclaudel** [comment]
Not sure what added them, though.

**Comment by cpitclaudel** [comment]
With --ugly, things look a bit more clear:

```
ASSERTION FAILURE: Not a protected embedded term: (MonadicLift-Tm_ascribed{FStar.Reflection.Types.term : Prims.PURE -> FStar.Tactics.Effect.TAC} ((FStar.Tactics.Builtins.__embed #Tm_unknown PatternMatching.var) <ascribed: [Prims.Tot] FStar.Reflection.Types.term ))
```

**Comment by mtzguido** [comment]
Yes, we needed to peel off ascriptions and Tm_metas. Fixed now in my branch. Thanks for the report!

(I'll cherry pick the commits to master later and push, since there are parts of my branch that I'm still dubious about)

**Comment by cpitclaudel** [comment]
Thanks! I'll wait for the cherry pick then.

**Comment by mtzguido** [comment]
Now in master. I actually just reverted the part I'm unsure about and merged the rest, so we don't diverge too much.
