### ISSUE TITLE
Confusing errors in `apply`, `apply_lemma`

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1286]
I'm having a lot of trouble just applying lemmas :/ For example, this fails:

```
let unsquash #a : a -> Lemma a =
  fun _ -> ()

let broken (#a: Type0) =
  assert_by_tactic a (apply_lemma (quote unsquash))
```

The error message says this:

```
Expected expression of type "Prims.Tot (uu___1035222:a -> Prims.Lemma Prims.unit)"; got expression "PatternMatching.unsquash" of type "uu___1035224:(*?u23*) _ a -> Prims.Lemma Prims.unit"
```

or (with more printing switches) this:

```
Expected expression of type "#a:Type0 -> Prims.Tot (uu___1030287:a -> Prims.Lemma Prims.unit (Prims.Nil #Prims.pattern) a)"; got expression "PatternMatching.unsquash #((*?u23*) _ a)" of type "uu___1030289:(*?u23*) _ a -> Prims.Lemma Prims.unit (Prims.Nil #Prims.pattern) ((*?u23*) _ a)"
```

What does this mean?

**Comment by cpitclaudel** [comment]
I tried with a regular `apply` too, and the apply does succeed:

```
let unsquash #a : a -> squash a =
  fun _ -> ()

let broken (a: Type0) =
  assert_by_tactic a (apply (quote (unsquash #a)))
```

but the F* complains about an unresolved implicit:

```
Failed to resolve implicit argument of type 'a' introduced in (*?u643*) _ a
```

**Comment by mtzguido** [comment]
The first problem is that the implicit argument for `unsquash` is being instantiated, so the quote is not doing what you want. We had a mechanism to prevent this, but at some point it stopped working, and I don't know why. Trying to fix it.

On the second one you gave the implicit argument explicitly, so that problem doesn't appear. The error is that you left an open goal (of type `a`), but the message is really bad.

**Comment by mtzguido** [comment]
The instantiation is now fixed, and some slightly better errors in master now:
```
$ ./bin/fstar.exe A.fst 
proof-state: State dump @ depth 0(failing due to uninstantiated implicits):
ACTIVE goals (1):
(a:Type0) |- (*?u35*) _ a : a
SMT goals (0):
./A.fst(8,0-9,51): (Error) Tactic left uninstantiated unification variable ?35 of type a (reason = "head of application is a uvar")
1 error was reported (see above)
```
I made some effort to have the reasons be the tactic function where the uvar is introduced, but during unification this changes a lot, so there's no real guarantee about them. Yet it may help a bit..

**Comment by cpitclaudel** [comment]
Thanks! This sounds very similar to what people call the "shelf" in Coq. 
Quick questions: why doesn't that evar become an extra goal? Is there a way to fetch it (Coq's `unshelve`)?

**Comment by mtzguido** [comment]
This one in particular is a goal, as the dump shows. However you can get be "shelved" variables, and there's currently no unshelving.

**Comment by cpitclaudel** [comment]
Oh, I see, thanks :) I'm not used to seeing proof state dumps on the command line.

**Comment by cpitclaudel** [comment]
Another question then: why does it fail so fast? I guess I was expecting the SMT solver to kick in on that last goal, but it seems to be failing instantly. Is that because it's a relevant goal?

Thanks for all your help!

**Comment by mtzguido** [comment]
Yes, precisely, it's a relevant goal so we fail hard immediately. If it were `squash` of something we would unify with `()` (just to instantiate with something) and then call the SMT.

**Comment by cpitclaudel** [comment]
Makes sense :)

**Comment by mtzguido** [comment]
This all made it to master, and further there's `mapply` to stop shooting ourselves in the foot with this kind of things. Closing, but please reopen if I missed something
