### ISSUE TITLE
Simplifying `idtac;; k` into `k` yields "Inconsistent implicit qualifier" after a long pause

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1287]
I posted a repro on `cpitclaudel_slow_idtac`.

In the code I posted, the call to `repeat` succeeds quickly if I write it as `(repeat (idtac;; …))`, but fails slowly if I write only `(repeat (…))`.

Is this a known issue?

**Comment by mtzguido** [comment]
(repro is commit bc3ed50e3273e5c39c3db8d8be270c0237cf87a2)

As far as the error goes, it is `./examples/pattern-matching/PatternMatching.fst(552,0-570,25): (Error) Inconsistent implicit qualifier (see also ./examples/pattern-matching/PatternMatching.fst(569,59-569,63))`, which is bizarre. It arises when checking that implicits where solved, and typechecking a solution.

As for the slowness, the proofterm generated by the tactic (which, note, succeeds) is absolutely huge, and seems to contain a lot of redexes. While with the extra bind, it is much smaller.

Smells like funky normalizer business.

**Comment by mtzguido** [comment]
Also caused by tactic re-typechecking, which is now gone.
