### ISSUE TITLE
Using projectors from qualified modules

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1289]
Take this example
```
module M1

type myrecord = { myx : int }
```
```
module M2

module M = M1

let f (r : M1.myrecord) : int =
    r.myx
```
This fails with `./M2.fst(6,6-6,9): (Error) Identifier not found: [myx]` at desugaring time. This succeeds in F# for example.

Is there a deep reason why this fails? Will look into it later for myself.

**Comment by tahina-pro** [comment]
In OCaml, this would work but produce a warning:
```
        OCaml version 4.02.3

# module M1 = struct type t = { u : unit } end 
  ;;
module M1 : sig type t = { u : unit; } end
# let f (m: M1.t) = m.u
  ;;
Characters 20-21:
  let f (m: M1.t) = m.u
                      ^
Warning 40: u was selected from type M1.t.
It is not visible in the current scope, and will not 
be selected if the type becomes unknown.
val f : M1.t -> unit = <fun>
```

**Comment by msprotz** [comment]
the way this works in OCaml is that in addition to unification, there is some sort of bidirectional type propagation, down from the parameters, and up from the return type, that allows you to do that sort of things

the unification rule for records requires you to know, from the field, the type of the left-hand side without ambiguities...

note that our extracted files somehow trigger warning 40 already, all over the place

**Comment by mtzguido** [comment]
Ha, I actually had no clue that one could do:
```
let f (r : M1.myrecord) : int =
    r.M.myx
```

I guess my question was read as "why can't I write this which is shorter" instead of "why is this impossible" :). I definitely don't mind this. I'll close the issue...
