### ISSUE TITLE
Some implicits that are wrongly inferred

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#129]
I've double-checked and in `stlc_cbv_db_parsubst.fst` it is still the case that some implicits are wrongly inferred. It's hard to see any big difference to `stlc_strong_db_parsubst.fst`, where as we saw, the implicits could be inferred correctly. The code looks like this:
```
val substitution_preserves_typing :
      x:var -> #e:exp -> #v:exp -> #t_x:ty -> #t:ty -> #g:env ->
      h1:rtyping empty v t_x ->
      h2:rtyping (extend g x t_x) e t ->
      Tot (rtyping g (subst_beta_gen x v e) t) (decreases e)
let rec substitution_preserves_typing x e v t_x t g h1 h2 =
...
  | TyApp #g' #e1 #e2 #t11 #t12 h21 h22 ->
     (* CH: implicits don't work here, why? *)
    (TyApp #g #(subst_beta_gen x v e1) #(subst_beta_gen x v e2) #t11 #t12
       (substitution_preserves_typing x h1 h21)
       (substitution_preserves_typing x h1 h22))
```
and after removing the explicitly passed implicits
```
...
  | TyApp h21 h22 ->
    (TyApp (substitution_preserves_typing x h1 h21)
           (substitution_preserves_typing x h1 h22))
```
it fails like this:
```
Error stlc_cbv_db_parsubst.fst(230,0-248,3): The following problems were found:
	Subtyping check failed; expected type _45028:(rtyping (extend ('e11199 x e v t_x t g h1 h2 _45645 _45646 _45647 _45648 _45649 h21 h22) x t_x) _45646 (TArrow _45648 _45649)){(%[_45646] << %[e])}; got type (rtyping _45645 _45646 (TArrow _45648 _45649)) (stlc_cbv_db_parsubst.fst(245,43-245,46))
```

Anyway, not high priority, just wanted to file it for later :)

**Comment by catalin-hritcu** [comment]
Here is one more example of implicits being wrongly inferred; taken from `lambda_omega.fst`:
```
val kinding_tequiv : #g:env -> #t1:typ -> #t2:typ -> #k:knd -> h:(tequiv t1 t2) ->
      Tot (xiff (kinding g t1 k) (kinding g t2 k)) (decreases h)
let rec kinding_tequiv g _ _ k h =
  match h with
...
  | EqTran #t1 #t2 #t3 h1 h2 ->
     let Conj ih11 ih12 = kinding_tequiv h1 in
     let Conj ih21 ih22 = kinding_tequiv h2 in
     Conj #(kinding g t1 k -> Tot (kinding g t3 k))
          #(kinding g t3 k -> Tot (kinding g t1 k))
          (fcomp ih11 ih21) (fcomp ih22 ih12)
(* This should work
     Conj (fcomp ih11 ih21) (fcomp ih22 ih12)
but instead we get this subtyping error for the second conjunct:
Subtyping check failed; 
expected type ((kinding _1019 _1023  _1025) -> Tot (kinding _1019 _1021  _1025)); 
     got type ((kinding _1019 _33555 _1025) -> Tot (kinding _1019 _33555 _1025))
(lambda_omega.fst(372,28-372,45)) *)
```
I'm starting to get more and more convinced that turning off subtyping on demand for some arguments would be a great thing, as it might fix such problems, right?

**Comment by catalin-hritcu** [comment]
Now that we have a way to turn off subtyping it would be nice to investigate whether is solves these problems, and maybe the original problem was somehow justified (not a bug in subtyping).

**Comment by catalin-hritcu** [comment]
This still occurs, even if using "=" for the proof arguments in the definition of `substitution_preserves_typing".

**Comment by vkanne-msft** [comment]
Catalin, can you kindly reverify this issue with universes ?

**Comment by catalin-hritcu** [comment]
Eventually yes, but it will take a while (some weeks at least).

**Comment by catalin-hritcu** [comment]
Could confirm that this problem no longer appears in `StlcCbvDbParSubst.fst`. For `LambdaOmega.fst` the code that caused this is already gone. Closing.
