### ISSUE TITLE
Typechecker rejects addition of implicit argument, but infers the same value when argument is missing

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1291]
There's another fishy thing happening on the `repeat'` line of the example posted in https://github.com/FStarLang/FStar/issues/1287 (there's a FIXME on that line).

Basically, there's a call to `repeat'`, which has signature `#a → …`.  If I add the implicit argument (`#unit`) to the call to `repeat'`, then typechecking fails:

```
Expected expression of type "FStar.Tactics.Effect.tactic ((*?u1778*) _ a b c y y y)"; got expression "Prims.unit" of type "Type0"
```

But if I print the full term after leaving the implicit argument out, then it shows `#Prims.unit` was inferred.

Am I missing something easy?

**Comment by mtzguido** [comment]
This was also due to tactic re-typechecking, seems gone now, so closing.
