### ISSUE TITLE
norm_step accepts to feed invalid input to the normalizer

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1299]
The normalizer assumes that the terms it gets won't contain monadic applications, but the norm_step tactic doesn't respect that precondition.  Here's a concrete example:

```
module Test

open FStar.Tactics

let id () : Tac unit = ()

let failing () : Tac unit = fail "Uh oh" ()

let make_term : tactic term =
  tt_tm <-- quote ();
  id_tm <-- quote id;
  failing_tm <-- quote failing;
  unit_tm <-- quote unit;
  let binder = fresh_binder unit_tm in
  return (pack (Tv_Abs binder (mk_app id_tm [(mk_app failing_tm [(tt_tm, Q_Explicit)], Q_Explicit)])))

// This fails, as expected
let test : unit =
  assert_by_tactic True
    (tm <-- make_term;
     print (term_to_string tm);;
     t <-- unquote #(tactic unit) tm;
     t)

// This succeeds!
let test : unit =
  assert_by_tactic True
    (tm <-- make_term;
     normalized_tm <-- norm_term [delta] tm;
     print (term_to_string normalized_tm);;
     t <-- unquote #(tactic unit) normalized_tm;
     t)
```

This starts by making a term, namely `fun _ -> id (failing ())`, which applies `id` to an effectful function `failing`.  Then it unquotes it and tries to run it, which properly fails.

The second example does the same, but adds a normalization step to the mix. This step simplifies the term to `fun _ -> (() <: Prims.PURE Prims.unit) <: Prims.unit`.  Note how the effectful code was erased.

Spotted with @kyoDralliam

**Comment by mtzguido** [comment]
Whoops, interesting! Thanks for reporting. I assume typechecking the term before normalizing is the solution? That seems to work on my end, but you guys might know better :).

Kind of related:

Something annoying about that is that we need an environment to typecheck the term, which is not needed for normalization (there is an environment needed, but not for the binders, so I was just using the main tactic context).

I'll make `norm_term` (or a more basic `norm_term_raw`) take an environment, so we can choose the main tactic context or the current goal's one (note that we could call `norm_term` without any goal) at will. But what should the default be? I think the current goal, but I'd appreciate some input if you differ.

**Comment by cpitclaudel** [comment]
> I'll make norm_term (or a more basic norm_term_raw) take an environment, so we can choose the main tactic context or the current goal's one (note that we could call norm_term without any goal) at will. But what should the default be? I think the current goal, but I'd appreciate some input if you differ.

How does one get access to the current tactic context? (Can you do that?)
If you can't, it'd make sense for that to be the default, though I would indeed prefer for the goal's context to be the default.

**Comment by mtzguido** [comment]
(Some comments about this issue in #1285, because I mixed them up)

This should now be fixed in master, with the solution we discussed. There's also a new `top_env` tactic to return the initial tactic environment.
