### ISSUE TITLE
Functions with inline pre-/post-conditions

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1306]
This is a total noob question but it's been nagging me for a few days now:

Instead of 

```
let f (x:int{x <= 2}): Tot (y:int{y<=4}) = op_Multiply 2 x
```

my brain keeps wanting to type

```
let f (x:int): Tot (y:int)
    (requires (x <= 2))
    (ensures (y <= 4))
  = op_Multiply 2 x
```

(with or without the `Tot`). Is there another way that allows the declaration, specification and definition of a function in a single `let ...`, or will I have to stick to complicated `{...}`s and/or separate lemmas? Is there perhaps another effect I'm not aware of yet?

**Comment by mtzguido** [comment]
The `Pure` effect does what you want:
```
let f (x:int): Pure int
    (requires (x <= 2))
    (ensures (fun y -> y <= 4))
  = op_Multiply 2 x
```

**Comment by wintersteiger** [comment]
Sweet, thanks for the quick reply! That's probably the only effect I didn't try... :-)
