### ISSUE TITLE
Typechecker is not idempotent

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1307]
Running the typechecker twice on a term, as in
```
let t, _ ,_ = tc_term env t in
[... ]
let t, _ ,_ = tc_term env t in
```
will cause all sorts of weirdness, in particular double `Meta_monadic` and `Meta_monadic_lift` annotations, which in the case of lifts are inconsistent (consider `lift {pure -> tac} (lift {pure -> tac} e)`)

One particular culprit is this case in `tc_maybe_toplevel_term`
```
   | Tm_meta(e, Meta_monadic _) ->
     (* KM : This case should not happen when typechecking once but is it really *)
     (* okay to just drop the annotation ? And what about Meta_monadic_lift then ? *)
     tc_term env e
```
@kyoDralliam is indeed right that this is not correct, but no problems seem to arise when we only typecheck once. If we have some subterm `e` that needs an annotation, it will be added again if we re-typecheck since we're just ignoring the existing one.

This was the (hopefully single) cause for issue #1272  in tactics, where we were re-typechecking the reified tactics just before running, as a defensive check, messing up monadic annotations. I've simply disabled that for now, but this likely needs a proper fix.

**Comment by catalin-hritcu** [comment]
@aseemr can probably confirm that the typechecker is not idempotent. The `aseem_two_phase_experiment` seems mostly about this.

**Comment by mtzguido** [comment]
Right, sorry if this was well-known, I was just very surprised by it.

**Comment by aseemr** [comment]
@mtzguido, closing this issue since 2-phase tc is the default, so hopefully the issues you observed are fixed. Please reopen if something remains.
