### ISSUE TITLE
Inferring terms (not just types) like in Coq

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#131]
We often have parameters that can't be inferred in _all_ contexts, but which _sometimes_ can be inferred, and in that case it would be nice to be able to write `_` like in Coq, or some other wildcard.

**Comment by nikswamy** [comment]
I thought this was already possible. Apparently not ... will fix.

**Comment by catalin-hritcu** [comment]
This seems to work now:
```
val id : a:Type -> a -> Tot a
let id x = x

let temp = id _ 42
```
but only for inferring types, not also values like in Coq:
```
val foo : unit -> Tot unit
let foo () = ()

let temp' = foo _
```
this causes the following error:
```
fstar.exe bug131.fst 
bug131.fst(11,16-11,17) : Error
Expected an expression; got a type
```

**Comment by catalin-hritcu** [comment]
This still fails, but I'm not sure how it's supposed to work:
```
[hritcu@detained bug-reports]$ fstar.exe bug131.fst
./bug131.fst(11,16-11,17): (Error) Failed to resolve implicit argument of type 'unit' introduced in ?39097 because user-provided implicit term
Verified module: Bug131 (5 milliseconds)
1 error was reported (see above)
```

Another instance of a place where Coq can infer a term but F\* can't is this:
https://github.com/FStarLang/FStar/blob/master/examples/metatheory/StackMachine.fst#L179

Are there any instances where this actually works in F\*?

**Comment by catalin-hritcu** [comment]
No changes here, still not working.

**Comment by mtzguido** [comment]
This seems to have improved. Catalin's example fails with
```
./examples/bug-reports/bug131.fst(11,16-11,17): (Error) Failed to resolve implicit argument of type 'Prims.unit' introduced in (*?u0*) _
```
which could be fixed by unifying all uvars of type `unit` to `()`.
Further, this works
```
val f :x:int -> squash (x+1 > x)
let f x = ()

val g : squash (6 > 5)
let g = f _
```

**Comment by nikswamy** [comment]
Implicit inference in StackMachine.fst works now.

We could have an eta rule in the unifier for solving case inductives, like in Agda. But that's not planned any time soon. 

If there are specific issues with inference, please open separate issues.

Closing.
