### ISSUE TITLE
OCaml build is failing with latest version of pprint

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1313]
```
Error: Files src/prettyprint/ml/FStar_Pprint.cmx
       and ~/.opam/4.02.3/lib/pprint/PPrintLib.cmxa
       make inconsistent assumptions over implementation PPrintEngine
```
The error disappears after `opam install pprint.20140424`, and reappears after `opam install pprint20171003`

**Comment by catalin-hritcu** [comment]
@A-Manning Have you tried a `make clean`? or `git clean -fdx .`? (warning: you will lose all local changes with the latter)

**Comment by ad-l** [comment]
This seems like a build sanity problem, `make clean` should do the trick.
