### ISSUE TITLE
Excercises in tutorial broken?

### ISSUE THREAD

**Issue by jaybosamiya** [FStarLang/FStar#1314]
Is the [tutorial](https://fstar-lang.org/tutorial/) excercise 4c broken on the online editor? It seems to verify fine offline on my system
```
$ fstar --version
F* 0.9.5.0
platform=Linux_x86_64
compiler=OCaml 4.05.0
date=2017-08-23T11:19:43-07:00
commit=fa9b1fd
$ fstar Ex04c.fst
Verified module: Ex04c (291 milliseconds)
All verification conditions discharged successfully
```

Online it gives the error:
```
Ex04c(16,26-16,75): (Error) Expected type "uu___161949:Prims.squash Prims.l_True -> Prims.Tot Type0"; but "Prims.b2t (Ex04c.mem x (Ex04c.append l1 l2)) <==> Prims.b2t (Ex04c.mem x l1 || Ex04c.mem x l2)" has type "Type0"
Ex04c(16,26-16,75): (Error) Expected type "uu___160980:Prims.squash Prims.l_True -> Prims.Tot Type0"; but "Prims.b2t (Ex04c.mem x (Ex04c.append l1 l2)) <==> Prims.b2t (Ex04c.mem x l1 || Ex04c.mem x l2)" has type "Type0"
Ex04c(18,0-21,32): (Error) could not prove post-condition(Also see: /var/fstar/ulib/prims.fst(270,28-270,35))
Ex04c(18,8-18,18): (Error) Expected type "uu___162969:Prims.squash Prims.l_True -> Prims.Tot Type0"; but "Prims.b2t (Ex04c.mem x (Ex04c.append l1 l2)) <==> Prims.b2t (Ex04c.mem x l1 || Ex04c.mem x l2)" has type "Type0" (see also Ex04c(16,26-16,75))
/var/fstar/ulib/FStar.Pervasives.fst(219,11-219,52): (Error) Expected type "uu___123420:Prims.squash Prims.l_True -> Prims.Tot Type0"; but "forall (x:FStar.Pervasives.Native.option a). Prims.b2t (None? x) \/ Prims.b2t (Some? x)" has type "Type0"
/var/fstar/ulib/FStar.Pervasives.fst(221,4-221,16): (Error) Expected type "uu___148985:Prims.squash Prims.l_True -> Prims.Tot Type0"; but "forall (x:FStar.Pervasives.Native.option a). Prims.b2t (None? x) \/ Prims.b2t (Some? x)" has type "Type0" (see also /var/fstar/ulib/FStar.Pervasives.fst(219,11-219,52))
Verified module: Ex04c (700 milliseconds) 6 errors were reported (see above)
```

For quick reference, the `Ex04c.fst` is:
```
module Ex04c
//mem

val append : list 'a -> list 'a -> Tot (list 'a)
let rec append l1 l2 = match l1 with
  | [] -> l2
  | hd :: tl -> hd :: append tl l2

val mem: #a:eqtype -> a -> list a -> Tot bool
let rec mem #a x xs =
  match xs with
  | [] -> false
  | hd::tl -> hd=x || mem x tl

val append_mem:  #a:eqtype -> l1:list a -> l2:list a -> x:a
        -> Lemma (ensures (mem x (append l1 l2) <==>  mem x l1 || mem x l2))

let rec append_mem #a l1 l2 x =
  match l1 with
  | [] -> ()
  | hd::tl -> append_mem tl l2 x
```

*Ninja edit:* Seems like lots of the exercises that worked fine a couple of days ago seem to be broken. Must be a recent change.

**Comment by nikswamy** [comment]
Antoine? Any idea what's up with the online editor here?

**Comment by tluyben** [comment]
Hope it comes back soon; I am doing the online tutorial and on my tablet I cannot put an install of F*.

**Comment by jaybosamiya** [comment]
Possibly more useful minimum working example:

For `Test.fst` containing only:
```
module Test
```
the error given is
```
/var/fstar/ulib/FStar.Pervasives.fst(219,11-219,52): (Error) Expected type "uu___123420:Prims.squash Prims.l_True -> Prims.Tot Type0"; but "forall (x:FStar.Pervasives.Native.option a). Prims.b2t (None? x) \/ Prims.b2t (Some? x)" has type "Type0"
/var/fstar/ulib/FStar.Pervasives.fst(221,4-221,16): (Error) Expected type "uu___148985:Prims.squash Prims.l_True -> Prims.Tot Type0"; but "forall (x:FStar.Pervasives.Native.option a). Prims.b2t (None? x) \/ Prims.b2t (Some? x)" has type "Type0" (see also /var/fstar/ulib/FStar.Pervasives.fst(219,11-219,52))
Verified module: Test (3 milliseconds) 2 errors were reported (see above)
```

Specifically, the `invertOption` at https://github.com/FStarLang/FStar/blob/master/ulib/FStar.Pervasives.fst#L217 seems to be what is breaking. The only (recent) change I see nearby is https://github.com/FStarLang/FStar/commit/0e8a1af37e8ad266da2d3716130a1d847e682a45.

The reason that that commit feels to be not the one breaking it though, is that lines 759 and 761 of https://github.com/FStarLang/FStar/blob/master/src/tosyntax/FStar.ToSyntax.ToSyntax.fs#L759 are exactly the same, and haven't been changed for a few months, except for the line that adds the deprecation warning.

Unfortunately, I am not yet well versed enough to understand why this might have broken it. I am just trying to help triage it a little faster :)

**Comment by mtzguido** [comment]
That error is caused by the fix to #57, the postcondition for Lemmas are now expected to be thunked, but this is made transparent by the desugaring, so users shouldn't ever see this.

What I think is going on is that the F* binary on the server is old, but parsing the new prims.fst. So it sees that lemma expects a thunked postcondition, and it lacks the needed extra desugaring to add it automatically, thus the error.

So, seems the server just needs a kick.

**Comment by jaybosamiya** [comment]
Ah, seems like the server kick fixed it. Thanks everyone :)

I'm closing this issue, since I think it has been resolved.

**Comment by mtzguido** [comment]
Cool!

Thanks for reporting, and please do it again if it breaks :)
