### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1337]
`<input>(664,81-664,112): (Info) Subtyping check failed; expected type x:a -> Prims.Lemma Prims.unit; got type x:a -> Prims.Lemma Prims.unit (see also ./prims.fst(52,21-83,40))`

(expected is the same as actual). Is this a known issue or should I save a bug repro?

**Comment by mtzguido** [comment]
It's known. There's a likely an actual difference but it's just not being printed.

You can use `--print_effect_args` (and possibly more printing flags) to see more information. Maybe we should make `Lemma` always print its arguments, though.

**Comment by wintersteiger** [comment]
Sweet, thanks for the hint! It does indeed show a whole bunch of additional args with that option.

**Comment by markulf** [comment]
I think this is a duplicate of another issue. I don't think this is resolved. Ideally F* would detect that the error message is unhelpful and would add details automatically without requiring the user to add the flat? Also, for large types, we likely would want F* to zoom in and highlight the differences. 

As parsing error messages like this, but sometimes covering half a page can take up a lot of time when debugging a failing proof, it I suspect this could improve usability quite a bit.

**Comment by markulf** [comment]
https://github.com/FStarLang/FStar/issues/1225
