### ISSUE TITLE
Can't compile function like "let rec test n = n/n"

### ISSUE THREAD

**Issue by hungvq00390** [FStarLang/FStar#134]
Display Unexpected exception :(
Can't compile

**Comment by catalin-hritcu** [comment]
Works for me. Did you take this out of context? What version of F* are you using?

**Comment by hungvq00390** [comment]
I checked on this website
http://rise4fun.com/FStar/tutorial/jsStar

**Comment by catalin-hritcu** [comment]
That's old stuff that no longer has anything to do with the current version of F*. You can find the most recent F* tutorial, together with a new online editor here: https://www.fstar-lang.org/tutorial/

@nikswamy Seems that the old tutorial / online editor confuses people, how about taking it down (and storing it somewhere in this repo if we want to still reference to it)?

**Comment by catalin-hritcu** [comment]
@nikswamy We don't have a new JsStar tutorial though (only saw that part now), so maybe just add a disclaimer with a link to the new F*? I don't know what's the best way to migrate such things.

**Comment by nikswamy** [comment]
Sorry for the confusion ... will take down the old stuff today.
