### ISSUE TITLE
Failed to resolve implicit argument for a simple code

### ISSUE THREAD

**Issue by aseemr** [FStarLang/FStar#1340]
```
module Test

assume type t (n:int) :Type0

let foo #n (x: t n) = x

private let foo' = foo
```

gives an error:

```
aseemr@ASEEMR-LT2 ~/FStar
$ fstar.exe Test.fst
.\Test.fst(9,8-9,22): (Error) Failed to resolve implicit argument of type 'Prims.int' in the type of foo' (x:Test.t (*?u0*) _ -> Prims.Tot (Test.t (*?u0*) _))
1 error was reported (see above)
```

It seems like the typechecker is not adding the implicit argument to the signature of `foo'`.

**Comment by mtzguido** [comment]
Maybe this is expected? Without an annotation, F* wouldn't be able to tell if `foo'` is just `foo` or the application of `foo` to some implicit int, which is also perfectly valid.

When I really do want the function, my usual workaround is `let foo' = fun #n -> foo #n`

**Comment by nikswamy** [comment]
This is indeed the expected behavior. See:
https://github.com/FStarLang/FStar/blob/master/CHANGES.md

The section on "Basic type-checking and inference"
