### ISSUE TITLE
another fold failure

### ISSUE THREAD

**Issue by zeta1999** [FStarLang/FStar#1344]
```F#
module Bug02

// RB tree from examples
type color =
  | R
  | B

type rbtree (k: eqtype) v =
  | E
  | T: col:color
       -> left: rbtree k v
       -> key: k
       -> value: v
       -> right: rbtree k v
       -> rbtree k v

val rbfold: (#a:Type) -> (#k:eqtype) -> (#v:Type) ->
             (f: a -> k -> v -> Tot a) -> (acc: a) -> (t: rbtree k v)
             -> Tot a
let rec rbfold (#a) (#k) (#v) f acc t = match t with
    | E -> acc
    | T _ l ky va r ->
      let (acc1:a) = rbfold f acc l in
      let (acc2:a) = f acc1 ky va in
      let (acc3:a) = rbfold f acc2 r in
      acc3
```

```
C:\Users\[...]>fstar.exe --verify_module Bug02 bug02.fst
[31;1m.\bug02.fst(25,35-25,36): (Error) Subtyping check failed; expected type (t:Bug02.rbtree k v{ Prims.LexCons k (Prims.LexCons acc2 (Prims.LexCons t Prims.LexTop)) <<
    Prims.LexCons k (Prims.LexCons acc (Prims.LexCons t Prims.LexTop)) }); got type Bug02.rbtree k v (see also .\bug02.fst(20,0-26,10))
[0m[31;1mVerified module: Bug02 (933 milliseconds)
[0m[31;1m1 error was reported (see above)
[0m
```
May I ask... How do you test drive the project? Would you be interested in having some 'clean' base support lib with simple and still useful examples? (i.e. with parametrized types, like 'map k v')

**Comment by mtzguido** [comment]
The error is exactly the same as #1343, you need to annotate a decreases clause over `t`. For the other question (if I understood correctly) you can find many many examples in `ulib/` and `examples/`.

**Comment by zeta1999** [comment]
YES! 
works with the same trick as one previous one
(I found by myself in fact)

####
module Bug02

// RB tree from examples
type color =
  | R
  | B

type rbtree (k: eqtype) v =
  | E
  | T: col:color
       -> left: rbtree k v
       -> key: k
       -> value: v
       -> right: rbtree k v
       -> rbtree k v

val rbfold: (#a:Type) -> (#k:eqtype) -> (#v:Type) ->
             (f: a -> k -> v -> Tot a) -> (acc: a) -> (t: rbtree k v)
             -> Tot a (decreases t)
let rec rbfold (#a) (#k) (#v) f acc t = match t with
    | E -> acc
    | T _ l ky va r ->
      let (acc1:a) = rbfold f acc l in
      let (acc2:a) = f acc1 ky va in
      let (acc3:a) = rbfold f acc2 r in
      acc3

**Comment by zeta1999** [comment]
>> For the other question (if I understood correctly) you can find many many examples in ulib/ and examples/.

I would suggest something in the style of the 'stl' (less many examples, but more 'generic usage' ones,
and, ... some kind of standard around it)
Fyi the source of the 'false bugs' is me trying to adapt the RBtree example with generics so I can actually
start using f* in simple scripts - scripts that do work all the time :-).
