### ISSUE TITLE
Subtyping on refinement types is not robust w.r.t type abbreviations

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1345]
@fournet  reports:

```
module Test
let pos = n:nat {n>0} 
type t0 = n: pos -> unit
type t1 = n: nat {n>0} -> unit

let _ = assert_norm (t0 == t1)
let f (x:t0): t1 = fun n -> x n

let g (x:t0): t1 = x // failing
```

**Comment by nikswamy** [comment]
This is quite tricky, particularly in the interaction with the inference of implicit arguments (no great surprise).

Consider, in addition to the original report, this program:

```
module Test2
type t (a:nat) = x:nat{x <= a}
let foo #a (x:t a{x < 20}) = ()
let bar (y:t 17{y < 10}) = foo y
```

In order for `Test2` to succeed, we need to infer the implicit argument in the application of `foo y` on the last line. The way this works is by 

1. producing a subtyping problem `y:t 17{y < 10} <: x:t ?a{x < 20}`, for a fresh unification variable `?a`
2. following the structure of the refinements, peeling them back one at at type to show
    a.  `y < 10 ==> y < 20`
    b. `t 17 <: t ?a` ... and solving this problem by  matching the head symbol `t` and then unifying `?a` with `17`.

Note, if instead of proceeding on the structure of the refinements, we just unfolded definitions in step 1, we'd be lost trying to solve for `?a`.

Pretty straightforward, but it's in direct tension with what's needed for the first example, `Test`. By following this strategy in `Test`, we end up doing comparing `t0 <: t1` and then `pos <: n:nat{n > 0}`, or equivalently `n:pos{True} <: n:nat{n > 0}`. Now if you follow the same strategy as the one described previously, proceeding on the structure of the refinements, this is doomed. Because you end up trying to prove that `True => n > 0` and then `pos <: nat`. 

So, the solution that I'm trying for is a compromise:

When comparing `x:t{phi} <: y:s{psi}`, if both side have no unsolved unification variables, then this does not interact with implicit argument inference and we'll just unfold both sides to the form `x:tc{phi'} <: y:sc{psi'}`, where `tc` and `sc` are type constants.

Otherwise, we proceed on the structure of the refinements.

Still trying to sort out a few regressions ...

**Comment by mtzguido** [comment]
Made a revision to this logic after Yao (@lastland) found another instance of this bug, which I at first misjudged to be #1470.

Now, we reuse `head_matches_delta` to bring the bases of both refinements to a common head (if possible!) and only then break the problem down in the two parts of equating the base and refinements. This seems to work neatly for the previous examples, Yao's new one, and a recent regression in miTLS' `Pkg.fst`. As well as the entire regression suite, of course.

Relevant commit: 89e83e9f3349398c2a9b2caaed8969c0d27008b2, coming to master soon.

**Comment by lastland** [comment]
@mtzguido Great! Thanks. I will be working with that branch for now.

**Comment by mtzguido** [comment]
Don't trust my branch too much though :) I routinely trash it...
