### ISSUE TITLE
Incompatible version for unification variable

### ISSUE THREAD

**Issue by Caroline-xinyue** [FStarLang/FStar#1351]
Error Message: 
Normalization failed with error Failure("Incompatible version for unification variable: current version is 503.160; got version 503.162")Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error. Failure("Incompatible version for unification variable: current version is 503.160; got version 503.162")

Code on reverse in linear time:
```
module LinearReverse

type vector (a:Type) : nat -> Type =
   | Nil : vector a 0
   | Cons : hd:a -> #n:nat -> tl:vector a n -> vector a (n + 1)

val reverseLinear: #a:Type -> #n:nat -> vector a n -> Tot (vector a n)
let rec reverseLinear #a #n v =
  let rec reverseFast #a #m #n v acc = match v with
      | Nil          -> acc
      | (Cons hd tl) -> reverseFast tl (Cons hd acc)
  in reverseFast #a #n #0 v Nil
```

I saw some issues regarding this error message, just post another function that fails on this.

Any help is hugely appreciated!

**Comment by mtzguido** [comment]
This seems fixed in the latest master version (since a few days ago, I think). There's an error there, but it is:
`
(Error) (*?u320*) _ a a m n tl is not equal to the expected type (*?u320*) _ a a m n v + 1
`
Pointing to `(Cons hd acc)`. This is an inference failure, and annotating the function fixes it. Either as an inner let as you have
```F#
val reverseLinear: #a:Type -> #n:nat -> vector a n -> Tot (vector a n)
let reverseLinear #a #n v =
    let rec reverseFast (#a:Type) (#m #n:nat) (v:vector a m) (acc : vector a n) : vector a (n + m) = match v with
      | Nil -> acc
      | Cons hd tl -> reverseFast tl (Cons hd acc)
    in reverseFast #a #n #0 v Nil
```
or moving your auxiliary function to a top-level
```F#
val reverseFast : #a:Type -> #m:nat -> #n:nat -> vector a m -> vector a n -> vector a (n + m)
let rec reverseFast #a #m #n v acc = match v with
  | Nil -> acc
  | Cons hd tl -> reverseFast tl (Cons hd acc)

val reverseLinear: #a:Type -> #n:nat -> vector a n -> Tot (vector a n)
let reverseLinear #a #n v = reverseFast #a #n #0 v Nil
```

So unsure there's an actual problem with this particular code.

**Comment by Caroline-xinyue** [comment]
I haven't run into the error in other cases, but annotating the helper function reverseFast fixed it. Thanks for the quick response!
