### ISSUE TITLE
Bad extraction of UInt8.t in match

### ISSUE THREAD

**Issue by bpowers** [FStarLang/FStar#1356]
The following code passes validation, but when extracted the OCaml compiler fails:

```
module Test

module U8 = FStar.UInt8

val test_all:
  i:UInt8.t{0 < (U8.v i) /\ (U8.v i) <= 64} ->
  Tot (bool)
let rec test_all i =
  let open FStar.UInt8 in
  match i with
  | 0uy -> true
  | _ -> (let m = i -^ 1uy in
         true && test_all m)

val test: unit -> Tot (bool)
let test () =
  test_all 64uy
```

OCaml says:

```
OCAMLPATH="/home/bpowers/src/fstar_testcase/dependencies/FStar/bin" ocamlfind opt -package fstarlib -linkpkg -g  -thread -package batteries,zarith,stdint -w -20-26-3-8-58 -w -8-20-26-28-10 -I test-spec  test-spec/Test.ml -o test.exe
File "test-spec/Test.ml", line 5, characters 26-49:
Error: Unbound value FStar_UInt8.__uint_to_t
Hint: Did you mean uint_to_t?
```

Maybe this is intentional (or I am missing something), but I would expect the above to work (if I replace the above with an if-statement with the same logic, everything behaves as intended).

I have a git repo for reproducing this here: https://github.com/bpowers/fstar-extraction-bug -- let me know if there is a better way to add this as a failing test case (or something?) here in FStar.

You should be able to reproduce by cloning and then running:

    $ FSTAR_HOME=$HOME/src/fstar KREMLIN_HOME=$HOME/src/kremlin make

This is using the current master branch of F* ( commit 512f4138bc0684ca8821d9db3a0489ec34017b82 )

Let me know if there is more info you need, or if I'm doing something obviously wrong!

**Comment by mtzguido** [comment]
This now works, after having added `__uint_to_t` to the ML realizations of integer libraries. (Though note this file only lax-checks, I think the match should be on `1` instead of `0` to be correct, and it needs a decreases clause). Thanks!
