### ISSUE TITLE
Off-by-one error in createL in FStar.Buffer.fst

### ISSUE THREAD

**Issue by kkohbrok** [FStarLang/FStar#1363]
In the precondition it's
`normalize (FStar.List.Tot.length init < UInt.max_int 32)`
where it should be
`normalize (FStar.List.Tot.length init <= UInt.max_int 32)`,
since `UInt.max_int` is already `pow2 32 - 1`.

**Comment by mtzguido** [comment]
Fixed by c94b0731e6b4a62f847e192e9da1696fba3128f4 (and see PR #1369)
