### ISSUE TITLE
Document how to use the ocaml backend

### ISSUE THREAD

**Issue by hungvq00390** [FStarLang/FStar#137]
I try with below code:
fstar --codegen Ocalm ex1a-safe.fst --prims D://prims.fst
Can i have execute file ?

**Comment by catalin-hritcu** [comment]
Sorry for the delay, we had an important deadline yesterday. The correct flag is `--codegen OCaml` (different capitalization). The command output should look something like this
```
[hritcu@detained metatheory]$ ../../bin/fstar.exe --codegen OCaml stlc_cbv_named.fst
OCaml: StlcCbvNamed
Gen Code: StlcCbvNamed
Lax type-checked module: Prims
Lax type-checked module: StlcCbvNamed
```
which means that a file called `StlcCbvNamed.ml` was generated. Running `ocamlc` on that file should give you an executable. If you use any primitive you will need to link against the fstar support library when calling `ocamlc`.

@ad-l @karthikbhargavan: Can you give some precise instructions about how to do that?

**Comment by markulf** [comment]
This seems resolved then? Was a question of getting a useful error message.

**Comment by catalin-hritcu** [comment]
That too, yes, but also we don't have any documentation about the backend. We should still try to improve that.

**Comment by markulf** [comment]
Good point. Should this go into the Tutorial? Maybe some of the examples should have a section on how to fill in the missing holes so they can be compiled and executed with some care devoted to cross platform issues, if there are any?

I remember seeing an executable example in the tutorial, but that seems gone now.

**Comment by ad-l** [comment]
Yes, there is still a lot to do on documenting the backends and libraries. We can discuss it in the next F* meeting.

**Comment by catalin-hritcu** [comment]
This keeps coming up. @jkzinzindohoue was asking about this the other day. If he got an answer it would be great if he could share it with the rest of us by adding some documentation.

**Comment by jkzinzindohoue** [comment]
Added to the README, you can try it.

2015-05-03 11:39 GMT+02:00 Catalin Hritcu <notifications@github.com>:
