### ISSUE TITLE
Termination of mutually recursive functions

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#138]
Currently, F* cannot prove this terminating:
```
val foo : l:list int -> Tot int
val bar : l:list int -> Tot int
let rec foo l = match l with
    | [] -> 0
    | x::xs -> bar xs
and bar l = foo l
```
In this very simple case, the definition of `bar` can be inlined ; when it is not the case, the best workaround I have found is to use the standard trick to have one single function:
```
type arg =
  | Foo : arg
  | Bar : arg

let rec foo_bar a l =
  match a with
    | Foo ->
       (match l with
          | [] -> 0
          | x::xs -> foo_bar Bar xs)
    | Bar -> foo_bar Foo l
```
and define a precedence on the arguments:
```
val arg_precede : arg -> Tot nat
let arg_precede a =
  match a with
    | Foo -> 0
    | Bar -> 1
val foo_bar : a:arg -> l:list int -> Tot int (decreases %[l;arg_precede a])
```
This trick might be used to make the first example work in F* without changing the kernel?

**Comment by ckeller** [comment]
See bug138.fst.

**Comment by nikswamy** [comment]
Nice report. This is already expressible in F* directly ... see my last commit.

**Comment by nikswamy** [comment]
For reference, here's how:

```
val foo : l:list int -> Tot int (decreases %[l;0])
val bar : l:list int -> Tot int (decreases %[l;1])
let rec foo l = match l with
    | [] -> 0
    | x::xs -> bar xs
and bar l = foo l
```

**Comment by ckeller** [comment]
Indeed, didn't think of that -- impressive!

**Comment by markulf** [comment]
Nice trick. :)

**Comment by ad-l** [comment]
Neat trick, but it needs to be documented

**Comment by markulf** [comment]
Lets add it to the tutorial!

**Comment by markulf** [comment]
Added a simple tutorial subsection and an example. Would be great to get feedback and help with wording by a PL person.
