### ISSUE TITLE
Z3 complains about wrong numbers of arguments

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1383]
Check out the `quic2c_parsers` branch of `mitls-fstar`, commit https://github.com/mitls/mitls-fstar/commit/61d1a6649d7646720258e8ab80e7a01a356d1d9f (and the everest branch `quic2c_parsers` for the other project hashes if needed). In `mitls-fstar/src/lowparse` run 

    fstar.exe --include $KREMLIN_HOME/kremlib --debug any LowParse.SLow.Bytes.fst

FStar/Z3 complain thusly:

```
Verifying implementation of LowParse.SLow.Bytes
<dummy>(0,0-0,0): (Warning 275) LowParse.SLow.Bytes: Unexpected output from Z3: (error "line 223145 column 44: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.Int.serialize32_u8 () Term)")
(error "line 223177 column 45: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.Int.serialize32_u16 () Term)")
(error "line 223345 column 45: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.Int.serialize32_u32 () Term)")
(error "line 232543 column 62: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.VLData.serialize32_bounded_integer_1 () Term)")
(error "line 232666 column 62: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.VLData.serialize32_bounded_integer_2 () Term)")
(error "line 232789 column 62: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.VLData.serialize32_bounded_integer_3 () Term)")
(error "line 233556 column 58: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.VLData.parse32_bounded_integer_2 () Term)")
(error "line 234071 column 58: Wrong number of arguments (1) passed to function (declare-fun LowParse.SLow.VLData.parse32_bounded_integer_4 () Term)")
```

The function called `LowParse.SLow.Int.serialize32_u8` in the corresponding SMT2 file is indeed declared to be a constant, when it should be a function. I think the consequence is unsoundness, because when Z3 returns unsat, it only proved that there is no constant, not that there is no function. 

Experts may be able to get an idea of what's going on by looking at the function names and the corresponding source definitions, but I had to start up Visual Studio to debug into it, but that threw assertion violations in my face. This may be a completely disjoint issue, but I patched it up for now as shown here: https://github.com/wintersteiger/FStar/commit/51f15b789b2311e682a259cfe58075b1bebb4cfe
(List.length us = 1 but List.length formals = 0). I expect my fix to be unsound too, I just wanted to get through to the actual problem I want to look at.

**Comment by tahina-pro** [comment]
Here is a more minimal example, without any dependencies:
```
module Te
let t (b: bool) : Tot Type0 = int → Tot int
let t' (b: bool) (f: t b) : Tot Type0 = ((x: int) → Pure int (requires ⊤) (ensures (λ y → ⊤)))
let f : t true = (λ x → x)
val g : t' true f
let g x = x
```
`F* reported issues in other files: [([cl-struct-fstar-issue warning ([cl-struct-fstar-location "<dummy>" 0 0 0 0]) "Te: Unexpected output from Z3: (error \"line 42060 column 16: Wrong number of arguments (1) passed to function (declare-fun Te.f () Term)\")"])]`

**Comment by tahina-pro** [comment]
If you remove the argument to `t`, then this message disappears.

**Comment by tahina-pro** [comment]
The message is also triggered by:
```
val f : t true
let f x = x
val g : t' true f
let g x = x
```
By contrast, the following code does not trigger that message
```
let h (x: ℤ) : Tot ℤ = x
let f : t true = h
val g : t' true f
let g x = x
```
(following a trick similar to the one I use to work around #1384 )

**Comment by nikswamy** [comment]
Cf. #1150

**Comment by nikswamy** [comment]
I have a fix in master. Would be great if you could try it out on your real examples and report back.

**Comment by tahina-pro** [comment]
I rechecked LowParse on miTLS quic2c_parsers with the latest F* master, and it works well, those Z3 errors disappeared. Thank you @nikswamy !

**Comment by nikswamy** [comment]
thanks for the bug report and concise repro! closing.

**Comment by nikswamy** [comment]
wrong reference in the commit message ... that commit was actually related to issue #1393
