### ISSUE TITLE
Inference of implicit arguments and definitions vs. assumptions

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/FStar#1384]
Consider the following code:
```
module U
let t (b: bool) : Tot Type0 = int → Tot int
let t' (#b: bool) (f: t b) : Tot Type0 = string
```
Then, the following successfully typechecks:
```
assume val f : t true
let g : t' f = "sou"
```
However, the following even fails to lax-typecheck (`h` succeeds, but not `k`):
```
val h : t true
let h x = x
let k : t' h = "oh"
```
`Failed to resolve implicit argument of type 'Prims.bool' in the type of k (U.t' U.h)`

Somehow it looks like `h` is unfolded in the type of `k` already at lax-typechecking time.
Is this expected?

**Comment by tahina-pro** [comment]
By contrast, the following successfully typechecks:
```
val u : (ℤ → Tot ℤ)
let u x = x
val v : t true
let v = u
let k : t' v = "ohu"
```

**Comment by tahina-pro** [comment]
This issue also happens with `--use_two_phase_tc true`

**Comment by aseemr** [comment]
All these example work with F* master, closing the issue.
