### ISSUE TITLE
Bug when mixing implicit arguments, recursion and totality

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#139]
The following code:
```
assume type A : Type
assume type B : Type
assume val f : #a:A -> b:B -> Tot bool
val bug : a:A -> b:B{f #a b} -> Tot unit
let rec bug a b = ()
```
returns the strange error `Expected expression of type "B"; got expression "a" of type "A"` at line 4, chars 10-11.

It works well if either:
- I do not use implicits;
- I remove `rec`; or
- I do not ask `bug` to be total.

**Comment by ckeller** [comment]
See examples/bug-reports/bug139.fst .

**Comment by catalin-hritcu** [comment]
This is still broken.
