### ISSUE TITLE
Recursion through modules

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1391]
A.fsti:
```f#
module A
val f : int -> int
```
B.fsti:
```f#
module B
val g : int -> int
```

A.fst:
```f#
module A
open B
let f x = g x
```

B.fst:
```f#
module B
open A
let g x = f x
```

This setup typechecks and extracts to diverging functions, which are marked as `Tot` and not even as `rec`. I'm not sure the result is compilable in OCaml, but this can clearly be used to prove `False` too.

**Comment by nikswamy** [comment]
yikes. nice catch! I see this as a bug in the dependence analysis.

**Comment by nikswamy** [comment]
No one has advocated for this flag. Closing
