### ISSUE TITLE
Qualifiers and interfaces in interactive mode 

### ISSUE THREAD

**Issue by fournet** [FStarLang/FStar#1393]
From emacs, the interface
```
module Foo
noextract val f: list nat -> list nat 
```
yields `The qualifier [assume noextract]` is not permissible for this element: ill-formed combination` and I can't go further. Building with the incremental Makefiles similarly fails. However, this file and its implementation  
```
module Foo
noextract let f x = 1::x
```
compile as expected using `fstar Foo.fsti Foo.fst --codegen Kremlin --extract Foo`. Is fstar too restrictive? More generally, where is the documentation for valid combinations of qualifiers vs interfaces? I tried `abstract noextract` and that did not go well.

**Comment by s-zanella** [comment]
I see no harm in allowing the `assume noextract` combination. It actually makes sense when one wouldn't want to extract an `assume val` as a declaration.

**Comment by nikswamy** [comment]
`assume noextract` is a permissible combination in F* master now.
