### ISSUE TITLE
admit() escapes

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1397]
@catalin-hritcu ran into this:
```
 let test () : Tot int =
    let x : nat = (admit () ; 5) in
    assert False;
    99
```
This succeeds. And while it has an `admit()`, and one could say all bets are off, it should probably fail as it is not scoped where we `assert False`.

I'm blaming the effect system, but I'm not sure. Note that there is no VC involved.

**Comment by nikswamy** [comment]
I don't think this is a bug. See the spec of Prims.admit: it intentionally discards the VC for the continuation.

**Comment by catalin-hritcu** [comment]
This seems like (1) super dangerous and (2) bad user experience. Don't think any human expects this behavior from admit.

**Comment by nikswamy** [comment]
Sorry, this is not changing. `admit` intentionally discards the VC of the continuation. We rely on that behavior heavily everywhere.
