### ISSUE TITLE
User-defined well-founded orderings

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#140]
Is there a mechanism to extend the *precedes* (`<<`) relation of F* with user-defined orders, that would have been proved well-founded?

**Comment by catalin-hritcu** [comment]
I don't think so, but I agree it would be nice to have, if at all possible. We would also need to be very careful, because the composition of two well-founded orders is not necessarily well-founded.

**Comment by nikswamy** [comment]
There is a mechanism: You can add an axiom ... 

```
assume Bad: 1 << 0
```

So,  it's possible to do ... but with extreme care, of course.

**Comment by ckeller** [comment]
It would be nice to also offer a mechanism to prove well-formedness.

**Comment by catalin-hritcu** [comment]
Currently, I can write Coq's definition of well-formedness using accessibility predicate (https://coq.inria.fr/library/Coq.Init.Wf.html) in F* and it is accepted:
```
type acc (a:Type) (r: (a -> a -> Type)) : a -> Type =
| AccIntro : x:a -> (y:a -> r y x -> acc a r y) -> acc a r x

type well_founded (a:Type) (r: (a -> a -> Type)) = x:a -> acc a r x
```
If this is still accepted after all checks are in place, then one will be able to prove well-formedness in F* the same way you would do it in Coq.

What will still be missing is a _safe_ mechanism that given such a well-formedness proof would partially change F*'s ambient well-founded order.

**Comment by ckeller** [comment]
Actually, I have started looking at what we can do in this direction, I just commited this in examples/wf/wf.fst . In run into problems when I try to prove termination: if I replace the definition of acc with
```
type acc (a:Type) (r:(a -> a -> Type)) (x:a) : Type =
  | AccIntro : (y:a -> r y x -> Tot (acc a r y)) -> acc a r x
```
F* returns an `Unexpected error : Bound term variable not found: _704`.

**Comment by catalin-hritcu** [comment]
The `Unexpected error` is of course a bug. The code is not correct either: no `Tot` required/allowed for type arrows.

**Comment by catalin-hritcu** [comment]
In any case, I don't think in F* there is any difference between uniform and non-uniform arguments to inductive relations. Is there? It's not like we're generating induction principles anything.

**Comment by ckeller** [comment]
Thanks about termination, sure, the bug was misleading me.

**Comment by ckeller** [comment]
Regarding parameters of inductive types, there could be a difference: the way I wrote it, AccIntro should be able to take one less argument.

**Comment by ckeller** [comment]
Coming back to Catalin's answer now I am less tired: it does make sense to write:
```
type acc (a:Type) (r:(a -> a -> Type)) (x:a) : Type =
  | AccIntro : (y:a -> r y x -> Tot (acc a r y)) -> acc a r x
```
since `acc a r x : Type` is a type and not a kind. And I do not have a bug if I wirte `ML` instead of `Tot`.

**Comment by catalin-hritcu** [comment]
I was indeed the confused one, sorry.

**Comment by ckeller** [comment]
I found a way not to trigger the bug, by naming a variable (I will make a separate bug report).

Nonetheless, as I expected, I do not see a way in current F* to prove the termination of fix_F, so contrary to what Catalin said, we cannot prove termination in the same way as in Coq (which is thus more expressive).

I think the way to do it would be to add `f x << f` as Nik suggested.
