### ISSUE TITLE
Improving error reporting on incomplete SMTPat clauses

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#141]
This is far from being critical, but the warning issued when an SMTPat clause does not instantiate all variables does not mention the file nor the line where it occurs :  

```
WARNING: pattern does not contain all quantified variables.
```

It would be nice to have a bit more information at some point in the future :)

**Comment by nikswamy** [comment]
Yes, sorry about that. What you're seeing is a Z3 message, and Z3 doesn't report a line number either. 

I should implement this check on all quantified variables appearing in a pattern in F* itself ... then I should be able to produce a proper error.

**Comment by s-zanella** [comment]
Note that a Z3 warning can still appear if there is an early F* warning

```(Warning) Pattern misses at least one bound variable: ...```

In this case, Z3 may output the same warning repeatedly even for seemingly unrelated proof obligations, because the assertion that triggers the warning happens to be in the context.

**Comment by catalin-hritcu** [comment]
Still happening, for instance:
```
[hritcu@resurrected termination]$ /home/hritcu/Projects/fstar/pub/bin/fstar.exe  --use_hints --verify_module termination termination.fst
WARNING: (72718,51): pattern does not contain all quantified variables.
WARNING: (72718,51): pattern does not contain all quantified variables.
WARNING: (72718,51): pattern does not contain all quantified variables.
WARNING: (6496,51): pattern does not contain all quantified variables.
WARNING: (72718,51): pattern does not contain all quantified variables.
WARNING: (72718,51): pattern does not contain all quantified variables.
```

**Comment by nikswamy** [comment]
We have addressed this issue. But there may still be some lingering occurrences.

Tracking further progress in issue #812. Closing this one.
