### ISSUE TITLE
Cache results of encode_modul in .checked files

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1413]
The .fst.checked files are a great improvement over the previous lax-rechecking of all dependencies.  Could we extend them to also include the results of `encode_modul`? After loading each .fst.checked we still go through a cycle of `finish_partial_modul` and `encode_modul`, which seems cacheable.

Of course, we'd have to see how much it grows the caches by.

**Comment by aseemr** [comment]
We have been caching smtencoding too for some time now :).
