### ISSUE TITLE
Discriminators and projectors from prims don't normalize

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1414]
I'm seeing broken behavior in the normalizer. Testers and projectors for options (`Some?`, `Some?.v`, ...) are reduced properly, but the analogous testers and projectors for lists (`Cons?`, `Cons?.hd`, ...) are not reduced at all:
```
let constant (t:term) : Tac unit = exact (norm_term [primops; delta; iota; zeta] t)

let f (x:option int) : int = if Some? x then Some?.v x else 0
let c1 : int = (synth (fun()-> constant (`( f (Some 42) ))))
// c1 = 42

let f' (x:list int) : int = if Cons? x then Cons?.hd x else 0
let c1' : int = (synth (fun()-> constant (`( f' (Cons 42 Nil) ))))
// c1' = if Cons? [42] then Cons?.hd [42] else 0
```
Funny, copying the definition of `list` from prims to my module makes this work again:
```
type list (a:Type) =
  | Nil  : list a
  | Cons : hd:a -> tl:list a -> list a

let f'' (x:list int) : int = if Cons? x then Cons?.hd x else 0
let c1'' : int = (synth (fun()-> constant (`( f'' (Cons 42 Nil) ))))
// c1'' = 42
```
So are lists or things in prims special cased in a bad way?

@aseemr says: I recall this being a continuous source of pain, we don't generate bodies of projectors and discriminators in prims (don't recall why)
Can you please file a bug I will fix it today or tomorrow
(Options are in Pervasives so they are fine)
Please assign it to me, I will take a look.

**Comment by aseemr** [comment]
Fixed in master (https://github.com/FStarLang/FStar/commit/bc4d8466cd4c3641c5e3f425d73314e726bc669e).
