### ISSUE TITLE
fstar not able to detect indirect decrease in list

### ISSUE THREAD

**Issue by singhsanjana** [FStarLang/FStar#1416]
let rec fn (var1:list (typeA * list typeB)) = 
     .... _some code_ ...
     fn (update var1)

in every iteration one of the lists of typeB decrease in length and eventually all lists of typeB become empty and function terminates.

How to I tell fstar that fn decreases?

Currently I am getting the error 'subtyping check failed

**Comment by aseemr** [comment]
You should be able to say `decreases (List.Tot.length (snd var1))`. E.g.:

```
let rec f (x:(list int * list int)) :Tot nat (decreases (List.Tot.length (snd x))) =
  match snd x with
  | [] -> 0
  | _  -> f (fst x, List.Tot.tl (snd x))
```
If that doesn't work, could you upload the example, and we can take a look.

**Comment by singhsanjana** [comment]
As I understand snd applies to a pair, but, var1 is a list of pair. How do I specify that I am talking about the snd of the list element?

**Comment by aseemr** [comment]
Oh sorry, I misread, let me see more.

**Comment by aseemr** [comment]
You could write a function that computes the sum of lengths of all the second components of `var1`, and specify that as the metric. For example:

```
let snd_l (var1:list (int * list int)) :list (list int) = List.Tot.map snd var1

let rec len_of_len (l:list (list int)) :nat =
  match l with
  | []    -> 0
  | hd::tl -> List.Tot.length hd + len_of_len tl

let rec fn (var1:list (int * list int))
  :Tot nat (decreases %[len_of_len (snd_l var1); var1])  //either sum of length decreases, or var1 decreases
  = match var1 with
    | []    -> 0
    | hd::tl ->
      let x, l = hd in
      match l with
      | []        -> fn tl
      | l_hd::l_tl -> fn ((x, l_tl)::tl)
```

**Comment by singhsanjana** [comment]
I changed my fn to work with a simple list and that worked for me. Thank you for your help.
