### ISSUE TITLE
Work items for the next F* release

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1417]
Aiming for F* 0.9.6 in about 1 month. Featuring Meta-F*, plus lots of other improvements as documented in CHANGES.md. However, there are still several more things we'd like to complete.

## Main features to be completed

- [x] Restoring the nightly binary build and standalone testing of binary packages @protz @catalin-hritcu @tahina-pro 
    TODO:
     * Updating the test target to only build some selected tests (catalin)
     * Opam package (Tahina)

- [x]  Making --cache_checked_modules and the new dependence analysis the default in all parts of the F* source tree. Requires avoiding some race conditions. @nikswamy owns, but will require help for migrating sub-projects. (estd. avoiding race conditions by April 6; propagating changes through all F* examples ... longer)

Update 04/07: F* now looks for .checked files first in the --cache_dir or in the same directory as the source file, and then searches elsewhere in the include path for it. If a valid .checked file for module A is found and F* is supposed to verify A, it copies the .checked file to the expected location for it, if it is not there already. examples/tactics/Makefile now uses this to reuse .checked files for ulib and to have a caching, incremental build for itself without racing with other builds that may also write .checked files. Would be good to propagate this style to other examples makefiles

Now used in examples/tactics, examples/lowparse, and examples/metatheory

Updat 05/15: F* now reads .checked files by default, but only writes them when --cache_checked_modules are present. This means that all of example at least reads the .checked files in ulib

* Makefile issues on negative tests (see examples/tactics/neg, e.g.,)
* Guido to work on a 'fail' attribute

- [x] --use_two_phase_tc, --use_extracted_interfaces the default and used everywhere in the F* source tree, and as much as possible in miTLS, Vale and HACL, with all exceptions well documented. @aseemr owns, but will require help to migrate projects to use this.
      - Used everywhere in F* (2 phase and extracted interfaces)
      - 2-phase tc used partially in Vale except on .vaf files
      - Extracted interfaces used in Vale
      - 2-phase tc used in miTLS
      - HACL not yet upgraded

      - use_two_phase_tc true is now the default
     
Upgrading miTLS, Vale, Quic-F* and HACL to use the latest F* master. TBD, need to understand requirements for a HACL upgrade. miTLS and Vale are already at or near F* master.

- [x ] Making `prop` work and removing the `logic` qualifier (#1048) @catalin-hritcu owns
      - This will not make it into this release
      - But, we have a transitionary alternative instead (A 'logical' type abbreviation and deprecation of the `logic` qualifier)
      - Aseem: the `logical` alternative is in master now, marking this task complete for the release.

- [x] Revised erasure for extraction (simply not extracting code for ghost functions) @nikswamy owns (estd completion by April 10)

* Aseem points out that aliases of unit need not be extracted at all
 
- [ ] Extracting some F* types to untagged unions in Kremlin @protz  owns
  ** NOT DOING **

- [x] Completing the pretty printer and --indent feature  maybe @victor-dumitrescu with help from @protz and @nikswamy
    Victor merged his work, although it is not yet sophisticated enough to be used to automatically enforce style conventions in F* source

- [x] Optimizing the representation of meta-variables in the unifier @nikswamy @aseemr @mtzguido (estd. ~10 days of work)
    - Design document at:https://github.com/FStarLang/FStar/wiki/Design-note:-Revising-the-unifier. Nik to implement this week
    - Guido implemented unification of match
    - Aseem to remove logical guards in Rel ... but only after 2 phase is settled, i.e., after this release?

- [x] Support for delta equational levels (@aseemr).
       - It seems `prop` changes require this support. 

- [ ] Making FStar.Integers usable mainstream and reconciling with HACL's integers @nikswamy
  ** NOT FOR THIS RELEASE **

- [x] Normalization improvements in support of Vale. @nikswamy with @Chris-Hawblitzel (nearing completion?)

- [x] Upgrading the F# build to use VS 2017; F# on CI machine?

- [x] Investigate the FD leak noticed by Catalin (@mtzguido, plugged one leak but uncertain that it was really significant, couldn't repro locally so postponing it for now)

## Bugs that we would really like fixed at a high priority

- [x] #1391 @nikswamy
- [x] #1141 @aseemr 
- [x] #1415 @mtzguido  (in progress, I don't think it's a tactic issue, so maybe not high-prio)
- [x] #1059, #1208
- [x] #1427 @aseemr
- [x] #638, #1189, #958, #1430 @aseemr
- [x] #1447

**Comment by parno** [comment]
This all sounds good to me.  I'm happy to help get Vale into sync with the proposed changes.

**Comment by aseemr** [comment]
Update 04/10: Upgrading Vale to the new F* flags:

`--use_extracted_interfaces` flag works for the whole Vale codebase.

There are issues with `--use_two_phase_tc true` flag, related to implicits inference in the presence of lambda expressions as function arguments. This is a known limitation of the two phases design and requires explicit annotations. After discussions with @nikswamy and @Chris-Hawblitzel, it seems like the new Vale typechecker will be well suited to emit the required annotations once in-place.

So, for now I have enabled the two phases flag for the F* files in `src` and not for the F* files generated by the Vale compiler. The changes are in the `aseem_new_fstar_flags` branch of Vale.

**Comment by nikswamy** [comment]
Addendum (from F* meeting 05/14)

1. Tahina's buffer v2 libraries, would be great to include them in the released bits, especially as we hope to use them for the tutorials 
  - It's in there, but perhaps some revisions are needed

2. Any low-hanging or critical bugs that we'd like to fix (e.g., #1091)
  - Many more bugs closed, and progress by guido on 1091, though not closed yes

3. Flipping the defaults on cache_checked_modules, use_two_phase_tc and use_extracted_interfaces
  - cache files read by default
  - use_two_phase_tc true default
  - use_extracted_interfaces still off: more work to do until next release before flipping it

4. Confusion around FSTAR_HOME, the location of ulib and the opam release and, related, upgrading remaining example makefiles to use cache_checked_modules etc. (edited)
  - F* no longer has an --fstar_home option
  - It can optionally read an FSTAR_LIB environment variable
  - example makefiles will not be ported now

5. Merging Victor's work on --indent
 - Done
 - Bonus: ocaml output no longer version dependent

6. Getting Vale under F* extended CI (several attempts, none successful yet)
 - TODO!

7. a warning, turned on by default (but non-fatal) to warn that a top-level binding without annotations is likely to lead to counter-intuitive behavior and is discouraged... this seems to confuse even seasoned F* hackers (I seem to recall Karthik got recently bitten by it) and pops up on a regular basis 
 
  - Discussed, but not doing at this time

**Comment by catalin-hritcu** [comment]
FYI: For 7 above the design we proposed a while back is here https://github.com/FStarLang/FStar/issues/1055

**Comment by nikswamy** [comment]
This release has been completed.
