### ISSUE TITLE
How does our termination check deal with impredicative polymorphism?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#142]
@maximedenes asks what's the order generated for the F* equivalent of the following Coq inductive type:

    Inductive foo := C : (forall P, P -> P) -> fop.

I can write this in F* as:

    type foo = | C : (p:Type -> p -> p) -> foo

F* accepts it, but I don't really know what "subterm ordering" means for this type.

**Comment by nikswamy** [comment]
https://github.com/FStarLang/FStar/commit/e2da10110e9a53a9c2836236f6c2809ed94b7119
