### ISSUE TITLE
Assertion Failure (unexpected unification variable remains)

### ISSUE THREAD

**Issue by theolaurent** [FStarLang/FStar#1423]
```
module Bug
open FStar.List.Tot

val subset_filter: #a: eqtype -> f: (a -> Tot bool) -> l: list a ->
  Lemma (requires True) (ensures (subset (filter f l) l))
let subset_filter #_ f l =
  let rec aux l' = match l' with
  | [] -> ()
  | h :: t -> ()
  in aux (filter f l)
```
Leads to
`Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.` with `CheckNoUvars: Unexpected unification variable remains`

Turn into a type error when
- replacing `aux (filter f l)` by `l`
- relacing the body of `aux` with `admit ()`

**Comment by aseemr** [comment]
Seems like some missing unification constraint for inner let recs. Because both removing `rec` from `aux` and hoisting `aux` to top-level work. Will look at it.

**Comment by aseemr** [comment]
@nikswamy pushed a re-haul of type inference to master, which seems to have solved this issue. Please re-open if you see the problem again.
