### ISSUE TITLE
Checked files don't contain docstrings

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1429]
There's an observable between loading a module from source and loading it from a `.checked` file: `.checked` files don't contain fsdocs.

It would be great to fix this before we start loading .checked files instead of .fst ones by default.  <del>The fix might be to move docs from `DsEnv.env` to `sigelt`.</del>

**Comment by cpitclaudel** [comment]
Hmm.  It turns out that that's how I originally wrote it (with a sigdoc field in sigelt).  @nikswamy, @protz, back in https://github.com/FStarLang/FStar/pull/931 you objected to that design.  Any ideas?

```
commit 75bff96f3f5c0683329458ce752e2d34e84ef1d8
Author: Clément Pit--Claudel <clement.pitclaudel@live.com>
Date:   Wed Apr 5 15:22:16 2017 -0400

    Move docs out of sigelt and into a side table in ToSyntax.Env

diff --git a/src/syntax/FStar.Syntax.Syntax.fs b/src/syntax/FStar.Syntax.Syntax.fs
--- a/src/syntax/FStar.Syntax.Syntax.fs
+++ b/src/syntax/FStar.Syntax.Syntax.fs
@@ -341,5 +330,4 @@
 and sigelt = {
     sigel: sigelt';
-    sigdoc: option<fsdoc>;
     sigrng: Range.range;
 }
```

**Comment by aseemr** [comment]
I am closing this issue since we are not supporting fsdocs anymore.
