### ISSUE TITLE
Broken string size inference

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1432]
With the latest F* master, this: 

```
let tls_client_label = FStar.Bytes.utf8_encode "client finished"
```

throws

```
(Error) Subtyping check failed; expected type (s:string{ String.length s < pow2 30 }); got type string
Related location (C-c C-' to visit, M-, to come back): /mnt/f/dev/sec/everest/verify/FStar/ulib/FStar.Bytes.fsti(274,13-274,35)
```

This used to work until recently. Also, there seem to be many vaguely related problems with inference of implicit arguments.

**Comment by s-zanella** [comment]
`Bytes.utf8_encode s` requires that `String.length s < pow2 30` but `String.length = String.strlen` is abstract (it's assumed in `FStar.String.fsti`), so there is currently no way of proving the required bound. 

I believe this has been broken since our switch to `FStar.Bytes` from `Platform.Bytes`, where the encoding function didn't enforce any bounds. A temporary solution would be to assume the lengths of any string literals until such time they could be computed.

**Comment by wintersteiger** [comment]
Yep, that looks like the right analysis! I'll continue adding lots of `assume`s :)

**Comment by A-Manning** [comment]
Currently F* can't infer lengths of string literals at all - this has nothing to do with proving that `String.length = String.strlen`. The solutions here are to either define strings in terms of some other type already in F* (eg. arrays of chars, or lists of chars), or to keep strings as a primitive and use SMT to reason about them. I have a [WIP PR](https://github.com/FStarLang/FStar/pull/1380) regarding the latter option.

**Comment by s-zanella** [comment]
@A-Manning The temporary solution that @nikswamy suggested and we ended up implementing is something midway.

We define
```
let strlen s = List.length (list_of_string s)

(**
 When applied to a literal s of less than n characters, this predicate
 reduces to True before going to the SMT solver.
 Otherwise, the left disjunct reduces partially but the right disjunct
 remains as is, allowing to keep `strlen s <= n` in the context.
*)
unfold let maxlen s n = b2t (normalize_term (strlen s <= n)) \/ strlen s <= n
```
And use `maxlen` to state a length bound that we might need to prove on string literals. 
This relies on `list_of_string` being a primitive in the normalizer.
