### ISSUE TITLE
Bad Z3 encoding (Unexpected output from Z3)

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1433]
We are again seeing a lot of Z3 warnings about missing constants in the encoding. E.g.,

```<dummy>(0,0-0,0): (Warning 276) FStar.Pointer.Base: Unexpected output from Z3: (error "line 18326 column 0: unknown constant fuel_12505")```

See for instance this recent build log: https://raw.githubusercontent.com/project-everest/ci-logs/master/fstar-nightly-54915e07-19392.err

They are caused by changes in the encoding between these two commits:
https://github.com/FStarLang/FStar/compare/75baf8a639cf78e85c4c5293869ed9f7134f12db...6281056d

While discussing this in Cambridge, we were wondering if we could avoid this issue in the future by making Z3 warnings fatal by default (e.g. `--warn_error @276`). There are a couple of related open issues (#1222, #843).

**Comment by nikswamy** [comment]
Also related is issue #613: a fix to that issue resulted in the bug here.

**Comment by s-zanella** [comment]
The fix appears to work and @nik turned `Unexpected output from Z3` warnings into fatal errors.
Closing
