### ISSUE TITLE
An emacs mode for F*

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#144]
I'm currently using [TuaregMode](http://www.emacswiki.org/emacs/TuaregMode) with some twists (https://github.com/FStarLang/FStar#emacs), but it would be nice to have something more tailored to F*.

**Comment by beurdouche** [comment]
Maybe we could from something like this ?
git://github.com/fsharp/fsharpbinding.git

**Comment by markulf** [comment]
TuaregMode crashes a lot once files differ from OCaml.

**Comment by catalin-hritcu** [comment]
@markulf  I've heard this from Nik as well, that Tuareg crashes a lot, still I haven't experienced that myself even if I used it quite a lot. The only crash I've got was when reflowing a comment that's not yet closed. Could your crashes be a Windows thing?

**Comment by catalin-hritcu** [comment]
Just for the record (indirectly related to this issue):
- @strub and @nikswamy started building an Atom (https://atom.io/) mode for F* (https://github.com/FStarLang/FStarIDE)
- @mlr-msft seems to be working on a vim plugin (https://github.com/FStarLang/FStar/issues/202#issuecomment-93781441)
Personally I think it's fine for different people to experiment with their favorite editors at this point.

**Comment by beurdouche** [comment]
> Just for the record (indirectly related to this issue):
> 
> @strub <https://github.com/strub> and @nikswamy <https://github.com/nikswamy> started building an Atom (https://atom.io/ <https://atom.io/>) mode for F* (https://github.com/FStarLang/FStarIDE <https://github.com/FStarLang/FStarIDE>)
This is very cool, thanks =)
> @mlr-msft <https://github.com/mlr-msft> seems to be working on a vim plugin (#202 (comment) <https://github.com/FStarLang/FStar/issues/202#issuecomment-93781441>) Personally I think it's fine for different people to experiment with their favorite editors at this point.

**Comment by catalin-hritcu** [comment]
Clement Pit-Claudel has contributed a prototype fstar mode:
https://github.com/FStarLang/fstar.el
