### ISSUE TITLE
Cross-module inlining, incremental extraction, use_extracted_interfaces, and already_cached

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1444]
Aiming to solve a few problems with build and dependency analysis

1. An F* project should be able to build itself; another project that
   depends on it should not have to try to build it again (and get it
   wrong)

2. Concurrent builds should be possible, so long as they avoid racing
   to write the same .checked file; mechanisms to ensure that a build
   can fail if a .checked file isn't present would be useful.

3. We should be able to build a project given only .checked files for
   its dependences.

4. With use_extracted_interfaces, we can shrink the dependences of a
   project to only the dependences of the interfaces it depends on.

Points 1 and 2 are already possible with the current support
available, but it can be a bit cumbersome and may require recursive
invocations of make.

## Proposal: A new F* option `--already_cached <namespace selector>`

where `<namespace selector>` is a string like `FStar MiTLS.LowParse`
or `* -MiTLS` etc., which can be used to select or deselect one or
more namespaces / module names.

### Dependence analysis

1. `fstar --dep full --already_cached ns ROOTS` will scan starting from
   ROOTS, as usual.

2. When it finds a dependence on module `M` that matches `ns`, rather
   than searching for `M.fst(i)` it searches for `M.fst(i).checked` in
   the include path. Say it finds it at path
   `<path_to_M>/M.fst.checked`

3. Having found the M.fst.checked file, it computes the immediate
   dependeces of `M` by just reading it from the list of immediate
   dependences of recorded in the interface section of the .checked
   file. 

   -- If any of those immediate dependences does not match the
      namespace selector `ns`, the dependence analysis fails with an
      error requesting to add that module to the namespace selector.

   -- While .checked files have an interface section, they do not yet contain interface dependences separately from module dependences. This would also have to be added.

4. It adds those immediate dependences to the set of pending modules
   to be scanned and continues.

5. The final output of the dependence analysis includes Makefile
   dependence rules only for those modules whose names do not match
   <ns>. For example, it will contain:

   ```A.fst.checked: A.fst <path_to_M>/M.fst.checked```

   But it will not contain such a rule for `M.fst.checked`.

6. The dependence analysis also defines three variables:

   * ALL_FST_FILES: This will contain all .fst and .fsti files
     encountered in the scan (i.e., excluding all the .checked files)

   * ALL_ML_FILES: This will contain .ml file names for all *modules*
     encountered in the scan, including .fst and .checked versions,
     subject to the "--extract <namespace selector>" feature. For a
     checked file, say, `<path_to_M>/M.fst.checked`, the dependence
     analysis will search for `M.ml` in the include path and emit
     `<path_to_M.ml>/M.ml`.

   * ALL_KRML_FILES: This behaves the same as for .ml files, except
     using .krml files. Additionally, since KreMLin is a full-program
     analysis, we include all .krml files, disregarding the `--extract
     <namespace selector>`.

### Verification runs of F*

1. `fstar --already_cached ns ROOTS` will run the dependence analysis
   as in the previous section.

2. F* will then load a set of .checked files as dictated by the
   dependence analysis, and for any .checked file that is in <ns>, F*
   will load the .checked file (it must exist, since otherwise the
   dependence analysis would have already failed).

   a. When loading M.fst.checked, if M.fst is found in the include
   path, F* will check the digest stored in M.fst.checked for
   consistency with M.fst (and its dependences).

   b. If M.fst is not found, F* will load the checked file without
   checking a digest.

**Comment by nikswamy** [comment]
Feedback from some of @aseemr @wintersteiger @s-zanella @fournet @protz @tahina-pro, would be great.

**Comment by wintersteiger** [comment]
I'm not sure about the namespace selection, but I guess it can be helpful if someone ever wants to use some .checked files, but not other ones (e.g. FStar.*). 

Re 5: Is `path_to_M` the directory in which `M.fst` (no `.checked`) lives? I suppose a natural choice would be to point to whatever `--cache_dir` points to. By default perhaps in the current directory?

**Comment by cpitclaudel** [comment]
I think I'm not understanding the proposal :/ Can you clarify why that setting is needed? My intuition would be that if a checked file is available it should be read, with no need for extra flags. Outdated .checked files (detected by checksum-ing the .fst or .fsti **if available**) should cause a warning (and F* should load the fst or fsti instead).

**Comment by nikswamy** [comment]
@cpitclaudel 
What if when trying to run `fstar A.fst` a checked file for one of its dependences `B.fst` was not found. What should we do then? 

Try to verify `B.fst` on the fly? 

-- That can be expensive and unpredictable, since verifying B.fst may require some special options of its own and the author of `A` may know nothing about how `B` should be verified. (related to problem 1 in my list)

-- Even if it does succeed in verifying it, should it produce a .checked file for B and if so, where should it put it? We have to be careful about that since concurrent builds may then race to write the same file. (related to point 2 in my list)

So, this new setting is a way of side stepping these issues by expressing that a project's dependences must already be built before trying to build the project itself.

**Comment by nikswamy** [comment]
@wintersteiger 

> Re 5: Is path_to_M the directory in which M.fst (no .checked) lives? I suppose a natural choice would be to point to whatever --cache_dir points to. By default perhaps in the current directory?

Sorry, that's a typo: I meant to write `<path_to_M_fst_checked>/M.fst.checked` Revising.

**Comment by nikswamy** [comment]
@wintersteiger 

> Re 5: Is path_to_M the directory in which M.fst (no .checked) lives? I suppose a natural choice would be to point to whatever --cache_dir points to. By default perhaps in the current directory?

Sorry, this was not clear.

Earlier in the proposal I say:

>2.  When it finds a dependence on module M that matches ns, rather
than searching for M.fst(i) it searches for M.fst(i).checked in
the include path. Say it finds it at path
<path_to_M>/M.fst.checked


So `<path_to_M>` is really the path to M.fst.checked.

**Comment by cpitclaudel** [comment]
> What if when trying to run fstar A.fst a checked file for one of its dependences B.fst was not found. What should we do then? Try to verify B.fst on the fly?

Yup, that'd be my intuition :) But we could also just bail out entirely (that's what Coq does: it never looks for .v files as dependencies).

Proof General has a lot of code to on the fly compilation of dependencies, and it's not pretty.  Conversely, Python generates pyc files on the fly.

> That can be expensive and unpredictable, since verifying B.fst may require some special options of its own and the author of A may know nothing about how B should be verified. (related to problem 1 in my list)

What special options are we concretely thinking of? I think they should be in the file itself, or in a local fstar.conf project file.

> Even if it does succeed in verifying it, should it produce a .checked file for B and if so, where should it put it? We have to be careful about that since concurrent builds may then race to write the same file. (related to point 2 in my list)

Yup, saving the checked file sounds good.  The location should be the one we usually use, which ATM seems to be in the same folder?

I'm not sure I understand the point about concurrency.  Of course, two fstar processes should not be writing the same checked file at the same time, but that's easy to avoid (both Windows and POSIX have ways to rename a file atomically, so the usual approach is to write to a temp file first, and then atomically rename to the intended destination).
Or are you worrying about something else?

**Comment by nikswamy** [comment]
> But we could also just bail out entirely (that's what Coq does: it never looks for .v files as dependencies).

The option is to provide this behavior. It's exactly what we had in mind in discussions with @tahina-pro

**Comment by s-zanella** [comment]
This flag would be very useful. Looking at the log of a recent Everest build, it seems like we're re-verifying files in `FStar/ulib` up to 7 times! Most in `--lax` mode, but stil...

**Comment by s-zanella** [comment]
Searching for `.checked`/`.checked.lax` files in the include path but writing new files to `--cache_dir`, together would already be a big improvement over the current behavior.

**Comment by nikswamy** [comment]
@aseemr and I had a long discussion about this and came up with the following implementation plan. We are starting to tackle it now and expect it to take the two of us about a week to complete (except for item 8, which will take some more time and item 9, which requires more thought).

An implementation plan for the above proposal, also including

   -- Context pruning
   -- Cross-module inlining (CMI)
   
 + Some notes in less detail about
   -- Friend modules
   -- Removing --expose_interfaces
   -- Memoizing extraction
   -- Support for extracted interfaces in fstar-mode.el
   -- A way to recover a bit of "separate extraction" even in the
      presence of CMI
   
1. Fix delta depths: Maintain them with sigelts in the
   environment rather than on each fvar.

   (will simplify tasks later in the list)

2. Need to reload the desugaring environment with the extracted
   interface so that subsequent modules are desugared with the
   appropriate qualifiers etc.

3. --already_cached (1444); mainly involves the dependence analysis

   `--already_cached ...` implies only 1 file on the command line

   Revising the format of .checked files to include interface
   dependences separately, in support of context pruning

   A.fst(i).checked:
        
        A.impl={
             Header={
                immediate-deps=
                   [self(A.fst, A.fst.hash);
                    dep(B.fst.checked, B.fst.checked.hash);
                    ...
                    dep(...)]
             }
        },

        //missing for modules with explicit interfaces
        //or for .fstis
        optional A.iface= {
              Header={
                  immediate-deps=
                    [self(A.fst, A.fst.hash);
                     dep(B.fst.checked, B.fst.checked.hash);
                     ...
                     dep(...)]
              }
        }

5. Cross-module inlining for extraction

   A .checked file contains the module implementation;
   and separately the module interface         

   fstar A.fst --codgen OCaml --extract A

   Note:  `--codegen _` implies `--already_cached *`

  (A depends on B)

   - Both A.fst.checked and B.fst.checked should be present
   
   - We load B's implementation in to the context
        
   - We load A's implementation into the context
     We extract A

   This should remove the need for --expose_interfaces for extraction
   purposes.
   
6. Verification runs

   As is. i.e., we load the interface section of a .checked file, if
   present

   
7. Friend modules for verification

   This should remove the need for --expose_interfaces for revealing
   representations during verification.

8. Memoizing extraction

   This would add another section to .checked files

   And every run of F* would actually do a bit of extraction for
   populating this part of the .checked file, without actually
   emitting any code

9. Extracted interfaces and interactive mode?

   The "ideal" behavior would be to maintain 2 type-checking/SMT
   environments in parallel as we progress through a buffer.

   One environment for checking the module implementation (as currently)

   And a second "shadow" environment in which we incrementally extract
   and check the interface.

   This sounds difficult to do in a single F* process, at least not
   without some significant redesign of our code, though not
   impossible, since a lot of work has already been done on making the
   typechecker's state persistent.

   Another, possibility may be for fstar-mode.el to maintain 2 running
   F* processes.

   An easier goal would be to run this check at the "end" of a module,
   with a command triggered by fstar-mode.el
   
   This is still open.   


--------------------------------------------------------------------------------

A variant we considered, but decided to leave for later, since it adds
even more complexity.

Cross-module inlining (CMI) is not an outright win. While it enables
more code specialization, it also gives up a bit of separate
extraction. That is, if A.fst changed although A.fsti did not, with
cross-module inlining we will have to re-extract all modules that
depend on A again.

To compensate for this, we considered automatically detecting when a
module requires cross-module inlining.

  Cross-module inlining is enabled for a module B whenever

   a. B's interface contains a symbol marked 'inline_for_extraction'
   
   b. B's interface contains a symbol whose definition is an
      non-informative type; in such cases we should insist that `t`
      (below) is also marked `inline_for_extraction`.

      e.g,
      
```   
     module B (.fsti)
       val t : Type0 //requires to be marked inline_for_extraction
       val f : (unit -> t) -> int
  
     module B (.fst)
       let t = unit
       let f x = 0                extracted as  let f (x:unit) = 0
```

This also has an impact on the format of .checked files, where we'd
add a header bit to record whether or not a module requires CMI.

The dependence analysis would also have to be aware of this:

   The dependence analysis should be aware of the cross-module
   inlining criterion below.

   In case A depends on B, then

   if there is no explicit B.fsti or if B requires cross-module
   inlining then we should emit

      A.ml: A.fst.checked B.fst.checked

   otherwise

      A.ml: A.fst.checked B.fsti.checked

**Comment by aseemr** [comment]
@nikswamy, with this scheme, we should also remove the step of adding `erase_for_extraction` attribute when extracting interfaces. It won't be needed anymore, since CMI is the default.

**Comment by nikswamy** [comment]
With @protz, we discussed a lightweight variant of --already_cached. 

The invocation `fstar --already_cached A B.fst` fails unless a valid A.fst(i).checked is found on the include path.

Furthermore, the --cache_dir is set to the lowest priority in the include path. So, typically, invocations of F* would prefer to use .checked files from ulib rather than from local cache directories.

This is implemented in `nik_dep` and awaiting a CI build from Everest before merging to master

**Comment by aseemr** [comment]
The remaining items in this issue are related to use_extracted_interfaces, which is long gone. Closing this issue.
