### ISSUE TITLE
`pipe_right` and `pipe_left` have ML effect

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1445]
https://github.com/FStarLang/FStar/blob/a50fb37341f6e3b7c9495c329a81a9059ea7bfb7/ulib/FStar.All.fst#L39-L40

It seems like these should really be in `FStar.Pervasives`, with `Tot` effect? It seems weird that the default resolution is to `FStar.All`. Also, why are they assumed? F* accepts 
```
val pipe_right : 'a -> ('a -> ML 'b) -> ML 'b
let pipe_right x f = f x

val pipe_left : ('a -> ML 'b) -> 'a -> ML 'b
let pipe_left f = f
```

**Comment by nikswamy** [comment]
Indeed, no reason for the assume. Would be good to remove it.

But, in the absence of effect polymorphism, the ML effect on the function argument is a more permissive type for the caller, at the expense of the ML effect in the result also.

**Comment by aseemr** [comment]
Users may define their own versions of these, but they have to fix the effect, closing since the actionable part of the issue (implementation of these) has been fixed.
