### ISSUE TITLE
Can't run Tutorial code

### ISSUE THREAD

**Issue by farao** [FStarLang/FStar#1453]
Hi,

I wanted to follow the tutorial https://www.fstar-lang.org/tutorial/ - and I can neither run the fstar checker in the browser ("unrecognized option '--fstar_home'") nor on my machine ("./Ex01a.fst(3,11-3,14) : (Error) Namespace FStar.Exn cannot be found"). How can I get one of them to work? The fstar version on my machine is 0.9.4.0 (commit=43c42bb) for Linux_x86_64 from the Archlinux AUR.

Thanks,
Marius

**Comment by nikswamy** [comment]
Sorry, the tutorial seems broken at the moment. We will fix it soon. 

0.9.4.0 is more than a year old and probably will not work with the current version of the tutorial.

We are releasing 0.9.6.0 today ... you will probably need that version to run the most recent tutorial files in the repository.

**Comment by nikswamy** [comment]
Seems to be working again.

You might consider upgrading to 0.9.6.0: https://github.com/FStarLang/FStar/releases/tag/v0.9.6.0

**Comment by mssabr01** [comment]
The web tutorial is returning the error below fyi

Please download the version of Z3 corresponding to your platform from:
https://github.com/FStarLang/binaries/tree/master/z3-tested
and add the bin/ subdirectory into your PATH

**Comment by mssabr01** [comment]
Its all good now, cheers!

**Comment by nikswamy** [comment]
Thanks for the report and all the testing. Much appreciated!
