### ISSUE TITLE
F* should return a non-zero error code when given invalid command-line options

### ISSUE THREAD

**Issue by parno** [FStarLang/FStar#1455]
If I run F* with an invalid option, it returns a success (0) return code:

```
$ fstar.exe --blah T.fst
unrecognized option '--blah'
$ echo $?
0
```

This means that build systems that rely on the return code to detect verification failures will think that verification succeeded, whereas we should be treating this as a failure.

**Comment by mtzguido** [comment]
Can you say a bit about your setup? It seems to fail as appropriate on a recent F* in my machine:
```
$ ./bin/fstar.exe --blah ; echo $?
unrecognized option '--blah'
1
$ ./bin/fstar.exe --blah A.fst ; echo $?
unrecognized option '--blah'
1
```
The relevant logic is in `go` inside `FStar.Main.fs`, and seems fine except for the fact that it doesn't fail when no files are provided (`fstar.exe --debug A` should fail, but it doesn't), which I can fix.

**Comment by parno** [comment]
Sorry, I should have specified: 
```
$ fstar.exe --version
F* 0.9.4.3
platform=Darwin_x86_64
compiler=OCaml 4.04.0
date=2018-05-23T16:26:43-07:00
commit=5b3b9a84e
```
This is on Mac OS X.  In my case `T.fst` does exist:

```
$ cat T.fst
module T

let test (x:int)
  = 
  assert ( x > 0 )
$ fstar.exe --blah T.fst && echo $?
unrecognized option '--blah'
0
```

**Comment by parno** [comment]
Looks like I was using an out-of-date master.  With the latest version, this issue is gone.  Sorry for the confusion.
