### ISSUE TITLE
Dependency analysis misses dependencies through code in interfaces

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1460]
`M.fsti`
```F#
module M
let x = N.x
```
`M.fst`
```F#
module M
```
`N.fst`
```F#
module N
let t = 0
```

The dependencies of `M.fst.checked` and `M.cmx` computed with `$ fstar.exe --dep full M.fst` miss the dependency on `N` though the definition in `M.fsti` (that is, `N.fst.checked` and `N.cmx`, respectively). Strangely enough, `N` appears in the dependency graph and it is present in all other dependencies.

This is a minimal example from a concrete occurrence in `mitls-fstar`, where `CommonDH.cmx` missed a dependency on `Format.NamedGroupList.cmx` resulting in intermittent errors during OCaml compilation in parallel builds.

**Comment by nikswamy** [comment]
fixed the .cmx dependences in master. Would be great if you can confirm that it works as expected in mitls.

**Comment by s-zanella** [comment]
Sorry, I didn't spot the transitive dependency of `M.fst.checked` on `N.fst.checked` and thought it was missing too.
I tried the fix in the example and mitls-fstar and it works as expected. Thanks!

**Comment by nikswamy** [comment]
note, this last bit is a breaking change, in case you had any makefiles/scons files etc. that were depending on this intermediate .source file
