### ISSUE TITLE
Projector name confilcts "silently"

### ISSUE THREAD

**Issue by theolaurent** [FStarLang/FStar#1463]
Counterintuitive (or at least non newbie-friendly) things happen when you define a type with the same projector name used twice, e.g.
```
type foo =
  | Foo : it:unit -> foo
  | Bar : it:unit -> bar
```
1. You get no shadowing warning or error
2. The identifier seems to stay undefined (you get error `Identifier not found` if you try to use `it`)

**Comment by s-zanella** [comment]
There is no shadowing.
```F#
type foo =
  | Foo : it:unit -> foo
  | Bar : it:unit -> foo
```
Introduces 2 projectors: `Foo?.it` and `Bar?.it`. What's counter-intuitive here is that if `Foo` was the only constructor of `foo` you could write `x.it` as syntactic sugar for `Foo?.it x` whereas you can't if `foo` has more than one constructor (even if you hadn't also named its argument `it`).

**Comment by theolaurent** [comment]
Ohh. Okay, sorry for the misunderstanding.
