### ISSUE TITLE
Tautological comparisons are not normalized away by F*

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1467]
This seems to be generated by a tactic. Found in mitls-fstar/src/tls/extract/Kremlin-Library/DHGroup.c

```
      uint32_t v1 = scrut0.v.fst;
      FStar_Pervasives_Native_option__K___uint32_t_uint32_t ite;
      if (!(v1 < (uint32_t)0U || (uint32_t)65535U < v1))
```

this generates a warning on modern compilers:

```
DHGroup.c:393:14: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if (!(v1 < (uint32_t)0U || (uint32_t)65535U < v1))
```

CC @nikswamy @tahina-pro

**Comment by s-zanella** [comment]
Related to #1482.
I hit this issue and had to add a `-Wno-error` flag to make the warning non-fatal when compiling with `-Werror`.

**Comment by aseemr** [comment]
We are tracking it in #1376, closing this issue (thanks for reporting it Jonathan!).
