### ISSUE TITLE
Agda-like editor support for devising proofs interactively

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#147]
Writing proof terms solely by inspecting error messages is a pain. Being able to print the types of things in context (#219) would already be helpful. Being able to additionally write terms with "holes" and see the types of these holes would be even better. In the long term we could aim for something like the wonderful Agda Emacs Mode:
http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.QuickGuideToEditingTypeCheckingAndCompilingAgdaCode

Update: could also look at Idris editor: https://www.itu.dk/people/drc/pubs/dtp2014-idris-mode.pdf

**Comment by cpitclaudel** [comment]
Related: https://github.com/FStarLang/FStar/pull/940

Agda mode is nice, but it's essentially structured editing: things work as long as the whole document parses. I'm not too fond of that idea.  It'd be much nicer if F* could robustly recover from parsing errors, and give interesting information even for partial terms.

**Comment by nikswamy** [comment]
Lots of work on fstar-mode.el. 

We also have a wiki page discussing how we might add support for holes and other related features:

https://github.com/FStarLang/FStar/wiki/Towards-a-Finer-grained-Incremental-Typechecker-for-F*

Closing this issue.
