### ISSUE TITLE
Dependent types in records

### ISSUE THREAD

**Issue by lastland** [FStarLang/FStar#1473]
Hi, I was trying to define a record type similar to this one:
```
noeq type a = { typ:Type; f:typ -> nat }
```
F* does not accept this because it cannot find the identifier `typ`. However, F* has no problem accepting the following definition:
```
noeq type a =
  | MkA : typ:Type -> f:(typ -> nat) -> a
```
I thought these two definitions are the same internally in F* so I expected F* would yield the same result in both of them.

**Comment by s-zanella** [comment]
This is a frequent request. See #801 and #1184.

**Comment by lastland** [comment]
Thanks for the pointer! Feel free to close it since there are multiple tickets about it already.

**Comment by nikswamy** [comment]
Closing.
