### ISSUE TITLE
Bug when mixing wildcards and totality

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#148]
The following program:
```
type foo (r:(unit -> Type)) : Type =
  | Foo : x:unit -> (r x -> Tot (foo r)) -> foo r
val bug : r:(unit -> Type) -> x:unit -> foo r -> r x -> ML (foo r)
let bug x = function | Foo _ h1 -> h1
```
raises "Bound term variable not found: _697" whereas there is no problem if either:
- I replace `Tot` with `ML`; or
- I give a name to the wildcard.

See `bug148.fst`.

**Comment by catalin-hritcu** [comment]
This might be the same as #116

**Comment by nikswamy** [comment]
Seems to be fixed now.
