### ISSUE TITLE
Internal error due to invalid numeric literal

### ISSUE THREAD

**Issue by parno** [FStarLang/FStar#1487]
This is a minor bug, but it seemed worth recording somewhere. 

Feeding F* the following program:
```
module U

module U64 = FStar.UInt64

assume val f (u:U64.t) : unit

let test() =
  f 2u
```
produces:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("This is not a valid numeric literal.")
```
rather than a syntax/verification error pointing to the `2u`.  Changing `2u` to `2` or `2ul` produces the expected error.

**Comment by fournet** [comment]
Another internal failure to promote to an error?
