### ISSUE TITLE
Refinement as return type for an inductive constructor somtimes erased silently.

### ISSUE THREAD

**Issue by theolaurent** [FStarLang/FStar#1488]
I am talking about this kind of declarations:
```
type test =
  | Test : unit -> t:test{phi}
```
Currently, the refinement is just silently erased, as shown by `--log_types`:
```
datacon Try.Test : _0: Prims.unit -> Prims.Tot Try.test
```
Silent erasure is just confusing, we should have type error, just as for
```
type test =
  | Test : t:test{phi}
```
which raise `Expected a constructor of type test; got t: Try.test{phi}`

**Comment by theolaurent** [comment]
BTW, what is the setting of the [PLDI 2013](https://www.microsoft.com/en-us/research/wp-content/uploads/2013/06/paper-pldi13.pdf) paper (see the `dyn` type page 7)? Seems that there is some kind of verified postcondition for type constructors.

Does it have some SMT-dischared index-like feature? Just curious.

**Comment by catalin-hritcu** [comment]
@theolaurent That PLDI paper is for F* 0.7, which was the version from before most of us even joined the project ... old stuff, but some ideas like Dijkstra monads to persist.

**Comment by aseemr** [comment]
Fixed in this commit: https://github.com/FStarLang/FStar/commit/52bad09fb7c7c38802af178e172ba84665e71e08.

Thanks for the report!
