### ISSUE TITLE
Broken error message with universes

### ISSUE THREAD

**Issue by theolaurent** [FStarLang/FStar#1489]
The following code
```
type bar = x:Type & x

let x : bar = (| Type, nat |)
let y : bar = (| (Type -> Type), list |)
let z : bar = (| nat, 0 |)

let l : list bar = [x ; y ; z]
```
gives me `(Error 54) Aha.bar is not a subtype of the expected type Aha.bar`

**Comment by mtzguido** [comment]
This is actually just a bad error message.. the list you're building cannot live in a single universe. Using `--print_universes` reveals the issue, but it should be considered to enable it when we print this mismatch
```
A.fst(9,28-9,29): (Error 54) A.bar u#0 is not a subtype of the expected type A.bar u#1
```

**Comment by theolaurent** [comment]
Ah, indeed. Thank you.

A few things I don't get right though,
1. Don't we have cumulative universes? In my understanding that would allow to make it work..
2. Dependent pairs suddenly seem much less useful. Am I missing something?

**Comment by catalin-hritcu** [comment]
@theolaurent F*'s universes are not cumulative.

**Comment by mtzguido** [comment]
We should at least print the universe discrepancy

**Comment by mtzguido** [comment]
I made F* retry printing with more and more flags until it finds a discrepancy, so this raises the following error:
```
B.fst(9,28-9,29): (Error 54) B.bar u#0 is not a subtype of the expected type B.bar u#1
1 error was reported (see above)
```
without any action from the user.
