### ISSUE TITLE
Can not prove below code with Lemma

### ISSUE THREAD

**Issue by hungvq00390** [FStarLang/FStar#149]
Please help to check is this bug or not: 
```
module Fibonacci
val fibonacci : nat -> Tot nat
let rec fibonacci n =
  if n <= 1 then 1 else fibonacci (n - 1) + fibonacci (n - 2)
val fibonacci_monotone : n:nat{n > 4} -> Lemma (fibonacci n > n)
let rec fibonacci_monotone n =
  match n with
  | 2 | 3 -> ()
  | _ -> fibonacci_monotone (n-1)
```
say 
```
Error Fibonacci_Lemma.fst(9,0-12,33): The following problems were found:
        Subtyping check failed; expected type _13159:n:nat{(n > 4)}{(_13159 << n)}; got type int (Fibonacci_Lemma.fst(12,28-12,33))
```
but if change to
```
let rec fibonacci_monotone n =
  match n with
  | 2 | 3 | 5 -> ()
  | _ -> fibonacci_monotone (n-1)
```
It's OK

**Comment by catalin-hritcu** [comment]
This seems like correct behavior to me. Your lemma has a precondition that `n > 4`. In the first case for `n = 5` you do a recursive call with `n = 4`, which doesn't satisfy this precondition. In the second case you just return unit in this case, which if fine.

**Comment by ckeller** [comment]
But it is true that we need to enhance error messages :-)

**Comment by catalin-hritcu** [comment]
I guess I got too used to this kind of errors to still see a problem. Now if I think about it more, the problem I see is that the << part is spurious and mentions an unification variable. Finding a "minimal conflict" in the case of a failed sub-typing seems non-trivial though.
