### ISSUE TITLE
When installing fstar through OPAM the codegen stuff seems to be missing

### ISSUE THREAD

**Issue by NobbZ** [FStarLang/FStar#1494]
I can not find the `ulib` folder anywhere, as well as the Makefiles that should be contained. Also the examples seem to be there in a subfolder but of course can't be built:

```
fstar/examples/hello $ make      
Makefile:7: ../../ulib/ml/Makefile.include: No such file or directory
make: *** No rule to make target '../../ulib/ml/Makefile.include'.  Stop.
fstar/examples/hello $ cd ../..
fstar $ ls
contrib  examples  tutorial
```

**Comment by catalin-hritcu** [comment]
Not sure if this is supposed to work with the opam package. Maybe @tahina-pro can clarify.

**Comment by theolaurent** [comment]
Not sure what you are trying to build and what's in your path, but I know that when you install fstar with opam, ulib is installed as an ocaml library under the name fstarlib (you can include it with ocamlfind/ocamlbuild/etc.)

**Comment by theolaurent** [comment]
Also the full fstar repo (including ulib) should be cloned in opam's packages.dev folder anyway, am I right?

**Comment by NobbZ** [comment]
I'm searching for the `Makefile.include`s refered to throughout the documentation about how to build a binary:

https://github.com/FStarLang/FStar/wiki/Executing-F*-code

Even the examples (which are installed via OPAM) want to use this `Makefile.include` and therefore are not able to compile.

So basically, after installing F* via OPAM, I want to be able to enter the examples folder and simply run `make` to get a working executable for my system.

Also when I install from OPAM, I assume that I can follow the documentation linked above without further ado.

**Comment by NobbZ** [comment]
> Also the full fstar repo (including ulib) should be cloned in opam's packages.dev folder anyway, am I right?

It seems as if there is not:

```shell
$ find .opam -name Makefile.include
.opam/4.06.1/lib/fstar/ml/Makefile.include
.opam/4.06.1/share/fstar/examples/Makefile.include
.opam/4.06.1/share/fstar/tutorial/code/Makefile.include
```
