### ISSUE TITLE
List literals and refinement types

### ISSUE THREAD

**Issue by lastland** [FStarLang/FStar#1498]
I don't know if this is a known issue, but I did not find anything with a quick search on GitHub.

F* accepts the following:
```
let lst : (l:list bool{length l = 7}) = [true; true; true; true; true; true; true]
```
but not this one:
```
let lst : (l:list bool{length l = 8}) = [true; true; true; true; true; true; true; true]
```
and the error message is:
```
(Error) Subtyping check failed; expected type l: list bool {length l = 8}; got type list bool
```

This scheme seems to only work with any list whose length is less than 8.

**Comment by msprotz** [comment]
Yes, this is know. The behavior is as follows: this type refinement emits an SMT guard that ought to be satisfied in order for the subtyping judgement to be true. Concretely, F\* asks Z3 to show that the list has length 7.

Z3 can "compute" and unroll function definitions, up to a number of times controlled by the "fuel" setting. This example might work by doing `#set-options "--max_fuel 8"` or greater. However, this is highly inefficient and not a good practice in general to rely on the SMT solver for proving those assertions.

What you can do instead is this:
```
let l:(l:list int { List.Tot.length l = 16 }) =
  let l = [ 0; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15 ] in
  assert_norm (List.Tot.length l = 16);
  l
```

This relies on F\* computing, at type-checking time, the length of the list and checking your assertion.
