### ISSUE TITLE
Refinement on return type of an effectful function is forgotten in monadic application

### ISSUE THREAD

**Issue by aseemr** [FStarLang/FStar#1500]
This fails to verify:

```
module Test

open FStar.ST

assume val bar (_:unit) :St (x:int{x == 42})

assume val foo (x:int) :Pure int (requires True) (ensures (fun r -> r == x))

#set-options "--max_fuel 0 --max_ifuel 0"
let test () :St unit =
  let y = foo (bar ()) in
  assert (y == 42)
```

Explicitly binding `bar ()` before the application works.

**Comment by mtzguido** [comment]
Similar to #1470? I didn't follow up there, sorry. I had some work in `guido_1470`, but I don't think it worked great, could try it again later today or tomorrow.

**Comment by aseemr** [comment]
Indeed, this is same as #1470. Adding the example there and closing this.
