### ISSUE TITLE
Unification/delta_depth issue

### ISSUE THREAD

**Issue by parno** [FStarLang/FStar#1503]
In the LowStar code below, the call to `C.Loops.for` fails if given the separately defined `body`, but it succeeds if given an equivalent lambda expression.  @mtzguido described it as "a stupid unification/delta_depth issue", and added "the unifier basically needs to solve U32.v (U32.uint_to_t 0) == 0 and gives up with 'this is impossible', which is wrong".  

We tabled it during the lead up to POPL, and it seems like a superficial difference, but the version with a separate body seems to verify faster and provide somewhat better error messages when body fails to preserve the invariant, so it would be nice to be able to support the cleanly factored version.

```
module Loop

module B = LowStar.Buffer
module M = LowStar.Modifies
module HS = FStar.HyperStack
module ST = FStar.HyperStack.ST
module HST = FStar.HyperStack.ST
open LowStar.ModifiesPat
open FStar.HyperStack.ST
module U8 = FStar.UInt8
module U32 = FStar.UInt32

assume val write (output_b:B.buffer U8.t) : Stack unit 
  (requires fun h -> B.live h output_b)
  (ensures fun h () h' -> 
    B.live h' output_b /\
    M.modifies (M.loc_buffer output_b) h h'
  )         

let t(b:B.buffer U8.t) (n:U32.t) : Stack unit
  (requires fun h -> B.live h b /\ B.length b == U32.v n)
  (ensures fun h () h' -> True)
  =
  let h0 = ST.get() in
  let inv (h:HS.mem) (i:nat) =
    B.live h b /\
    M.modifies (M.loc_buffer b) h0 h /\
    i <= U32.v n
  in
  let body (i:U32.t{ 0 <= U32.v i /\ U32.v i < U32.v n }) : Stack unit
    (requires (fun h -> inv h (U32.v i)))
    (ensures (fun h () h' -> inv h (U32.v i) /\ inv h (U32.v i + 1)))
    =
    write b;
    ()
  in
  // Works:
  // C.Loops.for 0ul n inv (fun (i:U32.t{ 0 <= U32.v i /\ U32.v i < U32.v n }) -> write b);
  // Fails
  C.Loops.for 0ul n inv body;
  ()
```

**Comment by aseemr** [comment]
Hi Bryan:

In the postcondition of `body`, is `h` in `inv h (U32.v i + 1)` a typo? Should it be `h'` instead? If I make it `h'` the code verifies.

(Also, the first conjunct in the postcondition of `body` is not required.)

**Comment by aseemr** [comment]
This style of lambda expressions does not anyway work very well with the 2-phase typechecker. It is working here since `C.Loops.for` does not abstract over the wp.

**Comment by parno** [comment]
Ah, you're right, that was a typo in the example.  I just tried the corrected example, and it works for me.  The original code that prompted this last month also appears to be working with the latest F* master, so it looks like this was fixed at some point.  Sorry for the confusion!
