### ISSUE TITLE
Failure("Impossible: tc_datacon: length of annotated universes not same as instantiated ones")

### ISSUE THREAD

**Issue by kkohbrok** [FStarLang/FStar#1506]
The following program may not make much sense, but F* asked me to file a bug report and since I didn't find a similar, existing one, here it is:
```
module Test

type single_or_tuple (t1:Type0) (t2:Type0) =
  | S: t1
  | T: t1*t2
```
Both in interactive mode and on the CLI, it fails with:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: tc_datacon: length of annotated universes not same as instantiated ones")
```
Using F*-Version
```
F* 0.9.7.0~dev
platform=Linux_x86_64
compiler=OCaml 4.05.0
date=2018-07-26T14:46:40+0300
commit=d2f5753fd (dirty)
```

**Comment by fournet** [comment]
You need to provide the resulting type in this syntax, e.g. `| S: t1 -> single_or_tuple t1 t2` or stick to the simple syntax `| S of t1`. Anyway, F* should issue a nicer error message.
