### ISSUE TITLE
Add bitwise operators to typechecker/normalizer

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1513]
These should really come for free:

```
let _ = assert (FStar.UInt64.logor 0x8000000000000000UL 0x8000000000000000UL = 0x8000000000000000UL)

let _ = assert (FStar.UInt64.logand 0x8000000000000000UL 0x8000000000000000UL = 0x8000000000000000UL)

let _ = assert (FStar.UInt64.lognot 0x8000000000000000UL = 0x7FFFFFFFFFFFFFFFUL)
```

(+ via `assert_norm`)

I'm going to give this a go on Bug Squashing Monday; shouldn't be too hard to do in a day I hope.

**Comment by fournet** [comment]
I remember being confused by that one. Uniformity would be good, e.g. normalize all integer operatiors.

**Comment by msprotz** [comment]
https://github.com/FStarLang/FStar/commit/bfc3b4b62c4cd55c83b14a3b5a67aace49e3203b and subsequent commits, e.g. 03f47c7ad

**Comment by msprotz** [comment]
The shifts remain to be implemented. Please open a new issue if need be.

Thanks,

Jonathan
