### ISSUE TITLE
Inconsistent assumptions errors when rebuilding F*

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1518]
When rebuilding F*, I usually do:
- `git pull`
- followed by `make` which now builds: the OCaml snapshot, then proceeds to build ulib and ulib/ml

This almost invariably results in inconsistent assumptions errors. Our theory is that changing the F* compiler source files changes the internal OCaml hash (accessible via `ocamlobjinfo`) of the corresponding compiler modules, and then `fstartaclib`, which links against the internal compiler modules, is somehow not picking up on the changes.

Thanks,

Jonathan

**Comment by victor-dumitrescu** [comment]
Just to note that while looking into this I realised that in some circumstances the `make` succeeds, without actually rebuilding `fstartaclib`, in which case the inconsistent assumption error can arise when actually trying to run native tactics.

**Comment by victor-dumitrescu** [comment]
Related: Another kind of build error I am getting when fast-forwarding is `make[2]: *** No rule to make target 'LowStar.Buffer.fsti', needed by 'LowStar.Buffer.fsti.checked'. Stop.` when the corresponding F* file has been renamed or removed.

**Comment by victor-dumitrescu** [comment]
It's not clear to me why changes to the compiler don't get picked up when building `fstartaclib`. The simplest fix I can think of is to require `fstartaclib` to be rebuilt whenever the `compiler-libs`, which seems like a reasonable thing to do anyway (dc063627de9642a256648e6fe10e5f4d067acde2).

**Comment by msprotz** [comment]
> make[2]: *** No rule to make target 'LowStar.Buffer.fsti', needed by 'LowStar.Buffer.fsti.checked'. Stop.
This is because the .depend file in ulib does not get regenerated correctly. One way to fix it is to always regenerate it, no matter what (it's cheap-ish).

I think rebuilding fstartaclib unconditionally is ok; it's OCamlbuild-based, anyhow, right? So there won't be any un-necessary work.
