### ISSUE TITLE
Typing problem with option and function types

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#152]
Hi, I was experimenting and came across the following problem:
The program

```
module Fail 

assume val foo : unit -> Tot (option (unit -> Tot unit))
assume val fail : x : unit {is_Some (foo x)} -> u : unit{((Some.v (foo x)) u) = ()}
```

raises the following error:

```
"Too many arguments to function of type (projectee:_122:(option ){(is_Some _122)} -> Tot a); got (Some.v (foo x) u)"
```

although the only argument for `Some.v` is `(foo x)` and `u` should be processed only by the resulting function.

**Comment by catalin-hritcu** [comment]
It seems a problem with our projectors. The following simpler example also fails:
```
val f : option (unit -> Tot unit) -> unit
let f x = Some.v x ()
```
for the wrong reasons:
```
Too many arguments to function of type (projectee:_122:(option ){(is_Some _122)} -> Tot a); got (Some.v x ())
```

**Comment by vkanne-msft** [comment]
Reproducible with --universes flag

**Comment by catalin-hritcu** [comment]
This is fixed now, probably by @tahina-pro 's latest changes?
