### ISSUE TITLE
assume val in fsti?

### ISSUE THREAD

**Issue by lastland** [FStarLang/FStar#1520]
It seems that `assume val` does not work in `.fsti` files. For example:
```
module Example

assume val x: int
```
F* will report a weird error claiming that `(Error) The qualifier list "[assume assume]" is not permissible for this element: duplicate qualifiers`.

The above example works fine if it's in some `.fst` file though.

Is this behavior expected?

**Comment by aseemr** [comment]
Yeah, this is by design. In an `.fsti`, a `val` only declaration is already treated like an `assume`, in that we can use it further without the definition. In a `.fst`, one needs to explicitly add the `assume` qualifier.

Do you have a specific use-case where you need it?

**Comment by lastland** [comment]
I'm mostly just wondering if this is by design.

In my use case, I have some automatic generated F* `val`s without definitions. Not having an implementation in the `.fst` file gives me an error. This is not a problem though, since I just need to generate some code to `assume` them in the `.fst`.

**Comment by mtzguido** [comment]
Just to see that I follow... The situation is this:
`I.fsti`:
```
module I
val x : int
val y : int
```
`I.fst`:
```
module I
let x = 2
```

How to assume only `y`? This fails of course with "`y` is not implemented". The only solution I came up with is defining `let y = magic ()`, but that's not very nice. Doing `assume val y : int` also complains that `y` is not implemented.

Should there be a way to do this (without adding modules)?

**Comment by ice1000** [comment]
maybe

```fstar
assume val y_impl: int
let y = y_impl
```
?

**Comment by mtzguido** [comment]
Right, that would work :). I was trying to find a way that does not give a definition to `y` *internally*, but it probably doesn't matter. We could mark it `irreducible` if need be.
