### ISSUE TITLE
Inference failure, (Error 54) (*?u1624*) _ is not equal to the expected type

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1525]
I ran into this error a few times already in different (big) contexts, but here's a standalone repro. Since the LHS is a uvar, my intuition is that we're creating it on the wrong context.

```f#
noeq
type mydep a b =
    | Mk : x:a -> y:(b x) -> mydep a b
```
```
TestSigmaProj.fst(6,23-6,24): (Error 54) (*?u1624*) _ is not equal to the expected type a (see also TestSigmaProj.fst(6,11-6,12))
```
Annotating `(b : a -> Type)` fixes it. Perhaps the uvar for `b`'s type does not have `a` in scope? Is that expected? That rings a bell, from #291 and #1074, but it'd be nice to confirm (also given that #291 has changed a bit).

**Comment by aseemr** [comment]
This works now, and my guess is https://github.com/FStarLang/FStar/pull/2473. Closing.
