### ISSUE TITLE
Unsoundness of shortcircuiting

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#154]
Here is a minimized version of an example that verifies, but it shouldn't. It basically says that searching an element only in the head of a list is the same as searching the whole list.
```
val search : x:int -> l:(list int) -> Tot (r:bool{r <==> mem x l})
let rec search x l =
  match l with
  | [] -> false
  | n :: l' -> x = n || (false && search x l')

(* this equivalent thing fails as it should
val search' : x:int -> l:(list int) -> Tot (r:bool{r <==> mem x l})
let rec search' x l =
  match l with
  | [] -> false
  | n :: l' -> x = n || (search' x l' && false)
*)

(* this equivalent thing fails as it should
val search' : x:int -> l:(list int) -> Tot (r:bool{r <==> mem x l})
let search' x l =
  match l with
  | [] -> false
  | n :: l' -> x = n
*)

(* this equivalent thing fails as it should
val search' : x:int -> l:(list int) -> Tot (r:bool{r <==> mem x l})
let rec search' x l =
  match l with
  | [] -> false
  | n :: l' -> if x = n then true else (if false then search' x l' else false)
*)
```

**Comment by catalin-hritcu** [comment]
F* is **as unsound as it gets** at the moment. Today, I've run over one more dead wrong example that type-checks. I've minimized it to this statements about any list having any property you like (note, one would expect this to hold only when `all` returns `true`).
```
val all : p:(int -> Tot bool) -> xs:list int ->
            Tot (r:bool{forall x. mem x xs ==> p x})
let rec all p xs =
  match xs with
  | [] -> true
  | x :: xs' -> p x && all p xs'
```

**Comment by catalin-hritcu** [comment]
We need to fix this before releasing the binaries for the course. I don't want this kind of homework solutions:
```
val ff : u:unit -> Lemma (False)
let ff u = ignore (all (fun _ -> false) [42])
```
Working on minimizing this further if possible.

**Comment by ckeller** [comment]
After inspecting the Z3 queries on `bug154.fst`, the bug comes from an hypothesis `(= (BoxBool false) (BoxBool true))` at line 24,090. Inspecting further...

**Comment by catalin-hritcu** [comment]
My guess is that the bug is in short-circuiting and.

**Comment by ckeller** [comment]
That was my first idea, but the function that flattens and simplifies and in `tosmt/term.fs` is correct.

**Comment by catalin-hritcu** [comment]
Type-checking of short-circuiting operators is bogus at the moment. As far as Chantal and me understand, in order to type-check `b1 && b2` F* checks that `b1` and `b2` are booleans, and then tries to prove the post-condition assuming the result is `b2` and in an environment in which `b1` holds. For this to be correct, one should also prove the post-condition, assuming the result is `false` and in an environment in which `not b1` holds. Basically `b1 && b2` should be equivalent to `if b1 then b2 else false` not to `match b1 with true -> b2` (an incomplete pattern match!). I also don't undestand why `&&`  and `||` are not simply desugared to the correct ifs (or matches).

**Comment by nikswamy** [comment]
Basically, I was mistakenly treating short-circuiting for WPs in the same way as i was short-circuiting well-formedness conditions that were just in `Type`. This was blatantly wrong ... Sorry! In effect, I now generate WPs for && and || that corresponds to their desugaring as conditionals.

**Comment by catalin-hritcu** [comment]
Thanks a lot for fixing this Nik!
