### ISSUE TITLE
Building the snapshot is too slow (on Cygwin?)

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1541]
@s-zanella and others report that building the snapshot has recently become very slow (~15mins). We should look into the cause, as it takes ~1min for many others. Perhaps Cygwin is to be blamed, but just guessing for now.

**Comment by aseemr** [comment]
https://superuser.com/questions/877051/cygwin-from-windows-very-slow-laggy

This helps for me.

**Comment by s-zanella** [comment]
@nikswamy suggested https://stackoverflow.com/questions/28410852/startup-is-really-slow-for-all-cygwin-applications
I tried **Solution 1** in the top-rated answer and it improved things for me (2 1/2 min down from 4 min).

**Comment by catalin-hritcu** [comment]
This seems solved. Please document this on the wiki if necessary.
