### ISSUE TITLE
October 2018 work items

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1548]
1. F* style guide and auto-formatting (https://github.com/FStarLang/FStar/wiki/Style-guide)

2. Unifier bug and typeclasses (cf.  #1486)

3. Calculational proofs #1549

4. Completing cross-module inlining and applying it to LowParse (https://github.com/FStarLang/FStar/wiki/Cross-module-Inlining)

**Comment by ice1000** [comment]
Any decision about proof-search or case-splitting in editor support?

**Comment by nikswamy** [comment]
@ice1000 : Not sure what you mean by "proof-search". Can you say more?

Case-splitting in the editor is nice, but it's not yet scheduled as a work item. We'll take note of your up-vote.

@valera-rozuvan : So far, it's just a wiki page. Maybe once we reach some local agreement about it, we can promote it to the source tree.

**Comment by ice1000** [comment]
@nikswamy Proof-Search is something like filling a "whole" automatically (Idris, Agda have this), where "whole"s are unfinished parts of a program whose type can be inferred according to the context.

**Comment by nikswamy** [comment]
F* takes a very different approach to proof search: SMT.
Holes can be (and are) filled by higher-order unification.
Recently, we gained support for holes to be filled using a user-provided tactic (see, e.g., how typeclasses are implemented).

That said, it would be nice to have more type-directed program completion. I don't know of anyone working directly on that in F* at the moment.

**Comment by ice1000** [comment]
z3 supports exporting proof.

**Comment by aseemr** [comment]
Not really an issue, closing.
