### ISSUE TITLE
FStar.ULexing.Error with no source filename or line number

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/FStar#1562]
This is low priority, as I have a workaround.

[test.txt](https://github.com/FStarLang/FStar/files/2480419/test.txt)
The attached .fst file reproduces the bug.  There is some whitespace after an FSDOC comment, and it triggers the bug.  Removing the trailing whitespace resolves it.

This is the output I see:

$ C:/Users/barrybo/everest/FStar/bin/fstar.exe --odir . --codegen Kremlin --lax test.fst
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
FStar_Ulexing.Error

But without a filename or line number, it's hard to figure out what fsdoc line has the unexpected whitespace.

**Comment by nikswamy** [comment]
I'm closing this and merging with another issue on fsdoc parsing difficulties.
