### ISSUE TITLE
Error locations when using assert_norm are off

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1563]
Compare:

<img width="666" alt="screen shot 2018-10-15 at 4 58 30 pm" src="https://user-images.githubusercontent.com/10673049/46984754-a2860300-d09b-11e8-9e56-bef489ac68b2.png">

with:

<img width="651" alt="screen shot 2018-10-15 at 4 58 40 pm" src="https://user-images.githubusercontent.com/10673049/46984756-a4e85d00-d09b-11e8-9793-53cfe9429e5c.png">

Thanks,

Jonathan

**Comment by nikswamy** [comment]
There's work on this by Qunyan in a branch. I'll try to revive it.
