### ISSUE TITLE
assertion failure: CheckNoUvars: Unexpected unification variable remains

### ISSUE THREAD

**Issue by petercommand** [FStarLang/FStar#1569]
I got this error
```
(Error) ASSERTION FAILURE: (<input>(6,24-6,28)) CheckNoUvars: Unexpected unification variable remains: (*?u8*) _
F* may be in an inconsistent state.
Please file a bug report, ideally with a minimized version of the program that triggered the error.
```
with the program
```
module Test1
open FStar.Classical
open FStar.Tactics

val test: 4 == pow2 2
let test = give_witness Refl
```

**Comment by aseemr** [comment]
Hi @petercommand:

1. With latest F* master, the error is a bit better, in that it does not crash but gives an error about an implicit not resolved.

2. Instead of `give_witness`, we could use `FStar.Squash.return_squash`:

```
val test: 4 == pow2 2
let test = Squash.return_squash Refl
```

**Comment by petercommand** [comment]
Hi @aseemr:
Thanks!

**Comment by petercommand** [comment]
Hi, thanks for the explanation!
> With give_witness, the return type of give_witness is Lemma (ensures a), which does not unify with squash (equals 4 (pow2 2)).

However, the definition of ```give_witness``` is ```let give_witness #a x = return_squash x```, and this definition type checks. Is this because ```squash a``` can be automatically transformed to ```Lemma (ensures a)```, but not the other way around?

**Comment by aseemr** [comment]
You are right. In the definition of `give_witness`, `x:a` and so the implicit in `return_squash` can be inferred as `a`.

But in the proof for test `give_witness Refl`, the type of `Refl` itself has unification variables, I think. If we help F* by providing those, then it works fine:

```
let test = give_witness (Refl <: equals 4 (pow2 2))
```
Now it can infer the implicit and the proof succeeds.

**Comment by petercommand** [comment]
Hi,
```
let test = give_witness (Refl <: equals 4 (pow2 2))
```
Nice!
Hmm..What are the rules for these automatic transformation? Are these transformations related to subtyping?

**Comment by aseemr** [comment]
As far as SMT is concerned, they are almost equivalent:

```
assume val a :Type0

let foo (x:squash a) :Lemma a = ()

assume val lemma (_:unit) :Lemma a

let bar () :squash a = lemma ()
```

However, they are a bit different for unification in that for unification variables that appear only in the proof irrelevant parts (e.g. `ensures`), F* may not be able to solve for them.

**Comment by aseemr** [comment]
Closing the issue, please reopen if needed.
