### ISSUE TITLE
Incompatible effect not recognized in Tot implementation of foldl.

### ISSUE THREAD

**Issue by fmrl** [FStarLang/FStar#157]
I'm attempting to write a total implementation of foldl. I would expect the following code to fail because the function f is not typed as a total function but that's not what the error message reports:

```
module Module

   val tot_foldl: ('a -> 'b -> 'a) -> 'a -> list 'b -> Tot 'a
   let rec tot_foldl f a l =
      match l with
        | [] -> a
        | hd::tl -> tot_foldl f (f a hd) tl

(*
issue-tot_foldl-1.fst(7,20-9,0) : Error
(issue-tot_foldl-1.fst(7,20-9,0)) Failed to solve the sub-problem
	(U4913 'a 'b f a l hd tl) (Typ_app(Typ_uvar, [7 args]))
		=(TOP)
	_12743:(list (U4905 'a 'b f a l hd tl)){(%[_; _12743] << %[a; l])} (Typ_refine) (guard (U4914 'a 'b f a l hd tl))
Which arose because:
	TOP
Failed because:free-variable check failed on a non-redex
*)
```

**Comment by ad-l** [comment]
The problem is that the default heuristics for proving termination doesn't work for foldl since the second argument of the function structurally grows for the << relation: this is the meaning of %[_; _12743] << %[a; l]. Section 5.3 of the F* tutorial explains how to deal with functions like that: the followng should typecheck fine

```
   val tot_foldl: ('a -> 'b -> Tot 'a) -> 'a -> l:list 'b -> Tot 'a (decreases %[l])
   let rec tot_foldl f a l =
      match l with
        | [] -> a
        | hd::tl -> tot_foldl f (f a hd) tl
```

**Comment by catalin-hritcu** [comment]
The error message here is a bit mind-blowing though. Sorry.

**Comment by fmrl** [comment]
No worries and thanks for the tip. I'll check out the relevant section of the tutorial. :)
