### ISSUE TITLE
Should `A u = B` normalize to `false`? Currently it does not.

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/FStar#1571]
Consider the following inductive type:
```
type t : eqtype = | V of nat | W
```
Then, given a _variable_ `n: nat`, it seems that F* does not normalize `V n = W`. Indeed, the following fails:
```
let _ : (n: nat) -> squash (not (V n = W)) = _ by (
  let open FStar.Tactics in
  let n = intro () in
  norm [delta; iota; zeta; primops];
  dump "after norm";
  trivial ();
  qed ()
)
```
`Not a trivial goal`

If `V` has no arguments, or if `n` is a constant, then normalization will work.

If I define my own equality, then normalization will also work, as shown by the success of the following code:
```
let t_eq (t1 t2: t) : Tot (b: bool { b == true <==> t1 == t2 } ) =
  match t1, t2 with
  | V n1, V n2 -> n1 = n2
  | W, W -> true
  | _ -> false

let _ : (n: nat) -> squash (not (V n `t_eq` W)) = _ by (
  let open FStar.Tactics in
  let n = intro () in
  norm [delta; iota; zeta; primops];
  dump "after norm";
  trivial ();
  qed ()
)
```

**Comment by aseemr** [comment]
This should work, looking at it.

**Comment by mtzguido** [comment]
This rings a bell: `eq_tm` seems to be missing a check for `Tm_fvar f -- Tm_app (Tm_fvar f', _)` when both `f` and `f'` are `Data_ctor`

**Comment by aseemr** [comment]
Thanks Guido for the pointer, this is fixed now.
