### ISSUE TITLE
Boolean && expecting a ghost value?

### ISSUE THREAD

**Issue by danelahman** [FStarLang/FStar#1579]
I was playing around with some binary trees and encountered the following.

In its current form, the next block of code typechecks
```fstar
module Test

open FStar.Heap
open FStar.ST

noeq type snode = 
{
  p : ref stree;
  c : ref nat;
  l : ref stree;
  r : ref stree
}
and stree = option snode

let rec snode_eq (x y:snode) : St bool =
  match !x.p , !y.p with
  | None , None -> true
  | Some x_p , Some y_p -> (
      let b    = snode_eq x_p y_p in 
      let b'   = !x.c = !y.c in 
      let b''  = stree_eq !x.l !y.l in
      let b''' = stree_eq !x.r !y.r in
      b && b' && b'' && b'''
    )
  | _ , _ -> false

and stree_eq (x y:stree) : St bool =
  match x , y with
  | None , None -> true
  | Some x' , Some y' -> snode_eq x' y'
  | _ , _ -> false
```

But if I inline `snode_eq x_p y_p ` for `b` in the definition of `snode_eq`, I get `Test.fst(25,6-25,24): (Error 58) Expected a ghost expression; got an expression "Test.snode_eq x_p y_p <: FStar.ST.STATE Prims.bool" with effect "St"`

**Comment by danelahman** [comment]
@mtzguido pointed out that this seems to be something special to `&&` because the following typechecks:

```
assume val f : bool -> bool -> bool

let rec snode_eq (x y:snode) : St bool =
  match !x.p , !y.p with
  | None , None -> true
  | Some x_p , Some y_p -> (
      //let b    = snode_eq x_p y_p in 
      let b'   = !x.c = !y.c in 
      let b''  = stree_eq !x.l !y.l in
      let b''' = stree_eq !x.r !y.r in
      snode_eq x_p y_p `f` (b' && b'' && b''')
```

**Comment by mtzguido** [comment]
What's funnier is that this also typechecks, by punning `&&`:
```fstar
open FStar.Heap
open FStar.ST

noeq type snode = 
{
  p : ref stree;
  c : ref nat;
  l : ref stree;
  r : ref stree
}
and stree = option snode

let (&&) = (&&) (* trick F*! *)

let rec snode_eq (x y:snode) : St bool =
  match !x.p , !y.p with
  | None , None -> true
  | Some x_p , Some y_p -> (
      //let b    = snode_eq x_p y_p in 
      let b'   = !x.c = !y.c in 
      let b''  = stree_eq !x.l !y.l in
      let b''' = stree_eq !x.r !y.r in
      snode_eq x_p y_p && (b' && b'' && b''')
    )
  | _ , _ -> false

and stree_eq (x y:stree) : St bool =
  match x , y with
  | None , None -> true
  | Some x' , Some y' -> snode_eq x' y'
  | _ , _ -> false
```
Inlining all of the conjuncts works too.

**Comment by aseemr** [comment]
This is a known limitation and documented here: https://github.com/FStarLang/FStar/wiki/Migrating-code-to-universes, see the 4th point. My guess is when you trick F*, it is no longer treated as a short-circuiting operator but not sure.

**Comment by danelahman** [comment]
Should we then just do this trick in Pervasives to get rid of the limitation mentioned in that 4th point?

**Comment by msprotz** [comment]
But then if you override (&&) you lose the short-circuiting semantics, because it becomes a regular application? I'd rather have an error than see:

`(print_endline "1"; true) && (print_endline "2"; true)` print both 1 and 2...

or am I missing what the redefinition of (&&) does?

**Comment by mtzguido** [comment]
That's right, that'll happen if you do this trick. What I'd prefer to both alternatives is desugaring/elaborating that to:
```f*
if (print_endline "1"; true)
then (print_endline "2"; true)
else false
```
or similar. But then we won't extract that to OCaml's `&&`, which might be undesirable. No real strong feeling though, I think we can live with this.

**Comment by msprotz** [comment]
You can always wrap this if-then-else in a `Tm_meta` so that the information can be recovered at extraction-time. We do something similar to turn back matches into if-then-elses, right?

**Comment by msprotz** [comment]
Actually it'd be important to do this for the quality of generated C code.

**Comment by mtzguido** [comment]
We decided that the current behaviour is fine, but we need to add a better error message

**Comment by s-zanella** [comment]
I'm hitting this issue too. 
Defining `let (&&) = (&&)` or using an `if ... then ... else` doesn't work for loop conditions extracted to C.
Any other work around?

**Comment by aseemr** [comment]
Let binding the arguments explicitly should work. Is that not desirable for C extraction or something?

**Comment by s-zanella** [comment]
KreMLin forbids `let` bindings in loop conditions:

_The translation of this while loop's test expression gives rise to let-bindings, which, once hoisted, would change the evaluation semantics. Please rewrite your code._

**Comment by s-zanella** [comment]
@kkohbrok recently ran into definitions losing short-circuiting semantics when trying to define a boolean implication operator:
```FStar
unfold let ( ===> ) (a b:bool) = not a || b
let ok (o:option bool) = not (Some? o) || Some?.v o
let ko (o:option bool) = Some? o ===> Some?.v o
```

**Comment by aseemr** [comment]
The error message is now more explicit:

```
Test.fst(22,6-22,22): (Error 58) Expected a ghost expression (arguments to short circuiting operators must be pure or ghost); got an expression "Test.snode_eq x_p y_p" with effect "St"
1 error was reported (see above)
```

Closing, thanks for reporting and the discussions!
