### ISSUE TITLE
Improve backticks/infix syntax

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1604]
Backticks can currently only enclose lowercase identifiers; I don't see why they shouldn't be able to  also enclose uppercase identifiers, like so:
```fstar
type infix = | Infix: int -> int -> infix
let f x y = x `Infix` y
```

This syntax would be much more powerful if backticks could enclose entire terms. for example:
```fstar
assume val foo: int -> int -> int -> bool
let g x y z = y `foo x` z
```

**Comment by mtzguido** [comment]
Definitely agree with point 1, but for the second we would need to disambiguate things like
```fstar
a `b` c `d` e
```
(It could be `d (b a c) e` or `b a (d c e)`.)

Any preference? FWIW GHCi associates to the left.

**Comment by A-Manning** [comment]
I think having backticks nest (as in `c b d a e`) is somewhat counterintuitive. Left associativity seems most familiar.

**Comment by mtzguido** [comment]
Yup, agreed! I did just that, merging soon.
