### ISSUE TITLE
Generate discriminator for single-case sum type

### ISSUE THREAD

**Issue by ad-l** [FStarLang/FStar#1605]
The following fails:
```fstar
type t = | X of int
let f (x:t) = X? x
```
while this succeeds:
```fstar
type t = | X of int | Y
let f (x:t) = X? x
```
Not a big deal in practice but annoying for meta-programmed types that end up having a single case

**Comment by aseemr** [comment]
Seems like a missed case, unless we are treating it like a record. Will take a look.

**Comment by aseemr** [comment]
This is fixed, thanks for reporting it!
