### ISSUE TITLE
FStar_UInt32.ml issue on 32bit machines

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#1608]
As for ML code we encode machine integers to `int` it seems that on 32 machines we are using 31 bits (OCaml integers) to encode 32 bit words.
https://github.com/FStarLang/FStar/blob/master/ulib/ml/FStar_UInt32.ml#L1

I think we could do the same as `FStar_UInt64.ml` module and use OCaml's `stdint` library instead. The other benefit is that we could align all those `.ml` modules to provide the same functions such as `to_string_hex`. I don't think there are much issues in doing so except that when I tried to make that change there were `[@deriving]` attributes on type definitions in `FStar_UInt8.ml` which caused problems.

What do people think ? Thanks ! : )

**Comment by s-zanella** [comment]
There are 32-bit versions of some modules in `ulib/ml/32bit` that don't have this issue. For instance, `ulib/ml/32bit/FStar_UInt32.ml` uses `Int64.t` to encode 32-bit integers.
We discussed using `stdint` before; I think that would be a good approach.

See also https://github.com/FStarLang/FStar/issues/1332

**Comment by mtzguido** [comment]
This is what PR #1850 is about.

**Comment by mtzguido** [comment]
#1850 is now merged.
