### ISSUE TITLE
`FStar.Integers.v` doesn't work in some refinements of dependent function types

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1612]
```
module Test

open FStar.Integers

/// Works
let f (x: Seq.seq UInt8.t) (l: UInt32.t { UInt32.v l = Seq.length x }) =
  ()

/// Fails
let g (x: Seq.seq UInt8.t) (l: UInt32.t { FStar.Integers.v l = Seq.length x }) =
  ()

```

I believe this hinders wider adoption of FStar.Integers, since this pattern is frequent in stateful functions, e.g.

```
let update (prev: G.erased bytes) (len: UInt32.t { v len = S.length (G.reveal prev) }) ...
```

this may be one of the issues that @fournet referred to when he said he had hit some issues with FStar.Integers.

Thanks,

Jonathan

**Comment by nikswamy** [comment]
I looked into this today. Here's a slightly smaller test.

```
module IntegerTest
open FStar.Integers
assume val l : UInt32.t
#set-options "--debug IntegerTest --debug_level High --debug_level Rel --debug_level RelDelta"
let test (n:Prims.nat) = FStar.Integers.v l = n
```

Internally, we end up having to solve the following unification problems, from the LHS and RHS of the equality, respectively.

```
169731:	y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y} 
		<:
	(* Instantiating implicit argument in application *)
((n: Prims.nat) |- ?1 : Type) 

	
169732:	Prims.nat 
		<:
	(* Instantiating implicit argument in application *)
((n: Prims.nat) |- ?1 : Type) 
```

At this point, the rule for solving refinement subtyping by taking meets kicks in.

``
Trying to solve by meeting refinements:169731
[meet/join]: pairwise: y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y} and Prims.nat
head_matches (y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y}, Prims.nat) = MisMatch (Some Delta_equational_at_level 1) (Some Delta_constant_at_level 1)
Head of y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y} is y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y}
Head of Prims.nat is Prims.nat
Inlined Prims.nat to i: Prims.int{i >= 0}
head_matches (y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y}, i: Prims.int{i >= 0}) = MisMatch (Some Delta_equational_at_level 1) (Some Delta_constant_at_level 0)
head_matches_delta (y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y}, Prims.nat) = MisMatch (Some Delta_equational_at_level 1) (Some Delta_constant_at_level 0) (y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y}; i: Prims.int{i >= 0})
```

However, when trying to reduce both lower bounds to a type with a common head symbol, things fail. The RHS is unfolded to a refinement of `Prims.int`, but the LHS remains unreduced, since at this part of the algorithm, we are very restrictive in what symbols we are willing to unfold and `FStar.Integers.int_t` is not unfolded.

So, it looks like we have two syntactically incomparable types. We end up arbitrarily choosing to equate ?1 with the LHS (the first sub-problem below) and then trying to prove that RHS is equal to the LHS (second one). And that second one is doomed.

```
After meet/join refinements: 
169735:	y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y} 
		=
	(* Instantiating implicit argument in application *)
((n: Prims.nat) |- ?1 : Type) 

	
169734:	y:
FStar.Integers.int_t (FStar.Integers.Signed (FStar.Integers.Winfinite))
  {FStar.Integers.within_bounds (FStar.Integers.Unsigned (FStar.Integers.W32)) y} 
		=
	Prims.nat
```

We could do slightly better and instead of producing an equality problem for the second one, we could produce another subtyping problem for RHS <: LHS. That would be more general, but it wouldn't help in this case.

Interestingly, if you flip the order of the equality in the original example, it goes through, since the arbitrary choice goes the other way.

The real fix would be to tweak the algorithm so that it goes ahead and unfolds the definition of `int_t` in this case.

**Comment by nikswamy** [comment]
Trying a fix in nik_1612. See 5838a01eef508bfbbde858b0fcd3bb67c0e55403

**Comment by nikswamy** [comment]
fixed in master now
