### ISSUE TITLE
Nested let rec fails mysteriously in fstar-mode

### ISSUE THREAD

**Issue by hjfreyer** [FStarLang/FStar#1638]
Two versions of the same sieve of Eratosthenes code:

```
let rec cons_if_none_divide (n : pos) (l full : list pos) : Tot (list pos) = match l with
  | [] -> n :: full
  | hd :: tl -> if n % hd = 0 then full else cons_if_none_divide n tl full
                                                                
val sieve : nat -> Tot (list pos) 
let rec sieve k = match k with 
  | 0|1 -> []
  | 2 -> [2]
  | _ -> 
    let prev = sieve (k-1) in
    cons_if_none_divide k prev prev

let _ = assert ((sieve 0) = [])
```

This works fine. The only difference in Round 2 is embedding `cons_if_none_divide` into `sieve`:

```
val sieve2 : nat -> Tot (list pos) 
let rec sieve2 k = match k with 
  | 0|1 -> []
  | 2 -> [2]
  | _ -> 
    let prev = sieve (k-1) in
    let rec cons_if_none_divide (n : pos) (l full : list pos) : Tot (list pos) = match l with
      | [] -> n :: full
      | hd :: tl -> if n % hd = 0 then full else cons_if_none_divide n tl full
    in
    cons_if_none_divide k prev prev

let _ = assert ((sieve2 0) = [])
```

Upon type-checking the last line, fstar-mode simply says "assertion failed". But if you reduce `sieve2 0`, you indeed get an empty list.

It seems it's known that nested let recs don't behave nicely, but the lack of feedback here is particularly bewildering. 

Let me know if this is an fstar-mode bug; I don't really know how to tell the difference.

**Comment by catalin-hritcu** [comment]
Unfortunately, our SMT encoding is incomplete for functions with inner let recs. You can write and prove such functions, but using their definitions to complete other proofs via SMT is not yet possible. This is a long-standing limitation tracked in issue #851.

The workaround is indeed to hoist the nested `let rec` to the top level.

As for the error message, it just says that the SMT solver couldn't prove the assertion. Would it have helped if you would have gotten a warning when defining `cons_if_none_divide` within `sieve2`?

**Comment by aseemr** [comment]
We can add a warning about this (I recall it used to there at some point).

**Comment by aseemr** [comment]
F* now gives a warning: `(Warning) Definitions of inner let-rec cons_if_none_divide and its enclosing top-level letbinding are not encoded to the solver, you will only be able to reason with their types`.

Closing the issue, thanks for the report!
