### ISSUE TITLE
Error 247 could be more helpful

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1642]
```
/Users/jonathan/Code/hacl-star/vale/code/crypto/ecc/curve25519/FastMul_helpers.fsti(0,0-0,0): (Warning 247) /Users/jonathan/Code/hacl-star/vale/code/crypto/ecc/curve25519/FastMul_helpers.fsti.checked was not written, since some of its dependences were not also checked
```
this error message could be more helpful; right now, figuring out which modules were not checked require to use `--debug yes`, then grepping for a mention of "lax-checking" then concluding that this is the faulty module.

Thanks,

Jonathan

**Comment by aseemr** [comment]
F* loads the caches in the topological sort order and as soon as one of the modules is found to be stale/checked file not there, F* lax checks all subsequent modules, irrespective of whether they had an edge to the stale/missing module. We can at least print the first module in the error message.

**Comment by aseemr** [comment]
The message now is something like this (from the latest everest CI):

```
test/KrmlTest.fst(0,0-0,0): (Warning 247) ..\secure_api\out\runtime_switch\cache\KrmlTest.fst.checked.lax was not written, since some of its dependences were not also checked: cache file ..\secure_api\out\runtime_switch\cache\Crypto.AEAD.Main.fsti.checked.lax does not exist
```

It still tells you the *first* such file, there could be other such stale/non-existent files but printing all of them would require a bit of code restructuring. Closing it for now, please re-open if needed.
