### ISSUE TITLE
Module comparison is case-sensitive for options

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1643]
This causes issues in two places when writing Makefiles.

Generally, in a Makefile, one does:

```
%.fst.dump: %.fst
  fstar --dump_module $(basename $*) -o $@
```

however, because some files in the universe (ulib/prims, vale/operator) are *not* abiding by the convention of the uppercase first letter, then F* just does not trigger the module dump, requiring makefile authors to do:

```
%.fst.dump: %.fst
  fstar --dump_module $(subst operator,Operator,$(basename $*)) -o $@
```

because of a similar reason, F* generates empty krml files for prims and operator.

It would greatly simplify writing Makefiles if `dump_module` and `extract_module` were performing a case-insensitive comparison.

Thanks,

Jonathan

**Comment by mtzguido** [comment]
Should be fixed, let me know if you find any rough edge (or # 1644)

**Comment by msprotz** [comment]
Thanks Guido! That's great! One less $(subst prims,Prims) in my Makefile...
