### ISSUE TITLE
OCaml binary ignores --z3timeout 

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#165]
The current binary release (for Linux 64 bit) ignores the --z3timeout flag and always uses the default value of 5 seconds.

**Comment by catalin-hritcu** [comment]
If we're doing a re-release for the course, then this should be high on the priority list.

**Comment by catalin-hritcu** [comment]
This actually explains why Simon was always getting failures when testing our stuff no matter how high I was setting the timeout.

**Comment by catalin-hritcu** [comment]
@ad-l @nikswamy  Any news about this? `make test` (`seqproperties.fst`) fails on my machine because timeouts are ignored.

**Comment by nikswamy** [comment]
fixed
