### ISSUE TITLE
ulib fails to build (linux)

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1653]
```
$ make -C ulib
```
```
make: Entering directory 'FStar/ulib'
make FSTAR_HOME=.. -f Makefile.verify verify-core
make[1]: Entering directory 'FStar/ulib'
.depend:1: *** target pattern contains no '%'.  Stop.
make[1]: Leaving directory 'FStar/ulib'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory 'FStar/ulib'
```

**Comment by aseemr** [comment]
Our CI build happens on a Linux machine and it is working fine. Could someone with a Linux machine confirm please? @catalin-hritcu?

**Comment by catalin-hritcu** [comment]
I just tried ulib and it worked no problem. What version of make do you have? I'm on 4.2.1.

**Comment by A-Manning** [comment]
Make 4.1, on Ubuntu 18.04.2 LTS x86_64

**Comment by catalin-hritcu** [comment]
@A-Manning  Can you try this again in a completely clean repo?

**Comment by A-Manning** [comment]
Can you try this again in a completely clean repo?
`make -C ulib`
```
