### ISSUE TITLE
Cached dependencies generate fatal errors on subsequent invocations with different include paths

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1657]
This happened after I had a successful build with only Foo.fsti in my source directories. I later added Foo.fst, and the error showed up.

**Comment by msprotz** [comment]
I fixed it by blasting the checked files for Foo.fsti

**Comment by s-zanella** [comment]
`Lib.IntVector.fst` and `Lib.IntVector.fsti` are the only files in `lib` excluded from verification. The default target in the `lib/Makefile` won't generate `.checked` files for them. A wild guess: this occurred because `Foo.fst` expected its dependencies to be cached if `Foo.fsti` existed, but `IntVector` wasn't a dependency of `Foo.fsti`?

**Comment by msprotz** [comment]
Sorry, I should've been clearer. I had a successful build of HACL* on protz_integration2 with Lib.IntTypes.fsti but not Lib.IntTypes.fst in scope. I later moved Lib.IntTypes.fst to a directory that was on the include path, and that's when I had the error.

I suspect some corner case related to the new caching of dependencies.

**Comment by msprotz** [comment]
Here's a complete testcase because I was bitten by this bug again.

```
jonathan@alibecsurface2:/tmp $ cat A.fst
module A

let x = 42
jonathan@alibecsurface2:/tmp $ cat Test.fsti
module Test

let x = A.x
jonathan@alibecsurface2:/tmp $ cat Test.fst
module Test

let y = A.x
jonathan@alibecsurface2:/tmp $ fstar --cache_checked_modules --already_cached '* -A' A.fst
Verified module: A (0 milliseconds)
All verification conditions discharged successfully
jonathan@alibecsurface2:/tmp $ fstar --cache_checked_modules --already_cached '* -Test' Test.fsti
Verified i'face (or impl+i'face): Test (3 milliseconds)
All verification conditions discharged successfully
jonathan@alibecsurface2:/tmp $ fstar --cache_checked_modules --already_cached '* -Test' Test.fst
Verified module: Test (1 milliseconds)
All verification conditions discharged successfully
jonathan@alibecsurface2:/tmp $ rm Test.fst
remove Test.fst? y
jonathan@alibecsurface2:/tmp $ fstar --dep full Test.fsti
(Error 119) Expected an implementation of module test, but couldn't find one
1 error was reported (see above)
```

@aseemr may know more

**Comment by aseemr** [comment]
`Test.fst` is recorded as a dependence in `Test.fsti.checked` for parsing purposes (required for cycle detection). When the `.checked` file is read again (in the `dep` invocation) and `Test.fst` does not exist, it gives an error.

The same error would also occur in the following example:

```
aseemr@aseemr-dt1 ~/ev1/FStar
$ cat A.fst
module A

aseemr@aseemr-dt1 ~/ev1/FStar
$ fstar.exe --cache_checked_modules A.fst
Verified module: A (0 milliseconds)
All verification conditions discharged successfully

aseemr@aseemr-dt1 ~/ev1/FStar
$ cat B.fst
module B

open A

aseemr@aseemr-dt1 ~/ev1/FStar
$ fstar.exe --cache_checked_modules B.fst
Verified module: B (2 milliseconds)
All verification conditions discharged successfully

aseemr@aseemr-dt1 ~/ev1/FStar
$ rm -f A.fst

aseemr@aseemr-dt1 ~/ev1/FStar
$ fstar.exe --dep full B.fst
(Error 119) Expected an implementation of module a, but couldn't find one
1 error was reported (see above)

aseemr@aseemr-dt1 ~/ev1/FStar
$
```

What should the behavior be in such cases? Note that in my example above, even after removing `B.fst.checked`, we will get a typechecking error for `B.fst` (`A` does not exist). Whereas in the original example, we could make it work by F* detecting that `Test.fsti.checked` is invalid, and then treating it as such. But is this corner case worth the code changes?

**Comment by aseemr** [comment]
We are currently doing cycle detection in every F* invocation. Instead we can separate it into a new F* command that the makefiles can invoke once for the project. This would also get rid of the need for adding `.fst` as a dependence of `.fsti`.

**Comment by msprotz** [comment]
> But is this corner case worth the code changes?
It's blocking a use-case in EverCrypt, where one switches the EVERCRYPT_CONFIG variable to get a different code specialization (see branch protz_wasm and providers/evercrypt/config/wasm).

When `Test.fsti` tries to find `Test.fst` for cycle detection, can we just ignore the error and move on if `Test.fst` does not exist? Would that be ok?

In the meanwhile, which subset of files can I remove to get rid of this error? I.e., which .checked files do I need to blast manually?

**Comment by msprotz** [comment]
I guess I could remove the `.fsti.checked` but that would invalidate the entire dependency graph and force rebuilding everything, which is what I was trying to avoid.

**Comment by aseemr** [comment]
I have a fix with the following behavior:

```
aseemr@aseemr-dt1 ~/ev1/FStar
$ cat A.fst
module A

let x = 42

aseemr@aseemr-dt1 ~/ev1/FStar
$ cat B.fsti
module B

let x = A.x

aseemr@aseemr-dt1 ~/ev1/FStar
$ cat B.fst
module B

let y = A.x

aseemr@aseemr-dt1 ~/ev1/FStar
$ fstar.exe --cache_checked_modules A.fst
Verified module: A (6 milliseconds)
All verification conditions discharged successfully

aseemr@aseemr-dt1 ~/ev1/FStar
$ fstar.exe --cache_checked_modules B.fsti
Verified i'face (or impl+i'face): B (6 milliseconds)
All verification conditions discharged successfully

aseemr@aseemr-dt1 ~/ev1/FStar
$ fstar.exe --cache_checked_modules B.fst
Verified module: B (7 milliseconds)
All verification conditions discharged successfully

aseemr@aseemr-dt1 ~/ev1/FStar
$ ls A.fst.checked B.fsti.checked B.fst.checked
A.fst.checked  B.fst.checked  B.fsti.checked

aseemr@aseemr-dt1 ~/ev1/FStar
$ rm -f B.fst

aseemr@aseemr-dt1 ~/ev1/FStar
$ fstar.exe --dep full B.fsti
C:/cygwin64/home/aseemr/ev1/FStar/bin/../ulib/FStar.Pervasives.Native.fst.checked: C:/cygwin64/home/aseemr/ev1/FStar/ulib/FStar.Pervasives.Native.fst\
        C:/cygwin64/home/aseemr/ev1/FStar/bin/../ulib/prims.fst.checked

FStar_Pervasives_Native.ml: C:/cygwin64/home/aseemr/ev1/FStar/bin/../ulib/FStar.Pervasives.Native.fst.checked\


FStar_Pervasives_Native.krml: C:/cygwin64/home/aseemr/ev1/FStar/bin/../ulib/FStar.Pervasives.Native.fst.checked\

...
```

Filing a PR.

**Comment by msprotz** [comment]
Thanks Aseem! I've given your fix a try but I'm still hitting issues in the hacl-star repository (reported initially by @parno).

Here's what's happening, in a nutshell.

```bash
jonathan@genepi:/tmp $ cat A.fst
module A

module B = B
jonathan@genepi:/tmp $ cat B.fsti
module B
jonathan@genepi:/tmp $ cat B.fst
module B
jonathan@genepi:/tmp $ fstar --cache_checked_modules B.fsti
Verified i'face (or impl+i'face): B (0 milliseconds)
All verification conditions discharged successfully
jonathan@genepi:/tmp $ fstar --cache_checked_modules B.fst
Verified module: B (0 milliseconds)
All verification conditions discharged successfully
jonathan@genepi:/tmp $ fstar --cache_checked_modules A.fst
Verified module: A (0 milliseconds)
All verification conditions discharged successfully
jonathan@genepi:/tmp $ # Now imagine that you're running git pull, and due to some upstream refactoring, B.fst, B.fsti have been renamed to something else
jonathan@genepi:/tmp $ # Now you need to re-run the depency analysis to start a fresh build
jonathan@genepi:/tmp $ mv B.fst C.fst
jonathan@genepi:/tmp $ mv B.fsti C.fsti
jonathan@genepi:/tmp $ fstar --dep full A.fst
(Error 119) Expected an implementation of module b, but couldn't find one
1 error was reported (see above)
jonathan@genepi:/tmp $ # Here, we are stuck and the only solution is to git clean -fdx because this is a fatal error that cannot be suppressed. (If this seems strange, imagine that A.fst is generated automatically and will be later replaced with a proper copy. But for the time being, we just need a dependency analysis to get started.)
jonathan@genepi:/tmp $ # As a reminder:
jonathan@genepi:/tmp $ cat A.fst
module A

module B = B
jonathan@genepi:/tmp $ # Constrast this behavior with what happens when checked files are not present:
jonathan@genepi:/tmp $ cat D.fst 
module D

module B = B
jonathan@genepi:/tmp $ fstar --dep full D.fst
D.fst(3,11-3,12): (Warning 285) module not found in search path: b
# Here this is a mere warning, which is the behavior I'd like instead of error 119
```

Can we replace Error 119 with Warning 285?

**Comment by aseemr** [comment]
Thanks for this report. I think the trouble we are having is, instead of caching the dependence modules in the checked files, we are storing a kind of file system image of this data ... and so, if the checked file is read in a slightly different file system than what was there at the time of writing the checked file, these kind of errors come up.

I have an idea of how to fix it, will try it soon. Basically instead of storing the file system image, we should only store the module identifiers that a particular module depends on, and then let F* again map it to the file system.

**Comment by aseemr** [comment]
Hi @protz, can you please check the fix in the F* branch `aseem_1657`? The invariant is now that the behavior is same whether or not checked files are present. So, in both the cases that you have reported here the behavior is as you want.

**Comment by aseemr** [comment]
Merged into master. Closing the issue.

**Comment by msprotz** [comment]
Thanks Aseem, and sorry I didn't get a chance to test it out fast enough! I successfully managed to do a full build starting from a wildly out of date HACL build tree on my laptop.

I didn't get any dependency errors, so it looks like between your fix and the small tweaks I added, we should have better incrementality for HACL* builds.

Thanks for your help, this will be super helpful!
