### ISSUE TITLE
Inconsistent SMT encoding of `==` in patterns

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1660]
In the following program the double equality (`==`) in the pattern of the first lemma is encoded to Z3 as `Prims.eq2` whereas it is encoded as Z3 term equality the pre-condition of the second lemma. Since the pre-condition of `test` doesn't match the pattern, an instantiation of `inj` doesn't trigger and the proof of `test` fails.

```FStar
module M

assume val t : Type0

assume val f: t -> t

assume val inj: a:t -> b:t -> Lemma (requires f a == f b) (ensures a == b) [SMTPat (f a == f b)]

val test: a:t -> b:t -> Lemma (requires f a == f b) (ensures a == b)
let test a b = ()
```
The pattern in `inj` is encoded as `(Prims.eq2 M.t (M.f @x0) (M.f @x1))`.
The pre-condition of `test` is encoded as `(= (M.f @x0) (M.f @x1))`.

The proof succeeds when wrapping `==` as in
```FStar
let p a b = (f a == f b)

assume val inj: a:t -> b:t -> Lemma (requires f a == f b) (ensures a == b) [SMTPat (p a b)]

val test: a:t -> b:t -> Lemma (requires p a b) (ensures a == b)
```

**Comment by s-zanella** [comment]
After discussing this with @nikswamy and @aseemr, using `==` in patterns is unreliable. 

Z3 forbids the use of `=` in patterns so the only way of resolving this issue would be to consistently wrap `==` as `eq2` everywhere, which is undesirable. At some point in the past the pre-condition of `test` might have been encoded using `eq2` and this might have worked, but it is no longer the case.

One could work around this issue by using a multi-pattern `[SMTPat (f a); SMTPat (f b)]` but this results in a quadratic number of instantiations (one for every pair of applications of `f`). 
The usual trick is to instead state the injectivity of `f` in terms of its inverse as in

```FStar
assume val finv: t -> t
assume val inj: a:t -> Lemma (ensures finv (f a) == a) [SMTPat (f a)]
```

This results in a liner number of instantiations.

So to conclude, the plan on record to close this issue is to make F* emit a warning (maybe fatal) when using `==` in patterns.

**Comment by s-zanella** [comment]
A quick grep shows a few uses of `==` in patterns in `ulib` (plus some in `examples` and `hacl-star`):

- `List.Tot.Properties.precedes_append_cons_prod_r`
```FStar 
[SMTPatOr [ [ SMTPat (x << l); SMTPat (l == append l1 ((x, y) :: l2))]; 
            [ SMTPat (y << l); SMTPat (l == append l1 ((x, y) :: l2))] ] ]
```
Just use `append l1 ((x, y) :: l2)` ?

- `FStar.Monotonic.Witnessed.get_eq`
```FStar 
[SMTPat (get #world (fun _ -> v == v'))]
```
It's an abstracted term so probably it's fine.
- `FStar.Monotonic.Witnessed.set_eq`
```FStar
[SMTPat (set (v == v') w)]
```
Not easy to fix; remove?
- `LowStar.Monotonic.Buffer.loc_union_idem_1`:
```FStar
[SMTPat (loc_union s1 (loc_union s1 s2) == loc_union s1 s2)]
```
Just use `(loc_union s1 (loc_union s1 s2))`
- `FStar.UInt.to_vec_mod_pow2`
```FStar
[SMTPat (index (to_vec #n a) i); SMTPat (a % pow2 m == 0)]
```
Use `=`.
- `LowStar.Vector.forall_as_seq`
```FStar
[SMTPat (p (S.index s0 k)); SMTPat (S.slice s0 i j == S.slice s1 i j)]
```
Use `Seq.equal`
- `FStar.Buffer.modifies_buffers`
```FStar
{:pattern (frameOf b == rid /\ live h b /\ disjoint_from_bufs b bufs)}
```
Use `=`?

I fixed the one use in Vale (project-everest/hacl-star@a19335d6e2d4bac49ed6d919cf3784674197693e)
I'll prepare a PR to remove the occurences in `ulib`.

**Comment by aseemr** [comment]
We now get these kind of warnings when a theory symbol is used in the patterns:

```
ulib/FStar.List.Tot.Properties.fst(1010,2-1010,136): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern:  Prims.eq2 Prims.eq2
```

```
C:/cygwin64/home/everest/everest/hacl-star/secure_api/merkle_tree/MerkleTree.New.High.Correct.Base.fst(303,8-303,17): (Warning 271) Pattern uses these theory symbols or terms that should not be in an smt pattern: Prims.op_Division 2 Prims.op_Subtraction 1
```

@s-zanella , should we close this?

**Comment by s-zanella** [comment]
Yes, let's close this.
