### ISSUE TITLE
Process cleanup issues

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1672]
@arpj-rebola and myself are having trouble with Z3 processes not being cleanup up after F* is done. It looks like at this point in the code: 

https://github.com/FStarLang/FStar/blob/cdf0d858765c9ade3f09d75809ae0e0748a85ffb/src/fstar/FStar.Main.fs#L167

 `delta_env` is set up, but it is never used. As per

https://github.com/FStarLang/FStar/blob/cdf0d858765c9ade3f09d75809ae0e0748a85ffb/src/fstar/FStar.Universal.fs#L654

this should invoke `tcenv.solver.finished` after the batch mode TC is done, but we never get that call. 

Is this a bug, or is `delta_env` a remnant of a mode of operation that's not in use anymore?

**Comment by nikswamy** [comment]
delta_env was used to delay extending the environment with the contents of checked modules until the first unchecked module was encountered (which may never actually happen, in case all modules are already checked)

@aseemr worked on this code most recently. Did this behavior change, Aseem?

**Comment by aseemr** [comment]
@wintersteiger, Adrian, `FStar.Main` should be calling the cleanup routine in master now. Please reopen if you still see some issue.

**Comment by wintersteiger** [comment]
(CC @arpj-rebola)
