### ISSUE TITLE
Relational F*

### ISSUE THREAD

**Issue by joshjdevl** [FStarLang/FStar#168]
```
module OneTimePad
open Bytes
open String
open List
open Array

type eq a=x:a{|L x = R x|}
```

Error

```
ERROR: Syntax error near line 7, character 15 in file /tmp/fstar_VfYYdn
```

**Comment by catalin-hritcu** [comment]
This seems like relational F*? Current version of F* is not relational.

**Comment by joshjdevl** [comment]
@catalin-hritcu yes relational. How can I run the code from the [POPL14 paper](http://research.microsoft.com/en-us/um/people/fournet/papers/probabilistic-relational-verification-for-cryptographic-implementations.pdf)? Where is the version of F* which is relational?

**Comment by catalin-hritcu** [comment]
Try this: https://web.archive.org/web/20140223055443/http://research.microsoft.com/en-us/downloads/e9089b8e-8871-46a8-987b-75effdcf70e6/default.aspx

For some reason @nikswamy decided to remove the old binaries from the web, which I think is very bad for research reproducibility.

**Comment by catalin-hritcu** [comment]
Just a warning: version 0.7 of F* is no longer being maintained. So if you can make it work great, otherwise you can try to write directly to authors of the papers you're trying to reproduce, not to this for the most part unrelated github repo.

**Comment by joshjdevl** [comment]
Thank you for the feedback and links. I will try and contact the authors.

However, I still this is quite strange. The [homepage](https://fstar-lang.org/) of FStar first sentence of the second paragraph claims that cryptographic verification can be done and the third paragraph links to Github. This is completely misleading as there is evidently no working implementation available.

**Comment by catalin-hritcu** [comment]
I agree this is all a bit confusing. Crypto verification doesn't necessarily involve relational reasoning though. You can look here for examples of simple cryptographic constructions verified in F* 1.0:
https://www.fstar-lang.org/tutorial/tutorial.html#sec-cryptography-examples
There is also an ongoing effort to port miTLS to F* 1.0: https://github.com/mitls/mitls-fstar

This being said, there is still hope in the current F* team that F* 1.0 will one day also support relational reasoning. That's not the case at the moment though.

**Comment by joshjdevl** [comment]
I guess I will ask this here, even though its not an issue...

I would like to do a cryptographic verification using the one time pad primitive and verifying unlinkability properties. Any thoughts if this is possible with the current F* in this repo ?

**Comment by catalin-hritcu** [comment]
I guess that the most qualified to answer this are @fournet and @markulf

**Comment by markulf** [comment]
Apologies for being quiet for so long on this. Must have been a paper deadline. :(

Catalin's assessment is quite right. Low-level cryptographic proofs of the kind that you are trying to do seem to require relational reasoning.

Only if you can express the security obtained by a cryptographic primitive as a typed interface, you can continue to reason about a larger cryptographic protocol using the current F* in this repo. 

You could define a one-time pad primitive as CPA secure encryption in which a key must only be used once. Depending on what you want to do, this may be doable, but more likely what you really want is relational reasoning. Its worth also having a look at [Easycrypt](https://www.easycrypt.info/trac/).

**Comment by catalin-hritcu** [comment]
We are now working again on this using the recently added support for monadic reification. We might have a paper draft on this in the following weeks/months.

**Comment by catalin-hritcu** [comment]
Relational verification using the recent support for monadic reification works surprisingly well. We have a new paper draft on this https://arxiv.org/abs/1703.00055 that describes the cool examples in https://github.com/FStarLang/FStar/tree/c_relational-ci_r3/examples/rel (soon to be merged into `master`). So this is fixed now.
