### ISSUE TITLE
Calc only works with pure terms

### ISSUE THREAD

**Issue by R1kM** [FStarLang/FStar#1682]
The following code fails because the `f 1` and `f 2` statements have effect GTot instead of Tot

```
open FStar.Calc

assume val f: (n:nat) -> GTot nat

let test (n:nat) =
  calc (==) {
    f 1;
    == { admit() }
    f 2;
  }
```

An easy workaround is to let-bind terms for calc outside of the statement as follows, but it would be nicer to be able to inline them directly
```
let test (n:nat) =
  let a = f 1 in
  let b = f 2 in
  calc (==) {
    a;
    == { admit() }
    b;
  }

**Comment by mtzguido** [comment]
This should work by using `GTot` in `FStar.Calc`, and making the desugarer provide the implicit arguments explicitly (otherwise we fail when the typechecker infers an implicit to be an effectful term). I'll give it a go.

**Comment by mtzguido** [comment]
That works, but for some reason it decreases performance. Checking `examples/calc/Long.fst` goes from ~50s to ~100s on my computer. Will run some more tweaks before merging, hopefully improving things.

**Comment by R1kM** [comment]
Sounds good thanks! In the worst case, it's not blocking or anything, and using this workaround would probably be better than decreasing performance.

**Comment by mtzguido** [comment]
This is now fixed, and I also did some tweaks that improve performance a lot. There's still quite some room for improvement performance-wise, but closing this issue.
