### ISSUE TITLE
Unknown depdendencies

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1702]
I'm getting a bunch of the following messages (correctly):

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Failed to find dependences of Hacl.Bignum.Constants.fst")
```

It would be great if F* reported the depdency that it can't find. (Also there's an `i` missing in `depdendences`).

**Comment by wintersteiger** [comment]
And further:

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Name not found: t")
```

There are about a gazillion `t`s in our codebases, it would be great if F* could be a little more specific!

**Comment by mtzguido** [comment]
Would you happen to have repros for these? I don't know how to trigger the first one in the dependency analysis.

The second one comes from the SMT encoding, and seems serious.

Both of them should anyway be turned to proper errors, but I'm not yet sure what error message to provide :).

**Comment by wintersteiger** [comment]
Sorry, it's been too long for me to remember. It's quite possible that the first one has been fixed as part of the work on dependencies and checked files, etc. I think that at the time I was either working on Ed25519 or the Merkle trees in HaCl, but that's probably not enough information to find a repro :)

**Comment by mtzguido** [comment]
Can't really do anything here, the first message indeed seems impossible to me now, and I'm not so confident on the second, but would need a repro. I'm improving the error messages slightly and closing this.
