### ISSUE TITLE
Outputing F* to Z3 encoding process

### ISSUE THREAD

**Issue by jamesbarne** [FStarLang/FStar#1705]
Hi,

Is there any way for me to display or output the F* to SMT encoding as I verify my file? I am looking at this report http://prosecco.gforge.inria.fr/personal/hritcu/students/alejandro/report.pdf and am curious about how F* is translating my codes to Z3. 

Many thanks

**Comment by aseemr** [comment]
Hello! You could pass `--log_queries` flag to F* on the command line and it would dump a `queries-<module name>.smt2` file, which is the smt encoding that is sent to Z3.

**Comment by jamesbarne** [comment]
I just checked it out and wow there are certainly plenty to digest. 

Thank you for the reply.
