### ISSUE TITLE
Issues with proofs

### ISSUE THREAD

**Issue by newuser1212** [FStarLang/FStar#1708]
Hi there,

When verifying my code, sometimes I'm faced with this particular error `(Error) could not prove post-condition`.

It is hard to pinpoint what proofs are missing which just that line of error. Does F* provide any method to have a better understanding of what additional proofs are required?

**Comment by aseemr** [comment]
Hello!

F* should provide an error location with the message pointing to the line and the column numbers of the exact postcondition that failed. If so, one way to go about it is then is to add explicit assertions in the proof to see what facts are provable, and try to guide the solver towards the proof (or modify the specs). It is a bit of a manual process as of now.

In some cases, F* may not provide an error location. If you have some such example, please raise an issue with the program that exhibits the behavior. It is most probably an oversight in the typechecker in tracking the error locations properly.

Feel free to also add your example here and we will be happy to take a look at your proof and try to help out. Thanks!

**Comment by newuser1212** [comment]
This is not the same error but I need some help over this. This is my attempt to replicate the implementation of SHA3 (quite similar to the one in the repo), but I have no clue to why this error is popping up. It gets stuck at the `chi_overall` function, which says that the line `let tmpState = chi_outer_repeat y s tmpState in` is returning a unit instead of a state. The function `chi_outer_repeat` is already verified above and it should be returning state instead. 

Any help will be greatly appreciated. Thanks and sorry for the long post.
 

Error 
```
(Error) Subtyping check failed; expected type state; got type unit
```

Specs Code
```
//state
//fixed sequence of length 25 of uint64s
type state = lseq uint64 25

//readlane function
let readLane (s:state) (x:nat{x<5}) (y:nat{y<5}) : Tot uint64 =
  s.[x + 5 * y]

//writelane function
let writeLane (s:state) (x:nat{x<5}) (y:nat{y<5}) (z:uint64) : Tot state =
  s.[x + 5 * y] <- z

//chi step
let chi_inner (y:nat{y<5}) (tmpState:state) (x:nat{x<5}) (rhopiState:state) : Tot state =  
  writeLane rhopiState x y (readLane rhopiState x y ^. ((lognot (tmpState.[(x + 1) % 5])) &. tmpState.[(x + 2) % 5]))
  

let chi_inner_repeat (tmpState:state) (rhopiState:state) (y:nat{y<5}) : Tot state =
  repeati 5 (chi_inner y tmpState) rhopiState


let chi_outer (y:ℕ{y<5}) (rhopiState:state) (x:ℕ{x<5}) (tmpState:state): Tot state =
  let tmpState = tmpState.[x] <- readLane rhopiState x y in
  tmpState 
  
let chi_outer_repeat (y:nat{y<5}) (rhopiState:state) (tmpState:state) : Tot state = 
  repeati 5 (chi_outer y rhopiState) tmpState

let chi_overall (tmpState:state) (y:nat{y<5}) (rhopiState:state) : Tot state = 
  let tmpState = chi_outer_repeat y rhopiState tmpState in
  chi_inner_repeat tmpState rhopiState y   
```

Low* Code
```
val chi_inner:
  y:size_t{v y < 5}
  -> tmpState: state
  -> x:size_t{v x < 5}
  -> rhopiState:state
  -> Stack unit
  (requires fun h -> live h tmpState /\ live h rhopiState /\ disjoint tmpState rhopiState)
  (ensures fun h0 r h1 -> 
    modifies (loc rhopiState) h0 h1 /\ 
    as_seq h1 rhopiState == S.chi_inner (v y) (as_seq h0 tmpState) (v x) (as_seq h0 rhopiState))


let chi_inner y tmpState x s = 
  s.(x +! 5ul *! y) <- readLane s x y ^. ((lognot (tmpState.((x +. size 1) %. size 5)) &. tmpState.((x +. size 2) %. size 5)))


val chi_inner_repeat:
  tmpState:state
  -> rhopiState:state
  -> y:size_t{v y < 5}
  -> Stack unit
  (requires fun h -> live h tmpState /\ live h rhopiState /\ disjoint tmpState rhopiState)
  (ensures fun h0 r h1 ->
    modifies (loc rhopiState) h0 h1 /\
    as_seq h1 rhopiState == S.chi_inner_repeat (as_seq h0 tmpState) (as_seq h0 rhopiState) (v y))

let chi_inner_repeat tmpState s y =
  let spec h0 = S.chi_inner (v y) (as_seq h0 tmpState) in
  let h0 = ST.get() in
  loop1 h0 5ul s spec
  (fun x -> 
    Loop.unfold_repeati 5 (spec h0) (as_seq h0 s) (v x);
    chi_inner y tmpState x s 
  ) 
  
val chi_outer:
  y:size_t{v y < 5}
  -> rhopiState:state
  -> x:size_t{v x < 5}
  -> tmpState:state 
  -> Stack unit
  (requires fun h -> live h rhopiState /\ live h tmpState /\ disjoint rhopiState tmpState)
  (ensures fun h0 r h1 -> 
    modifies (loc tmpState) h0 h1 /\
    as_seq h1 tmpState == S.chi_outer (v y) (as_seq h0 rhopiState) (v x) (as_seq h0 tmpState))


let chi_outer y s x tmpState =
  let ab = readLane s x y in
  tmpState.(x) <- ab



val chi_outer_repeat:
  y:size_t{v y < 5}
  -> rhopiState:state
  -> tmpState:state
  -> Stack unit
  (requires fun h -> live h rhopiState /\ live h tmpState /\ disjoint rhopiState tmpState)
  (ensures fun h0 r h1 -> 
    modifies (loc tmpState) h0 h1 /\
    as_seq h1 tmpState == S.chi_outer_repeat (v y) (as_seq h0 rhopiState) (as_seq h0 tmpState))
    
let chi_outer_repeat y s tmpState =
  let spec h0 = S.chi_outer (v y) (as_seq h0 s) in
  let h0 = ST.get() in
  loop1 h0 5ul tmpState spec
  (fun x ->
    Loop.unfold_repeati 5 (spec h0) (as_seq h0 tmpState) (v x);
    chi_outer y s x tmpState
  )



val chi_overall:
  tmpState:state
  -> y:size_t{v y < 5}
  -> rhopiState:state
  -> Stack unit
  (requires fun h -> live h tmpState /\ live h rhopiState /\ disjoint tmpState rhopiState)
  (ensures fun h0 r h1 -> 
    modifies (loc rhopiState) h0 h1 /\ modifies (loc tmpState) h0 h1 /\
      as_seq h1 tmpState == S.chi_overall (as_seq h0 tmpState) (v y) (as_seq h0 rhopiState) /\   
      as_seq h1 rhopiState == S.chi_overall (as_seq h1 tmpState) (v y) (as_seq h0 rhopiState))
 


let chi_overall tmpState y s = 
  let tmpState = chi_outer_repeat y s tmpState in
  
  chi_inner_repeat tmpState s y
```

**Comment by aseemr** [comment]
With a quick look, the return type of `chi_outer_repeat` is `unit`, and so in the function `chi_overall`, the type of the first let binding is `unit`. Whereas the first argument of `chi_inner_repeat` is `state`. And therefore F* complains that it got type `unit` where it expected type `state`.

**Comment by newuser1212** [comment]
Hi there,

I edited the `chi_overall` function to this and got the could not prove post condition error. Am I overcomplicating the post conditions or and I missing something? Thank you in advance.

```
let chi_overall tmpState y s =
  chi_outer_repeat y s tmpState;
  chi_inner_repeat tmpState s y
```

**Comment by newuser1212** [comment]
Hi, is there any update on this?

**Comment by catalin-hritcu** [comment]
@newuser1212 If this is still a problem you could post it on https://fstar.zulipchat.com  We're using the issue tracking increasingly little for user help.

**Comment by aseemr** [comment]
Closing , since it seems that this, and other subsequent queries, were asked and answered in the hacl repo. Please reopen if necessary.
