### ISSUE TITLE
Intrinsic proof that fails for no apparent reason (extrinsic variant succeeds)

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#171]
Yannick Forster reported some strange behavior. He tried to verify insert intrinsically, but fstar failed to typecheck it. It can prove

```
val insert : f:('a -> 'a -> Tot bool){total_order 'a f} -> i:'a -> l:list 'a ->
             Tot (r : list 'a { permutation 'a r (i::l)})
```

but not

```
val insert : f:('a -> 'a -> Tot bool){total_order 'a f} -> i:'a -> l:list 'a{sorted f l} ->
             Tot (r : list 'a { sorted f r /\ permutation 'a r (i::l)})
```

He need to use the first version and then proof the lemma

```
(* for some reason, sortedness was not intrinsically provable *)
val insert_sorted : f:('a -> 'a -> Tot bool){total_order 'a f} -> i:'a -> l:list 'a {sorted f l} ->
                           Lemma (requires True) (ensures (sorted f (insert f i l)))
                           [SMTPat (insert f i l)]
let rec insert_sorted f i l =
  match l with
  | [] -> ()
  | hd :: tl ->
     if f i hd then () else insert_sorted f i tl
```

In Yannick' eyes, fstar should be able to prove the stronger version automatically, since the proof is really straightforward. I tried increasing the z3timeout (could that theoretically help in such situations?), but that also didn't help.

I'll put some files in `bug-reports` about this:
Working: `insertionsortcmp.fst`
Not working: `insertionsortcmpfails.fst`
Still now working: `insertionsortcmpfails2.fst`

**Comment by catalin-hritcu** [comment]
now `insertionsortcmp.fst` fails too ... not sure what's happening

**Comment by vkanne-msft** [comment]
unable to test. 
$ fstar --universes insertionsortcmpfails.fst
Warning: the module declaration "module InsertionSortCmp" found in file insertionsortcmpfails.fst does not match its filename. Dependencies will be incorrect.
D:\Sources\FStar\examples\bug-reports\insertionsortcmpfails.fst(11,0-12,60) (Warning): The 'opaque' qualifier is deprecated; use 'unfoldable', which is also the default
D:\Sources\FStar\examples\bug-reports\insertionsortcmpfails.fst(12,4-12,10) : Error
Identifier not found: [length]

**Comment by s-zanella** [comment]
I could reproduce this by updating the examples so that they use the correct dependencies.
```
$ bin/fstar.exe --universes examples/bug-reports/insertionsortcmp.fst 
Verifying module: InsertionSortCmp
All verification conditions discharged successfully

$ bin/fstar.exe --universes examples/bug-reports/insertionsortcmpfails.fst 
examples/bug-reports/insertionsortcmpfails.fst(23,71-29,29): (BoxBool_proj_0(InsertionSortCmpFails.sorted(_a__3488) (f__3489) @0))
Error: 1 errors were reported (see above)

$ bin/fstar.exe --universes examples/bug-reports/insertionsortcmpfails2.fst 
examples/bug-reports/insertionsortcmpfails2.fst(24,50-30,29): (Valid(ApplyTT@2 @0))
examples/bug-reports/insertionsortcmpfails2.fst(24,50-30,29): (Valid(ApplyTT@4 @0))
examples/bug-reports/insertionsortcmpfails2.fst(24,50-30,29): (Valid(ApplyTT@3 @0))
Error: 3 errors were reported (see above)
```

**Comment by tahina-pro** [comment]
In fact, I really don't even know why the automatic extrinsic proof `insert_sorted` succeeds at all; trying to prove the cons case "axiomatically" by the following attempt:
```
let insert_sorted_cons_false
  (a: eqtype)
  (f:(a -> a -> Tot bool){total_order a f})
  (i:a)
  (l:list a {sorted f l})
  (hd: a)
  (tl: list a)
  (insert_tl: list a {sorted f insert_tl /\ permutation a insert_tl (i::tl) } )
: Lemma
  (requires (l == hd :: tl /\ (f i hd == false)))
  (ensures (sorted f (hd::insert_tl) /\ permutation a (hd::insert_tl) (i::l)))
= ()
```
fails to prove `sorted f (hd::insert_tl)`. So my doubt is more on the success of `insert_sorted` rather than on the failure of intrinsic `insert`.

**Comment by s-zanella** [comment]
@tahina-pro `insert_sorted` knows more things about `insert_tl` than what you're assuming in your axiomatic proof. Namely, it knows that it's the result of `insert f i tl`, which is non-empty and can only have `i` or `hd` as head. Adding these facts the proof succeeds:
```F#
let insert_sorted_cons_false
  (a: eqtype)
  (f:(a -> a -> Tot bool){total_order #a f})
  (i:a)
  (l:list a {sorted f l})
  (hd: a)
  (tl: list a)
  (insert_tl: list a {sorted f insert_tl /\ permutation #a insert_tl (i::tl) /\ 
    (List.Tot.hd insert_tl == i \/ List.Tot.hd insert_tl == i)} )
: Lemma
  (requires (l == hd :: tl /\ (f i hd == false)))
  (ensures (sorted f (hd::insert_tl) /\ permutation #a (hd::insert_tl) (i::l)))
= ()
```

**Comment by nikswamy** [comment]
Confirmed that the intrinsic proof of sortedness in bug171.fst still fails

**Comment by nikswamy** [comment]
An indeed the intrinsic proof can be adapted to succeed with a stronger induction hypothesis. This works:

``

val insert_alt : #a:eqtype -> f:(a -> a -> Tot bool){total_order f} -> i:a ->
             l:list a{sorted f l} ->
             Tot (r:list a {sorted f r /\ permutation r (i::l) /\
                            (Cons? r /\ (let hd::_ = r in hd == i \/ (Cons? l /\ hd == Cons?.hd l)))
                            })
let rec insert_alt #a f i l =
  match l with
  | [] -> [i]
  | hd::tl ->
     if f i hd then i::l
     else hd :: insert_alt f i tl
```
