### ISSUE TITLE
Lexing fails on [l@l] in fsdoc

### ISSUE THREAD

**Issue by SECtim** [FStarLang/FStar#1713]
This does not verify (F* just crashes):
```fstar
module AnotherBug

(** [l@l] *)
let rec abc (a:int) : Tot bool = true
```

But this does (note the space after `@` in the fsdoc):
```fstar
module AnotherBug

(** [l@ l] *)
let rec abc (a:int) : Tot bool = true
```

Maybe related to/should be linked to #776.

**Comment by mtzguido** [comment]
This should be fixed by the removal of fsdoc @nikswamy

**Comment by SECtim** [comment]
Oh, you're planning on removing fsdoc? Is there any replacement?

**Comment by nikswamy** [comment]
Yes, the replacement is fstardoc. See PR #1939. Closing.
