### ISSUE TITLE
Tutorial module Ex01a doesn't compile

### ISSUE THREAD

**Issue by brianberns** [FStarLang/FStar#1717]
https://www.fstar-lang.org/tutorial/

Expected behavior: Tutorial module compiles cleanly

Observed behavior:
```
Ex01a(63,0-63,48): (Warning 272) Top-level let-bindings must be total; this term may have effects
Ex01a(63,0-63,48): (Warning 272) Top-level let-bindings must be total; this term may have effects
Ex01a(53,21-53,28): (Error 12) Expected type "Prims.unit"; but "Ex01a.write f" has type "s: Prims.string -> FStar.All.ML Prims.unit"
Ex01a(53,21-53,28): (Error 12) Expected type "Prims.unit"; but "Ex01a.write f" has type "s: Prims.string -> FStar.All.ML Prims.unit"
Verified module: Ex01a (1352 milliseconds)
2 errors were reported (see above)
```

**Comment by catalin-hritcu** [comment]
@brianberns What exactly are you doing to get these errors? I tried locally and everything works fine from the web interface (![screenshot attached](https://user-images.githubusercontent.com/5850655/57009731-cef90b00-6bf8-11e9-9338-96d899c43ec3.png)). Also all this code is under CI, so it works for us!

**Comment by brianberns** [comment]
I just tried it again and got the same output as you, so I'll close this issue. Thanks.
