### ISSUE TITLE
relational fstar 0.7 

### ISSUE THREAD

**Issue by joshjdevl** [FStarLang/FStar#172]
@nikswamy 

When following the install for the older fstar 0.7 release on Windows 8.1, .NET 4.x is already installed on the system due to the OS version, and installed the  FSharpPowerPack-2.0.0.0,  receive the following error

```
make test
fstar --cert --gadt --prims ../lib/prims_wotuples.f9 certify/coretyping.fst 2> dump
Makefile:205: recipe for target 'selfcert' failed
make: *** [selfcert] Error 127
```

Also
```
$ ./fstar.exe

Unhandled Exception: System.IO.FileNotFoundException: 
Could not load file or assembly 'FSharp.Core, Version=4.0.0.0, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The system cannot find the file specified.
   at <StartupCode$fstar>.$Microsoft.FStar.Wrapper.main@()

```

**Comment by nikswamy** [comment]
As I have already said, this version is unsupported. It's never been tested on the configuration you report.

Sent from my Windows Phone
________________________________

**Comment by catalin-hritcu** [comment]
Wrong place for reporting this.
