### ISSUE TITLE
Questions about fstar

### ISSUE THREAD

**Issue by parkerscott1** [FStarLang/FStar#1724]
Hello! I am currently going through the tutorial and have some questions about the verification process as the tutorial does not elaborate on it.

1) When you run fstar.exe against a module, what verification does fstar put the program through? From what I know so far, the program is typechecked, and verification conditions are generated and passed to Z3.

2) How does Fstar generates weakest pre condition?

3) How does Fstar generates the verification conditions?

4) On a side note, what do you all think are the current flaws of F*?

**Comment by catalin-hritcu** [comment]
> 1. When you run fstar.exe against a module, what verification does fstar put the program through? From what I know so far, the program is typechecked, and verification conditions are generated and passed to Z3.

Correct.

> 2. How does Fstar generates weakest pre condition?

It uses something we call Dijkstra Monads, which basically does type inference in dependent type theory to lift a monadic program to its weakest precondition. Here are [two](https://arxiv.org/abs/1903.01237) [papers](https://www.fstar-lang.org/papers/dm4free/) about this.

> 3. How does Fstar generates the verification conditions?

The weakest preconditions are first evaluated to obtain formulas in F*'s dependently typed higher-order logic, and these are then encoded into the SMT logic. Here is a [technical report explaining this](https://prosecco.gforge.inria.fr/personal/hritcu/students/alejandro/report.pdf).

> 4. On a side note, what do you all think are the current flaws of F*?

There's many ways to interpret this questions. For instance, here are some flaws:
https://github.com/FStarLang/FStar/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fbug

[Our zulip chat](https://fstar.zulipchat.com) might be a better place to discuss such things, although please note that we do expect that you've done your research beforehand :)
