### ISSUE TITLE
MkTuple2._1 works where fst doesn't

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#173]
I'm encountering a weird situation in which replacing `MkTuple2._1` by `fst` fails, although the definition of `fst` is just:
```
val fst : ('a * 'b) -> Tot 'a
let fst x = MkTuple2._1 x
```
The file is this:
http://prosecco.gforge.inria.fr/personal/hritcu/talks/fstar-sb-2015/stuff/while.fst
and changing the signature of the preservation lemma from
```
val preservation : g:env -> h:heap{typed_heap g h} -> 
                   s:stmt{typing g s /\ is_Some (step h s)} -> Lemma
                   (typing g (MkTuple2._2 (Some.v (step h s))) /\
                     typed_heap g (MkTuple2._1 (Some.v (step h s))))
```
to
```
val preservation : g:env -> h:heap{typed_heap g h} -> 
                   s:stmt{typing g s /\ is_Some (step h s)} -> Lemma
                   (typing g (snd (Some.v (step h s))) /\
                     typed_heap g (fst (Some.v (step h s))))
```
causes an error:
```
~/Projects/fstar/pub/bin/fstar.exe --fstar_home ~/Projects/fstar/pub/ arith.fst while.fst --z3timeout 1000
while.fst(209,0-215,0): Unknown assertion failed
```

**Comment by catalin-hritcu** [comment]
This was previously marked as a duplicate of the simpler #203, but fixing that didn't fix this. Reopening.

**Comment by vkanne-msft** [comment]
@nikswamy  can you look at this bug ? I am getting a different error. 

D:\Sources\FStar\examples\bug-reports\bug173.fst(207,39-207,41) : Error
Identifier not found: [MkTuple2._2]
Hint: MkTuple2._2 belongs to module MkTuple2, which does not belong to the list of modules in scope, namely FStar.All, FStar.ST, FStar.Heap, FStar.Set, FStar.FunctionalExtensionality, Prims

**Comment by s-zanella** [comment]
This appears to be fixed after updating the example. 
@vkanne-msft : `MkTuple2` is now `Mktuple2`, thus the error you got.
