### ISSUE TITLE
Interactive mode issues in the absence of --z3refresh

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1764]
Now that z3refresh is no longer the default for interactive mode, it appears that killing a z3 process then trying to process a definition results in the following series of errors:
```
(error "line 846 column 25: invalid sorted variables: unknown sort 'Term'")
(error "line 871 column 25: invalid sorted variables: unknown sort 'Fuel'")
(error "line 937 column 25: invalid sorted variables: unknown sort 'Term'")
(error "line 964 column 14: unknown constant MaxFuel")
(error "line 967 column 14: unknown constant MaxIFuel")
(error "line 970 column 30: invalid sorted variables: unknown sort 'Term'")
(Error) Unknown assertion failed (SMT solver says: sat because unknown (fuel=0; ifuel=0; ))
```
I had a feeling that this became easier to trigger with z3 4.8.5 but I don't have any evidence.

This can be worked around by setting z3refresh in one's ~/.emacs but is not a viable long-term fix.

Thanks,

Jonathan

**Comment by msprotz** [comment]
I think @nikswamy fixed this one a while ago, but I couldn't find the F* commit. Nik, can you confirm and/or post a link to the commit?

**Comment by nikswamy** [comment]
See fe152a42f791122aa9bae2e255b341e49a048c9a
and PR #1701
