### ISSUE TITLE
Proof of false using not really inferrable implicit

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#177]
This allowed me to prove a bogus progress lemma today, without noticing!
```
val foo : #y:nat{false} -> x:nat -> Tot unit (ensures false)
let foo y x = ()

val bar : x:unit -> Tot unit (ensures false)
let bar _ = foo 42
```

**Comment by catalin-hritcu** [comment]
Seems fixed:
```
bug177.fst(7,12-8,0) : Error
Unresolved implicit argument
```

**Comment by nikswamy** [comment]
Yes, but I still have to carefully check that my fix handles all similar cases.

Sent from my Windows Phone
________________________________

**Comment by catalin-hritcu** [comment]
Reopening to keep progress on similar cases.

**Comment by nikswamy** [comment]
Closing it for now. We can always reopen as needed. I guess that's what you were proposing originally anyway.
