### ISSUE TITLE
Incorrect extraction when record field is a keyword

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1783]
Found while debugging why HSL.Receive did not extract properly.

```
module Test

type range = { from: UInt32.t; to: UInt32.t }
```

extracts as:

```
jonathan@WCSMTODVT34A102:/tmp $ cat test.ml
open Prims
type range = {
  from: FStar_UInt32.t ;
  to_: FStar_UInt32.t }
let (__proj__Mkrange__item__from : range -> FStar_UInt32.t) =
  fun projectee  -> match projectee with | { from; to = to_503;_} -> from
```
note that the record type definition uses `to_` but the pattern in the projector uses `to`

Thanks,

Jonathan

**Comment by mtzguido** [comment]
This can be fixed with this patch: d3acb6eb2d6fbc09801d519448250e9d9ab6dd2c. However it's still not perfect since collisions might occur:
```fstar
module B
type t = { to : int; to_ : bool }
```
```ocaml
open Prims
type t = {
  to_: Prims.int ;
  to_: Prims.bool }
let (__proj__Mkt__item__to : t -> Prims.int) =
  fun projectee  -> match projectee with | { to_ = to_488; to_;_} -> to_488 
let (__proj__Mkt__item__to_ : t -> Prims.bool) =
  fun projectee  -> match projectee with | { to_ = to_502; to_;_} -> to_
```

This is not new at all, however, see #310. So perhaps we should take the patch? Thoughts?

**Comment by mtzguido** [comment]
@W95Psp just ran into this. I think I'd be in favor of taking the patch (if not stale), and dealing with #310 later. But the collision is terrifying, and we should fix it.

**Comment by nikswamy** [comment]
Yes, let's at least fix this issue and then address 310 more systematically
