### ISSUE TITLE
Migrate from ulex to sedlex

### ISSUE THREAD

**Issue by XVilka** [FStarLang/FStar#1792]
Long story short - ulex is dying, mainstream depends on the camlp4, which is dead, fork depends on the camlp5, which seems dead too. This prevents from porting F* to more modern OCaml versions and dependencies versions.

See these links for more information:
- https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985/4
- https://github.com/ocaml/opam-repository/pull/14351

Sedlex is an active maintained project by OCaml community: https://github.com/ocaml-community/sedlex

**Comment by catalin-hritcu** [comment]
@ad-l

**Comment by catalin-hritcu** [comment]
@avsm also strongly encourages us to get rid of the camlp4 dependency:
https://github.com/ocaml/opam-repository/pull/14377#issuecomment-506235733

**Comment by XVilka** [comment]
Related also https://github.com/FStarLang/kremlin/issues/138

**Comment by ad-l** [comment]
We considered moving to sedlex when we first implemented Unicode support but at that time sedlex had significant limitations (in particular whith custom implementations of lexing buffer). I'm happy to have another look and discuss this at the next F* meeting

**Comment by XVilka** [comment]
Note, the Kremlin PR [was merged](https://github.com/FStarLang/kremlin/commit/4acd7cccc2dd345c0065352eba8f9ac89db189ef)

**Comment by XVilka** [comment]
And the official Camlp4 deprecation announcement: https://discuss.ocaml.org/t/the-end-of-camlp4/4216

**Comment by XVilka** [comment]
[OCaml 4.09 was released](https://discuss.ocaml.org/t/ocaml-4-09-0-released/4384) and it [comes without camlp4 support](https://discuss.ocaml.org/t/the-end-of-camlp4/4216).

**Comment by XVilka** [comment]
OCaml 4.10 is [going to be released soon](https://discuss.ocaml.org/t/ocaml-4-10-0-release-plan/4811) and the [first beta is already available](https://discuss.ocaml.org/t/ocaml-4-10-0-first-beta/4989). Obviously, still can't be used with camlp4.

**Comment by fangyi-zhou** [comment]
Is it being worked on? I can try to submit a PR if that's not the case

**Comment by catalin-hritcu** [comment]
@fangyi-zhou  I've asked the F* team, and it seems no one is working on this. So patches welcome!

**Comment by XVilka** [comment]
@fangyi-zhou you can use the Kremlin commit as a reference in case there are issues with this task:https://github.com/FStarLang/kremlin/commit/4acd7cccc2dd345c0065352eba8f9ac89db189ef

**Comment by fangyi-zhou** [comment]
It's more complicated than the kremlin commit because there is also the FStar.ULexing module that uses some APIs sedlex doesn't support.
I pushed my progress to https://github.com/fangyi-zhou/FStar/tree/sedlex

**Comment by XVilka** [comment]
@fangyi-zhou depending on what must be enhanced in Sedlex it might be useful to ask its developers or send a pull request https://github.com/ocaml-community/sedlex/issues

**Comment by catalin-hritcu** [comment]
Our Homebrew formula's deletion (#1938) is also a consequence of the camlp4/ulex dependency:
https://github.com/Homebrew/homebrew-core/pull/49745

**Comment by fangyi-zhou** [comment]
Sorry I didn't manage to make a pull request. On a separate note, maybe replace ulex with [ulex-camlp5](https://opam.ocaml.org/packages/ulex-camlp5/) as a quick workaround?

**Comment by XVilka** [comment]
Quick workarounds tend to stay forever. IMHO, it's better to fix it properly. Nobody will fix ulex bugs in the future, there is no guarantee it will be compatible with the next OCaml version, etc.

**Comment by fangyi-zhou** [comment]
If you're happy to dig into why sedlex hangs on compilation, I'm happy to make the rest of the changes
