### ISSUE TITLE
--smt option looks broken

### ISSUE THREAD

**Issue by Chris-Hawblitzel** [FStarLang/FStar#1793]
Running `fstar.exe --smt a/z3.exe foo.fst` sometimes invokes z3 as `a/z3.exe` and sometimes as `z3.exe`:

```
[z3_version] a/z3.exe -version
[bg-0] a/z3.exe -smt2 -in smt.random_seed=0
[bg-1] z3.exe -smt2 -in smt.random_seed=0
```

It may be that the [bg-1] invocation is using an old value returned by `get_smt ()` to the `bg_z3_proc` function before the command-line options are processed, specifically via `make_new_z3_proc next_params`.

**Comment by ctk21** [comment]
Apologies, this was me. I put `next_params` in the wrong place. 
PR to fix is here: https://github.com/FStarLang/FStar/pull/1794

**Comment by mtzguido** [comment]
Merged now. Thanks for reporting Chris!
