### ISSUE TITLE
Any way to actually use cut?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#180]
We tried about everything one could possibly try (including redefining `cut` in various ways, like adding an extra unit argument, using refinements, etc). We always get:
```
Expected an expression; got a type
```
This should just work, so filing this as a bug, even if there might be workarounds like making assert do the right thing.

**Comment by nikswamy** [comment]
The type of cut is fixed. It's used routinely ... see qsort_arr.fst, for example
