### ISSUE TITLE
Incorrect handling of machine signed integers

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1803]
We never really used signed machine integers before. Now HACL* is adding support for them, and here comes a new bug report from Paul Zimmermann.

```
Hi,

with Félix Breton (in cc) we get the following behaviour:

   module Bug

   open FStar.HyperStack.IO

   module I32 = FStar.Int32

   let main () =
       if (I32.((-1l) <^ 0l)) then print_string "correct\n" else print_string "wrong\n";
       0

This prints "wrong", and was compiled with:

bug-ocaml: out Bug.fst
        $(FSTAR) $(FSTAR_DEFAULT_ARGS) --lax --odir out --codegen OCaml Bug.fst
        echo "let _ = main ()" >> out/Bug.ml
        $(OCAMLOPT) -I $(FSTAR_HOME)/ulib/ml -I out out/Bug.ml -o out/Bug
        out/Bug

It seems the number -1l is converted to 2^32-1 = 4294967295, and not to -1 as
expected.

We use the following version:

$ /localdisk/zimmerma/FStar/bin/fstar.exe --version
F* 0.9.7.0-alpha1
platform=Linux_x86_64
compiler=OCaml 4.05.0
date=<not set>
commit=745b7a747ac2724484452e06669e738dd86fc02a (dirty)

(This probably worked in an earlier version of Fstar.)

Félix and Paul
```

Probably worth doing another pass over the normalizer, and our usage of bigintegers via zarith.

**Comment by ad-l** [comment]
How did this happen? It did work correctly in the past - negative literals were used at some point in EverCrypt.fsti

**Comment by mtzguido** [comment]
At a first glance, I think the problem comes from the realization of the `FStar.Int32` module, which defines `int32 = int` (i.e. OCaml ints). But I'm not so familiar with this code.

**Comment by karthikbhargavan** [comment]
Paul sent over this patch:

zimmerma@tomate:/localdisk/zimmerma/FStar$ git diff ulib/ml/
diff --git a/ulib/ml/FStar_Int32.ml b/ulib/ml/FStar_Int32.ml
index efd59aec43..35725c584e 100644
--- a/ulib/ml/FStar_Int32.ml
+++ b/ulib/ml/FStar_Int32.ml
@@ -3,6 +3,9 @@ type uint32 = int
type t = int32
type t' = t

+let cmod x =
+  if x > 2147483647 then x - 4294967296 else x
+
let v (x:int32) : Prims.int = Prims.parse_int (string_of_int x)

let zero = 0
@@ -30,7 +33,8 @@ let logxor (a:int32) (b:int32) : int32 = a lxor b
let logor  (a:int32) (b:int32) : int32 = a lor b
let lognot (a:int32) : int32 = lnot a

-let int_to_int32 (x:Prims.int) = int_of_string (Prims.to_string x) land 4294967295
+(* let int_to_int32 (x:Prims.int) = int_of_string (Prims.to_string x) land 4294967295 *)
+let int_to_int32 (x:Prims.int) = let u = int_of_string (Prims.to_string x) in (cmod u)

let shift_right (a:int32) (b:uint32) : int32 = a lsr b
let shift_left  (a:int32) (b:uint32) : int32 = (a lsl b) land 4294967295
@@ -66,9 +70,6 @@ let op_Greater_Equals_Hat = gte
let op_Less_Hat = lt
let op_Less_Equals_Hat = lte

-let cmod x =
-  if x > 2147483647 then x - 4294967296 else x
-
let to_string s = string_of_int (cmod s)
let int_to_t s = int_to_int32 s
let __int_to_t = int_to_t

**Comment by karthikbhargavan** [comment]
Can we merge this patch? I don't want to touch ulib myself; but someone
with easy access to CI may be able to do this?
