### ISSUE TITLE
Implicit argument errors don't have locations

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1806]
```
(Error) Implicit argument: Expected a total term; got a ghost term: FStar.Ghost.reveal a 
```

this error highlights the entire function, meaning I have to bisect to figure out the culprit. This is very time-consuming.

Thanks,

Jonathan

**Comment by mtzguido** [comment]
Do you happen to have a repro for this? The actual call that raises the error does try to use the location from the environment:
```
 raise_error (Errors.Fatal_UnexpectedImplictArgument, (BU.format1 "Implicit argument: Expected a total term; got a ghost term: %s" (Print.term_to_string e))) (Env.get_range env)
```
But apparently that's empty in your case.

**Comment by msprotz** [comment]
Something seems to have changed in this area, because I tried removing the workarounds I used to need in EverCrypt.Hash.Incremental and the file still went through.

The only thing I was able to reproduce is the following:

Above this line: https://github.com/project-everest/hacl-star/blob/410184fd27af76cd686652dfbe83cd3680970398/providers/evercrypt/fst/EverCrypt.Hash.Incremental.fst#L613 add

```
﻿  let hash_state = (!*p).hash_state in
```

then I get an error that is puzzling (unless I know that the implicit for the projector is not resolved properly) but it is properly localized. I think this is the error that used to be located across the whole function.

I think you can close this.
