### ISSUE TITLE
Strange syntactic restrictions on predicate arguments

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#181]
These work:
```
type t1 (t:Type) = t
type t2 (a:Type) ('p:a->Type) = a
```
But this doesn't work:
```
type t2' (a:Type) (p:a->Type) = a
```
it doesn't even pass parsing:
```
../../bin/fstar.exe --fstar_home ../.. bug181.fst
ERROR: Syntax error near line 8, character 24 in file bug181.fst
```
Why?

**Comment by catalin-hritcu** [comment]
The same problem appears with quantifiers over predicates.

**Comment by nikswamy** [comment]
The binding rules for parsing ticked type variables is evidently a bit different than parsing non-ticked ones.

You should write:
```
type t2' (a:Type) (p:(a->Type)) = a
```

I will change it so that the convention for ticked variables is the same.

**Comment by nikswamy** [comment]
This syntax below is no longer supported. Ticked variables cannot be explicitly bound or ascribed kinds. Use unticked variables for that.

```
type t2 (a:Type) ('p:a->Type) = a //syntax error on 'p
```
