### ISSUE TITLE
Syntactic equality fails on top-level terms

### ISSUE THREAD

**Issue by ad-l** [FStarLang/FStar#1810]
There is something different in the encoding of top-level terms that prevents syntactic equality of terms from working correctly. I usually work around this by adding an assert_norm of the definition of the term (this appears in a few places in TLS, in DefineTable.fst and KDF.fst) but I wonder if there is a way to fix it? Itsaka actually ran into this issue trying to prove the CPS fib example of the tutorial.

```fstar
let a = fun x -> x + 1
let b = fun x -> x + 1
[@expect_failure]
//assert_norm(a == (fun x -> x + 1) /\ b == (fun x -> x + 1))
let t () : Lemma (a == b) = ()

let _ =
  let a = fun x -> x + 1 in
  let b = fun x -> x + 1 in
  let t () : Lemma (a == b) = () in
  ()
```

**Comment by aseemr** [comment]
This is somewhat by-design. By default top-level definitions are not substituted when queries are encoded to Z3. As a result we need `assert_norm` or some such normalization to prove equality of top-level `a` and `b` (in general `assert_norm` may be unnecessarily aggressive, so controlled normalization using `Pervasives.reveal_opaque` or tactics is better). Whereas inner let-bindings are substituted and so, in the encoding of inner lemma `t`, the postcondition is simply `fun x -> x + 1 == fun x -> x + 1`, which goes through.

**Comment by aseemr** [comment]
Closing this issue for now, changing this behavior would require some changes to the smt encoding. Instead there is a workaround of using normalization. Please reopen if necessary, thanks!
