### ISSUE TITLE
Error "Wrong composed operator format"

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#1812]
Hi, I ran in a rather odd bug last week: I get the error "Wrong composed operator format" when I delta-reduce a term with the `norm` tactic.
Here is a reduced version of it:
(note that without the double match, the error is not triggered)

```fstar
module WrongComposedOpFormat

open FStar.Tactics

unfold let op_any_word o = 1 // any identifier fitting the pattern `op_*_*` works

let f v w: unit
  =
    match v with
    | true  -> (
              match op_any_word w with
              | 1 -> ()
              )
    | false -> () 

let test v w
  = assert (
    f v w == ()
  ) by (norm [delta]; qed ())
```

It clearly seems like it's a (sort of) name clash since the bug is present only for names fitting the pattern `op_*_*` (in the above example, the error holds for any such identifiers instead of `op_any_word`).

`src/syntax/FStar.Syntax.Resugar.fs#L153` (for instance) seems indeed to indicate that name operators are encoded in that `op_*_*` form.

**Comment by mtzguido** [comment]
Thanks for reporting and the small repro! This is actually a bug in the pretty printer, and can also be triggered like this:
```fstar
module Bug1812
let op_any_word o = 1 // any identifier fitting the pattern `op_*_*` works
let t = op_any_word
```
And typechecking with `--dump_module Bug1812` to cause F* to print it. In your case what happens is that F* tries to give an error and a proofstate dump containing that term, and fails to print it (you can get around it with `--ugly` to bypass the pretty printer).

Anyway, fix incoming. Thanks again for reporting.
