### ISSUE TITLE
Warning 241 for prims.fst.checked in OPAM installed fstar.exe

### ISSUE THREAD

**Issue by camlspotter** [FStarLang/FStar#1813]
Probably a newbie question.  I have installed `fstar.0.9.7.0-alpha1` via OPAM and am playing with some examples.  I always get Warning 241 which complains the lack of `prims.fst.checked`:

```
$ fstar.exe Ex01a.fst
/Users/jun/.opam/4.07.1/lib/fstar/prims.fst(0,0-0,0): (Warning 241) Unable to load /Users/jun/.opam/4.07.1/lib/fstar/prims.fst.checked since checked file /Users/jun/.opam/4.07.1/lib/fstar/prims.fst.checked does not exist; will recheck /Users/jun/.opam/4.07.1/lib/fstar/prims.fst (suppressing this warning for further modules)
Verified module: Ex01a (9 milliseconds)
All verification conditions discharged successfully
```

This does not change even if I add `--cache_checked_modules` option.

It seems to create `prims.fst.checked` and other `*.fst.checked` in the library directory, I have to manually run `fstar.exe --cache_checked_modules` against each of them.  Is it the intended behaviour?  Caching of the dependent modules is not automatic?

**Comment by catalin-hritcu** [comment]
I'm not an expert for the OPAM package (@tahina-pro and @msprotz are), but what I can say is that for the binary packages (so not exactly OPAM) one would have to run the following command to eliminate these warnings:
```
$ make -j6 -C ulib
```
The OPAM package doesn't seem to run this command, but maybe it should? Can you try to add it locally to the following list and see if it helps? https://github.com/ocaml/opam-repository/blob/master/packages/fstar/fstar.0.9.7.0-alpha1/opam#L28

**Comment by tahina-pro** [comment]
So far the standard library is not rebuilt when installing the F* opam package because Z3 is not assumed to be installed on the user's machine. There may be several solutions to this problem:
* during the installation of the F* opam package, we could rebuild ulib with `--admit_smt_queries true`
* now that we support Z3 4.8.5, we could add a dependency on the z3 opam package, but we are not sure whether the ulib proofs are robust wrt. Z3 upgrades
* could we assume that some Z3 is on the user's machine? no, because our package would fail the opam repository CI

**Comment by catalin-hritcu** [comment]
The first option seems fine to me, and it would also keep the build process fast :)

**Comment by catalin-hritcu** [comment]
And while we are at it, can we also add a < "4.08.0" bound for the [ocaml dependency](https://github.com/ocaml/opam-repository/blob/master/packages/fstar/fstar.0.9.7.0-alpha1/opam#L8)? Not even batteries works with ocaml 4.08.0 at this point, and we have even bigger problems with ulex (see #1792).

**Comment by zubovm** [comment]
@tahina-pro @catalin-hritcu 
Hi, guys, is there any progress on this problem?

I have the very same warning when installing from opam 2 years later:
> ~/.opam/4.07.0/lib/fstar/prims.fst(0,0-0,0): (Warning 241) Unable to load ~/.opam/4.07.0/lib/fstar/prims.fst.checked since checked file ~/.opam/4.07.0/lib/fstar/prims.fst.checked does not exist

Probably there is some way to add .check files to lib/fstar folder, isn't it? Or what should I do to be free of this warning, 'cause I suppose not the warning itself is a problem, but verification time increase (considering also

factorial.fst(0,0-0,0): (Warning 247) factorial.fst.checked was not written since checked file ~/.opam/4.07.0/lib/fstar/FStar.Mul.fst.checked does not exist ).

Also is there any way to use z3 installed from opam?

Thanks in advance.

**Comment by catalin-hritcu** [comment]
> Also is there any way to use z3 installed from opam?

If the version we need is available via OPAM we could use it. @tahina-pro and me discussed about this not long ago, but I still can't remember.

**Comment by zubovm** [comment]
> > Also is there any way to use z3 installed from opam?
> 
> If the version we need is available via OPAM we could use it. @tahina-pro and me discussed about this not long ago, but I still can't remember.

fstar says this:
> Expected Z3 version "Z3 version 4.8.5"
and opam says this:
> opam list z3
> # Packages matching: (installed | available) & name-match(z3)
> # Package  # Installed # Synopsis
> z3.4.6     --          Z3 solver
> z3.4.7.1   --          Z3 solver
> z3.4.8.1   --          Z3 solver
> z3.4.8.4   --          Z3 solver
> z3.4.8.5   --          Z3 solver
> z3.4.8.6   --          Z3 solver
> z3.4.8.7   --          Z3 solver
> z3.4.8.8   --          Z3 solver
> z3.4.8.8-1 --          Z3 solver
> z3.4.8.9   --          Z3 solver

So probably it matches; I'll try, thank you. 

But the main question remains:

I have many-many .fst and .fst.hints files at my
~/.opam/4.07.0/lib/fstar/*
is there any process (sequence of commands) that would lead to check all of them and put 
corresponding .checked files in that directory?

'Cause my goal is not 'making all going the correct way', some dirty hack would be completely enough
(but not so dirty that it would require binary blob installation).

**Comment by catalin-hritcu** [comment]
@zubovm That was the first thing I wrote on the thread:
```
$ cd ~/.opam/4.07.0/lib/fstar
$ make -j6 -C ulib
```

**Comment by zubovm** [comment]
@catalin-hritcu 
Unfortunately, it says 
> make -j6 -C ulib
> make: *** ulib: No such file or directory.  Stop.
there is no subdirectory ulib indeed

**Comment by zubovm** [comment]
@catalin-hritcu 
I've found a dirty hack workaround though, thanks to your comment:
download binary package, make .checked files, copy checked files to opam folder.

Unfortunately, I have a little experience with opam inner mechanics, so I do not know right now how to download opam src and install its custom variant with modified build recipe. But I'll try to conquer that knowledge.

**Comment by tahina-pro** [comment]
@zubovm If you want, until it is merged, you can test PR #2261 by doing `opam pin fstar git://github.com/FStarLang/FStar#taramana_opam`, which uses the `z3.4.8.5` opam package.

**Comment by zubovm** [comment]
@tahina-pro 

Yeah,  it works, as far as I tried, thanks a lot.
Btw, .checked files live in fstar/.cache

Is that ok, wouldn't they be deleted somehow?

Also wanted to ask is there any channel to ask questions about verified programming and F* in particular?
IRC, gitter, telegram group?

**Comment by tahina-pro** [comment]
When building the opam package, everything under `ulib/` (including the `.cache` subdirectory obtained by verifying the standard library) is copied into `.opam/<switch>/lib/fstar` with no changes, and everything there is relevant, so nothing from those will be removed at all.

There is a public Zulip chat, as advertised in README.md as well as on the F* website: https://fstar.zulipchat.com/  I guess @catalin-hritcu can tell you more on that.
