### ISSUE TITLE
Type annotations in match (and destructuring let) get completely ignored

### ISSUE THREAD

**Issue by yforster** [FStarLang/FStar#183]
The following should in my eyes be refused (or at least trigger a warning).

```
module Test

type test : Type = | T : x:bool -> test

val f : test -> bool
let f h = match h with T (t : int) -> t
```

**Comment by catalin-hritcu** [comment]
Agreed, this definitely gives the wrong impression to the unsuspecting user. If we allow such annotations, we should check they are correct; otherwise we disallow them.

**Comment by vkanne-msft** [comment]
Gives a syntax error. 
@catalin-hritcu can you kindly reproduce and reopen the issue? 

$ fstar --universes bug183.fst
D:\Sources\FStar\examples\bug-reports\bug183.fst(7,24-7,25) : Error
Syntax error

**Comment by s-zanella** [comment]
Still type checking without any warning. 
It should fail or warn about the inconsistent type annotation in the pattern.

**Comment by s-zanella** [comment]
Again, some confusion because of this issue:
https://lists.gforge.inria.fr/pipermail/fstar-club/2017/000093.html

**Comment by nikswamy** [comment]
THis came up again today with @parno  who observed a confusing unification error message in Vale, in part because type annotations `let (x:t, y:s) = e in ...` were being ignored.
