### ISSUE TITLE
Couldn't find any name for this bug that's not offensive towards our tool

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#185]
I'll commit a file, not yet fully minimized that shows (again) the kind of non-sense we have to suffer in the certificates example. The code looks like this:
```
            | [ vk ] -> if verify #certified vk0 ctxt ctag then
              (
(*               assert (verified vk == certified); magic() -- succeeds *)
(*               validate vk chain_tl -- fails*)
(*               assume (verified vk == certified); -- adding this makes it work *)
                validate vk chain_tl
```
and fails with:
```
../../bin/fstar.exe --fstar_home ../.. bug185.fst
bug185.fst(24,4-40,15): Patterns are incomplete
bug185.fst(35,25-35,27): Subtyping check failed; expected type (vkey certified); got type data
Verified module: Prims
Verified module: Bug
```
The `Patterns are incomplete` part seems just spurious in this case, so let's look at the subtyping failure. The type `vkey p` is just `data` for which it `verified k == p` holds. If we assert `verified vk == certified` the assert succeeds, so F* should also be able to prove the subtyping, but it's not. If we add an `assume` with this before the `verified` then it works ... unless we keep the `assert` around, in which case the `assert` starts failing. So an assert that succeeds on it's own, and two lines of code that also succeed on their own start failing as soon as we put them together with ";". This makes no sense.

**Comment by nikswamy** [comment]
seems to be fixed by my latest commit.
