### ISSUE TITLE
Failure("Impossible: missing universe instantiation on length")

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1855]
[This file](https://github.com/FStarLang/FStar/blob/bd05950aa266e944bf8016674ab6bce2f8461171/ulib/LowStar.Union.fsti) triggers the following error:

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: missing universe instantiation on length")
```

Thanks,

Jonathan

**Comment by mtzguido** [comment]
Whoops, we were replacing decreases clauses with their elaborated version after typechecking. I have a fix running in CI.
