### ISSUE TITLE
Termination of function without inlining

### ISSUE THREAD

**Issue by satos---jp** [FStarLang/FStar#1857]
I want to prove the termination of the following function f.
```
let g (v:(list nat){Cons? v}) f = 
  match v with
  | x :: xs -> f xs

let rec f v = 
  match v with
  | [] -> ()
  | _ -> g v f
```
However, the compiler gives an error for it. 
```
term.fst(10,13-10,14): (Error 19) Could not prove termination of this recursive call (see also term.fst(8,2-10,14))
```

The termination can be proven by inlining g in f.
```
let rec f' v = 
  match v with
  | [] -> ()
  | _ -> begin
      match v with
      | x :: xs -> f' xs
    end
```

But I don't want to inline g, since, in my practical situation, g is a much bigger function and used in many places.  (Actually, it is a "bind" function for result type.) I have tried adding `unfold` quantifier and `[@ "opaque_to_smt"]` custom attribute for g, both of them didn't work.

**Comment by catalin-hritcu** [comment]
How about giving `g` a specification that allows you to prove the termination of `f`? Otherwise you're relying on whatever spec F* infer by itself which might not be strong enough.

**Comment by mtzguido** [comment]
Indeed, one way to do so is this:

```fstar
let g (v:(list nat){Cons? v}) (f : (l:list nat{l << v}) -> Tot 'a) : Tot 'a = 
  match v with
  | x :: xs -> f xs

let rec f v = 
  match v with
  | [] -> ()
  | _ -> g v f
```

Without the annotation, the `f` argument of `g` is assumed to be a function of type `list nat -> Tot 'a`, but `f` does not have such in its body due to the termination check (its domain is restricted to those elements smaller than `v`). The [tutorial](https://www.fstar-lang.org/tutorial/tutorial.html#sec-termination) goes into more detail about how the termination check works.

Would this solve your original problem?

**Comment by satos---jp** [comment]
Thank you, it worked! In my original situation, I wanted to prove the termination of the following function `problem`. This is acheived by adding `Tot (result (r:(list int){r << x}) string)` annotation to the function `g`.
```
type result 'a 'b = 
  | Ok of 'a
  | Error of 'b

let bind x f = 
  match x with
  | Error e -> Error e
  | Ok x -> f x

let g x : Tot (result (r:(list int){r << x}) string) =
  match x with
  | [] -> Error "hoge"
  | d :: ds -> if d = 0 then Error "huga" else Ok ds

let rec problem x =
  match x with
  | [] -> Ok ()
  | _ -> bind (g x) problem
```
