### ISSUE TITLE
Assertion failure: unexpected pattern term

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1863]
Hi,

This file, when processed in the interactive mode with the patterns un-commented, triggers the following assertion:

https://github.com/project-everest/hacl-star/blob/f89a7c50198200e93ef72ce1aa4b11ec023bac1b/providers/quic/Impl.QUIC.fsti#L110

I'm sure I did something wrong but I'm staring at this code and I can't figure out what it is. In any case, a more informative error message would be a big usability improvement.

Thanks,

Jonathan

**Comment by mtzguido** [comment]
The problem is that one can only use `SMTPatOr` at the top-level of a lemma's pattern, and one cannot combine `[SMTPat ...; SMTPatOr ...]` like that. (I don't know if this is documented...) Would an error like this, pointing to the `SMTPatOr` be good enough?
```
(Error 326) Not an atomic SMT pattern: SMTPatOr [...]; SMT patterns must be a list of simple SMTPat's or a single SMTPatOr containing a list of lists of patterns
```

**Comment by msprotz** [comment]
yes just a good error message would go a long way -- thanks!

**Comment by mtzguido** [comment]
Ack, fix incoming, and the documentation issue is tracked in #1832.
