### ISSUE TITLE
Support let operators à la OCaml

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1868]
tl;dr see https://github.com/ocaml/ocaml/pull/1947

We could support them in F* syntax to have a more flexible do notation, where one can combine different binds as needed (@beurdouche recently asked for this) and to make extracted programs more readable, especially for DM4F/DM4A.

**Comment by nikswamy** [comment]
Note, we now have source support for this, but extraction to OCaml does not preserve the monadic sugar.
