### ISSUE TITLE
ulib/.depend contains incorrect dependencies due to lack of path normalization

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1871]
Following the latest round of changes, the situation is now as follows.

Makefile.verify is written with relative paths, e.g.:

```
  40 verify-core: $(addprefix .cache/, $(addsuffix .checked, $(notdir $(filter-out $(EXTRA) ,$(FSTAR_FILES)))))
```

however, the generated dependency graph uses absolute paths, i.e. I see this in .depend:

```
3201 /Users/jonathan/Code/fstar/bin/../ulib/.cache/FStar.Reflection.Data.fst.checked: FStar.Reflection.Data.fst\
```

since for GNU make, dependencies are only syntactic, this means that the contents of the .depend file are entirely ignored.

I would suggest using the variable ALL_CHECKED_FILES in there too.

Thanks,

Jonathan

**Comment by nikswamy** [comment]
Thanks for spotting this. I'm attempting a fix based on your suggestion. But I haven't been able to reproduce the .depend with absolute paths in there … I see only relative paths in mine. Anything unusual about your set up?

**Comment by nikswamy** [comment]
pushed to master; closing. Please re-open if you still observe a problem.

**Comment by msprotz** [comment]
I'm still observing an issue:
```
/Users/jonathan/Code/fstar/ulib/FStar.UInt.fst(0,0-0,0): (Warning 241) Unable to load /Users/jonathan/Code/fstar/ulib/.cache/FStar.UInt.fst.checked since checked file /Users/jonathan/Code/fstar/ulib/.cache/FStar.UInt.fst.checked is stale (digest mismatch for /Users/jonathan/Code/fstar/ulib/FStar.UInt.fst); will recheck /Users/jonathan/Code/fstar/ulib/FStar.UInt.fst (suppressing this warning for further modules)
(Error 317) Expected /Users/jonathan/Code/fstar/ulib/FStar.UInt.fst to already be checked
1 error was reported (see above)
```

but:

```
jonathan@wifi-pro-82-016:~/Code/fstar/ulib (master) $ make -f Makefile.verify  /Users/jonathan/Code/fstar/bin/../ulib/.cache/FStar.UInt.fst.checked
make: Nothing to be done for `/Users/jonathan/Code/fstar/bin/../ulib/.cache/FStar.UInt.fst.checked'.
```

let's try to debug this together sometime this week. For now, I've taken to doing `git clean -fdx` upon pulling.

**Comment by msprotz** [comment]
I fixed it.

**Comment by nikswamy** [comment]
how?

**Comment by msprotz** [comment]
0ad4b6347b7258abce2dc66cdb8f921f2841b4b4

basically, the Makefile contained an entry for `cache/%.checked:` which was not matching the form of the .depend-generated entries, meaning that make was actually not triggering that rule.

I added a note that some other pattern rules of that form were also ineffective: things like

```
 .cache/LowStar.Printf.fst.checked: USE_EXTRACTED_INTERFACES=
 .cache/FStar.ModifiesGen.fst.checked: OTHERFLAGS+=--z3rlimit_factor 8
 .cache/LowStar.Monotonic.Buffer.fst.checked: OTHERFLAGS+=--z3rlimit_factor 4
```

wouldn't kick in based on what's happening on my OSX and Linux machines.
