### ISSUE TITLE
F* attempts to read too much parsing data, resulting in spurious 285 errors

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1882]
Steps to reproduce:
- from a *clean* checkout of hacl-star, branch fstar-master, run:
`make -j obj/Hacl.Curve25519_64.fsti.checked`

this prints out a bunch of warnings:

/home/jonathan/Code/hacl-star-other/vale/code/arch/x64/interop/Vale.Inline.X64.Fadd_inline.fst(25,32-25,40): (Warning 285) module not found in search path: vale.curve25519.x64.fastwide

while this is technically correct (these files have not been generated yet), the culprit `Vale.Inline.X64.Fadd_inline.fst` *is not reachable through this fsti* (verification stops at fsti boundaries).

So, I don't understand why F* attempts to read the parsing data for these files...

Thanks,

Jonathan

**Comment by mtzguido** [comment]
I believe this is due to the fix for #1391. See Nik's last comment where he proposes an (unsafe) flag to indeed stop at fsti boundaries.

**Comment by msprotz** [comment]
Meh, it's not the end of the world, then. HACL folks will just live with the warning. Thanks for the fast reply!
