### ISSUE TITLE
Nested pattern match does not return expected result

### ISSUE THREAD

**Issue by Jazperson2** [FStarLang/FStar#1893]
I am sorry if it is a problem with my code logic but this does not return the expected result.
 
```FStar

val buildlist1 : (t:nat) → (fixedt:nat) → Tot(a:list nat) (decreases t)

let rec buildlist1 t fixedt =
  match t with
  | 0 → Nil
  | _ -> 
    match t with
      | fixedt → (2) :: (buildlist1 (t-1) fixedt)
      | _ →   (3) :: (buildlist1  (t-1) fixedt)

let a = buildlist1 2 2 
```

Evaluating ```a``` gives ```[2;2]```, but expected behavior should be ```[2;3]```

**Comment by aseemr** [comment]
The `fixedt` that you use as the pattern variable is not the same `fixedt` as the argument of the function, rather it is a new binder in the scope (that shadows the `fixedt` argument of the function in the body of that branch).  So the second match always takes the first branch, and hence gives the answer `[2;2]`.

Hope that helps! Please reopen if you still see some problems.
