### ISSUE TITLE
`to` (as a record field) is not getting renamed properly when extracting to OCaml

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#1904]
Hi,

The following module:
```fstar
module T
type foo = { to: int }
```

exports (`--codegen Plugin`) as:
```fstar
open Prims
type foo = {
  to_: Prims.int }
let (__proj__Mkfoo__item__to : foo -> Prims.int) =
  fun projectee -> match projectee with | { to = to_263;_} -> to_263
```

The last line contains an occurence of `to` which is a reserved caml word, and the formatting seems odd, so I guess there is a little issue with the renaming and the code generation.

**Comment by mtzguido** [comment]
See #1783 and #310, hopefully we'll sort them out soon.
