### ISSUE TITLE
Set attribute(s) on projectors

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#1907]
Hi,

I have a few records that hold function definitions, which I need to normalize at some point. I tried to write the following: 
```fstar
irreducible let norm_me = ()
[@norm_me]
noeq type foo a b = {
bar: a -> b;
}
```

But then, `attrs` evals to ``[`Substitute]`` (and not to ``[..., `norm_me]``) in the code below, so it seems like attributes on inductives do not propagate to projectors. 
```fstar
open FStar.Tactics
open FStar.Reflection.Basic
let sigelt: sigelt = _ by (
    let n = inspect_fv (let Tv_FVar x = admit (); inspect (`(*`*)Mkfoo?.bar) in x) in
    let Some sigelt = admit (); lookup_typ (top_env ()) n in
    exact (quote sigelt)
  )
let attrs = sigelt_attrs sigelt
```

I have a lot of inductives each containing multiple projectors, so writting some `delta_only` for each manually is not that nice. I'm currently using this https://gist.github.com/W95Psp/8a344f1ff39e2a4cda60d07e37beae44 as a workaround.

Is there a way to set attributes on projectors ?

Thanks ! :)

**Comment by mtzguido** [comment]
I would be fine with attributes on a record type propagating to its projectors, just as those of an inductive propagate to its constructors. Trying it out.

**Comment by mtzguido** [comment]
#1933
