### ISSUE TITLE
`(/\)` is desugared to `Prims.c_or` (and `(\/)` in `c_and`)

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#1913]
Hi,

I've just run in a quite silly bug: `(/\)` seems to be desugared to `Prims.c_or`!

Here is a example:
```
[@expect_failure]
let _ = assert (False /\ True)
let _ = assert ((/\) False True)
```

Or:
```
let (/\) = "slash-backslash"
let (\/) = "backslash-slash"

let _ = assert (op_Backslash_Slash == "slash-backslash")
let _ = assert (op_Slash_Backslash == "backslash-slash")
```

I guess it's the way F* parses operators transformed in prefix with parenthesis, but I were not able to find the reason. 

EDIT: and I guess `(/\)` should be `c_and`, not `l_and`, right?

**Comment by mtzguido** [comment]
Whoops, that's a bit embarassing. Luckily it's an easy fix and triggered no regressions. Merging soon.
