### ISSUE TITLE
F* fails on lenth-indexed lists with length ≥ 19

### ISSUE THREAD

**Issue by wenkokke** [FStarLang/FStar#1922]
Let's assume a length-indexed list type and a number of lists of increasing length:
```fstar
open FStar.List.Tot

type vector 'a n = v:list 'a {length v == n}

val v1 : vector nat 1
let v1 = [1]

val v2 : vector nat 2
let v2 = [1; 2]

val v3 : vector nat 3
let v3 = [1; 2; 3]

// ...

val v18 : vector nat 18
let v18 = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18]

val v19 : vector nat 19
let v19 = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 19]

val v20 : vector nat 20
let v20 = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 19; 20]
```
F* fails with some variant of the following error for each list of length ≥ 8:
```
Bug1.fst(29,9-29,33): (Error 19) Subtyping check failed; expected type Bug.vector Prims.nat 8; got type Prims.list Prims.nat; The solver found a (partial) counterexample, try to spell your proof in more detail or increase fuel/ifuel (see also Bug1.fst(5,30-5,43))
```
This makes sense: the default setting for fuel is 8, so F* is probably running out of fuel while checking the length of the larger lists. Indeed, if we increase the fuel, we can progressively push back the errors: with 9 fuel we can check lists up to length 9, with 10 fuel we can check lists up to length 10, etc.

Unfortunately, this stops at 19... no matter what amount of fuel we give F*, it fails to check length-indexed lists with length ≥ 19.

---

[Bug1.fst](https://github.com/FStarLang/FStar/files/4207139/Bug1.fst.txt)

**Comment by wenkokke** [comment]
Curiously, the bug does not happen when the lists contain _nested lists_ as opposed to numbers:
```fstar
open FStar.List.Tot

type vector 'a n = v:list 'a {length v == n}
type matrix 'a r c = vector (vector 'a c) r

val m_1_1 : matrix nat 1 1
let m_1_1 = [[1]]

val m_2_1 : matrix nat 2 1
let m_2_1 = [[1]; [1]]

val m_3_1 : matrix nat 3 1
let m_3_1 = [[1]; [1]; [1]]

// ...

val m_18_1 : matrix nat 18 1
let m_18_1 = [[1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]]

val m_19_1 : matrix nat 19 1
let m_19_1 = [[1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]]

val m_20_1 : matrix nat 20 1
let m_20_1 = [[1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]; [1]]
```

---

[Bug2.fst](https://github.com/FStarLang/FStar/files/4207145/Bug2.fst.txt)

**Comment by s-zanella** [comment]
Z3 could easily get deep in the weeds with such a high fuel setting.

A better, more predictable way of doing this is to use the normalizer, as in 
```
val v20 : vector nat 20
let v20 = 
  let v = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17; 18; 19; 20] in
  assert_norm (length v = 20);
  v
```

**Comment by wenkokke** [comment]
Thanks! That does work. Why isn't normalising done by default before querying Z3?

**Comment by Chris-Hawblitzel** [comment]
The limit of `19` comes from a Z3 cutoff that you can adjust with `--z3cliopt smt.QI.EAGER_THRESHOLD=n` for whatever number `n` you want.  But, as Santiago said, using the normalizer is safer than adding a lot of fuel.  F* could normalize more by default before querying Z3, but this can result in larger SMT queries that are slower for Z3 to process.

**Comment by wenkokke** [comment]
Thanks, @Chris-Hawblitzel, that's great to know!
