### ISSUE TITLE
Add an option to retry failing queries

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1942]
Several developments use either intentionally or unintentionally higher `--fuel` and `--ifuel` settings as a means of retrying a failing query. This usually suggests that a proof is fragile and needs to be elaborated. However, some proofs are inherently fragile and retrying them is the most convenient and inexpensive way of stabilizing them. 

This can now be partially achieved by abusing the new `--quake` option: `--quake 1/n` would run each query `n` times and succeed if at least one run does. This is wasteful, because each query would be attempted `n` times even when a previous attempt had succeeded. Rather than abusing `--quake`, it would be convenient to add a `--retry n` option that retries a failing query at most `n` times, stopping after the first successful attempt.

**Comment by mtzguido** [comment]
Perhaps we could make this a feature of `--quake` so as to not *ab*use it :)

For instance `--quake N/M` could stop retrying as soon as `N` successes or `M-N` failures are obtained, to either succeed or fail early respectively. We could also introduce a `--quake N/M/k` variant (`k` being a literal character) where we "keep going" regardless of the criterion above. The current behaviour is to always keep going, which I find useful to diagnose how a proof is, but is indeed wasteful when quake is being used for retrying.

**Comment by s-zanella** [comment]
If you believe modifying the behavior of `--quake N/M` is reasonable, that could indeed be a quick solution. I personally prefer a separate option with a self-documenting name, even if it ends up being just a synonym of `--quake 1/M`. 
Anyways, this would be really useful in practice (`--quake` is already great!)

**Comment by mtzguido** [comment]
Having a synonym sounds good: let's just make `--retry n` desugar into `--quake 1/n`? So we get a good name and an explanation for it in the options.

It would also prevent questions such as "what does `--quake 3/5 --retry 25` mean?".

**Comment by msprotz** [comment]
that'd be great -- I started using quake in merkle_trees with the intent for it to be a "retry"
