### ISSUE TITLE
Bug with topdown_rewrite

### ISSUE THREAD

**Issue by Kachoc** [FStarLang/FStar#1950]
The following code raises the following error:
"(Error) user tactic failed: Tactic got stuck! Please file a bug report with a minimal reproduction of this issue."

```
open FStar.Tactics

let rec list_sum (l:list nat) : nat =
  match l with
  | [] -> 0
  | n :: l' ->
    n + (list_sum l')

let recursive_norm () : Tac unit =
  let ctrl (t : term) = (true, 0) in
  topdown_rewrite ctrl trefl

#push-options "--fuel 0"
let list_sum_lem () : Lemma (list_sum [1;2;3;4;5] = 15) =
  assert(list_sum [1;2;3;4;5] = 15)
    by (recursive_norm () (* HERE *) )
#pop-options
```

**Comment by mtzguido** [comment]
Hi! Sorry, this is a known problem with subeffecting (#1390). The workaround is to annotate the effect in `ctrl`, i.e. writing:
```fstar
let ctrl (t : term) : Tac _ = (true, 0) in
```

I'm closing this issue and commenting in #1390. Thanks for the report!
