### ISSUE TITLE
Documentation for homogeneous vs heterogeneous equality

### ISSUE THREAD

**Issue by mlr-msft** [FStarLang/FStar#198]
I am attempting to write an IPv4 endpoint type:

```
module Network

    type UnrefinedEndPoint = 
        {
            addr : Bytes.bytes;
            port : int
        }

    val is_valid_endpoint_ipv4 : UnrefinedEndPoint -> bool
    let is_valid_endpoint_ipv4 ep = 
        (Bytes.length ep.addr == 4)
        && (ep.addr <> Bytes.make 4 0)
        && (ep.port >= 0)
        && (ep.port <= 65535)

    type IPv4EndPoint = ep:UnrefinedEndPoint{is_valid_endpoint_ipv4 ep}
```

I attempt to verify with the following command (in PowerShell):

`fstar $env:FSTAR_HOME/lib/bytes.fst network.fst`

I get the following error:

```
network.fst(11,8-12,40) : Error
Expected two boolean arguments
```

I'm not certain what's wrong as both expressions on either side appear to be Boolean expressions. 
This is assuming that I got the inequality operator correct, however: Using OCaml references as fallback documentation, I attempted to use `!=` to represent inequality but F\* complains about that with a syntax error.

Thanks in advance.

**Comment by catalin-hritcu** [comment]
The problem F* is complaining about is that heterogeneous equality `==` returns a `Type` not a `bool`. Changing to homogeneous equality `=`, which does return a `bool`, fixes the `Expected two boolean arguments` problem.

Also, the first argument passed to `Bytes.make` doesn't have the right type: `Bytes.make` expects a function from `nat` to `bytes`, while the code above gives it a nat (`4`).

Finally, if you want to use `is_valid_endpoint_ipv4` in the refinement below, you need to mark it as `Pure`. For instance by annotating it with type `UnrefinedEndPoint -> Tot bool`.

After fixing these 3 things the code above type-checks for me. Hope this helps.

**Comment by catalin-hritcu** [comment]
The `Type` vs `bool` distinction is explained in the tutorial:
https://www.fstar-lang.org/tutorial/tutorial.html#sec-bool-versus-type
although we might indeed want to explain the `=` vs. `==` distinction somewhere too.

**Comment by catalin-hritcu** [comment]
Also, our code unnecessarily uses `==` way too often, which sends out the wrong message. In fact, in most situations `=` is good enough, and should be the thing to use. Filed a separate issue about this (#199).

**Comment by mlr-msft** [comment]
> The problem F* is complaining about is that heterogeneous equality  ==  returns a  Type  not a  bool . Changing to homogeneous equality  = , which does return a  bool , fixes the  Expected two boolean arguments  problem.
>
> Also, the first argument passed to  Bytes.make  doesn't have the right type:  Bytes.make  expects a function from  nat  to  bytes , while the code above gives it a  nat  ( 4 ).
>
> Finally, if you want to use  is_valid_endpoint_ipv4  in the refinement below, you need to mark it as  Pure . For instance by annotating it with type  UnrefinedEndPoint -> Tot bool .

That did it. Thanks! This is what I have now:
```
module Network

    assume val n2b: n:nat{n < 256} -> Tot byte
    
    type UnrefinedEndPoint = 
        {
            addr : Bytes.bytes;
            port : int
        }

   val is_valid_ipv4 : UnrefinedEndPoint -> Tot bool
    let is_valid_ipv4 ep = 
        (Bytes.length ep.addr = 4)
        && (ep.addr <> Bytes.make (fun _ -> n2b 0) 4)
        && (ep.port >= 0)
        && (ep.port <= 65535)

    type IPv4EndPoint = ep:UnrefinedEndPoint{is_valid_ipv4 ep}
```
> The  Type  vs  bool  distinction is explained in the tutorial:
https://www.fstar-lang.org/tutorial/tutorial.html#sec-bool-versus-type
 although we might indeed want to explain the  =  vs.  ==  distinction somewhere too

I was aware of the existence of and difference between the two operators but unfortunately, I had their representations reversed in my mind. I had assumed that `==` would be associated with Boolean values in a misguided attempt to leverage its resemblance to Boolean equality operators from other languages as an indication that it might be similar to `==` as used in other languages.

May I make a suggestion? I think my confusion would have been promptly resolved by reporting the types on either side of the `&&` operator. e.g:

`&& operator expected two boolean arguments, got Type and bool instead.`

Thanks again for your assistance.

**Comment by catalin-hritcu** [comment]
Agreed, error message could indeed be better. Reopening until we fix the various little things here.

**Comment by msprotz** [comment]
To be fixed in @aseemr @aseemr-msr 's branch.

**Comment by s-zanella** [comment]
The difference between the different equality operators is explained at the end of `https://github.com/FStarLang/FStar/wiki/Deriving-hasEq-predicate-for-inductive-types,-and-types-of-equalities-in-F*`

I think this summarizes it well:
```
val (=)  : #a:Type{hasEq a} -> a -> a -> Tot bool
val (==) : #a:Type -> a -> a -> Tot Type0
val (===): #a:Type -> #b:Type -> a -> b -> Tot Type0
```

**Comment by catalin-hritcu** [comment]
I created a separate wiki page with more explanations:
https://github.com/FStarLang/FStar/wiki/Different-types-of-equality-in-F*
Feel free to improve if needed. Closing.
