### ISSUE TITLE
topdown_rewrite and trefl normalize the goal when they shouldn't

### ISSUE THREAD

**Issue by Kachoc** [FStarLang/FStar#1980]
The following shouldn't do anything:
```fstar
let rewrite_nothing () =
  let ctrl (t : term) : Tac (bool & int) =
    false, 0 (* always return false ! *)
  in
  let rw () : Tac unit =
    norm [primops; iota; zeta]; trefl ()
  in
  topdown_rewrite ctrl rw; trefl ()
[@(Tactics.postprocess_with (rewrite_nothing))]
let test3 () =
  let x = 1 in
  let y = 1 in
  let b = if true then true else false in
  let z = if b then x + y else y in
  z
```

But if we print `test3` we get:
`visible let  test3 <> : _: Prims.unit -> Prims.Tot Prims.int = fun _ -> 1 + 1`

**Comment by mtzguido** [comment]
This is now fixed for `topdown_rewrite`, but I don't think we can fix `trefl` to not do normalization. The new `ctrl_rewrite` might also prove useful to you (it's similar to `topdown_rewrite` but can also work bottom up, and now handles more cases, such as lets).
