### ISSUE TITLE
Change our code to use = instead of == whenever possible

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#199]
Many people will learn F* by looking at our code, so let's make sure it's as clean as possible. For instance, I see no reason to use `==` in a context in which `=` will just do. So, unless somebody objects soon, I'm going to replace `==` with `=` whenever possible in all our code.

**Comment by nikswamy** [comment]
Good call. The (==) should be much less common now, since we moved to --rel2. What you see in existing code is often a relic of poor type inference that we had earlier.

**Comment by catalin-hritcu** [comment]
I've started doing this. In the process I noticed that in some contexts the switch requires adding explicit `b2t`coersions: https://github.com/FStarLang/FStar/commit/bb5660ddab576b3b3292ea9edce84181b1197a0a#diff-437e1d7d683c5b905a52c4c1e635fd92R32

**Comment by markulf** [comment]
One question I assume is whether we prefer b2t over (==), from the discussion here, I assume that's the case, why?

**Comment by catalin-hritcu** [comment]
I would of course prefer `=` without the b2t. Heterogeneous equality `==` at the type level is something rather exotic that should be needed very rarely.
