### ISSUE TITLE
SMT encoding of string constants is not stable

### ISSUE THREAD

**Issue by aseemr** [FStarLang/FStar#1999]
@prosecco reported a problem where F* successfully verified code with `--cache_off` while failed with `--cache_checked_modules`. After minimization, it boiled down to this:

`A.fsti`:

```
module A

val foo : string -> int

let bar () : bool =
  match foo "abcdefghijklmnopqrstuvqxyz" with
  | 0 -> true
  | _ -> false
```

`Test.fst`:

```
module Test

open A

let tbar () : bool =
  match foo "abcdefghijklmnopqrstuvqxyz" with
  | 0 -> true
  | _ -> false

let test () = assert (tbar () == bar ())
```

If we build `A.fsti.checked`, and then try to verify `Test.fst` with `--cache_checked_modules`, verification fails. While verifying `Test.fst` with `--cache_off` works.

The reason is a bug in the smt encoding of the string constants. For each string constant, F* generates a fresh `int` id, using a counter, and that's what identifies the string. When we did not cache smt encoding, this worked fine. But now since we cache the smt encoding, the id that is used in `A.fsti` becomes different than what we might use in `Test.fst` when checked files are used. With `--cache_off`, we end up using the same counter again (it's the same counter), and so the code works.

We need to properly hashcons string constants, like we do for other terms like refinement nodes etc.

**Comment by karthikbhargavan** [comment]
Wow, nice catch, Aseem!

**Comment by aseemr** [comment]
Merged to master, closing.
