### ISSUE TITLE
How can F* assert result matching with array

### ISSUE THREAD

**Issue by hungvq00390** [FStarLang/FStar#200]
I try to use assert with Quicksort function in tutorial but got error: 
Error SortPoly.fst(66,0-66,48): An unknown assertion in the term at this location was not provable
How can i do in this case ?
```
module QuickSort
val mem: 'a -> list 'a -> Tot bool
let rec mem a l = match l with
  | [] -> false
  | hd::tl -> hd=a || mem a tl
val append : list 'a -> list 'a -> Tot (list 'a)
let rec append l1 l2 = match l1 with
  | [] -> l2
  | hd :: tl -> hd :: append tl l2
val append_mem:  l1:list 'a
    -> l2:list 'a
    -> Lemma (requires True)
        (ensures (forall a. mem a (append l1 l2) = (mem a l1 || mem a l2)))
        [SMTPat (append l1 l2)]
let rec append_mem l1 l2 = match l1 with
  | [] -> ()
  | hd::tl -> append_mem tl l2
val length: list 'a -> Tot nat
let rec length l = match l with
  | [] -> 0
  | _ :: tl -> 1 + length tl
val sorted: list int -> Tot bool
let rec sorted l = match l with
    | [] -> true
    | [x] -> true
    | x::y::xs -> x <= y && sorted (y::xs)
val partition: ('a -> Tot bool) -> list 'a -> Tot (list 'a * list 'a)
let rec partition f = function
  | [] -> [], []
  | hd::tl ->
     let l1, l2 = partition f tl in
     if f hd
     then hd::l1, l2
     else l1, hd::l2
val partition_lemma: f:('a -> Tot bool)
    -> l:list 'a
    -> Lemma (requires True)
    (ensures ((length (fst (partition f l)) + length (snd (partition f l)) = length l
        /\ (forall x. mem x (fst (partition f l)) ==> f x)
        /\ (forall x. mem x (snd (partition f l)) ==> not (f x))
        /\ (forall x. mem x l = (mem x (fst (partition f l)) || mem x (snd (partition f l)))))))
    [SMTPat (partition f l)]
let rec partition_lemma f l = match l with
    | [] -> ()
    | hd::tl -> partition_lemma f tl
val sorted_concat_lemma: l1:list int{sorted l1}
    -> l2:list int{sorted l2}
    -> pivot:int
    -> Lemma (requires ((forall y. mem y l1 ==> not (pivot <= y))
        /\ (forall y. mem y l2 ==> pivot <= y)))
        (ensures (sorted (append l1 (pivot::l2))))
        [SMTPat (sorted (append l1 (pivot::l2)))]
let rec sorted_concat_lemma l1 l2 pivot = match l1 with
    | [] -> ()
    | hd::tl -> sorted_concat_lemma tl l2 pivot
let cmp i j = i <= j
val sort: l:list int -> Tot (m:list int{sorted m /\ (forall i. mem i l = mem i m)})
                            (decreases (length l))
let rec sort l = match l with
  | [] -> []
  | pivot::tl ->
    let hi, lo = partition (cmp pivot) tl in
    append (sort lo) (pivot::sort hi)

let test2 = assert((sort [3;5;7;6;8;9]) = [3;5;6;7;8;9])
```

**Comment by catalin-hritcu** [comment]
F* is not really meant for doing full evaluation of complex expressions at verification time. First, this won't be efficient. Second, there is a fixed bound up to which F* is unfolding fixpoints. If you don't care about efficiency you can set this bound much higher using these flags:
```
  --initial_fuel non-negative integer  Number of unrolling of recursive functions to try initially (default 2)
  --max_fuel non-negative integer  Number of unrolling of recursive functions to try at most (default 8)
  --min_fuel non-negative integer  Minimum number of unrolling of recursive functions to try (default 1)
```
If you care about efficiency then just extract your code to OCaml using `--codegen OCaml` and then test it in OCaml.

**Comment by catalin-hritcu** [comment]
If you go for the first option you might also want to set the `--z3timeout` flag to something large ... and then go get a coffee or something :)

**Comment by hungvq00390** [comment]
@catalin-hritcu: How can i ensure that this is correct with my below bubble sort code:
module BubbleSort

val length: list 'a -> Tot nat
let rec length l = match l with
  | [] -> 0
  | _ :: tl -> 1 + length tl
  
val sorted: list int -> Tot bool
let rec sorted l = match l with
    | [] -> true
    | [x] -> true
    | x::y::xs -> x <= y && sorted (y::xs)

let rec swap lst = 
    match lst with
    |[] -> []
    |x::[] -> x::[]
    |x::y::[] -> if x > y then y::x::[]
                 else x::y::[]
    |x::y::xs -> if x > y then 
                    y::(swap (x::xs))
                else 
                    x::(swap (y::xs))
					
let rec sort x count = if count > 1 then sort (swap x) (count - 1)
                       else x
					   
let bubleSort x = sorted (sort x (length x))
let testBubleSort x = sort x (length x)

**Comment by catalin-hritcu** [comment]
Sorry, but I don't understand your question.

**Comment by hungvq00390** [comment]
@catalin-hritcu :
I want to make sure let sort x (length x) work correctly with  sorted (sort x (length x)) = true;
How can i write this.
Thank you

**Comment by catalin-hritcu** [comment]
This is not something a tool can prove automatically for you. You can have a look here:
https://github.com/FStarLang/FStar/blob/master/examples/algorithms/insertionsort.fst
at how a similar theorem can be manually proved.

**Comment by hungvq00390** [comment]
@catalin-hritcu:
One more question. So i can not try this code:
val bubleSort : l:list int -> Tot (m:list int{sorted m})
let rec bubleSort l = match l with
    | [] -> []
    | x::xs -> bubleSort (sort xs (length xs))
Because i got BubbleSort.fst(29,0-31,34) : Error
Computed type "m:(list int){(sorted m)}" and effect "ALL" is not compatible with the annotated type "m:(list int){(sorted m)}" effect "Tot"
Can you help to explain more about this.
Thank you

**Comment by ckeller** [comment]
Dear @hungvq00390,
I think the code for of the `bubbleSort` function is simply:
```
let bubleSort x = sort x (length x)
```
You would like to prove two things.

Totality: that is quite easy to prove by annotating the type of the functions with "decreases" clauses":
```
val swap : lst:list int -> Tot (list int) (decreases (length lst))
let rec swap lst =
    match lst with
    |[] -> []
    |x::[] -> x::[]
    |x::y::xs -> if x > y then
                    y::(swap (x::xs))
                else
                    x::(swap (y::xs))

val sort : list int -> count:nat -> Tot (list int) (decreases count)
let rec sort x count = if count > 1 then sort (swap x) (count - 1)
                       else x

val bubleSort : list int -> Tot (list int)
let bubleSort x = sort x (length x)
```
(I also simplified the code for swap since one computation was redundant.)

Functional correctness: in order to prove that the result of `bubbleSort` is indeed sorted, you will need to state good invariants for the functions `swap` and `sort`... which might not be that easy.

Hope this helps,
Chantal.

**Comment by catalin-hritcu** [comment]
Everything here seems answered, closing.
