### ISSUE TITLE
Standardized output for F*

### ISSUE THREAD

**Issue by strub** [FStarLang/FStar#202]
The F* compiler should have a standardized output for helping IDE parsing its result.

**Comment by catalin-hritcu** [comment]
Do you have a particular standard in mind, or just that all errors should look the same?

This is also related to #78. There I devised a couple of regexps for parsing the current format, see:
https://github.com/FStarLang/FStar/blob/master/README.md#emacs

**Comment by strub** [comment]
I don't have any specific standard in mind, any standard will fit my needs. I can try to hack one - I know a couple of them.

**Comment by mlr-msft** [comment]
Thanks for mentioning to the regexps that you've written. I'm working on a vim plugin and those will be really helpful.

**Comment by nikswamy** [comment]
All errors are now formatted in a uniform style
