### ISSUE TITLE
Crash with bad layered `sub_effect`

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#2036]
Take for instance `examples/layered_effects/LL.fst` and replace the line:
```fstar
sub_effect PURE ~> EXN = lift_pure_exn
```
with
```fstar
sub_effect PURE ~> EXN = ereturn
```
Then F* explodes with:
```
(Error) ASSERTION FAILURE: Bound term variable not found  a#8359 in environment: ...,arrow_to_impl, uu___#8548, uu___#8541, a#8537
```

Also, non-sensical things like
```
sub_effect PURE ~> EXN = (fun (a:Type) () () () -> a)
```
give a good error, but the range is empty and makes emacs jump to the top of the file.

**Comment by aseemr** [comment]
Thanks Guido, I am cleaning up some error messages, debug logs, etc. around it, will try to fix these as well.

**Comment by aseemr** [comment]
This is working fine in master:

![image](https://user-images.githubusercontent.com/3921573/228235273-00823763-6aa9-42b0-b502-cc2caf99f9da.png)

![image](https://user-images.githubusercontent.com/3921573/228235348-6f4ffe4a-4d7a-4063-aa46-b35c504d82d0.png)


Similar error and range is shown for the second example of abstraction.

Closing it, please reopen if needed, thanks!
