### ISSUE TITLE
Can F* convert from string to list character ?

### ISSUE THREAD

**Issue by hungvq00390** [FStarLang/FStar#204]
I want to convert from string like "#34+12-21#1" to list char ['#'; '3'; '4'; '+'; '1'; '2'; '-'; '2'; '1'; '#'; '1']
in F# i can do 
let string2char (s:string) = [for c in s -> c]

And i want to know more about SMTPat, which is difference when do not have this SMTPat.
Thank you

**Comment by catalin-hritcu** [comment]
I'm not sure about the first question, but for the second you can have a look here:
https://www.fstar-lang.org/tutorial/tutorial.html#sec-smt-lemmas--bridging-the-gap-between-intrinsic-and-extrinsic-proofs
With SMTPat the lemma is can be automatically applied by the SMT solver, without it not.

You can look at page 25 of the SMT-LIB standard for how SMT solvers use patterns:
http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.0-r12.09.09.pdf

**Comment by nikswamy** [comment]
`string` is an abstract primitive type in F*. 

To convert between strings and list of char you can write an implementation in F# or OCaml and link to it in your F* development. 

For example:

```
assume val to_char_list : string -> Tot (list char)
```

We may add this to the standard library ourselves.
