### ISSUE TITLE
Bug with dependent tuples inside records

### ISSUE THREAD

**Issue by nomen-fictus** [FStarLang/FStar#2042]
The following fragment of code
```fstar
noeq type example = {
  one   : t:Type0 & (t -> Type0) ;
  two   : dfst one ;
  three : dsnd one two
}
```
produces the next error message
```
(Error) Expected a term of type 'Type'; got FStar.Pervasives.dsnd one two : b (let (| _1 , _ |) = t in
    _1)
```
while its modification (as suggested by Catalin Hritcu)
```fstar
noeq type record = {
  fst : Type0;
  snd : fst -> Type0
}

noeq type example = {
  one   : record ;
  two   : one.fst ;
  three : one.snd two
}
```
is accepted.

**Comment by catalin-hritcu** [comment]
Here's a link to the original discussion about this:
https://fstar.zulipchat.com/#narrow/stream/184683-questions-and.20help/topic/Me.20vs.2E.20tuples

For whatever that's worth, the original code works when ported to Agda.

**Comment by aseemr** [comment]
This example works with master, I am tempted to point to the recent projectors/patterns fixes. Closing the issue, please reopen if you still see this.
