### ISSUE TITLE
Problem with WellFounded.apply ? (aka Function application is not invariant under ==)

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#2043]
Reported by Nomen Fictus on [zulip](https://fstar.zulipchat.com/#narrow/stream/183902-language-design/topic/Termination.20checker.20too.20strict). 
The following function definition `func` that looks legitimate to me fails to be defined 
```fsharp
open FStar.WellFounded

noeq type example =
  | One : (nat -> example) -> example
  | Two : example

val func : example -> example
let rec func e =
  match e with
  | One f -> func (apply f 1)
  | Two -> Two
```
Terminates with 
```(Error 19) Could not prove termination of this recursive call; The solver found a (partial) counterexample, try to spell your proof in more detail or increase fuel/ifuel```

It works if `func (apply f 1)` is replaced by `apply f 1 ; func (f 1)`. 
F* is also able to prove the assertions
```fsharp
assert (apply f 1 << e); 
assert (apply f 1 == f 1)
```
so the failure above is a bit mysterious for me.

**Comment by nikswamy** [comment]
Thanks for reporting. Looks like we're losing precision in building VCs in monadic application. This works, for example (using Tot instead of Pure).

```
open FStar.WellFounded

noeq type example =
  | One : (nat -> example) -> example
  | Two : example


let apply (#a:Type) (#b:a -> Type) (f: (x:a -> Tot (b x))) (x:a)
  : Tot (r:b x{r == f x /\ f x << f})
  = axiom1_dep #a #b f x ; f x

val func : example -> example
let rec func e =
  match e with
  | One f -> func (apply f 1)
  | Two -> Two
```

**Comment by aseemr** [comment]
This is fixed as part of https://github.com/FStarLang/FStar/pull/2205. Since there are several similar testcases in tests/micro-benchmarks/TestWellFoundedRecursion.fst, not adding a testcase for it.
