### ISSUE TITLE
Bug in extraction when two records have a field with the same name

### ISSUE THREAD

**Issue by mateuszbujalski** [FStarLang/FStar#2058]
Hi,

I've noticed that when you have two records which have a field with the same name, type definitions extract correctly with unique field names, however call sites are always using a name generated for the last defined record.

Example

```
type record1 = { field : string }
type record2 = { field : list string }

let r1 = Mkrecord1 "aaa"
let r2 = Mkrecord2 [ "aaa"; "bbb" ]
```

extracts to

```
type record1 = { field : Prims.string }
type record2 = { field1 : Prims.string Prims.list }

(* Notice that r1 has field "field1" instead of "field" *)
let r1 : record1 = { field1 = "aaa" }
let r2 : record2 = { field1 = ("aaa")::("bbb")::[] }
```

It happens both for OCaml and FSharp extraction.

**Comment by mtzguido** [comment]
This was fixed by the PR, closing.
