### ISSUE TITLE
Layered effect: extraction failure (`Warn 4: subtype mismatch`)

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#2059]
Hi,

We are trying to make a layered effect (named `BUG` here) and extract it with KreMLin, but we face a `Warning 4` (`subtype mismatch, Bug_context (a.k.a. Bug_context) vs Bug_context -> Bug_context (a.k.a. Bug_context -> Bug_context)`) while extracting.

We wrote a minimal example for our bug (the module `Bug` here https://gist.github.com/W95Psp/f56882379b756ca3f7511000ec6d0969, for which KreMLin gives the following output https://gist.github.com/W95Psp/d05d0fb84afbb4e4d0b1947441072ca2).

Our goal is to have an effect defined as a "proxy" of `STATE`, and extract it to C (by reifying `BUG` to `STATE`).

Our layered effect has the following representation:
```
type context = | Context

let pair = context & HS.mem

type pre_t = st_pre_h pair
type post_t (a:Type) = a -> pair -> Type0
type wp_t (a:Type) = wp:(post_t a -> pre_t){
  forall p q. (forall x s. p x s ==> q x s) ==> (forall s. wp p s ==> wp q s)
}

type repr (a:Type) (wp:wp_t a) =
  (c: context) -> STATE a (fun (p: st_post_h _ a) (h0: HS.mem) ->
    wp (fun x (c', h1) ->
         c' == c /\
         ( equal_domains h0 h1
         ) ==> p x h1
       )
       (c, h0)
  )
```

From KreMLin's output, it seems like functions in our effect `BUG` are reified weirdly: it seems like the `context` used in our representation is duplicated in type signature.

We're not too sure it's an actual bug or something we did wrong :)

Thanks for your help!

**Comment by msprotz** [comment]
Thanks for the great bug report, I'll take a look at it. I don't know if we've tested extraction of layered effects yet... @aseemr ?

**Comment by aseemr** [comment]
I have tested extraction of layered effects on some example (e.g. `examples/layeredeffects/parsing` etc.). I can check the F* output to Kremlin first, and then ping @protz if it needs Kremlin debugging.

**Comment by W95Psp** [comment]
Thanks for your answers!

@aseemr: yes, I saw the examples, they were quite helpful :)
I think these used to work, but trying to extract them with F* from master (that is: `make extract` in `examples/layeredeffects`, removing the `Buffers` module from that makefile) now leads to that same `Warning 4`: see https://gist.github.com/W95Psp/f585e258ab272069f76b4081b1f9af5c#file-log-parsing-examples-without-buffers-L344-L357.

I'm currently building F* at the latest commit from `examples/layeredeffects/parsing` (that is `07a8583a18e38680743c861574a951b883b2d560`), to see if it's a newer F* commit that introduced a bug or something; I'll post an update later today about that.

**Comment by aseemr** [comment]
Many thanks @W95Psp, appreciate your help. The extraction is under CI, so it may have regressed.

**Comment by W95Psp** [comment]
Happy to help! :)

So, I've tried several F* version, especially the two following:

| F*                                       | Kremlin                                  |
| --- | --- |
| https://github.com/FStarLang/FStar/commit/381e2f659f0f73e09dff13fe968eeb61f5449e1f (17 Oct 2019) | https://github.com/FStarLang/kremlin/commit/882534387830a4cc259c1a543e0dfc10dcc70f52 |
| https://github.com/FStarLang/FStar/commit/07a8583a18e38680743c861574a951b883b2d560 (06 Nov 2019) | https://github.com/FStarLang/kremlin/commit/882534387830a4cc259c1a543e0dfc10dcc70f52 |

Sadly, I still some `warning 4` (e.g. https://gist.github.com/W95Psp/2ce8cbfb3aa9e5ebe4617331f863f878 with F* rev. 07a8583a18e38680743c861574a951b883b2d560) about type mismatch.

However, with a recent version of F*, looking again at the output I posted the other day (https://gist.github.com/W95Psp/f585e258ab272069f76b4081b1f9af5c#file-log-parsing-examples-without-buffers-L344-L357), the `warning 4` are not about `subtype` any longer, but : `Type annotation is not an lid`. What is a `lid` in F*'s AST?

So I'm not too sure about what to conclude here.

**Comment by msprotz** [comment]
sorry for the delay... I'll try to take a look this week

**Comment by W95Psp** [comment]
Hi, did you had some time to look a bit?

**Comment by aseemr** [comment]
Sorry for not looking at it earlier @W95Psp , I just debugged it a little.

I first tried to see if the OCaml code generation is working fine. And I saw that there was an `Obj.magic` in there, which is already a red flag. When I made the `repr` type as `inline_for_extraction`, that `Obj.magic` went away, so somehow F* is not able to type the OCaml expression appropriately, unless the type is inlined.

I then tried the Kremlin extraction, and still got some errors (subtype mismatch errors). So then I also inlined `test` and then Kremlin extraction also worked. May be Kremlin is not able to properly determine the arity of this function, cc @msprotz.

I had to update the report a bit to make it work with the latest F* master (there were some changes in how the layered effect is typechecked). Please find the latest defn. below, hopefully this should unblock you. I will try to look into the OCaml extraction issue, while happy to discuss the Kremlin issue with @msprotz .

```
module Test

open FStar.HyperStack.ST
module U32 = FStar.UInt32
module HS = FStar.HyperStack

inline_for_extraction
type context =
  | Context

let pair = context & HS.mem

inline_for_extraction type pre_t = st_pre_h pair
inline_for_extraction type post_t (a:Type) = a -> pair -> Type0
inline_for_extraction type wp_t (a:Type) = wp:(post_t a -> pre_t){
  forall p q. (forall x s. p x s ==> q x s) ==> (forall s. wp p s ==> wp q s)
}

inline_for_extraction
type repr (a:Type) (wp:wp_t a) =
  c:context -> STATE a (fun (p:st_post_h _ a) (h0:HS.mem) ->
    wp (fun x (c', h1) -> (c' == c /\ equal_domains h0 h1) ==> p x h1) (c, h0))

unfold
let return_wp (#a:Type) (x:a) : wp_t a = fun p s -> p x s

inline_for_extraction
let return (a:Type) (x:a)
  : repr a (return_wp x)
  = fun _ -> x

unfold
let bind_wp (#a:Type) (#b:Type) (wp_f:wp_t a) (wp_g:a -> wp_t b)
  : wp_t b
  = fun p -> wp_f (fun x -> wp_g x p)

inline_for_extraction
let bind (a:Type) (b:Type)
  (wp_f:wp_t a) (wp_g:a -> wp_t b)
  (f:repr a wp_f) (g:(x:a -> repr b (wp_g x)))
  : repr b (bind_wp wp_f wp_g)
  = fun c ->
    let x = f c in
    g x c

inline_for_extraction
let subcomp (a:Type)
  (wp_f:wp_t a) (wp_g:wp_t a)
  (f:repr a wp_f) 
  : Pure (repr a wp_g)
      (requires forall p s. wp_g p s ==> wp_f p s)
      (ensures fun _ -> True)
  = f

unfold
let if_then_else_wp (#a:Type) (wp_f wp_g:wp_t a) (p:bool)
  : wp_t a
  = fun post s -> (p ==> wp_f post s) /\ ((~ p) ==> wp_g post s)

inline_for_extraction
let if_then_else (a:Type)
  (wp_f:wp_t a) (wp_g:wp_t a)
  (f:repr a wp_f) (g:repr a wp_g)
  (p:bool)
  : Type
  = repr a (if_then_else_wp wp_f wp_g p)

reifiable reflectable
layered_effect {
  BUG : a:Type -> wp_t a -> Effect
  with
  repr           = repr;
  return         = return;
  bind           = bind;
  subcomp        = subcomp;
  if_then_else   = if_then_else
}

inline_for_extraction noextract
let get_ctx () : BUG context (fun p (c, h) -> p c (c, h))
  = BUG?.reflect (fun c -> c)

//We use ulib/FStar.Monotonic.Pure module to assume the monotonicity of pure wps
//But somehow that doesn't work if I add a call to that lemma inside the defn. of lift_pure
//So adding it here for now
assume WP_mono :
  forall (a:Type) (wp:pure_wp a).
    (forall (p q:pure_post a). (forall x. p x ==> q x) ==> (wp p ==> wp q))

unfold
let lift_pure_wp (#a:Type) (wp:pure_wp a)
  : wp_t a
  = fun p s -> wp (fun x -> p x s)

inline_for_extraction
let lift_pure (a:Type) (wp:pure_wp a) (f:eqtype_as_type unit -> PURE a wp)
  : repr a (lift_pure_wp wp)
  = fun s -> f ()

sub_effect PURE ~> BUG = lift_pure

inline_for_extraction
let test () : BUG U32.t (fun p tup -> p 5ul tup)
  = 5ul

let main ()
  : ST U32.t (fun _ -> True) (fun _ _ _ -> True) =
  let ctx = Context in
  let test_ret = reify (test ()) ctx in
  test_ret
```

**Comment by msprotz** [comment]
sorry for the delay

@aseemr taking your latest iteration of the example, I ran:
```
jonathan@absinthe:~/Code/kremlin/test (master) $ fstar.exe --include .cache --codegen OCaml --extract Layered Layered.fst
```

then here's what I got in Layered.ml:

```
  26 let (test : unit -> (FStar_UInt32.t, unit) repr) =
```

but `repr` is `inline_for_extraction`, so it should never appear anywhere -- it seems like the normalizer is failing to replace `repr` with its definition

this is a first issue, I'll keep digging a little bit

**Comment by msprotz** [comment]
this is actually the only issue in the current example, but it's compounded by some other unpleasantness:

1) when trying to generate a (mostly) first-order kremlin AST, F* looks into the type annotation of a top-level binding to find the types of the arguments and the return type... let's look at the OCaml extraction to figure out how things are going:

```
let (test : unit -> (FStar_UInt32.t, unit) repr) =
  fun uu____407 -> fun s -> FStar_UInt32.uint_to_t (Prims.of_int (5))
```

F* is trying to interpret this as a first-order function signature before handing it off to KreMLin; however, the type annotation has one arrow, and the `fun` has *two* arguments, so there's a mismatch here... giving rise to this error (an F* error):

```
Attempting to translate module Layered
Not extracting Layered.test to KreMLin (function type annotation has less arrows than the number of arguments; please mark the return type abbreviation as inline_for_extraction)
```

2) however, for some reason, the function is extracted nonetheless

---

Conclusion: there's a genuine F* normalization bug that fails to inline the `repr` type in the type annotation of `test`

Some takeways:
- if your layered effect has an arrow type, always make that type inline_for_extraction
- the error reporting isn't that great, sorry
- maybe we should make that warning ("less arrows than arguments on the function") fatal

**Comment by msprotz** [comment]
I hope this helps, @aseemr let me know if you agree with me that there's a normalizer bug and @W95Psp let me know if you're unblocked once that normalization bug is fixed...

**Comment by aseemr** [comment]
Right, we needed one more call to the normalizer after reifying the computation type. I have fixed it in master, and so, `test` is now extracted as:

```
let (test : unit -> context -> FStar_UInt32.t) =
  fun uu____18526 -> fun s -> FStar_UInt32.uint_to_t (Prims.of_int (5))
```

I am all in favor of making ("less arrows ...") fatal.

Closing the issue. Thanks for your patience @W95Psp , hope this unblocks you, and thanks @msprotz for debugging help.

**Comment by msprotz** [comment]
This is now under regression testing in kremlin

**Comment by W95Psp** [comment]
That's great, thank you very much! :)
(I'm not able to test this right now on my code, upgrading F* breaks other stuff -- related to stricter subtyping in layered effect I think)
