### ISSUE TITLE
Linux binary build broken (looks for hints at the wrong location)

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#2068]
(Also reported on Slack, but since no one reacted I'm saving this information here.)

Our F* binary builds started failing on Linux around 2 weeks ago (after working just fine most of the time since our last release one year ago): https://everestlogstorage.blob.core.windows.net/fstar-binaries-linux/buildlogfile_FStar-Binaries-Linux-20200608-1.txt

I can also reproduce the problem locally, both when running `.scripts/process_build.sh` and afterwards and until a full cleanup even when running `make -C tests/micro-benchmarks` in the root of the repo:
```
[CHECK     Steel.Semantics.Hoare.MST.fst]
/home/hritcu/Projects/fstar/pub/src/ocaml-output/fstar/ulib/experimental/Steel.Semantics.Hoare.MST.fst(1259,2-1277,29): (Error 16) Unknown assertion failed; The SMT query timed out, you might want to increase the rlimit
(Warning 333) Unable to open hints file: /home/hritcu/Projects/fstar/pub/src/ocaml-output/fstar/ulib/experimental/Steel.Semantics.Hoare.MST.fst.hints; ran without hints

make: *** [../../examples/Makefile.common:74: _cache/Steel.Semantics.Hoare.MST.fst.checked] Error 1
make: Leaving directory '/home/hritcu/Projects/fstar/pub/src/ocaml-output/fstar/tests/micro-benchmarks'
```

The problem seems to be caused by the hints being looked up at the wrong location:
`Unable to open hints file: <fstar-dir>/src/ocaml-output/fstar/ulib/experimental/Steel.Semantics.Hoare.MST.fst.hints; ran without hints`.
The actual location of this hint file is
`<fstar-dir>/src/ocaml-output/fstar/ulib/.cache/Steel.Semantics.Hoare.MST.fst.hints`

There are lots of such warnings in the log of binary builds now, not just for this particular file.

**Comment by catalin-hritcu** [comment]
The binary build for Linux started working again, but the underlying problem seems still there: the log is still full of `run without hints` warnings (including the original one above): https://everestlogstorage.blob.core.windows.net/fstar-binaries-linux/buildlogfile_FStar-Binaries-Linux-20200706-1.html

So I suspect that what happened is that someone (@aseemr ?) made `Steel.Semantics.Hoare.MST.fst` work again even without hints. We also need a fix for the underlying problem though :)

**Comment by tahina-pro** [comment]
The underlying cause is that, since ulib .checked files were not part of the binary packages back then, they were reverified as part of tests/ and examples/ . PR #2275  will solve this issue.
