### ISSUE TITLE
"Bound term variable not found" in Hurkens paradox

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#207]
This one was reported by Yannik Forster and Steven Schäfer a while back. It's still happening. The code is in: https://github.com/FStarLang/FStar/blob/master/examples/paradoxes/hurkens.fst

**Comment by nikswamy** [comment]
This is a duplicate with 170b ... which is still open.

**Comment by catalin-hritcu** [comment]
Closing that one instead, since this one has a better description on what's left to do.

**Comment by nikswamy** [comment]
We now get an accurate (if very verbose) error message. 

However, I think this paradox should be encodable in F\*. I guess `b2p` should not be declared as an inductive ... rather it should be an assumed type ... as in the Coq development of this.

**Comment by nikswamy** [comment]
Closing this as it is no longer a bug.

**Comment by yforster** [comment]
The initial idea why we approached  this was that Hurkens paradox might be encodable in F* without any further assumptions.

At least, anything that is assumed in the Coq development can be encoded in F* in some way by just importing the classical library. I don't know if this is enough to port the rest of the Coq proof (p2p1 has a weaker type than the version in Coq), but writing it down here might allow somebody else to investigate this :)

```
assume val excluded_middle : p:Type -> Tot (b:bool{b = true <==> p})
assume val give_proof: #a:Type -> a -> Lemma (ensures a)

val p2b: p:Type -> Tot (b:bool{b = true <==> p})
let p2b (p : Type) = excluded_middle p
                                             
type b2p : bool -> Type =                          
  | B2pI : b2p true

val p2p1 : a:Type -> x : (b2p(p2b a)) -> Lemma a
let p2p1 (a:Type) x = ()

val p2p2 : a:Type -> a -> Tot (b2p(p2b a))
let p2p2 (a : Type) (x : a) = give_proof x; match p2b a with true -> B2pI
```
