### ISSUE TITLE
A soundness issue?

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#2072]
I was handed a bug report for the HaCl* Merkle trees, where the highest-level symptom is that the extracted C code segfaults after a few operations on the tree. I've traced it down to the fact that it tries to malloc zero bytes, which causes null pointers where they are not expected. 

The problem is that during deserialization of a Merkle tree, zero-size vectors are created ([here](https://github.com/project-everest/hacl-star/blob/9cd7e909083a04452f7ef614fae48aa45db88dc2/secure_api/merkle_tree/MerkleTree.Low.Serialization.fst#L328)); those also have capacity zero. Then, an attempt is made to insert a hash into that tree via `mt_insert`, which grows the capacity of one of the vectors ([here](https://github.com/FStarLang/FStar/blob/15fe9e9322ed406b7144a688e68e5d2804b08ab2/ulib/LowStar.Vector.fst#L466)). However, `new_capacity` has `cap > 0ul` as a precondition ([here](https://github.com/FStarLang/FStar/blob/15fe9e9322ed406b7144a688e68e5d2804b08ab2/ulib/LowStar.Vector.fst#L440)). For some reason, this verifies and extracts without problems, but the final C code is not safe. 

Here's my attempt at a minimal repo:

```
module MerkleTree.Bug

open FStar.Integers

module V = LowStar.Vector
module B = LowStar.Buffer
module HST = FStar.HyperStack.ST

type hash_size_t = n:V.uint32_t{n > 0ul}
type hash (#hsz:hash_size_t) = b:B.buffer FStar.UInt8.t { B.len b = hsz ∨ B.g_is_null b }

let f (#hsz:hash_size_t) (h:hash #hsz)
: HST.ST (V.vector (hash #hsz))
    (requires (λ h0 → ⊤))
    (ensures (λ h0 v h1 → ⊤))
= let v = V.alloc_empty hash in
  let h0 = HST.get() in
  assert (V.live h0 v);
  assume (V.freeable v);
  assert (not (V.is_full v));
  assume (HST.is_eternal_region (V.frameOf v));
  assert (V.Vec?.sz v == 0ul);
  assert (V.Vec?.cap v == 0ul);
  V.insert v h
```

This verifies despite the fact that `cap > 0ul` in `V.insert` is violated (with `sz==cap==0`). I'm not sure about the two `assume` statements - somehow these are satisfied by other means in rest of the code.

I'll submit a patch for `new_capacity` to handle the 0-case gracefully, but I think this should never have verified, so it would be great if one of you could take a look at this to check whether that's a real bug.

**Comment by mtzguido** [comment]
This lemma in `LowStar.Monotonic.Buffer` makes me think that it's the `freeable` assumption that should not be provable.
```fstar
val freeable_length (#a:Type0) (#rrel #rel:srel a) (b:mbuffer a rrel rel)
  :Lemma (requires (freeable b)) (ensures (length b > 0))
         [SMTPat (freeable b)]
```
This also works:
```fstar
let f (#hsz:hash_size_t) (h:hash #hsz)
: HST.ST (V.vector (hash #hsz))
    (requires (λ h0 → ⊤))
    (ensures (λ h0 v h1 → ⊤))
= let v = V.alloc_empty hash in
  assume (V.freeable v);
  assert False;
  V.insert v h
```
But I'm not an expert in all this so maybe wait for an authoritative opinion :-).

**Comment by wintersteiger** [comment]
Yeah, that `length b > 0` definitely looks related! I'll have to check how the Merkle tree code satisfies that.

**Comment by msprotz** [comment]
This is strange. Christoph, keep us posted once you narrow it down.

Some context: the Low\* model of C heap-allocated arrays is more restrictive than C. In particular, Low\* rules out heap-allocated zero-length arrays (see `malloc_pre` at line 2110 of LowStar.Monotonic.Buffer.fsti). This is what allows `freeable_length` to be provable.

However, this is incorrect with regards to the C standard (zero-length, heap-allocated arrays *are* allowed, it's just that the return value in this case is implementation-dependent and not necessarily NULL). It's not a big deal and just means that users need to always use NULL when they need a zero-length array. (Hence the definition of `hash`.)

Could it be that somewhere there is a `false` precondition, e.g. someone requiring a heap-allocated array that *is in region `r`* and of size zero?

**Comment by wintersteiger** [comment]
I think I've gotten somewhere close to the bottom of this. The problem is that the definition of the Merkle tree type doesn't require memory safety its substructures, it has to be established separately (`mt_safe`). My deserialization code doesn't establish all of this, but some other functions assume it (and are then called from C without checks). 

I submitted https://github.com/project-everest/hacl-star/pull/328, which uses the "correct" non-empty vectors, this is what the new proofs will be based on, but CCF needs a fix immediately.

Another workaround is https://github.com/FStarLang/FStar/pull/2073, which enables growing empty vectors. I think this should be merged in any case, because nobody expects that `new_capacity` of a zero-size vector is again zero.

**Comment by msprotz** [comment]
Thanks for the investigation. Merging #2073 only seems like the best solution, since it makes the Vector API more robust and general.

Once #2073 is merged, the C code in dist/merkle-tree will be automatically refreshed by the nightly job within 24h to include the fix. Is this ok for you? This entails closing project-everest/hacl-star#328 without merging. Let me know if you believe that PR has to be merged as well.

Once way to make sure there are not further errors lurking in the code is to write a verified test, which exercises the deserialization, serialization and merkle tree APIs to make sure that there's no un-satisfiable precondition or missing post-condition from any of these functions. (It's a classic pitfall and has happened in the past for HACL.)

**Comment by wintersteiger** [comment]
Yeah, we need only one of them quickly. https://github.com/project-everest/hacl-star/pull/328 is the behavior it will have after the proofs are finished, so that can wait until I'm done with the proofs.

I'm planning to add a verified test as you suggest, but I can't currently estimate how much effort that will take. It may take me quite a bit of time to get all of that through the toolchain.

**Comment by nikswamy** [comment]
Is this really an unsoundness?

Any resolution of this issue? @protz  @wintersteiger 

Thanks!

**Comment by msprotz** [comment]
Based's on Christoph's earlier comment: the deserialization function does not establish the invariant, which makes it likely that a C client will deserialize a merkle tree (for which the invariant thus does *not* hold), then feed it to the merkle tree API which expects the invariant to hold. This triggers a segfault which #2073 works around but we don't know for sure that there aren't other unsoundnesses lurking in the Merkle Tree API.

The current API requires `False` for all preconditions: https://github.com/project-everest/hacl-star/blob/master/secure_api/merkle_tree/MerkleTree.fsti -- so we shouldn't look at this top-level file to see if the invariants are setup properly.

If we look at individual modules, we can see that e.g `mt_insert` requires the `mt_safe` invariant https://github.com/project-everest/hacl-star/blob/master/secure_api/merkle_tree/MerkleTree.Low.fst#L945 but that this is not established by the deserialization function https://github.com/project-everest/hacl-star/blob/master/secure_api/merkle_tree/MerkleTree.Low.Serialization.fst#L456

The best course of action would be to fix the top-level API to have proper pre- and post-conditions, then to write a verified test that exercises all the API functions to make sure the API can be used soundly. It's not an absolute guarantee, but at least would rule out that sort of errors.

So, if anything, this issue can be closed as it's an unsoundness of the merkle tree API as currently exposed, not an unsoundness in F*.

**Comment by wintersteiger** [comment]
Yeah, the .fsti is just a shim to get a more readable .h. I started setting up an end-to-end test, but I didn't get very far yet. It will likely take me a very long time to get there and until then we shouldn't assume there's a bug in F*, so we can close this issue.
