### ISSUE TITLE
Unexpected error: "NYI: eta_expand(Tm_app)"

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#208]
Blowup while working on wf.fst.

**Comment by vkanne-msft** [comment]
Unable to reproduce exact issue. 
$ fstar --universes bug208.fst
D:\Sources\FStar\examples\bug-reports\bug208.fst(11,34-11,35) : Error
Expected expression of type "(Bug208.acc (?14321 a))";
got expression "a" of type "(_:Prims.int -> Type)"

@catalin-hritcu can you kindly check and reopen the issue ?

**Comment by catalin-hritcu** [comment]
After a very small tweak to account for the way `--universes` deals with implicit arguments I could reproduce the blow up with `--universes`. The unexpected error looks a bit different:
```
Failure("NYI: eta_expand(Tm_app) (?14344 r a)")
```

**Comment by catalin-hritcu** [comment]
This seems to no longer blow up now. Closing.
```
[hritcu@detained bug-reports]$ fstar.exe bug208.fst
./bug208.fst(11,39-11,50) : Error
(?31760 r a) is not equal to the expected type (r y)
```
