### ISSUE TITLE
Invalid_argument("output_value: functional value")

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#2086]
On branch `protz_null` (commit 9a04e1d9ac827a1d42699400dd913a0a52efeb1e), running `make` results in:

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Invalid_argument("output_value: functional value")
make[3]: *** [.cache.lax/LowStar.Buffer.fst.checked.lax] Error 1
make[3]: *** Waiting for unfinished jobs...
```

This is probably related to my removing the use of use_extracted_interfaces on a couple files. This has been observed on CI as well: https://msr-project-everest.visualstudio.com/Everest/_build/results?buildId=48418&view=logs&j=8f20da19-31b7-5cef-4813-95b8788bd086&t=cf64427e-dd63-54b9-31a8-cb7e035fee68

Thanks,

Jonathan

**Comment by mtzguido** [comment]
Will be fixed by PR #2091
