### ISSUE TITLE
Not so natural way to name implicit arguments in function definition

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#209]
Problem while working on wf.fst. No time to minimize, but I'll return to this.

**Comment by catalin-hritcu** [comment]
Just for the record, never really meant to make those arguments implicit. Any way to override the questionable default that all types are implicit, by the way?

**Comment by nikswamy** [comment]
How about this:

If you write:
```
'a -> 'b -> M ('a * 'b)
```
i.e., ML-style types; then this is sugar for 

```
#a:Type -> #b:Type -> a -> b -> M (a * b)
```

where the type arguments are implicit.

Otherwise, with the notation

```
a:k -> t
```

the type variable `a` must be explicitly provided.

**Comment by catalin-hritcu** [comment]
@nikswamy I think this would be much more reasonable. It's unrelated to the original problem in this issue though, where we had no way to name implicit type arguments in the function's body. Sorry for mixing two problems into one here.

**Comment by nikswamy** [comment]
a465a241a90e064faa347f9deacde8eec12a1c70 Should be supported now

**Comment by catalin-hritcu** [comment]
The test file for this bug still fails and I still don't know how to fix it.

**Comment by nikswamy** [comment]
Here's how you can write it:

```
module Bug209

(* Need a way to name the implicit t in the body *)

val foo : #t:Type -> x:t -> Lemma (x = x)
let foo (#t:Type) x = ()

val foo2 : t:Type -> x:t -> Lemma (x = x)
let foo2 (t:Type) x = ()

val foo3 : x:'a -> Lemma (x = x)
let foo3 'a x = ()
```

**Comment by nikswamy** [comment]
I guess you would prefer to write it as

```
val foo: #t:Type -> x:t -> Lemma (x=x)
let foo t x = ()
```

At the moment, F\* does not recognize that the variable `t` in the second line is a type-binding. Adding the `:Type` tells the desugaring phase to treat `t` as a type. Alternatively, you can use a ticked variable. It would be nice if F\* could figure that out without the tick.

Changing this to an enhancement.

**Comment by catalin-hritcu** [comment]
This is no longer a problem with universes.
