### ISSUE TITLE
Closed typeclass doesn't work, but it works in Coq

### ISSUE THREAD

**Issue by andricicezar** [FStarLang/FStar#2097]
Me and Catalin tried the following code but it fails with an error:
```
module Test

type is_ml : Type -> Type0 =
| ML_unit : is_ml unit
| ML_bool : is_ml bool
| ML_int : is_ml int
| ML_string : is_ml string
| ML_arrow : a:Type -> b:Type -> is_ml a -> is_ml b -> is_ml (a -> b)
// | ML_pair : a:Type -> b:Type -> is_ml a -> is_ml b -> is_ml (a & b)    // fails for this one too

```

Error:
```
(Error) Failed to solve universe inequalities for inductives
```
Are we doing something wrong or is it a bug?

The same thing works fine in Coq :
```
Inductive is_ml : Type -> Prop :=
| ML_unit : is_ml unit
| ML_nat : is_ml nat
| ML_pair : forall (a b:Type), is_ml a -> is_ml b -> is_ml (a*b).
```

This was tested on FStar branch master: 35343f0c1d235fb7b67fd73a4e4a9ee5b908bf4c (14 July)

Thank you!

**Comment by catalin-hritcu** [comment]
This was just a misunderstanding from our side of how universes work. The only reason it worked in Coq is that we were using `Prop`, which is impredicative.
