### ISSUE TITLE
Encoding of polymorphic refined functions total fail

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#210]
Problem while working on `wf.fst`. Basically had to hoist two type arguments to the very top level so that they can be shared among 2 definitions, otherwise F* can't even prove transitivity of `<<`. No time to minimize, but I'll return to this.
```
(* Working around silly implicit argument stuff in F*,
   can't name these things otherwise in function body 
   + putting this just before fix_F also causes lots of troubles
     (see all the commented out admitPs in fix_F;
      even transitivity doesn't work) *)
assume type aa : Type
assume type r : (aa -> aa -> Type)
```

**Comment by catalin-hritcu** [comment]
The minimal counterexample for this is this:
```
assume val acc_inv : aa:Type -> a:int -> Tot (e:int{e = a})
val fix_F : a:int -> Tot unit
let fix_F a = assert(acc_inv a = a)
```
The problem seems to be caused by incompleteness in the SMT encoding of polymorphic functions. Removing the `aa` argument to `acc_inv` makes this work.

**Comment by catalin-hritcu** [comment]
Turning the `a:int` into `a:aa` in the signature of `acc_inv` in the minimal code above (in `bug210c.fst`) makes this work again:
```
assume val acc_inv : aa:Type -> a:aa -> Tot (e:int{e = a})
```
Same thing if I explicitly pass the type argument explicitly when calling `acc_inv`:
```
let fix_F a = assert(acc_inv #unit a = a)
```
I'm starting to think that for a start we might want to reject this because of unbound unification variables before SMT encoding anything.

**Comment by nikswamy** [comment]
This is no longer reproducible. `fstar` complains about an unresolved unification variable in the argument of `acc_inv` now.
