### ISSUE TITLE
Typo in option name.

### ISSUE THREAD

**Issue by arthuraa** [FStarLang/FStar#2103]
Not super important, but one of the command-line options has a misspelling of "coercions" (`__ml_no_eta_expand_coertions`).

**Comment by mtzguido** [comment]
Thanks for reporting! I think I added this option some years ago to retain the old behavior after some patches to extraction, but I don't think anyone ever needed it. I would advocate for just removing it. (Unless you are using it?)

**Comment by arthuraa** [comment]
I am not -- I just noticed it by accident!
