### ISSUE TITLE
Standard ML modules

### ISSUE THREAD

**Issue by artella-coding** [FStarLang/FStar#211]
Hi, will FStar be getting Standard ML modules & functors like those described in http://jozefg.bitbucket.org/posts/2015-01-08-modules.html ? Thanks

**Comment by catalin-hritcu** [comment]
Maybe via a F-ing modules translation?

**Comment by artella-coding** [comment]
I didn't have any particular approach in mind (just wondered whether you had something like that in mind, or whether there was a similar feature already in the language: I looked through the docs but could not find anything).

**Comment by catalin-hritcu** [comment]
Nik can probably give you a better answer, but I think there are no immediate plans for this. My impression is that historically this has to do with F# not supporting functors either (https://stackoverflow.com/questions/14777522/if-sml-net-had-functors-why-cant-f). We're no longer tied that much to F# now though, so maybe at this point it's just for simplicity?

**Comment by nikswamy** [comment]
It's unlikely that we'll be adding functors any time soon. There are too many other things in the queue before it. If we do eventually get to it, I imagine we'd encode it like Catalin suggests.

**Comment by artella-coding** [comment]
@catalin-hritcu @nikswamy p.s. there was an interesting discussion (involving Rob Harper https://github.com/RobertHarper) on the rust programming language issue at https://github.com/rust-lang/rfcs/issues/493

**Comment by artella-coding** [comment]
@catalin-hritcu @nikswamy 

In the absence of modules, how can I succinctly synthesize a third type without explicitly specifying all the "arguments" of the types from which it is being constructed from? For example in SML (polyml) I can do the following. Note that when I construct a type of type `THIRD` from types `FIRST` and `SECOND` then I do not need to explicitly specify all the types contained in `FIRST` and `SECOND`. (p.s. I saw something about implicit arguments in the documentation but I wasn't sure if it was what I was looking for) : 

```
signature FIRST =
sig
  type 'a first_type1
  type 'b first_type2
  type 'c first_type3
  type 'd first_type4
  type 'e first_type5
end

signature SECOND =
sig
  type 'a second_type1
  type 'b second_type2
  type 'c second_type3
  type 'd second_type4
  type 'e second_type5
end

signature THIRD =
sig
  type 'a third_type1
  type 'b third_type2
  type 'c third_type3
end

functor createThird(
  structure f:FIRST;
  structure s:SECOND) : THIRD =
struct
  type 'a third_type1 = 'a f.first_type1
  type 'b third_type2 = 'b s.second_type1
  type 'c third_type3 = 'c f.first_type5
end

structure structFIRST : FIRST =
struct
  type 'a first_type1 = int
  type 'a first_type2 = bool
  type 'a first_type3 = bool
  type 'a first_type4 = bool
  type 'a first_type5 = bool
end 

structure structSECOND : SECOND =
struct
  type 'a second_type1 = real
  type 'a second_type2 = bool
  type 'a second_type3 = bool
  type 'a second_type4 = bool
  type 'a second_type5 = bool
end 

structure structTHIRD: THIRD =
  createThird(structure f = structFIRST
              structure s = structSECOND)

fun main() = ()
```

**Comment by artella-coding** [comment]
@catalin-hritcu @nikswamy For example in fstar one can do : 

```
module Test

type myfirst 'a1 'b1 'c1 = {fst1:'a1; snd1:'b1; third1:'c1}
type mysecond 'a2 'b2 'c2 = {fst2:'a2; snd2:'b2; third2:'c2}
type mythird 'd1 'd2 = {dfst:'d1; dsnd:'d2}

val createMythird : (myfirst 'a1 'b1 'c1) -> (mysecond 'a2 'b2 'c2) -> (mythird 'a1 'b2)
let createMythird x y = {dfst=x.fst1; dsnd=y.snd2}
```

but in `createMythird` we need to specify all the constituent types of `myfirst` (namely `a1`,`b1`,`c1`) and `mysecond` (namely `a2`,`b2`,`c2`), whereas in the SML functor `createThird` we do not need to do this.
