### ISSUE TITLE
"Double Dijkstra monads" seem to be no longer used

### ISSUE THREAD

**Issue by shiatsumat** [FStarLang/FStar#2113]
[The online tutorial](https://www.fstar-lang.org/tutorial/) says that F\* uses "double Dijkstra monads", tracking both the weakest precondition and the weakest liberal precondition.
However, looking at source code such as `ulib/prims.fst`, I suppose that F\* does not use double Dijkstra monads any longer.
Shouldn't the document be fixed?

**Comment by nikswamy** [comment]
Thanks, yes indeed. This part of the tutorial is stale. Thanks for reporting

**Comment by k4rtik** [comment]
Thanks for pointing this out, I was in the middle of reading that section of the tutorial. It seems like weakest liberal preconditions are not used anymore.

I was looking at the code history and found some relevant commits (mainly for my reference):
- Introduces WLPs in the tutorial sec. 9.3: e6c592525fbdb312e74fa13ba11a01bea4bee616
- NewPrims without WLPs: 4673818bf00f871f891b878a860ea87d6a3bbcb5

**Comment by catalin-hritcu** [comment]
PR #2123 tries to quickly remove any mentioning of WLPs in the tutorial, and unless anyone objects I'll merge that soon.
