### ISSUE TITLE
Impossible: Forced tk not present

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#212]
```
module UnexpectedError
  
type foo : (unit -> Tot bool) -> Type = 
  | Test : f:(unit -> Tot bool) -> foo f 

val bar : foo (fun _ -> true) -> unit
let bar t = match t with
  | Test _ -> ()
```

This code fails with
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Impossible: Forced tk not present (bug.fst(6,24-6,28))
```

**Comment by nikswamy** [comment]
thanks for the report ... this is related to my most recent commits, obviously. Working on it now

**Comment by nikswamy** [comment]
Yes, indeed. This is an issue at least as far back as e9efcadf4ef041d237d7907db16fa21e01619250

**Comment by nikswamy** [comment]
Just pushed a fix ... but it's not an optimal one. You may not get all the equations you expect on implicitly bound function-typed values. In this case, the implicitly bound function appears in the discriminator `isTest #(fun x -> true) t` 

Closing it for now ... but may have to reopen in the future.
