### ISSUE TITLE
"Unbound module Prims" for exported ocaml code

### ISSUE THREAD

**Issue by farao** [FStarLang/FStar#2127]
I'm using F* 0.9.7.0-alpha1 on an up to date Arch linux and OCaml 4.07.1 via opam. I compiled the Ex01a.fst from the F* tutorial to OCaml via `fstar.exe --codegen OCaml Ex01a.fst` and it appears to be succesful:
```
Extracted module Ex01a
Verified module: Ex01a (1401 milliseconds)
All verification conditions discharged successfully
```
Unfortunately, when I try to compile the ocaml code using `ocamlopt Ex01a.ml`, I get `Error: Unbound module Prims` - and indeed, none of the generated files defines a module `Prims` (which is in the fstar standard library but did apparently not get exported?)

Here the names of the generated files:
```
Ex01a.fst           FStar_Calc.ml  FStar_List_Tot_Base.ml        FStar_Math_Lib.ml           FStar_PredicateExtensionality.ml      FStar_Seq.ml                   FStar_TSet.ml    FStar_UInt.ml
Ex01a.ml            FStar_Exn.ml   FStar_List_Tot.ml             FStar_Mul.ml                FStar_Preorder.ml                     FStar_Seq_Properties.ml        FStar_UInt32.ml
FStar_All.ml        FStar_Heap.ml  FStar_List_Tot_Properties.ml  FStar_Pervasives.ml         FStar_PropositionalExtensionality.ml  FStar_ST.ml                    FStar_UInt64.ml
FStar_BitVector.ml  FStar_IO.ml    FStar_Math_Lemmas.ml          FStar_Pervasives_Native.ml  FStar_Seq_Base.ml                     FStar_StrongExcludedMiddle.ml  FStar_UInt8.ml
```

**Comment by k4rtik** [comment]
You may need to build and link the support library as documented at https://github.com/FStarLang/FStar/wiki/Executing-F%2A-code, if you haven't already done it before.

**Comment by farao** [comment]
Thanks for the pointer!
