### ISSUE TITLE
Unexpected result when passing a function as argument 

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#2130]
Hello,

I've encounter a strange behavior when passing a function as argument.

```
module Test

val fold_left: l:list 'a -> acc:'b -> f:(x:'a {x << l} -> 'b -> 'b) -> 'b
let rec fold_left l acc f = match l with
  | [] -> acc
  | t::q -> fold_left q (f t acc) f

type ind_type =
  | A : ind_type
  | B : ind_type
  | C : list ind_type -> ind_type

val test : t:ind_type -> int -> Tot int (decreases t)
let rec test t acc = match t with
  | A -> acc
  | B -> acc + 1
  | C args -> fold_left args acc (fun t' acc' -> test t' acc')

val test2 : t:ind_type -> int -> Tot int (decreases t)
let rec test2 t acc = match t with
  | A -> acc
  | B -> acc + 1
  | C args -> fold_left args acc test2
```

Both functions test and test2 behave similarly and return the same result. The only difference is the function passed to `fold_left`, i.e. `(fun t' acc' -> test t' acc')` versus just calling `test2`.

To my surprise, the function `test` can be type checked but not the function `test2`. It gives the following error:
```
test.fst(23,33-23,38): (Error 19) Could not prove termination of this recursive call; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel (see also test.fst(20,22-23,38))
```

 If it's not a bug, what is the reason behind the difference of type checking ?

Thanks a lot !

Best,
Vincent

**Comment by VincentCheval** [comment]
Hello,

I have a follow-up question. Why the following `assert` fails ?

```
let test_assert t acc = match t with
  | A -> ()
  | B -> ()
  | C args -> assert((test t acc) = fold_left args acc (fun t' acc' -> test t' acc'))
```

I came up with this  while trying to prove some Lemma. Intuitively, I was trying to prove that lemma of the form 
`Lemma (f (test t acc) <==> phi)` where `f` returns a boolean and `phi` is also some code that returns a boolean.

The proof was done by case analysis on `t` and in the case `C args`, I was able obtain that the assertion `assert(f (fold_left args acc (fun t' acc' -> test t' acc'))) <==> phi))` holds. However when I followup this assertion with the assertion `assert (f (test t acc) <==> phi)` then the second assertion fails. I'm wondering why it is the case.

**Comment by aseemr** [comment]
Also cc @nikswamy and @mtzguido.

**Comment by aseemr** [comment]
The assertion failure in your second question is an impreciseness in the smtencoding. But we can prove it with some normalization:

```
let test_assert t acc = match t with
  | A -> ()
  | B -> ()
  | C args ->
    assert ((test (C args) acc) == fold_left args acc (fun t' acc' -> test t' acc'))
      by (T.norm [zeta; iota; delta_only [`%test]])
```

**Comment by VincentCheval** [comment]
Hello again,

@aseemr I tried running your code but I obtained the following error:

```
test.fst(31,12-31,16): (Error 72) Identifier not found: [T.norm]
Module T does not belong to the list of modules in scope, namely FStar.Tactics.Effect, FStar.Tactics.Result, FStar.Tactics.Types, FStar.Reflection.Types, FStar.Tactics.Common, FStar.Range, FStar.Pervasives, FStar.Pervasives.Native, Prims
```

With module should I open to access the function `T.norm` ?

**Comment by nikswamy** [comment]
```
module T = FStar.Tactics
```

**Comment by VincentCheval** [comment]
Thanks a lot !

**Comment by VincentCheval** [comment]
Hello,

I manage to work out some of my proofs but I'm still struggling to understand how the normalization works. For example, I'm trying to prove the following:

```
val for_all: l:list 'a -> f:(x:'a{x<<l} -> bool) -> bool
let rec for_all l f = match l with
  | [] -> true
  | t::q -> f t && for_all q f

assume val p : 'a -> bool

val lemma_test : x:'a -> l:list 'a -> Lemma
  (ensures (for_all (x::l) p ==> for_all l p))
```

I have tried several things but none of it works:

```
let lemma_test x l =
  assert ((for_all (x::l) p == true) <==> (for_all l p && p x) == true)
    by (T.norm [zeta; iota; delta_only ["Test.for_all"]])
```
and 
```
let lemma_test x l =
  assert (for_all (x::l) p == (for_all l p && p x))
    by (T.norm [zeta; iota; delta_only ["Test.for_all"]])
```
yield the same error `test.fst(46,2-47,57): (Error 19) Could not prove goal #1 `.

Of course the basic `let lemma_test x l = ()` yields `test.fst(45,21-45,23): (Error 19) could not prove post-condition;`

Finally I tried with `normalize_term` as follows:
```
let lemma_test x l =
  assert (normalize_term (for_all (x::l) p) == (p x && for_all l p))
```
but I also raises and error `test.fst(46,9-46,68): (Error 19) assertion failed;`.

Any hints ?

Thanks !
Best,

Vincent

**Comment by VincentCheval** [comment]
Hello,

I may have isolated the problem from my previous example but I still don't understand why it does not work. If I write a lemma where the predicate is an argument of the lemma then it works. The following type-check.

```
val lemma_for_all : x:'a -> l:list 'a -> f:('a -> bool) -> Lemma
  (ensures (for_all (x::l) f ==> f x && for_all l f))
let lemma_for_all x l f =
  if for_all (x::l) f
  then ()
  else ()
```

But if I write the same lemma with the predicate 'outside' then it does not work, which is strange. The following does not type-check.

```
val p : #a:Type -> a -> bool
let p x = true

val lemma_test : x:'a -> l:list 'a -> Lemma
  (ensures (for_all (x::l) p ==> p x && for_all l p))
let lemma_test x l =
  if for_all (x::l) p
  then ()
  else ()
```

I also tried calling `lemma_for_all` in the proof of `lemma_test` but that does not solve the problem.
```
val lemma_test : x:'a -> l:list 'a -> Lemma
  (ensures (for_all (x::l) p ==> p x && for_all l p))
let lemma_test x l =
  lemma_for_all x l p;
  if for_all (x::l) p
  then ()
  else ()
```
and 
```
val lemma_test : x:'a -> l:list 'a -> Lemma
  (ensures (for_all (x::l) p ==> p x && for_all l p))
let lemma_test x l =
  if for_all (x::l) p
  then lemma_for_all x l p
  else ()
```
Both of them do not type-check.

It's really confusing to be honest. Can it be a bug ? 

Thanks in advance for your help.
Best,
Vincent

**Comment by VincentCheval** [comment]
Got a reply on Stack:

```
val lemma_for_all2: #a:Type -> y:a -> l:list a -> Lemma
  (ensures (for_all (y::l) (p #a) ==> p y && for_all l (p #a)))
let lemma_for_all2 (y:'a) (l:list 'a) = ()
```

Thanks 😊
