### ISSUE TITLE
Mismatch of types between FStar.Char.fsti and FStar_Char.ml

### ISSUE THREAD

**Issue by bichhawat** [FStarLang/FStar#2131]
We get the following error:
`Error: This expression has type FStar_String.char = int
       but an expression was expected of type FStar_UInt32.t = Stdint.uint32`
when performing FStar_UInt32.lte on arguments of type (FStar_Char.u32_of_char x) in OCaml extracted code. 
It looks like FStar.Char.fsti defines char_code as UInt32 while FStar_Char.ml defines it as int.

**Comment by mtzguido** [comment]
Thanks for reporting, I'm pushing a fix to master soon.

**Comment by mtzguido** [comment]
It should work now, thanks again for the report! :)
