### ISSUE TITLE
Linux/Mac != Mono

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#214]
We now have a lot of code like this in our `Makefiles`:
```
ifeq ($(OS),Windows_NT)
RUNTIME =
else
RUNTIME = mono
endif

blah:
	$(RUNTIME) ../../bin/fstar.exe ...
```
So the current global assumption is that non-windows users will always use the Mono version of F*. This assumption is of course not always true, and to make things worse `make test` now does this:
```
	cp ocaml-output/fstarml.exe ../bin/fstar.exe
```
which violates the current global assumption and makes every other make target fail afterwards (not just `make test` itself).

First, do we really want this behavior from `make test`? It's not what I would expect given a Makefile target with this name.

Second, and more importantly, how do we get rid of this obsolete global assumption? On my machine (Arch Linux) I don't even need the `mono` prefix for running Mono executables, but it seems it's needed at least on Macs (http://www.mono-project.com/archived/guiderunning_mono_applications/#registering-exe-as-non-native-binaries-linux-only). How about this for a fix: when we compile using Mono we rename the binary to something else, say `fstarmono.exe`, and then add a little script called `fstar.exe` with the following contents:
```
#!/bin/bash
mono fstarmono.exe "$@"
```
Can a Mac user try this out and make sure this also works on Mac?
Does anyone have a better solution for this? Otherwise, I'll implement the solution above.

**Comment by ad-l** [comment]
This is not even required. I think it is possible to directly invoke fstar.exe regardless of whether it's bootstrapped or not, on any platform.

**Comment by catalin-hritcu** [comment]
Can Mac and Linux (other distros) users that they can run Mono binaries directly just because they have the `.exe` extension? The official documentation says that this is not the case, but maybe they are wrong: http://www.mono-project.com/archived/guiderunning_mono_applications/#registering-exe-as-non-native-binaries-linux-only

**Comment by catalin-hritcu** [comment]
The documentation page I've linked seems outdated, but the new one says basically the same:
http://www.mono-project.com/docs/getting-started/application-deployment/#layout-recommendation
> Although Linux supports a mechanism to load .NET programs directly, the problem is that this solution is not portable to other Unix systems (BSD, Solaris, MacOS).
It actually recommends the solution I wrote above.

**Comment by ad-l** [comment]
Your proposal isn't cross platform either (doesn't work on non-Cygwin Windows). I'd stay the "other Unix users" should know better. Or, you can name the bash script "fstar" (which invokes fstar.exe) and invoke fstar with just "fstar" which should work on all platforms (at least for the non-bootstrapped version)

**Comment by catalin-hritcu** [comment]
I'm not attached at all to the `.exe` extension, sure this would work for me.

**Comment by aseemr** [comment]
-- Replacing fstar.exe with fstarml.exe as part of Makefile is a bit confusing. For me (on mac), 'make test' fails since bootstrapping replaces fstar.exe with ML version, which then mono cannot run. Instead we can make fstar binary name a variable in Makefiles (two of them: one in src and one in examples/), and to run the tests with OCaml binary, override the variable with fstarml.exe on command line.

-- The script Catalin mentioned in first email works for me on mac (and I cannot run fstar.exe directly without mono).

**Comment by beurdouche** [comment]
I confirm that `make test` fails on mac because of this issue..

```
cp ocaml-output/fstarml.exe ../bin/fstar.exe || cp ocaml-output/fstarml ../bin/fstar.exe
cp: ocaml-output/fstarml.exe: No such file or directory
make -C ../examples
make -C bug-reports
mono ../../bin/fstar.exe  ../../lib/list.fst ../../lib/string.fst ../../lib/partialmap.fst ../../lib/st.fst bug22.fst bug19.fst bug29.fst bug26.fst bug15.fst bug25.fst bug24.fst bug28.fst bug52.fst bug23.fst bug21.fst bug96.fst bug77.fst bug92.fst bug62.fst bug67.fst bug56.fst bug103.fst bug60.fst bug97b.fst bug101.fst bug111.fst bug116.fst bug117.fst bug122.fst bug148.fst bug161.fst bug162.fst bug170.fst bug175.fst bug178.fst bug179.fst bug186.fst bug189.fst bug190.fst bug192.fst bug195.fst bug212.fst bugWildcardTelescopes.fst
Cannot open assembly '../../bin/fstar.exe': File does not contain a valid CIL image.
make[2]: *** [.all.ver] Error 2
make[1]: *** [all] Error 2
make: *** [test] Error 2
bbeurdouche@MBBP:/opt/fstar/
```

**Comment by catalin-hritcu** [comment]
I've fixed this by turning (the mono variant of) fstar.exe into a script that calls the real binary using `mono` and by removing the `RUNTIME` variable everywhere.

**Comment by nikswamy** [comment]
phew
