### ISSUE TITLE
Mysterious error message: "post-condition at"

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#216]
```
../../bin/fstar.exe  constr.fst classical.fst ext.fst set.fsi heap.fst st.fst all.fst --admit_fsi Set lambda_omega.fst --max_fuel 1 --max_ifuel 1 --initial_fuel 1 --log_types
...
val LambdaOmega.esubst_beta : (exp -> exp -> Tot exp)
let esubst_beta : (exp -> exp -> Tot exp)
...
let preservation : (hs:(step e e') -> ht:(typing g e t) -> Tot (typing g e' t) (decreases ht))
lambda_omega_reduced.fst(107,0-111,4): post-condition at lambda_omega_reduced.fst(64,26-64,66)
```
`preservation` is just the end of the `--log_types` output and has nothing to do with the problem. The error doesn't really say what's up with this "post-condition at" and disappears if I add a(n otherwise unnecessary) type annotation for `esubst_beta`
```
val esubst_beta : exp -> exp -> Tot exp
```
Very mysterious. No clue what this is about.

**Comment by vkanne-msft** [comment]
@catalin-hritcu can you kindly help verify this ?

**Comment by catalin-hritcu** [comment]
This problem seems to no longer occur with universes.
