### ISSUE TITLE
Tactic language

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#217]
Devising an [Mtac](http://plv.mpi-sws.org/mtac/)-like tactic language keeps appearing in discussions, so let's have an issue for it. I think it would be really cool if we could do this easily given the infrastructure we already have in place for effects. Still, my impression is that SMT automation using **local** hints like the `using` keyword (#51) will be easier to get and easier to use when it works, and Mtac-like tactics should anyway be plan B, when SMT automation fails.

For a start Nikhil plans to add a `reduce` keyword to explicitly trigger computation in the type-checker.

It's still unclear how/whether we will support syntactic matching as an effect, but it seems like a required feature for a tactic language.

PS: Beta and some people in Paris are apparently working on Mtac 2, but so far there is nothing published on that.

**Comment by catalin-hritcu** [comment]
@david-christiansen is working on a tactic language for Idris. He expects to have something more polished in the next months. There is already some documentation online: http://docs.idris-lang.org/en/latest/reference/elaborator-reflection.html but he said his upcoming PhD thesis will have more about this.

**Comment by catalin-hritcu** [comment]
Elaborator Reflection: Extending Idris in Idris. David Christiansen and Edwin Brady.
http://davidchristiansen.dk/drafts/elab-reflection-draft.pdf

**Comment by catalin-hritcu** [comment]
Was discussing today a bit with @victor-dumitrescu about the primitive effects we would need to add to F* to do meta-programming, and it seemed that that we would need is:
- Syntax introspection effect: a way to turn F* expressions into their deep embedding in F* (Mtac seems to have a variant of this for matching on the syntax of expressions)
- Syntax generation effect: a way to turn a deeply embedded F* expression into a real F* expression
This also reminds me of Lightweight Modular Staging in Scala:
https://scala-lms.github.io

Anyway, just wanted to save these thoughts for later thinking and reading :)

**Comment by catalin-hritcu** [comment]
Another interesting point in this space is William J. Bowman's (@wilbowma) cur language, which uses Racket's wonderful macro system to implement a whole proof assistant for CIC:
https://www.williamjbowman.com/resources/cur.pdf
https://github.com/wilbowma/cur

**Comment by catalin-hritcu** [comment]
We now have a design document based on Lean's design:
https://github.com/FStarLang/FStar/wiki/F%2A-tactics

**Comment by catalin-hritcu** [comment]
@nikswamy @tahina-pro @victor-dumitrescu are working on this.

**Comment by nikswamy** [comment]
See Meta-F*. @mtzguido 

Closing.
