### ISSUE TITLE
Typechecker result caching (per file)

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#218]
This was almost ready up to some bugs [a long time ago](https://github.com/FStarLang/FStar/issues/98#issuecomment-74704368). In the absence of proof obligation caching (#130), it would be really cool to use this to scale up to large proofs that take a long time to check, by splitting the file with the proof in two: the stable part and the unstable part, and only rarely change the stable part.

@aseemr How hard would it be to make this feature available to us soon? We don't really care if it works on all examples, it just needs to work on ours :)

**Comment by nikswamy** [comment]
There's a flag called "--verify_module" that approximates this a bit.

If you do `fstar a.fst.b.fst --verify_module B` it will only check the proof obligations from `B` discarding the rest.

**Comment by catalin-hritcu** [comment]
Very nice, with this we don't even need to break things into files. The only problem is that this only saves time on the SMT solver, and we also have a lot of time spent in the type checker. I've just tried this on `tinyfstar-new.fst` which currently contains almost no proofs, still it takes ~14s to check on my machine. This trick saves ~3.5s (probably mostly on termination checks), still taking ~10.5s.

**Comment by nikswamy** [comment]
Agreed... proper caching will be great to have. We should revisit that mysterious bug we were hitting a while ago.

**Comment by nikswamy** [comment]
The other way to do this is to keep an F* process running and feed new modules to it incrementally on stdin. We need this eventually for an IDE anyway.

**Comment by catalin-hritcu** [comment]
I was also thinking today about a top level and then ProofGeneral for F* :)

**Comment by catalin-hritcu** [comment]
@aseemr working again on caching:
https://github.com/FStarLang/FStar/tree/aseem_serialization_experiment

**Comment by mtzguido** [comment]
We now have a `--cache_checked_modules` flag.
