### ISSUE TITLE
Can't find a working FStar Crypto example

### ISSUE THREAD

**Issue by KristianOstrup** [FStarLang/FStar#2180]
Hello,
I am trying to create a simple FStar example using ECDH and noticed an implementation of ECDH in CoreCrypto fsti/ml. I therefore tried to make \examples\crypto but it seems to be outdated as it produces a lot of errors straight from the branch.
I have read CoreCrypto is sourced to the MLCrypto repos but I can't find any examples similar to the one above. Is there anywhere I can find similar and maintained FStar crypto examples to get me started (preferable with a ECDH implementation)?

Best regards,
Kristian

**Comment by nikswamy** [comment]
You might have more luck asking this question on https://github.com/project-everest/hacl-star

**Comment by nikswamy** [comment]
For the record, `make -C examples/crypto all` is part of our CI and continues to work, but it does not provide anything related to ECDH.
