### ISSUE TITLE
Print the proof context and the proof goal

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#219]
It would greatly help proving to have a way to print the types of all the binders in the local scope, and to be able to admit a goal while also printing the type that was inferred for it; like `magic()`/`admit()` on steroids.

**Comment by catalin-hritcu** [comment]
Also see the `printType e` idea in https://github.com/FStarLang/FStar/issues/27#issuecomment-77545198

**Comment by catalin-hritcu** [comment]
Omar Montano Rivas recently asked on fstar-club whether we could have a way to print the context at the place a proof fails.

@victor-dumitrescu @tahina-pro Were you looking at printing contexts earlier this year?

**Comment by mtzguido** [comment]
Should we consider this done by the introduction of tactics?

**Comment by catalin-hritcu** [comment]
@mtzguido It seems to me it's still a bit clunky to integrate tactics this way without adding extra type or formula annotations. The simplest thing I can think of is:
```
let foo (x y : int) =
  assert_by_tactic True (dump "print_goal"); admit()
```
So would a solution be to just add an alias `print_goal` for `assert_by_tactic True (dump "print_goal")`, but I don't really know how to do this without the print triggering already in the definition of `print_goal`.

**Comment by mtzguido** [comment]
Yeah, this isn't friendly at all. One way around that problem you mention is this:

```
let dump_admit a : tactic unit =
  dump1 "ctx";;
  g <-- cur_goal;
  gg <-- unquote #Type g;
  exact (quote #gg (magic ()))

assume val print_goal : #a:Type -> unit ->
    Pure a (requires (by_tactic (dump_admit a) a))
           (ensures (fun _ -> True))

val l : x:int -> y:int -> squash (x + y == y + x)
let l x y = print_goal ()
```

Then you get
```
TAC>> Current goal (ctx):
TAC>> (x:Prims.int), (y:Prims.int), (b:Prims.unit) |- (*?u19*) _ x y b : Prims.squash (x + y == y + x)
```

But if you switch the `squash` to a `Lemma`...
```
TAC>> Current goal (ctx):
TAC>> (x:Prims.int), (y:Prims.int), (p:Prims.pure_post Prims.unit), (uu___531373:Prims.squash (forall (x:Prims.unit). x + y == y + x ==> p x)), (b:Prims.unit) |- (*?u11*) _ x y p uu___531373 b : Prims.unit
```
you get a bogus goal (just `unit`) and you see all of the VC binders too (maybe desirable?).

**Comment by catalin-hritcu** [comment]
@mtzguido Your solution looks good enough for me. Please add to the library, maybe renamed to `admit_goal` so that it's clearer that this is an unsafe feature (maybe one day we'll also solve #81 though).

**Comment by mtzguido** [comment]
Added, with two changes

1) I changed the ensures to `fun _ -> False`, otherwise we were not actually admitting the Lemma VC.
2) Called `clear_top` to get rid of that extra unit binder.

going to master soon

**Comment by mtzguido** [comment]
Now in master (in `FStar.Tactics.Derived`), but I'll keep this open since I think we need a better solution.

**Comment by mtzguido** [comment]
I'm about to add something better implemented via meta-args. `admit_dump` and `magic_dump` should behave exactly like `admit` and `magic`, but printing a warning. I'll close this when I merge to master. Here's how they're defined:
```
val admit_dump : #a:Type -> (#[tadmit_t (quote (fun () -> admit #a () <: Admit a))] x : (unit -> Admit a)) -> unit -> Admit a
let admit_dump #a #x () = x ()
 
val magic_dump : #a:Type -> (#[tadmit_t (quote (magic #a ()))] x : a) -> unit -> Tot a
let magic_dump #a #x () = x
```

**Comment by nikswamy** [comment]
@mtzguido  ... ping.

**Comment by mtzguido** [comment]
Seems like I just forgot to close this. Already in master, but pushing a few tweaks soon.
