### ISSUE TITLE
Using an action from the wrong effect makes verification fail with the message "Failed to find d@0 Env is"

### ISSUE THREAD

**Issue by semitangential** [FStarLang/FStar#2190]
**Summary:**
Creating an effect as a specialization of another effect, and using actions from the more general effect in a function with the more specific effect yields the following message:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Failed to find d@0\nEnv is \n")
```

**Environment:**
Reproducible with:
* The online F* editor (https://www.fstar-lang.org/run.php)
* F* commit `a7373564d99663b6621f2b059cf5630ef57abfcc` and `Z3 version 4.8.5 - 64 bit`

**Steps to reproduce:**

1. In a file or in the online F* editor, enter the following:
```
module Bug.Minimal

let state (d: Type) (a: Type) = (list d) -> M (a * (list d))

val return_state: (d: Type) -> (a: Type) -> (x: a) -> state d a
let return_state d a x = fun d0 -> (x, d0)

val bind_state: (d: Type) -> (a: Type) -> (b: Type) -> (f: state d a) -> (g: a -> state d b) -> state d b
let bind_state d a b f g = fun d0 ->
  let (x, d1) = f d0 in
  let (y, d2) = g x d1 in
  (y, d2)

val getNone: (d: Type) -> (d -> bool) -> state d unit
let getNone (d: Type) (p: d -> bool): state d unit = fun d0 -> (), d0

total reifiable reflectable new_effect {
  STATE_GENERAL (d: Type): (a: Type) -> Effect
  with repr    = state d
     ; bind    = bind_state d
     ; return  = return_state d
     ; getNone = getNone d
}

total reifiable reflectable new_effect STATE_INT = STATE_GENERAL int

effect ST (a:Type) (pre: STATE_INT?.pre) (post: list int -> a -> list int -> Type0) =
        STATE_INT a (fun d0 p -> (pre d0) /\ (forall (x:a) d1. post d0 x d1 ==> p (x, d1)))

val works: p: (int -> bool) -> ST unit (fun _ -> True) (fun _ _ _ -> True)
let works p = let _ = STATE_INT?.getNone p in ()

val triggersBug: p: (int -> bool) -> ST unit (fun _ -> True) (fun _ _ _ -> True)
let triggersBug p = let _ = STATE_GENERAL?.getNone p in ()
```
2. Run F* to verify the file/code.

**Expected result:** An error message saying something about `STATE_GENERAL?.getNone` not being valid for use in `triggersBug`.

**Observed result:** The following is printed:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Failed to find d@0\nEnv is \n")
```
Removing the function `triggersBug` makes the verification go through.

**Comment by aseemr** [comment]
We have deprecated support for DM4Free effects, instead the recommended way to define new effects in F* is to use layered effects. See `ulib/experimental/FStar.MSTTotal.fst` for a state effect that you may be able to use as is for the example above. Please let us know if you see any issues.
