### ISSUE TITLE
Prove termination of inductive type including other inductive types

### ISSUE THREAD

**Issue by nuaaysh** [FStarLang/FStar#2201]
Hello,
I find F* can not prove the termination of one kind of inductive type elegantly:

```fsharp
type tlist =
  | Base: nat -> tlist
  | Llist: list tlist -> tlist

val size_tlist_fail: tl:tlist -> Tot nat (decreases %[tl])
let rec size_tlist_fail tl =
  match tl with
  | Base _ -> 1
  | Llist l -> 
    match l with
    | [] -> 0
    | hd:: tl -> size_tlist_fail hd  + size_tlist_fail (Llist tl)
```
where `size_tlist_fail (Llist tl)` satisfies `Llist tl <<` `old (tl)` of `size_tlist_fail tl`.

However, F* says: Could not prove termination of this recursive call; The SMT ....

Currently, I only find one solution:
```fsharp
...
type tlists = list tlist

val size_tlist_ok: tl:tlist -> Tot nat (decreases %[tl])
let rec size_tlist_ok tl =
  match tl with
  | Base _ -> 1
  | Llist l -> size_tlists l
and size_tlists (l:tlists) : Tot nat (decreases %[l]) =
  match l with
  | [] -> 0
  | hd :: tl -> let tn = size_tlist_ok hd in
    tn + size_tlists tl
```

So my question is: Can F* support some notations like `decreases %[tl; tl?Llist]` or `type tlist (decreases %[Llist]) =` in order to make the recursion function like `size_tlist_fail` can be accepted by z3?  Or maybe F* already supports some features to solve it?

**Comment by nuaaysh** [comment]
However, the only solution (mutually inductive types) bears the known bug #2193 . That is,


if A.fst defines a mutually inductive type, and if you declare `open A` in B.fst, then you get the same bug #2193 


I am trying the solution https://github.com/FStarLang/FStar/pull/2200/files?file-filters%5B%5D=.fs&file-filters%5B%5D=.fst&file-filters%5B%5D=No+extension#

**Comment by W95Psp** [comment]
Hi,

> Or maybe F* already supports some features to solve it?

You can provide your function `size_tlist_fail` a custom measure for your type `tlist` (that is, a total function from `tlist` to, for instance, `nat`), so that F* is able to reason about decreasing `tlist`s. For example:

```fstar
type tlist =
  | Base: nat -> tlist
  | Llist: list tlist -> tlist

let rec lex (tlst: tlist): nat =
  match tlst with
  | Base n -> 0
  | Llist l -> 1 + lex_helper l
and lex_helper (l: list tlist): nat
  = match l with
  | [] -> 0
  | hd::tl -> 1 + lex hd + lex_helper tl

val size_tlist_fail: tl:tlist -> Tot nat (decreases (lex tl))
let rec size_tlist_fail tl =
  match tl with
  | Base _ -> 1
  | Llist l -> 
    match l with
    | [] -> 0
    | hd:: tl -> size_tlist_fail hd  + size_tlist_fail (Llist tl)
```

**Comment by nuaaysh** [comment]
Thanks, my colleague :-) @W95Psp 
    
So, now we need an auxiliary function (e.g. `aux`) with the mutually inductive type to tell FStar how to do `descreases aux`. (because FStar is not so smart)

But if we use the mutually inductive type within the target function, like `size_tlist_ok`, the bug #2193 will appear.

**Comment by aseemr** [comment]
I don't see any other way to do this. There are essentially two inductions involved, one on `tlist` and one on `list`. And since F* does not automatically set up the induction, you have to specify both. Now whether you do it "inline" as @nuaaysh did or as a separate function as @W95Psp did, is a matter of choice and whether the induction principle needs to be applied multiple times.

I am closing the issue (#2193 is already being tracked separately), please reopen if needed. Thanks!
