### ISSUE TITLE
Unexpected unresolved (universe) uvar in deep_compress

### ISSUE THREAD

**Issue by denismerigoux** [FStarLang/FStar#2224]
Minimal working example:

`Mod1.fst`:

```fstar
module Mod1

let rec foo (e: int) : Tot (int) (decreases %[ e; 0 ]) = e
and bar (e: int) : Tot (int) (decreases %[ e; 1 ]) = e
```

`Mod2.fst`:

```fstar
module Mod2

open Mod1
```

Typechecking `Mod1.fst` succeeds. When lax-typechecking `Mod2.fst`, I get the following error message:

```
(Error 339) Error while computing or loading dependencies:
Internal error: unexpected unresolved (universe) uvar in deep_compress
```

Any idea how to fix or get past it?

**Comment by aseemr** [comment]
This should be fixed in master now, as part of fixing #2193. Thanks Denis for the report.
