### ISSUE TITLE
Identifier not found: [ParseIt.read_build_config]

### ISSUE THREAD

**Issue by jonleivent** [FStarLang/FStar#223]
I am trying to build F* for the first time, and am getting this error when building the test via:

$ source setenv.sh
$ make test.net -C src

The error is:
parser/driver.fs(59,37-59,54) : Error
Identifier not found: [ParseIt.read_build_config]

This is using git master version 356219b

**Comment by catalin-hritcu** [comment]
I've been getting the same problem since a couple of days. It seems to be the breakage Nik was talking about here: https://github.com/FStarLang/FStar/commit/65fd56c8c8ba4bdb9d585109cc4044fa9bcde4ff#commitcomment-10985298

Going back in time 4 days before these changes with:
```
git checkout e18356e
```
solved it for me. Sorry for the trouble, hope this workaround does it for you for now and we fix this soon.

**Comment by jonleivent** [comment]
On 05/04/2015 03:07 AM, Catalin Hritcu wrote:
> Closed #223 via e215a7634815f35277ac9ac97c44fb0bb3ef5578.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/FStarLang/FStar/issues/223#event-295982922
>

That fixed the issue for test.net, but I still get it for "make ocaml":

jil@lmde:~/git/FStar/src$ make ocaml
mono ../bin/fstar.exe --eager_inference --MLish --lax --fs_typ_app 
--odir ocaml-output  --codegen OCaml --admit_fsi Microsoft.FStar.Util 
--admit_fsi Microsoft.FStar.Platform ../lib/system.fst ../lib/stboot.fst 
../lib/list.fst ../lib/option.fst ../lib/string.fst ../lib/char.fst 
basic/bytes.fst basic/platform.fsi basic/util.fsi basic/getoptsimple.fst 
basic/options.fs basic/range.fst basic/unionfind.fst basic/lazyset.fsi 
basic/lazyset.fs absyn/syntax.fsi absyn/syntax.fs absyn/const.fs 
absyn/visit.fs absyn/util.fs absyn/print.fs absyn/ssyntax.fs 
parser/ast.fs parser/dsenv.fsi parser/dsenv.fs parser/desugar.fsi 
parser/desugar.fs parser/parse.fst parser/lexhelp.fs parser/parseit.fst 
parser/driver.fs tc/tcenv.fsi tc/tcenv.fs tc/recheck.fs tc/normalize.fsi 
tc/normalize.fs tc/errors.fs tc/rel.fsi tc/rel.fs tc/tcutil.fsi 
tc/tcutil.fs tc/tc.fs tosmt/term.fsi tosmt/term.fs tosmt/z3.fs 
tosmt/encode.fs format/format.fsi format/formatml.fs backend/nameenv.fsi 
backend/nameenv.fs backend/ocaml-syntax.fs backend/ocaml-asttrans.fsi 
backend/ocaml-asttrans.fs backend/ocaml-codegen.fsi backend/ocaml-codegen.fs
parser/driver.fs(59,37-59,54) : Error
Identifier not found: [ParseIt.read_build_config]
make: *** [ocaml] Error 1

**Comment by catalin-hritcu** [comment]
True, the underlying problem is not really fixed. I was just trying to give you a workaround for make test.net. Reopening until the real problem is fixed.

**Comment by nikswamy** [comment]
fixed.

**Comment by catalin-hritcu** [comment]
I can confirm that this also fixed OCaml bootstrapping on Linux. `make test` still has problems due to #214 though.
