### ISSUE TITLE
Cannot use STATE2 to show trivial property on trivial function

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#225]
I tried to use STATE2 to show a very trivial property on a very trivial program:

```
let bar () = ()
                           
val equiv_test: 
            unit
         -> STATE2.ST2 (unit * unit)
                (requires (fun h -> True))
                (ensures (fun h1 r h2 -> True)) 
let equiv_test () = compose2 bar bar () ()
```

This fails with 
```Unknown assertion failed```

This is unexpected, because the following (more complicated) programm is successfully verified.
```
let bar a = a := 0
                           
val equiv_test: 
            a:ref int
         -> STATE2.ST2 (unit * unit)
                (requires (fun h -> True))
                (ensures (fun h1 r h2 -> True)) 
let equiv_test a = compose2 bar bar a a
```

**Comment by nikswamy** [comment]
This issue and #224 are the same and have to do with a known limitation in the way type inference currently works. I plan to improve it ... but it may take a couple of weeks before I get to it. 

This program type-checks just fine:

```
val bar: x:unit -> STATE unit (fun 'p h -> 'p () h) (fun 'p h -> 'p () h)
let bar () = ()

val equiv_test: 
            unit
         -> STATE2.ST2 (unit * unit)
                (requires (fun h -> True))
                (ensures (fun h1 r h2 -> True)) 
let equiv_test () = compose2 bar bar () ()
```

Without the annotation, when trying to pure an equality between the inferred type of `bar` `(unit -> Tot unit)` and the expected type in `compose2` ... i.e.,  `(x:a -> STATE (b x) (wp x) (wp x))` ... we get a failure, and the default to using subtyping instead. That leaves unresolved unification variables in the VC, which Z3 cannot reason about. 

A temporary fix would be to not default to subtyping when the equality test fails and then we can report a better error message. 

The long-term fix I have in mind is to allow the use of user-provided coercions when solving these equality constraints. But, that's more work.

**Comment by ngrimm** [comment]
This is solved, closing.

**Comment by nikswamy** [comment]
Thanks for checking and closing this. I implemented something a while back to address this and related issues but didn't have the chance to come back and check it out on the examples you have here.
