### ISSUE TITLE
`lookup_typ` on a `val` toplevel throws an exception

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#2257]
Hi,

Inspecting a name that points to a `val` declaration using `lookup_typ`, then matching on it throws an exception: `File "src/ocaml-output/FStar_Reflection_Embeddings.ml", line 1476, characters 4-9: Pattern matching failed`.
I guess

Here is an example:
```
module SigeltVal
open FStar.Tactics

let match_sigelt (n: name) =
  let se = lookup_typ (top_env ()) n in
  match se with | Some _ -> ()
                | None -> ()

val foo: int
let _ = run_tactic (fun _ -> match_sigelt ["SigeltVal";"foo"])
```

PR #2197 introduced the support of `val`s for `lookup_typ`.
I just tried to typecheck the module above with F* compiled at commit 54ddadbdd8aa36b2bbb60b3c0a24fc4bfa3e90ce, and I get the same error.

**Comment by aseemr** [comment]
Thanks for the report @W95Psp , I pushed a fix to master.

**Comment by W95Psp** [comment]
Nice, thanks for fixing the issue that fast! :)
