### ISSUE TITLE
Building F* from source results in segfault

### ISSUE THREAD

**Issue by antoniolocascio** [FStarLang/FStar#2273]
While building F* with the provided Makefile, I got the following error:

```
make[1]: *** [Makefile.verify:51: .cache/Steel.FramingTestSuite.fst.checked] Segmentation fault (core dumped)
```

I'm building on macOS (Intel), at commit `eea0880d54aaa2e140c18975e405fa94f4024c0f`, but don’t know how reproducible this error is. After a few attempts, it built successfully.

Is this a known bug?

**Comment by germanD** [comment]
I can confirm I've the same issue building from sources (at the `make -C ulib/` step) from master, on linux/Ubuntu, with an opam switch based on `ocaml-base-compiler.4.10.2`.

Iterating the build invokation eventually succeeded.

**Comment by nikswamy** [comment]
Thanks for reporting. Can you point me at the directions you were following? I guess it's this one?
https://github.com/FStarLang/FStar/blob/master/INSTALL.md#step-2l-building-the-f-libraries

It looks a little stale to me. Instead for steps 1 and 2 there, you should just be able to run `make` in the root directory and it should do it in the right order for you. Doing it manually as per the current instructions builds the steps in a different order and results in a seg fault, which I've noticed too and have been trying to debug. 

I have updated the instructions here and will soon push those instructions to master. https://github.com/FStarLang/FStar/blob/nik_install/INSTALL.md#building-f-and-its-libraries

It would be great if you could confirm that it works for you.

Thanks!

**Comment by germanD** [comment]
Thanks @nikswamy! Indeed I was following the instructions you pointed to on master without success.
I tried `make -j 4` on the commit @antoniolocascio pointed out and I still get
```
make[1]: *** [Makefile.verify:51: .cache/Steel.FramingTestSuite.fst.checked] Segmentation fault (core dumped)
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/gad/git-repos/related/FStar/ulib'
make: *** [Makefile:10: all] Error 2
```
I will try with master.

**Comment by antoniolocascio** [comment]
Thanks! I tried the new instructions with master and it worked well.

**Comment by germanD** [comment]
Indeed, it works on master for me as well--- after I `git-clean`ed. I suspect there were some leftovers that made my immediately previous attempt fail.

**Comment by nikswamy** [comment]
thanks! I pushed those instructions to master. 

Now to keep digging to find why it segfaults otherwise... it really shouldn't be doing that. Tracking it in #2243
