### ISSUE TITLE
Equality generation for selectors is now quadratic

### ISSUE THREAD

**Issue by R1kM** [FStarLang/FStar#2280]
Steel propagates framing information by generating selector equalities using the `frame_equalities` function.
Until now, we only generated equalities for atomic subresources, that were identified as VUnit nodes. The rationale is that almost all specifications relate to atomic subresources. Furthermore, since lemmas on relating selectors with the underlying separation logic are exposed, but do not have patterns to avoid an SMT context blowup (for instance, that `sel (p * q) h == sel p h, sel q h`), equalities on composite resources are rarely useful because of the AC-commutative rewriting. For instance,
an equality on sel (p * q) does not automatically give the same equality on sel (q * p).

Commit da47c0 instead generates equalities for all subresources, and not just atomic subresources. This is needed to support generic vprops: if p and q are two abstract vprops (for instance, passed as arguments for generic combinators), and we have `p * q` in the context, equalities on p and q are not generated: Since p and q are neither VUnit nor VStar nodes, normalization gets stuck when calling frame_equalities on the subresources p and q.

Generating equalities for all subresources is intended as a temporary workaround. A better solution would be to recursively call frame_equalities on subresources when we have a VStar node, but always generate an equality when this is not the case, or when normalization fails.

**Comment by tahina-pro** [comment]
Thank you for raising this issue. Yes, so far all my ongoing examples (arrays, EverParse, etc.) currently rely on quadratic `frame_equalities`.
I assume that you mean commit da47c0c6542947d27fecd4db92ffd21339d28fc9 currently in PR #2277 , and that you intend to merge it into `steel` (at least as part of that PR) in the short run.

**Comment by R1kM** [comment]
Yes, correct. I'm fine with keeping it for now with the comment in the file and the issue open, and revisit later. Having more examples and files using this feature should also provide us a testbase to ensure that the future encoding will work as intended.
