### ISSUE TITLE
The Interactive Tutorial web page isn't working

### ISSUE THREAD

**Issue by andybrackley** [FStarLang/FStar#229]
I'm trying to work through the tutorial page here: 
https://www.fstar-lang.org/tutorial/

But, whenever I run the script using the ">" button I get the error:
Cannot open assembly '/var/fstar/bin/fstar.exe': File does not contain a valid CIL image.

Tried on Firefox and Chrome just to make sure it wasn't a browser issue.

**Comment by catalin-hritcu** [comment]
It was a server issue I could also reproduce, and which had to do with some recent changes I made (f985e052 and 53b4acd8). Should be fixed now.
