### ISSUE TITLE
More robust output check for negative unit tests

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#231]
Just counting errors is unreliable (very unreliable without minimal models #45) and wastes precious human cycles. We could write a little script that processes source comments in a very simple format, say:

```
(* BEGIN ERROR: <regexp> *)
... code that should cause error matching regexp... 
(* END ERROR *)
```

and then matches the ranges and error messages in the F\* output against the ranges and regexps of the `ERROR` comments.

WDYT?

**Comment by catalin-hritcu** [comment]
Markulf suggests testing that we check automatically whether our open bugs still fail (https://github.com/FStarLang/FStar/issues/262#issuecomment-131554904). I think this would only make sense once this issue is fixed.

**Comment by beurdouche** [comment]
See also #476

**Comment by beurdouche** [comment]
As mentioned in #476 : 
What about an F* flag like --expect_failure MyNegTestModule1 that would prevent to write on the standard error and display a nice “Verification failed as expected” ?

**Comment by catalin-hritcu** [comment]
@beurdouche This issue is not only about making sure that something fails, but about making sure it fails in the right way / for the right reasons. A lot of old files will just fail for strange reasons because they are no longer maintained, and just an `--expect_failure` flag will not force them to keep maintaining them.

Anyway, will discuss about this issue with Nik again today.

**Comment by catalin-hritcu** [comment]
@tahina-pro Hey Tahina. Was there any progress on this issue? If not, Tomer (@shaolintl) could look at this. Could you in any case remind us what was the design we were planning for this (i.e. what we discussed in Redmond).

**Comment by tahina-pro** [comment]
There has not been much progress on the testing side, so yes, @shaolintl, you are definitely welcome to help on that.

One way we discussed was to incorporate code in the compiler itself to automatically generate test ASTs and expected failures/results at the same time, if I remember well.

**Comment by cpitclaudel** [comment]
Question: if this is for regression testing purpose, why not save the whole expected output to a file and check that it matches exactly? Do you expect a regexp to be significantly less brittle that the full, exact output?

**Comment by cpitclaudel** [comment]
One thing I've been wishing for is unique identifiers for each error -- this would make it easy to document the errors individually.

**Comment by catalin-hritcu** [comment]
> Question: if this is for regression testing purpose, why not save the whole expected output to a file and check that it matches exactly? Do you expect a regexp to be significantly less brittle that the full, exact output?

Yes, significantly less brittle. Say you want some particular assertion to fail in some piece of code, it does matter a lot that it's precisely that assertion that fails, and not some other one.

> One thing I've been wishing for is unique identifiers for each error -- this would make it easy to document the errors individually.

This would indeed be great. We discussed it before and might even be filed somewhere (although I can't find it right now).

**Comment by cpitclaudel** [comment]
> Yes, significantly less brittle. Say you want some particular assertion to fail in some piece of code, it does matter a lot that it's precisely that assertion that fails, and not some other one.

Ah, so your `BEGIN ERROR` blocks can be applied to subparts of a term, too? Neat.
(I'm a but confused though: the full output does identify the exact assertion that fail, doesn't it?)

I was thinking of something like `let a = expected_failure "assertion-failure" assert false; assert true`.

**Comment by catalin-hritcu** [comment]
> I was thinking of something like let a = expected_failure "assertion-failure" assert false; assert true.

I would personally like this over some external tool. @nikswamy @tahina-pro WDYT?

**Comment by mtzguido** [comment]
We have something mid-way now, a top-level `fail` attribute to check that a definition fails, and with a set specific errors. Copying from slack:

>I just added a fail attribute￼￼
>The easy way to use it is like
```
[@fail]
let foo = ...
```
>which will succeed if foo fails to typecheck, and raise an error if not.
>So `[@fail] let x = 1 + 'a'` succeeds.
>When one is interested in the specific error numbers, there's fail_errs which takes a list of error codes.
>It works as `fail` but will further check that the errors in the list are raised in the exact amount they appear.￼￼￼
>This means
```
[@ (fail_errs [19;19])] let foo = ...
```
>will succeed when foo succeeds and raises exactly two instances of error 19, but possibly more error codes too.
> (Maybe we should not allow that last bit though... what do people think?)
> Note that fail is really equivalent to `fail_errs []`.

I'll probably make the list in `fail_errs` exhaustive, forbidding the extra errors mentioned above. Feedback welcome!

**Comment by catalin-hritcu** [comment]
Agreed that error list should be exhaustive, or otherwise the potential presence of extra errors should be marked somehow.

**Comment by mtzguido** [comment]
BTW: https://github.com/FStarLang/FStar/wiki/Failure-attributes. Some points on improving it:

1. For more robust checks, say of the error's text, we could definitely implement that. I think we've just didn't have a real need for it in these past months.

2. As for making the check more "local" (like `let a = expected_failure "assertion-failure" assert false; assert true`), I have no clue how such a thing would work. Would `let a = expected_failure "assertion-failure" assert false; assert false` succeed, proving false? It would unless we discard the postcondition of the failed fragment, which I just don't see flying. Or take for instance `let x = (expected_failure "something" (1 + 'a')) + 2`, what does that mean?

Doing top-level definitions makes all of this easier. We just check that they fail (as expected), and then basically forget about them.

**Comment by mtzguido** [comment]
I would propose we close this: we can use `expect_failure` to do negative unit testing, and if we are interested in the precise range or the text of the error message we can just use makefiles to compare the error output via a regex or simply a complete match. I don't expect too much brittleness there, and having many of those tests would actually help us in not inadvertently breaking ranges (which happens once in a while).

**Comment by catalin-hritcu** [comment]
> if we are interested in the precise range or the text of the error message we can just use makefiles to compare the error output via a regex or simply a complete match

Sounds great, how about we start actually doing it? :)

It's what this issue is proposing, so we can still use it to track progress.

**Comment by mtzguido** [comment]
See #1991.

**Comment by nikswamy** [comment]
Congratulations, Guido! This is a long-standing one with tons of work on your part to solve it. Much appreciated.
