### ISSUE TITLE
Question on syntactic-sugar for combinaison of effects and refined types 

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#232]
Hi, 
For this function `let addition x y = x + y`

Those two variants type-check :
```
    val addition: x:int{x>=0} -> y:int{y>=0} -> Tot int
    val addition: x:int{x>=0} -> y:int{y>=0} -> z:int{z=x+y && z>=0}
```
while this does not because of a syntax error
```
   val addition: x:int{x>=0} -> y:int{y>=0} -> Tot z:int{z=x+y && z>=0}
```
Is that expected ?
Thanks

**Comment by beurdouche** [comment]
Ok, answering my own question, I am just missing the parenthesis..
```
 val addition: x:int{x>=0} -> y:int{y>=0} -> Tot (z:int{z=x+y && z>=0})
```
Does it make sense to provide syntactic sugar for it ?

**Comment by nikswamy** [comment]
I see this as an instance of #83 

I don't think we will change the syntax to accept things like `Tot z:int{blah}`.
