### ISSUE TITLE
Publish last release on opam

### ISSUE THREAD

**Issue by pitag-ha** [FStarLang/FStar#2326]
Is it possible to publish the last release on opam? Or is there something blocking that? I'm asking because it would be great to have a `ppxlib` compatible `fstar` on opam.

**Comment by kit-ty-kate** [comment]
Fixed in https://github.com/ocaml/opam-repository/pull/19020. Though it would be very much appreciated for the devs to do it themselves if they have the time to.

**Comment by pitag-ha** [comment]
Thanks a lot, @kit-ty-kate!
