### ISSUE TITLE
Why do our binaries include ocamlopt and ocamlrun? Are they really needed? Are we legally allowed to redistribute them?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#234]
The `make package` target from the `Makefile` in `src/ocaml-output` includes this:
```
	cp /usr/bin/ocamlopt fstar/bin/ocamlopt || true
	cp /usr/bin/ocamlrun fstar/bin/fsocamlrun || true
```
@ad-l Why are these OCaml binaries sometimes copied in (and sometimes not, since the hardcoded path seems very fragile)? Are they needed for anything?

If they are really needed we would need to think more seriously about licensing issues. OCaml is released under the rather non-standard Q Public License:
https://ocaml.org/docs/license.html
https://en.wikipedia.org/wiki/Q_Public_License

**Comment by avsm** [comment]
Note that it's possible to get OCaml under the BSD license by joining the Caml Consortium; http://caml.inria.fr/consortium/. (Microsoft is already a member)

**Comment by catalin-hritcu** [comment]
@avsm  This is good to know, thanks a lot. My impression is that we don't need to bundle OCaml with our binaries anyway. In fact we just removed them from the latest release.

**Comment by avsm** [comment]
Nope, it shouldn't be necessary.  I'm taking a look at adding an OPAM package for Fstar that'll make it even easier.  Just needs Z3 first (ocaml/opam-repository#3298).

**Comment by catalin-hritcu** [comment]
Having an OPAM package for Fstar would be great, of course. Please let us know when there is something with which we can help.

**Comment by ad-l** [comment]
It is no longer necessary in the current setup.

**Comment by markulf** [comment]
https://github.com/FStarLang/FStar/issues/294

**Comment by markulf** [comment]
Apparently MSR is a member of the Caml Consortium.
