### ISSUE TITLE
Build problems with opam because of z3=4.8.5

### ISSUE THREAD

**Issue by andreasabel** [FStarLang/FStar#2344]
It seems that the latest opam release of fstar is married to z3-4.8.5, but this version has build problems on macOS which are fixed in 4.8.11, see https://github.com/Z3Prover/z3/issues/5437.

Can a new version of fstar be released that works with a more recent z3?
```
$ opam show fstar

<><> fstar: information on all versions <><><><><><><><><><><><><><><><><><><><>
name         fstar
all-versions 0.9.0  0.9.1.1  0.9.2.0  0.9.3.0-beta1  0.9.4.0-beta0  0.9.5.0  0.9.6.0~alpha1  0.9.6.0
             0.9.7.0-alpha1  2021.06.06

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       2021.06.06
...
depends:      "ocaml" {>= "4.04.1" & < "4.13.0"}
              ...
              "z3" {= "4.8.5"}
```
Related: #2330.

**Comment by hacdias** [comment]
cc @nikswamy @aseemr

**Comment by aseemr** [comment]
We have started to investigate migration to the recent Z3 versions. Hoping to have some development to share in a couple of weeks or so. Thanks for highlighting it!

**Comment by xgqt** [comment]
cc @xgqt
Hi! I attempt to package F* for Gentoo and just wanted to comment that I also am looking forward to port to Z3 >= `4.8.11`.

**Comment by R1kM** [comment]
Hi,
The z3 4.8.5 opam package should now be fixed. I could locally build F* from scratch on MacOS using opam.
Closing this issue for now, please feel free to reopen it if this problem is not fixed for you.

**Comment by xgqt** [comment]
> Hi, The z3 4.8.5 opam package should now be fixed. I could locally build F* from scratch on MacOS using opam. Closing this issue for now, please feel free to reopen it if this problem is not fixed for you.

I took a quick look, it still does not seem version 4.8.11 is supported, right?

**Comment by xgqt** [comment]
> Sorry, that's correct. But the opam build using z3 4.8.5 should now work

I shall open a issue to keep track of whether the newest version is supported then, is that ok?

**Comment by R1kM** [comment]
Yep, that's a good idea. Thanks!
