### ISSUE TITLE
defining new Operators fails 

### ISSUE THREAD

**Issue by DemuirGos** [FStarLang/FStar#2346]
```
//  1 - the following passes the compilation
let (=>) (f:'a->'b) (g:'b->'c) (x:'a) = g (f x)
// 2 - the following does not pass the compilation
let (|>)  (f:'a->'b) (g:'b->'c) (x:'a) = g (f x)
```
the second definition gives a parsing error "(Error 168) Syntax error: Parsing.Parse_error  1 error was reported (see above)", I suspect it has to do with the char '|'.

**Comment by aseemr** [comment]
You are right, `(| ... |)` is F* syntax for dependent tuple values, and so this is a parsing error.

However, you can add a space `let ( |> ) ...` and then it should work. In fact, we already have a definition of this symbol for the `ML` effect in `FStar.All` (https://github.com/FStarLang/FStar/blob/master/ulib/FStar.All.fst#L39), you can similarly re-define it for `Tot` effect.

Closing it, please reopen or file other issues as you see fit, thanks!
