### ISSUE TITLE
Cannot use record value directly

### ISSUE THREAD

**Issue by hacdias** [FStarLang/FStar#2353]
Hello!

I'm trying to learn F* but I can't find anything related to this on the tutorial and I find the behavior quite odd. I'm trying to model a simple wallet deposit according to a message.

This works fine:

```fstar
module Bank

type address = string
type positiveValue = v:int{v >= 0}

type message = {
  sender: address;
  value: positiveValue
}

let getValue (m:message) : positiveValue = m.value

type wallet = {
  owner: address;
  value: positiveValue
}

let deposit (w:wallet) (m:message) : wallet =
  { w with value = (getValue m)  + w.value }
``` 

However, if I try to replace `deposit` by:

```fstar
let deposit (w:wallet) (m:message) : wallet =
  { w with value = m.value + w.value }
```

I.e., use `m.value` directly instead of needing an additional function, I get the error:

```
Bank.fst(27,19-27,20): (Error 189) Expected expression of type "Bank.wallet"; got expression "m" of type "Bank.message" (see also Bank.fst(26,24-26,25))
```

Am I missing something important here?

**Comment by hacdias** [comment]
I also notice it only affects `m.value`. If I use `m.sender` inside a function, it doesn't throw an error.

**Comment by W95Psp** [comment]
Hi,

I think your version of F* is simply a bit too old, you should update to an F* version more recent than PR #2350 (which was two weeks ago).

What happens with your code here (with an older F*), is that F* is shadowing the projector "value" from your record "message" in favor of the one from record "wallet".
Thus, after defining "wallet", the projector "value" denotes exclusively extracting the field "value" of a value of type "wallet", whence the type error you mention.

But this is not the case anymore, updating should solve your issue. (your code type-checks on my side with F*'s master)

**Comment by hacdias** [comment]
Hello @W95Psp! Yes, it seems I was using a version from June! It works now. Thanks!
