### ISSUE TITLE
Should document build-config

### ISSUE THREAD

**Issue by Nemuri** [FStarLang/FStar#240]
So, I downloaded the windows binary and set up the environment variables.
But when trying to compile code that uses some of the libraries in  the lib folder I get errors. 
One example is in  `/examples/security/`: 
```
C:\Users\sebastian\Desktop\fstar\examples\security>fstar acls.fst
acls.fst(89,13-89,18) : Error
Identifier not found: [List.assoc]
```
Trying with --prims seems to solve the List issue but now there is a problem with string instead. 
```
C:\Users\sebastian\Desktop\fstar\examples\security>fstar --prims acls.fst
acls.fst(5,21-5,27) : Error
Identifier not found: [string]
```
How do I fix this?

**Comment by catalin-hritcu** [comment]
You can run `make` or `make acls2.ver` in `fstar\examples\security`. It unfolds to this:
```
../../bin/fstar.exe  --admit_fsi Set ../../lib/set.fsi ../../lib/heap.fst ../../lib/list.fst ../../lib/string.fst ../../lib/st.fst acls2.fst
```
Should we document this better somewhere?

**Comment by Nemuri** [comment]
Ohh thanks! 
I completely missed the option to add specific paths to the libraries, I do not know
if I did not look hard enough or if it needs more documentation.

**Comment by nikswamy** [comment]
maybe we should start moving more towards the style with a `build-config` prelude in each file.

See `lib/mref.fst` or `examples/metatheory/tinyfstar-new.fst` for examples.

**Comment by catalin-hritcu** [comment]
What is `build-config` precisely? How exactly is the "build metadata" in these examples used? (the current Makefiles don't seem to use it)

**Comment by nikswamy** [comment]
A file can begin with `(*--build-config ... --*)`

If it does, then calling `fstar file.fst` (only a single file on the cmd line) will cause that build-config to be parsed and used for the build.

A build-config can specify three fields, delimted by semi-colon.

`options`: a space separated list of command line options
`variables`: a space separated list of equalities, e.g., `LIB=../../lib`
`other-files`:a space separates list of files, which may contain references to the variables, e.g., `$LIB/ext.fst`, where `$LIB` is replaced by the variable's value.

An example like `example/metatheory/tinyfstar-new.fst` should be self-explanatory.

Note, this is particularly useful in interactive mode. It allows you to check a file interactively, after having  type-checked some dependences.

**Comment by beurdouche** [comment]
`Build-config` does not exist anymore.
Closing
