### ISSUE TITLE
FStar.List.Tot.count doesn't extract to OCaml correctly

### ISSUE THREAD

**Issue by mgritter** [FStarLang/FStar#2403]
The implementation of `FStar.List.Tot.count` in ulib/ml/FStar_List_Tot_Count is incorrect.

Example snippet:

```FStar
module ExampleBug
open FStar.List.Tot

val x:list nat
let x = [1;2;3;4;1]

let count_1 (prev_total:nat) (l:list nat) : nat = prev_total + (count 1 x)
```

When extracted as Ocaml, the compiler omits the error message:
```
File "out/ExampleBug.ml", line 10, characters 26-69:
10 |     fun l -> prev_total + (FStar_List_Tot_Base.count Prims.int_one x)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type int but an expression was expected of type
         Z.t
```

I think the problem is that the integer literals need to be replaces by `Prims.int_zero` and `Prims.int_one` in the ML file, or perhaps use `Z.of_int`?

```Ocaml
let rec count x = function
  | [] -> 0
  | hd::tl -> if x=hd then 1 + count x tl else count x tl
```
A workaround is to copy the definition of 'count' into another module, so that the correct ML code is emitted, and use that version.

**Comment by aseemr** [comment]
Hi @mgritter , thanks for the bug report. Your suggested fix of using `Prims.int_zero` and `Prims.int_one` in the ML file sounds good to me.

Would you be interested in doing a PR that fixes it? (No issues if not, I can do it too.)
