### ISSUE TITLE
FStar.Set.as_list doesn't extract to OCaml

### ISSUE THREAD

**Issue by mgritter** [FStarLang/FStar#2412]
`FStar.Set.as_list` is defined in terms of `as_set'` which already has a note

```
(* WHY IS THIS HERE? It is not strictly part of the interface *)
let rec as_set' (#a:eqtype) (l:list a) : set a =
```
Because this function defined in the .fsti file but not in the .fst or in ml/FStar_Set.ml, no code is generated for `as_set'` and as a result OCaml compilation fails on modules that call `FStar.Set.as_list`:

```
179 |              FStar_Set.union (FStar_Set.singleton hd) (FStar_Set.as_set' tl))
                                                             ^^^^^^^^^^^^^^^^^
Error: Unbound value FStar_Set.as_set'
```

(The extracted code would probably be fine if it was a constant list?  I think that's the intent of using `normalize_term` here.)

Workaround: copy the definition of `as_list'` into the calling module and use that instead.

**Comment by aseemr** [comment]
Hi @mgritter , thanks for the report. Would you be interested in doing a PR that fixes it by adding definitions of both `as_set` and `as_set'` in `ulib/ml/FStar_Set.ml`, they can be defined as `BatSet.of_list`. And yes, for literal lists, F* would reduce `as_set'` and this would work.

**Comment by mgritter** [comment]
I'd be happy to take a look.  Is there a way to write an extraction unit test that I should follow?

It looks like adding the .fst file to `SHOULD_EXTRACT_CLOSE` in bug-reports/Makefile will try to extract and run the code?
