### ISSUE TITLE
Inconsistent error messages with type parameters + squash

### ISSUE THREAD

**Issue by gancherj** [FStarLang/FStar#2419]
I have noticed the following behavior with error messages:

Construct an inductive type `t`, and have the constructors return `squash t` instead of `t`. (This is an easy thing to accidentally do, since it is convenient for the arguments to be squashed in inductive types encoding proofs.) 
```
// This is the error that we should always get (I think)
// (Error 185) Expected a constructor of type t0; got x: Prims.unit{Test.t0}
type t0 =
 | T0 :  squash t0
```

Now, let's add some type parameters:
```
// This parameter is not constant: expected x#21767, got Test.t1 x

type t1 (x : nat) =
 | T1 : squash (t1 x)
```

And one more, even worse:
```
(*
ASSERTION FAILURE: firstN
F* may be in an inconsistent state.
Please file a bug report, ideally with a minimized version of the program that triggered the error.
*)

type t2 (x y : nat) =
 | T2 : 
   squash (t2 x y)
```

The above assertion failure continues with three or more type parameters.

**Comment by mtzguido** [comment]
Thanks Joshua! This seems to be working now, I'll add a test and close.
