### ISSUE TITLE
Wrong --codegen OCaml information with fst and snd function

### ISSUE THREAD

**Issue by hungvq00390** [FStarLang/FStar#242]
When execute code gen with fst and snd funtion, we have Support.Prims.snd , Support.Prims.fst
OCaml said: Error: Unbound module Support
Please help to check --codegen in this case

**Comment by catalin-hritcu** [comment]
Have you followed the instructions for building the support libraries here?
https://github.com/FStarLang/FStar#building-an-executable

**Comment by catalin-hritcu** [comment]
Did you manage to make this work? Any other way we can help?

**Comment by hungvq00390** [comment]
ocamlfind: Package `batteries' not found
Makefile:79: recipe for target 'support.cmx' failed
I can not install batteries to my cygwin. Please help me in this case.

**Comment by catalin-hritcu** [comment]
Batteries is not a Cygwin, but an OCaml package, and you should install it via Wodi.

Have you tried downloading Wodi from here: [wodi32] and [wodi64]?
[wodi32]: http://wodi.forge.ocamlcore.org/wodi32.tar.xz
[wodi64]: http://wodi.forge.ocamlcore.org/wodi64.tar.xz

**Comment by hungvq00390** [comment]
It's OK. Please close this.
