### ISSUE TITLE
The following actions failed │ λ build conf-python-2-7 1.2

### ISSUE THREAD

**Issue by Chaos-Crypto** [FStarLang/FStar#2420]
Hello， when I run the following command，it occur some error， could you give me some suggests?

$ opam pin add fstar --dev-repo
[NOTE] Package fstar is already pinned to git://github.com/FStarLang/FStar (version 2021.12.31~dev).
[fstar.2021.12.31~dev] no changes from git://github.com/FStarLang/FStar
fstar is now pinned to git://github.com/FStarLang/FStar (version 2021.12.31~dev)

The following actions will be performed:
  ∗ install conf-python-2-7 1.2             [required by z3]
  ∗ install z3              4.8.5           [required by fstar]
  ∗ install fstar           2021.12.31~dev*
===== ∗ 3 =====
Do you want to continue? [Y/n] y

[z3.4.8.5] downloaded from https://github.com/Z3Prover/z3/archive/Z3-4.8.5.tar.gz

[ERROR] The compilation of conf-python-2-7 failed at "dash.exe -ec  python2.7 test.py".

#=== ERROR while compiling conf-python-2-7.1.2 ================================# 

# context     2.0.8 | win32/x86_64 | ocaml-variants.4.12.0+mingw64c | git://github.com/fdopen/opam-repository-ming
w.git#opam2
# path        ~/.opam/ocaml-variants.4.12.0+mingw64c/.opam-switch/build/conf-python-2-7.1.2
# command     dash.exe -ec  python2.7 test.py
# exit-code   127
# env-file    ~/.opam/log/conf-python-2-7-20960-1872ec.env
# output-file ~/.opam/log/conf-python-2-7-20960-1872ec.out
### output ###
# dash: 1: python2.7: not found

<><>    Error report    <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

┌─ The following actions failed
│ λ build conf-python-2-7 1.2
└─
╶─ No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.

**Comment by tahina-pro** [comment]
It seems that a system package required by `python2.7` is absent. To know which one, I'd suggest using depext following https://fdopen.github.io/opam-repository-mingw/depext-cygwin/

**Comment by tahina-pro** [comment]
In fact,  you need to install Python 2.7 via Cygwin (you need to use Cygwin Python, not Windows Python), it seems that depext does not detect that missing package.

**Comment by WestSuper** [comment]
Could you help me to give some concrete steps?

**Comment by SwampertX** [comment]
Having the same problem while installing via OPAM. However, I found that `z3>=4.8.13` (latest is [4.11.2](https://opam.ocaml.org/packages/z3/z3.4.11.2/)) would no longer need the deprecated Python 2.7 and uses Python 3 instead. I see that the version is [intentionally pinned](https://github.com/FStarLang/FStar/blob/master/fstar.opam#L23); any chance we could bump it?

**Comment by SwampertX** [comment]
Related: https://github.com/FStarLang/FStar/issues/2431

**Comment by ncihnegn** [comment]
Nowadays macOS does not come with python2.

**Comment by gebner** [comment]
This should be fixed by #3069
