### ISSUE TITLE
Incorrect interaction between Errors 19 and 303

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#2424]
I am trying out a new version of Z3, so naturally I'm running the build with `OTHERFLAGS="--warn_error +19"` to see how many proofs break with the new version of Z3. Unfortunately, it seems like the implementation of `[@expect_failure]` assumes that Error 19 is always fatal and I could find no workaround that would allow me to complete the build with a new version of Z3.

Here's a minimal repro. This works:

```
module Test

[@expect_failure]
let _ = assert false
```

But this doesn't:

```
module Test

#set-options "--warn_error +19"
[@expect_failure]
let _ = assert false
```

Even though the `assert false` *is* failing, and even though the failure is correctly marked as expected, F* errors out on the latter file:

```
Test.fst(5,0-5,20): (Error 303) This top-level definition was expected to fail, but it succeeded
Test.fst(5,8-5,14): (Warning 19) assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel (see also Test.fst(5,15-5,20))
```

My hope is that the behavior of `[@expect_failure]` can be improved to not rely on the implementation detail of whether 19 was thrown as an error (or not), but instead can be made to look at the actual outcome of the query.

**Comment by tahina-pro** [comment]
I think the behavior of `[@expect_failure]` that you are describing is a feature, not a bug. If `--warn_error +19` is meant to turn 
error 19 into a warning, then no error will stop `let _ = assert false` from typechecking.
My understanding of `expect_failure` is that some F* error is expected to stop the typechecking of a definition. Such a F* error can be a tactic failure, not necessarily a SMT failure; I don't think the behavior of `expect_failure` is assuming anything specific about error 19.

**Comment by msprotz** [comment]
I don't think the notion of whether `let _ = assert false` succeeds or not should be defined in terms of whether `Error 19` aborted type-checking. I think it'd be useful to distinguish several different notions:
i) did checking a definition succeed or not
ii) did we have Error 19 or Warning 19
iii) did the expected failure to check materialize itself or not.

I see i) as a *semantic* notion, that may have multiple causes, e.g. unification error, SMT failure, tactic failure, etc. and I see ii) strictly as a user interface notion that does not affect the semantic notion.

Right now, iii) is defined in terms of ii), which is a user-interface concept. Specifically, iii) is defined in terms of the *implementation* of ii), and in a very operational manner: iii) is (right now) defined as "did ii) throw an exception or not".

My claim is  that iii) should only be a function of the semantic notion i), and should not depend on ii) or its implementation.

In the case of my specific example, per my proposal, we would have:
i) an SMT failure, so checking the definition *fails*
ii) a user interface choice, which is to report the failure of type-checking as a warning rather than an error
iii) checking failed per i), which is expected, so Error 303 does not appear and all is well.

**Comment by msprotz** [comment]
From @nikswamy, on Slack:

I've run into this issue myself before, when trying to run regressions and collect all failures. But, I've considered turning error 19 into a warning as a dubious usage.If a definition fails to verify but is admitted (because of the demotion of 19 or some other setting (e.g., admit_smt_queries)) then the verification of the rest of the program  is questionable. E.g., let _ : False = ... with a warn_error +19 trivializes all further queries.The interaction with the expect_failure attribute is tricky, because if a definition fails as expected, then that name is not added to the context. Whereas if it succeeds, then it is added to the context. So, if you had

```
[@expect_failure]
let a = ...

[@expect_failure]
let a = ...

let a = ()
```

This succeeds, because the first two do not add a to the context. Whereas is either of first two definitions were to only raise warnings and be accepted, then the inclusion of a in the environment would lead to the third definition failing due to a top-level name clash.I think this particular usage of trying to collect all failures is a valid (though somewhat specialized) use case. Maybe we should find some other way to support it via a completely different option, rather than fiddling with questionable warn_error settings and ending up with messy interactions.

**Comment by msprotz** [comment]
The agreed solution was to make it possible to turn 303 into a warning rather than an error, and *not* insert the definition into the environment to avoid the problem described above.
