### ISSUE TITLE
z3 4.8.5

### ISSUE THREAD

**Issue by sure0813** [FStarLang/FStar#2429]
when I install fstar with "opam install fstar" in Mac. there are always some errors in installing z3 4.8.5.
 I can install other version of z3 but 4.8.5. 
can you give me some advice? 
 thank you!
<img width="680" alt="截屏2022-01-16 下午6 36 41" src="https://user-images.githubusercontent.com/92378505/149656585-c8c7c94b-21ba-4d23-b7d7-46f7f6bb71b7.png">
![Uploading 截屏2022-01-16 下午6.36.41.png…]()

**Comment by sure0813** [comment]
there are some  informations:


<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
⬇ retrieved z3.4.8.5  (https://github.com/Z3Prover/z3/archive/Z3-4.8.5.tar.gz)
[ERROR] The compilation of z3.4.8.5 failed at "make -C build -j 7".

#=== ERROR while compiling z3.4.8.5 ===========================================#
# context     2.1.2 | macos/arm64 | ocaml.4.12.1 | https://opam.ocaml.org#c50d5700
# path        ~/.opam/default/.opam-switch/build/z3.4.8.5
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -C build -j 7
# exit-code   2
# env-file    ~/.opam/log/z3-85870-0b70d0.env
# output-file ~/.opam/log/z3-85870-0b70d0.out
### output ###
# [...]
# clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
# g++  -o z3  shell/lp_frontend.o shell/dimacs_frontend.o shell/z3_log_frontend.o shell/install_tactic.o shell/mem_initializer.o shell/datalog_frontend.o shell/gparams_register_modules.o shell/opt_frontend.o shell/smtlib_frontend.o shell/main.o cmd_context/extra_cmds/extra_cmds.a api/api.a opt/opt.a tactic/portfolio/portfolio.a tactic/fpa/fpa_tactics.a tactic/smtlogics/smtlogic_tactics.a tactic[...]
# g++ -o libz3.dylib -dynamiclib api/dll/install_tactic.o api/dll/mem_initializer.o api/dll/gparams_register_modules.o api/dll/dll.o api/api_array.o api/api_fpa.o api/api_arith.o api/api_datatype.o api/z3_replayer.o api/api_model.o api/api_log_macros.o api/api_ast_map.o api/api_datalog.o api/api_ast_vector.o api/api_commands.o api/api_opt.o api/api_special_relations.o api/api_algebraic.o api/ap[...]
# cp libz3.a libz3-static.a
# ocamlfind ocamlc -package num  -ccopt "-D_MP_INTERNAL -DNDEBUG -D_EXTERNAL_RELEASE   -fvisibility=hidden -c -msse -msse2 -D_NO_OMP_ -O3 -Wno-unknown-pragmas -Wno-overloaded-virtual -Wno-unused-value -fPIC -I /Users/sure/.opam/default/lib/ocaml -I ../src/api -I ../src/api/ml -o api/ml/z3native_stubs.o" -c ../src/api/ml/z3native_stubs.c
# clang: warning: argument unused during compilation: '-msse' [-Wunused-command-line-argument]
# clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
# cp libz3.dylib python
# ocamlmklib -o api/ml/z3ml -I api/ml -L. api/ml/z3native_stubs.o api/ml/z3enums.cmo api/ml/z3native.cmo api/ml/z3.cmo  -lz3-static -lstdc++ -lgomp 
# ld: library not found for -lgomp
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# make: *** [api/ml/z3ml.cma] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build z3 4.8.5
└─ 
╶─ No changes have been performed

**Comment by R1kM** [comment]
Hi,
I just fixed the Z3 4.8.5 opam package (https://github.com/ocaml/opam-repository/pull/20461), and could build fstar locally using opam on MacOS
Could you please run `opam update` and try reinstalling fstar, and report if there are other issues?
Thanks
