### ISSUE TITLE
Error: Unbound module PPrintOCaml

### ISSUE THREAD

**Issue by zhaomengshan666** [FStarLang/FStar#2430]
Hello! When I use `opam install fstar` to install fstar on debian system, it will download the fstar-2021.06.06 and build，but There seems to be a bug:

`File "src/prettyprint/ml/FStar_Pprint.ml", line 22, characters 20-36:`
`22 | let doc_of_char c = PPrintOCaml.char (Char.chr c)`
` ​                               ^^^^^^^^^^^^^^^^`
`Error: Unbound module PPrintOCaml`
`Command exited with code 2.`

![119b683cf5d73849ed9e8b08ebf64b0](https://user-images.githubusercontent.com/48112648/149778882-b9fc8268-c8f8-458d-913d-c71fd8af20c3.png)

I found that you have changed the code in your repo a few days ago, then what should I do if I still want to install use `opam install fstar`? Should I install fstar another way?
Thx.

**Comment by R1kM** [comment]
You should be able to install the latest F* version using `opam pin add fstar --dev-repo`.

@tahina-pro given the latest update to PPrint, we probably should have the constraint `pprint<20220103` in the actual (non-dev) opam package, wdyt?

**Comment by zhaomengshan666** [comment]
Thank you very much!
I have changed the constraint by `opam pin edit fstar` and added the constraint `pprint<20220103`, then the fstar v2021.06.06 can be installed correctly by `opam install fstar`.
![5J8@ 77(ZK)V{2Y__~0L5)R](https://user-images.githubusercontent.com/48112648/150262297-01ef7030-8c26-4d28-bfb8-5be318d12e8c.png)
![$3@SLQJI5(JS4)HE4VCCXST](https://user-images.githubusercontent.com/48112648/150262328-bd3fdc35-5927-4779-b0f7-1b9c01cf042b.png)

**Comment by R1kM** [comment]
This was fixed in opam, closing
