### ISSUE TITLE
Error when argument of a record is constrained to implement a typeclass

### ISSUE THREAD

**Issue by TWal** [FStarLang/FStar#2432]
Hello,

I'm trying to use typeclasses in my code and got an error which can be demonstrated in the following minimal working example:

```fstar
class test_typeclass a = {
  pred: a -> bool;
}

type test_type (t:Type) {|test_typeclass t|} = x:t{pred x}

// Works fine
type test1 (t:Type) {|test_typeclass t|} = (test_type t & bool)

// (Error 173) Too many arguments to function of type t: Type -> (#[Tactics.Typeclasses.tcresolve ()] _: test_typeclass t) -> Prims.Tot Type; got 2 arguments, remaining type is Type
[@@expect_failure [173]]
type test2 (t:Type) {|test_typeclass t|} = {
  x: test_type t;
  y: bool;
}
```

I believe it should be possible to write such a record?

**Comment by aseemr** [comment]
A workaround is to write it as an inductive (which records are desugared to internally):

```
type test2 (t:Type) {|test_typeclass t|} =
  | Mk: x:test_type t -> y:bool -> test2 t
```

(Note that you can still use `v.x` and `v.y` syntax for projecting the `x` and `y` fields.)

**Comment by TWal** [comment]
Thanks, I thought it would be required to use `Mk?.x` and `Mk?.y` but since we can use record-like projectors this workaround is fine for my usage :)

**Comment by aseemr** [comment]
The bug is in desugaring, when converting the record type to an inductive, meta arguments are not considered as implicits when constructing the type of the (only) dataconstructor.

**Comment by aseemr** [comment]
Fixed in master, thanks for the report!
