### ISSUE TITLE
Name "String.strcat" not found

### ISSUE THREAD

**Issue by hungvq00390** [FStarLang/FStar#244]
I try with code

let strcat s1 s2 = s1 ^ s2
let strcat3 s1 s2 s3 = strcat s1 (strcat s2 s3)

But F* say 
CoreTypeSystem.fst(174,19-175,3) : Error
Name "String.strcat" not found
Please help to check in this case

**Comment by catalin-hritcu** [comment]
As the error message suggests, the `^` symbol is desugared to the Strong.strcat function. The declaration of this function is in `lib/string.fst`, so it's just a matter of passing this file too when invoking F*, like this:
```
../../bin/fstar.exe  ../../lib/string.fst bug244.fst
```
output:
```
../../bin/fstar.exe  ../../lib/string.fst bug244.fst
Verified module: Prims
Verified module: String
Verified module: Bug244
All verification conditions discharged successfully
```

**Comment by hungvq00390** [comment]
$ fstar --prims D://Fstar-New//FStar-master//lib//prims.fst  D://Fstar-New//FStar-master//lib//string.fst CoreTypeSystem.fst
CoreTypeSystem.fst(173,23-173,29) : Error
Name "String.strcat" not found
This still happen. Did i do something wrong with this ?

Line 173 is: let strcat3 s1 s2 s3 = strcat s1 (strcat s2 s3)

**Comment by catalin-hritcu** [comment]
I'm having trouble reproducing this. Please try the file I've just added in 75fc7354 and report back whether that worked or not. If that worked then please try to minimize your failing file and then list here what you got at the end.

**Comment by hungvq00390** [comment]
Ah. It's OK now. I try to download new version, compile new F* and it's OK.
Thank you.
