### ISSUE TITLE
Steel with or without selectors: small normalization bug

### ISSUE THREAD

**Issue by cmovcc** [FStarLang/FStar#2447]
Hello,
I noticed the following bug while using Steel with selectors, that also affects Steel without selectors.
It can be demonstrated with the following minimal example using a dummy structure without selectors.
This small example also contains a simple workaround.
```fstar
module Bug_norm

open Steel.FractionalPermission
module Mem = Steel.Memory
open Steel.Effect.Atomic
open Steel.Effect
open Steel.Reference

#set-options "--ide_id_info_off"

let tree (a: Type0) = bool

let rec linked_tree (#a: Type0) (ptr: ref bool) (v: tree a)
  : Tot vprop
  = match v with
  | true -> pure (ptr == null)
  | false -> Steel.Reference.pts_to ptr full_perm v

let intro_linked_tree (#a: Type0) (_:unit)
  : SteelT unit
  emp (fun _ -> linked_tree #a null true)
  = sladmit ()

[@@ expect_failure]
let create_leaf1 (#a: Type0) (_: unit) : SteelT (ref bool)
  emp (fun ptr -> linked_tree #a ptr true)
  = intro_linked_tree #a ();
    return null

let create_leaf2 (#a: Type0) (_: unit) : SteelT (ref bool)
  emp (fun ptr -> linked_tree #a ptr true)
  = intro_linked_tree #a ();
    // TODO: it should be possible to remove next line
    let h = get () in
    return null
```
Fixing this quite small bug would lead to cleaner code, I have had to use this workaround several times.
Following discussion with @R1kM, it is likely a small normalization bug.
Thanks in advance!

**Comment by R1kM** [comment]
Early diagnosis seems to indicate that this is a bug with the framing tactic, the failing goal is of the shape
`"fun x -> linked_tree x" cannot be unified with "fun _ -> linked_tree null_t"`.
My current guess is that there is a tricky interaction between the framing tactic and normalization that leads to a goal becoming unsolvable.
I'll debug further and post an update here.

**Comment by R1kM** [comment]
Minimizing further, the following:
```fstar
assume
val linked_tree (#a: Type0) (ptr: ref a)
  : Tot vprop

assume
val intro_linked_tree (#a: Type0) (_:unit)
  : SteelT unit
  emp (fun _ -> linked_tree #a null)

[@@ expect_failure]
let create_leaf1 (#a: Type0) (_: unit) : SteelT (ref a)
  emp (fun ptr -> linked_tree ptr)
  = intro_linked_tree #a ();
    return (null #a)
```
fails with
```(Error 228) user tactic failed: `could not find a solution for unifying
Bug_norm.linked_tree Steel.Reference.null
and
Bug_norm.linked_tree x`
```

**Comment by R1kM** [comment]
Interestingly, the root problem seems to come from F* introducing an additional `return` during effect elaboration, which breaks some invariant from the Steel calculus.
This seems to only occur when the return type of `return null` is either not fully inferred or imprecisely inferred, for instance, the following code does not introduce an additional `return`, and hence verifies. Note that the type implicit for return is passed explicitly here.
```fstar
let create_leaf2 (#a: Type0) (_: unit) : SteelT (ref a)
  emp (fun ptr -> linked_tree ptr)
  = intro_linked_tree #a ();
    return #(ref a) null
```

**Comment by aseemr** [comment]
The code in the original report works after the fix, without any implicit annotations and `get`.

**Comment by cmovcc** [comment]
Many thanks!
