### ISSUE TITLE
Highly confusing interaction between command line arguments and build-config comments

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#246]
Passing command line arguments silently discards build-config comments. This might be expected behavior at the moment (https://github.com/FStarLang/FStar/issues/240#issuecomment-103659107), but it's highly confusing that this happens silently. We wasted quite a bit of time until we understood what was happening.

**Comment by SimonForest** [comment]
Actually, it seems worse than that. When both are used, the options provided in the command line seem to be applied only for the first file. In tinyfstar-new.fst, at the top, there is 
```fsharp
(*--build-config 
    options:--z3timeout 15 --max_fuel 4 --max_ifuel 4 --initial_fuel 4 --initial_ifuel 2;
    other-files:../../lib/classical.fst ../../lib/ext.fst
  --*)
```

If I add --log_types in the command line or the Makefile, I only get the types for classical.fst.

**Comment by markulf** [comment]
Actually, it is even worse than that. When you supply environment variables `--fstar_home` and `--smt` on the command line, these are overwritten by `options:`, causing an unexpected error if Z3 is not found:

```
Unexpected error; please file a bug report, ideally with a minimized version of the source 
program that triggered the error. ApplicationName='z3', CommandLine='-smt2 -in -t:10000
AUTO_CONFIG=false MODEL=true SMT.RELEVANCY=2', CurrentDirectory='', 
Native error= Cannot find the specified file 
```
This error is different from the error when z3 isn't found because of the `variables` set on the command line.

Currently my fix is to set the same variable twice. I stumbled over this while working on a patch for the tutorial environment, to be able to use `build-config` there which should be useful for larger examples, or code extraction.

**Comment by markulf** [comment]
See also (https://github.com/FStarLang/FStar/issues/272#issuecomment-118917744).

**Comment by nikswamy** [comment]
Commit 16138cf should have fixed this

The current behavior is that all the command line arguments are parsed and set.

Then the build-config is parsed and all the options it provides are set. If the same option is provided in both places, the build-config overwrites the command line value.

Whenever reset-options is called (at the end of type-checking a module, or when the  user writes \#reset-options in the source), the current options are cleared; the command line is parsed and set again; and then the build-config options of the original file is taken.

Note, the build-config is parsed only when either the user gives the option '--use_build_config' or when there is only a single file on the command line.

**Comment by catalin-hritcu** [comment]
Closing this, although there are more improvements we might want to do to the build-config mechanism to make it more usable in the future.
