### ISSUE TITLE
Slack and maillists are inaccessible

### ISSUE THREAD

**Issue by WhiteBlackGoose** [FStarLang/FStar#2465]
Hello. I already joined the Zulip forum, but just to report about these issues:
- Slack does not work beacuse it requires me to have @microsoft.com email (I think it can be configured in the settings?)
- Mailing list link (http://lists.gforge.inria.fr/mailman/listinfo/fstar-club) does not open (ERR_CONNECTION_TIMED_OUT)

**Comment by kant2002** [comment]
@WhiteBlackGoose Did you try https://aka.ms/JoinEverestSlack ? I successfully join this project. Also current communications can happens on GitHub Discussions which was activated [recently](https://github.com/FStarLang/FStar/discussions/2510#discussion-3969615)

**Comment by WhiteBlackGoose** [comment]
Thanks, I'll check those out one day...

**Comment by aseemr** [comment]
Closing the issue, thanks @kant2002 for the comment!

**Comment by WhiteBlackGoose** [comment]
@kant2002 not really, still requires msft or google. cc @aseemr probably worth opening
![image](https://user-images.githubusercontent.com/31178401/173190663-9b498008-0cdc-4094-a50d-01268f91e763.png)

**Comment by kant2002** [comment]
@WhiteBlackGoose welcome back from your exile! Maybe you are right an I do have gmail account.

**Comment by nikswamy** [comment]
You should be able to join slack from https://aka.ms/JoinEverestSlack 
I just updated the joining link
Email list is still inaccessible---we're planning on creating a new one.

**Comment by WhiteBlackGoose** [comment]
Thanks, it worked!
