### ISSUE TITLE
Tutorial sandbox seems to be have some issues

### ISSUE THREAD

**Issue by kant2002** [FStarLang/FStar#2490]
Error I'm seeing in the tutorial
```
(Error 152) not a valid include directory: /var/fstar/doc/tutorial/code/solutions

1 error was reported (see above)
```
1. I go to https://www.fstar-lang.org/tutorial/
2. Enter first code to sandbox
```
module Welcome

type vec (a:Type) : nat -> Type =
  | Nil : vec a 0
  | Cons : #n:nat -> hd:a -> tl:vec a n -> vec a (n + 1)
```
3. Press Run button in the right bottom corner.

Error message appears.

**Comment by tahina-pro** [comment]
Thank you for notifying us. There was a useless `--include` setting on the F* command line, which we just removed, it seems to work better now.
