### ISSUE TITLE
Unpredictable results from the compiler

### ISSUE THREAD

**Issue by DemuirGos** [FStarLang/FStar#2492]
why does the code below fail with error `Test.fst(8,8-8,14): (Error 19) assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel (see also Test.fst(8,14-8,27))`
``` 
module Test
open FStar.Mul 

let divides  (divisor :nat) (n:nat) = exists (k:nat). k*divisor=n
let _ = assert(divides 3 6)
``` 
but this one passes the type checker
```
module Test
open FStar.Mul 

let divides  (divisor :nat) (n:nat) = exists (k:nat). k*divisor=n
let _ = assert(divides 3 9)
```

**Comment by nikswamy** [comment]
Validity of first-order formulae (i.e., those with quantifiers) is an undecidable problem. 

F* and Z3 (its underlying automated theorem prover) use various heuristics to try to find solutions. It's not guaranteed to work in all cases. 

In general,  you will have to help F* and Z3 find instantiations to quantifiers: See
https://github.com/FStarLang/FStar/wiki/Quantifiers-and-patterns
