### ISSUE TITLE
Ensures clauses on Tot silently ignored

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#250]
F* accepts the following junk:
```ocaml
val foo : int -> Tot int (ensures (fun _ -> false))
let foo x = x
```
```
../bin/fstar.exe ill-typed-ensures.fst
Verified module: Prims
Verified module: Bug250
All verification conditions discharged successfully
```
It seems this is not because of some sort of inconsistency (although it looks a hell lot like one), but because `Tot` doesn't really take an `ensures` clause and whatever is passed there is silently ignored.
```
val bar : int -> Tot int (ensures (42 "is the the answer"))
let bar x = x
```

This can be super confusing. We even had a test in our suite containing this mistake:
https://github.com/FStarLang/FStar/blob/0f8a8dc1f25cc9ec13819881fb8bfd00a4ba791c/examples/bug-reports/bug177.fst

**Comment by nikswamy** [comment]
Closed with --universes
