### ISSUE TITLE
SMTPat lemmas and fsi do not mix well

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#251]
See associated files in bug-reports

In f.fsi
```
module F
type T : unit -> Type
val lemma_1 : x:unit -> Lemma (requires True) (ensures (T x)) [SMTPatT (T x)]
val lemma_2 : x:unit -> Lemma (ensures (T x))
```

In f.fst:

```
module F
type T : unit -> Type
let lemma_1 () = admit()
let lemma_2 () = lemma_1()
```

`fstar.exe f.fsi f.fst` fails with 
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Name not found: lemma_1
```

**Comment by vkanne-msft** [comment]
Getting a new error. 
    
    .\examples/bug-reports/bug251.fst(2,5-2,6) : Error
    Invalid identifer 'T'; expected a symbol that begins with a lower-case character

**Comment by s-zanella** [comment]
The example typechecks fine after working around the syntax error.
Closing.
