### ISSUE TITLE
Error code different

### ISSUE THREAD

**Issue by kant2002** [FStarLang/FStar#2520]
I did try to reproduce https://github.com/FStarLang/FStar/issues/2468 and what I receive is following message
```
$ X=1000 ; ../bin/fstar.exe --fuel $X --ifuel $X --z3rlimit 1000 --codegen OCaml ~/A.fst
Extracted module FStar.Pervasives.Native
Extracted module A
/home/kant/A.fst(19,71-19,147): (Error 16) Unknown assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel
(Warning 282) Expected Z3 version "Z3 version 4.8.5", got "Z3 version 4.8.8 - 64 bit
"
Please download the version of Z3 corresponding to your platform from:
https://github.com/FStarLang/binaries/tree/master/z3-tested
and add the bin/ subdirectory into your PATH

Verified module: A
1 error was reported (see above)
```

If you carefully check error messages you will see

**Previous error**
```
(Error 19) assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel (see also A.fst(19,100-19,146))
```
**My error**
```
(Error 16) Unknown assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel
```

What explanation does this behavior have

**Comment by aseemr** [comment]
When Z3 fails, F* tries to find out from the failure what assertion/postcondition did Z3 fail to prove. Sometimes the output of Z3 allows F* to infer it (the first error that you report), but sometimes Z3 does not report back enough for F* to infer anything useful, that's the second error.

I also see that the Z3 version that you are using is 4.8.8, so the change in the Z3 behavior is not unexpected.

**Comment by kant2002** [comment]
@aseemr would it be reasonable to change message, so they would be different for these two cases? 

For example
```
(Error 19) Assertion failed at A.fst(19,100-19,146); The SMT solver could not prove the query, Try to spell your proof in more detail or increase fuel/ifuel
```
and let `Error 16` be the same.
```
(Error 16) Unknown assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel
```

what do you think?
