### ISSUE TITLE
unexpected assertion failure because of type inference

### ISSUE THREAD

**Issue by aa755** [FStarLang/FStar#254]
```
(*--build-config
    other-files:list.fst
  --*)

module StructuredMem
open FStar.List

val foo : list nat -> Tot bool
let foo _  = true

val bar :
 ms1:(list (nat * nat))
  -> ms2:(list (nat * nat)){mapT fst ms1 = mapT fst ms2}
  -> Lemma
      (requires (foo  (mapT fst ms1))) (ensures true)
let bar ms1 ms2 =
  let x = mapT fst ms1 in
  let y = mapT fst ms2 in
(** this fails, but removing any one of the assertions below succeeds *)
  let _ = assert (foo x) in
  let _ = assert (x = y) in
  admit ()

**Comment by ckeller** [comment]
It works if we give the following type to `foo`:
```
val foo : 'a -> Tot bool
```
I suspect that, by applying `foo` to `x`, we are losing type information on `x`...

**Comment by ckeller** [comment]
I tried to minimize it, but if I replace everywhere `mapT fst` with some
```
assume val f : list ('a * 'b) -> Tot (list 'a)
```
then there is no error...

**Comment by nikswamy** [comment]
This issue is that type inference is picking a less precise type than it should for the equality in the refinement formula. Specifically, if you write the program this way, it type-checks.

```
(*--build-config
    variables:LIB=../../lib;
    other-files:$LIB/list.fst
--*)

module Bug254
open List

val foo : list nat -> Tot bool
let foo _ = true

val bar : ms1:list (nat * nat)
        -> ms2:list (nat * nat){mapT #_ #nat fst ms1 = mapT #_ #nat fst ms2}
        -> Lemma
        (requires (foo (mapT fst ms1)))
        (ensures true)
let bar ms1 ms2 =
let x = mapT fst ms1 in
let y = mapT fst ms2 in
let _ = assert (foo x) in
let _ = assert (x = y) in
()
```

Notice the explicit instantiation of the second type argument of `mapT` in the refinement formula in the type of `bar`.

Without that annotation, F\* picks the second argument to be `int`. 

Fixing this properly requires a deeper look at type inference ... the workaround is to provide the explicit annotation.

**Comment by aa755msr** [comment]
Thanks. This reminds me of Coq's "Set Printing Implicit", which is helpful for debugging in situations like this. Such an option would be useful when the facility to inspect the context(hypotheses) and conclusion is implement.

**Comment by catalin-hritcu** [comment]
@aa755msr  We already have `--print_implicits` and `--log_types`, but yes, no context printing yet.

**Comment by aa755msr** [comment]
Thanks, I did not know about --print_implicits.

**Comment by vkanne-msft** [comment]
Does not fail. All assertions pass successfully
