### ISSUE TITLE
Misleading error message when trying to define a function starting with an uppercase letter

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#255]
It is forbidden to give a name starting with an uppercase letter to something which is not a constructor, such as:

```
let Wrong x = x
```

but the error message is misleading:

```
Identifier not found: [x]
```

**Comment by nikswamy** [comment]
The trouble is that this is parsed as 
```match x with Wrong x -> x```

And it may actually be valid to write this if there is an `x` in scope.

**Comment by catalin-hritcu** [comment]
Is this really parsed this way even without the `in` at the end?

**Comment by catalin-hritcu** [comment]
This problem is still a there:
```
$ fstar.exe bug255.fst
./bug255.fst(3,14-3,15) : (Error) Identifier not found: [x]
```

**Comment by mtzguido** [comment]
Still present, but I think this is superseded by #1228.
