### ISSUE TITLE
Unexpected error output from Z3: unknown constant Prims.precedes@tok

### ISSUE THREAD

**Issue by jaylorch** [FStarLang/FStar#2552]
The following code leads to the following error:

```
module Test32

assume val t: Type -> Type
assume val r (#a: Type) (w: t a) (x1: a) (x2: a) : Type0
assume val p (a: Type) : (w: t a{r w == precedes #a})

let lem () : Lemma (True) =
  assert (r (p nat) == precedes #nat)
```

```
Unexpected output from Z3 (error "line 127673 column 0: unknown constant Prims.precedes@tok")
```

**Comment by aseemr** [comment]
Thanks for the report @jaylorch. `precedes` gets special treatment in the smt encoding, which also means that it is not set up for partial application reasoning or even typing in smt.

May be we shouldn't allow client code to program with it directly, e.g. by marking it `private` in `prims.fst`. This snippet would then fail to typecheck.

Another fix is to encode it completely, as we do with other symbols.

WDYT? cc @nikswamy and @tahina-pro

**Comment by jaylorch** [comment]
My personal preference would be to just improve the understandability of the error message. It would be nice if it explained the underlying issue, provided a workaround (writing a function wrapper around precedes, and using that), and perhaps even gave an example of using such a workaround.

**Comment by jaylorch** [comment]
...and it would be nice if the error happened at the time of encoding, rather than passing an invalid encoding to Z3.

**Comment by nikswamy** [comment]
For the record, I had mentioned to Jay offline that a workaround is to 

```
module Test32

assume val t: Type -> Type
assume val r (#a: Type) (w: t a) (x1: a) (x2: a) : Type0
assume val p (a: Type) : (w: t a{r w == (fun x y -> precedes #a x y)})

let lem () : Lemma (True) =
  assert (r (p nat) == (fun x y -> precedes #nat x y))
```

Detecting this in the encoding as Jay suggests should be feasible. Changing the encoding to support partially applied precedes will be a fair bit harder and will likely introduce some noise in the overwhelmingly common case where precedes is fully applied.

**Comment by aseemr** [comment]
Nik, Tahina, and I discussed it offline, and finally ended up adding support for partial applied precedes to the smt encoding. Closing the issue, thanks again Jay!
