### ISSUE TITLE
Forgetting refinements on the return type of nested lets

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#256]
The following does not typecheck:

```
assume type P : int -> Type
assume val witness: i:int{P i}

val f: unit -> i:int{P i}
let f = let g () = witness in g
```

The current workaround is to explicitely give the type of `g`.

**Comment by jkzinzindohoue** [comment]
Interestingly the following seems to work :

assume type P : int -> Type
assume val witness: i:int{P i}

val f: unit -> i:int{P i}
let f = let g = fun unit -> witness in g

The nested lets may not be the problem, rather something with the inference
in applications ?

2015-06-09 12:06 GMT+02:00 ckeller <notifications@github.com>:

**Comment by ckeller** [comment]
Indeed, but it does not work with:
```
let f = let g = fun () -> witness in g
```

**Comment by ckeller** [comment]
Here is another example that fails and that does not involve pattern matching:
```
assume type P : int -> Type
assume val witness: i:int{P i}

val f: int -> ((i:int{P i}) * int)
let f = let g i = (witness,4) in g
```

**Comment by nikswamy** [comment]
This also seems related to #254 
Type inference currently picks a type that is too imprecise.
