### ISSUE TITLE
misleading error message about matching on a:Type

### ISSUE THREAD

**Issue by aa755** [FStarLang/FStar#257]
I did not expect to be able to define the following function (which might break parametricity). However, the error message seems misleading.

```
val  sizeof : Type -> int
let sizeof (a:Type) =
match a with
| int -> 99
| _ -> 0
```

The error says "identifier not found [a]". The identifier [a] is indeed in the context of the match.
It should rather say that [Type] is not a (co)inductively defined type/kind.

**Comment by catalin-hritcu** [comment]
Agreed. I thought I had already filed this in the past, but couldn't find it, so maybe not.

**Comment by nikswamy** [comment]
This has to do with the stratification of F\*'s syntax. In the match, it looks for an expression and there isn't any expression variable `a` bound in the context. 

I think the best I can do right now is to say "there is no expression variable `a`".

**Comment by catalin-hritcu** [comment]
This does type-check now, although it doesn't do anything interesting (`int` is just a variable name here and matches everything). This discussion occurred again in #768.
