### ISSUE TITLE
Possibly redundant explicit parameter requirement in typeclasses

### ISSUE THREAD

**Issue by hacklex** [FStarLang/FStar#2576]
The last definition requires explicit provision of `#t`, which should probably be derived automatically.
Note how it works fine if we move the associativity field to the base typeclass, and we don't need to provide `#t` manually there...

```fst
module Sandbox

module TC = FStar.Tactics.Typeclasses

class equatable (t:Type) = {
  eq: t -> t -> bool;
  reflexivity : (x:t -> Lemma (eq x x));
  symmetry: (x:t -> y:t -> Lemma (requires eq x y) (ensures eq y x));
  transitivity: (x:t -> y:t -> z:t -> Lemma (requires (x `eq` y /\ y `eq` z)) (ensures (x `eq` z)))
} 
let ( = ) (#t:Type) {|h: equatable t|} = h.eq

type associativity_lemma (#t:Type) {| equatable t |} (op: t->t->t) = 
  x:t -> y:t -> z:t -> Lemma (op (op x y) z = op x (op y z))

type commutativity_lemma (#t:Type) {| equatable t |} (op: t->t->t) = 
  x:t -> y:t -> Lemma (op x y = op y x)

type congruence_lemma (#t:Type) {| equatable t |} (op: t->t->t) = 
  x:t -> y:t -> z:t -> w:t -> Lemma (requires x=z /\ y=w) (ensures op x y = op z w)
 
class test_add (t:Type) = {
  add: t->t->t;
  [@@@TC.no_method] eq: equatable t;
  [@@@TC.no_method] congruence: congruence_lemma add  
}

instance ta_eq (t:Type) (ta: test_add t) = ta.eq

class test_add_assoc (t:Type) = {
  [@@@TC.no_method] has_add : test_add t; 
  [@@@TC.no_method] associativity: associativity_lemma #t add  // Do we really need to provide #t here?
}
```

**Comment by nikswamy** [comment]
Yes, I don't see how F* could infer that the associativity field is intended to be an instance of the `associativity_lemma` at type `t`. 

I think you may be thinking that in this particular context, there is only of instance of the class `test_add` in scope, so why can't F* just resolve it to that one instance. But, this is non-modular: If this module appeared in the scope of some other module where there happened to be some other instance around, then suddenly this single instance heuristic would fail and your program would fail to check.

At the usage of the `congruence_lemma` in the base class `test_add`, the name `add` is monomorphic: it has type `t -> t -> t`, so there is no ambiguity in inferring the implicit argument of the congruence lemma. 

But, in `test_ad_assoc`,  the name `add` polymorphic `#t:Type -> {|test_add t|} -> t -> t -> t`.

**Comment by hacklex** [comment]
Crystal clear, thank you!
