### ISSUE TITLE
Spurious singleton lex tuples get in the way of a termination proof

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#258]
See bug258.fst

**Comment by vkanne-msft** [comment]
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
impossible

**Comment by s-zanella** [comment]
Did you get that error while checking `examples/bug-reports/bug258.fst`?
With the current file I get
```
$ bin/fstar.exe --universes examples/bug-reports/bug258.fst 
Warning: the module declaration "module Ast" found in file examples/bug-reports/bug258.fst does not match its filename. Dependencies will be incorrect.
examples/bug-reports/bug258.fst(1,10-6,27) : Error
Mutually defined type contains a non-inductive element
```
...which makes sense. 
I can reproduce the original issue after patching the example to work around that error. That is, the termination proof of the mutually recursive function succeeds with a `decreases` clause, but doesn't without it.

**Comment by catalin-hritcu** [comment]
This is still the current status:
```
$ fstar.exe bug258.fst
./bug258.fst(15,14-15,27): (Error) Subtyping check failed; expected type (uu___:nat -> Tot value); got type (n:(n#597:nat{(precedes (LexCons en LexTop) v)}) -> Tot value (decreases en)) (see ./bug258.fst(13,0-16,51))
./bug258.fst(16,43-16,51): (Error) Subtyping check failed; expected type (v#1191:value{(precedes v@0 (LexCons en LexTop))}); got type value (see ./bug258.fst(13,0-16,51))
Verified module: Bug258 (456 milliseconds)
2 errors were reported (see above)
```
Things work if I uncomment the decreases clause for `slice_v`.

**Comment by mtzguido** [comment]
Seems the failure is that, without the clause, we're checking for `Prims.LexCons en Prims.LexTop << v` instead of `en << v`.

**Comment by nikswamy** [comment]
Also related, issue #1916
