### ISSUE TITLE
VConfig associated to a sigelt is empty

### ISSUE THREAD

**Issue by R1kM** [FStarLang/FStar#2580]
Consider the following minimized example:

```fstarmodule Test

open FStar.Reflection
open FStar.Tactics

#set-options "--fuel 0 --ifuel 0"

let f () = ()

#set-options "--fuel 1 --ifuel 1"

let g () =
  assert True by (
    let fsig = lookup_typ (top_env ()) (["Test"; "f"]) in
    match fsig with
    | None -> fail "should not happen"
    | Some fsig ->
      (let opt_conf = sigelt_opts fsig in
      match opt_conf with
      | None -> fail "no vconfig"
      | Some conf -> dump (term_to_string (embed_vconfig conf)))
    )
```
I would have expected `sigelt_opts` to return the options in which f was typechecked (i.e., fuel and ifuel set to 0).
However, this code fails, since sigelt_opts returns None.
This seems like a recent-ish regression, as this feature was previously heavily used in HACL* without issues.

**Comment by aseemr** [comment]
I can take a look, but the example fails even with Feb. 5th 2022 F* release, so may be there is something different here than HACL* usage. But I will look more.

**Comment by R1kM** [comment]
This actually seems related to me not fully understanding the expected behaviour of sigelt_opts. See #2581 that tries to clarify this, in the meantime, closing this issue.

**Comment by aseemr** [comment]
Great, thanks for documenting it!
