### ISSUE TITLE
Can the Tutorial be provided as a PDF ?

### ISSUE THREAD

**Issue by DemuirGos** [FStarLang/FStar#2604]

**Comment by nikswamy** [comment]
I have been using restructured text and sphinx to generate the documentation and it supports a PDF mode. However, there are currently many glitches in the generated PDF that I need to sort out (missing unicode characters etc.), hierarchical structure that does not match the HTML pages, etc. But it should be possible to fix that. I will try to post a PDF version in the next week or two.

**Comment by nikswamy** [comment]
I posted a PDF here http://fstar-lang.org/tutorial/proof-oriented-programming-in-fstar.pdf

It's also linked from the main fstar-lang.org page
