### ISSUE TITLE
Equality (=) is not reduced for elements with different types

### ISSUE THREAD

**Issue by 857b** [FStarLang/FStar#2615]
On the following example, the equality `=` is not reduced for  `test_fail`:
```fstar
module Main

open FStar.Tactics

[@@ expect_failure [228]]
let test_ok_0 =
  assert (Some 0 = Some 0)
      // reduced to [squash true]
      by (norm [primops]; fail "print")

let int1 = int
[@@ expect_failure [228]]
let test_fail =
  assert (Some #int 0 = Some #int1 0)
      // not reduced
      by (norm [primops]; fail "print")


let eq_Some (#a : eqtype) (x y : option a) : bool =
  match x, y with
  | Some x, Some y -> x = y
  | None,   None   -> true
  | _              -> false

[@@ expect_failure [228]]
let test_ok_1 =
  assert (Some #int 0 `eq_Some` Some #int1 0)
      // reduced to [squash (true == true)]
      by (norm [delta; iota; primops]; fail "print")

```
`test_ok_0` suggests that this behavior is due to the syntactical difference between `int` and `int1`. When this happens, a possible workaround is to unfold the type or to use a specialized comparator such as `eq_Some` as in `test_ok_1`.

**Comment by tahina-pro** [comment]
I think the failure is legit: the `primops` equality rule only applies to two syntactically equal terms, and the user has to explicitly ask for `int1` to be unfolded to `int` with a `delta` (or `delta_only`) rule.
