### ISSUE TITLE
Update the VSCode extension state

### ISSUE THREAD

**Issue by jmg-duarte** [FStarLang/FStar#2624]
The VSCode extension repo has been archived (https://github.com/artagnon/vsfstar), which would imply it's unmaintained. 
The wiki should reflect this. https://github.com/FStarLang/FStar/wiki/Editor-support-for-F*

**Comment by nikswamy** [comment]
Thanks, I've updated the wiki page. It would be great to revive the VS code extension for F*. @kant2002 has been working on updates to the LSP support in F* which caters to this scenario (among others). So, maybe we'll recover VSCode support sometime soon.
