### ISSUE TITLE
Refinement of function references fails to give a precise enough type

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#264]
F* is currently not able to give refinements to function references.

Here is an example of what I would like to do : 

```
open Heap
open ST

logic type ref_identity (f:ref (nat -> Tot nat)) (h:heap) =
    (contains h f /\ (forall (n:nat). (sel h f) n = n))  // Say that f points to the identity
``` 
But F* does not infer a general enough type : 
```
Error
Too many arguments to function of type (heap -> (ref a) -> Tot a); got (sel h f n)
```

NB : while that is not fixed it can be worked around with a let binding.

Thanks

**Comment by vkanne-msft** [comment]
Seems to be problem still 

Too many arguments to function of type (_:FStar.Heap.heap -> _:(FStar.Heap.ref a@1) -> Tot a@2); got 3 arguments

**Comment by s-zanella** [comment]
Cannot reproduce with `--universes`. 
@vkanne-msft: I checked in a file with the example above. Can you confirm this was fixed?

**Comment by vkanne-msft** [comment]
Works for me too. Closing the issue.
