### ISSUE TITLE
Cannot export Platform.Bytes.fst to FSharp

### ISSUE THREAD

**Issue by kant2002** [FStarLang/FStar#2649]
During exportation of Platform.Bytes.fst 
```
Program.fst(154,0-154,8): (Error 72) Identifier not found: [abstract]
```

https://github.com/FStarLang/FStar/blob/24211ccf485befdbec44457889fb597b035602c4/examples/bytes/Platform.Bytes.fst#L154

Command line (regular one in examples)
```
fstar.exe --warn_error -271 --odir extracted --codegen FSharp  Platform.Bytes.fst --extract "+Platform.Bytes"
```

**Comment by aseemr** [comment]
The directory is not part of our CI, so it has regressed. There is also `ucontrib/Platform`, that I think supersedes the bytes implementation here. I have deleted the directory.

See `examples/Makefile` for examples that are actually maintained and are part of our CI.

(`abstract` used to be an F* keyword, that was removed a while back!)
