### ISSUE TITLE
Unexpected error when "rec" is forgot in mutually recursive functions

### ISSUE THREAD

**Issue by SimonForest** [FStarLang/FStar#265]
This code : 

```
module Test

let f x = x
and g x = x
```

makes F\* stop and return the following message : 

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("impossible")
```

Putting a "rec" after the first "let" solve the problem. So it should just be a syntax error but F\* fails on it.

**Comment by catalin-hritcu** [comment]
This is still happening, only thing that changed is the capitalization of `Impossible`
```
[hritcu@detained pub]$ fstar.exe examples/bug-reports/bug265.fst
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible")
```

**Comment by nikswamy** [comment]
@kyoDralliam can this just be ruled out by the parser?

**Comment by msprotz** [comment]
why does it have to be a syntax error? `let and` is useful for non-recursive things, e.g.

```
let a = a + b
and b = a - b in
```

**Comment by nikswamy** [comment]
what? I don't get it

**Comment by kyoDralliam** [comment]
Could be possible to enforce it in the parser but I agree with @msprotz that elaborating it to a serie of let binding would be a nice alternative

**Comment by nikswamy** [comment]
I find the syntax of @protz's example extremely confusing. He had to explain it to me in person and I've never personally used that syntax in OCaml. In the original error report, the missing `rec` was indeed the problem. I would prefer to insist that `and` can only being used with `let rec`, although concrete syntax is a matter of taste.
