### ISSUE TITLE
Exportation failed

### ISSUE THREAD

**Issue by kant2002** [FStarLang/FStar#2661]
Seems to be this part is not implemented, but in GC.fst
https://github.com/FStarLang/FStar/blob/5bcd16865e5161ccbc7b2b9ead96ba099618adf8/examples/algorithms/GC.fst#L99-L100

Produce in OCaml
```ocaml
let (get : unit -> gc_state) =
  fun uu___ -> failwith "Not yet implemented:get"
let (set : gc_state -> unit) = fun g -> failwith "Not yet implemented:set"
```
and in F#
```fsharp
let get : unit  ->  gc_state = (fun ( uu___  :  unit ) -> (failwith "Not yet implemented:get"))
let set : gc_state  ->  unit = (fun ( g  :  gc_state ) -> (failwith "Not yet implemented:set"))
```

I'm not sure why is that, because it's `assumed` or for other reasons?

**Comment by nikswamy** [comment]
This is meant to be an example proof rather than executable code. As such, it assumes primitives to get and set the state which cannot be extracted or executed.

**Comment by kant2002** [comment]
@nikswamy does that mean that error message should be changed. “Not implemented” in this case more like “not exportable”. If this constructs are can never to be exported, seems to be I understand why, since they are “purely fictional”, then maybe just changing message is enough. Because I thought that this is compiler issue and something not implemented there. From your explanation I understand that nothing to export I first place. Can you reopen? Maybe I itch changed title
