### ISSUE TITLE
assert by normalize

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#267]
```
let rotValues : l:(list (n:nat{n<32}))
 =
[7; 12; 17; 22;     5; 9; 14; 20;    4; 11; 16; 23;    6; 10; 15; 21]

val lenthRotValue : unit -> Lemma (List.length rotValues = 16)
let lenthRotValue u = () (* F* does not get this *)
```

**Comment by catalin-hritcu** [comment]
This is a _feature_ not a bug. As already discussed in https://github.com/FStarLang/FStar/issues/200#issuecomment-92324688, without a limit on unrolling fixpoints the SMT solver would loop forever. You can increase the limit, but that can have a serious performance impact.

If you really need more efficient evaluation at verification time (as opposed to just extracting to OCaml and running things there) then on 20 April 2015 Nik was writing on fstar-priv-club about adding a `reduce` primitive:
> 4. Explicitly triggering computations in the type-checker
> (a) Should be able to prove this directly without calling SMT

     assert (reduce (quicksort (fun x y -> x < y) [3; 2; 1]) = [1; 2; 3])

I don't think that's implemented yet though.

**Comment by aa755msr** [comment]
Why can't F* fully normalize terms before giving them to the SMT solver?
If strong normalization holds in the pure fragment of F*, every pure term is guaranteed to eventually reach a normal form. Can one encode in the SMT solver the usual (e.g. in Coq) trick to only unfold recursive matches when the top-level structure of the discriminee is known?

**Comment by catalin-hritcu** [comment]
@nikswamy can probably answer this much better than I can. The only thing I'll say is that pure terms in F* are only weakly normalizing (under CBV) and only in a consistent environment.

**Comment by msprotz** [comment]
We have a more powerful normalizer in universes, so this is theoretically possible, but we have not exposed it to the user. We're considering `assert by normalize`.

**Comment by catalin-hritcu** [comment]
This is currently supported by `assert_norm`. For instance:
```
assert_norm (pow2 64 == 18446744073709551616)
```
