### ISSUE TITLE
No active-verification region in emacs

### ISSUE THREAD

**Issue by jaylorch** [FStarLang/FStar#2679]
Since updating to the latest F* release, I've noticed the following issue with the emacs plugin when using emacs for Windows.  Sometimes, it gets into a state where a prefix of the file is blue (verified) and the rest of it is purple (verification pending), but there's no pink region (verification ongoing). It stays in this situation indefinitely. This happens even for files with no corresponding .fsti file.

**Comment by nikswamy** [comment]
hi Jay, 

If you're able to reproduce this reliably, you could try to follow the instructions here to extract a replayable log from the interaction with emacs and see if we can isolate the problem (e.g., with F* itself hanging) independently of emacs.

https://github.com/FStarLang/FStar/wiki/Debugging-FStar#debugging-interactive-mode-specific-issues

**Comment by jaylorch** [comment]
I tried the technique outlined in https://github.com/FStarLang/FStar/wiki/Debugging-FStar#debugging-interactive-mode-specific-issues today, but the output didn't match. It seems like that debugging technique assumes that the F* file contents don't change during the debugging session. But I only see this issue after having changed the F* file contents in the editor.

**Comment by jaylorch** [comment]
I upgraded from emacs 27.1 to emacs 28.2, and the problem went away. So I guess that's the solution.
