### ISSUE TITLE
REQ: Predefined build-config variable that expands to the F* home directory

### ISSUE THREAD

**Issue by mlr-msft** [FStarLang/FStar#268]
REQ: Predefined build-config variable that expands to the F* home directory. e.g.

```
(*--build-config
    options:--admit_fsi Set;
    variables:LIB=$FSTAR/lib;
    variables:MATHS=../maths;
    other-files:$LIB/ext.fst $LIB/set.fsi $LIB/heap.fst  $LIB/list.fst stack.fst listset.fst
  --*)
```

RATIONALE:

I'm attempting to integrate syntax checking and build tools into VimFStar such as syntastic and vim-dispatch.

An obstacle to doing this, however, is being required to specify dependencies relative to the root directory of the F* installation.

For example, in `examples/low-level/misc.fst`, we currently see the following `build-config` declaration:

```
(*--build-config
    options:--admit_fsi Set;
    variables:LIB=../../lib;
    variables:MATHS=../maths;
    other-files:$LIB/ext.fst $LIB/set.fsi $LIB/heap.fst  $LIB/list.fst stack.fst listset.fst
  --*)
```

Claiming dependency in on files in `$LIB` (such as `$LIB/ext.fst`) works in this case because the `lib` directory is relative to the examples directory. This isn't the case for user programs, where there's no reasonable expectation of a single relative path that can connect the `lib` directory with source files that depend on it.

Currently, I deal with the issue in VimFStar by using a tool I wrote called jdepp (developed before `build-config` was available in F*). It works in a similar fashion except I can specify values for variables such as `$LIB` on the command line. e.g., when using jdepp, the equivaltent dependency declaration for ext.fst is:

```
//@requires "fstar:ext.fst"
```

The prefix `fstar:` is a substitution variable that I parameterize when I invoke the `jdepp` tool as a front-end to `fstar.exe`:

```
$ jdepp -a -Dfstar=$FSTAR_HOME/lib src/specs/seq.fst -- $FSTAR_HOME/fstar.exe
action: /opt/fstar/bin/fstar.exe /opt/fstar/lib/ext.fst src/specs/map.fst src/specs/seq.fst
```

In this manner, my source files do not need to be concerned with being in a specific location relative to the location of `fstar.exe`.

**Comment by markulf** [comment]
There seem to be two options for doing this: 
* Add the possibility to specify build variables at the fstar command line
* Read in some default variables from the shells environment

Of course one can always do both, but we should only add what we also want to maintain.

**Comment by mlr-msft** [comment]
I see option #1 as also being useful to provide the location of third-party libraries.

**Comment by nikswamy** [comment]
It's not quite what you ask for, but I am about to push support for a new "--include <path>" option. 

If you call `fstar --include_path p1 ... --include_path pn f.fst`

then, `F\*` will search for `f.fst` in the following paths in order

```
p1/f.fst 
...
pn/f.fst
./f.fst
$(FSTAR_HOME)/lib/f.fst
```

**Comment by mlr-msft** [comment]
that's awesome! thanks. :+1:
