### ISSUE TITLE
build conf-python-2-7 1.2 failed in MacOS

### ISSUE THREAD

**Issue by prpr2770** [FStarLang/FStar#2680]
While trying to install FStar using the following command
```
opam install fstar
```
in an environment using `ocaml-base-compiler-4.14.0`, I obtained the following error

```
#=== ERROR while compiling conf-python-2-7.1.2 ================================#
# context     2.1.1 | macos/x86_64 | ocaml-base-compiler.4.14.0 | https://opam.ocaml.org#06881a73
# path        ~/.opam/fstar/.opam-switch/build/conf-python-2-7.1.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build python2.7 test.py
# exit-code   71
# env-file    ~/.opam/log/conf-python-2-7-50274-4142d8.env
# output-file ~/.opam/log/conf-python-2-7-50274-4142d8.out
### output ###
# sandbox-exec: execvp() of 'python2.7' failed: No such file or directory



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build conf-python-2-7 1.2
```

While reviewing the processing steps  I obtained the following error
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
⬇ retrieved csexp.1.5.1  (cached)
[ERROR] The compilation of conf-python-2-7.1.2 failed at "python2.7 test.py".
```
Could you please provide some guidance on how I may resolve this error?

**Comment by tahina-pro** [comment]
Do you have Python 2.7 installed on your system? If not, you should install it, following https://www.python.org/downloads/release/python-2718/

**Comment by prpr2770** [comment]
I proceeded to first use `conda` to create an environment with `py2.7`. And then, I created an `opam switch` to handle the installations for F* using `opam install fstar`. This worked smoothly. Thank you for your help.

**Comment by chandradeepdey** [comment]
Had the same issue in Ubuntu 23.04. I tried using `conda` as well, but `conf-python-2-7` is hardcoded to depend on the system `python2.7` package on Ubuntu. I ended up creating a dummy package using `equivs`.

```
Section: misc
Package: python27-dummy
Provides: python2.7
```
