### ISSUE TITLE
C-interop?

### ISSUE THREAD

**Issue by haf** [FStarLang/FStar#269]
I'm thinking of writing a wrapper with F\* for libuv and use the session types to prove the states that the different concepts can take (TCP socket, Stream etc). Aiming to build a highly reliable TCP implementation for F# where all edge cases can be explicitly handled and/or FsCheck-tested.

Would this be tractable?

**Comment by catalin-hritcu** [comment]
I think the miTLF* folks are already linking against OpenSSL for their crypto, so yes C-interop seems possible. Maybe some of the miTLF* person can answer? @beurdouche @ad-l @markulf @karthikbhargavan @fournet @nikswamy

**Comment by haf** [comment]
@catalin-hritcu Do you mean miTLS? [code here](https://github.com/haf/miTLS/tree/master/src)

**Comment by catalin-hritcu** [comment]
Nope, the private miTLS* repo here: https://github.com/mitls (don't ask me why it's private, I have no clue)

**Comment by beurdouche** [comment]
Both miTLS-f7 and miTLS-fstar (miTLS*) repositories are supposed to be private right now for licensing issues and there was a human error when making them public on Github. Also we choose to distribute miTLS as releases for now (the next one possibly under Apache2) but at some point we might go public. 

Regarding the F* version of miTLS, yes we link against native libraries to get some primitives. We use a CoreCrypto module that include OCaml and F# wrappers to a CryptoProvider library like OpenSSL or BouncyCastle (exactly as in the f7 version) but provide an F* interface file that assumes those functions. When the code is stable and the licensing issues solved we we'll make a release.

**Comment by aa755** [comment]
One way is as follows:
1) write OCaml bindings for those C functions.
2) In F*, assume functions of same name and "similar" (techincally, pre-image of extraction) types as the OCaml functions defined above. If necessary, you can define these functions in a new effect, to enable reasoning about those C functions, and more importantly to prevent the C functions from being invoked in unintended ways. For example, you want to prevent a close on a socket that was never opened.
3) Extract to OCaml and link with the OCaml files in 1)

**Comment by catalin-hritcu** [comment]
I think it would be great to have some example code illustrating all this.

**Comment by aa755** [comment]
Based on Mike's suggestion, (I think) we are following this strategy for implementing stack-allocation. 
Once done, I'll be happy to comment on our experience and add code snippets illustrating each step.

**Comment by nikswamy** [comment]
I guess @haf is looking to use F\# and interop with C from there. Currently, our code generator only emits OCaml code. This should change by the end of this week---we will emit either F\# or OCaml depending on a flag. 

You will then want to use .NET native interop to call from the generated F\# to a C library. This is purely a matter of .NET hackery. There's no reason why F\* should not accommodate this scenario. 

Also, @haf: a verified/highly-tested implementation of TCP using a combination of F\* and F\# sounds very interesting and useful. I encourage you to pursue this line of work. We will be happy to provide you with guidance on how to make F\* work in this setting. It would also be very useful for us to figure out how to adapt F\* so that such scenarios are more easily supported.

**Comment by markulf** [comment]
It may also be interesting for you that the `CoreCrypto` code for miTLS was moved as a `contrib` library to `FStar/contrib`. It still is purely for `OCaml` extraction though.

But the idea is to have multiple subfolders in contributed libraries, e.g. `contrib/CoreCrypto/fst` for the FStar specification, `contrib/CoreCrypto/ml` for the OCaml implementation and in the future `contrib/CoreCrypto/fs` for F#. Other contrib libraries should follow a similar structure.

**Comment by catalin-hritcu** [comment]
Extraction to C is supported via KreMLin: https://github.com/FStarLang/kremlin
Interop between OCaml and C is achieved via the OCaml FFI, see this: https://arxiv.org/abs/1703.00053

**Comment by ysangkok** [comment]
@catalin-hritcu , how is the Low* paper related to OCaml? I thought OCaml is completely sidestepped if using Low*.  So I don't understand how that paper is explaining how to use OCaml FFI for calling C code, when not using Low*.

**Comment by catalin-hritcu** [comment]
You will have to read the paper to find out :)
