### ISSUE TITLE
Tutorial code names include section numbering

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#270]
As we reorder sections in the tutorial, the filenames of exercises desynchronize. A better solution might for instance allow specifying the actual filename and a filename that should be presented to the user separately.

Related questions are 
- should we add the exercises and their solutions to the regression tests? 
- should we include the files for exercise and solution directly from  $FSTAR_HOME/examples/?

**Comment by catalin-hritcu** [comment]
Agreed that maintaining the tutorial is a pain. I've sent out a literate programming proposal a while back. Seems like something to discus this August in Redmond. I have a ton of Madoko gripes to make :)

**Comment by markulf** [comment]
In the meantime we could do best effort changes to the Madoko macros and the PHP of the tutorial.

Having separate exercises and solution folders may be good for a school, but its a mess for maintenance. 

I would prefer a common folder, or Madoko controlled sub folders, as well as the possibility to separately specify the name of the file in the Server file-system and the Tutorial editor.

I am happy to develop something like that as a 'nice' web programming exercise for the weekend and test it on new examples, before we update the whole lot.

**Comment by catalin-hritcu** [comment]
I think there were some commits a week ago. Just curious: what's the status on this?

**Comment by markulf** [comment]
They should be working but are somewhat experimental, like the tutorial in general.

**Comment by vkanne-msft** [comment]
#565

**Comment by nikswamy** [comment]
The old tutorial is defunct (thought still accessible at fstar-lang.org/tutorial/old.php for archival reasons). We no longer plan to maintain it.
