### ISSUE TITLE
`(Warning 240) Admitting [...] without a definition` should be an error ?!!!

### ISSUE THREAD

**Issue by TWal** [FStarLang/FStar#2705]
I noticed this warning the build log of my project, and I'm very surprised?
I hoped my build succeeding would mean that all my code is correct and proved, but apparently this is not the case?

It would be nice if "warnings" that could lead to unsoundness were actually errors (like the top-level effect warning).

**Comment by mtzguido** [comment]
This was fixed by that PR. This one also helps when splices or syntax extensions are involved: https://github.com/FStarLang/FStar/pull/3330.
