### ISSUE TITLE
review all the files in ulib and remove anything that's not useful

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#271]
Many examples still use old libraries. We should port the examples one by one, and clearly mark the libraries as deprecated, so no one uses them for new verification projects. Should we have a `deprecated` folder in the `lib` folder, mirroring the `to_be_ported` folder in the `exercise` folder?
## Seq & Array

`Array.fst` defines `seq` and seems to be replaced by `Seq.fst` and `SeqProperties.fst` and is used in the following examples:

```
algorithms/downgrade.fst
algorithms/qsort_arr.fst 
bignum/eval_st.fst 
bug-reports/bug151.fst 
crypto/cert.fst
crypto/cnt-format.fst
crypto/encrypt.fst
crypto/encrypt2.fst
crypto/encrypt3.fst
crypto/hybrid.fst
crypto/hybrid2.fst
crypto/rpc2.fst
to_be_ported/misc/ringbuffer.fst
to_be_ported/monadic/sparseArray0-1.fst
to_be_ported/monadic/sparseArray0.fst
to_be_ported/sep/rbsep.fst
to_be_ported/sep/rbsep.fst
to_be_ported/sep/rbsep2.fst
to_be_ported/sep/rbsep2.fst
unit-tests/certsig.fst
unit-tests/mac2.fst
```

I finished off a few:
~~crypto/acls-cap.fst~~
~~crypto/format.fst~~
~~crypto/mac.fst~~
~~crypto/mac3.fst~~
~~crypto/padding.fst~~
~~crypto/rpc.fst~~
~~crypto/sig.fst~~

`partialmap.fst` defines modules `Set`, `Map`, `Heap`, `Array` and appears in 

```
crypto/cnt-format.fst
```
## Bytes

`bytes.fst` defines type 'bytes', examples in `examples/crypt` define `type bytes=seq byte`. 
`src/basic/bytes.fst` defines `bytes` in a module `Microsoft.FStar.Bytes` using `array`.
miTLS-fstar has its own bytes library using `seq`.

**Comment by beurdouche** [comment]
I suggest maybe we could associate a status info to each file to know wether it is
- Stable
- InConstruction (or whatever...)
- Deprecated

Then we can review the deprecated one, check that everything has been ported to the new one and cleanup when ready.

**Comment by markulf** [comment]
Sounds like a good idea. Should we agree on the syntax of this metadata, even if we don't have a java-doc like tool to process it?

**Comment by catalin-hritcu** [comment]
Screw deprecation! We don't care about backwards compatibility! Just delete the libraries you think are no longer needed.

**Comment by nikswamy** [comment]
Strongly agree with Catalin. Delete old ones. Partialmap.fst, especially.

**Comment by msprotz** [comment]
in particular, `FStar.JS.fst` is no longer used, I think...

**Comment by markulf** [comment]
Nik suggested creating a new issue for F* Lib cleanup, but we should likely also revisit the status of this one.

**Comment by markulf** [comment]
For instance I am wondering whether we really need a `TwoLevelHeap` library? We could move it to `examples/` if it has didactic value?

**Comment by beurdouche** [comment]
There are probably a few things that should be removed like `FStar.Crypto.fst` but I think `ulib` is currently in a much better shape than `lib` was when we created the issue. To me documentation should have higher priority as we can remove or relocate files when documenting...
