### ISSUE TITLE
feature request: transitive dependencies in build-config

### ISSUE THREAD

**Issue by mlr-msft** [FStarLang/FStar#272]
It would be helpful if F* supported transitive dependency declarations in `build-config` specifications. The lack of this feature can cause large projects to become burdensome to manage and could be a source of friction to new-comers to the language.

Also, if F* were to support transitive dependencies, I think it also be helpful if F* had a command line flag that reports what transitive dependencies would be processed so that build tools (`make`, `rake`, et al) can better detect when rebuilds are necessary.

Thanks!

**Comment by catalin-hritcu** [comment]
+1

**Comment by beurdouche** [comment]
Also I think we can then generalise a "build-config" on top of each file, right ?

**Comment by mlr-msft** [comment]
Also, the current implementation of `build-config` searches the current directory relative to where `fstar.exe` is invoked from for declared dependencies (see #268). It seems that when the time comes to search for "dependency.fst" in ".", it should be relative to the source file that declares the given dependency instead.

I can work around this right now but I suspect it will need to be addressed before transitivity can implemented.

**Comment by markulf** [comment]
Another small 'bug' stumbled across:

```
options: ...
```

currently has to be a single line. Would be nice to support `\` as in Makefiles.

**Comment by mlr-msft** [comment]
FYI-- this is being worked on:

https://github.com/mlr-msft/FStar/commit/98a4030bc69a81b1aa91c8c35de9b8b4ba61dc3e

I still need to do some testing before I submit a pull request but the basic logic of this feature should be complete.

**Comment by catalin-hritcu** [comment]
I saw a recent commit about this (e8a09d4ab09ea3741885d5d044253ee4e4c0e5cb). Is this finished? How does one use it?

**Comment by mlr-msft** [comment]
This feature is finished but hasn't been used extensively yet, so there may still be problems. Here's a rundown of information that should be useful:

- Pass the `--auto_deps` argument to `fstar.exe` to interpret `build-config` headers transitively.
- Pass the `--find_deps` argument to `fstar.exe` to interpret `build-config` headers transitively and display a list of dependencies associated with any source files passed to `fstar.exe`. 
  - The list is `\n` delimited and should be able to be used to generate dependencies for a `Makefile`.
  - Paths will be absolute and should be considered good for one use only.
- If F* doesn't have a file name associated with the input (may not always be the case in interactive mode), transitive dependency searching is disabled, as there's no contextual directory to search from. The old dependency behavior is used.
- Editor extensions are likely to require some updates to work with transitive dependencies:
  - Editors should pass an absolute path to a filename and add `--find_deps` in order to make use of transitive dependency scanning. This hasn't been tested yet, unfortunately; I don't have much experience with any of the editor plugins yet.
  - If the editor environment doesn't provide a filename (e.g. scratch buffer), then there's no transitive dependencies. I noticed that in Atom, the filename is `<input>`, so transitive dependencies would be unavailable in this case. If we need to support this case, I'd need to modify the include path searching to disregard the "." case when there's no filename available for the input.
- Note that this is a temporary implementation of transitive dependencies, intended to help out until we can get something that scans for dependencies without the need to name them in `build-config` headers (like `ocamldep`).

**Comment by cpitclaudel** [comment]
I'll add emacs support; it should be easy. It would be great for testing purpose to have a test case that will only pass with proper support for this feature; maybe a zip with a few files?

**Comment by mlr-msft** [comment]
I can do that. 

Would you elaborate on how the test would work? I'm not clear on the specifics of what you're looking for.

I'll leave this issue open until it's done.

**Comment by cpitclaudel** [comment]
Thanks! Since I haven't touched F* very much, it would just be nice to have a small file/set of files that is expected to compile fine with transitive dependencies, but would fail in the current state of things. This way I'll know if my implementation is correct :)

**Comment by mlr-msft** [comment]
Oh, I understand now. I'd be happy to send you a test case. :smile:

I'll throw something together today and attach it to this issue.

**Comment by cpitclaudel** [comment]
I'm looking at this right now. How does it connect with the --in option?

**Comment by mlr-msft** [comment]
I haven't done any work related to the `--in` option; I'm still ignorant regarding how editors use interactive mode, unfortunately. I had planned on discovering this myself by updating VimFStar in my spare time but that is coming along slowly.

What do you think you need from me in order to make editor integration work? 

For example, do I need to change F* to allow you to name the input source? Internally, providing a name for the input source is an important precondition for F* to decide to use transitive dependencies. The `--in` option accepts no arguments, so it doesn't seem to permit that.

**Comment by cpitclaudel** [comment]
> For example, do I need to change F* to allow you to name the input source? Internally, providing a name for the input source is an important precondition for F* to decide to use transitive dependencies. The --in option accepts no arguments, so it doesn't seem to permit that. 

Yes, I expect so. At the moment I just call `fstar --in` to start the interactive toplevel. I could call `fstar --some-flag file-name` instead.

**Comment by mlr-msft** [comment]
I'll get to work on it. :smile:

**Comment by mlr-msft** [comment]
I think I've pushed the changes needed to make this work.

Instead of calling `fstar.exe --in`, you will now call `fstar.exe --auto_dep --in_context <path-name>`, where `<path-name>` is the file's path name. It's actually the directory the file resides in that's important, so if you pass an absolute path name to the source file, you're assured that F* will interpret the specified dependencies as intended.

Please let me know how it goes.

**Comment by s-zanella** [comment]
I'm missing a generated `FStar_Parser_Dep.ml` file in `src/ocaml-output` to build the OCaml binary:

```make[2]: *** No rule to make target 'FStar_Parser_Dep.cmx', needed by 'fstar.exe'.  Stop.```

**Comment by catalin-hritcu** [comment]
@s-zanella  Fixed now.

**Comment by s-zanella** [comment]
Thanks.
It'd be nice to modify the Makefile to re-generate the file.

**Comment by catalin-hritcu** [comment]
The `Makefile` (`make ocaml boot-ocaml`) does regenerate the file.
```
[hritcu@detained ocaml-output]$ make purge
rm -dfr fstar
rm -f .depend fstar.exe *.cmi *.cmx *.cmo *.o
rm -f prims.cmx FStar_ST.ml FStar_All.ml FStar_Option.ml FStar_List.ml FStar_Char.ml FStar_String.ml FStar_Util.ml FStar_Bytes.ml FStar_Getopt.ml FStar_Range.ml FStar_Platform.ml FStar_Unionfind.ml FStar_Parser_Util.cmx main.ml parse.mly parse.ml FStar_Parser_Parse.ml FStar_Parser_LexFStar.ml lex.mll FStar_Parser_ParseIt.ml FStar_Parser_Dep.ml
rm -f *.tar.gz *.zip
rm -f *.ml || true
[hritcu@detained ocaml-output]$ ls FStar_Parser_Dep*         
zsh: no matches found: FStar_Parser_Dep*
[hritcu@detained ocaml-output]$ cd ..
[hritcu@detained src]$ make ocaml boot-ocaml
[...]
[hritcu@detained src]$ ls ocaml-output/FStar_Parser_Dep*
ocaml-output/FStar_Parser_Dep.cmi  ocaml-output/FStar_Parser_Dep.cmx  ocaml-output/FStar_Parser_Dep.ml  ocaml-output/FStar_Parser_Dep.o

```

**Comment by s-zanella** [comment]
Brilliant. Thanks again.

**Comment by beurdouche** [comment]
`build-config` headers do not exist anymore and `auto-dep` works fine now.
Closing

**Comment by cpitclaudel** [comment]
Woops, this totally fell off my radar on the `fstar-mode` side. I still need to push an update, right?

**Comment by msprotz** [comment]
https://github.com/FStarLang/FStar/wiki/Dealing-with-F%E2%98%85-dependencies I documented the auto-deps feature extensively; I believe everything should still work "out of the box", but now there's a couple restrictions. You could conceivably do some pre-processing in the Emacs mode to give a friendlier error message (e.g. file has not yet been saved to disk; write your "opens" then save it?)

**Comment by cpitclaudel** [comment]
Ah, cool. Does this mean that https://github.com/FStarLang/fstar-mode.el/issues/28 isn't relevant anymore?
