### ISSUE TITLE
Unexpected error: Bound type variable not found

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#274]
Got the following error when trying to make `wf.fst` build again: 
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Bound type variable not found: aa")
```
Saving this for later study.

**Comment by vkanne-msft** [comment]
hitting an error

$ fstar --universes bug274.fst
D:\Sources\FStar\examples\bug-reports\bug274.fst(4,11-4,13) : Error
Inconsistent implicit argument annotation on argument aa#53

**Comment by catalin-hritcu** [comment]
This does not occur with universes. Closing.
