### ISSUE TITLE
Issue with quantifying over types

### ISSUE THREAD

**Issue by jaylorch** [FStarLang/FStar#2755]
This wasn't a problem with release 2022.08.10, but it is an issue with release 2022.11.07.  When there's a quantification over types, it causes problems with verification:

```
open FStar.FiniteSet.Base

let simple_fact (a: Type) =
  forall (l: list a). true

(* Unless you comment this `let` out, verification of `trivial` fails. *)
let all_simple_facts =
  forall (a: Type). simple_fact a

let trivial (s: set int) : Lemma (cardinality s = 0 || cardinality s >= 1) =
  ()
```

**Comment by jaylorch** [comment]
I find I can simplify the example even further:

```
let simple_fact (a: Type) =
  forall (l: list a). true

(* Unless you comment this `let` out, verification of `trivial` fails. *)
let all_simple_facts =
  forall (a: Type). simple_fact a

let trivial (n: nat) : Lemma (n = 0 || n >= 1) =
  ()
```

**Comment by aseemr** [comment]
Hi @jaylorch, I had a look at it. Some observations:

* `#set-options --z3rlimit 20` before `trivial` works.
* Adding a pattern to `all_simple_facts` also works:

```
let all_simple_facts =
  ∀ (a: Type).{:pattern simple_fact a} simple_fact a

let trivial (s: set ℤ) : Lemma (cardinality s = 0 ‖ cardinality s ≥ 1) =
  ()
```
* With no patterns and no rlimit tweak, in the smt encoding of `all_simple_facts`, we emit an axiom of the form `assert (phi <==> forall (a:Type). simple_fact a)` (omitting some details), with the unguarded `forall`. If I comment that axiom, then also the smt query works.

Other than this, I did not notice anything fishy. The query looks as expected.

**Comment by jaylorch** [comment]
Ah, thanks! So the issue is a missing pattern on the quantifier.

Now, to fix the real problem that I reduced to this issue:  that ulib/FStar.FiniteMap.Base.fsti's `all_finite_set_facts` is missing such a pattern. I talked to @nikswamy about this, and he thinks that FiniteMap and FiniteSet can be updated to use patterns yet still quantify over all types in all universes.
