### ISSUE TITLE
Two copies of support.ml checked in ... which one should I remove?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#276]
```
[hritcu@detained pub]$ find . -name support.ml
./src/support/ocaml/fstar-lib/src/support.ml
./src/ocaml-output/support.ml
```

**Comment by markulf** [comment]
This is a more general issue: 

```
$ find . -name Bytes.ml
./mitls-fstar/libs/fst/Platform/Bytes.ml
./mitls-fstar/libs/ml/CoreCrypto/Bytes.ml
./mitls-fstar/libs/ml/Platform/Bytes.ml
```
None of which are actually used, as `Platform` is implemented in `platform.ml`.

**Comment by jkzinzindohoue** [comment]
The version of `support.ml` in `src/support/ocaml/fstar-lib/src/support.ml` looks outdated.

**Comment by markulf** [comment]
I was also using 
```./src/ocaml-output/support.ml```

A more general question, how much of `./src/support/ocaml/fstar-lib/` is still alive, what depends on it?
