### ISSUE TITLE
Command-line argument --timing ignored

### ISSUE THREAD

**Issue by jaylorch** [FStarLang/FStar#2768]
The usage message emitted by the `--help` command-line argument says:

```
  --timing  Print the time it takes to verify each top-level definition
```

But adding `--timing` to the command line doesn't seem to do anything.

**Comment by mtzguido** [comment]
Hi Jay. Sorry, this seems to have regressed. One way to get this behavior now is to do something like this:
```
./bin/fstar.exe --profile_component FStar.TypeChecker.Tc.process_one_decl --profile Test --profile_group_by_decl Test.fst
```
where `Test` is your module. The profiler is much more expressive, but an easy `--timing` would be good. I will make a PR soon.

**Comment by jaylorch** [comment]
Thanks, @mtzguido, that's quite helpful!
