### ISSUE TITLE
Shouldn't extract lemmas and ghost things in general

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#277]
We had issues extracting RPC to OCaml because it uses some assumed lemmas, and those uses get compiled down to calls in OCaml, but then there is nothing to link against because they are just assumed. Needed to remove the assume and instead admit their body ...

In general, we shouldn't extract lemmas and ghost things.

**Comment by markulf** [comment]
Thanks, pragmatically, we should have unit-tests for .fst files with .ml implementations to catch the addition of unimplemented functions.

**Comment by nikswamy** [comment]
Yes, this is very much among the things we are addressing in --codegen
OCaml-experimental
