### ISSUE TITLE
suspicious syntax error in lemma

### ISSUE THREAD

**Issue by fmrl** [FStarLang/FStar#280]
i've run into a syntax error that i suspect isn't right. the following error:

`tesseract.fst(28,24-28,24): Syntax error`

is produced by the following code:

```
val __tesseract_effect_log_recursion:
  log: Effects._log_g 'state 'step
  -> Lemma
     (ensures True)
     (decreases (Seq.length log))
let rec __tesseract_effect_log_recursion log =
  let length = Seq.length log in
     if 0 = length then
        ()
     else
        __tesseract_effect_log_recursion (Seq.slice log 0 (length - 1))
```

the reason i'm distrustful is i have a similar lemma in another file that verifies:

```
val __region_event_log_recursion:
  log: Effects._log_g 'state 'step
  -> Lemma
     (ensures True)
     (decreases (Seq.length log))
let rec __region_event_log_recursion log =
  let length = Seq.length log in
     if 1 >= length then
        ()
     else
        __region_event_log_recursion (Seq.slice log 0 (length - 1))
```

given the inconsistency, i didn't think it worthwhile to simplify the code that reproduces the problem. instead, you can find a repro branch of my project [here](https://github.com/fmrl/tesseract/tree/bug-repro-00). i have added instructions to the README. my apologies that i don't have anything simpler.

thanks in advance.

**Comment by catalin-hritcu** [comment]
This is a very strange parsing problem. Adding a (spurious) parenthesis around `True` in `(ensures True)` as follows:
```
         (ensures (True))
```
makes this work again. This seems the same problem as in #252, and it seems it was introduced around Jun 3.
