### ISSUE TITLE
Argument `--report_assumes error` doesn't permit simple types

### ISSUE THREAD

**Issue by jaylorch** [FStarLang/FStar#2801]
The following code generates the following error when run with the command-line argument with `--report_assumes error`:

```
module Test68

type t =
  | T: (n: nat) -> t
```

```
(Error 335) Admitting a top-level assumption t__uu___haseq
Verified module: Test68
1 error was reported (see above)
```

**Comment by mtzguido** [comment]
Hi Jay, thanks for the report. Indeed this is quite silly, pushing a fix soon to not raise a warning/error about internally-added axioms. However `--report_assumes` is still not great since it won't report an `assume val`, but getting that to work is a bit tricky due to interfaces. Just a heads up.
