### ISSUE TITLE
Tactic `compute` doesn't work with dependent tuples

### ISSUE THREAD

**Issue by jaylorch** [FStarLang/FStar#2819]
The following trivial request of the normalizer fails, when it seems easy enough to compute. This suggests the `compute` tactic doesn't deal well with dependent tuple types. Is this fundamental, or can this be fixed or worked around?

```
module Test69

let t: ((v: nat) & nat) = (| 0, 0 |)

let lem () : Lemma (True) =
  let (| x, y |) = t in
  assert (x == 0) by (FStar.Tactics.compute(); FStar.Tactics.trivial ())
```

Output:
```
test69.fst(7,2-7,8): (Error 228) user tactic failed: `uncaught exception: FStar.Tactics.Derived.Goal_not_trivial` (see also FStar.Tactics.Derived.fst(98,2-100,31))
1 error was reported (see above)
```

**Comment by nikswamy** [comment]
hi Jay, 

This is because the goal sees something like `x:nat, y:nat, _:squash ((| x, y |) == t) |- x == 0` so it's not trivial by computation.

This version works:

```
module Test69

let t: ((v: ℕ) & ℕ) = (| 0, 0 |)

[@@expect_failure]
let lem () : Lemma (⊤) =
  let (| x, y |) = t in
  assert (x == 0) by (FStar.Tactics.compute(); FStar.Tactics.trivial ())


let lem () : Lemma (⊤) =
  assert (let (| x, y |) = t in
           x==0) by FStar.Tactics.(compute(); trivial ())
```

because now the assert reduces by computation to `0 == 0`

**Comment by jaylorch** [comment]
Ah, thanks, good to know.
