### ISSUE TITLE
What's the LSP status?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [FStarLang/FStar#2823]
Hey there.

Is there some public checklist of what's available in F*? I'm a nvim user and trying to get it work. I [ported](https://github.com/WhiteBlackGoose/VimFStar) the existing vim plugin to python3, however, [cannot](https://github.com/FStarLang/VimFStar/issues/22) get interactive verification to work. Also it doesn't look like the server provides completions, but I may be wrong.

I also tried attaching the LSP server (`fstar.exe --lsp`) manually, but also can't find anything that it would do.

**Comment by gruhn** [comment]
Same here. LSP is just an HTTP server, right? If I run `fstar.exe --lsp` I don't even see a server running when I check `netstat -tnlp`.

**Comment by aseemr** [comment]
We have a vscode extension for F* here: https://github.com/FStarLang/fstar-vscode-assistant. The LSP server support in the typechecker itself is not maintained anymore. Closing this issue, please reopen if you have more questions.

**Comment by WhiteBlackGoose** [comment]
Sad, thanks for the info
