### ISSUE TITLE
Refinement subtyping with opaque term

### ISSUE THREAD

**Issue by Sup3Legacy** [FStarLang/FStar#2842]
I stumbled upon an issue where a type refined by an `opaque` predicate would fail to coerce to the base type, when wrapped in an inductive type.

Here is a small example:

```fstar
type my_wrapper (a: Type) =
    | S: a -> my_wrapper a

[@@"opaque_to_smt"]
let cond (n: nat -> bool)=
    n

let cond_func (n: nat)=
    true

let my_nat = 
    n:nat{cond cond_func n}

let my_func (n: my_wrapper nat): my_wrapper nat=
    n

assume val a: my_wrapper my_nat

(* Fails to typecheck *)
let _ = my_func a
```

This fails to typecheck with following error message:

```shell
Subtyping check failed; expected type Test.my_wrapper Prims.nat; got type Test.my_wrapper Test.my_nat; The SMT solver could not prove the query.
```

The source however correctly typechecks if I either:

- remove the `opaque_to_smt` tag
- use `nat`/`my_nat` instead of the `my_wrapper`-wrapped variants
- manually inline the refinement like that

```fstar
[@@"opaque_to_smt"]
let cond (n: nat): bool)=
    true

let my_nat = 
    n:nat{cond n}
```

I am not sure whether this is an expected behaviour.

**Comment by Sup3Legacy** [comment]
I just noticed the issue is simpler than that; following snippet doesn't typecheck:

```fstar
type even = n:nat{n % 2 = 0}

assume val b: option even

let _: option nat = b
```

I guess refinement subtyping doesn't happen when the types in question are arguments to a type constructor, unless it can be proven that the refinement is a tautology?

**Comment by nikswamy** [comment]
F* does not support subtyping beneath an inductive type constructor.

> https://github.com/FStarLang/FStar/issues/65#issuecomment-1067239774

This is an often-requested feature. But, supporting it requires more research.
You can coerce an `option even` to an `option nat` by mapping it with an `even -> nat` (identity) coercion.
