### ISSUE TITLE
notifications on broken builds

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#285]
Can I sign up to be notified if my push breaks the build at
https://www.fstar-lang.org:3443/fstarlang/fstar/ ?

**Comment by nikswamy** [comment]
notifications would be good, but we really shouldn't count on notifications to check that a push didn't break the build. Run 'make -C src test' before pushing.

**Comment by aa755msr** [comment]
I can't run make -C src test on my phone, yet.

**Comment by nikswamy** [comment]
but you're pushing from your phone?

**Comment by aa755msr** [comment]
Sometimes, e.g. https://github.com/FStarLang/FStar/commit/6deaca05c0c64947e33c95d5982e134ab01c947a

**Comment by nikswamy** [comment]
don't push from a device on which you cannot test. it's simple.

**Comment by aa755msr** [comment]
Is it?
https://github.com/FStarLang/FStar/commit/03630dc1f1c025ba676ecc604eea478eaf3a6095#diff-471b8499b494bb70885f8ddce5a4583cR31

**Comment by nikswamy** [comment]
I'm not saying that I have never broken the build. I have never committed from a device on which I cannot test.

**Comment by catalin-hritcu** [comment]
Notifications on broken builds would indeed be useful and could be sent directly to fstar-priv-repo@lists.gforge.inria.fr. Who's the admin for the Strider project? @ad-l? Can Nik and me also get added please?

**Comment by markulf** [comment]
Admin for Strider is a bit funny. It sends invitation emails that never arrive. Maybe same reason why I (we?) don't get too many build notifications. I can add you manually to Strider, and hopefully you can help improve the situation.

**Comment by s-zanella** [comment]
We are tracking the issue with Strider SMTP configuration in #317.
I do get e-mail notifications from Travis for builds triggered by my commits, so this issue is resolved.
