### ISSUE TITLE
Package documentation as HTML instead of Markdown + Makefile

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#286]
Remark from the industry =)

**Comment by catalin-hritcu** [comment]
Packing happens in the `package` target of the `Makefile` in `src/ocaml-output/`. Here is the command responsible for the tutorial:
```
	cd ../.. && git archive --format=tar --prefix=doc/tutorial/ HEAD:doc/tutorial/ | tar -x -C src/ocaml-output/fstar
```
We would need to replace this with a command that builds the tutorial and than packages the whole thing. Patches from industry welcome ;)

**Comment by catalin-hritcu** [comment]
Or alternatively, keep this command but then run `make` in the exported tutorial. This would have the advantage of not packaging uncommited files (if any).
