### ISSUE TITLE
Time for a ulib/FStar.Printables 

### ISSUE THREAD

**Issue by briangmilnes** [FStarLang/FStar#2872]
Folks, working through the tutorial, heck I wrote one, and Nik agreed that is past time.
Would someone like to review this one and add data types and modify as needed?
Note: I made sequences print with a "<>" but have taken no other liberties.
[Printable.fst.txt](https://github.com/FStarLang/FStar/files/11150822/Printable.fst.txt)

**Comment by mtzguido** [comment]
Hi Brian, thanks for this. The reason we hadn't yet added such a module is due to all the dependencies it would have-- maybe you want to print strings, but this makes you bring all machine integer types into scope. The other alternative is defining the class higher up in the dependency tree, and then each module defines its own instance, but this pushes the tactics module itself very high up, and makes pretty much every file depend on it.

That said... while we were indecisive, I see no reason not to add this module which is totally opt-in. I did have a few fixes though, here's my changes (I kept your authorship): [FStar.Printable.fst.txt](https://github.com/FStarLang/FStar/files/11253552/FStar.Printable.fst.txt)

Could you please open a PR for it?

**Comment by briangmilnes** [comment]
Guido,

 Thanks! You answered one question, how do I get refinement types print.
That was a nuisance in my setup.

 However, I'm a stuck on setting up a pull. I have one with tutorial typos
for Nik. When I go to github, it won't
let my user id ***@***.***) set one up. Do I need permissions
or do I branch the whole system
as Github suggests?

 Thanks, Brian

**Comment by mtzguido** [comment]
Yes, just create a fork of your own, and freely push there. Then you can open a PR from it to this repo.

**Comment by briangmilnes** [comment]
Before I would check in for the first time, I thought I'd do the SE standard and write some test code mostly to find my
mental bugs. 

The attached raises the small issue of the U*IntN to_strings are mostly not implemented, should we keep the Printables?

At the top of the file are five issues. First (to_string -1) won't type right but (to_string letboundminusone) does. 
Then a to_string of a string can't be proven by compute to be that string.
And it can't prove sequence prints by compute either. Both of which would be nice for test code for
parsers and such (I have yet to see how everparse tests, but it proves, so it's really a user expectation and
development thing).
[TestPrintable.fst.txt](https://github.com/FStarLang/FStar/files/11276549/TestPrintable.fst.txt)

 Any suggestions?

**Comment by briangmilnes** [comment]
It's the map. 
``
module ProveConcat
open FStar.Tactics
open FStar.Seq
open Printable

let _ = assert (("a"^"b") = "ab")

let l = ["a";"b"]
let _ = assert ((FStar.String.concat "" l) = "ab") by compute()
let _ = assert ((FStar.String.concat ";" l) = "a;b") by compute()


let s = seq_of_list [0;1]

let _ = assert(to_string 0 = "0") by compute()

let _ = assert (id 0 = 0)

(* Is it the seq_to_list ?*)


let l' = [0;1]
let l2s2l = (seq_to_list (seq_of_list l'))

let _ = assert(l2s2l = l') by compute()

(* So it's really the map. *)

[@@ expect_failure [19]]
let _ = assert ((List.Tot.map id (Seq.seq_to_list s)) = [0;1]) by compute()

[@@ expect_failure [19]]
let _ = assert ((List.Tot.map to_string (Seq.seq_to_list s)) = ["0";"1"]) by compute()

[@@ expect_failure [19]]
let _ = assert ((map_seq (fun x -> "") s) = (seq_of_list ["";""])) by compute()

 With both the list map and the seq map.

**Comment by briangmilnes** [comment]
Or
[@@"opaque_to_smt"]
let rec seq_of_list (#a:Type) (l:list a) : Tot (s:seq a{L.length l = length s})  =
  match l with
  | [] -> Seq.empty #a
  | hd::tl -> create 1 hd @| seq_of_list tl

is the problem. This is in there to avoid performance problems?
Any obvious (to you) workarounds? 

It's fun, this is not terribly important.

**Comment by briangmilnes** [comment]
Ah, I get it, after much fun playing around. Lists are first class with a literal. So compute() can reduce them and the
asserts on them work. But sequences are second class so functions like seq_of_list stop evaluation. And it's
marked opaque.

Leaving only these questions:

[@@ expect_failure [189]]
let printable_int_test_minus_1_no_let_bug = assert((to_string -1) = "-1") by compute()

(* Yet this works. *)
let mone : int = -1 
let printable_int_test_minus_1_no_let = assert((to_string mone) = "-1") by compute()

[@@ expect_failure [19]]
let printable_string_test1     = assert(to_string "1" == "1") by compute()

 Then I can check in.

 Should I also check in the test code? Is anything documented on how test is setup? The wiki's only test page
is not relevant.

**Comment by briangmilnes** [comment]
let printable_string_test1 = assert(to_string "1" == "1") is
quoting of strings.

So only the -1 issue.

**Comment by briangmilnes** [comment]
let printable_int_test_minus_1 = assert((to_string (-1 <: int)) = "-1") by compute() works with a type ascription, so what
the heck does the literal -1 type to by default?

So I'll check in when I know when and if to include the test code.

**Comment by nikswamy** [comment]
hi Brian, `to_string -1` is parsed as `(to_string) - (1)`. You need to write `to_string (-1)`. This is the same convention as in languages like OCaml.

That expect_failure 189 would have produced the error message "(Error 189) Expected expression of type "int"; got expression "to_string" of type "_: int -> string"

**Comment by briangmilnes** [comment]
Printables in a fork, branch milnes-printables. But the wiki is way the
heck out of date with the makefiles/test stuff.
 And each test setup is external with different code. So I wrote a trivial
Makefile to do a verifications passed test
 in tests/printable.

 According to github I need write permission to make a pull request. Can
you confirm that and add me?

**Comment by mtzguido** [comment]
Hi Brian, I don't see the that branch in your repo (it's [this repo,](https://github.com/briangmilnes/FStar-1) right?)

As for requiring permissions, that really should not be the case. Once your branch is on github you can just go here https://github.com/briangmilnes/FStar-1/branches and you should see a button to make a PR from it.

What you mention about Seq being opaque is correct. While these functions will run in extracted code, neither the SMT nor normalizer know about them in order to write these tests. It's fine to skip this for now.

**Comment by briangmilnes** [comment]
Guido,

 I always find the Github docs vague. Then one goes to some other random
site and get a second
opinion that's way different.

 So I should push this public (somehow) to mine then do a pull. Have a link?

 I'll give it a try.

 Know any good examples of making an exception and raising it?

 Thanks, Brian

**Comment by briangmilnes** [comment]
Guido,

 After 20 minutes reading some long winded screed about the history of
github, you should
have a pull request!

Thanks, Brian
