### ISSUE TITLE
Bug with a sequence subtyping when a lemma and an assert both prove the property

### ISSUE THREAD

**Issue by briangmilnes** [FStarLang/FStar#2874]
Folks,
 I'm new so I might have missed something, but the return here can not prove the
subtyping on my sequence in this simple set an element of an array go 1 example.
So I proved a lemma showing the subtyping and checked an assert and they
both prove, but the subtyping still does not.

Any ideas? I have other proving versions.
(* Proves the lemma, asserts the postcondition for the return and still
 can't get the postcondition. *)

module BugSeqSubtyping

open FStar.Seq

let rec ones_prefix (howmanyzeros : nat) (a : seq int{howmanyzeros <= length a}) =
 if howmanyzeros = 0 then true
 else if (index a 0) <> 1 then false 
 else ones_prefix (howmanyzeros - 1) (slice a 1 (length a))

let rec lemma_index_upd (i: nat) (s :seq int{i < length s}) (v : int) :
  Lemma (requires ones_prefix i s)
        (ensures  ones_prefix (i+1) (upd s i 1))
        (decreases (length s))
= if i = 0 then ()
  else if i = 1 then ()
  else 
   let s' = (slice s 1 (length s)) in
    lemma_index_upd (i - 1) s' v

//#push-options "--fuel 4 --ifuel 10 --query_stats --log_queries --z3rlimit_factor 2 --split_queries"
// #restart-solver
let
 forloopup_body (i: nat) (a: seq int{i < length a /\ ones_prefix i a}) :
  Tot (a' : seq int{ones_prefix (i+1) a'})
= let a' = upd a i 1 in
   lemma_index_upd i a 1;
   assert(ones_prefix (i+1) a' /\ i+1 <= length a');
    a'

///home/milnes/third-party/fstar/bin/fstar.exe /home/milnes/fstar/CRLS/experiments/Iteration/BugSeqSubtyping.fst --smt /home/milnes/third-party/fstar/bin/z3 --include ///home/milnes/third-party/fstar/ucontrib/Platform/fst --print_universes --print_implicits
///home/milnes/fstar/CRLS/experiments/Iteration/BugSeqSubtyping.fst(27,38-27,40): (Error 19) Subtyping check failed; expected type a: FStar.Seq.Base.seq u#0 Prims.int //{Prims.b2t (i + 1 <= FStar.Seq.Base.length u#0 #Prims.int a)}; got type FStar.Seq.Base.seq u#0 Prims.int; The SMT solver could not prove the query. Use --query_stats for //more details. (see also /home/milnes/fstar/CRLS/experiments/Iteration/BugSeqSubtyping.fst(8,54-8,78))
//Verified module: BugSeqSubtyping
//1 error was reported (see above)

**Comment by nikswamy** [comment]
Hi Brian, 

Here's a version of your code that works:

```fstar
module BM

open FStar.Seq

let rec ones_prefix (howmanyzeros: nat) (a: seq int {howmanyzeros <= length a}) =
  if howmanyzeros = 0
  then true
  else if (index a 0) <> 1 then false else ones_prefix (howmanyzeros - 1) (slice a 1 (length a))

let rec lemma_index_upd (i: nat) (s: seq int {i < length s}) (v: int)
    : Lemma (requires ones_prefix i s)
      (ensures ones_prefix (i + 1) (upd s i 1))
      (decreases (length s)) =
  if i = 0
  then ()
  else
    if i = 1
    then ()
    else
      let s' = (slice s 1 (length s)) in
      lemma_index_upd (i - 1) s' v

let forloopup_body (i: nat) (a: seq int {i < length a /\ ones_prefix i a})
    : Tot (a': seq int {length a == length a' /\ ones_prefix (i + 1) a'}) =
  let a' = upd a i 1 in
  lemma_index_upd i a 1;
  assert (ones_prefix (i + 1) a' /\ i + 1 <= length a');
  a'
```

In your example, F* fails to typecheck the code pointing to the occurrence of `a'` in the refinement `ones_prefix (i + 1) a'`

```
Subtyping check failed; expected type a: seq int {i + 1 <= length a}; got type seq int; The SMT solver could not prove the query. Use --query_stats for more details. (See related location: <input>:5:53)
```

i.e., F* is complaining that it couldn't prove the precondition of `ones_prefix` on `a'`, it has nothing to do with the definition of the function. E.g., even this fails:

```
let forloopup_body (i: nat) (a: seq int {i < length a /\ ones_prefix i a})
    : Tot (a': seq int {ones_prefix (i + 1) a'}) = admit()
```

So, you need to enrich the type so that the refinement formula is itself well-typed. The way I did it was to add a conjunct to say that the `length a == length a'`.

Hope that helps.

**Comment by briangmilnes** [comment]
Thanks Nik, tried that in an assert and F*+Z3 knew it but it has to be in the Tot refinement.
