### ISSUE TITLE
Simple assertion causes Type Error with dependent pairs

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#293]
The program
```
val test : (a:int & b:int{a=b}) ->(unit*unit) -> Tot unit
let test (|a, b|) ((),()) =  assert(a = b)
```
causes the error 
```
dpairs.fst(4,9-4,17): Subtyping check failed; expected type (DTuple2 int (fun a -> int)); got type (DTuple2 int (fun a -> b:int{(a = b)}))
```

**Comment by nikswamy** [comment]
I see your stumbling on bugs related to type inference with dependent tuples. The reports are much appreciated. 

It you're blocked waiting for fixes, I suggest (temporarily) moving to using your own dependent sums at specific types. For example, you could write:

```
type dpint (a:int) (p:(a -> Type)) : Type =
   | MkDPInt: x:a -> p x -> dpint a p
```
and use this type instead. ... just as a temporary workaround. 

Thanks for the reports ... sorry for the bugs.

**Comment by ngrimm** [comment]
Thanks for proposing this workaround.
In case anyone is facing similar problems: 
The proposed code did not directly work, but I modified and could then use it as intended:
```
type dpint (p:(int -> Type)) : Type =
   | MkDPInt: a:int -> b:p a-> dpint p

type eq_int = dpint (fun x -> i:int{x=i})
val test: unit -> Tot eq_int
let test () = MkDPInt 0 0
val test2 : eq_int -> Tot unit
let test2 d = let a = MkDPInt.a d in
              let b = MkDPInt.b d in 
              assert(a = b)
```

**Comment by ngrimm** [comment]
Also (probably related to #203) using aliases for the projectors of the form
```
let fst_dpint = MkDPInt.a
let snd_dpint = MkDPInt.b
```
causes tying errors.

**Comment by s-zanella** [comment]
This has been fixed with universes.
