### ISSUE TITLE
OPAM for windows

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#294]
I have been playing with compiling OPAM both using Cygwin and MSYS / MINGW32.

Cygwin:

`make install` fails because the resulting executables have a `.exe` suffix. 

MSYS:

I run into an old but not too well documented problem with flexdll during linking: 

```
let get_output1 ?use_bash cmd = 
    List.hd (get_output ?use_bash cmd) 
```
This function isn't happy when invoked on something that produces an empty list as in the following code snippet from the [`flexdll`](https://github.com/alainfrisch/flexdll/blob/71c819ebb397d81f65e74dbb549a081e8519631d/reloc.ml#L1059) GitHub:

```get_output1 (!gcc ^ " -print-sysroot") ^ "/mingw/lib";```

Unfortunately `gcc -print-sysroot` in MSYS seems to do exactly that.

The error message is `** Fatal error: hd`.

**Comment by markulf** [comment]
See https://github.com/ocaml/opam/issues/246

**Comment by markulf** [comment]
I made some more progress in Cygwin, but `opam init` was acting up at least in Cygwin64.

**Comment by markulf** [comment]
The best starting point seems to be https://github.com/dra27/opam/tree/windows.

**Comment by beurdouche** [comment]
I think I did read somewhere (don’t remember where…) that this is gonna be merged in the OPAM master branch relatively soon right ?

**Comment by msprotz** [comment]
Last time I chatted with David Allsop (dra27) this wasn't quite ready to be merged. But this was a couple months ago, maybe the situation has improved.

**Comment by msprotz** [comment]
Closing this since I now distribute opam for windows along with the installer + an fstar opam package.
