### ISSUE TITLE
Non-thunked Ghosts

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#296]
I cannot remove the dummy unit argument in:
https://github.com/FStarLang/FStar/blob/cd7474186ad473038d59ac09968f16ba3cccc8e5/examples/extraction/ghostTest.fst#L20 (this is the same example as the one in #295 )

I wanted to write it as follows:
val aSizedList  : sizedList
let aSizedList = let h2 = (hide 2) in MkSList h2 [1]

Ghosts have no effects. So, why is the additional unit is needed?
For example, it was not needed here:
https://github.com/FStarLang/FStar/blob/cd7474186ad473038d59ac09968f16ba3cccc8e5/examples/extraction/ghostTest.fst#L14 (just 6 lines above)

**Comment by nikswamy** [comment]
Using computationally irrelevant terms *is* an effect. 
Consider: 

```
val x : erased nat

val y : nat
let y = reveal x
```

This program is not sound. The definition of `y` has a ghost effect that is incorrectly forgotten. How would we compile y, given that x is erased to a unit?

Note, you cannot write:

```
val y: GTot nat
```

Computation types like `GTot nat` are not types.

Hence, you must write:

```
val y : unit -> GTot nat
let y () = reveal x
```

**Comment by aa755msr** [comment]
I agree. However, I have a related confusion.
How does F* determine that the following is not ok
    ```val aSizedList : sizedList```
but, the following is ok:
    ```val aSizedListNG :  sizedListNonGhost```
Do types carry some kind of a ghostness qualifier? I don't remember any such thing in the F* AST.

More importantly, why is sizedList a ghost type? Because it uses reveal only in a pattern that is only visible to the SMT solver, I think it does not suffer from the issues you mentioned above.

Definitions of sizedList and sizedListNonGhost can be found in:
https://github.com/FStarLang/FStar/blob/cd7474186ad473038d59ac09968f16ba3cccc8e5/examples/extraction/ghostTest.fst

**Comment by nikswamy** [comment]
There are no qualifiers on types.

We infer a Ghost effect for the definition. At the top level, we do not allow the Ghost effect.

**Comment by aa755msr** [comment]
So, I think it is suboptimal to infer a ghost effect for aSizedList:
type sizedList =
| MkSList: maxsize:(ghost nat)->  cont:(list int){length cont < (reveal maxsize)} -> sizedList

**Comment by nikswamy** [comment]
It boils down to the type of hide. As discussed, this will now be in Tot.
