### ISSUE TITLE
reserved names in OCaml

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#297]
OCaml does not like variable names such as ' new:
https://github.com/FStarLang/FStar/blob/99fe091c23909035c8ec3d801f99acdde917f597/examples/low-level/sieve.fst#L96
Extraction should automatically rename such variables. Is there a master list of such "reserved names" in OCaml?
Does the old extraction have code that can be reused for this purpose?

**Comment by mtzguido** [comment]
This seems better now, there is indeed a table for OCaml reserved names in `FStar.Extraction.ML.Syntax`, and it is used:
```
$ cat X.fst
module X
let initializer = 22

$ cat X.ml
open Prims
let initializer_: Prims.int = Prims.parse_int "22"
```
but Tahina has a recent commit working around this, because it's apparently not used for **types**.
```
$ cat X.fst 
module X
type struct = int

$ cat X.ml
open Prims
type struct = Prims.int[@@deriving show]
```
Will take a look later.

**Comment by s-zanella** [comment]
We ran into the same problem with @tomsib2001 with an inductive named `sig`.

**Comment by mtzguido** [comment]
I semi-fixed this one. It now matches the behaviour for usual names, but they might clash.

```
$ cat B.fst 
module B

let struct = 1
let struct_ = 2

type initializer = unit
type initializer_ = int
```
```
$ cat B.ml
open Prims
let struct_: Prims.int = Prims.parse_int "1"
let struct_: Prims.int = Prims.parse_int "2"
type initializer_ = Prims.unit[@@deriving show]
type initializer_ = Prims.int[@@deriving show]
```
This is bad, but it was already the case for `let`s so it's an improvement.

There's also #310, which probably tracks this issue better, so closing and moving there.
