### ISSUE TITLE
GTot functions in lemmas

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#298]
I would like to use GTot functions `f` in lemmas, which is not possible right now because GHOST and PURE effects are not compatible.
What would be the proper way to do that ?
I would like that `f` function to be erased by the backend but still be able to use it in proofs.

**Comment by aa755msr** [comment]
I made `hide` a pure function:
https://github.com/FStarLang/FStar/commit/6e440d07f89b25558ad8aeedbffb282e93240ce7 
The idea that the only way you can use a hidden thing is by using reveal. But you can use reveal only in a ghost context. So, there is no need to require even `hide` to be in a ghost context.

Now, you can rewrite your f to have pure effect, but produce a hidden value.
I'll try to post a concrete example.

**Comment by jkzinzindohoue** [comment]
I do not see those elif functions, were they commited ?

Also my issue is that I want to define a recursive function like

````
val id : int -> Tot int
let id x =
    match x with
    | 0 -> x
    | _ -> 1 + id (x-1)
````
Because of the recursive call, if I return an `erased int` I also have to reveal it, which leads to a computed `GTot` effect rather than a `Tot` effect.
 The function can probably be rewritten with an accumulator to make it work, but that means that existing specs have to be rewritten throuhoutly.

Since the new extraction no longer accepts the "erase" function, it makes it quite hard for me to switch to the new backend.

**Comment by aa755msr** [comment]
https://github.com/FStarLang/FStar/blob/master/lib/ghost.fst#L44

Going by the analogy of Coq's Prop, I think it is safe to remain in Pure effect as long as we return a hidden value. So, we should add a combinator to lib/ghost.fst that lets you define your I'd to have type (erased int) -> Tot (erased int)

**Comment by vkanne-msft** [comment]
Ghost functions that return non-informative types are promoted to PURE. This should now be possible today.
