### ISSUE TITLE
incorrect inferred type in case of effect abbreviations

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#299]
(I discussed this issue with Nik on last Friday)

For example, there is an incorrect magic in the extract of scopedWhile:
https://github.com/FStarLang/FStar/blob/master/examples/low-level/sstCombinators.fst#L79 :

```
let rec scopedWhile = (fun ( wg ) ( mods ) ( bd ) -> (match ((wg ())) with
| true -> begin
(let _12_77 = (withNewScope () (Obj.magic bd))
in (scopedWhile wg () bd))
end
| false -> begin
()
end))
```
This magic is because type of bd is incorrectly provided to the extraction function as unit -> SST 'loopInv _ _, instead of unit -> SST unit _ _.

**Comment by mtzguido** [comment]
Couldn't repro because of the stale code, and some simple tests work. Further I think this was fixed at some point while fixing #1072, since I remember a similar issue. So, I err on the side of closing this one :)
