### ISSUE TITLE
Bad OCaml generated for pair match

### ISSUE THREAD

**Issue by briangmilnes** [FStarLang/FStar#2993]
drop Makefile Main.fst and AssocList.fst 
into F* 2023.04.08~dev
platform=Linux_x86_64
compiler=OCaml 4.13.1
date=2023-05-01 14:34:42 -0300
commit=f7869aea1d1bd5ae53eeaa926adf96f162d8e5a6
make all
and OCaml compilation will 
cd OCaml; dune build --profile release
File "bin/AssocList.ml", line 9, characters 14-64:
9 |           if (FStar_Pervasives_Native.__proj__Mktuple2__item___1 hd) = k'
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value FStar_Pervasives_Native.__proj__Mktuple2__item___1
Hint: Did you mean __proj__Mktuple12__item___1, __proj__Mktuple3__item___1, __proj__Mktuple4__item___1, __proj__Mktuple5__item___1, __proj__Mktuple6__item___1, __proj__Mktuple7__item___1, __proj__Mktuple8__item___1 or __proj__Mktuple9__item___1?

The files were attached as *.fst.txt. 
[AssocList.fst.txt](https://github.com/FStarLang/FStar/files/12074604/AssocList.fst.txt)
[Main.fst.txt](https://github.com/FStarLang/FStar/files/12074605/Main.fst.txt)
[Makefile.txt](https://github.com/FStarLang/FStar/files/12074606/Makefile.txt)

**Comment by mtzguido** [comment]
Hi Brian, this should be fixed by #2994. We happened to notice it around the exact time you posted this! :)
