### ISSUE TITLE
Old OCaml backend no longer ignores admited modules

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#302]
The OCaml backend used to ignore the admited fsi modules, or the fsi modules in general. It no longer does, which means that among others code using `seq.fsi` can no longer be extracted as it crashes the backend with a `unsupported: not-an-ML-kind`.

Could this behavior be restored for the old backend ?

**Comment by markulf** [comment]
Delete old backend and close this issue?

**Comment by jkzinzindohoue** [comment]
The old backend will be removed.
