### ISSUE TITLE
interaction between erasure and refinement

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#304]
(*--build-config
variables:LIB=../../lib;
other-files: $LIB/ghost.fst
  --*)

module GhostRefinement
open Ghost

val consHd : (a:Type) -> (l:(list a){is_Cons l}) -> Tot a
let consHd (a:Type) l = Cons.hd l
(* F* is happy*)

val ghostConsHd : (a:Type) -> (l:(erased (list a)){is_Cons (reveal l)}) -> Tot (erased a)
let ghostConsHd (a:Type) l = elift1 (consHd a) l

(*
 F* is unhappy :
<input>(4,36-4,46): Subtyping check failed; expected type ((list a) -> Tot a); got type (l:l:(list a){(is_Cons l)} -> Tot a)
#fail
*)

**Comment by aa755msr** [comment]
The following works now:

val ghostConsHd : (a:Type) -> (l:(erased (list a)){is_Cons (reveal l)}) -> Tot (erased a)
let ghostConsHd (a:Type) l = elift1_p #_ #_ #(fun l -> (b2t (is_Cons l))) (consHd a) l

Unfortunately, many implicit arguments have to be manually provided.

**Comment by nikswamy** [comment]
This should be fixed now. I have added a similar test to the end of unit1.fst in the regression suite.
