### ISSUE TITLE
the projector of aref (hetero refs) does not typecheck in OCaml

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#305]
(However, no one is using this projector)

type aref =
  | Ref : #a:Type -> r:ref a -> aref

(the original source is at : https://github.com/FStarLang/FStar/blob/1205caabc51f37cf26f3ac8930b170e5779ff437/lib/heap.fst#L7)

The current extract is:

let ___Ref___r = (fun ( projectee ) -> (match (projectee) with
| Ref (_4_4) -> begin
(Obj.magic _4_4)
end))

**Comment by nikswamy** [comment]
Ok, the magic is expected. 
I guess we're missing adding the unit for the type argument 'a'
