### ISSUE TITLE
dangerous name collision after renaming

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#310]
The extract of 

`type capture (a:Type) 'a = 'a*a`

is 

```
type (' a, 'a) capture =
('a * ' a)
```

https://github.com/FStarLang/FStar/commit/72104b586a62067378a7b9baa3e1caed82bbdead

**Comment by aa755msr** [comment]
Nik suggested emitting (cryptic) realnames to OCaml. Realnames are guaranteed to contain distinct numbers and hence adding/removing a tick shouldn't matter.

Another solution could be to make sure that the functions used to extend the context with a local binding can check current collection of OCaml bound vars and fail if the OCaml name being added already exists. The error message should contain the F* location of the error.

If it is always the case that such collisions cause compilation errors in OCaml, it might be fine to procrastinate on this issue.

**Comment by markulf** [comment]
There is some value in keeping the OCaml code readable, though that may be just wishful thinking on my side.

**Comment by mtzguido** [comment]
Current example:
```
$ cat X.fst 
module X
type capture (a:Type) 'Aa = 'Aa*a

$ cat X.ml
open Prims
type ('Aa,'Aa) capture = ('Aa,'Aa) FStar_Pervasives_Native.tuple2
```

**Comment by mtzguido** [comment]
Another worrying clash:
```
$ cat B.fst 
module B

let struct = 1
let struct_ = 2

type initializer = unit
type initializer_ = int
```
```
$ cat B.ml
open Prims
let struct_: Prims.int = Prims.parse_int "1"
let struct_: Prims.int = Prims.parse_int "2"
type initializer_ = Prims.unit[@@deriving show]
type initializer_ = Prims.int[@@deriving show]
```

**Comment by mtzguido** [comment]
Another worrying clash:
```
$ cat B.fst 
module B

let struct = 1
let struct_ = 2

type initializer = unit
type initializer_ = int
```
```
$ cat B.ml
open Prims
let struct_: Prims.int = Prims.parse_int "1"
let struct_: Prims.int = Prims.parse_int "2"
type initializer_ = Prims.unit[@@deriving show]
type initializer_ = Prims.int[@@deriving show]
```

**Comment by msprotz** [comment]
If I recall correctly, there is a very limited notion of lexical environment in the OCaml code-generation -- the initial intent of the extraction was to reuse the lexical structure of F\* on the basis that both being lexically scoped, there was no need to re-do name disambiguation.

This assumption is broken by keyword-avoidance, but also by inline_let's, e.g.
```
let x = 0 in
[@inline_let] let y = x in
let x = 2 in
(y, x)
```

↑ this would previously print (x, x), until disambiguation code was added to the OCaml printer to make sure no two local let's in the same scope have the same name. This results in ugly x0, x1, x2, and also makes it harder for kremlin to infer which variables could be updated in-place (a long-standing feature request in kremlin).

**Comment by s-zanella** [comment]
Someone hit this bug again in [Zulip](https://fstar.zulipchat.com/#narrow/stream/184683-questions-and.20help/topic/Implementing.20Modular.20multiplicative.20inverse/near/178937685).

Here's a minimized example:
```FStar
val r: unit -> a:Type -> f:(a -> a) -> int
let r _ _ _ = 0

val g: int -> int -> int
let g _ _ = 0

val ko: int -> int 
let ko a =
  let a = a in
  r () int (g a)
```
The OCaml extraction of the last function captures `a` in `g a`:
```OCaml
let (ko : Prims.int -> Prims.int) =
  fun a -> let a1 = a in r () () (fun a1 -> (Obj.magic (g a1)) a1)
```

**Comment by mtzguido** [comment]
I'm marking this for the v1 release, it's serious. See also #1783.

**Comment by nikswamy** [comment]
Looking into this.

For the record, the last example now produces:

```
open Prims
let (r : unit -> unit -> (Obj.t -> Obj.t) -> Prims.int) =
  fun uu____430  -> fun uu____431  -> fun uu____432  -> Prims.int_zero 
let (g : Prims.int -> Prims.int -> Prims.int) =
  fun uu____450  -> fun uu____451  -> Prims.int_zero 
let (ko : Prims.int -> Prims.int) =
  fun a  -> let a1 = a  in r () () (fun a21  -> (Obj.magic (g a1)) a21) 
```

Which looks correct to me. 

Note, `g a1` gets magic'd since the `r` cannot be given a polymorphic type after translation to ML (it's not prenex quantified).

I'm not yet sure why why it also gets eta-expanded.

**Comment by mtzguido** [comment]
>I'm not yet sure why why it also gets eta-expanded.

See `maybe_eta_expand` in `FStar.Extraction.ML.Term` and this commit 21d544ce001a4ea4183199f32fefd99d1c1139f8

**Comment by nikswamy** [comment]
Just clarifying @protz's remark above for my understanding: https://github.com/FStarLang/FStar/issues/310#issuecomment-506758900

Since 69bde008419a9361bccad52ce522fef4cc20d12a (Jonathan's work in 2017) we generate local names in the ML AST that are unique for a scope to avoid name capture. This is part of FStar.Extraction.ML.UEnv. The actual printing of OCaml terms (in FStar.Extraction.ML.Code) is (correctly) unaware of any of these scope or name capture isseus.

**Comment by nikswamy** [comment]
FYI, while we for the most part produce names that are unique in a scope, several utility functions bypass the protections that are in place and generate names in an ad hoc fashion. I plan to revise name generation in the extraction pipeline to all go through the single mechanism used in extend_bv to extend a scope with a name that is fresh in that scope.

**Comment by nikswamy** [comment]
FYI, my previous post about `ko` being extracted correctly was just a coincidence. Name capture due to eta expansion is still possible in master. For example, this program

```
module Bug310
val r: unit -> a:Type -> f:(a -> a) -> int
let r _ _ _ = 0

val g: int -> int -> int
let g _ _ = 0

val ko: int -> Tot int
let ko a =
  let a21 = a in
  r () int (g a21)
```

Extracts incorrectly to

```
let (ko : Prims.int -> Prims.int) =
  fun a  -> let a21 = a  in r () () (fun a21  -> (Obj.magic (g a21)) a21) 
```

However, with the fix in nik_310, this now produces

```
let (ko : Prims.int -> Prims.int) =
  fun a  ->
    let a21 = a  in r () () (fun uu____545  -> (Obj.magic (g a21)) uu____545)
```

**Comment by nikswamy** [comment]
See https://github.com/FStarLang/FStar/blob/master/tests/bug-reports/Bug310.fst
and https://github.com/FStarLang/FStar/blob/master/tests/bug-reports/Bug310.ml.expected
