### ISSUE TITLE
Make rpc example extract properly with codegen OCaml

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#314]
The rpc example doesn't currently extract properly with `codegen OCaml-experimental`. I've made a list of problems below, hopefully someone familiar with this (@aa755 ?) can look at them in more detail.

The current output looks like this:
```
[hritcu@detained crypto]$ make rpc-ml 
../../bin/fstar.exe  --z3timeout 10 --prims ../../lib/prims.fst --verify_module Formatting --verify_module SHA1 --verify_module MAC --verify_module RPC --admit_fsi Seq  \
          ../../lib/ext.fst ../../lib/classical.fst ../../lib/set.fsi ../../lib/set.fst ../../lib/heap.fst ../../lib/st.fst ../../lib/all.fst ../../lib/string.fst ../../lib/io.fst ../../lib/list.fst ../../lib/seq.fst ../../lib/seqproperties.fst \
				../../contrib/Platform/fst/Bytes.fst ../../contrib/CoreCrypto/fst/CoreCrypto.fst \
				sha1.fst mac.fst formatting.fst rpc.fst  \
				--codegen-lib Platform --codegen-lib CoreCrypto --codegen OCaml-experimental
extracting: Prims
extracting: FunctionalExtensionality
extracting: Classical
extracting: Set
extracting: Set
extracting: Heap
extracting: ST
extracting: All
extracting: String
extracting: IO
extracting: List
extracting: Seq
extracting: SeqProperties
extracting: Platform.Bytes
extracting: CoreCrypto
extracting: SHA1
extracting: MAC
extracting: Formatting
extracting: RPC
Gen Code: FunctionalExtensionality
Gen Code: Classical
Gen Code: Set
Gen Code: Heap
Gen Code: ST
Gen Code: All
Gen Code: String
Gen Code: IO
Gen Code: List
Gen Code: Seq
Gen Code: SeqProperties
Gen Code: Platform_Bytes
Gen Code: CoreCrypto
Gen Code: SHA1
Gen Code: MAC
Gen Code: Formatting
Gen Code: RPC
Verified module: SHA1
Verified module: MAC
Verified module: Formatting
Verified module: RPC
All verification conditions discharged successfully
ocamlfind ocamlopt -cc "gcc-5" -cclib -L/usr/lib  -cclib -lcrypto -o rpc.exe -package batteries -linkpkg -g -thread -I ../../contrib/Platform/ml -I ../../contrib/CoreCrypto/ml -I \
        ../../src/ocaml-output/ \
				../../src/ocaml-output/support.ml \
				../../contrib/Platform/ml/platform.cmx ../../contrib/CoreCrypto/ml/CoreCrypto.cmxa \
				Seq.ml SeqProperties.ml SHA1.ml MAC.ml Formatting.ml RPC.ml
File "../../src/ocaml-output/support.ml", line 48, characters 4-5:
Warning 11: this match case is unused.
File "../../src/ocaml-output/support.ml", line 60, characters 4-5:
Warning 11: this match case is unused.
File "Seq.ml", line 31, characters 52-53:
Warning 20: this argument will not be used by the function.
File "Seq.ml", line 9, characters 2-3:
Warning 11: this match case is unused.
File "SHA1.ml", line 12, characters 0-26:
Error: The type constructor Platform.Bytes.lbytes expects 0 argument(s),
       but is here applied to 1 argument(s)
Makefile:83: recipe for target 'rpc-ml' failed
make: *** [rpc-ml] Error 2
```
1) It seems that `type key = lbytes keysize` in `sha1.fst` gets extracted to `type key = unit Platform.Bytes.lbytes`. Removing the (apparently) spurious `unit` makes this error go away.

Once this is fixed the next problem is this:
```
[hritcu@detained crypto]$ ocamlfind ocamlopt -cc "gcc-5" -cclib -L/usr/lib  -cclib -lcrypto -o rpc.exe -package batteries -linkpkg -g -thread -I ../../contrib/Platform/ml -I ../../contrib/CoreCrypto/ml -I \
>         ../../src/ocaml-output/ \
>                               ../../src/ocaml-output/support.ml \
>                               ../../contrib/Platform/ml/platform.cmx ../../contrib/CoreCrypto/ml/CoreCrypto.cmxa \
>                               Seq.ml SeqProperties.ml SHA1.ml MAC.ml Formatting.ml RPC.ml
File "../../src/ocaml-output/support.ml", line 48, characters 4-5:
Warning 11: this match case is unused.
File "../../src/ocaml-output/support.ml", line 60, characters 4-5:
Warning 11: this match case is unused.
File "Seq.ml", line 31, characters 52-53:
Warning 20: this argument will not be used by the function.
File "Seq.ml", line 9, characters 2-3:
Warning 11: this match case is unused.
File "MAC.ml", line 50, characters 4-25:
Error: Unbound value Support.Prims.is_Some
Hint: Did you mean is_Cons?
```
2) The closest I could find to `Support.Prims.is_Some` is `Support.Option.isSome`. Once I rename it in MAC.ml I get the next error:
```
[hritcu@detained crypto]$ ocamlfind ocamlopt -cc "gcc-5" -cclib -L/usr/lib  -cclib -lcrypto -o rpc.exe -package batteries -linkpkg -g -thread -I ../../contrib/Platform/ml -I ../../contrib/CoreCrypto/ml -I \
        ../../src/ocaml-output/ \
                                ../../src/ocaml-output/support.ml \
                                ../../contrib/Platform/ml/platform.cmx ../../contrib/CoreCrypto/ml/CoreCrypto.cmxa \
                                Seq.ml SeqProperties.ml SHA1.ml MAC.ml Formatting.ml RPC.ml
File "../../src/ocaml-output/support.ml", line 48, characters 4-5:
Warning 11: this match case is unused.
File "../../src/ocaml-output/support.ml", line 60, characters 4-5:
Warning 11: this match case is unused.
File "Seq.ml", line 31, characters 52-53:
Warning 20: this argument will not be used by the function.
File "Seq.ml", line 9, characters 2-3:
Warning 11: this match case is unused.
File "MAC.ml", line 16, characters 2-3:
Warning 11: this match case is unused.
File "MAC.ml", line 44, characters 8-16:
Warning 26: unused variable verified.
File "Formatting.ml", line 6, characters 0-26:
Error: The type constructor Platform.Bytes.lbytes expects 0 argument(s),
       but is here applied to 1 argument(s)
```
3) Which I fixed again by removing the spurious unit. Finally, I got this:
```
[hritcu@detained crypto]$ ocamlfind ocamlopt -cc "gcc-5" -cclib -L/usr/lib  -cclib -lcrypto -o rpc.exe -package batteries -linkpkg -g -thread -I ../../contrib/Platform/ml -I ../../contrib/CoreCrypto/ml -I \
        ../../src/ocaml-output/ \
                                ../../src/ocaml-output/support.ml \
                                ../../contrib/Platform/ml/platform.cmx ../../contrib/CoreCrypto/ml/CoreCrypto.cmxa \
                                Seq.ml SeqProperties.ml SHA1.ml MAC.ml Formatting.ml RPC.ml
File "../../src/ocaml-output/support.ml", line 48, characters 4-5:
Warning 11: this match case is unused.
File "../../src/ocaml-output/support.ml", line 60, characters 4-5:
Warning 11: this match case is unused.
File "Seq.ml", line 31, characters 52-53:
Warning 20: this argument will not be used by the function.
File "Seq.ml", line 9, characters 2-3:
Warning 11: this match case is unused.
File "MAC.ml", line 16, characters 2-3:
Warning 11: this match case is unused.
File "MAC.ml", line 44, characters 8-16:
Warning 26: unused variable verified.
File "RPC.ml", line 20, characters 35-50:
Error: Unbound type constructor l__Request
```
The offending generated code looks as follows:
```
type ' msg reqresp =
((string, (unit Support.Prims.b2t, unit l__Request) Support.Prims.l_and) Support.Prims.l__Exists, (string, (string, (unit Support.Prims.b2t, (unit, unit) l__Response) Support.Prims.l_and) Support.Prims.l__Exists) Support.Prims.l__Exists) Support.Prims.l_or
```
and corresponds to the following type definition in F*:
```
opaque logic type reqresp (msg:message) =
    (exists s.   msg = Formatting.request s    /\ Request s)
 \/ (exists s t. msg = Formatting.response s t /\ Response s t)
```
4) This is really a logical formula used only in refinements and shouldn't be extracted at all. Commenting it out in the generated ml file makes the whole thing work:
```
[hritcu@detained crypto]$ ocamlfind ocamlopt -cc "gcc" -cclib -L/usr/lib  -cclib -lcrypto -o rpc.exe -package batteries -linkpkg -g -thread -I ../../contrib/Platform/ml -I ../../contrib/CoreCrypto/ml -I \
>         ../../src/ocaml-output/ \
>                               ../../src/ocaml-output/support.ml \
>                               ../../contrib/Platform/ml/platform.cmx ../../contrib/CoreCrypto/ml/CoreCrypto.cmxa \
>                               Seq.ml SeqProperties.ml SHA1.ml MAC.ml Formatting.ml RPC.ml
File "../../src/ocaml-output/support.ml", line 48, characters 4-5:
Warning 11: this match case is unused.
File "../../src/ocaml-output/support.ml", line 60, characters 4-5:
Warning 11: this match case is unused.
File "Seq.ml", line 31, characters 52-53:
Warning 20: this argument will not be used by the function.
File "Seq.ml", line 9, characters 2-3:
Warning 11: this match case is unused.
File "MAC.ml", line 16, characters 2-3:
Warning 11: this match case is unused.
File "MAC.ml", line 44, characters 8-16:
Warning 26: unused variable verified.
```

**Comment by aa755msr** [comment]
I have updated your issue to enumerate all concerns, so that I can easily reference them here.
1) The unit is not spurious. The type constructor ``lbytes`` takes an integer argument in F*. That argument is erased to unit, because OCaml types cannot depend on terms.  On my computer, I get the following error:
```` Error: Unbound module Platform ````
Perhaps Platform.ml was manually written and needs to be updated.

As long as all the ML code is extracted from F*, extracts should compile and run with "expected" results. When compiling with manually written OCaml code, care must be taken to ensure that the manual implementation has the same OCaml type as the original F* extract.

**Comment by catalin-hritcu** [comment]
About the `Error: Unbound module Platform`, have you run `make` in `contrib/Platform/ml` already? You should do that for `contrib/CoreCrypto/ml` too (and report back if you have troubles with it).

About 2, maybe @nikswamy can confirm whether there are constraints that make us redefine so many things in prims.

**Comment by aa755msr** [comment]
$ make
ocamlopt -c -cc i686-w64-mingw32-gcc -ccopt '-I /usr/local/lib/ocaml' -ccopt "-I ../../../../openssl-1.0.1p/include" -ccopt -fPIC -cclib -lcrypto -cclib -c openssl_stub.c
openssl_stub.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* -------------------------------------------------------------------- */
 ^
openssl_stub.c:15:25: fatal error: openssl/err.h: No such file or directory
 #include <openssl/err.h>
                         ^

In any case, I don't think 1) and 3) have anything to do with extraction. 


About 2), I see the value of extracting Prims.option to the native option in OCaml. So Support.ml should be fixed to rename  Support.Option.isSome to Support.Option.is_Some, so that we stick to a consistent convention. If not, we can just copy  Support.Option.isSome to Support.Option.is_Some.


About 4), what does the `logic` qualifier indicate? can I not these types in regular computations?

**Comment by catalin-hritcu** [comment]
The -fPIC warning should be fixed by my latest commit. As for the `/usr/include/openssl/err.h` error, yes you need openssl to build this. @markulf can give you more details on how to get that working on Windows. I guess you'll also need to set the `-I ../../../../openssl-1.0.1p/include` part to something more generic, that's probably the path on markulf's machine.

**Comment by markulf** [comment]
I will assume for the time being that the `openssl` git project is cloned out in the same parent folder as `FStar`. Or that you unzipped openssl source to an `openssl` folder in that directory. We could think about using git sub-modules: http://www.git-scm.com/book/en/v2/Git-Tools-Submodules.

I created a reproducible bug in https://github.com/FStarLang/FStar/blob/master/examples/bug-reports/extraction-error1.fst. Run `make extraction-error1` in that folder. This should remove all dependencies on `FStar/contrib` and point you to what needs to be removed or added in the extraction.

**Comment by aa755msr** [comment]
extraction-error1.fst does not indicate any problem with extraction. It assumes a type `Request` and uses it in the definition of `reqresp`. Either you have to define `Request` in F*, or after extraction in OCaml. 
If you choose to define it in OCaml land, you have to define l__Request. This renaming occurs to meet OCaml's naming conventions.

**Comment by aa755msr** [comment]
https://github.com/FStarLang/FStar/commit/b3c3eeb3e85c0a3222f44d77c5380635244047fa

**Comment by markulf** [comment]
As a big of background, `Request` and `Response` simulate the way we used to model events in F7. I don't see how we could define them in OCaml land. 

We could probably define them in F* using an explicit ghost event log?

**Comment by catalin-hritcu** [comment]
In this particular case using an explicit ghost event log seems indeed like the less dangerous solution (assumes are indeed evil).

In general, I'm worried that extraction interacts very poorly with our monolithic `Type` kind that includes both types that are supposed to be extracted like `int` and types that can't be meaningfully be extracted, like `exists s. Request s`. I was thinking whether classifying such things with a kind `Prop` would solve this problem, but it seems this wouldn't really work if `Prop` was a subkind of `Type`, would it?

**Comment by aa755msr** [comment]
We have enough of Coq's Prop to serve the erasure needs.
See the type `erased` in lib/ghost.fst.
In PURE contexts, any type of the form `(erased _)`  gets extracted as `unit`
This is similar to Nuprl's and HoTT's squash type which has seemed enough for our(Nuprl group's) erasure needs.
I agree that the ghost library needs to be further developed to make this easy. We need erased version of the existential quantifier.

If I find time, I'll insert erased in extraction-error1.fst, and get it's extract to compile automatically.

**Comment by catalin-hritcu** [comment]
Just for comparison in Coq `nat` has sort `Set` and is properly extracted even if "promoted" to `Type`, which seems a bit strange (non-modular at least).

Things in `Prop` like `exists x : nat, True` are extracted to `Obj.t` in OCaml (again irrespective of whether they are promoted to `Type` or not).

**Comment by catalin-hritcu** [comment]
@aa755msr 
> We need erased version of the existential quantifier.

Indeed, all logical constants should be erased and that's the only version we should provide. I'm curious where exactly you'll add the erased for the logical constants and whether it really makes a difference.

**Comment by aa755msr** [comment]
I meant that we can *already define* an erased version of the existential quantifier using the `erased` type in lib/ghost.fst
Why complicate the theory which new primitives that are not needed.

**Comment by catalin-hritcu** [comment]
> I meant that we can already define an erased version of the existential quantifier using the erased type in lib/ghost.fst

Show me the code :)

> Why complicate the theory which new primitives that are not needed.

Indeed.

**Comment by aa755msr** [comment]
https://github.com/FStarLang/FStar/commit/086d4c8dc38170688abfebf9e32cfe2c3e4a9b46

**Comment by aa755msr** [comment]
To make existing libraries extract without changes, we can put erased in front of the definitions of logical connectives in lib/prims.fst
For example, the definition of `exists` can be changed from
````opaque type Exists (#a:Type) (p:a -> Type) = x:a & p x  ````
to 
````opaque type Exists (#a:Type) (p:a -> Type) = erased (x:a & p x) ````

https://github.com/FStarLang/FStar/blob/fd787d6d5c08750787bf8f7818f6c10b327e9bf4/lib/prims.fst#L47

Extraction uses these definitions (in prims.fst) and will comply with such erasure requests.
Also, because the above definition is opaque, noone is using the constructive interpretation of `exists`.

**Comment by nikswamy** [comment]
Yes, this will work currently.

However, I plan to remove the opaque qualifier there eventually.

As I remove it, I will make sure to retain the erasure semantics.

-Nik



Sent from my Windows Phone
________________________________

**Comment by catalin-hritcu** [comment]
Nik seems to somehow have fixed this, even part 4, but I can find no `erased` in the definition of the logical connectives. So what exactly is the current fix?

**Comment by catalin-hritcu** [comment]
Looking at commit db2398e (originally unreadable because of line ending change), 
```{patch}
--- extraction/extracttyp.fs    2015-08-29 19:27:19.117863438 -0700
+++ /home/hritcu/Temp/extracttyp.fs     2015-08-29 19:23:49.834539144 -0700
@@ -425,9 +425,9 @@
 (* \pi_1 of returned value is the exported constant*)
 let rec extractSigElt (c:context) (s:sigelt) : context * list<mlmodule1> =
     match s with
-    | Sig_typ_abbrev (l,bs,_,t,_,_) ->
+    | Sig_typ_abbrev (l,bs,_,t,quals,_) ->
         let c, tds = extractTypeAbbrev c ({abTyName=l; abTyBinders=bs; abBody=t}) in
-        (c, [MLM_Ty [tds]])
+        (c, (if quals |> List.contains Logic then [] else [MLM_Ty [tds]]))
 
     | Sig_bundle(sigs, [ExceptionConstructor], _, _) ->
         let _, _, exConstrs = parseInductiveTypesFromSigBundle c sigs in
```
it seems that Nik's using the `logic` qualifier to decide which type definitions to extract and which not. Abhishek already has an example showing that this is **unsound**: https://github.com/FStarLang/FStar/commit/b3c3eeb3e85c0a3222f44d77c5380635244047fa

**Comment by nikswamy** [comment]
I agree that erasure of `logic type` is not guaranteed to produce well-typed Ocaml code. 

But, this example, with its used of assumed type constructors, is not really complete anyway. 

As a stop gap, you can mark type constructors for erasure as 'logic'. Just as with 'assume', you do this at your own risk. The risk is somewhat slighter however: if you mistakenly use a type marked as `logic` in a concrete context, the resulting code will fail to type-check in OCaml. In contrast, if you use `assume`, all bets are off---you code could happily compile and run and do strange things.

**Comment by markulf** [comment]
Likely a bug was still lurking, even though the test wend through: https://github.com/FStarLang/FStar/issues/371

**Comment by s-zanella** [comment]
I browsed through rpc.fst and its dependencies and couldn't find anything that would depend on equality in a non-logical context such that extracting it to structural equality would create a problem. It may be a good idea to introduce such a dependency in rpc.fst or some other extraction test that is run during regression.

**Comment by markulf** [comment]
@catalin-hritcu @s-zanella what's the status of this? Can we close it?
Tests run correctly. How did we resolve integer extraction? We verify with mathematical integers but extract using native int as --use_native_int is set? ok, as verification guarantees that there are no overflows?

**Comment by s-zanella** [comment]
I don't know if we verify that all integers computations are within bounds, probably not.
We extract with native integers and it runs, so fine to close this inasmuch as the issue in the title has been resolved.

**Comment by nikswamy** [comment]
I'm pretty sure we don't verify the absence of overflows. 

To do that, we'd have to use FStar.Int32 or a similar library, instead of using Prims.int.

**Comment by msprotz** [comment]
Alright, closing this. If you use --use_native_int, then the resulting code is unsound. If you're concerned with the soundness of the generated code re. integer overflows, just drop --use_native_int; we now use zarith that's supposedly pretty efficient as long as you stay within int63.
