### ISSUE TITLE
Can't compile contrib/CoreCrypto on 64bit Linux

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#315]
I'm having troubles compiling `contrib/CoreCrypto` on 64bit Linux. The error message looks as follows:
```
[hritcu@detained ml]$ make
ocamlc -I ../../Platform/ml -c CoreCrypto.mli
ocamlopt -I ../../Platform/ml -c CoreCrypto.ml
ocamlopt -c -cc gcc -ccopt '-I /usr/local/lib/ocaml' -ccopt "-I /usr/include" -cclib -fPIC -cclib -lcrypto -cclib -c openssl_stub.c
ocamlmklib  -o  openssl_wrap  openssl_stub.o
/usr/bin/ld: openssl_stub.o: relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
openssl_stub.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'dllopenssl_wrap.so' failed
make: *** [dllopenssl_wrap.so] Error 2
```
Adding `-cclib -fPIC` to `ocamlopt` as suggested by the error message and Markulf doesn't seem to make a difference. Any idea what else to try?

**Comment by markulf** [comment]
It worked fine on my Linux VM instance.

**Comment by beurdouche** [comment]
I guess you managed to get it compile =) What was the problem ?

**Comment by catalin-hritcu** [comment]
Needed to pass the `-ccopt -fPIC` flag to ocamlopt on Linux: https://github.com/FStarLang/FStar/commit/308073669b50798dd9f49f1a55ba4d6d44c62327 and https://github.com/FStarLang/FStar/commit/7f100cc8dd84430f71fbfc9cabb4099245f3c753
