### ISSUE TITLE
Broken SMTP configuration on strider

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#317]
Our strider server https://www.fstar-lang.org:3443/ does not seem able to send emails.

https://futurestud.io/blog/strider-configuration-guide-and-available-options/

Though I vaguely remember having received a broken build notification in the past, so maybe it was working at some point.

Related to https://github.com/FStarLang/FStar/issues/285, and essential for the late emergency push from our phones. :) This feature also becomes more important as we have more than one strider test. It also makes adding new users to strider a pain.

**Comment by catalin-hritcu** [comment]
Don't get notifications even if I now have admin on strider and I've added myself explicitly to the list.
![screenshot from 2015-08-24 19-19-51](https://cloud.githubusercontent.com/assets/5850655/9457160/ad22e61a-4a94-11e5-952f-679c085f0316.png)
I've also tried adding fstar-priv-repo to the list but never got any notification there.
![screenshot from 2015-08-24 18-47-24](https://cloud.githubusercontent.com/assets/5850655/9457170/c677344a-4a94-11e5-8e2d-64b72878b2f3.png)

@ad-l Any ETA on this one?

**Comment by markulf** [comment]
This is still broken and a bit embarrassing. We should also find a way to put more test targets up to make strider more genuinely useful.

**Comment by s-zanella** [comment]
This is still broken.
Strider used to notify Slack, so not having e-mail notifications wasn't critical.
Currently Strider builds are broken. We need to update Mono on the server.

**Comment by s-zanella** [comment]
I think we could close this issue as wontfix as long as we recover Slack notifications.

**Comment by nikswamy** [comment]
Close?

**Comment by catalin-hritcu** [comment]
Closed. We don't use strider for a long time, afaik.
