### ISSUE TITLE
hooks for backward compatibility and integration testing

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#318]
`FStar/hooks` contains hooks that should be installed in `FStar/.git/hooks` by individual developers. http://www.git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

We should optimize this process and document it in the `README.md`.

Some/one of these hooks (`pre-post`) depend(s) on the user having an admin strider account. Creation of which requires human work from someone who is already admin while strider refuses to send emails (see https://github.com/FStarLang/FStar/issues/317).

**Comment by catalin-hritcu** [comment]
We're no longer using Strider. Closing.
