### ISSUE TITLE
Unexpected error: abstraction with no binders

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#320]
```F#
module Bug

type r (#a:nat) = x:int { x < a }
type s (a:nat) = { x:r #a; }
type t (#a:nat) = s a
let foo: t = { x = 0; }
```
results in

`Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
abstraction with no binders!`

May be related to #316.

**Comment by nikswamy** [comment]
This is fixed now. 

However, note that the program as written still will not type-check. 

There isn't a unique way to infer the instantiation of the implicit parameter of `t` in the type of `foo`. 

It now fails (as expected) with the following error message:

```
bug320.fst(8,19-8,20): Subtyping check failed; expected type (r #'e5545); got type int
```
