### ISSUE TITLE
polymorphic recursion

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#323]
Extraction is currently not designed to support polymorphic recursion. There is some special syntax do get such functions accepted by OCaml.

**Comment by vkanne-msft** [comment]
Extraction is designed for polymorphic recursion although because we cannot print out explicit type annotations, the functionality doesnt work as expected .

**Comment by mtzguido** [comment]
This was fixed by PR #1127 for issue #1072, indeed adding the explicitly-polymorphic annotations for OCaml code.
