### ISSUE TITLE
Mark old (F* 0.7 and earlier) tutorial as obsolete

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#324]
> http://rise4fun.com/FStar/tutorial/guide

I'm surprised that this link is still live, as it describes a completely obsolete and un-maintained version of F*, and the plan was to take this thing down a while back.

**Comment by nikswamy** [comment]
Thanks for the reminder. Will do first thing on Monday

**Comment by nikswamy** [comment]
It took the whole week for this to happen. 

Made some progress on it: at least all the links to F* from rise4fun.com now point to our website. 

But, unfortunately, you can still go directly to the link mentioned above and get a stale, broken web page.

It will take longer to fix this.

**Comment by vkanne-msft** [comment]
We will not remove this from internet since other papers reference it.

**Comment by catalin-hritcu** [comment]
Fair enough, but can we clearly mark it as obsolete then? With a huge banner at the top? :)  Every now and then we're still receiving questions from confused people asking why the syntax there doesn't work with (modern) F*.

**Comment by catalin-hritcu** [comment]
> Every now and then we're still receiving questions from confused people asking why the syntax there doesn't work with (modern) F*.

Here is a recent example: https://github.com/FStarLang/FStar/issues/598#issuecomment-240675875

**Comment by mtzguido** [comment]
Old version still there, without any banner or notice.

**Comment by mtzguido** [comment]
Still there... but I don't have permission to change it (nor do I know where this is hosted). @nikswamy ? or maybe @ad-l ?

**Comment by nikswamy** [comment]
it's an internal RiSE website which is a bit hard to modify. I'll have another crack at it today.

**Comment by nikswamy** [comment]
rise4fun is gone
