### ISSUE TITLE
Typeclasses: meta argument of `solve` is sometimes not to instantiated

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#3264]
Consider the following example:
```fstar
class class_a (t: Type0): Type u#1 = {
   type_a: Type0;
   f_a: t -> type_a
}
class class_b (t: Type0): Type u#1 = {
   super_a: class_a t;
   f_b: t -> super_a.type_a
}

[@expect_failure]
instance foo1 (t: Type) {| i: class_a t |}: class_b t = {
  super_a = FStar.Tactics.Typeclasses.solve;
  f_b = (fun (y: t) -> f_a y)
}

instance foo2 (t: Type) {| i: class_a t |}: class_b t = {
  super_a = (_ by (FStar.Tactics.Typeclasses.tcresolve ()));
  f_b = (fun (y: t) -> f_a y)
}
```

The first instance, `foo1`, is using `FStar.Tactics.Typeclasses.solve` to get the super instance of `class_a`, which is available directly in the context as `i`.
In `foo1`, F* expect the expression `f_a y` to be of type `FStar.Tactics.Typeclasses.solve #? _ #? _`: the meta argument of `solve` seems not to be ran in that case.

If I write `FStar.Tactics.Typeclasses.solve #_ #i` directly in `super_a`, things are fine. If I use `tcresolve`, things are fine as well, and the same if I just use directly `i` there.

**Comment by mtzguido** [comment]
Thanks for the report Lucas! That was quite the cornercase. The solution is not entirely satisfactory... I think this could pop up again. Please reopen if it does!
