### ISSUE TITLE
Switch to Z3 4.4

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#327]
Switch to Z3 4.4.0 (https://github.com/Z3Prover/z3/releases), since it has a more permissive license (Apache 2.0) and it will make it easier to redistribute binaries. I have no clue whether this will be easy or not, but should definitely try.

**Comment by catalin-hritcu** [comment]
Just tried a Z3 4.4.0 binary for 64-bit Linux, and there are a couple of new `Unknown assertion failed` errors with it.

`lambda_omega.fst` fails in `tsubst_comp`:
```
../../bin/fstar.exe  constr.fst classical.fst ext.fst set.fsi heap.fst st.fst all.fst --admit_fsi Set lambda_omega.fst --max_fuel 1 --max_ifuel 1 --initial_fuel 1
lambda_omega.fst(182,0-224,60): Unknown assertion failed
Error: 1 errors were reported (see above)
```

`f-omega.fst` fails in `typing_weakening_tbnd`:
```
../../bin/fstar.exe  f-omega.fst
f-omega.fst(1276,0-1301,125): Unknown assertion failed
```
`micro-fstar.fst` fails in `typing_substitution` (which was very flaky even with Z3 4.3.2 anyway):
```
../../bin/fstar.exe  micro-fstar.fst
micro-fstar.fst(5542,0-5851,14) (Warning): Focusing on only some cases
micro-fstar.fst(5864,1-6015,2) (Warning): Focusing on only some cases
micro-fstar.fst(6404,2-6504,3) (Warning): Focusing on only some cases
micro-fstar.fst(6337,0-6506,1) (Warning): Focusing on only some cases
micro-fstar.fst(3335,0-3873,8): Unknown assertion failed
Error: 1 errors were reported (see above)
```

**Comment by ngrimm** [comment]
I have switched to z3 4.4 (also on 64-bit linux) about 2 weeks ago and didn't face any problems with it.
`make test` works fine for me and I also can't reproduce the unknown asserstions that you mentioned.

**Comment by catalin-hritcu** [comment]
Tried again and I can no longer reproduce any of the 3 the problems I was getting last night. I've also tried with both my laptop disconnected from power and that succeeded as well. Last night I was running this in parallel with some other CPU hungry tasks (recompiling OCaml, Coq, SSReflect, etc with `make -j`) and my computer was also getting quite hot, so maybe that's the reason for the failures.

In any case, can more people try out Z3 4.4.0 and report back on their experience? I would be especially interested in people running on laptops and not so powerful machines, but which can still successfully run the tests with Z3 4.3.2.

**Comment by catalin-hritcu** [comment]
Seems that 4.4.0 works as much as everything else works. Timeouts are a problem not only with this version.

**Comment by cpitclaudel** [comment]
Small note: Z3 uses an MIT license, not Apache; at least I think: https://github.com/Z3Prover/z3/blob/master/LICENSE.txt

**Comment by catalin-hritcu** [comment]
@cpitclaudel  Indeed, fixed the original post :)
