### ISSUE TITLE
Add version flag

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#328]
Add --version flag that displays not just the version but also the date when the binary was built and whether it's a F#/.NET/mono or an OCaml binary.

**Comment by catalin-hritcu** [comment]
This works now for the binaries we build during our release process (i.e. via `src/ocaml-output/Makefile`), which dynamically generates a `FStar_Version.ml` file in ``src/ocaml-output` for that. It doesn't work though in any other cases though.

**Comment by mtzguido** [comment]
I was gonna do this as it sounded easy enough, and it definitely is if one uses the Makefile, but I have no clue about Visual Studio.

**Comment by catalin-hritcu** [comment]
Don't let perfect be the enemy of the better.

**Comment by nikswamy** [comment]
Lots of work on this by many people, including @mtzguido @jaybosamiya et al.

No plans to support this in the F# build. Let's track this along with the rest of the discussion regarding F# support in F*.  If we generate F# code from the F* sources, we could add version info easily. See #1737
