### ISSUE TITLE
Induction-recursion?

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#331]
I would like to write something like to following : 

```fsharp
type list1 (a:Type) =
  | Nil1 : list1 a
  | Cons1: hd:a -> tl:list2 a -> list1 a
and list2 (a:Type) =
  | List: t:uint8{t=0uy \/ t=1uy} -> 
           v:list a{ (t=0uy <==> is_Nil1 v)
                     /\ (t=1uy <==> is_Cons1 v) } ->
           list2 a
```

However the identifiers `is_Nil1` and `is_Cons1` are unknown to F* at this point. Is it possible to make F* aware of those constructors ?
Is there another way to write that ?

**Comment by catalin-hritcu** [comment]
I think the following type is isomorphic:
```
type list1 (a:Type) =
  | Nil1 : list1 a
  | Cons1: hd:a -> tl:list2 a -> list1 a
and list2 (a:Type) =
  | Nil2: list2 a
  | Cons2: hd:a -> tl:list1 a -> list2 a
```
What exactly are you trying to do?

**Comment by jkzinzindohoue** [comment]
I want to make some type transformations in F* to make some boxing / unboxing explicit and add tags to sum types to experiment with going to C.
Said otherwise, I would like to know if I can write something like

```F#
type ptr (#a:Type) = | Ptr: v:a -> ptr a
type list1 (a:Type) =
  | Nil1 : list1 a
  | Cons1: hd:a -> tl:list2 a -> list1 a
and list2 (a:Type) =
  | List: t:uint8{t=0uy \/ t=1uy} -> 
           v:ptr (list1 a){ (t=0uy <==> is_Nil1 (Ptr.v v))
                     /\ (t=1uy <==> is_Cons1 (Ptr.v v)) } ->
           list2 a
```
 It is supposed to mimic C pointers and structures, and I want to say that the knowledge of the tag value is enough to know which constructor it points to, I don't need to dereference the pointer.

In any case, I would be interested in knowing if the above typeis acceptable with regards to the type system and if so, if we could get F* to accept it.

**Comment by catalin-hritcu** [comment]
Allowing such a type would be shady from a metatheory point of view. Coq also rejects such types for instance:
```
Inductive list1 (a:Type) : Type :=
  | Nil1 : list1 a
  | Cons1: forall hd:a, forall tl:list2 a, list1 a
with list2 (a:Type) : Type :=
  | List: forall t:bool,
            { v:list a | (t=false <-> match v with
                                        | Nil1 => True
                                        | _    => False
                                      end)
                         /\ (t=true <-> match v with
                                          | Cons1 _ _ => True
                                          | _         => False
                                        end) } ->
            list2 a.
```
produces:
```
Toplevel input, characters 462-467:
Error: Unknown constructor: Cons1.
```
Just discussed this a bit with Nik, and he thinks you can add additional indices to identify each constructor of an inductive type. Here is how this would look for your type (using bool instead of uint8 here):
```
type list1 (a:Type) : bool -> Type =
  | Nil1 : list1 a false
  | Cons1: hd:a -> tl:list2 a -> list1 a true
and list2 (a:Type) =
  | List: #b:bool -> 
           v:list1 a b ->
           list2 a
```

**Comment by jkzinzindohoue** [comment]
OK I will experiment with that.
Thanks.

**Comment by s-zanella** [comment]
Note that Agda accepts this kind of inductive-inductive definition:

```Agda
module Shady where

open import Data.Bool
open import Data.Product

mutual
  data List1 (A : Set) : Set where
    nil1  : List1 A
    cons1 : (hd : A) -> (tl : List2 A) -> List1 A

  data List2 (A : Set) : Set where
    list2 : (t : Bool) -> 
            (v : Σ (List1 A) 
                   (λ x -> T (if t then is_nil1 x else is_cons1 x))) ->
            List2 A

  is_nil1 : ∀ {A : Set} -> List1 A -> Bool
  is_nil1 nil1         = true
  is_nil1 (cons1 _ _)  = false

  is_cons1 : ∀ {A : Set} -> List1 A -> Bool
  is_cons1 nil1        = false
  is_cons1 (cons1 _ _) = true
```

Now I'm not saying that the theory behind this is entirely clear, but the idiom is useful enough to raise the question of whether you want F* to support it. Coq is quite conservative in this regard...and Agda is, well, on the opposite end.

**Comment by nikswamy** [comment]
Yes, Catalin and I were discussing that Agda supports it. Induction-recursion is pretty non-trivial though. I don't think we'll be adding this to F\* any time soon.

**Comment by catalin-hritcu** [comment]
Some things to add to me reading list :)
https://en.wikipedia.org/wiki/Induction-recursion_(type_theory)

**Comment by s-zanella** [comment]
I think the original question is more about inductive-inductive definitions than inductive-recursive ones. Add this one to the reading list too :) 

 http://www.cs.swan.ac.uk/~csetzer/articles/forsbergSetzerInductionInductionCsl2010.pdf

**Comment by ad-l** [comment]
+@adl I too am interested in supporting induction recursion in F*

**Comment by vkanne-msft** [comment]
This is not in the roadmap. @ad-l, reopen this if you think this is necessary/relevant.
