### ISSUE TITLE
Contribute F* syntax highlighting back to ace editor

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#333]
We should contribute the F\* syntax highlighting back to ace editor. Once our language appears on this list:
https://github.com/ajaxorg/ace/tree/master/lib/ace/mode then we can also make GitHub (https://github.com/github/linguist/) pick up on this.

@ad-l  What would it take to do this? Any cleanup needed?

**Comment by catalin-hritcu** [comment]
I mean, we already have something in https://www.fstar-lang.org/ace/mode-fstar.js  ... but I can't tell how hacky it is.

**Comment by nikswamy** [comment]
I vote for closing this as there's really no plan for actually doing it, no one is really asking for it, and it's quite low priority

**Comment by sishtiaq** [comment]
How about an editor mode for VS Code?

**Comment by catalin-hritcu** [comment]
@nikswamy: My vote is to label this "patches-welcome" or something. If you want to close it then label it "wontfix".

@sishtiaq: We already have an unmaintained atom mode (https://github.com/FStarLang/atom-fstar), but probably the VS Code extension mechanism is different, right? More importantly, make sure that there are enough interested users before putting energy into building yet another editor mode. Would you use it?

**Comment by sishtiaq** [comment]
I use Code myself over Windows and Mac. But, yes, we should check where the demand is before doing work.
