### ISSUE TITLE
Linguist support for recognizing F* files

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#334]
Just sent in a pull request for this, let's see how this works:
https://github.com/github/linguist/pull/2590  [Update: it didn't]

Here are the rules:
https://github.com/github/linguist/blob/master/CONTRIBUTING.md

**Comment by beurdouche** [comment]
You did not pass Github’s CLA ..

**Comment by catalin-hritcu** [comment]
CLA? What does it mean?

**Comment by catalin-hritcu** [comment]
Ah, I see, I had to agree to some license for my PR. Done.

**Comment by catalin-hritcu** [comment]
Only now I see that Benjamin had also tried this:
https://github.com/github/linguist/issues/1889
His proposal was at least answered (negatively) in a reasonable amount of time, mine is still lagging.

**Comment by catalin-hritcu** [comment]
Unfortunately this won't happen until github starts supporting custom repository-level highlighting (https://github.com/github/linguist/issues/2627) or F* is used in hundreds of github repositories. So let's keep up the good work, hoping that F* takes over the world and then we can get syntax highlighting! :)

**Comment by nikswamy** [comment]
@catalin-hritcu  close?

**Comment by catalin-hritcu** [comment]
There's no "can't fix" so marking this "won't fix"

**Comment by catalin-hritcu** [comment]
It seems there is some renewed interest in this https://github.com/FStarLang/atom-fstar/issues/6

**Comment by ice1000** [comment]
github/linguist#4178 is now merged! Congrats!

**Comment by ice1000** [comment]
![][img]

 [img]: https://img.shields.io/github/issues/detail/s/github/linguist/4178.svg

**Comment by ice1000** [comment]
But please take a look at https://github.com/github/linguist/pull/4178#pullrequestreview-147466002

**Comment by catalin-hritcu** [comment]
It works. Hurrah!
