### ISSUE TITLE
Links to www.fstar-lang.org not working (subdomain misconfigured/gone)

### ISSUE THREAD

**Issue by DestyNova** [FStarLang/FStar#3348]
The Github repo and README link to the [F* homepage](https://www.fstar-lang.org) and tutorial, but both of them produce a 404 error in Azure for me. Removing the `www.` subdomain works, so perhaps we could just update the links here.

**Comment by devkral** [comment]
and no https

**Comment by mtzguido** [comment]
Sorry for not replying here, we had a transient DNS issue but it should be fixed now. Thansk for reporting!
