### ISSUE TITLE
OCaml binary produces bad extracted strings for F* (re)bootstrapping

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#335]
Steps to reproduce:
1) make test -C src
2) make ocaml -C src
3) Now look in src/ocaml-output and see diffs like this with respect to trunk:
https://gist.github.com/catalin-hritcu/8934de3f11aea3818bb4
4) make -C src/ocaml-output
5) Now you have a broken binary
```
cp fstar.exe ../../bin/fstar.exe
make[1]: Leaving directory '/home/hritcu/Projects/fstar/pub/src/ocaml-output'
make: Leaving directory '/home/hritcu/Projects/fstar/pub/src/ocaml-output'
[hritcu@detained pub]$ fstar.exe --version
F* 0.9.0
platform=Linux_x86_64
compiler=OCaml 4.02.3
date=2015-08-28T20:37:13-0700
commit=f244572
[hritcu@detained pub]$ Error: using standard input to read formula.
For usage information: z3 -h
/bin/sh: line 1: $'\r': command not found
/bin/sh: line 2: $'\r': command not found
/bin/sh: line 3: SMT.RELEVANCY=2: command not found

[hritcu@detained pub]$ 
```

This should also explain the latest apparitions of #245, which I'll mark as a duplicate.

**Comment by msprotz** [comment]
In `src/tosmt/z3.fs`:

```
  78   format2 "-smt2 -in %s \
  79     AUTO_CONFIG=false \
  80     MODEL=true \
  81     %s=2"
  82     timeout relevancy
  83 
```

I looked at the extraction code, and it seemed legit, so I believe the parser of F* doesn't strip the "\r\n" from the string constant at it should. Looking into it.

**Comment by msprotz** [comment]
@nikswamy I don't see anything in the lexer that would handle this case. Could it be that previously, string literals were passed "as is" through the extraction mechanism, hence leaving it up to the OCaml parser to handle the escaped end of line? Do we have a reason for re-encoding the strings when extracting?

**Comment by nikswamy** [comment]
Yes, I don't see anything handling this in `src/parser/ml/lex.mll`. Perhaps @ad-l has a better idea about it.

Note that the F# backend seems to do the right thing.

**Comment by nikswamy** [comment]
It seems that a fix is to remove this `Buffer.add_string buffer x;` at line 328 in lex.mll

@msprotz: is this what you had in mind?

**Comment by nikswamy** [comment]
Also, the escaping comes up because of the difference in `src/basic/util.fs` and `src/basic/ml/FStar_Util.fs`, specifically in the `string_of_unicode` functions in each of those modules.
I'm not sure why the OCaml version is encoding benign characters like `_`.

**Comment by nikswamy** [comment]
Nevertheless, it seems that emitting the encoded versions of the strings is not really a semantic problem ... is it?

**Comment by nikswamy** [comment]
I've tentatively pushed the change to `lex.mll`. It seems to fix the broken binary problem.
