### ISSUE TITLE
More user friendly error message when Z3 is not found

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#336]
The current error message is this:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
ApplicationName='z3', CommandLine='-smt2 -in -t:20000 AUTO_CONFIG=false MODEL=true SMT.RELEVANCY=2', CurrentDirectory='', Native error= Cannot find the specified file
```
In general, we should only use `Unexpected error` for broken invariants in our tool, not for normal errors.

**Comment by catalin-hritcu** [comment]
Our artifact evaluation reviewer also reported this stupid error message to us.

**Comment by beurdouche** [comment]
I have fixed it for the F# version in the following commit : 
https://github.com/FStarLang/FStar/commit/7a2635ca1161658afba5736bfc0051185ec1fc04

It seems that the patch is not suffisant for the OCaml backend because it seems to call `z3` earlier in the the execution of F*

**Comment by msprotz** [comment]
```
jonathan@chartreuse:~/Code/fstar/bin (master) $ PATH= ./fstar.exe /tmp/test.fst
/bin/sh: z3: No such file or directory
/bin/sh: z3: No such file or directory
```

This is the OCaml version, so I'd say good enough for me.

**Comment by catalin-hritcu** [comment]
indeed, this works now
