### ISSUE TITLE
Unable to open files by absolute paths

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#337]
Hi all,

Is the following behavior expected? Did I miss something in the documentation?

```
C:\>ls -lh C:\home\test.fst
-rw-r--r-- 1 clement Clément 23 Aug 30 11:21 C:\home\test.fst

C:\>fstar home\test.fst
Verifying module: A
All verification conditions discharged successfully

C:\>fstar C:\home\test.fst
Error: Unable to open file: C:\home\test.fst
```

I seem to have this same problem with all absolute paths. This is using Friday's release.

The relevant source seems to be https://github.com/FStarLang/FStar/blob/16138cf41a4ded4fe4516d050037621c30466065/src/parser/parseit.fs#L43.

**Comment by catalin-hritcu** [comment]
I've committed tentative support for this on the absolute-paths branch. It works on Unix when using OCaml, but it still needs testing in all other cases (F# on Windows and mono, etc).

**Comment by catalin-hritcu** [comment]
The F# on mono version fails with:
```
[hritcu@detained src]$ fstar.exe /home/hritcu/Projects/fstar/pub/examples/unit-tests/fact.fst

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Could not find file "/home/hritcu/Projects/fstar/pub/src/prims.fst".
```
I have no clue why it's looking for prims.fst in the `src` folder, but probably I broke something here.

**Comment by catalin-hritcu** [comment]
This is fixed now, and with this fstar-mode works well.

**Comment by cpitclaudel** [comment]
Great! Could you upload a build somewhere? I don't have a build environment set up a the moment.

**Comment by catalin-hritcu** [comment]
Sent you a link by private email.

**Comment by cpitclaudel** [comment]
Thanks! I downloaded something from your server, but it didn't seem to make a difference for me :/

**Comment by catalin-hritcu** [comment]
Ouch, I didn't do the packaging right last time and you ended up with an
old version. I've uploaded the binary at the address above, please try
again.

**Comment by cpitclaudel** [comment]
Yup, works fine now :) Thanks for the fix!
