### ISSUE TITLE
Missing projectors/discriminators of primitive types 

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#338]
Projectors and discriminators of primitive types like ```option``` and ```either``` are extracted to symbols that are not defined in F# and OCaml libraries. For example,  ```let f = Some.v``` typechecks in F*, but extraction to OCaml generates ```let f = Prims.___Some___v```, which can't be compiled using the libraries provided. 

Is the intention to some day extend the built-in libraries to define these symbols? I understand is very brittle to write F* code that depends on internal names in primitive libraries, like 'v' above, but discriminators as ```is_Inl``` are also extracted to undefined symbols and is reasonable for a user to expect them to be extracted correctly.

**Comment by nikswamy** [comment]
This is an oversight. We should define __Some__v in prims.ml and prims.fs, is_Inl etc. too.

**Comment by catalin-hritcu** [comment]
Seems that @aseemr added these recently to prims.ml, but not to prims.fs. Should we try to check automatically that these 3 files are always in sync?

**Comment by aseemr** [comment]
Yes, that would be great. We could also move types such as 'either' out of prims so that they can be extracted normally.

**Comment by catalin-hritcu** [comment]
@s-zanella  Is this fixed by now?

**Comment by s-zanella** [comment]
Well, it is for the functions above, but there are still some missing (e.g. `is_Err`).
I guess we can add them on demand, or not add them at all since the definitions that are now missing are rarely used.

**Comment by s-zanella** [comment]
I couldn't find any missing projector or discriminator in prims, so I consider this issue is resolved.

OCaml implementations of other modules are less consistent in this respect (e.g. ucontrib/Platform/ml/platform.ml) comes to mind.
