### ISSUE TITLE
Incompleteness for lambdas in binary search trees

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#339]
The following variant of the `is_bst` (from `data_structures/binary_search_tree_basic.fst`) doesn't currently work (causes failures all over in the binary search tree example)

```
val is_bst : tree -> Tot bool
let rec is_bst t =
  match t with
  | Leaf -> true
  | Node n t1 t2 -> all (fun n' -> n > n') t1 &&
                   all (fun n' -> n' < n) t2 && is_bst t1 && is_bst t2
```

although it's equivalent and more natural than what we write now:

```
val lt : int -> int -> Tot bool
let lt n1 n2 = n1 < n2

val gt : int -> int -> Tot bool
let gt n1 n2 = n1 > n2

val is_bst : tree -> Tot bool
let rec is_bst t =
  match t with
  | Leaf -> true
  | Node n t1 t2 -> all (gt n) t1 && all (lt n) t2 && is_bst t1 && is_bst t2
```

Also, the most natural way of writing this is not even syntactically accepted

```
val is_bst : tree -> Tot bool
let rec is_bst t =
  match t with
  | Leaf -> true
  | Node n t1 t2 -> all ((>) n) t1 &&
                   all ((<) n) t2 && is_bst t1 && is_bst t2

```

we can't partially apply operators at the moment, right? Would it be hard to add?

**Comment by nikswamy** [comment]
You can partially apply them if you use there full names. 
For example, `op_GreaterThan`

**Comment by catalin-hritcu** [comment]
Messed up the direction of comparison, this is not a bug. Closing.
