### ISSUE TITLE
Error message from desugaring

### ISSUE THREAD

**Issue by fournet** [FStarLang/FStar#340]
Errors such as 

tls/Sig.fst(19,29-19,52) : Error
The operator "*" is resolved here as multiplication since "foo" is a term, although a type was expected

thrown in src/parser/desugar.fs are misleading when "foo" is undefined. How to report a more helpful error?

**Comment by nikswamy** [comment]
"since 'foo' is not a type"?

**Comment by catalin-hritcu** [comment]
This kind of issues will go away on the universes branch, right?

**Comment by vkanne-msft** [comment]
This is no longer possible in universes. Although, we have other issues with overloading "*" Closing this one.
