### ISSUE TITLE
Specifying effects for inner functions

### ISSUE THREAD

**Issue by hoheinzollern** [FStarLang/FStar#342]
I would like to specify an effect for an inner function, but the language somehow does not allow me to do that. For example:

``` ocaml
val f: nat -> Tot nat
let f n =
  let rec f_loop (i: nat) (acc: nat): Tot nat =
    if i > 0 then f_loop (i-1) (acc+i)
    else acc
  in f_loop n 0
```

would give me the following error for the inner loop:

```
testinner.fst(5,38-5,47) : Error
Kinds "Effect" and "Type" are incompatible
```

but if I remove this annotation, the automatic computation for effects is not precise:

``` ocaml
val f: nat -> Tot nat
let f n =
  let rec f_loop i acc =
    if i > 0 then f_loop (i-1) (acc+i)
    else acc
  in f_loop n 0
```

gives

```
testinner.fst(11,0-25,0) : Error
Computed type "nat" and effect "ALL" is not compatible with the annotated type "nat" effect "Tot"
```

The only way that I found to overcome this limitation is to make f_loop top-level:

``` ocaml
val f_loop: i:nat -> acc:nat -> Tot nat
let rec f_loop i acc =
  if i > 0 then f_loop (i-1) (acc+i)
  else acc

val f: n:nat -> Tot nat
let f n = f_loop n 0
```

this succeeds in verifying, but in my specific case I would like to avoid it, and I don't see why this should not be allowed. Am I missing the proper way to do it?

**Comment by catalin-hritcu** [comment]
I agree we should have a proper way to do this. On the other hand, there are more serious problems with nested `let rec`s (#194, #58), so you should hoist those to the top level anyway.

**Comment by aseemr** [comment]
You could also write this:

```ocaml
val f: nat -> Tot nat
let f n =
  let rec f_loop: nat -> nat -> Tot nat =
    fun i acc ->
    if i > 0 then f_loop (i-1) (acc+i)
    else acc
  in f_loop n 0
```

This verifies, but with a warning "Non-top-level recursive functions are not yet fully encoded to the SMT solver; you may not be able to prove some facts". So you would need to reason only using types in this style.

**Comment by hoheinzollern** [comment]
Thank you both for your replies. I will then stick to the top level until those issues are solved.

**Comment by s-zanella** [comment]
This is now possible.
