### ISSUE TITLE
Effect overloading?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#343]
The tutorial (4.3) claims that we plan to add some form of effect overloading. Is that true?

> **No parametric polymorphism on effects**: You might hope to give
> `map` a very general type, one that accepts a function with any effect
> `E` and returns a function with that same effect. This would require a
> kind of effect polymorphism, which _F* does not support_. This may
> lead to some code duplication. We plan to address this by allowing you
> to write more than one type for a value, an ad hoc overloading
> mechanism.

**Comment by nikswamy** [comment]
We had many discussions about this a while back. Not sure how high it is currently on our list of priorities. Would be nice to have.

**Comment by catalin-hritcu** [comment]
@mtzguido @kyoDralliam It would be nice to return to this idea now that we have type classes and support for resolving implicit arguments using tactics. I guess that the main challenge is to verify the code of functions like map, which would be parameterized over a Dijkstra monad, and would thus need to be verified in a rather generic fashion using generic properties of Dijkstra monads? Given that other than the call to the effectful function it gets as argument all the code is pure, this doesn't sound too crazy, does it?

**Comment by aseemr** [comment]
Catalin's proposed direction is interesting, but this requires more research, marking it wontfix and closing for now.
