### ISSUE TITLE
Parse build-config in interactive mode too

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#346]
Currently each editor mode has to implement it's own build-config parser, and that seems silly and error prone.

**Comment by nikswamy** [comment]
It would be easier to implement if we went with the following design: 

1. We add a command line flag like so: --build_config "options: ...; variables:...; other-files: ... "; this argument is only allowed when the `--in` flag (for interactive mode) is also provided.
2. The compiler parses this string as it would the contents of a "(*--build-config ... --*)" block.
3. It's the job of each editor to detect if the file begins with a build config block; if so, it should pass the contents of that block among the arguments of the `fstar` process it starts.
4. If the user edits the build-config while in the interactive mode, the editor has to kill the fstar process and start a new one with the new build-config.

@aseemr @cpitclaudel What do you think?

**Comment by aseemr** [comment]
This sounds good to me. However I wonder how much additional work would it be for the interactive mode to parse the build config directly (without the editor sending the --build_config argument).

-- The interactive mode maintains a flag. The flag is set if either (a) the interactive mode has already processed a build config, or (b) the interactive mode has type checked some code fragment. The flag is false to begin with.

-- If the flag is set, there's no need to look for a build config.

-- If the flag is not set, see if the string sent by the editor starts with a build config format, and if so, parse it (using the existing code in parseit.fs).

-- Batch mode tc the files mentioned in build config and update the envs. Set the flag.

-- If the flag is not set and the string sent by editor does not start with build config, set the flag, and proceed to type check the sent fragment.

I guess with fstar --in, one can specify files on the command line also. That's fine, and they can be processed as is done currently. What do you think ?

**Comment by cpitclaudel** [comment]
@nikswamy Your solution seems fine to me, although @aseemr's suggestion seems a bit more robust. Indeed, if we pass the build config as an argument, we may run into restrictions on the length of argument lists (8191 on Windows; that's large, but I'm sure some large project that auto-generates build configs will run into the issue at one point or other).

Editors will still have to recognize build config sections, as they'll want to restart entirely if the build config is changed; that seems fine by me.

**Comment by nikswamy** [comment]
I agree the @Aseemr's proposal is more robust. It requires more significant reworking of the top level fstar.fs, however. Aseem, do you want to implement it?

Sent from my Windows Phone
________________________________

**Comment by aseemr** [comment]
Pushed a commit for this. The interactive mode now parses the build config as I outlined above. Also pushed a change in fstar-interactive, removing code that used to parse build config (https://github.com/FStarLang/fstar-interactive/commit/f3151ed9b8dd2aa58e1d009a90824887c83d823a).

**Comment by cpitclaudel** [comment]
Awesome! Thanks @aseemr for implementing this so quickly. I'm running into one small issue though:

```bash
$ pwd
/build/fstar/examples/algorithms
$ ../../bin/fstar.exe --in
(*--build-config
  options:--z3timeout 20;
  variables:LIB=../../lib;
  other-files:$LIB/classical.fst $LIB/ext.fst $LIB/set.fsi $LIB/set.fst $LIB/heap.fst
              $LIB/stperm.fst $LIB/seq.fsi $LIB/seq.fst $LIB/seqproperties.fst $LIB/arr.fst
              qs_seq.fst qsort_arr.fst
--*)
#end
qsort_arr.fst(180,0-188,46): Refusing to check more than one module at a time incrementally
fail
```

**Comment by nikswamy** [comment]
Thanks for the nice implementation of this feature, Aseem. 

The issue with parsing empty fragments should be fixed now. 

Please let me know if glitches remain.

Closing it.

**Comment by cpitclaudel** [comment]
Thanks, looks great. One caveat is that F* will let you pop the build-config, but then all sort of funny things will happen. I've made the Emacs mode actively kill F* if the build config is retracted.
