### ISSUE TITLE
Weak type variables

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#347]
Type inference leaks unification variables. This happens in `paradoxes/berardi` and now in a much simpler file that's supposed to check for the absence of the problem that lead to the ML value restriction (`paradoxes/value-restriction.fst`):
```
let r = ref None  // -- this *leaks* an unification variable

val r1 : ref (option string)
let r1 = r                  // -- variable gets instantiated to string

val r2 : ref (option int)
let r2 = r                // -- this fails
```
causes
```
value-restriction.fst(10,9-10,10) : Error
Expected expression of type "(ref (option int))";
```
<del>It's likely that such an error can be used to prove false.</del>

**Comment by nikswamy** [comment]
I don't see the problem here. The behavior is consistent with what OCaml does, for example, with weak type variables. 

The type of `r` is not generalized initially, since it is not a pure term.

When it is used in `r1`, the variable is instantiated to string, and then it is fixed at that type.

**Comment by catalin-hritcu** [comment]
This is non-local and for me also highly unintuitive.

1. Is there any way to add a type annotation that expresses the inferred type?

2. Can we at least raise a warning when no annotation is found and a unification variable is leaked?

**Comment by vkanne-msft** [comment]
Closed.

**Comment by nikswamy** [comment]
Universes mode is much stricter about unresolved implicits.

**Comment by catalin-hritcu** [comment]
I like the stricter implicits. Unfortunately, the `ValueRestriction.fst` paradox now goes through (#583).
