### ISSUE TITLE
Support for F* in Visual Studio

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#348]
Last attempt to create such an IDE support was for VS2013 and was a failure.
In Visual Studio 2015, there is now a mechanism that ease support for other languages through the use of VS extensions templates written in C#. 
It should be easier to support F\* and the interactive mode and I think it should be a priority when we have some spare time.

**Comment by catalin-hritcu** [comment]
Patches welcome :)

**Comment by sirinath** [comment]
Ability to have mixed F# and F* projects also should be a must. With seamless ability to convert from on to the other.

**Comment by AnastasiyaRagozina** [comment]
Hi, we are working on this task. Repo https://github.com/YaccConstructor/VisualFStar. We are at the beginning. And we thought about ability to have mixed F# and F* projects.

**Comment by sirinath** [comment]
Great!!!

**Comment by bogdangaliceanu** [comment]
Very cool. It will be wonderful to have a high quality integration with Visual Studio

**Comment by sirinath** [comment]
@AnastasiyaRagozina Another language which might interest your research group: http://felix-lang.org/

**Comment by nikswamy** [comment]
This is very old issue. Please re-open in case there are any updates.

Meanwhile, this page is a good resource:
https://github.com/FStarLang/FStar/wiki/Editor-support-for-F*
