### ISSUE TITLE
Corner case for which higher kinded equality does not work properly

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#351]
While working on `paradoxes/InjectiveTypeFormers.fst`, I've discovered a corner case in which higher kinded equality does not work properly. The following slightly simplified code should type-check, but it doesn't:

```
// even if the definition of P shouldn't matter below, it actually does
// (everything works if we assume P or if we define it in a simpler way)
type P (a:Type) = (cexists (fun (x:a) -> ctrue))

// all this works fine if we change to h2':(P p -> Tot unit)
val aux : p:Type -> h:P p -> a:(Type->Type) -> h2':(a p -> Tot unit) ->
            Pure unit (requires (a == P)) (ensures (fun _ -> True))
let aux (p:Type) (h:P p) (a:(Type->Type)) h2' = h2' h
// bug351b.fst(16,37-16,38): Subtyping check failed;
// expected type (a p); got type (P p)
```

Experimented quite a bit, but didn't manage to find a simpler counterexample illustrating the problem. Higher kinded equality works well in all other cases I've tried.

**Comment by catalin-hritcu** [comment]
The shrunk counterexample works now, but the original problem in `inj.fst` is still there.

**Comment by vkanne-msft** [comment]
The example in 351.fst works fine. 
The example in inj.jst does not complete because of the below error. 

    .\examples/paradoxes/inj.fst(13,5-13,6) : Error
    Invalid identifer 'I'; expected a symbol that begins with a lower-case character

@catalin-hritcu  can you verify ?

**Comment by s-zanella** [comment]
@vkanne-msft: that's an unrelated error due to a syntax change.

Reproducing this requires a means to denote universes beyond `Type0`, which is still pending in #505.
See also #349 for the discussion on injectivity of type constructors.

**Comment by catalin-hritcu** [comment]
After porting `inj.fst` to universe syntaxt (and renaming it to `InjectiveTypeFormers.fst`), I think I'm hitting the error @s-zanella was talking about:
```
[hritcu@detained paradoxes]$ fstar.exe InjectiveTypeFormers.fst
./InjectiveTypeFormers.fst(14,2-14,4) : Error
Expected expression of type "(_:Type -> Type)";
got expression "f" of type "(_:Type -> Type)"
```

**Comment by catalin-hritcu** [comment]
@s-zanella @kyoDralliam: Kenji has just implemented explicit universe syntax, so we should be able to reproduce this now? https://github.com/FStarLang/FStar/wiki/Explicit-universes

**Comment by nikswamy** [comment]
InjectiveTypeFormers.Explicit.fst typechecks and we're able to demonstrate that assuming injectivity (via an axiom) leads to a contradiction.
