### ISSUE TITLE
(Warning 328) - Global binding .. is recursive but not used in its body

### ISSUE THREAD

**Issue by briangmilnes** [FStarLang/FStar#3545]
I get a 328 here but should not. Finally got a small example but it must be compiled in a system environment. 
F* 2024.09.05~dev
platform=Linux_x86_64
compiler=OCaml 4.14.2
date=2024-10-09 12:30:25 +0100
commit=15e02875d0989b3bd9ed149a689c8848cea07705

module RecButNotUsed

open FStar.TypeChecker.Env
open FStar.Syntax.Syntax

let rec diff_Tm_bvar (e: env) (f: term)         (x: term) = f

and typdiff (e: env) (f: typ) (x: typ) : term = 
 if f = x  // Just for example.
 then f
 else 
 match x.n with
  | Tm_bvar     bv -> diff_Tm_bvar e f x
  | _              -> diff_Tm_bvar e f x

**Comment by mtzguido** [comment]
The warning is legit since `typdiff` is not used in the group. This warning is in fact conservative: it does not compute SCCs as it should, so things like `let rec f () = f () and g () = g ()` do not trigger a warning, even if the group can be split.

**Comment by briangmilnes** [comment]
And yet with fully recursive functions I have seen this but my last
attempt to boil it down failed. I'll try again when I run into it in a
clean way.
