### ISSUE TITLE
Problem with F#-compiled binary and --in flag

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#356]
With an F#-compiled binary (from `make -C src` or VS) and M.fst containing

```F#
(*--build-config
    options: --verify_module M;
    other-files: listTot.fst 
--*)
module M
``` 
```
$ fstar M.fst
Verifying module: M
All verification conditions discharged successfully

$ echo -e "#push\n`cat M.fst`\n#end" | fstar.exe --in
listTot.fst(196,45-196,48) : Error
Identifier not found: [fst] (Possible clash with related name at prims.fst(513,0-513,29))
```
With an OCaml-compiled binary (from `make -C src/ocaml-output`) the latter succeeds, as expected.

**Comment by catalin-hritcu** [comment]
same problem here

**Comment by beurdouche** [comment]
I believe this is not a problem anymore. Can someone please confirm before I close ?

**Comment by s-zanella** [comment]
I confirm this can be closed.
The issue has become moot because `build-config` blocks are no longer interpreted. 
Regardless, I tried reproducing this using the command-line and interactive modes and they both consistently report the same error, as expected.
