### ISSUE TITLE
Better pretty printer

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#36]
NS: better printing of terms would improve the readability of error messages immediately (and would also be useful groundwork for better visualizations in the future)

NS: About debug level low: It's not designed to be robust right now. Hence one of my tasks on the list I sent last night. It's using a very naive normalizer to print types. That thing blows up on anything but the smallest types.

**Comment by catalin-hritcu** [comment]
The Idris semantic pretty printer seems really cool:
https://wiki.haskell.org/HaskellImplementorsWorkshop/2015#A_Pretty-Printer_that_Says_what_it_Means

**Comment by msprotz** [comment]
In Mezzo we used Pottier's pprint library (OCaml implementation of Wadler/Leeijen's Pprint). It worked out pretty well; more importantly, I think the implementation is smart and makes sure we don't allocate too much memory. This *may* help with the large string problems you've been seeing (allocating too many sub-strings?).

I suspect it may be easily portable to F*?

**Comment by catalin-hritcu** [comment]
This would indeed be the simplest way. Pierre-yves already ported this F# (https://github.com/strub/pprint-for-fsharp) and part of it also to a F* (https://github.com/FStarLang/FStar/tree/master/src/format), and the old extraction mechanism was already using this.

**Comment by sishtiaq** [comment]
Plan:
1. The `format.fs` module will implement a version of Wadler/Leeijen/Pottier/Strub's PPrint. `format.fs` will be written in an intersection of F*/F# and, ideally, F*/F#/OCaml. 
2. `format.fs` is currently used by `fstar/fstar.fs`, `extraction/kremlin.fs` and `extraction/codegen.fs`, but only in very simple ways. `syntax/print.fs` does not currently use format at all. These clients of format will be upgraded to use it's smart combinators (like brackets, hbox, nest).

**Comment by catalin-hritcu** [comment]
Comment about this from @nikswamy on Slack on April 27:
> Just merged in long-standing work on a new pretty printer for F*. Many thanks to Qunyan, Kenji, Jonathan and Samin! It's still a work in progress with many more opportunities remaining to prettify the output. But, the basic framework on which to improve it is now in place

@nikswamy @qunyanm @kyoDralliam @msprotz @sishtiaq 
Does this mean we can now close this longest standing issue?

**Comment by kyoDralliam** [comment]
Even if we made real progress on this issue I don't think it is solved yet...

**Comment by s-zanella** [comment]
Thanks! Error messages get much more legible with this.

What's the criteria to print or not print module names? 
It's not consistent. I see `Prims.GTot` and `M.foo` but `return_squash` while checking `foo` in module `M` without opening `FStar.Squash`. I would rather not have the `Prims.` or `M.` prefixes printed, but it probably makes sense to print `Squash.`

**Comment by qunyanm** [comment]
OK. I will take a look.


On May 2, 2017, at 3:42 AM, Santiago Zanella-Beguelin <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Error messages get much more legible with this.

What's the criteria to print or not print module names?
It's not consistent. I see Prims.GTot and M.foo but return_squash while checking foo in module M without opening FStar.Squash. I would rather not have the Prims. or M. prefixes printed, but it probably makes sense to print Squash.

**Comment by catalin-hritcu** [comment]
There are various issues to keep track on pretty printer work: #1152 and #1298

**Comment by aseemr** [comment]
As per Catalin's comment, there are more recent reports to track various issues with the F* pretty printer. Hence closing this issue.
