### ISSUE TITLE
let comment (p : Type) = () is useful while working on proofs

### ISSUE THREAD

**Issue by briangmilnes** [FStarLang/FStar#3602]
A small addition to prims would be:
let comment (p : Type) = ()

because while you are working on proofs you want to
if ...
then (assert or assume(P); term)
...

and check if it's needed without deleting it. So you can change it
to comment. Or ignore or such.

**Comment by nikswamy** [comment]
Why not just make it a real comment with `//` or `(* ... *)`?

**Comment by briangmilnes** [comment]
It's just faster and clearer than commenting, which I do otherwise.
It would be nice too to have a comment(lemma...) that did not apply
the lemma.

 Just a nice little flourish.

**Comment by briangmilnes** [comment]
I should say it lets you show the intermediate asserts that you don't need
in the final
proofs.

**Comment by briangmilnes** [comment]
Like this:
let not_subset_lstl_impl_not_subset (#e: eqtype) (lsa: (listset
e){~(isempty lsa)}) (lsb: listset e) :
 Lemma (requires ~(subset (lstl lsa) lsb))
       (ensures  ~(subset lsa lsb))
 [SMTPat (~(subset (lstl lsa) lsb)); SMTPat (~(subset lsa lsb))]
= introduce subset lsa lsb ==> False
  with pf_subset_lsa_lsb .
  begin
   comment(~(subset (lstl lsa) lsb));
   comment(~(forall e'. mem e' (lstl lsa) ==> mem e' lsb));
   comment(~(forall e'. mem' e' (lstl lsa) ==> mem' e' lsb));
   comment(exists e'. ~(mem e' (lstl lsa) ==> mem e' lsb));
   comment(exists e'. mem' e' (lstl lsa) /\  not(mem' e' lsb));
   eliminate exists e'. mem' e' (lstl lsa) /\  not(mem' e' lsb)
   returns ~(subset lsa lsb)
   with pf_mem_e'_lstl_lsa_and_not_mem_e'_lsb .
   begin
    comment(mem' e' (lstl lsa));
    assert(mem' e' lsa);
    assert(not(mem' e' lsb));
    ()
   end
  end

**Comment by briangmilnes** [comment]
Nik,

 The advantage here is both typographical and for changes. If you put that
in the editor it and it reads right and
gets type checked. So if you change something you see it. My comment though
is getting into the proof state
which is interesting.

 If you // it out it's a different color, different fonts and just plain
ugly. Proofs should be beautiful in my mind.

 Do you like the idea or not?

-B

**Comment by nikswamy** [comment]
I'm not in favor of having this in prims. If you like this style, then you could use your own `let comments p = ()` definition.

**Comment by briangmilnes** [comment]
But somehow p is being processed in the proof, so I can't really do that.
Is there someway to ensure that p is just parsed, type checked but not
used in the proof? A tactic perhaps?

**Comment by briangmilnes** [comment]
Ah let comment p = assert(True) is doing the job. It type checks p, puts
trivial True in the goal stack, and prints nicely.
You don't find //p printing in red in different fonts ugly enough to fix?
I wonder how many of the 940 asserts in ulib are needed in the proof versus
being commentable.

**Comment by nikswamy** [comment]
Glad that you have a style that works for you. I don't want to suggest that this is a recommended style by including it in prims.
