### ISSUE TITLE
Negative occurrence of a type in a constructor parameter

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#362]
I was surprised to find out that F* is happy to accept the following
```F#
type t = | C : (t -> Type) -> t
```
This can obviously be used to prove False. In contrast, this other definition is rejected
```F#
type u = | C : (u -> Tot unit) -> u
```
The only related issues I found are #319 and #278. I hope this is a bug. If not, this *feature* should be better documented and at least the user should be warned about the non strictly positive occurence in `t`, like proposed in #278.

**Comment by nikswamy** [comment]
@s-zanella : Just to confirm, this is indeed a bug. Also, `type t` would be ruled out both by the cardinality check and the positivity check.
