### ISSUE TITLE
Equality of constructed polymorphic types in the SMT solver / hash-consing open refinement types

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#363]
Aseem and I observed the following issue, where the assertion below fails. 
We discussed several potential fixes, including trying to do a better job with hash-consing in the SMT encoding. But, the right fix is quite subtle ...

```
module Bug
type ordmap 
type Good : nat -> Type
type tpar (ps:nat) = m:ordmap{Good ps} 

val pstep: ps':nat -> pi:(tpar ps' * unit) -> Tot (tpar ps')
let pstep ps' pi  = MkTuple2._1 pi

let pstep_lemma (ps':nat) (pi:(tpar ps' * unit))  =  assert(pstep ps' pi = MkTuple2._1 pi)
```

**Comment by nikswamy** [comment]
@aseemr: Decided to not implement the fix we spoke about right now. It's not a very robust fix anyway---we cannot rely only on hash consing to get the job done for us. There will always be situations in which slight syntactic differences lead to different terms being generated for the SMT solver. We'll need to come up with a way to recover semantic equality in general ... and then hash consing is just an optimization for shorter proofs.

**Comment by aseemr** [comment]
Sure. For reference, one workaround is to define a custom tuple. That is, instead of type (tpar ps * unit), define a custom tuple: type ctuple: nat -> Type = | Mk_t: #ps:nat -> tpar n -> unit -> ctuple n.

**Comment by nikswamy** [comment]
Regarding the workaround: yes, then it is no longer polymorphic.

**Comment by s-zanella** [comment]
Cannot reproduce anymore.

**Comment by vkanne-msft** [comment]
Not reproducible.
