### ISSUE TITLE
Automatically find and include .fsi files, consistently

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#364]
From fstarlang/fstar-mode.el#13:

> I'd argue that it's great that F* found the fsi file automatically. OCaml also finds ".mli" files in the include path (lib directory, current directory), and I would be awful if we had to specify the list of all the .mli files we need when type-checking an OCaml file. I'll file an issue against F*.

So I'd say that this issue is about:
- <del>making the behavior consistent between interactive and batch</del> [CH: filed this separately as #374]
- making sure we don't need extra configuration or voodoo in both these cases, because finding fsi's automatically is great

**Comment by s-zanella** [comment]
+1. Different behaviour between batch and interactive mode, and between verifying single and multiple files is source of a lot of confusion.

I don't see why this shouldn't work for .fst files too: look for a matching .fsi file in the include path first, and if there's none look for a .fst file. We probably want to admit .fsi's as if there was a `--admit_fsi` flag.

**Comment by catalin-hritcu** [comment]
Please define "matching" fst/fsi file.

**Comment by msprotz** [comment]
Here's what we did for Mezzo:
- if you want to open module Foo, there must be a file whose name is foo.mzi in your include path
- the definitions from foo.mzi are *admitted* when you "open Foo"
- it is up to your build system to make sure that foo.mz type-checks against foo.mzi

I'd say having the same behavior would be desirable for F* (replace "mz" with "fs").

**Comment by msprotz** [comment]
Speaking of build system, we had custom rules for ocamlbuild, meaning that you could build a mixed project with ocaml/mezzo files, and ocamlbuild would take care of: making sure mz's match against mzi's, extracting mzi's to mli's, extracting mz's to ml's, and compiling everything altogether.

So as long as you have a good solution for your build system, the recipe above is, imho, pretty user-friendly.

**Comment by catalin-hritcu** [comment]
Seems like a nice, simple and usable setup, but quite different than what we currently have for F*, where a single file can export multiple top-level modules and where modules with the same name are defined by multiple files (usually they are replacements of each other). I guess in OCaml you can afford this simplicity by having a more complex module system ... for instance F* modules don't nest AFAIK.

**Comment by msprotz** [comment]
Oh right I was unaware you could export multiple modules from the same file. What about, if file "foo.fs" contains "module bar" and "module baz", considering that it exports "foo.bar" and "foo.baz" (nesting at depth one)?

But then you could no longer switch between files easily in your build system.

**Comment by s-zanella** [comment]
There are more subtleties: the matching mechanism should be aware of namespaces. I'd say it's reasonable to map the FStar to F* lib directory. Other namespaces can be inferred from directory names on the include path, or explicitly mapped. Coq uses e.g. `Add LoadPath "../contrib/CoreCrypto" as CoreCrypto` [Coq's LoadPath](https://coq.inria.fr/refman/Reference-Manual008.html#sec269)

**Comment by catalin-hritcu** [comment]
The rest of this is now discussed in #438, closing.
