### ISSUE TITLE
Separate data and control in REPL protocol

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#366]
See #361 to see why combining the two is a bad idea and how it's done in Dafny.

**Comment by catalin-hritcu** [comment]
I think the current protocol was a quick fix Nik implemented, but was never not supposed to be the end of the story. We could of course try to incrementally improve it, but we could also look at the standard interaction protocols for proof assistants: in particular Proof General's (both the implemented one and the proposed replacement Proof Kit / PGIP http://proofgeneral.inf.ed.ac.uk/kit) and the more modern and less emacs specific PIDE (Prover IDE) framework which Isabelle and now Coq (http://www4.in.tum.de/~wenzelm/papers/coqpide.pdf) support.

**Comment by cpitclaudel** [comment]
PGIP is mostly dead IIUC, and the current pG is just based on looking for prompts sent by a REPL.  INRIA has been working on porting PG to Coq's custom XML-based async protocol. CoqPIE is just a UI on top of the regular REPL-based `coqtop`.  The dafny protocol is REPL-like too (I wrote it during my internship two years ago), and documented at https://github.com/boogie-org/boogie-friends/blob/master/emacs/inferior-dafny.el#L54.
