### ISSUE TITLE
min and max functions in FStar.Prims

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#368]
What's the purpose of these assumed functions in prims.fst?
```F#
assume val min: int -> int -> Tot int
assume val max: int -> int -> Tot int
```
They aren't specified and they aren't translated to any function defined in Z3. Maybe they were added in accident (75f9152b23de91a1fedc9b2b12e5c6fa1e4ae1cd)?

**Comment by nikswamy** [comment]
Would be great to remove them. Can you, please?

**Comment by s-zanella** [comment]
Done. Nothing seemed to depend on them.
