### ISSUE TITLE
Round Trip Support. OCaml, F# -> F*

### ISSUE THREAD

**Issue by sirinath** [FStarLang/FStar#369]
Support to issue free fully automatic round trip conversion from F#, OCaml into F*

**Comment by sirinath** [comment]
You will need to be able to convert any pure / unsafe CIL to F* as well as F# can use any CIL libraries.

**Comment by nikswamy** [comment]
Extremely unlikely that we will ever automatically port CIL to F*.

**Comment by sirinath** [comment]
You will need some form of understanding of other .net languages.

**Comment by sirinath** [comment]
Some way to analyse and reason over existing code in an easy way.

**Comment by gsvgit** [comment]
Well... What about F#(OCaml) and F* unification? Syntax for functions and types specification can be unified. Yes, it will be only small subset of F#, but can be extended in future. Extended types annotations can be filtered (seems that on lexical level). 

code | -> remove extended types annotation -> F# compiler | -> merge errors
-------|--------|------
         | -> F* core   -> Z3 ->                                                    | 

It seems like F7 but I think that more deep integration of F* core and F# is possible.

The next step is AST to AST transformations.

**Comment by sirinath** [comment]
This will bee great if you can convince all the folk who can do this. This would definitely b the best possible solution.

**Comment by nikswamy** [comment]
This is an extremely old issue with no planned work in this direction---sorry.

If you are still interested and want to contribute to this, please re-open and propose a concrete solution.
