### ISSUE TITLE
Platform.Bytes.equalBytes not specified. Using structural equality instead breaks code extraction.

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#371]
`examples/crypto/mac.fst` used structural equality. This caused subtle bugs when extracting crypto examples. 

See https://github.com/hoheinzollern/FStar/commit/e1ac94e86138c2951c91e2769ea3a0a2d7057b3d .

**Comment by markulf** [comment]
Santiago invested a bit more:

`Platform.Bytes` defines `type bytes = Seq.seq byte` and `=` in `lib/Seq.fsi` is defined extensionally: https://github.com/FStarLang/FStar/blob/master/lib/seq.fsi#L86

But `=` of the OCaml implementation for Bytes doesn't have the same property. Can we map `=` to `equalBytes` in the OCaml implementation?

**Comment by msprotz** [comment]
Two things.
1) @wangpengmit has been working on this; can you give us an update?
2) @aseemr @aseemr-msr one of these two guys is working on a new branch that properly deals with types that support or do not support equality in a branch https://github.com/FStarLang/FStar/tree/has_eq_impl

When both these sub-things are finished this can be closed

**Comment by nikswamy** [comment]
Platform.Bytes is on its way out. We will not fix this.
