### ISSUE TITLE
Extraction of standard libraries

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#372]
Some standard libraries are implemented in `lib/ml/` but the OCaml backend nevertheless extracts non-functional code for them. 

```
FStar_All.ml   FStar_IO.ml    FStar_Option.ml  FStar_ST.ml      prims.ml
FStar_Char.ml  FStar_List.ml  FStar_Set.ml     FStar_String.ml
```

Of these, as far as I can tell, only `prims.fst` is not also extracted.

This is confusing especially for beginners.

**Comment by s-zanella** [comment]
I expected the --codegen-lib flag to prevent those files from being generated, or use the ones in the lib/ml folder. But either I'm using it wrong or it does something different from what I expected. Any documentation about what the --codegen-lib flag is welcome.

**Comment by markulf** [comment]
Indeed documentation would be good. The code is here:
https://github.com/FStarLang/FStar/blob/master/src/extraction/codegen.fs#L67


As I understand  it, it is indeed annotation to provide hints to the extracted ML code where to look for library implementations.

For instance the `RPC.ml` target in `examples/crypto/Makefile` uses `--codegen-lib Platform` to tell RPC.ml compilation to look for the `Platform.Bytes` implementation in `contrib/Platform/Platform.ml` rather than in `Platform_Bytes`.

Removing it leads to the following error: 

```
Error: Unbound module Platform_Bytes
```

So the difference is between the module `FStar.Foo` being provided by a file like `FStar_Foo.ml`, and all modlues `FStar.*` being provided in a file `FStar.ml`.

**Comment by catalin-hritcu** [comment]
Feel free to document this on our new wiki:
https://github.com/FStarLang/FStar/wiki/codegen-and-codegen-lib-flags

**Comment by msprotz** [comment]
There is a Makefile.include in ulib/ml that defines default parameters for the libraries that should not be extracted; however, this is brittle. What about using `native module Foo` at the beginning of the file so that 1) fstar knows not to extract it and 2) people do not have to be aware of this caveat?

It is documented on the wiki but agreed it's not the most discoverable thing ever.

**Comment by msprotz** [comment]
@nikswamy has a suggestion:

```
module FStar.List realized as FStar_List
```

this would in turn allow us to get rid of the `--codegen_lib` flag.

```
module Platform.Bytes realized as Platform.Bytes
```

**Comment by beurdouche** [comment]
I like this idea a lot, this would improve usability a lot ;)

**Comment by nikswamy** [comment]
I don't think we will add a syntax extension to mark this.

But, it will be good to prominently note as we document files if a given module as a native implementation. Tagging #1566
