### ISSUE TITLE
Name "FStar.All.ML" not found

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#373]
(Cross posted from https://github.com/FStarLang/fstar-mode.el/issues/20): Processing the bytes.fst library file in interactive mode seems to confuse F*:

```shell
# From the `lib` folder"
$ (cat bytes.fst; echo "#end") | ../bin/fstar.exe --in
<input>(5,21-5,32): Name "FStar.All.ML" not found
fail
```

Did I miss something?

**Comment by jkzinzindohoue** [comment]
The F* command line includes some files, among which all.fst which has the MLeffect.
If has to be included via a build config for instance :
![image](https://cloud.githubusercontent.com/assets/9868015/9978441/9f9ef672-5f26-11e5-8c28-e4212fe3dffb.png)

I do not know if this is a stable feature. If so it should probably be documented somewhere.

**Comment by catalin-hritcu** [comment]
Just filed this usability problem as #374. Closing this.
