### ISSUE TITLE
Make the file inclusion behavior consistent between interactive and batch and get rid of special cases

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#374]
This point already appeared in #364, #373, FStarLang/fstar-mode.el#13, and https://github.com/FStarLang/fstar-mode.el/issues/20#issuecomment-141713135; let's separate this part on which it seems most of us agree: there should be **no special cases** in which files are included through the back door (e.g. only from command line and only if one file is passed as argument). This confuses users big time.

**Comment by markulf** [comment]
+1

**Comment by beurdouche** [comment]
I believe this to be fixed since everything is using `--auto-deps` now.
Closing, feel free to reopen if necessary

**Comment by johanatan** [comment]
I just downloaded the latest fstar.exe for Mac OS X and the fstar-mode for Emacs and am getting the errors reported here: https://github.com/FStarLang/fstar-mode.el/issues/20

for this input file:
```
module Factorial

(* What are some other types you can give to factorial?
   Try writing them and see if F* agrees with you. *)

val factorial: int -> int   // FStar.All.ML not found
val factorial: int -> ML int // Identifier not found: [ML]
val factorial: x:int{x>=0} -> Tot int
val factorial: x:int{x<0 || x>=0} -> ML int
let rec factorial n = if n = 0 then 1 else n * factorial (n - 1)
```

**Comment by catalin-hritcu** [comment]
This should be fixed on the `master` branch. You're probably using an old release (they are all old) and
> if the release you use is old you might be missing out on new features and bug fixes. Please do not report bugs in old releases until making sure they still exist in the master branch (see Building F* from sources section below).

Source for the quote: https://github.com/FStarLang/FStar/blob/master/INSTALL.md#binary-releases

**Comment by johanatan** [comment]
I downloaded the binaries from the website tonight-- I suppose it hosts binaries that are over 3 months old now. 😀

I will try building from source. Thanks!
