### ISSUE TITLE
problematic parenthesis in val declaration: (Curried function, but not total)

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#375]
The following versions of `foo` should all be equivalent:

```
val foo : unit -> unit -> unit
let foo a b = ()

val foo2: unit -> (unit -> unit)
let foo2 a b = ()

type bar = unit -> unit 

val foo3 : unit -> bar
let foo3 a b = ()
```

However, only the first version verifies; the other two fail with

```
Expected a term of type "(unit -> (unit -> unit))";
got a function "(fun a b -> ())" (Curried function, but not total)
```

**Comment by s-zanella** [comment]
```
val foo : unit -> unit -> unit
let foo a b = ()
```
Here `unit -> unit -> unit` is interpreted as `unit -> Tot (unit -> ML unit)`

```
val foo2: unit -> (unit -> unit)
let foo2 a b = ()
```
Here `unit -> (unit -> unit)` is interpreted as `unit -> ML (unit -> ML unit)`

Still, I don't get why F* complains that the definition is not total.

**Comment by s-zanella** [comment]
The flags ` --log_types --print_effect_args` are nice to debug these kinds of errors.

**Comment by ngrimm** [comment]
I see, thanks for the clarification. 
Apparently I can write a function 
```
val foo2: unit -> Tot (unit -> unit)
let foo2 a = let _ = () in fun b -> ()
```
but I cannot use any other effect instead of `Tot`. I find this unintuitive as `Pure` is a sub-effect of `All`, so I thought that every `Tot` function would also be typable with an `ML` effect.

If i have some additional computations, then I can use other effects, so this issue seems to be quite specific to curried functions:
```
val foo2: unit -> ML (unit -> unit)
let foo2 a = let _ = () in fun b -> ()
```

**Comment by nikswamy** [comment]
FYI, the error message now produced is:
```
Expected a term of type "(_:Prims.unit -> (_:Prims.unit -> Prims.unit))";
got a function "(fun a b -> ())" (Function definition takes more arguments than expected from its annotated type)
```

This is annoying, I agree. But not sure why it is tagged a Priority 1.

**Comment by catalin-hritcu** [comment]
`bug375.fst` containing Niklas' original code works well now. Closing.
