### ISSUE TITLE
Something like Coq's "Program"

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#376]
Nik was mentioning today that it would be nice if any proof obligation that's now sent to the SMT could instead be provided manually. This seems like a rather minor engineering effort once we figure out a sound way to do `get_proof` and `give_proof`.

**Comment by catalin-hritcu** [comment]
This is one of the main use cases of our new tactic language (#217), for instance `assert_by_tactic` is similar: https://github.com/FStarLang/FStar/blob/master/examples/tactics/micro-benchmarks/UserTactics.Example1.fst#L155

**Comment by nikswamy** [comment]
See Meta-F*.
