### ISSUE TITLE
Unexpected Error "Type name not found: pure_return"

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#377]
```
type ni_exp (l:unit) = unit -> St2 (double int)

val expr : unit -> Tot (ni_exp ()) 
(* The inlined version works *)
(* val expr : unit -> Tot (unit -> St2 (double int)) *)

let expr () = fun () -> compose2 (fun _ -> 0) (fun _ -> 0) (twice ()) 
```

causes 

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Type name not found: pure_return
```

This can be circumvented by inlining the type `ni_exp`.

**Comment by ngrimm** [comment]
Adding parenthesis around the abstraction fixes the issue
```
let expr () = (fun () -> compose2 (fun _ -> 0) (fun _ -> 0) (twice ()))
```

**Comment by vkanne-msft** [comment]
causes an error in FStar,Heap 
D:\Sources\FStar\lib\FStar.Heap.fst(48,5-48,7) : Error
Invalid identifer 'On'; expected a symbol that begins with a lower-case character

**Comment by nikswamy** [comment]
@vkanne-msft  this repro looks dubious. did you really use the --universes flag, because with that flag we should never look at FStar/lib.

**Comment by vkanne-msft** [comment]
Interesting, without referencing the libraries (and module dependencies in the test file), i am unable to build the test sample.

**Comment by nikswamy** [comment]
Ok, this is a tricky case. Leave it open ... I'll investigate later.

**Comment by s-zanella** [comment]
After updating the code, I can no longer reproduce this and I haven't seen this error message in a while.
