### ISSUE TITLE
type foo = Tot int   causes unexpected Error

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#378]
```
module Bug

type foo = Tot int
```

causes 

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Type name not found: Tot
```

**Comment by aseemr** [comment]
Hi Niklas, ```Tot int``` is a computation type and not a type. So, you have to add a dummy ```unit``` argument, ```unit -> Tot int```.

**Comment by nikswamy** [comment]
It certainly should fail gracefully in this case rather than throwing that exception.

**Comment by vkanne-msft** [comment]
@nikswamy this is still reproducible.

**Comment by s-zanella** [comment]
It no longer throws an exception with `--universes`.
I get just a normal (but somewhat confusing) error message: 

```Identifier not found: [Tot]```
