### ISSUE TITLE
fstar-lang.org is down

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#381]
The webpage http://www.fstar-lang.org/ (and thus also the tutorial) is not reachable since (at least) yesterday.

**Comment by catalin-hritcu** [comment]
We are aware of this, but unfortunately there is little we can do without help from @ad-l.

**Comment by mwookawa** [comment]
:(

**Comment by catalin-hritcu** [comment]
Unfortunately this is taking longer to fix than we thought. Without @ad-l  around we have no control over the fstar-lang.org domain or server, so we temporarily brought up a static copy of the website and tutorial at
http://fstar.gforge.inria.fr/ and http://fstar.gforge.inria.fr/tutorial/tutorial.html
This way people can at least get information on F* and try the tutorial locally on their machine (there is no way to run it online at the moment).

Sorry for the trouble!

**Comment by catalin-hritcu** [comment]
The fstar-lang.org domain seems back in business. No clue what happened.
