### ISSUE TITLE
Gitbook for Fstar

### ISSUE THREAD

**Issue by unbalancedparentheses** [FStarLang/FStar#382]
What do you think of creating a git book for fstar based on the tutorial?

**Comment by catalin-hritcu** [comment]
Sorry, but I don't see the point in formally publishing the F* tutorial.

**Comment by unbalancedparentheses** [comment]
- https://www.fstar-lang.org/tutorial/ is down. https://www.gitbook.com should be always running since it was created by github.

- anybody can easily contribute it sending PRs for changing the mardkown

**Comment by catalin-hritcu** [comment]
I'm still skeptical. Would this support online editing and verification of F* code? That's the only thing we have a hard time bringing back up. It's computationally intensive stuff and we use a dedicated server for that.
