### ISSUE TITLE
Some libraries like  hyperHeap.fst  and  map.fst  cannot be extracted together with their .fsti.

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#384]
Some libraries like `hyperHeap.fst` and `map.fst` cannot be extracted together with their `.fsi`.

As a side remark, we should rename `.fsi` to `.fsti`. 

We get the following error

```
now synthesizing expression :  (includes i j)

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
(hyperHeap.fsi(43,24-43,32)) free Variable includes not found
```

when running 

```
fstar.exe ext.fst classical.fst set.fsi set.fst heap.fst map.fsi listTot.fst hyperHeap.fsi --admit_fsi FStar.Map --admit_fsi FStar.Heap  --codegen OCaml --lax --debug Extreme --trace_error
```

**Comment by vkanne-msft** [comment]
@markulf can you kindly help test this with Universes (it is the default now)

**Comment by vkanne-msft** [comment]
FSIs dont exist anymore. So closing the issue.

**Comment by s-zanella** [comment]
.fsi files should now have extension .fsti. We do have .fsti files for some libraries, so this may as well still be a bug.

**Comment by vkanne-msft** [comment]
Nikhil, comments ?

**Comment by nikswamy** [comment]
but we do extract .fsti+.fst after interleaving them. Do we know of a case where it doesn't work?

**Comment by s-zanella** [comment]
I don't know of any case. 
The issue was about `FStar.HyperHeap`, but we no longer have `FStar.HyperHeap.fsti`. Feel free to close.

**Comment by s-zanella** [comment]
@adl ran into a similar problem today (can we have a minimal example, perhaps in a new issue?)
