### ISSUE TITLE
Confusion between open Seq and open FStar.Seq

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#387]
I'm trying to bring back to life some of Abhishek's code, and it (unsurprisingly) no longer compiles. Among other things, one of the files was complaining about "identifier not found: seq". Replacing `open Seq` with open `FStar.Seq` seemed to fix the problem.

Are there two distinct libraries, or was one renamed into the other at some point? Is this a duplicate of #271?

Thanks,

Jonathan

**Comment by aseemr** [comment]
Hi Jonathan, at the time of making the ICFP release, the F* standard library module names were prefixed with 'FStar.'. Perhaps this code was not in regressions and so did not get changed.

**Comment by catalin-hritcu** [comment]
Aseem is right, this was indeed renamed, and indeed we only updated the code in the regression. In general please add all code that's supposed to work to the regression (either `make -C examples` if the only dependency is F* or `make -C src test` if the code has dependencies on things like OCaml).

**Comment by msprotz** [comment]
Cool, thanks, but then what is it that was being opened with `open Seq`? Is there another `Seq` module somewhere, or is it the semantics of open in F* that when the module is not found, it returns no error?

**Comment by catalin-hritcu** [comment]
That's the broken semantics of `open` (#153).

**Comment by nikswamy** [comment]
Closing this one as it is tracked in #153
