### ISSUE TITLE
Fstar runs out of memory (>10 GB) on simple St code 

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#389]
FStar runs out of memory (on my machine the process is killed after using ~ 10 GB of RAM) for the following very simple ST2 program
```
let a = alloc 0

let test () = a := 0;
              a := 0;
              a := 0;
              a := 0;
              a := 0;
              a := 0;
              a := 0;
              a := 0;
              a := 0;
              a := 0

val test2 : double unit -> St2 (double unit)
let test2 x = compose2_self test x
```
(  https://github.com/FStarLang/FStar/blob/master/examples/relational/out_of_mem.fst )

The memory consumption  seems to depend exponentially with a factor ~3 on the number of assignments used:

Number of assigments | Memory Consumption
----------------------- | -------------------------
  0  assignments | 0.072 GB
  1  assignments | 0.072 GB
  2  assignments | 0.072 GB
  3  assignments | 0.075 GB
  4  assignments | 0.085 GB
  5  assignments | 0.091 GB
  6  assignments | 0.17 GB
  7  assignments | 0.42 GB
  8  assignments | 1.16 GB
  9  assignments | 3.39 GB
  10 assignments | dies at 10.12 GB

Maybe this is expected due to the encoding of ST2, but I'm still surprised that such a simple program is sufficient to make FStar run out of memory.

**Comment by catalin-hritcu** [comment]
Even worse, this has the same memory exhaustion problem even if replacing `St2` with `St`.

**Comment by catalin-hritcu** [comment]
Sorry, I was a bit confused. Seems that replacing `St2` with `St` the way I did only causes a lift at the end, but `compose2_self` is still an `St2` thing.

**Comment by catalin-hritcu** [comment]
This time I really managed to reproduce this using only St (14c37db).

**Comment by s-zanella** [comment]
This is apparently because the inference algorithm is too lazy. Adding a few *checkpoints* in the `test` forces it to be less lazy:

```F#
val f : unit -> State unit (fun 'p h -> 'p () (Heap.upd h a 0))
let f () = a := 0

let test () = a := 0;
              a := 0;
              f ();
              a := 0;
              a := 0;
              f ();
              a := 0; 
              a := 0;
              f ();
              a := 0;
              a := 0
```
Setting the `--eager_inference` flag also makes the example type check almost instantly. We tried with Niklas the most hairy example he had using `St2` and adding this flag makes it type check.

Curiously, setting the flag somewhere in the file rather than specifying it from the command-line or in a build-config, doesn't seem to work. That is, `#set-options "--eager_inference"` doesn't seem to have any effect.

**Comment by nikswamy** [comment]
Worrying. Thanks for tracking all of this down ... this is very informative bug report. 

I will probably defer fixing this in master and instead address it in the universes branch.

**Comment by vkanne-msft** [comment]
Needs #569

**Comment by s-zanella** [comment]
Cannot reproduce anymore.
