### ISSUE TITLE
Confusing parsing error when defining a "print" function

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#390]
This is a syntax error:

```
module Test

let print e =
  ""
```

This isn't.

```
module Test

let pprint e =
  ""
```

I didn't see this mentioned anywhere on the tutorial. Is that normal?

**Comment by aseemr** [comment]
print seems to be a keyword in the language (https://github.com/FStarLang/FStar/blob/master/src/parser/ml/lex.mll#L69).

**Comment by msprotz** [comment]
the only occurrence of "print" that I could find in the source code was in `old/to_be_ported/monadic/iflow.fst`. Is it a remnant of the old F* or perhaps was to be used for some debugging?

**Comment by nikswamy** [comment]
does seem to be a remnant from an ancient parser

**Comment by nikswamy** [comment]
Probably got ported to lex.mll from lex.fsl/lexhelp.fs; then we improved the fs version but the ML version lagged. So, probably, Jonathan's issue is specific to the OCaml binary of F*
