### ISSUE TITLE
Unexpected error: BatUChar.Out_of_range

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#391]
```
protz@Joprotze-Z420:~/Code/fstar-priv/papers/low-level/code (master) $ fstar --codegen OCaml $(cygpath -d /tmp/test.fst)

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
BatUChar.Out_of_range
protz@Joprotze-Z420:~/Code/fstar-priv/papers/low-level/code (master) $ cat /tmp/test.fst
module Test

let s = "×"
```

(Notice the character "×", not "x").

This is not the semantics of OCaml strings, which are just strings of bytes; if they happen to be multi-byte utf-8 sequences, well that's just life, and they pass through "as is", then if the terminal of the user happens to be utf-8 too, everything works out in the end.

**Comment by s-zanella** [comment]
This now succeeds and extracts the character "×" as 0xC3 0x83 0xC2 0x97.
Not sure if this is what we want. The multiplication sign in UTF8 is 0xC3 0x97.

**Comment by msprotz** [comment]
Huh no that's not good. I thought I had changed the strings to be completely pass-through, but the behavior is still incorrect.

**Comment by s-zanella** [comment]
Closing the original issue. Opened #556 to track the new one.
