### ISSUE TITLE
Unexpected errors should at least print the file that triggered them

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#392]
Cf #391 -- fortunately I knew which file the error was in, so I was able to produce a minimal test case, but with 10 files on the command-line, it's a struggle to figure out where exactly the error came from.

**Comment by catalin-hritcu** [comment]
I also find the completely uninformative way Unexpected errors are handled quite pathetic. Nik seems to want this behavior though, so I won't try again to fix this.

**Comment by aseemr** [comment]
We have had significant revisions of invoking and using F*, e.g. only one command line file at a time etc. Closing this issue since it seems outdated.
