### ISSUE TITLE
fstar --help should document what happens with --codegen

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#393]
Here's the specification that I inferred by playing around. Feel free to correct it if it's wrong.

```
--codegen OCaml|FSharp Generate code for execution. For every "module M" directive found in any of the .fst files passed on the command-line, write out to disk a corresponding "M.(ml|fs)" file in the current working directory. For prefixed modules such as "FStar.Heap", the file is FStar_Heap.(ml|fs).
```

**Comment by s-zanella** [comment]
`write out to disk a corresponding "M.(ml|fs)"` ...except when there is a corresponding `--codgen-lib` flag.

The meaning of `--codegen-lib` should also be specified (see #372).

**Comment by catalin-hritcu** [comment]
Feel free to document this on our new wiki:
https://github.com/FStarLang/FStar/wiki/codegen-and-codegen-lib-flags

**Comment by msprotz** [comment]
If I want to document something, where should it go? Right now, we have the tutorial, the README.md, the --help flag, the doc folder, and the wiki? Is there a rule to determine what goes where?

**Comment by catalin-hritcu** [comment]
Here is my take on this:
- the `--help` flag is only for one line (80 chars) descriptions not for complete documentation
- the Wiki is for in-depth technical documentation (think reference manual)
- the Tutorial is for getting new users quickly up to speed

You should not use `README.md` or the `doc` folder for documentation. I know this was previously done for `README.md`, but I don't think that's a good idea, and I've moved all those things to the wiki recently.

**Comment by msprotz** [comment]
https://github.com/FStarLang/FStar/wiki/Executing-F*-code done
