### ISSUE TITLE
Add a `--codegen-module M` flag

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#395]
Discussed this with @markulf,  but there doesn't seem to be an issue opened for this feature request.

This flag would behave similarly to `--verify-module M`, telling F\* to extract code for `M`, but not any other files mentioned in the command line.

Also, it would be nice if both these flags could take lists of module names, rather than a single one.

**Comment by markulf** [comment]
This should be simple, but still better make a plan to make sure we know what we are doing:

* Add the new option to
  https://github.com/FStarLang/FStar/blob/master/src/basic/options.fs .
* Make this iterator write only files specified in  `--codegen-module M`
https://github.com/FStarLang/FStar/blob/master/src/fstar/fstar.fs#L265 .

Is that the semantic we want? 
Is some of the other work unnecessary if we want to only extract some files? 
How does this interact with build-config and interactive?

**Comment by prosecco** [comment]
I propose that we use two flags:
—verify-only M1,…Mn will verify only these modules (default is to verify everything)
—codegen-only M1,…Mn will gen code for only these modules

I’ve been looking at fstar/fstar.fs and it seems it would be quite simple to implement these.
I can take a crack at it next week, unless someone beats me to it.

-K.

**Comment by s-zanella** [comment]
Then `--verify-only M1 ... Mn` would behave exactly as `--verify-module M1 ... --verify-module Mn`
That means we should deprecate `verify-module` and remove it at some time.

**Comment by catalin-hritcu** [comment]
@s-zanella Is any of this still needed now?

**Comment by s-zanella** [comment]
The command-line options that @prosecco proposed above are now implemented in `--extract_module` and `--verify_module`, except that they take single modules rather than lists of modules. 

Here are all relevant command-line options:
```
--extract_all  Discover the complete dependency graph and do not stop at interface boundaries
--extract_module [module name]  Only extract the specified modules (instead of the possibly-partial dependency graph)
--extract_namespace [namespace name]  Only extract modules in the specified namespace
--no_extract [module name]  Do not extract code from this module
--verify_all  With automatic dependencies, verify all the dependencies, not just the files passed on the command-line.
--verify_module [module name]  Name of the module to verify
```

Also, see the relevant discussion in #908.

Closing this and opening a new issue to track extending the command-line options that take a module as parameter to lists of modules.
