### ISSUE TITLE
Some proofs in seqproperties extremely flaky, admitted for now

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#396]
Some of the proofs in `seqproperties.fst` like those for `split_5` and `lemma_swap_slice_commute` are **extremely** flaky. They have unpredictable failure behavior that seems to depend on lots of things:
- like the power and load of the machine
- the contents of the rest of the file, even definitions that appear **after** the failing ones
- the name of the file in which they reside
- whether the `--logQueries` flag is set or not

I've admitted these proofs until we figure out what is happening and come up with reliable proofs.

PS: Here are the error messages for `lemma_swap_slice_commute`
```
[hritcu@detained pub]$ fstar.exe --admit_fsi FStar.Set --admit_fsi FStar.Seq set.fsi heap.fst st.fst seq.fsi classical.fst seqproperties.fst    
seqproperties.fst(304,0-304,137): post-condition at seqproperties.fst(303,23-303,105)
seqproperties.fst(304,47-304,137): assertion failed
Error: 2 errors were reported (see above)
```
and `split_5` (although for this one sometimes the error is just `Unknown assertion failed`):
```
seqproperties.fst(191,0-191,27): post-condition at seqproperties.fst(187,16-187,
48)
```

**Comment by vkanne-msft** [comment]
No more admits in seqproperties. Closed
