### ISSUE TITLE
Unexpected error: Not_found

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#401]
```
protz@Joprotze-Z420:/tmp $ fstar b.fst

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Not_found
protz@Joprotze-Z420:/tmp $ cat !$
cat b.fst
(*--build-config
    other-files: c.fst
*)

module B
```

**Comment by aseemr** [comment]
Hi Jonathan, what is the bug here ? The error message not informative (that c.fst is not found), or you do have c.fst, and it still gives the error ?

**Comment by msprotz** [comment]
The Not_found is actually an OCaml exception. It's because I forgot the closing "--" in the build-config special comment. This actually doesn't have anything to do with c.fst (which did exist).

Sorry, I should've been more specific in my bug report.

**Comment by beurdouche** [comment]
Build configs are not parsed anymore.
Closing
