### ISSUE TITLE
requires vs. refinement on argument

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#403]
F* properly accepts this:

```
val tail_rids_commute: s:regionStack{is_Cons s} ->
  Lemma
    (ensures (ridsSt s = fst (Cons.hd s) :: ridsSt (Cons.tl s)))
```

however,

```
val tail_rids_commute: s:regionStack ->
  Lemma
    (requires (is_Cons s))
    (ensures (ridsSt s = fst (Cons.hd s) :: ridsSt (Cons.tl s)))
```

complains that the subtyping checked failed for the argument of `Cons.tl`. Is this expected?

**Comment by aseemr** [comment]
It's a known issue (#57). The workaround is to either use the refinement (as you have), or repeat ```is_Cons s``` in the ```ensures``` clause too (i.e. ```ensures (is_Cons s /\ ...)```.

**Comment by msprotz** [comment]
Oh right I recall that Nik had mentioned it at some point a while ago. My bad.

We should change section 3.3.2 of the tutorial then; because the claim that Lemma (requires) is syntactic sugar for a refined argument is not true.

**Comment by catalin-hritcu** [comment]
> We should change section 3.3.2 of the tutorial then; because the claim that Lemma (requires) is syntactic sugar for a refined argument is not true.

That would be documenting a bug (#57). The better solution is to fix it.

**Comment by catalin-hritcu** [comment]
Let's track this problem in #57. Closing.
