### ISSUE TITLE
Spurious syntax error with dependent pairs (only occuring with FSharp build)

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#404]
The follwing code 

```
(* Adding this line fixes the issue *)
//type bar (i:int) = int

val foo : (i:int & int)
let foo = (| 0, 0 |)
```

causes a syntax Error when using the FSharp build.
When using the ocaml binary the file verifies correctly.

Strangely, adding the commented type declaration fixes the issue.

**Comment by s-zanella** [comment]
See also #356 for another example of divergence between the OCaml and F# binaries.

**Comment by catalin-hritcu** [comment]
This also reminds me #252, which also disappeared if adding a type declaration.

**Comment by catalin-hritcu** [comment]
#252 happens with both the OCaml and the .NET binary though.

**Comment by catalin-hritcu** [comment]
I can confirm that this parsing issue still appears with `--universes` and the FSharp build.
```
[hritcu@detained bug-reports]$ fstar.exe --universes bug404.fst
/home/hritcu/Projects/fstar/pub/examples/bug-reports/bug404.fst(6,22-6,23) : Error
Syntax error
```

**Comment by nikswamy** [comment]
Is this really Priority 1? I'd be delighted if someone fixed the F\# lexer ... but I'm not going to get around to it anytime soon myself.

**Comment by kyoDralliam** [comment]
fixed with the menhir parser
