### ISSUE TITLE
Unknown assertion failed for trivial refinement -- broken logical encoding

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#405]
This is a strange error for which I coudln't find a workaround. 

```F#
(*--build-config
    options:--admit_fsi FStar.Set --print_implicits --log_types;
    other-files:set.fsi heap.fst st.fst all.fst
--*)

module M

type t // = unit is a model for t
(* Definition of v below typechecks without {True} refinemenet *)
type F = f:(t -> Tot t){True}

assume val x: t

assume val y: t

assume val f: F

assume val g: f:F -> Tot (u:unit{f x = y})

val v: u:unit{f x = y}
let v = g f
```

**Comment by ngrimm** [comment]
I tried the FSharp-Build and the OCaml binary and cannot reproduce this on my machine (on 64-bit Linux).

**Comment by aseemr** [comment]
This works for me as well (Mac, F# and OCaml).

**Comment by s-zanella** [comment]
I can reproduce it on both Mac and Windows with F# and OCaml binaries. Could it be Z3? I'm using Z3 4.3.2.

**Comment by aseemr** [comment]
Yep, I get the error with Z3 4.3.2, not with Z3 4.4.0.

**Comment by s-zanella** [comment]
It *is* Z3. Z3 4.4.0 works just fine.

**Comment by ngrimm** [comment]
This issue is occuring again with Z3 4.4.1 (official release) and Z3 4.4.2 (built from the currenct github source)

**Comment by s-zanella** [comment]
I can also reproduce it with Z3 4.4.1.

The problem with the above example is with the encoding of `M.f`. The encoding declares it as a function with no arguments `(declare-fun M.f () Term)`, and later on there is an assertion where `M.f` is applied to `M.x`. Somehow Z3 4.4.0 doesn't complain but Z3 4.4.1 does. I think this is a genuine bug in the F* encoding (and possibly in Z3 4.4.0).

```
(assert (not (or label_2765
   (implies (Valid (Prims.b2t (Prims.op_Equality M.t
     (M.f M.x)
     M.y)))
```

**Comment by catalin-hritcu** [comment]
Thanks for tracking this down Santiago. We should really not be swallowing Z3 errors but stop the press completely when we feed crap to z3! (#248)

**Comment by s-zanella** [comment]
I just saw that with both Z3 4.4.0 and 4.4.1 there are other errors in the output (as in #248):

`(error "line 28580 column 16: model is not available")`

The difference between 4.4.0 and 4.4.1 is that the answer we get with 4.4.1 is `unknown` while 4.4.0 answers `unsat`. In any case, if we didn't ignore Z3 errors we would have caught this before. At any rate, we shouldn't ignore errors.

**Comment by nikswamy** [comment]
The `model is not available` errors are normal. 
We call Z3 asking it to check-sat and then evaluate a bunch of terms in the model, in case there is one, to provide an error report. 
If the query succeeds (i.e., is unsat), then those evaluations will fail, as expected.
We should not ignore all Z3 errors. But, we need to ignore model is not available.

**Comment by vkanne-msft** [comment]
Verified works with Z3 4.4.1
