### ISSUE TITLE
Trivial proof of False

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#406]
Santiago and I just came accross this when looking at #405.
```
val v : u:unit{False}
let v = ()
```

Things that to do not work:
```
let v: u:unit{False} = ()
```
```
val v: u:bool{u = false}
let v = true
```

Also, including `all.fst` seems to be important for this to work.
Maybe related: #289, #311

**Comment by s-zanella** [comment]
`--warn_top_level_effects --cardinality warn` don't give any warning about whatever may be going on.

**Comment by aseemr** [comment]
The SMT encoding of type u:unit{False} says:

forall x. x has type u:unit{False} iff  false

which is fine.

But then before checking that () has type u:unit{False}, the SMT encoding is first asserting that:

v has type u:unit{False}

which brings false into Z3's context, and after that anything is provable. If we remove this assertion, then the proof fails as it should.

Not sure which cases require type of v to be asserted before type checking its body.

**Comment by s-zanella** [comment]
Thanks @aseemr for looking into this. 
Do you have a good intuition of why ALL needs to be in the effect lattice for this to work?

I'm guessing that a `let rec` requires its type to be asserted before checking the body.

**Comment by aseemr** [comment]
I think the inclusion of all.fst is related to #311. Even this code does not type check without all.fst:

val v: n:nat{n > 2}
let v = 3

**Comment by nikswamy** [comment]
Silly bug, sorry. The `val` should not need to be in the environment in this case. It is also not needed for `let rec`. Will fix ASAP.
