### ISSUE TITLE
How can we start FStar

### ISSUE THREAD

**Issue by AnastasiyaRagozina** [FStarLang/FStar#408]
Hi, I cloned your repository and try to start your examples. I build src and try to start:
```
FStar.exe --odir out --codegen FSharp ...\FStar\examples\hello\hello.fst
```
And we have exception:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
The type initializer for '<StartupCode$tosmt>.$FStar.ToSMT.Z3' threw an exception.
```

I installed https://github.com/Z3Prover/z3/releases/tag/z3-4.4.0. OS windows 8, visual studio 2015. 

Maybe, Do you have any ideas what problem is? 

It seems like #159 , but I didn't use cygwin, the project was built in VS. 

Thanks.

**Comment by catalin-hritcu** [comment]
1. Can you confirm that z3 is in your path?
2. How did you build F*?
3. If you use F#, then what version ?

**Comment by s-zanella** [comment]
See also #308 for a similar issue with VS.

As a workaround, you can use the OCaml binary built using `make -C src/ocaml-output`
To install native OCaml on Windows, you can use http://protz.github.io/ocaml-installer/

**Comment by catalin-hritcu** [comment]
Let's first see what the problem is before talking about workarounds. There are a ton of problems that manifest themselves this way.

**Comment by gsvgit** [comment]
Thanks. This problem solved. Also I hope that my pr can help to solve some problems from issue #308.
