### ISSUE TITLE
Discussion about continuous integration

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#411]
The website is up again (#381) but Strider integration is still down.
It used to be at https://www.fstar-lang.org:3443/

**Comment by catalin-hritcu** [comment]
We'll can try to work on fixing this after moving to a new server under our control. Hopefully soon, but don't hold your breath. Volunteers welcome, of course.

**Comment by s-zanella** [comment]
Give me a server and I can do it.

**Comment by markulf** [comment]
Would be great, I can also help.

**Comment by beurdouche** [comment]
We could also setup an instance of F* for Travis instead of creating our own CI…
I guess it is less flexible though ?

**Comment by s-zanella** [comment]
I think we do need the extra flexibility of having our own server or VM instance: we need to test several platforms, we depend on OCaml and F# compilers, and typechecking in F* uses significant resources.

There are plenty of free, hosted CI services we could use, but I don't think that any of them allows to do everything we want. We could use Travis to do some of those things as a temporary solution, though.

**Comment by catalin-hritcu** [comment]
I don't think we seriously considered VMs for something other than Linux so far. I don't think that Mac OS can be legally installed in a VM, and a Windows WM might cause security and maintenance trouble. We could still discuss though, at least for creating releases and nightly builds it might be useful.

**Comment by prosecco** [comment]
For nightly testing and regression, we will need to run VMs for linux + windows; but for the web-facing servers we’ll only use linux VMs.

-K

**Comment by s-zanella** [comment]
I noticed the Strider server is now back up. That's excellent news, I hope it's not just temporary.

**Comment by catalin-hritcu** [comment]
@s-zanella That's Jenkins not Strider. I even forgot we had that set up on https://ci.inria.fr
It doesn't do much on each commit at the moment (only `make -C src`) but we could set up it so that it runs bootstrapping and more tests. If you would like access to it please make an account on https://ci.inria.fr and send me your credentials by email.

**Comment by s-zanella** [comment]
@catalin-hritcu Hmmm. The one on https://www.fstar-lang.org:3443 is Strider and it appears be working as it used to do. I've created an account on https://ci.inria.fr with my MSR address (first name at microsoft.com).

**Comment by catalin-hritcu** [comment]
True, it seems we have 2 CI servers at the moment, and only the Jenkins one sends emails, so I missed the fact that the Strider one also come back up. I have no clue why Strider was down and why it came back up now. It seems to still be running on Antoine's server, so no big changes yet. I've added you as admin on Jenkins and will also send you an invite for Strider.

**Comment by s-zanella** [comment]
Thanks! 
(I don't seem to be an admin on Jenkins, but that's fine.)

**Comment by vkanne-msft** [comment]
We now use Travis and it is functional. Closing this issue.
