### ISSUE TITLE
Github logo

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#412]
It would be neat to have the F* logo shown as the Github organization's profile picture :)

**Comment by catalin-hritcu** [comment]
Done

**Comment by nikswamy** [comment]
How about using the new color scheme on both github and fstar-lang?

![fstar-logo-5x5-1](https://cloud.githubusercontent.com/assets/6163359/10615927/6289e1c6-7717-11e5-89b9-4bd894ec7958.png)

**Comment by beurdouche** [comment]
+10 =P

**Comment by catalin-hritcu** [comment]
Done :)
