### ISSUE TITLE
fstar main function is not clean, so can not be reexecuted

### ISSUE THREAD

**Issue by gsvgit** [FStarLang/FStar#414]
In order to create MSVS extension I try to run main function multiple times. New  main function code presented below (fstar\fstar.fs)

```
let main () =
    try
      printfn "---First session";
      go ();
      cleanup ();
      printfn "\n---Second session";
      go ();
      cleanup ();
```

I use simple correct file as an input. Result of first run is Ok, but second session is failed. How can I create "clean" sessions?  Seems, that something is cached and cleanup function miss it.

```
---First session
Verifying module: FStar.Set
Verifying module: FStar.Heap
Verifying module: FStar.ST
Verifying module: FStar.All
Verifying module: FileName
Verifying module: ACLs
Verifying module: FileIO
Verifying module: UntrustedClientCode
All verification conditions discharged successfully

---Second session

Unexpected error; please file a bug report, ideally with a minimized version of
the source program that triggered the error.
Impossible: Got a computation Prims.Tot with effect args []
Press any key to continue . . .
```

**Comment by markulf** [comment]
Plenty of state in the `FStar.Options` module, e.g. 

@nikswamy would know whether `go ()` was ever intended to be used like this. But this seems like useful property to have.

**Comment by gsvgit** [comment]
Not only FStar.Options module may be a source of problem because there are many other modules with top level mutable bindings. 

I try to reset (possibly) all fields in FStar.Options but problems still occur. Any other ideas why Prims  verification steps may be changed  on session rerunning.

**Comment by nikswamy** [comment]
Can you say more about why you're trying to run 'go' multiple times?

Even if we did manage to make it possible to do this, it's not clear that this is the right way to support interactive editing/verification in Visual Studio (or any other editor). 

For the other editor modes (emacs, Atom etc.), we start a single F\* process, keep it open, and write to that process, marking rollback points with push, and resetting the state with pop. I would have expected something like that to work well for VS also.

**Comment by gsvgit** [comment]
Current version is implemented as you describe (we run F* in isolated process).  But cross process communication is hard for complex data transferring. It may be necessary to get more than error messages back from FStar for some IDE functions implementation, and "hidden" side effects can make it impossible to call functions like 'go' directly.

**Comment by vkanne-msft** [comment]
@gsvgit Contributions welcome. Leaving the issue open.

**Comment by nikswamy** [comment]
This is an old issue.

Meanwhile, we have made many parts of the typechecker backtrackable. F* flycheck-mode relies on this to typecheck terms speculatively. Though the top-level, including extraction etc. remains effectful

Please re-open if needed.
