### ISSUE TITLE
F* should fail when module mentioned by --verify-module flag is not present

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#415]
@s-zanella  reports that "F* not warning about useless --verify-module flags, gave the impression that everything verified instantly"

**Comment by s-zanella** [comment]
Files are processed sequentially, so F* would only know that it has to fail at the very end. Still, we want that a make target running F* several times fails as early as possible. 

In brief, the desired behaviour would be: warn and terminate with a non-zero exit code when there is a `--verify_module M` flag, but after processing all files no module `M` was ever found.

**Comment by msprotz** [comment]
Fixed via f81093399b85245a4cdc01d0e14c8dbd8e76e1cb
