### ISSUE TITLE
Easy opportunity for a better error message about decreases

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#418]
I'm getting "subtyping check failed: expected _some_internal_id:τ{ unreadable decreases clause }; got τ.

I think the shape of the error message is simple enough that maybe the error printer could match on it and print something along the lines of "could not find a decreasing argument"?

**Comment by parno** [comment]
Seems like a great idea.  Otherwise, that error message is a beast to decipher (I was lucky enough to first encounter it while Nik was in the room, but that doesn't seem like a scalable solution).

**Comment by msprotz** [comment]
Other easy opportunity: using `*` for multiplication when `FStar.Mul` is not in scope.

Other easy error message fix: name not found, suggest restarting the emacs mode when in interactive mode.

**Comment by mtzguido** [comment]
For the decreases clause, I think we can just wrap a custom message (`Meta_labeled`) around it when we build it, as we do for other things, instead of matching on the output. Doesn't sound too scary to do, so I might attempt it soon.

**Comment by parno** [comment]
Cool, this is a definite improvement!  I agree that the second one could still use some cleaning, but having an actual termination error message should be a lot easier for anyone who bumps into it.  Thanks Guido!

**Comment by msprotz** [comment]
Thanks Guido, this is great. This issue has also been reported by Kevin Kane and numerous other people. I think this will make a huge difference.

**Comment by nikswamy** [comment]
Closing this issue, The remaining aspect of not shadowing in the error message in case 2 is an instance of a more precise printing of the expected type in an error message, for which we have issue #2034
