### ISSUE TITLE
Assigning reference to variable breaks verification

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#424]
In the following example, just assigning the reference to a variable before reading it breaks verification.
Any idea why ? I am labelling it as a bug for now, for usability this is quite problematic.

```F#
(*--build-config
    options:--admit_fsi FStar.Seq --admit_fsi FStar.Set --verify_module Bug;
    other-files:classical.fst ext.fst set.fsi seq.fsi seqproperties.fst heap.fst st.fst all.fst arr.fst ghost.fst
  --*)

module Bug

open FStar.Heap
open FStar.ST
open FStar.Array

type lint (n:nat) = x:nat{ x < n }

type box2 = | B: size:pos -> v:FStar.Heap.ref (lint size) -> box2

val get_size: box2 -> Tot pos
let get_size b = B.size b

val get_ref: b:box2 -> Tot (ref (lint (get_size b)))
let get_ref b = B.v b

val get_val: 
  b:box2 -> 
  ST (lint (get_size b))
    (requires (fun h -> contains h (get_ref b)))
    (ensures (fun h0 v h1 -> (h0==h1)
			  /\ (contains h0 (get_ref b))
			  /\ (sel h0 (get_ref b) = v)))
let get_val b = ST.read (get_ref b) // Succeeds

(* Fails immediately *)
//let get_val b = let r = get_ref b in ST.read r

(* Fails as well 
let get_val b = 
  match b with
  | B _ r -> ST.read r *)
```

**Comment by s-zanella** [comment]
Adding type annotations/subtyping constraints helps:
```F#
(* Succeeds *)
let get_val b = let r:ref (lint (get_size b)) = get_ref b in ST.read r

(* Succeeds *)
let get_val b = 
  match b with
  | B _ r -> ST.read (r<:ref (lint (get_size b)))
```
Setting `--eager_inference` also works.

Side remark: Nikhil's recent changes made it possible to write `b.v` instead of `B.v b`, as if `b` was a record (it works for inductive types with a single constructor).

**Comment by jkzinzindohoue** [comment]
Thanks Santiago.

My concern is about traceability of such things. The failing post condition is this case was `sel h0 (get_ref b) = v`, it is not obvious to me why adding typing information on the reference helps, and why it was not simply infers since it is the exact type returned by the `get_ref` function.

Also I am confused about what `--eager_inference` does. I expected is to be more restrictive and improve verification speed. Here it does not seem to be a timeout issue, it fails immediately.

**Comment by nikswamy** [comment]
'--eager_inference' should be disabled. It's extremely non-standard and was there to support a transition from the old inference algorithm to the current one. I don't think anyone has used this flag very much.

**Comment by nikswamy** [comment]
The failure of inference when you add the let binding is puzzling. It's fair to call this a bug. We shouldn't need the type annotation.

**Comment by s-zanella** [comment]
There seems to be something wrong with the SMT encoding. This is a simpler example:

```F#
(*--build-config
    options:--admit_fsi FStar.Set --verify_module Bug;
    other-files:classical.fst ext.fst set.fsi seq.fsi heap.fst st.fst all.fst
--*)

module Bug

type f (t:Type)
// making this opaque lets the program check
type t (u:unit) = x:int{u = ()}
type box = | B: v:f (t ()) -> box

val get: b:box -> St (f (t ()))

(* Fails immediately with 'Unknown assertion failed' *)
let get b = let r = b.v in r

(* Succeeds *)
// let get b = b.v

(* Succeeds *)
// assume val recall_type: a:Type -> x:a -> Tot unit
// let get b = recall_type (f _) b.v; let r = b.v in r
```

This is the (simplified) assertion that Z3 verifies to check the definition that succeeds:

```
(not (forall ((@t Type) (@x Term))
        (implies (and (HasKind @t Kind_arrow_1603)
                      (HasType @x heap)
                      (forall ((@y Term) (@z Term))
                         (implies (and (HasType @y (Bug.f Typ_refine_1602))
                                       (HasType @z heap))
                                  (Valid (ApplyTE (ApplyTE @t @y) @z)))
                      ) // forall
                 ) // and
                 (forall ((@r Term))
                    (implies (and (HasType @r (Bug.f Typ_refine_1602))
                                  (= @r (Bug.B.v b___8_8)))
                             (Valid (ApplyTE (ApplyTE @t @r) @x))

                    ) // implies
                 ) // forall
        ) // implies
     ) // forall
) // not
```

While this is the one that fails:

```
(not (forall ((@t Type) (@x Term))
        (implies (and (HasKind @t Kind_arrow_1603)
                      (HasType @x heap)
                      (forall ((@y Term) (@z Term))
                         (implies (and (HasType @y (Bug.f Typ_refine_1602))
                                       (HasType @z heap))
                                  (Valid (ApplyTE (ApplyTE @t @y) @z)))
                      ) // forall 
                 ) // and
                 (Valid (ApplyTE (ApplyTE @t (Bug.B.v b___8_8)) @x))
         ) // implies
      ) // forall
) // not
```

To check that this is unsat, it would be enough to prove 

`(HasType (Bug.B.v b___8_8) (Bug.f Typ_refine_1602))`

but Z3 says 'unknown' to 

`(assert (not (HasType (Bug.B.v b___8_8) (Bug.f Typ_refine_1602))))`

**Comment by vkanne-msft** [comment]
Not reproducible on Master using bug424.fst

**Comment by s-zanella** [comment]
I can still reproduce this on master using bug424.fst.

Note that this only affects the stratified type checker, so we don't care about it now.

**Comment by nikswamy** [comment]
As a general rule. @vkanne-msft  is closing all bugs not reproducible with --universes.

**Comment by nikswamy** [comment]
I've updated the name of the label to "needs confirmation with --universes" to make it a bit clearer that this is our policy.
