### ISSUE TITLE
Unpredictable behavior with quantified formulas that have no patterns

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#426]
I have trouble minimizing this issue because it disappears when the code gets smaller, here is what I get:

```F#
val fsum:
  a:bigint -> a_idx:nat -> b:bigint{...} -> b_idx:nat -> len:nat -> ctr:nat{ ctr <= len } ->
  ST unit
    (requires (fun h -> (...)
      // Notice the order of the terms in the addition
      /\ (forall (i:nat{i >= ctr /\ i < len}). getSize h a (i+a_idx) < wordSize a)
    ))
    (ensures (fun h0 _ h1 -> (...)
    ))

let rec fsum a a_idx b b_idx len ctr =
  match len - ctr with
  | 0 -> admit()
  | _ -> 
      let h1 = ST.get () in
      let i = ctr in
      let ai = index a (a_idx+i) in
      let size_ai = getSize h1 a (a_idx+i) in
      assert(a_idx + i = i + a_idx); // Necessary assertion
      assert(size_ai <= (wordSize a - 1)); // Fails without the assertion above
      admit();
```

The `assert` is sufficient, I do not need to put a `cut` there. But it means that without help Z3 cannot figure that out, it needs a trigger of some sort, which I find very unexpected and difficult to work with.

**Comment by nikswamy** [comment]
You have a quantified assertion in the context (the requires clause) without an explicit pattern.
This is always risky. Z3 will then pick some arbitrary term from the body of the formula as a pattern. The term it picks need not even be a term that appeared in the source program... it could be some term that appeared after the encoding. 
In this case, I suspect Z3 picked the trigger to be the encoding of `(i + a_idx)`. So, unless such a term appears somewhere in the active terms of your proof, the requires clause is useless. 
I bet your program would go through even with a `assert (i + a_idx = i + a_idx)`. The content of the assertion is not important ... it's the presence of the `i + a_idx` that counts.

The fix would be to write a pattern for the quantifier. Not sure if there's a good intrinsic pattern though.

**Comment by catalin-hritcu** [comment]
@jkzinzindohoue Were you able to confirm Nik's hypotheses?

**Comment by jkzinzindohoue** [comment]
Yes, it is a trigger issue.
I still think that for usability it is an issue, but I guess there is no easy way around when using quantifiers with SMT solvers.
Closing

**Comment by catalin-hritcu** [comment]
Would it help if F* warned you every time you have quantifiers without triggers?

**Comment by jkzinzindohoue** [comment]
I believe not, because as Nikhil said I am not sure what the trigger should be and I am using a lot of such properties: `forall (i:nat). P (i)`. 
A typical case would be : `forall (i:nat). P(i+idx)` would not be triggered by `idx+i`. But if would not be either by `i` when `idx = 0` or on any other expression that is not exactly the initial one.
I think that one needs to be aware of the fact that the SMT will indeed have an unpredictable performances in such cases, and that they should use the exact original expression although it makes it more painful.
