### ISSUE TITLE
max_fuel greater than 18 no effect

### ISSUE THREAD

**Issue by Potpourri** [FStarLang/FStar#427]
See these examples:
```
// This code work OK
module Test

#set-options "--initial_fuel 18 --max_fuel 18 --z3timeout 10000"

val rec_fun: x: int -> Tot int
let rec rec_fun x = if x <= 1 then 100 else rec_fun (x - 1)

let assert_fun = assert (rec_fun 18 > 0)
```
```
// This code don't work
module Test

#set-options "--initial_fuel 19 --max_fuel 19 --z3timeout 10000"

val rec_fun: x: int -> Tot int
let rec rec_fun x = if x <= 1 then 100 else rec_fun (x - 1)

let assert_fun = assert (rec_fun 19 > 0) // this line got `assertion failed`
```
I tested on linux with F*:
```
F* 0.9.1.1
platform=Linux_x86_64
compiler=OCaml 4.02.3
date=2015-10-13T10:18:59+0200
commit=c41ea17
```
and on https://www.fstar-lang.org/run.php

**Comment by catalin-hritcu** [comment]
max_fuel greater than 18? What are you trying to do? :)

**Comment by nikswamy** [comment]
Relying on the SMT solver to do heavy reductions like this is not a good idea. 

On some other issue (can't find it now) we have a proposal for supporting this sort of scenario by relying on F\* reduction machinery rather than SMT.

**Comment by catalin-hritcu** [comment]
This question seems answered, and improvements will be further discussed in #357 and #267.

**Comment by nikswamy** [comment]
FYI, the original program is now provable with fuel 19 in just 45 milliseconds.

(.\test.fst(7,59-9,40)) Query (Test.assert_fun, 1) succeeded in 45 milliseconds with fuel 19 and ifuel 1

The relevant change that enabled this is from src/smtencoding/encode.fs in commit 6e350f905d33671fb0bbeb21d843e70f7f232c96

```
 +                    //NS 08/10: Setting the weight of this quantifier to 0, since its instantiations are controlled by F* fuel
 +                    let eqn_g = Term.Assume(mkForall'([[gsapp]], Some 0, fuel::vars, mkEq(gsapp, body_tm)),
```
