### ISSUE TITLE
[Question] Compatibility with OCaml 

### ISSUE THREAD

**Issue by gsvgit** [FStarLang/FStar#428]
Is it possible to use standard F#/.NET libraries in F* core for error logging, cmd args parsing, etc? Is it possible to make F* code more F#-friendly?

**Comment by nikswamy** [comment]
We try to write as much of the code in F\* as possible, only leaving fundamentally platform-specific stuff to external libraries. Doing so allows us to bootstrap the compiler in both F\# and OCaml, while minimizing the code duplication. 

If there's some specific code that you think would be better handled in F\# than we do currently, please point it out. If the tradeoffs make sense, we may change it.

**Comment by gsvgit** [comment]
Well. What the reason to support bootstrapping in F# and OCaml?

**Comment by nikswamy** [comment]
Well, we want F* to be usable on both .NET and OCaml (and, eventually, JavaScript).In fact, I think most people are using the OCaml variant of F*.  Bootstrapping the compiler provides us a way to generate platform-specific code for the compiler for each backend.

**Comment by catalin-hritcu** [comment]
This question was answered.
