### ISSUE TITLE
Visual Studio build broken

### ISSUE THREAD

**Issue by mlr-msft** [FStarLang/FStar#430]
A fresh clone of the repository fails to build in Visual Studio. This appears to affect both 2013 and 2015.

The relevant excerpt from build log follows:
```
------ Rebuild All started: Project: parser, Configuration: Debug Any CPU ------
	"C:\Users\%USERNAME%\Documents\wip\FStar-official\src\VS\.nuget\NuGet.exe" install "C:\Users\%USERNAME%\Documents\wip\FStar-official\src\parser\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\Users\%USERNAME%\Documents\wip\FStar-official\src\VS\ "
	Restoring NuGet packages...
	To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
	Installing 'FsLexYacc 6.1.0'.
	Installing 'FsLexYacc.Runtime 6.1.0'.
	Successfully installed 'FsLexYacc.Runtime 6.1.0'.
	Successfully installed 'FsLexYacc 6.1.0'.
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FsLexYacc.Runtime". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
	C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Debug\parser.dll -g --debug:full --noframework --define:TRACE --define:DEBUG --optimize+ -r:C:\Users\%USERNAME%\Documents\wip\FStar-official\bin\absyn.dll -r:C:\Users\%USERNAME%\Documents\wip\FStar-official\bin\basic.dll -r:C:\Users\%USERNAME%\Documents\wip\FStar-official\bin\FSharp.PowerPack.Compatibility.dll -r:C:\Users\%USERNAME%\Documents\wip\FStar-official\bin\FSharp.PowerPack.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll" -r:C:\Users\%USERNAME%\Documents\wip\FStar-official\bin\tc.dll --target:library --warn:1 --warnaserror:76 --vserrors --validate-type-providers --LCID:1033 --utf8output --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ --sqmsessionguid:c62548b0-f9b7-4880-8784-8086f137cbfc --mlcompatibility "C:\Users\%USERNAME%\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.fs" ast.fs parseutil.fs parse.fs lexhelp.fs lex.fs dsenv.fsi dsenv.fs desugar.fsi desugar.fs parseit.fsi parseit.fs driver.fs 
FSC: error FS0225: Source file 'C:\Users\%USERNAME%\Documents\wip\FStar-official\src\parser\parse.fs' could not be found
FSC: error FS0225: Source file 'C:\Users\%USERNAME%\Documents\wip\FStar-official\src\parser\lex.fs' could not be found
Done building project "parser.fsproj" -- FAILED.

Build FAILED.
```

Thanks in advance.
~mlr

**Comment by s-zanella** [comment]
The reference to FsLexYacc.Runtime was broken. Once fixed, I'm getting the same error as in #325. I tried closing and reopening the solution and compiling several times with no luck: couldn't make VS regenerate lex.fs and parse.fs. I solved it by generating these files using the Makefile in `src/parser` and then re-compiling the solution.

**Comment by nikswamy** [comment]
I merged in @mlr-msft's pull request. But, I'm still having trouble doing a fresh build in VS. I have to build the parser manually.

**Comment by mlr-msft** [comment]
This ended up being an incompatibility between FsLexYacc and Visual Studio's automatic NuGet package restore.

Here's details for those interested:

> FsLexYacc recommends that you add a line like this to your `.fsproj` file in order to include the build rules needed for the parser generator to function:
 
`<Import Project="..\VS\packages\FsLexYacc.6.1.0\build\FsLexYacc.targets” />`
 
> Unless the NuGet packages are already restored, Visual Studio won’t load `parser.fsproj` because the `FsLexxYacc.targets` file is missing. Unless Visual Studio can load the project file, the NuGet cache cannot be rebuilt.
 
> It appears that a workaround was added to `parser.fsproj` that looks like this:
 
`<Import Project="..\VS\packages\FsLexYacc.6.1.0\build\FsLexYacc.targets" Condition="Exists('..\VS\packages\FsLexYacc.6.1.0\build\FsLexYacc.targets')" />`
 
> Unfortunately, while this permits Visual Studio to start, it hides the real problem.
 
> In the event that your NuGet package cache is empty, this permits Visual Studio to load the project at startup but the project loads without the build targets needed to produce the parse.fs and parse.fsi files. The result is that your `parse.fs(i?)` files will never be (re)generated until you reload the project (or reload Visual Studio and rebuild with the package cache already restored).
 
The workaround is now documented in INSTALL.md (d3cc240)-- basically, you need to restore NuGet packages *before* using the solution for the first time in order for F* to build correctly. I have, hopefully, mad it impossible for the solution to function at all unless you've performed this step.

**Comment by catalin-hritcu** [comment]
Thanks a lot for tracking this down. Can we also close #325 and #73?

**Comment by mlr-msft** [comment]
Yes, it appears so. I'll take care of it.
