### ISSUE TITLE
Nested recursive functions verification problem

### ISSUE THREAD

**Issue by gsvgit** [FStarLang/FStar#433]
I have a problem with nested recursive functions verification. Full code:

```
module Test

let isDigit x = x >= 0 && x <= 9

type digit = x:int{isDigit x}

type num = 
	| D of digit
	| N of digit * num
	
val f: num -> num -> num
let f n1 n2 =
    match n1 with
        | D d -> n1
        | N (d, n) ->
            begin
                let rec g x =
                    match x with
                        | D d1 -> N (d, x)
                        | N (d1, n1) -> N (d1, n1)
                in 
                g n
            end
```

Error message:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Bound term variable not found: d
```
Definition of ```d``` is pattern ``` | N (d, n) ->```. If I specify ```g```  as non-recursive function (``` let g x = ```) then verification is OK.

**Comment by catalin-hritcu** [comment]
Thanks for reporting.

We had similar problems in the past even for non-nested recursion, but those were fixed already (#192).

In general the support for nested fixpoints is rather flaky in F* (#194), and the usual workaround is hoisting such fixpoints to the top level.

**Comment by s-zanella** [comment]
But in @gsvgit example `f` is not even recursive.
This is a simpler example:

```F#
// Substituting `pos` for a non-refined type makes `f` below typecheck
// type num = | N of int
type num = | N of pos

val f: num -> num
let f n =
  match n with
  | N d -> let rec g x = N d in g 1
```

**Comment by catalin-hritcu** [comment]
Sorry if I wasn't clear enough, by nested recustion I meant "not top level" recursion. I don't think it makes any difference if you nest a let rec within another let rec or anything else.

**Comment by nikswamy** [comment]
A fix for this kind of bug will probably be relegated to the universes branch ...

**Comment by gsvgit** [comment]
Yet another test for this problem: refined types and mutual recursion.
[RefinedTypesAndMutualRecursion.txt](https://github.com/FStarLang/FStar/files/51764/RefinedTypesAndMutualRecursion.txt)

**Comment by catalin-hritcu** [comment]
It's clearly not the same problem, so I've filed it separately (#442).

**Comment by nikswamy** [comment]
Cannot repro with --universes. Closing.
