### ISSUE TITLE
Revising the semantics of assumed type constants

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#434]
Currently, if you write 

```
type t
```

 i.e., a type without a definition, F\* treats this as a **new** type constant, distinct from all other constants. 

This has led to some confusion in many developments, where the intended usage was just to assume some type variable. The confusion has been bad enough that some developments inadvertently end up proving false. 

To make this behavior less surprising, we should:
1. Forbid the constructor above. 
2. If you want a new type constant without any constructors (occasionally we do, e.g., in Prims, where we introduce new primitive types), then you must write

```
new type t
```
1. If you want to assume a type variable, then you must write

```
assume type t
```

All of this applies equally to types that have parameters.

**Comment by catalin-hritcu** [comment]
How about calling it "fresh" instead of "new"?

**Comment by catalin-hritcu** [comment]
@nikswamy Is this still a plan?

**Comment by nikswamy** [comment]
this is implemented (although it is still called `new`). Please close, unless you really want to argue strongly for `fresh`
