### ISSUE TITLE
#push-options and #pop-options

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#439]
Let's rename #set-options and #reset-options. 

Let's also make it so that #push-options can take any valid command line argument (except for file names) as an valid option. Currently, it does not respect many such options, e.g., z3timeout.

**Comment by catalin-hritcu** [comment]
Let's also keep in mind that `fstar.exe` is run by fstar-lang.org and we don't want users to be able to take over that machine. For instance, `#push-options --smt "rm -dfr /"` could erase the server's disk if there weren't other protections in place.

**Comment by nikswamy** [comment]
Good call. Thanks for the reminder.

**Comment by s-zanella** [comment]
This wiki entry attempts to clarify the state of affairs: 
[Options that can be changed in the middle of a file](https://github.com/FStarLang/FStar/wiki/Options-that-can-be-changed-in-the-middle-of-a-file)

**Comment by catalin-hritcu** [comment]
I guess Santiago's documentation is now here: https://github.com/FStarLang/FStar/wiki/Pragmas-(%23set-options,-%23reset-options)

@nik Is there still a plan for  #push-options and #pop-options?

**Comment by nikswamy** [comment]
It's not currently high on my own TODO list, but it does seem useful and not so hard to implement. So if someone wants to take a crack at it, I'd be very happy.

**Comment by s-zanella** [comment]
Updated the wiki.

**Comment by aseemr** [comment]
Thanks to @mtzguido, we now have `push-options` and `pop-options`, closing the issue.
