### ISSUE TITLE
Fixing the implementation of interfaces

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#440]
The way interfaces are currently checked is badly broken. 
Here's how I plan to fix it. Comments are welcome. Heads up @fournet, @ad-l 

A module M may be implemented in M.fst and have an interface in M.fsti.

You will be able to run `fstar M.fsti M.fst`. The semantics of this is: 
1. Type check the module implementation in `M.fst`, independently of its interface.
2. The interface in `M.fsti` must be specified using the syntax

```
module M = sig
 d1
 ...
 dn
```

Note the compulsory use of `sig` to indicate that this is an interface. 

The declarations d1... dn within an interface are only:

--  val declarations
--  type definitions (possibly abstract)
--  assumed formulas
1. To check the interface, we check that every val declaration in the interface is given a type that subsumes the type of the corresponding definition in the implementation---a definition must be given; if not the val must be tagged with an `assume`.

Each type definition is checked to exactly match the type definition provided in the implementation, unless the type in the interface is abstract, in which case at least the kind given in the interface must subsume the one in the implementation. 
1. Any symbol in the implementation that is not exposed in the interface is unusable in the interface and any client of the interface.
2. For pure function `f` defined in the implementation, if a corresponding `val f : t` appears in the interface (where `t` is also a pure function type), clients can rely on both the signature of `f` **as well as its definition**. In order to hide the definition of `f` from clients, the interface must expose `f` using the `opaque val f : t` syntax. 
3. For impure functions exported by the interface, only the signature is available. (Note, this will change as we add support for reify/reflect, so that the definitions of impure functions that are not marked `opaque` will be reifiable, bringing their semantics more inline with that of pure functions).
4. We will still support the `--admit_fsi` functionality, although perhaps renaming the flag to `--admit_iface` or maybe `--admit_sig`. In that case, an interface can be provided without an implementation. As such, all `val` symbols provided by the interface will necessarily be opaque.
5. We will still allow an interface file to have the `.fsi` extension, for compatibility with F# and for bootstrapping. However, this use will only be allowed in a special `--fsharp_compatibility` mode. This should not be a common use case.

---

Note, this style will insist on some duplicated specifications between the implementation and the signature. Of course, the use of an interface is optional. Additionally, we may provide some support to automatically extract a signature from an implementation file. Perhaps our editor modes can also be smart about rendering an interface file, by optionally inlining in them the code of any non-opaque definition exposed by the interface. Is that feasbile, @cpitclaudel ?

**Comment by nikswamy** [comment]
FYI, given the implementation effort involved, I am inclined to leave this for the universes branch.

**Comment by cpitclaudel** [comment]
Hey Nik,

Seems like an exciting change. I'll be happy to contribute IDE improvements to make working with interfaces nicer. There are small things that I can do easily at the IDE level (toggling between an interface file and the corresponding implementation file for example). Other things can be done with some help from the F* binary itself; for example, when switching from an implementation file to the interface file, if the latter doesn't exist, I can call F* to create it.
Similarly, if F* can provide an annotated interface file to point out where to add inlined definitions and what these definitions are, I can render that easily. The upside of doing this on the F* side is that other editors can take advantage of it, too.

Clément

**Comment by catalin-hritcu** [comment]
@nikswamy Can this issue be closed now?

**Comment by nikswamy** [comment]
This is ancient. There are many other issues tracking interface improvements now. e.g.,  #959
