### ISSUE TITLE
Print out the mapping between SMT labels and code locations

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#443]
Printing out the mapping between SMT labels and code locations as smt2 comments could help debug proof obligations.

**Comment by nikswamy** [comment]
This is an internal debugging feature. 

We have many kinds of user-facing features to relate labels to their source locations. 

And in SMT queries, we print positions near the labels (actually near all sub-terms in a query). 

E.g., 

```
;; def=<input>(4,36-4,44); use=<input>(4,36-4,44)
(or label_2

;; def=<input>(4,36-4,44); use=<input>(4,36-4,44)
(>= (BoxInt_proj_0 @x0)
(BoxInt_proj_0 (BoxInt 0)))
```
