### ISSUE TITLE
--eager_inference flag should be disabled

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#444]
According to Nik's comment on https://github.com/FStarLang/FStar/issues/424#issuecomment-150864813 --eager_inference flag should be disabled. "It's extremely non-standard and was there to support a transition from the old inference algorithm to the current one."

**Comment by s-zanella** [comment]
Is the `--eager_inference` flag hard to maintain? 
It was useful at debugging in the past, so why not just keep it.

**Comment by nikswamy** [comment]
It will be yet another configuration of the type-checker to test. I don't think our regression suite uses it at all. So, I worry that counting on it going forward will lead to unpredictability.

If you really want to keep it, I don't mind. Let's document it as "experimental" or "brittle" or something like that.
