### ISSUE TITLE
Distribution of verified libraries

### ISSUE THREAD

**Issue by gsvgit** [FStarLang/FStar#447]
There is an issue on extraction of standard libraries (#372), but what about distribution of verified libraries? Not core only. For example, i want to publish library with verified advanced data structures. It may has references to F* "core" libraries, libraries with other data structures.

Seems, that for .net it would be a good solution to pack F* code as embedded resource for compiled code. After that, we can distribute binaries using Nuget or other package management system.
* for verification: resources can be extracted at run time
* for F* code investigation: resources can be extracted statically (decompiler, reflector, resource viewer, etc)
* if binaries are signed, then F* code is read only. This way we can guarantee "equivalence" of F* specification and extracted (and compiled) code. In other ways F* code can be modified independently of F# code (or binaries) and we can not be ensure that  target system is correct.

**Comment by vkanne-msft** [comment]
This is valuable but not currently in our roadmap. Thanks for the input. It is beyond the core F* tool.
