### ISSUE TITLE
Unable to open files by absolute paths

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#448]
This looks similar to #337.
```
$ pwd
/home/santiago/FStar

$ bin/fstar.exe /home/santiago/FStar/examples/hello/hello.fst
Error: Unable to open file: /home/santiago/FStar/examples/hello/hello.fst

$ bin/fstar.exe examples/hello/hello.fst
Verifying module: Hello
All verification conditions discharged successfully
```
I'm having this problem on Cygwin with an OCaml binary built using OCaml 4.02.1. Works fine on Mac OS X.

With an F# binary it is even worse:
```
$ bin/fstar.exe /home/santiago/FStar/examples/hello/hello.fst
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Could not find a part of the path 'C:\home\santiago\FStar\examples\hello\hello.fst'.
```
I don't remember running into this problem recently.

**Comment by catalin-hritcu** [comment]
AFAIK, on windows `fstar.exe` expects windows paths. You're passing in Cygwin paths.

**Comment by s-zanella** [comment]
Thanks Catalin. These work:
```
$ bin/fstar.exe /cygwin/home/santiago/FStar/examples/hello/hello.fst
$ bin/fstar.exe "C:\cygwin\home\santiago\FStar\examples\hello\hello.fst"
```
Strange I don't remember having this problem in the past. Closing it.

**Comment by catalin-hritcu** [comment]
It would be nice to also support Cygwin paths, if someone knew how to make that work.

**Comment by msprotz** [comment]
Test for the cygpath utility, then run the argument through cygpath -m... that's heavyweight and tedious. Not sure it's worth the trouble.
