### ISSUE TITLE
Z3 models not minimal leads to bad error messages: e.g. admitted post-condition shouldn't fail

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#45]
F\* sometimes reports failing post-condition when other things failed, but the post-condition does hold (e.g, we've admited it). For instance:

```
val xxx : unit -> Fact unit (ensures (False))
let xxx _ = assert(False); admit()
```

Causes the following errors:

```
Error bug45.fst(5,0-6,0): The following problems were found:
    assertion failed (call at bug45.fst(5,12-5,26)) (call at bug45.fst(5,12-5,26))
    post-condition at bug45.fst(4,37-4,42)
```

Yes, the assertion is wrong, but the post-condition is not, and having anything about it in the error message is extremely confusing. When removing the wrong assert, the whole thing succeeds, as it should.

**Comment by catalin-hritcu** [comment]
The original example above is still good illustration of the issue. The error message points only to the wrong place now:
```
./bug045.fst(5,0-5,34): could not prove post-condition
Error: 1 errors were reported (see above)
```
The `--detail_errors` flag seems to not help here (or elsewhere):
```
[hritcu@detained bug-reports]$ fstar.exe --detail_errors bug045.fst                                                      (git)-[catalin_private] 
unknown(0,0-0,0) (Warning): Bug045: Unexpected output from Z3: DETAILING ERRORS1

Error: Detailed error report follows
./bug045.fst(5,0-5,34): could not prove post-condition
Error: 1 errors were reported (see above)
```

**Comment by nikswamy** [comment]
No longer reproducible. F* points to the failed assertion in Bug045.fst
