### ISSUE TITLE
Be aware of restrictions on the rhs of let-rec in OCaml

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#450]
The following code, once #275 is fixed, will be type-checked and accepted by both F\* and F#, but will extract to OCaml code that doesn't compile.

```
module Test

let what =
  let rec g x =
    h x
  and h =
    g
  in
  g 0
```

**Comment by catalin-hritcu** [comment]
I can confirm that with a little bit of annotations the code above type-checks now:
```
let what =
  let rec g (x:int) : Dv int =
    h x
  and h : int -> Dv int =
    g
  in
  g 0
```
and extracts to invalid OCaml code:
```
Error: This kind of expression is not allowed as right-hand side of `let rec'
```

**Comment by catalin-hritcu** [comment]
Guido has another example of this in #1017; here is a variant that doesn't circumvent the termination checker:
```
let rec loop2 : Dv (unit -> Dv unit) = loop2
```

**Comment by nikswamy** [comment]
In my branch, I am restricting `let rec`s to only define lambda literals (after desugaring). I.e., both 

`let f x = e`
and 
`let f = fun x -> e`

are allowed. 

However, this is not allowed, even though it doesn't immediately lead to divergence.

`let f = foo (fun y -> f y)`

**Comment by mtzguido** [comment]
Should we mark this one fixed?
