### ISSUE TITLE
Coercion from Ghost lemmas to Lemmas

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#455]
I am looking for ways to use "ghost lemmas" into lemmas or actual code. So far I have come up with something like the following:

```F#
effect GLemma (a:Type) (pre:Type) (post:Type) (pats:list pattern) =
       Ghost a pre (fun r -> post)

assume val coerce: pre:Type -> post:Type -> pats:list pattern -> g:(unit -> Ghost unit pre (fun r -> post)) -> Pure unit pre (fun r -> post)

val dummy_ghost_lemma: n:nat -> GLemma unit (requires (True)) (ensures (n > -1)) []
let dummy_ghost_lemma n = ()

val dummy_lemma: n:nat -> Lemma (n > -1)
let dummy_lemma n =
  coerce (requires (True)) (ensures (n > -1)) [] (fun _ -> dummy_ghost_lemma n)
```

Which works. So I have a couple questions:
- is it sound (I restricted the coercion function to unit types only) ?
- if so could it be added to FStar.Ghost so as to allow one to write lemmas reasoning on ghost values ?
- is there a more appropriate way to write the effect and the coercion function above ?

Thanks!

**Comment by vkanne-msft** [comment]
This has been implemented. Closed.
