### ISSUE TITLE
Can't find `prims.fst` after `make install`

### ISSUE THREAD

**Issue by wizeman** [FStarLang/FStar#456]
When I build F* from source and try to install the OCaml-compiled binary by running `make install -C src/ocaml-output`, the binary gets installed into `$PREFIX/bin` and the library files get installed into `$PREFIX/lib/fstar`.

However, when I try to run `fstar.exe` from `$PREFIX/bin` to verify the first exercise in the tutorial, it fails saying that it cannot open `prims.fst`. The reason it cannot open is that it's trying to look for `prims.fst` in `$PREFIX/lib` rather than `$PREFIX/lib/fstar`, where it was installed.

I think the relevant code should be here: https://github.com/FStarLang/FStar/blob/56ad833f68e3a87e58d6ae33c3e5df19cd1bfa14/src/basic/options.fs#L190

As you can see, it always tries to load `prims.fst` from `<fstar-home>/lib` (instead of `<fstar-home>/lib/fstar`), even though in the function `get_include_path` which is right above, it correctly contemplates the two different possibilities.

**Comment by catalin-hritcu** [comment]
@msprotz  Did the opam package already solve this somehow?

**Comment by catalin-hritcu** [comment]
@wizeman Do you have any good reason for running `make install` in the first place? Beyond the opam package we never use that.

**Comment by wizeman** [comment]
@catalin-hritcu I was working on packaging F* for Nix / NixOS (in NixOS/nixpkgs#12462).

It is true that the F* documentation mentions using `make package` to create binaries, but this requires a whole bunch of extra dependencies compared to `make install`, such as git, LaTeX, zip, and especially Madoko, which is not packaged in Nix yet (I would have to do it myself), the latter of which also adds even more dependencies such as Node.js, Express and, if I were to do things right, also Koka, which is also not packaged for Nix / NixOS yet.

Note that packaging F* for Nix with `make install` was already a significant challenge all by itself, given Mono and F# idiosyncrasies and bugs, the not-quite-standard system of Makefiles used by F*, and the unconditional calling of NuGet to fetch things from the network (which is undesirable when you want to build packages deterministically, and forbidden by many package managers, such as Nix, during the compilation phase).

I understand the extra dependencies are needed to properly build the F* documentation, but I wasn't ready to spend the extra effort to do it properly, and at least this way I got something that works (and that can be used by other people).

That said, feel free to ignore / close this issue, since in the end I was able to workaround it (by moving everything under `lib/fstar/` to `lib/`). I just assumed that this was a bug, since usually when you do `make install` on a package, the binary usually knows where to find the libraries that were installed.

**Comment by msprotz** [comment]
Hmm this is strange indeed. The code for `prims ()` should find `prims.fst` in the include path, and shouldn't bypass `get_include_path`...

I think this was broken by @mlr-msft 's commit (see https://github.com/FStarLang/FStar/blame/56ad833f68e3a87e58d6ae33c3e5df19cd1bfa14/src/basic/options.fs#L190 ); I think you should use the git tag that I used to build the OPAM package, and then "make install" will work just fine (hopefully).

The other option would be to fix that function.

**Comment by msprotz** [comment]
And thanks for the report by the way. We all use local development builds of F*, so we don't try "make install" too much.

**Comment by mlr-msft** [comment]
@wizeman: Yes, thanks for submitting the report. :smile: I've submitted a pull request that I hope addresses the problem. Please let me know if it doesn't.
