### ISSUE TITLE
Unexpected error: "Impossible: this instance has already been assigned a solution"

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#459]
Hello,

I've restarted using Fstar recently and while I was going through the tutorial, I found the following unexpected error.

```
module Test

let create n =
    let c = ref n in
    let f () = 
        c := !c + 1;
        !c
    in 
    f
```

When I run this code, I obtain:

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: this instance has already been assigned a solution")
```

Any idea ?

**Comment by catalin-hritcu** [comment]
You could try minimizing and see if you hit anything similar to #208 or #398.

**Comment by VincentCheval** [comment]
By minimizing, do you mean the following ?

```
let create n =
      let c = ref n in
      (fun () ->  c := !c + 1; !c)
```

If yes then same result as above. 

Would it be because I use the Mac Binary instead of compiling from source ?

**Comment by christophe-calves** [comment]
Hi,

 For info, I get the same error on a Linux box with both the last release binaries[1] and when building from source (up to commit 719dec7393b0add07d34a9b2d8581a55877c65de) by the F# build. 

```
#$ uname -a
Linux localhost 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#$ fstar bin/fstar.exe --version
F* 0.9.2.0
platform=Linux_x86_64
compiler=OCaml 4.02.3
date=2016-02-02T16:36:42+0100
commit=2a8ce0b
```

**Comment by nikswamy** [comment]
I tried the program below with commit 719dec7393b0add07d34a9b2d8581a55877c65de type-checking it like so: `fstar --universes test.fst`. It worked fine. 

A couple of points to note: 

1. See the wiki for some notes about migrating code the universes mode https://github.com/FStarLang/FStar/wiki/Migrating-code-to-use-the---universes-mode-(particularly,-as-related-to-mitls-fstar). One of the points there is the renaming of `ref` to `alloc`.

2. The non-universes mode (aka the stratified type-checker) will be deprecated in the next release. As such, I do not plan to fix this issue there. Very sorry if this is troublesome for you.

```
module Test
let create n =
    let c = alloc n in
    let f () = 
        c := !c + 1;
        !c
    in 
    f
```
