### ISSUE TITLE
Physical equality on references

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#460]
Hello,

How does F* handle equality between references ? Here is my code:

```
module Test

open FStar.IO

let x = ref 0

let y = ref 0

let z = ref 1

let print_test () =
  print_string "Test (x = y) = ";
  print_string (string_of_bool (x = y));
  print_string "\n";
  print_string "Test (x = z) = ";
  print_string (string_of_bool (x = z));
  print_string "\n"

;;


print_test ()
```

Running this with the ocaml extractor returns me the following result:

```
Test (x = y) = true
Test (x = z) = false
```

Since x, y, z are all references defined separately (hence physically different), I would have expected that both tests return false. However, it seems that F* never compare reference but the content of the references. Is it normal ? If yes, how can I test the equality of references as a physical equality ?

Best,
Vincent

**Comment by vkanne-msft** [comment]
Thanks for the input. We will look into it.

**Comment by s-zanella** [comment]
Still valid using either Heap or HyperHeap. 

I checked in the example code updated to reflect syntax changes. 
Reproduce with
```
$ bin/fstar.exe examples/bug-reports/bug460.fst --codegen OCaml
$ ocamlfind ocamlopt -package batteries,stdint,fileutils,sqlite3,zarith -linkpkg -g -thread -w a+A-27 -I ulib/ml/ ulib/ml/fstarlib.cmxa Bug460.ml -o Bug460
$ ./Bug460
Test (x = y) = true
Test (x = z) = false
```

**Comment by msprotz** [comment]
Yes, this is a known bug. We should switch our implementation of references to https://www.lexifi.com/blog/references-physical-equality

**Comment by msprotz** [comment]
Valid only in universes, naturally.
