### ISSUE TITLE
Module FStar.List does not open

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#461]
Hello,

I'm sorry for spamming you with question but I have an issue when using the module FStarList. I tried all three following codes and it returns the error "Identifier not found: [FStar.List.length]" for the first two, and "Identifier not found: [length]" for the third. (I'm using the binary for MAC)

```
module Test

let x = FStar.List.length []
```

```
module Test

open FStar.List

let x = FStar.List.length []
```

```
module Test

open FStar.List

let x = length []
```

On the other hand, there is a file list.fst and list.fsi in my lib folder that defines the module FStar.List so I'm a bit lost.

Best
Vincent

**Comment by catalin-hritcu** [comment]
You're using an old binary. Please try trunk before filing anything.

**Comment by VincentCheval** [comment]
I don't think I'm using an old binary. When I run --version, it gives me:

```
F* 0.9.1.1
platform=Darwin_x86_64
compiler=OCaml 4.02.3
date=
commit=c41ea17
```

It seems it is the latest release available on GitHub. Am I mistaken ?

**Comment by catalin-hritcu** [comment]
Latest release yes, but it's 3 months old, and we do not maintain old releases. As our README mentions:

> Please report issues using the F* issue tracker on GitHub. We don't maintain old releases, so if possible please use the online F* editor or directly the GitHub sources to check that your problem still exists.

**Comment by VincentCheval** [comment]
My bad. Sorry.

**Comment by VincentCheval** [comment]
I'm terribly sorry but I still don't manage to "open" correctly the library FStar.List (or any other from your package typically). I tried on the F* version online as well as on the bash version and I always get the "Identifier not found". What is the command line for fstar.exe to tell him to go look for library in the lib folder from the distribution ?

**Comment by msprotz** [comment]
Hi there,

The easiest way to get the latest version of F* would be to check out the sources, make sure you have an up-to-date, recent OCaml (e.g. via OPAM), then run `cd FStar && make -C src/ocaml-output`. Then, if you run the F* binary that's found in `bin/`, your example should work.

**Comment by beurdouche** [comment]
Hi Vincent !

```
module Test
let x = FStar.List.length []
```
when trying to type-check it, I got the following error :
```
$ fstar.exe ~/Desktop/test.fst
/Users/bbeurdouche/Desktop/test.fst(4,19-4,25) : Error
Identifier not found: [FStar.List.length]
```
It seems that the module is not recognized.
If I add explicitly the `FStar.List.fst` before `test.fst ` I also need all it's dependencies which are listed here
```
fstar.exe  --admit_fsi FStar.Set FStar.Set.fsi FStar.Heap.fst FStar.ST.fst FStar.All.fst FStar.List.fst ~/test.fst
Verifying module: FStar.Heap
Verifying module: FStar.ST
Verifying module: FStar.All
Verifying module: FStar.List
Verifying module: Test
All verification conditions discharged successfully
```

**Comment by beurdouche** [comment]
Ps: you might require less dependancies to the FStar.List module but I personally do not remember which...

**Comment by VincentCheval** [comment]
So, does that mean every time I need one of the library already written in the distribution, I need to go an check what are its dependencies ? There is no option for fstar.exe where we could put a directory in which he can just go and look automatically ?

**Comment by beurdouche** [comment]
I agree it is not practical, we have progress on having the dependancies automatically fetched but the feature is not complete yet. In the mean time, on top of many `lib` files, there is a "build-config" header that usually contain these dependancies for interactive type-checking. You might find it useful.
Did you manage to make it work at the end ?

**Comment by VincentCheval** [comment]
Thanks a lot for the tip =) I finally manage to compile it following your example. I'm gonna check the build-config of the lib files to learn a bit more about them. Thanks !

**Comment by msprotz** [comment]
`fstar --dep make test.fst` should help you out with the dependencies in this example...
