### ISSUE TITLE
Possible bug with the operator && ?

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#465]
Hello,

I think I found a bug with the operator && in the type-checking but I'm not sure. With the following code, I obtain the error message `Test.fst(7,96-7,98): Subtyping check failed; expected type n:name{(is_private n)}; got type name`

```
module Test

type name

assume val is_private : name -> Tot bool

assume val fresh_private : mem:(n:name{ is_private n } -> Tot bool) -> Tot (n':name {  not (mem n') && is_private n'})
```

But with the following code, it type checks:
```
module Test

type name

assume val is_private : name -> Tot bool

assume val fresh_private : mem:(n:name{ is_private n } -> Tot bool) -> Tot (n':name { is_private n' && not (mem n') })
```

To be clear, I changed ` not (mem n') && is_private n'`in `is_private n' && not (mem n')`.

Is it a normal behavior ?

Vincent

**Comment by s-zanella** [comment]
It is normal behavior, sound with respect to the short-circuit evaluation semantics of `&&`. 
That is, `a && b` is equivalent to `if a then b else false`, so when type checking `b` it is fine to assume `a`.

**Comment by VincentCheval** [comment]
Thanks 😊 So I need to be careful in which order I put my boolean terms when I use the operator &&
