### ISSUE TITLE
Collisions from different namespaces

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#467]
```
module Bug

open FStar.Strange
open Bob.Strange

let test = Strange.my_valueX
```

If two namespaces contain a module with the same name and a similar method, it is unclear which one will be used...

```
$ fstar.exe foo.fst
Verifying module: FStar.Strange
Verifying module: Bob.Strange
Verifying module: Bug
All verification conditions discharged successfully
```

I believe there are two problems here : 
1 - `Strange.my_valueX` should not go through as neither `open FStar` nor `open Bob` are explicitly present
2 - In the case where both are open, F* should fail, saying there is a possible clash (which is not the case even if you remove `Strange.` in front of `my_valueX` )

I think we should enforce the two rules but the first one should be discussed..
WDYT ? ;)

**Comment by jkzinzindohoue** [comment]
I think that when the FStar namespace was added to the standard library, a mecanism of automatic resolution for the namespaces was added so that all the codebase would not break. Like if you say `Set` it would be able to understand `FStar.Set`.
In your example, is it the `FStar` or the `Bob` module that is infered ? I guess it should be documented anyway.

**Comment by msprotz** [comment]
What I know for sure is "open Foo" either:
- opens the module "Foo" if Foo.fst is in the search path, that is brings all of its definitions into scope, or
- if Foo.fst is not in the search path, then "open Foo" re-binds all Foo.Barᵢ.fst in the search path as Barᵢ.fst

I need to check with Nik, but I suspect the following also happens:
- "open Foo.Bar.fst", when "Foo.Bar.fst" is in the search path, also binds "Bar" as a module name in the scope

I argued at some point for a "require" directive that would have better semantics but I'm afraid we need to keep the current form to be compatible with F#.

**Comment by beurdouche** [comment]
Hum... also on second thoughts about my point 2 here, we should be careful as it allows shadowing right ?

**Comment by nikswamy** [comment]
The reason is that `open FStar` is implicitly added to the set of open namespaces in every file.

You should not observe this behavior if you `open Foo.Strange` instead of `open FStar.Strange`

**Comment by beurdouche** [comment]
Ok cool =) So should we make everything consistent by enforcing 1) or just document somewhere that `open FStar` is added automatically ? I personally prefer enforcing 1)...

**Comment by beurdouche** [comment]
This wasn't a really a bug. Closing
