### ISSUE TITLE
Standard library folder (lib) required for OCaml build

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#472]
If the `lib` folder does not exist then `make -C src/ocaml_output` will fail with:

```
make[1]: *** No rule to make target `../../lib/ml/native_int/prims.ml', needed by `copy_lib_files'.  Stop.
make: *** [all] Error 2
```

It does not fail for the F# build because the behaviour is not the same (there is the `basic` directory)
It would be nice to make all the backends consistent and non-dependant on `lib` at some point...

**Comment by msprotz** [comment]
Actually a better solution would be to make the files in basic/ links to the files in lib/ (or the opposite) so that we don't have several implementations of the same libraries... (I'm thinking about list that has several copies all over the source tree).

```
./lib/FStar.List.fst
./lib/list.fsi
./src/basic/list.fs
./src/basic/list.fsi
```

**Comment by nikswamy** [comment]
Lots of work on fstarlib and fstartaclib. This is not longer an issue.
