### ISSUE TITLE
Regression target broken since merge or autodep branch

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#475]
I see that people are making good progress on making the examples build again (it would have been great to do that *before* merging the branch, by the way).

The `make regressions -C src` target starts with `make -C lib` though, and that's in a very sorry state after this merge, with a dozen of its actions failing. (Here's a list: https://gist.github.com/catalin-hritcu/5a56384c62ab19fd39c6)

Any volunteers for fixing this?

**Comment by beurdouche** [comment]
> The make regressions -C src target starts with make -C lib though, and that's in a very sorry state after this merge, with a dozen of its actions failing. (Here's a list: https://gist.github.com/catalin-hritcu/5a56384c62ab19fd39c6 <https://gist.github.com/catalin-hritcu/5a56384c62ab19fd39c6>)
> 
> Any volunteers for fixing this?
> 
I am having a look at this right now starting by `lib` but help is welcome ;)
B.

**Comment by beurdouche** [comment]
`lib` is done by https://github.com/FStarLang/FStar/commit/71e301c1618154e215bef9c7515ee88c5feefedb <https://github.com/FStarLang/FStar/commit/71e301c1618154e215bef9c7515ee88c5feefedb>

Taking a look at `regressions`

**Comment by beurdouche** [comment]
looks that `regressions` is behaving properly once `lib` is fixed. Can someone confirm and close ?

**Comment by beurdouche** [comment]
`make regressions -C src` is very strange, it builds `CoreCrypto` that relies on having `OpenSSL` and so on ...

**Comment by catalin-hritcu** [comment]
And what's strange about this?

**Comment by beurdouche** [comment]
Bugs are fixed and the behaviour of regressions regarding that particular isssue is correct
