### ISSUE TITLE
Unit tests are failing with one more error than expected

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#476]
`make -C examples/unit-tests` gives :
https://www.fstar-lang.org:3443/fstarlang/fstar/job/56b486923453a92f5e00c078

**Comment by beurdouche** [comment]
I had to fix the makefile for unit-tests so I added one failing case in the Makefile without searching the entire history (https://github.com/FStarLang/FStar/commit/83b57eb175c74da1212f204cd4d8cba78e50cc48).

I feel like that our way of handling negative tests and count them is bad and it would be better if we could know exactly what is supposed to fail and what is failing.

Maybe having separated modules for the negative tests (1 test per module) ?

**Comment by catalin-hritcu** [comment]
The general problem here is related to #231 where I also proposed a potential fix.

**Comment by beurdouche** [comment]
What about an F* flag like `--expect_failure MyNegTestModule1` that would prevent to write on the standard error and display a nice “Verification failed as expected” ?

**Comment by beurdouche** [comment]
Closing in favor of #231
