### ISSUE TITLE
Tutorial seems broken

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#477]
`Error: not a valid FStar file: /tmp/fstar_HGyEBP`
![fstar_broken_tutorial](https://cloud.githubusercontent.com/assets/1193431/12847861/8df3c238-cc16-11e5-849d-57c3cb1840ed.jpg)

**Comment by ad-l** [comment]
This is quite annoying and urgent, trying to see how I can still maintain compatibility with files containing multiple modules

**Comment by msprotz** [comment]
--explicit_deps to get the old behavior?

**Comment by ad-l** [comment]
Many tutorial exercises use multiple modules in the same file and broken patterns (e.g. open Prims.PURE) that won't be solved by --explicit_deps. As a workaround I am now using autodeps + splitting inputs in different files based on declared module, but this is brittle.

Someone needs to go through doc/tutorial/code and fix the examples to adhere with the new rules.

**Comment by ad-l** [comment]
This was fixed a long time ago but not closed
