### ISSUE TITLE
Generate mli's from .fst files in lib/

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#485]
Right now, the files in `lib/ml` are not kept in sync with the corresponding `fst`'s. For instance, `FStar_List.ml` does not implement `tryFindT`; `FStar_String.ml` had a wrong signature for `make`, and so on...

We could have a special mode for extraction where we extract `mli`'s for all these files into the `lib/ml` directory, rather than wait until extraction-time to figure out that things are not quite right.

**Comment by msprotz** [comment]
```
protz@Joprotze-Z420:~/Code/fstar/lib (master) $ egrep "^let" ml/FStar_List.ml | sed 's/let\( rec\)\? \(\w\+\).*/\2/g' | sort > /tmp/in_ml
protz@Joprotze-Z420:~/Code/fstar/lib (master) $ egrep "^let" FStar.List.fst | sed 's/let\( rec\)\? \(\w\+\).*/\2/g' | sort > /tmp/in_fst
protz@Joprotze-Z420:~/Code/fstar/lib (master) $ diff /tmp/in_fst /tmp/in_ml2,5d1
< appendT
< assoc
< assocT
< bool_of_compare
7d2
< chooseT
9,13d3
< collectT
< concat
< concatMap
< concatMapT
< concatT
15,17d4
< containsT
< count
< countT
20d6
< filterT
22d7
< findT
24d8
< flattenT
27d10
< fold_leftT
29c12
< fold_rightT
---
> fold_right2
31d13
< for_allT
35d16
< isEmptyT
36a18
> iter2
38,39d19
< iteri_aux
< iterT
41d20
< lengthT
46,48d24
< mapi_init
< mapi_initT
< mapiT
54,55d29
< partition_length
< partitionT
57d30
< rev_acc
59d31
< revT
61d32
< sortWithT
63d33
< splitT
66d35
< total_nth
70c39
< tryPickT
---
> unique
73,74c42
< unzip3T
< unzipT
---
> unzip3


All the lines that start with `<` are top-level definitions in the `fst` that are not matched by a corresponding implementation in the `ml`. Lines that start with `>` are useless definitions in the `ml` file.

**Comment by nikswamy** [comment]
@protz  is this something that we still care to address?

**Comment by msprotz** [comment]
Sure, but the mli could be auto-generated by extracting an `.ml` file via F*, then extracting its intended interface via `ocamlc -i` and then checking the hand-written `.ml` against the auto-generated `.mli`... this is more build system trickery... not sure it's worth it. Thoughts?

**Comment by mtzguido** [comment]
Linking to #1515

**Comment by nikswamy** [comment]
Generating mli's will require a significant re-design/engineering effort with unclear benefits. Closing.
