### ISSUE TITLE
Classes and Structs in F*

### ISSUE THREAD

**Issue by GKerfImf** [FStarLang/FStar#491]
Hello,
If there are Classes or Structs in F*? For I'm trying to translate the following code: 
```fs
type Position =
        val line : int
        val column : int
        new (line, column) = {line = line; column = column}
        new (line : int) = {line = line; column = 0}
        override this.ToString() = "some text"
```
and I have no idea, how to implement constructor.

**Comment by nikswamy** [comment]
F\* does not provide any primitive support for object-oriented features. 

You can encode something like this in various ways. For example:

```
type position = {line:ref int; col:ref int; toString:unit -> string}
let mk_position l c = 
   let l = ref l in
   let c = ref c in
     {line=l; col=c; toString=(fun () -> string_of_int !l ^ ", " ^ string_of_int !c)}
```

But there are many other styles one could adopt too.
