### ISSUE TITLE
Documentation for declaration of infix function

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#492]
Hello,

I've looked over the github and there were some old posts talking about the declaration of infix operator (like @ \* + - ... or sequence of these) but I did not quite get if it was implemented or if it is under development. I'd be very grateful if someone could give the syntax to declare infix operator if it is possible.

Thanks
Vincent

**Comment by jkzinzindohoue** [comment]
It is implemented, though not documented as far as I know.
The list of usable symbols shall be something like (from the sources):
```
            |'&' -> "Amp"
            |'@'  -> "At"
            |'+' -> "Plus"
            |'-' when (arity=1) -> "Minus"
            |'-' -> "Subtraction"
            |'/' -> "Slash"
            |'<' -> "Less"
            |'=' -> "Equals"
            |'>' -> "Greater"
            |'_' -> "Underscore"
            |'|' -> "Bar"
            |'!' -> "Bang"
            |'^' -> "Hat"
            |'%' -> "Percent"
            |'*' -> "Star"
            |'?' -> "Question"
            |':' -> "Colon"
```
The way to declare them is to name the operator `op_` + a combination of those names above separated by underscores, e.g. `let op_Hat_Plus x y = x + y` can be used to write `x ^+ y`.
It is usable immediately after declaration.
In my experience some of the symbols do not work when used as the first symbol, but I cannot remember which ones.

**Comment by VincentCheval** [comment]
Thanks a lot !

**Comment by msprotz** [comment]
Probably consistent with the first answer in http://stackoverflow.com/questions/6150551/ocaml-why-i-cant-use-this-operator-infix

**Comment by kyoDralliam** [comment]
Documentation is now available in the wiki [Parsing and operator precedence](https://github.com/FStarLang/FStar/wiki/Parsing-and-operator-precedence)
