### ISSUE TITLE
Curried function, but not total

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#493]
Hello,

I don't understand why this code does not work:

```
val foo : x:('t -> nat -> Type) -> a:'t -> Lemma (x a 0 <==> x a 0)
let foo x a = ()
```

It gives me the following error:

```
Expected a term of type "(x:('t -> nat -> Type) -> a:'t -> Lemma (unit) True, ((x a 0) <==> (x a 0)), (Nil ))";
got a function "(fun x a -> ())" (Curried function, but not total)
```

I checked on the github and I found similar problem with solutions: #209 and #375. However, when I applied these solution, the problem persists. 

```
module Test

val foo : t:Type -> x:(t -> nat -> Type) -> a:t -> Lemma (x a 0 <==> x a 0)
let foo (t:Type) x a = ()
```

It gives me the error 

```
Expected a term of type "(t:Type -> x:(t -> nat -> Type) -> a:t -> Lemma (unit) True, ((x a 0) <==> (x a 0)), (Nil ))";
got a function "(fun t x a -> ())" (Curried function, but not total)
```

Best,
Vincent

**Comment by jkzinzindohoue** [comment]
I think F* needs an extra type annotation to bind the variables properly. The following works:
```
module Test

val foo : t:Type -> x:(t -> nat -> Type) -> a:t -> Lemma (x a 0 <==> x a 0)
let foo (t:Type) (x:t-> nat -> Type) a = ()
```
The binders in the type declaration are probably relevant only for the type declaration and not for the let binding.

**Comment by nikswamy** [comment]
Thanks for the workaround, JK. 

I'm surprised by this behavior. I'm calling it a bug ... I expected Vincent's code to work.

**Comment by nikswamy** [comment]
Actually, I take that back. This is a quirk in the syntax in the stratified approach of the default checker. 

Basically, a good rule of thumb is that if you are using type variables with ' (tick) prefixes, then make sure that they are all of that form. Here you have 't and x ... mixing them leads to strange behaviors like this.

**Comment by jkzinzindohoue** [comment]
The last example was not using tick prefixes though. I could write 
```
val foo : 't -> x:('t -> nat -> Type) -> a:'t -> Lemma (x a 0 <==> x a 0)
let foo x a = ()
```
I did not manage to write it using implicit `(#t:Type)` symbols.
Should we consider that the `'` (tick) notation is the most robust to use ?

**Comment by nikswamy** [comment]
I would say that the non-tick notation is more robust. I use the tick notation only when writing ML-style code. 

Without universes, you can write:

```
val foo : #t:Type -> #x:(t -> nat -> Type) -> a:t -> Lemma (x a 0 <==> x a 0)
let foo (#t:Type) (#x:(t -> nat -> Type)) a  = ()
```

With --universes, you can write:

```
val foo : #t:Type -> #x:(t -> nat -> Type) -> a:t -> Lemma (x a 0 <==> x a 0)
let foo #t #x a = ()
```

**Comment by VincentCheval** [comment]
Thanks for all these answers. It works well with this trick of @jkzinzindohoue

**Comment by catalin-hritcu** [comment]
Now even the original code works well. Closing.
