### ISSUE TITLE
Less ambiguous F* syntax (if breaking F# compatibility)

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#495]
---------- Forwarded message ----------
From: Catalin Hritcu catalin.hritcu@gmail.com
Date: Mon, Feb 15, 2016 at 11:58 AM
Subject: Re: [fstar-priv-club] Better parsing errors with Menhir
To: Cedric Fournet fournet@microsoft.com
Cc: "fstar-priv-club@lists.gforge.inria.fr" fstar-priv-club@lists.gforge.inria.fr

Maybe in some cases stronger parsing technology could indeed help, but
there are many problems with ambiguities in the ML grammar that would
simply need more tokens to fix (like an end for matches and maybe even
for ifs). When teaching F\* most of our students and our tutor (so a
smart guy, Niklas!) have spent hours not understanding that the
semantic error they were trying to fix were in fact just badly parsed
syntax caused by a bad grammar. Here are some examples gathered from
my Saarbrücken course:
http://prosecco.gforge.inria.fr/personal/hritcu/talks/fstar-sb-2015/03/slides03.html#sec-syntactic-pitfalls--nested-patterns

On Mon, Feb 15, 2016 at 11:48 AM, Cedric Fournet fournet@microsoft.com wrote:

> Hi Catalin,
> 
> Concrete syntax makes a big difference in usability, so I am a bit frightened re: moving to "a less ambiguous grammar"; I am already struggling with the need for extra parentheses compared to F# or OCaml. I'd like to plan towards building a more user-friendly parser, relying on stronger technology.
> 
> -Cédric
> 
> -----Original Message-----
> From: fstar-priv-club [mailto:fstar-priv-club-bounces@lists.gforge.inria.fr] On Behalf Of Catalin Hritcu
> Sent: 15 February 2016 10:35
> To: fstar-priv-club@lists.gforge.inria.fr
> Subject: [fstar-priv-club] Better parsing errors with Menhir
> 
> Just listened to a talk by Francois Pottier on new facilities for better parsing error messages in Menhir. The summary is that he has
> (1) a very resource intensive grammar analysis tool that detects the automaton states for which errors can be produced, and (2) a way for the grammar designer to write and maintain error messages for those states. He's already added such messages successfully for the CompCert C grammar, but the C grammar is a lot less ambiguous than the OCaml grammar, which is future work.
> 
> From what, I see at this point we anyway use ocamlyacc not Menhir, but the two tools seem to be  nearly compatible with each other.
> 
> Anyway, something we could look at too at some point. Until then we will hopefully give up F# compatibility and move to a less ambiguous grammar, for which good error messages are much easier with or without Francois' latest ideas :)
> 
> Catalin

**Comment by drbo** [comment]
I think the solution is to have an *unambiguous* LALR(1) grammar.

**Comment by catalin-hritcu** [comment]
Just for the record, one more thing in this space at which we were looking these days is Reason:
http://facebook.github.io/reason/
https://facebook.github.io/reason/mlCompared.html
Their grammar seems less ambiguous, but not sure about LALR(1) though.

**Comment by nikswamy** [comment]
No action on this for a long time. 

The main syntax revisions we're considering are in the following contexts:

https://github.com/FStarLang/FStar/wiki/Towards-a-Finer-grained-Incremental-Typechecker-for-F*
https://github.com/FStarLang/FStar/wiki/Steel:-surface-language

Closing this issue
