### ISSUE TITLE
Improve crypto modules in `examples/crypt` and tutorial

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#498]
`rpc.fst` and `CntProtocol.fst` verify, model different agreement properties, and extract and run. 

`mac.fst` verifies but does not have a concrete implementation. In particular this means that rpc.fst can only be run in a single process for now.

`Sig.fst` does not model concrete signatures correctly, e.g. if verification key is not honestly generated signatures should be verified concretely. Moreover, there is no way to express the idealization statement. 

`CCA2.CCA2.fst` verifies and models some form of functional correctness. 

The correct use of plain modules by idealized encryption modules is currently not enforced. Can we have a programming style that achieves this using, e.g., using an `ideal` flag so that `not ideal` is a precondition of repr?

We also do not express the desired idealization statement, namely that `cca2 false pk enc dec` and `cca2 true pk enc dec` are computationally indistinguishable. This is a different style from the usual module defining functions with compilation/global flag idealization.

`encrypt.fst`, `encrypt2.fst`, `encrypt3.fst`, are all deprecated and explore different styles. `encrypt3.fst` is somewhat similar to `CCA2.CCA2.fst`.

`hybrid.fst`, `hybrid2.fst`  are only rough sketches. Idealization of public key encryption should guarantee that the symmetric encryption key is treated abstract, i.e. the symmetric key scheme should be the plain module of the PKE scheme.

`Sig.fst`, `encrypt.fst`, and `hybrid.fst` are not part of regression and are outdated.

**Comment by markulf** [comment]
@catalin-hritcu

**Comment by nikswamy** [comment]
The old tutorial is defunct. A crypto section in the new tutorial will be welcome.
