### ISSUE TITLE
Feature request: pragmas and replacement of build-config

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#501]
Since the build-config has been removed I feel like there has been no proper replacement for some of its features, or I do not know about it.
Specifically it used to provide great customization possibilities in interactive mode via the  `options` line.
Using the latest F* version I can no longer (in interactive mode):
- set a custom timeout for each file
- set some debugging features (e.g. --print_implicits) etc.
- is the `--verify_module X` options automatically set to the current file in interactive mode ?

The auto-deps feature is great for file inclusion but the build-config was not useful only for that but also to pass other options.

Here is typically how I progress into a file, using a previous version of F* and build configs: 
- I use the emacs interactive mode
- I verify one function  at a time with a small timeout
- When functions take more time to prove, I insert `assert`s or `cut`s and incrementally increase the timeout to test whether it really cannot prove something or merely needs more time
- I put an `admit();` at the very beginning of the functions that as just been proven an move to the next.
It is the most efficient pattern I have experienced.

Hence is it possible to:
- restore the build-config for options so that the timeout and other options can be modified ?
- otherwise provide a pragma to at least set custom timeout and options per file in interactive mode, set at the top of the file just like the build-config used to work ? AFAIK only the fuel is modifiable through the `#set-options` pragma in the file
- I would love to have a pragma like `#lax-on` and `#lax-off` to be able to lax typecheck blocks while in verification mode, the same way it works with the --verify_module option typically. What already exists for module-per-module verification would be great to have function-per-function inside a module so that one does not have to assume or to put `admit()` in every function that has already been verified when a modification is made at the beginning of a partially verified file in interactive mode. It would also be super useful in CLI mode.

Thanks

**Comment by beurdouche** [comment]
+100 
I really think that we lack those features to be efficient in producing a large amount of verify code.

**Comment by catalin-hritcu** [comment]
I think the right way to bring back this functionality is via pragmas. There is already an issue on allowing any non-security-critical option to be set in pragmas (#439).

**Comment by jkzinzindohoue** [comment]
Such pragmas would be great.
It is too bad that introducing `auto-deps` led to removing useful features. It feels like taking a step back for the interactive mode.

**Comment by msprotz** [comment]
> is the --verify_module X options automatically set to the current file in interactive mode ?

I don't think so but I think it's a valid feature request. Thoughts?

**Comment by nikswamy** [comment]
@jkzinzindohoue  The functionality is still available for interactive mode via the fstar-subp-prover-args variable of the emacs mode.

I agree that controlling all non-security-critical compiler options via pragmas should be supported.

Adding --verify_module X for the current file in interactive mode is a good idea.

**Comment by nikswamy** [comment]
cf. 0b4d9b8: allowing reset-options with arguments to control parameters like z3timeout via pragmas - Nikhil Swamy
16a2f8b: snap - Nikhil Swamy
e2bd1eb: merging and re-snap - Nikhil Swamy
36ae901: removing spurious #set-options "--z3timeout n" in various places ... these were not being honored anyway. if you want to set the timeout, you need to use #reset-options "--z3timeout n" - Nikhil Swamy
