### ISSUE TITLE
Request for a 'subgoal' feature

### ISSUE THREAD

**Issue by ahmadsalim** [FStarLang/FStar#507]
So after some helpful discussion with @catalin-hritcu on the mailing list on how `F*` novices like me could use `assert`, `assume` and `admit` to guide the semi-automated prover, I have gotten the idea that something like a `subgoal` feature might be useful.

The simplest implementation, would have `subgoal G` be equivalent to `assert G; assume G` which would essentially only be an annotation if everything succeeds, and if things fail it would tell you whether `G` can not be reached from the precondition, or that `G` is not enough (together with other things in context) to prove the post condition.
However, the feature would be much more interesting if one adds a `skip()` function, which works like `admit()` but instead of admitting the whole proof it would only `skip()` the next subgoal (or the whole proof if there aren't any).

This combination of `subgoal` and `skip()` would allow users to incrementally develop proofs, saving some of the more difficult proofs for later. One could imagine then having a script like this:

``` fsharp
let proof = 
   subgoal P;
   skip();
   subgoal G1;
   lemma1; lemma2;
   subgoal G2;
   //solved automatically
   subgoal G3;
   skip();
   subgoal Q
```

This would essentially be something like (but not the same as) to 'equational reasoning' in Agda or Idris on steroids (because of semi-automation) and I think would provide a nice way to develop and structure more complicated proofs/lemmas with the help of the solver.

Let us take a concrete example from the tutorial:

``` fsharp
val fold_left_cons_is_reverse: l:list 'a -> l':list 'a ->
                             Lemma (fold_left Cons l l' = append (reverse l) l')
let rec fold_left_cons_is_reverse l l' = match l with
  | Nil -> ()
  | Cons hd tl ->
    subgoal true; // precondition
    fold_left_cons_is_reverse tl (Cons hd l');
    subgoal (fond_left Cons tl (Cons hd l') = append (reverse tl) (Cons hd l')); // IH 
    append_cons (reverse tl) hd l';
    subgoal (fold_left Cons tl (Cons hd l') = append (append (reverse tl) (Cons hd Nil)) l'); // By above lemma
    reverse_append tl hd;
    subgoal (fold_left Cons (Cons hd tl) l' = append (reverse (Cons hd tl)) l') // Goal
```

One could imagine that in future extensions one could use the manual proving capabilities only between specific subgoals, and that the error messages could refer to the subgoals (or pre/post conditions) when assertions fail (like other issues state).

I hope that you found my idea interesting, and take my feature request under consideration.
Thank you in advance.

**Comment by catalin-hritcu** [comment]
It's an interesting idea we could try out at some point. Wouldn't hold my breath though :)

**Comment by ahmadsalim** [comment]
OK, thank you for the consideration.
I understand that since this is a request for a convenience feature, it is nowhere near your top priorities.

**Comment by catalin-hritcu** [comment]
@ahmadsalim We now have a full fledged tactics engine, so you should try if you're able to use it for this: https://arxiv.org/abs/1803.06547

**Comment by ahmadsalim** [comment]
Awesome, thanks for the response! I will try to look at it.
