### ISSUE TITLE
assert fails in the online editor

### ISSUE THREAD

**Issue by YaakovDavis** [FStarLang/FStar#508]
The following snippet, taken from the tutorial, fails to compile in the online editor:
`assert (max 0 1 = 1)`

**Comment by catalin-hritcu** [comment]
Indeed, this is confusing. There is no such thing as a top level assert statement in F*. You can only this within a top-level let definition.

**Comment by YaakovDavis** [comment]
Thanks.
What is the typeof such an expression?

Also, is there a way to print the type of an expression (either in the online editor, or in a compiled program)?

**Comment by catalin-hritcu** [comment]
> What is the type of such an expression?

Result type `unit`, but with a strong pre-condition.

> Also, is there a way to print the type of an expression (either in the online editor, or in a compiled program)?

For top-level definitions there is `--log_types`. For non-top-level things unfortunatelly we have nothing at the moment AFAIK, but it's on our list (see #219 and https://github.com/FStarLang/FStar/issues/27#issuecomment-77545198).

**Comment by YaakovDavis** [comment]
It would be nice to have it indeed :)
