### ISSUE TITLE
Kind system vs. Lean's universes

### ISSUE THREAD

**Issue by YaakovDavis** [FStarLang/FStar#512]
How does F*'s kind system compare with Lean's universes system?
What are the pros and cons of both approaches in terms of expressiveness, verifiability, etc?

**Comment by nikswamy** [comment]
The kind system of F\* is on the way out. The master branch now provides support for a '--universes' option. This provides universe polymorphism that's very similar to what Lean provides (in fact, our design was inspired by Lean's). The next release of F\* (anticipated in a few weeks) will make this --universes mode the default. While we don't have very much documentation of this new feature yet, you might be interested to read: https://github.com/FStarLang/FStar/wiki/Migrating-code-to-use-the---universes-mode-(particularly,-as-related-to-mitls-fstar)

**Comment by YaakovDavis** [comment]
Great info, thanks.
