### ISSUE TITLE
Extraction of machine integers

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#515]
Hi everyone,

Here is a summary of our last discussion with @protz @nikswamy and @aseemr regarding machine integers:

# Factoring the specification in a single file

Rather than actually rewriting N times the specification for the same operators, one for each signed and unsigned integers of each size, the plan is to encode everything in a single file.
That would lead to base types for signed and unsigned integer logic with definitions like
```
let rec pow2 (x:nat) : Tot pos = if x = 0 then 1 else 2 * pow2 (x-1)

type uint (n:nat) = x:int{x >= 0 /\ x < pow2 n}
type int_t (n:pos) = x:int{x >= - (pow2 (n-1)) /\ x x < pow2 (n-1)}
```
On those types all the operators will be defined with different specifications depending on how overflows are to be encoded (that has to be the programmer's choice).

For instance
```
val add: #n:nat -> a:uint n -> b:uint n{a + b < pow2 n} -> Tot (uint n)
let add #n a b = a + b

abstract val add_underspec: #n:nat -> a:uint n -> b:uint n -> Tot (c:uint n{a + b < pow2 n ==> c = a + b})
let add_underspec #n a b = if (a + b < pow2 n) then a + b else magic ()

val add_mod: #n:nat -> uint n -> uint n -> Tot (uint n)
let add_mod #n a b = (a + b) % (pow2 n)
```

Overall there should be operators for 
``` 
Arithmetic: +, -, *, /, %
Bitwise logic: &, |, ^, ~, >>, << (arithmetic or logical shifts based on whether the int is signed or not)
Comparisons: =, >=, >, <=, <
Various conversions: of_int, of_string, uint32_of_uint8 etc.
```

# Independent modules with different types for each actual integer

The issue was raised that with the previous type, one cannot prevent the user from using the actual integer to compute (using `Prims.op_Multiply` for instance), and the solver will not be able to tell that 
`type uint32 = uint 32` is actually different from `type uint64 = uint 64` for instance. At least not in the --universe branch because of a previous unsoundness on the type formers.

So each module should actually implement a specific type in the following pattern:
```
module FStar.UInt.UintN

abstract type uintN = | MkUIntN: v:uint N -> uintN

let v (x:uintN) : Tot (x':int{x >= 0 /\ x < pow2 N}) = x.v

let add (a:uintN) (b:uintN{v a + v b < max_int n}) : Tot uintN = MkIntN (add #N a.v b.v)
```
That implies that there will be some redundancy of the preconditions unfortunately.
The `v` function will allow people to retrieve and reason about the concrete mathematical value of the integer.
As it will be realized by big integers, it is probably not a good idea to use it is real code, there should be ad-hoc conversion between different sizes of uintNs, but I see no reason to forbid it.

# Separate modules and types for bitvectors
I would like to introduce some bitvector representation to encode the bitwise operator properly and @nikswamy says that Z3 has a theory for it.
They are envisioned implemented in separate modules with distinct types so that one could use Z3 logic with them. In which case there would be conversion function to and from those bitvectors to machine integers.
That is to be done.

# Overloading
A form of overloading could be made available for the specific operators of the machine integers. And only for those.
The idea would be to allow writing:
```
val blah: x:uint32 -> y:uint32{v x + v  y < 42} -> Tot unit
let blah x y = let (z : uint32) = x + y in ()

```
This assumption is that all the overloaded operators will be homogeneous. Instead of resolving the operator during the desugaring phase, it would happen during the typechecking phase.
These are not type classes however, meaning that `fun x y -> x + y` would be rejected, while `fun (x:int64) y -> x + y` or `let z:int = fun x y -> x + y` would be accepted.

NB: the `*` operator would still be reserved for tuples.

# Changes to FStar.Array
In order to realize integers properly and to be able to access F* arrays with integers, one currently has to use `--use_native_int` which is not safe.
The plan is to use 32 bit integers as indexes for arrays and similar cases.
Hence it will become necessary to give a bound proof for those values. How painful that would be is to be determined.

# Switching to Zarith for big integers

C.f. @msprotz post of the F* mailing list:
> When extracting unbounded integers (i.e. when NOT using --use_native_int), we now use zarith instead of OCaml's built-in bignum library. There are various reasons for that:
- Zarith is (harder) better faster stronger.
- Uses Pervasives.int as long as the number stays within bounds, switches to GMP otherwise.
- Big_int is going to die anyhow.
- More importantly, it supports polymorphic comparison, meaning that "if 1 = 1" is now properly extracted...
>
>Everyone: please run "opam install zarith" now. For our friends on Windows, you probably need "opam depext zarith" first.
>
>If you're using Makefile.include in ulib/ml, then everything should work "out of the box". If you're not, you need to use "ocamlfind ocamlopt -package batteries,stdint,zarith"
>
>Drawback:
- on Windows, if you get a message about a libstdc++.dll that cannot be located, you need to add:
>
>export PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/bin/:$PATH
>
>in your ~/.bashrc

I will soon push an example of the machine integer code in FStar/ulib.

**Comment by msprotz** [comment]
Zarith is done.

**Comment by jkzinzindohoue** [comment]
Had not seen that, I will edit, thanks !

**Comment by msprotz** [comment]
Everything is now done IIRC

**Comment by jkzinzindohoue** [comment]
This is now documented in the [wiki](https://github.com/FStarLang/FStar/wiki/Machine-integers).
Closing.
