### ISSUE TITLE
Issue in universe inference

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#516]
I have the following snippet:

``` fsharp
module Test

assume new type foo  //: Type0
abstract type bar = | Cons: foo -> bar
```

Without the `Type0` annotation, this code fails to typecheck with 

```
Expected expression of type "Test.foo<37>";
got expression "_0" of type "Test.foo<36>"
```

With the annotation uncommented it goes through, but then if I write a second module

``` fsharp
module Test2
open Test 
type tt = ref bar
```

it fails with 

```
Expected expression of type "Type(?15112)";
got expression "Test.bar" of type "Type(0)"
```

while if I typecheck

``` fsharp
module Test
assume new type foo : Type0
abstract type bar = | Cons: foo -> bar
type bar' = bar
type tt = ref bar // works here
```

with

``` fsharp
module Test2
open Test 
type ttt = ref bar' // works here too
```

it actually works.

**Comment by s-zanella** [comment]
I can no longer reproduce the first part of this bug: module Test now typechecks evenwithout the universe annotation. The second issue, typechecking Test2 without the annotation in Test1 is still open.

**Comment by tahina-pro** [comment]
I can no longer reproduce the second part of this bug: module Test2 now typechecks (except that one needs to add `open FStar.All` otherwise F* complains about `ref` not found.)
