### ISSUE TITLE
&& too eagerly lifted to /\

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#518]
The following code fails to typecheck:

```fsharp
module Test

let test () = 
  let x = alloc 0 in
  (read x = 1) && (read x = 1)
```
It gives `Expected a ghost expression;
got an expression "(Prims.op_Equality (FStar.ST.read x) 1)" with effect "FStar.ST.STATE"` 
After some testing, it seems that it is seen by F* as if the boolean expression was actually `read x = 1 /\ read x = 1` or `b2t(read x = 1 && read x = 1)`.
In the stratified branch it worked.
And the following also works as a workaround (but one does not get precedence):
```fsharp
module Test

let op_Amp_Amp = Prims.op_AmpAmp

let test () = 
  let x = alloc 0 in
  (read x = 1) && (read x = 1)
```

**Comment by nikswamy** [comment]
This is a known limitation, arguably by design. See Section 5 of the wiki page here: https://github.com/FStarLang/FStar/wiki/Migrating-code-to-use-the---universes-mode-(particularly,-as-related-to-mitls-fstar)

**Comment by nikswamy** [comment]
Your workaround is ok, but you will not get the expected short-circuiting semantics.

**Comment by jkzinzindohoue** [comment]
Sorry. 
I have now read that wiki page thoroughly so that I can stop complaining about documented things. Closing for now.
