### ISSUE TITLE
Various issues on osx

### ISSUE THREAD

**Issue by protz** [FStarLang/FStar#520]
- When I hit `make` from the `src` directory, the parser is rebuilt everytime
- I would argue for fstar-mono.sh to add a `--debug` argument by default to the invocation of `mono`; it took me a while to figure out why I had backtraces without line numbers...

@beurdouche thoughts?

**Comment by beurdouche** [comment]
@protz: to me this isn't very problematic. Maybe @s-zanella will have a different opinion ?

**Comment by s-zanella** [comment]
- Cannot reproduce the first issue anymore.
- I would just remove `bin/fstar-mono.sh`. It calls `fstar-mono.exe`, which is never generated.

**Comment by s-zanella** [comment]
Closing via 2c647f017a18294a534242c29daed2796a05531e
