### ISSUE TITLE
Add extraction to C/C++

### ISSUE THREAD

**Issue by eloraiby** [FStarLang/FStar#521]
What is the state of the C extraction branch ? c-extraction2 seems to have some activity.

Is it possible to have the road-map/progress shown somewhere ?

**Comment by jkzinzindohoue** [comment]
F* is moving from a stratified type system to universes.
The c-extraction2 branch was a prototype to experiment compilation from a subset to F* to C, using the stratified AST. As F* is moving away from it this branch will be deleted. It is not worth it currently to port it to the universes AST.

However we are working on designing and implementing this extraction to C properly in the master branch in the coming months (ideally in the coming 2~3 months).
Note that this shall target only a limited subset of F*, meaning that the code, after erasure of the ghost code and the specifications, will have to be first order, use specific memory monads, use only certain datatypes etc. It will have to be "C-like".

**Comment by nikswamy** [comment]
We also plan a backend to C++ that will support the full language. Probably in the 6 months timeline.

**Comment by eloraiby** [comment]
Good to know. Are there any road-map/task descriptions so someone could contribute ?

**Comment by eloraiby** [comment]
Any progress on this one ?

**Comment by msprotz** [comment]
Yes; work is happening at https://github.com/FStarLang/kremlin and significant chunks of code can be extracted already from the examples/low-level directory. Right now, this only makes sense for specific kinds of code (mostly, cryptographic code). The plan on record is still to extend the mechanism to be more general and eventually extract any F* code.

**Comment by catalin-hritcu** [comment]
This is being incrementally addressed by KreMLin, so I don't think we need an issue here for it.
