### ISSUE TITLE
Fail or warn on meaningless qualifier combinations

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#523]
I would like F* to fail or at least emit a warning when lax typechecking a file that has declarations or definitions with meaningless qualifiers. This would make the actual meaning of the qualifiers clearer for users. Some things that are currently accepted without warning:

```F#
assume type t = unit // assumed types mustn't be given a definition
assume abstract type u // `assume` and `abstract` must be mutually exclusive
abstract private type v = unit // `abstract` and `private` must be mutually exclusive
assume irreducible abstract private new type w // `irreducible` and `assume` must be mutually exclusive
inline val f: unit -> St unit // `inline` may be used only for pure functions
```

**Comment by catalin-hritcu** [comment]
For a start it would be great to document the various qualifiers on the wiki. I don't know what things like `abstract`, or `private`, or `irreducible`, do. Since you're already one step ahead on this, do you want to have a whack at documenting it?

**Comment by s-zanella** [comment]
Sorry, I should have said there's a wiki on this: https://github.com/FStarLang/FStar/wiki/Abstraction,-reduction-and-visibility-of-type-definitions

It hasn't been updated lately and doesn't answer all questions. For instance, it says that `abstract` is mutually exclusive with `private`, but it doesn't say whether it's also mutually exclusive with `assume`. I'm also a bit lost about the semantics of qualifiers, so I'll wait for confirmation for my guesses on the internal Slack channel before editting the wiki.

**Comment by catalin-hritcu** [comment]
Cool. I've just renamed that page so that it's easier to find:
https://github.com/FStarLang/FStar/wiki/Qualifiers-for-definitions-and-declarations

**Comment by nikswamy** [comment]
Fixed in bd846a7d48e5249c37bf69a7e69265100a450969

**Comment by s-zanella** [comment]
I saw that @kyoDralliam updated the wiki. Thanks, it reads much better now!

The fix still allows for `abstract private type v = unit`, although I don't think it makes much sense. `private` would make the definition opaque outside the module, so `abstract` doesn't seem to add anything.

**Comment by nikswamy** [comment]
Actually `abstract private` does make sense. `private` is just about hiding a symbol from a module `M`'s external namespace, so as not to pollute a client module's namespace when it does `open M`. I'll update the wiki.

And `inline val` is just a qualifier for the definition that should appear later in the module. `inline assume val` is rightfully rejected.

I'm closing the issue again. But, please feel free to report back here and re-open the issue if you come across puzzling cases again.
