### ISSUE TITLE
How to define a Money data type dependent on time

### ISSUE THREAD

**Issue by carsten-j** [FStarLang/FStar#524]
In Idris I can define a money data time dependent on time (represented by a double) like this
```
data Money : (time : Double) -> Type where
Amount : (x : Double) -> Money time
```
Money has a time value to 1 dollar today is not the same as 1 dollar tomorrow. Hence an add function for the money time should only allow adding money for the time time t. In Idris this goes like

```
add : Money t -> Money t -> Money t
add (Amount x) (Amount y) = Amount(x + y)
```
Is there a way to define something similar in F*? And if so can I also use the F# unit of measure type to ensure that one cannot add 1 dollar to 1 euro?

**Comment by nikswamy** [comment]
Not sure I follow Idris' syntax for this. Is `(time:Double)` a parameter of the `Money` type constructor? Assume so. 

In F\*, you can write something similar, except that we currently lack concrete support for the `double` type. We should add it soon (nothing particularly deep about lacking it now, except that it is not done yet). 
 
So, temporarily defining `double` as an alias for `int`, you can write something like this:

```
module Money
type double = int
type time = double
type currency = 
  | Dollar
  | Euro
type money (t:time) (c:currency) = 
 | Amount : x:double -> money t c

val add: #t:time -> #c:currency -> money t c -> money t c -> Tot (money t c)
let add #t #c (Amount x) (Amount y) = Amount (x + y)
```

Note, F\* is quite unrelated from F\#, aside from being inspired by it in some ways. So, you can't really use F\#'s units of measure in F\*.

**Comment by carsten-j** [comment]
You are right in the assumption. `(time:double)` is a parameter for the `money`type constructor. When I try to compile your suggestion I get an error:
```
Failed to solve the sub-problem
	(U7964 t c _6_13 _6_15) (Typ_app(Typ_uvar, [4 args]))
		=(TOP)
	(money _6_144 _6_145) (Typ_app(Typ_const Money.money, [2 args])) (guard ((U7973 t c _6_13 _6_15) /\ ((U7975 t c _6_13 _6_15) /\ True)))
Which arose because:
	TOP
Failed because:flex-rigid case failed all backtracking attempts
```
The error message is rather cryptic and hard to understand. I believe it is related to the add function because omitting that and I compiled without errors. Any ideas about why this fails?

**Comment by nikswamy** [comment]
Sorry about that. 

I tried it using the head revision of F\* from the master branch and it works fine. I guess you're using another version?

**Comment by carsten-j** [comment]
I am using version 0.9.2.0 from the release page and I am running OSX/mono. Will try to see if I can figure out how to build latest version from the master branch.

**Comment by carsten-j** [comment]
I got it to work after a bit of hacking. With the lastest version I can get as far as this message from the F* compiler.
> All verification conditions discharged successfully

However the generated F# file cannot compile without errors. But a few modification to the generated F# file got things running.
Thanks for the help and support.

**Comment by nikswamy** [comment]
Most of us using F\* tend to use the `--codegen OCaml` option. So, sadly, I'm not surprised that the F\# backend has regressed. If you have a spare moment, a bug report would be most welcome. We'll probably take our time to get to fixing it since getting the F\# backend up to speed again will take a bit of work, but it will be useful to track it.
