### ISSUE TITLE
Print.print_string instead of IO.print_string in the tutorial.

### ISSUE THREAD

**Issue by christophe-calves** [FStarLang/FStar#525]
The following line in section 2.3.1 of the tutorial (file [tutorial.mdk](https://github.com/FStarLang/FStar/blob/master/doc/tutorial/tutorial.mdk), line 557 and 564)

```
let hello_incr i = Print.print_string "hello"; i + 1
```

gives the error `Identifier not found: [Print.print_string]`. Shouldn't module `IO` be used instead?

[patch.txt](https://github.com/FStarLang/FStar/files/257604/patch.txt)

**Comment by beurdouche** [comment]
Indeed it should be `IO`, fixed by 4d562434bb5f299069b1e3da59aa28abeb5edb56
Thank you !
