### ISSUE TITLE
Tutorial not working: Unexpected error, Impos: expected String

### ISSUE THREAD

**Issue by bignoncedric** [FStarLang/FStar#529]
Hello,

Since this week-end, the fstar-lang website [tutorial section](https://fstar-lang.org/tutorial/) doesn't work anymore. When executing the code online, the F* output keeps returining:
> Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
> Impos: expected String

Even with the "Welcome" code snippet. Or even:
`module Welcome`

If this is not the right place to report this issue, please forward me to the right place.

Cédric

**Comment by catalin-hritcu** [comment]
Apparently Nik did some work on options 3 days ago that's probably related to this problem (https://github.com/FStarLang/FStar/commit/1465e9bb0ad5b8e13cdedc7a9e9b020ee7429a08).

**Comment by sishtiaq** [comment]
Where is the source for the tutorial?

**Comment by nikswamy** [comment]
How come this wasn't caught by the regression suite? We do run doc/tutorial regressions on each commit.

**Comment by ad-l** [comment]
The problem is not the tutorial; the F* backend of the tutorial is broken which is a problem with the compiler or the standard libraries. I suspect it's a library issue in this case.

**Comment by nikswamy** [comment]
The problem is that the tutorial invokes F\* in a manner slightly different than the way we test it in our regression suite. In particular, it specifies the --smt option, which the regressions tests do not. And my overhaul of the options broke the setting of --smt. I'm pushing a fix. Would be good to fix the regression suite to match the website.

**Comment by nikswamy** [comment]
pushed. Please give it a few minutes to update on the website. Many thanks, @bignoncedric, for the bug report.

**Comment by nikswamy** [comment]
FYI, @sishtiaq, the tutorial sources are in doc/tutorial

The code for the tutorial website itself is in the fstar-priv private repository.

**Comment by bignoncedric** [comment]
Thanks for the fix!
