### ISSUE TITLE
Error with the pipeline operator

### ISSUE THREAD

**Issue by polubelova** [FStarLang/FStar#530]
Hello, 

why the use of the pipeline operator (|>) changes the effect of computations?

Example:

```
val isEps: string -> list string -> Tot (list string)
let isEps s epsList = List.Tot.filter (fun x -> x = s) epsList
```

`All verification conditions discharged successfully`

With the pipeline operator:

```
val isEps: string -> list string -> Tot (list string)
let isEps s epsList = epsList |> List.Tot.filter (fun x -> x = s) 
```

`Computed type "(list string)" and effect "ALL" is not compatible with the annotated type "(list string)" effect "Tot"`

**Comment by nikswamy** [comment]
See `lib/FStar.All.fst`: it provides pipe_left and pipe_right, for the `ALL` monad.

You could define your own versions for whatever monad you're interested in, e.g,. Pure. 

Note, F\* lacks effect polymorphism. So, we don't have a generic way of defining the pipe operators for every monad.
