### ISSUE TITLE
Automated dependency analysis misses a dependency

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#531]
```F#
module M
assume type t

module N
assume val x:M.t -> bool
```

```
$ ./fstar.exe --universes --verify_module N N.fst
[...]/N.fst(2,15-2,16) : Error
Identifier not found: [M.t]
```

Setting `--debug Low` one can confirm that M is not processed

`Here's the list of filenames we will process: /Users/anonymous/fstar/ulib/FStar.FunctionalExtensionality.fst /Users/anonymous/fstar/ulib/FStar.Set.fst /Users/anonymous/fstar/ulib/FStar.Heap.fst /Users/anonymous/fstar/ulib/FStar.ST.fst /Users/anonymous/fstar/ulib/FStar.All.fst N.fst
`

Surprisingly changing `assume val x:M.t -> bool` to `assume val x:M.t` works fine.

**Comment by msprotz** [comment]
Huh. I'll take a look at it, thanks
