### ISSUE TITLE
assertion failure does not print sufficient information to debug

### ISSUE THREAD

**Issue by johanatan** [FStarLang/FStar#536]
I also enabled debug printing with:
`--debug ModuleName --debug_level Extreme`

and scanned that output but could not find any information on example values that would cause the assertion to fail.

Am I missing an easy way to get this information out of the engine? Or is it that the engine is reasoning at a level where this information is not easy for it to produce?

Here's the code that is causing the assertion failure:
```
module Primes

val isNotDivisor: n:nat -> d:pos -> r:nat -> Tot bool (decreases r)
let rec isNotDivisor n d runs =
  match runs with
  | 0 -> true
  | _ -> d * d > n || (n % d <> 0 && isNotDivisor n (d + 1) (runs - 1))

val isPrime: x:pos -> Tot bool
let isPrime n = n <> 1 && isNotDivisor n 2 (n / 2)

type prime = x:pos{isPrime x}

let a = assert(forall (p:prime) (n:pos{n > 1 && n < p}). p <= 2 || isNotDivisor p n 1)
```

**Comment by johanatan** [comment]
Also, any advice on debugging assertion failures generally would be appreciated (as well as any specific insight re: the particular failure above).

**Comment by s-zanella** [comment]
There is not much you can debug. This is a case where *the engine is reasoning at a level where this information is not easy for it to produce*. The formula inside the assertion is sent as a whole to Z3, which fails to prove (or disprove) it. This shouldn't be too surprising, because a proof requires to reason by induction.

If it is of any help, here's a proof of the assertion you wanted to prove, using the more idiomatic `Lemma` notation:

```F#
val fact_1: n:nat -> d:pos -> Lemma (isNotDivisor n d 1 <==> (d * d > n) \/ (n % d <> 0))
let fact_1 n d = ()

val fact_2: n:nat -> d:pos -> r:nat -> a:nat{ d <= a /\ a < d + r } -> Lemma
  (requires isNotDivisor n d r)
  (ensures  (a * a > n \/ n % a <> 0))
  (decreases r)
let rec fact_2 n d r a =
  if r = 0 || d = a then ()
  else fact_2 n (d + 1) (r - 1) a

val conclusion: p:prime -> n:pos{n > 1 /\ n < p} ->
  Lemma (p <= 2 \/ isNotDivisor p n 1)
let conclusion p n =
  if p <= 2 then ()
  else if n < 2 + (p / 2) then (fact_2 p 2 (p / 2) n; fact_1 p n)
  else ()
```

At the moment, there is little support for debugging typing errors. You may try the `--detail_errors` and `--split_cases` command-line options in the master branch, but I haven't had any luck using them. Instead, what I do is to insert `admit()` and intermediate assertions at strategic points to reduce the scope and detect the part of the verification condition that is failing. Another handy trick is using `~>` in place of `->`  in pattern matching branches to *focus* on one branch at a time. This has effectively the same effect as admitting every branch but the ones using `~>`.

**Comment by johanatan** [comment]
Thanks for that although I don't think it is fair to call that code "more idiomatic". Per the tutorial (and common sense), the decision to use refinement types on the functions, assertions or lemmas is "subjective" and a matter of personal style.

And, in my opinion, the code I tried to write is much prettier and to the point. It would be really great to find a way to make it work. It appears like maybe the engine just needs more hints/facts (so I'll try capturing a few more of your specs [in hopefully tighter syntax]).

**Comment by jkzinzindohoue** [comment]
I think you are missing the point about the "more idiomatic" remark.
As Santiago stressed out, the assertion you are trying to verify requires a proof the solver cannot completely infer. There is no "magic" involved here. If the solver cannot do it alone, you need to provide additional lemmas to help it, whatever the style you are using may be.

In your case, if you add a pattern to Santiago's lemma:
```
val conclusion: p:prime -> n:pos{n > 1 /\ n < p} ->
  Lemma (requires (True))
	(ensures (p <= 2 \/ isNotDivisor p n 1))
	[SMTPat (isNotDivisor p n 1)]
let conclusion p n =
  if p <= 2 then ()
  else if n < 2 + (p / 2) then (fact_2 p 2 (p / 2) n; fact_1 p n)
  else ()

let a = assert(forall (p:prime) (n:pos{n > 1 && n < p}). p <= 2 || isNotDivisor p n 1)
```
Then your assertion works like a charm because the solver has all the hints it requires. The thing is that using lemmas in that fashion, and associating them to patterns for quantifiers, is a robust way to help the solver instantiate quantifiers properly.

**Comment by s-zanella** [comment]
Thanks Jean-Karim. That's a nice example of using patterns, which I completely forgot.

@johanatan: If you want tighter syntax, here is a concise (but arguably less readable) proof that doesn't use `Lemma`:
```
let conclusion (p:prime) (n:_{1 < n /\ n < p}): Tot (u:_{p <= 2 \/ isNotDivisor p n 1}) =
  let rec f n d r (a:int{isNotDivisor n d r /\ d <= a /\ a < d + r}):
    Tot (u:_{a * a > n \/ n % a <> 0}) (decreases r) =
    if d = a then () else f n (d + 1) (r - 1) a
  in if n < p/2 then f p 2 (p/2) n else _
```
The first argument of `f` could be omitted if #533 was fixed.

Another remark: in your original code, `a` doesn't carry any computational or logical meaning. So, once the assertion is proven, there is no way you can later use what was proven.

**Comment by johanatan** [comment]
@jkzinzindohoue As I mentioned before, it was the assertion that Lemmas are "more idiomatic" than refinement types directly on the functions that I took issue with (and that view is supported by the tutorial itself). SMTPat is neat--I'll have to look into that some more.

@s-zanella Thanks! That is better to my eyes at least. Just a couple of questions though-- is the type of `u` Unit? Does the `_` represent unit in that case or just whatever type needs to be inferred there (i.e., generic)? Or something else?

**Comment by s-zanella** [comment]
Both `u`s are inferred to have type `unit`. The notation `_` asks F* to infer a type.
You can see inferred types with `--log_types`

**Comment by johanatan** [comment]
Ahh, that's what I figured. Is there any reason these two return `Tot` instead of `GTot`? There doesn't seem to be any computation at the value-level going on in there. And, if not, I'm not completely opposed to benefiting from Lemma's 'sugar' where Lemmas can't be avoided-- was more just a desire to avoid the Lemmas in the first place (but at least we have gotten rid of `fact_1` and `fact_2`). :)

**Comment by s-zanella** [comment]
No reason to use `Tot`, using `GTot` is actually better.
You can get rid of `fact_1`, but not the induction in `fact_2`. It is hidden in the local `let rec` in the second proof.

**Comment by johanatan** [comment]
Yea, I understand that the essence of `fact_2` was nested inside `conclusion` but I meant that the actual top-level val `fact_2` is eliminated. 😉

Thanks again for all your help!

**Comment by s-zanella** [comment]
Good to know we're on the same page.
Thanks for bringing up the question!

**Comment by johanatan** [comment]
P.S. It seems that your code isn't compiling.

```
/Users/jonathan/Documents/SourceCode/fstar-examples/primes.fst(22,50-22,92) : Error
Kinds "Effect" and "Type" are incompatible
```

[Line 22 is the first line and column 50 is the beginning of the first `Tot`]. I tried changing both `Tot`s to `GTot` as well to no avail.

**Comment by s-zanella** [comment]
You're likely missing the `--universes` flag.

**Comment by johanatan** [comment]
Hmm, adding that flag caused a lot of other stuff to break earlier in the file.

Copied from FStar.Constructive (as my build isn't currently able to import things directly)
```
type cexists (#a:Type) (p:a -> Type) : Type =
  | ExIntro : x:a -> h:p x -> cexists p

type divides (a:pos) (b:pos) = (cexists (fun (c:pos) -> (a*c) == b))  // Error: Expected expression of type "Type"; got expression "a" of type "Prims.pos"
```

```
val isNotDivisor: n:nat -> d:pos -> r:nat -> Tot bool (decreases r)
let rec isNotDivisor n d runs =
  match runs with
  | 0 -> true
  | _ -> d * d > n || (notDivides n d && isNotDivisor n (d + 1) (runs - 1)) // Error: Expected expression of type "Type"; got expression "d" of type "Prims.pos"
```

**Comment by s-zanella** [comment]
A consequence of `--universes` is that the type constructor `*` and the multiplication operator cannot be disambiguated by the kind. Try with `let op_Star = op_Multiply`

**Comment by johanatan** [comment]
That seems to have helped but there are still issues:

```
Jonathans-MacBook-Pro:fstar-examples jonathan$ fstar.exe --universes primes.fst  
/Users/jonathan/Documents/SourceCode/fstar-examples/primes.fst(15,9-15,10) : Error
Expected expression of type "Type";
got expression "d" of type "Prims.pos"
Jonathans-MacBook-Pro:fstar-examples jonathan$ fstar.exe --universes primes.fst  
/Users/jonathan/Documents/SourceCode/fstar-examples/primes.fst(25,2-30,3) (Warning): Non-top-level recursive functions are not yet fully encoded to the SMT solver; you may not be able to prove some facts
/Users/jonathan/Documents/SourceCode/fstar-examples/primes.fst(25,2-30,3) (Warning): Non-top-level recursive functions are not yet fully encoded to the SMT solver; you may not be able to prove some facts
/Users/jonathan/Documents/SourceCode/fstar-examples/primes.fst(28,23-30,3): Subtyping check failed; expected type (?17125 p n f); got type (u#3162:Prims.unit{(Prims.l_or (Prims.b2t (Prims.op_GreaterThan (Primes.op_Star n n) p)) (Prims.b2t (Prims.op_disEquality (Prims.op_Modulus p n) 0)))})
Error: 1 errors were reported (see above)
```

Here's the entire file:
```
module Primes

let op_Star = op_Multiply

type cexists (#a:Type) (p:a -> Type) : Type =
  | ExIntro : x:a -> h:p x -> cexists p

type divides (a:pos) (b:pos) = (cexists (fun (c:pos) -> (a*c) == b))

val notDivides: n:nat -> d:pos -> Tot bool
let notDivides n d = n % d <> 0

val isNotDivisor: n:nat -> d:pos -> r:nat -> Tot bool (decreases r)
let rec isNotDivisor n d runs =
  match runs with
  | 0 -> true
  | _ -> d * d > n || (notDivides n d && isNotDivisor n (d + 1) (runs - 1))

val isPrime: x:pos -> Tot bool
let isPrime n = n <> 1 && isNotDivisor n 2 (n / 2)

type prime = x:pos{isPrime x}

let conclusion_0 (p:prime) (n:_{1 < n /\ n < p}): Tot (u:_{p <= 2 \/ isNotDivisor p n 1}) =
  let rec f n d r (a:int{isNotDivisor n d r /\ d <= a /\ a < d + r}):
      Tot (u:_{a * a > n \/ n % a <> 0}) (decreases r) =
    if d <> a then f n (d + 1) (r - 1) a
    in if n < p/2 then f p 2 (p/2) n

val fact_1: n:pos -> d:pos -> Lemma (isNotDivisor n d 1 <==> d * d > n \/ notDivides n d)
let fact_1 n d = ()

val fact_2: n:nat -> d:pos -> r:nat -> a:nat{ d <= a /\ a < d + r } -> Lemma
  (requires isNotDivisor n d r)
  (ensures  (a * a > n \/ notDivides n a))
  (decreases r)
let rec fact_2 n d r a =
  if r = 0 || d = a then ()
  else fact_2 n (d + 1) (r - 1) a

val conclusion: p:prime -> n:pos{n > 1 /\ n < p} -> Lemma (p <= 2 \/ isNotDivisor p n 1)
let conclusion p n =
  if p <= 2 then ()
  else if n < 2 + (p / 2) then (fact_2 p 2 (p / 2) n; fact_1 p n)
  else ()

val gcd: a:nat -> b:nat -> Tot nat (decreases %[b;a])
let rec gcd a b =
  match b with
  | 0 -> a
  | _ -> gcd b (a % b)

val coprime: a:nat -> b:nat -> Tot bool
let coprime a b = gcd a b = 1

val fact_4: a:nat -> b:nat -> Lemma(coprime a b <==> gcd a b = 1)
let fact_4 a b = ()

//val abs: x:int -> Tot (y:int{ ((x >= 0) ==> (y = x)) /\ ((x < 0) ==> y = -x) })
//let abs x =
//  if x >= 0 then x
//  else -x

//val fact_5: a:pos -> b:pos -> Lemma(coprime a b <==> isPrime (abs (a - b)))
//let fact_5 a b = ()
```

**Comment by s-zanella** [comment]
It works for me with Z3 4.4.1.
The proof of `conclusion_0` may be too demanding for your setup. You can try increasing `--z3timeout`.

**Comment by johanatan** [comment]
Ahh, yep. That worked! 

Do you know what this warning means (re: your `let rec f ...` inside `conclusion_0`?

```
/Users/jonathan/Documents/SourceCode/fstar-examples/primes.fst(25,2-30,3) (Warning): Non-top-level recursive functions are not yet fully encoded to the SMT solver; you may not be able to prove some facts
```

**Comment by s-zanella** [comment]
Great!

That means that when typechecking `conclusion_0`, Z3 doesn't see the definition of `f`. But that's fine because the rest of the proof doesn't rely on the definition, just on the type signature.

**Comment by johanatan** [comment]
So, the following variation type checks much faster (only a few seconds) and doesn't require the --z3timeout flag:

```
let conclusion_0 (p:prime) (n:_{1 < n /\ n < p}): Lemma (p <= 2 \/ isNotDivisor p n 1) =
  let rec f n d r (a:int{isNotDivisor n d r /\ d <= a /\ a < d + r}):
      Lemma (ensures (a * a > n \/ n % a <> 0)) (decreases r) =
    if d <> a then f n (d + 1) (r - 1) a
    in if n < p / 2 then f p 2 (p / 2) n
```

whereas this one takes a couple of minutes with --z3timeout set to 600:
```
let conclusion_0 (p:prime) (n:_{1 < n /\ n < p}): Lemma (p <= 2 \/ isNotDivisor p n 1) =
  let rec f n d r (a:int{isNotDivisor n d r /\ d <= a /\ a < d + r}):
      GTot (u:_{a * a > n \/ n % a <> 0}) (decreases r) =
    if d <> a then f n (d + 1) (r - 1) a
    in if n < p / 2 then f p 2 (p / 2) n
```

Is this a known performance bug? Doesn't Lemma de-sugar into exactly that same code?

**Comment by s-zanella** [comment]
I don't observe much difference between the two. For me, the latter takes slightly more time to typecheck, but the difference is at most a couple of seconds.

My understanding is that `Lemma` should de-sugar to the same code you wrote, except that `_` would become `unit`. Replacing `_` by `unit` does seem to speed up typechecking.
