### ISSUE TITLE
Add support for coinduction

### ISSUE THREAD

**Issue by johanatan** [FStarLang/FStar#538]
I've scanned the examples and tutorial and can't find any mention of this. Is there some other way to achieve the same? [I did notice that 'lazy' itself for a single val is not supported and not planned to be (unfortunately)]. Are there common techniques to workaround lack of laziness/ infinitudes?

**Comment by catalin-hritcu** [comment]
F* has no laziness but you can encode it with thunks (`fun _:unit -> e` is a suspended version of `e`). You can do streams and other lazy data structures using thunks:
https://www.cs.cornell.edu/courses/cs3110/2011sp/lectures/lec24-streams/streams.htm

**Comment by johanatan** [comment]
Hi @catalin-hritcu , thank you for that helpful answer.

Do you know what it would require to make the `from`function below `Tot[al]`? It would seem to me to be total already (given that the creation of `stream` containing a head and a thunked tail should return immediately) but that won't compile due to the following error:

```
/Users/jonathan/Documents/SourceCode/fstar-proofs/primes.fst(31,25-31,32): Subtyping check failed; expected type (n#3520:Prims.pos{(Prims.precedes n@0 n)}); got type Prims.int
```

```
type stream 'a =
  | Nil : stream 'a
  | Cons : hd:'a -> rest:(unit -> stream 'a) -> stream 'a  // line 31

let rec from (n:pos) : stream pos =
  Cons n (fun () -> from (n + 1))
```

**Comment by catalin-hritcu** [comment]
Right. Proving that co-recursive functions on streams are total is indeed tricky, if at all possible. F\*'s semantic termination check targets recursion, not co-recursion. It would be interesting to see if co-recursion ideas from other tools like Dafny could at some point be ported to F\*.

So you can still program with streams, but you won't be able to prove totality for now.

**Comment by fangyi-zhou** [comment]
Hi, sorry to comment on this old thread. Is there any development on coinduction as of now?

**Comment by catalin-hritcu** [comment]
@fangyi-zhou  Not as far as I know. AFAIK @kyoDralliam did think a bit about some workarounds based on axioms.

**Comment by aseemr** [comment]
It is not on the roadmap right now, marking as wontfix and closing until we revisit.
