### ISSUE TITLE
Feature request: automatic generation of lemmas

### ISSUE THREAD

**Issue by johanatan** [FStarLang/FStar#539]
In the file `FStar/examples/verifythis/2015/01.fst` there are 3 value-level functions and 3 type-level functions (lemmas) which are structurally identical to the functions they are verifying (i.e., values returned from the one become `unit` returned in the other; recursion in the one becomes recursion in the other/etc).

I propose the introduction of a syntax like the following (for example) and automatic generation of the Lemma bodies (i.e., uninteresting rote) requiring only the `ensures`/`requires`/etc clauses (the interesting bits) of the Lemma (and this covers probably the vast majority of Lemmas):

```
   val prefix : p:list nat -> str:list nat -> Tot bool
     [Lemma (prefix p str = true <==> (exists (l:list nat). append p l = str)]
   let rec prefix p str = match p with
   | [] -> true
   | a::q ->
        (match str with
        | [] -> false
        | a'::q' -> if a = a' then prefix q' q else false
       )
```

This repetition/reality of dealing with Lemmas is also why I was initially inclined to try to avoid them if at all possible. The potential for making mistakes in the copies (e.g., swapping the order of `q` and `q'` in the recursive call above [which would apparently have no effect at the type level but would otherwise confuse readers]) is too great and the requirement of making two copies of each algorithm is too burdensome.

**Comment by catalin-hritcu** [comment]
For very simple cases you might use the "Automatic induction" experimental feature:
https://www.fstar-lang.org/tutorial/tutorial.html#auto-ind

When this doesn't work (i.e. very often) you currently need to duplicate things and while I agree this is not nice, we currently have no support for meta-programming in F\*, and I wouldn't hold my breath for that landing any time soon (see #217).

**Comment by s-zanella** [comment]
Most of the time you can avoid writing a separate Lemma (an extrinsic proof) and just attach the property you want to prove to the functions themselves (an intrinsic proof). Your example is exactly a case where you could do that:

```F#
val prefix : p:list nat -> str:list nat -> Tot (b:bool{ b ==> (exists l. append p l = str)})
let rec prefix p str = match p with
| [] -> true
| a::q -> 
     (match str with 
      | [] -> false 
      | a'::q' -> if a = a' then prefix q q' else false
     )
```

If you haven't already, see the discussion in the tutorial:
[4.2. To type intrinsically, or to prove lemmas?](https://www.fstar-lang.org/tutorial/tutorial.html#sec-to-type-intrinsically-or-to-prove-lemmas)

**Comment by aseemr** [comment]
This is not on the roadmap right now and Santiago's example provides an alternate way to structure things. Marking as wontfix and closing until we decide to revisit.
