### ISSUE TITLE
Difference between SMTPat and SMTPatT in --universes

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#547]
Can someone shed some light on why this is accepted with `--universes`?

`val f: u:unit -> Lemma (requires True) (ensures True) [SMTPat True]`

More generally, what's the difference between `SMTPat` and `SMTPatT` with `--universes`, if any?

I'm asking because I was confused by this error message:

``` F#
module M
val f: u:unit -> Lemma (requires True) (ensures True) [SMTPat True]
let rec f _ = ()
```

```
$ fstar.exe --universes M.fst --print_universes
M.fst(3,54-3,67) : Error
(Prims.list<(S (S 0))> Prims.pattern<(S 0)>) is not a subtype of the expected type (Prims.list<(max (S 0), (S ?14413))> Prims.pattern<?14413>)
```

Why`?14413` doesn't unify with `S 0`?
It typechecks if one replaces the `let rec` above with `let`.

Edited: I think I see what's going on, `SMTPat` must be adding a `?14413 = 0` constraint. Still, I don't understand why using `let rec` makes a difference.

**Comment by nikswamy** [comment]
I think SMTPatT is around for a bit of backwards compatibility; We should remove it.

Not sure about the let rec. Will have to stare at it a bit more.

**Comment by s-zanella** [comment]
The error is gone in master.
Tracking the separate issue of removing `SMTPatT` in #957.
