### ISSUE TITLE
Make universes the default

### ISSUE THREAD

**Issue by vkanne-msft** [FStarLang/FStar#550]

**Comment by nikswamy** [comment]
Very easy to implement. But the switch requires either porting more of our regression suite to universes or fixing the make files to get them to use --stratified

**Comment by sishtiaq** [comment]
I can do this. What's the urgency/duedate?

**Comment by nikswamy** [comment]
Would be great to do this ASAP. Many of us have been bitten by forgetting to add --universes

**Comment by jkzinzindohoue** [comment]
Adding `(setq fstar-subp-prover-args '("--universes"))` to the `.emacs` as you showed me may help in the mean time.

**Comment by catalin-hritcu** [comment]
One blocker is the online tutorial which still uses stratified and would break immediately if this change was made in master. @beurdouche had started porting things at some point (b7361c31), but I don't know what the status of that is.

**Comment by sishtiaq** [comment]
So, can Nik and Catalin confirm what needs to be ported:
- FStar/doc/tutorial/code
- FStar/examples
- mitls-fstar [is mostly working with universes, I think]

**Comment by nikswamy** [comment]
We marked this an "easy fix" with the following tasks in mind:

1. Add a new flag, '--stratified', to the F\* compiler. This should set the Options.universes variable to false. By default, Options.universes should be true.

2. Remove the '--universes' flag

3. Go through all the makefiles, FStar/examples and FStar/doc/tutorial setting the flags appropriately. mitls-fstar already uses --universes exclusively. We just have to drop the flag from the Makefile.

Actually porting all the examples etc. is a much more lengthy task. We should track that separately.

**Comment by s-zanella** [comment]
Closed by 1ed937b3e5f7452bc7f08e85ccff464e1e0693a4.
Thanks @sishtiaq.

**Comment by sishtiaq** [comment]
Nik's comment:
> Actually porting all the examples etc. is a much more lengthy task. We should track that separately.

A lot of the examples and tutorial code carries on working because they use --stratified. #565 tracks the work to removed the use of this flag.
