### ISSUE TITLE
rm .old dir

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#553]
Find out (@nikswamy @vkanne-msft should know) whether this is used or not. If not, then delete.

**Comment by catalin-hritcu** [comment]
The information in `.old` is not publicly available anywhere else, so probably no.

**Comment by sishtiaq** [comment]
Is it still used tho'?

**Comment by catalin-hritcu** [comment]
It's the subject of a ton of already published papers and it needs to be available somewhere for good reproducibility of research reasons. It's currently linked here:
https://github.com/FStarLang/FStar#old-f-versions-v071-and-earlier
So in this sense, yes, it is used.
Whether it was a good idea to add it to the repo is a different question, Nik doubted that afterwards too, but now it's done, and there is no benefit in removing it. On the contrary, it would just cause more confusion.

**Comment by sishtiaq** [comment]
That links to .old/ fstar-0.7.1-alpha.zip. Do you know anything about the .old/to_be_ported dir?

**Comment by catalin-hritcu** [comment]
@nikswamy can answer this better. AFAIK they some old examples he took out of the zip file thinking that it would be a good idea to one day port them to new F*. That was 2 years ago, or so, and it doesn't seem that much happened with them. Still, I don't see any harm in having them there.

**Comment by nikswamy** [comment]
I agree with Catalin: removing this would only cause more confusion now. 

As for the to_be_ported directory: Yes, it would be nice to port them, But, it's now a much lower priority than porting stuff from src/examples to universes.

Closing this issue. Recording that we could port more examples in #90
