### ISSUE TITLE
FStar.All.ML not found when using an FStar.* module that uses the ML effect 

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#555]
`M.fst`
```F#
module M
open FStar.N
```
`FStar.N.fsti`
```F#
module FStar.N
val f: unit -> unit
```
```
$ fstar.exe --universes M.fst
\FStar.N.fst(2,15-2,19) : Error
Name "FStar.All.ML" not found
```
The problem comes from the order in which dependencies are processed. When depending on `FStar.N.fsti`, `FStar.N.fsti` is processed before `FStar.All.fst`. When depending on `N.fsti`, `N.fsti` is processed after `FStar.All.fst`.

One can argue that one shouldn't add new modules in the FStar namespace, but some libraries (e.g. `FStar.String`) already trigger this bug.

**Comment by s-zanella** [comment]
Thanks. 
Actually, I remember you said you were going to change this behavior before (probably on Slack). I'll fix FStar.String and maybe other libraries accordingly and then close this.

**Comment by msprotz** [comment]
Thanks!

**Comment by msprotz** [comment]
I'm surprised that these haven't been caught by the regression suite. If you can add the files you fix in the `Makefile` for `ulib/` that would probably be helpful
