### ISSUE TITLE
Interactive mode for interfaces/implementations when files are split between FSTI and FST 

### ISSUE THREAD

**Issue by vkanne-msft** [FStarLang/FStar#557]
Interactive mode is broken when files are split into fsti and fst

**Comment by nikswamy** [comment]
Not sure I agree with the "broken" part. It just wasn't designed to support interactive mode in the first place. 

There was a proposal (not sure it was ever written up) about having a feature in the interactive mode to mark definitions that may rely on as-yet-undefined values (coloring them differently, for example). And to only mark them as checked when all their immediate dependences have been checked also.

This requires work both on fstar-mode.el and on the F* compiler itself.

**Comment by nikswamy** [comment]
This is now supported.
