### ISSUE TITLE
Pre-type-checking bug for polymorphic function applied to partial application

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#56]
The way I run across this problem involved `using_induction_hypothesis`, but that isn't crucial for the bug, so I simplified it to this:
```
val g : x:'a -> Lemma (ensures True)
let g x = ()

val xxx : x:nat -> y:nat -> Lemma (ensures (x=y))
let rec xxx x y = g (xxx y)
```
The error message is very strange:
```
examples\unit-tests\bugXX.fst(7,20-7,27) : Error
Expected type "U1026"; got type "(y:nat -> Lemma (unit))"
```
The partial application of `xxx` seems crucial for triggering this; just `g xxx` works fine.

**Comment by nikswamy** [comment]
This is fixed now.
