### ISSUE TITLE
Function type not unfolding when projecting from a pair

### ISSUE THREAD

**Issue by danelahman** [FStarLang/FStar#561]
I would expect the following small piece of code to typecheck, but it doesn't:
```
let t = nat * (nat -> Tot unit)

val f : t -> nat -> Tot unit
let f p n = (snd p) n
```

Instead, I need to do an explicit bind to get the application to work:
```
let t = nat * (nat -> Tot unit)

val f : t -> nat -> Tot unit
let f p n = 
  let q = snd p in
  q n
```

**Comment by beurdouche** [comment]
Hum, when I am testing this with `--universes`, both typecheck. Can you confirm ?

**Comment by danelahman** [comment]
I was also using fstar with `--universes` but apparently my copy of fstar was older than I thought. Can now confirm that it typechecks with today's checkout from github.
