### ISSUE TITLE
Issue with interfaces/implementations when files are split between FSTI and FST

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#563]
Hello,

In the wiki, it is written the following:

```
Put the vals in A.fsti (the "partial module"), the lets in A.fst in the same order, then call fstar A.fsti A.fst. What happens is:

F* verifies the concatenation of A.fsti and A.fst
drops the environment
then starts over with only A.fsti, where every val is now assume'd
```

I was really pleased with this system so I tried it but I have the impression that it's not working. (I just pulled the last version of Fstar).

Test.fst:
```
module Test

let p n = []
```

Test.fsti
```
module Test

val p : nat -> nat
```

I thought the concatenation would correspond to:
```
module Test

val p : nat -> nat
let p n = []
```
which should not compile.

But if I call `mono fstar.exe test.fsti test.fst` then I obtain
```
Verifying i'face: Test
All verification conditions discharged successfully
```

Any suggestion ?

Best,
Vincent

**Comment by beurdouche** [comment]
Hi Vincent, 
I think this is due to the stratified typechecker that apparently only checks the interface.
You might want to try that with the new typechecker using the `--universes` option.
I think in that case it will fail... Can you please confirm ?

**Comment by VincentCheval** [comment]
Ho I thought that the universes option was by default in the latest version of FStar. It's not the case then ? I can't test it right now since he tells me that I need a new version of Z3 but I'll try it as soon as I install it.

Best,
Vincent

**Comment by VincentCheval** [comment]
I just installed Z3 with the new version and it works well with the `--universes` option. Thanks

**Comment by beurdouche** [comment]
Unfortunately `--universes` is not yet the default. It will be in the next release but we have first to update the tutorial, the examples... Cheers. B.

**Comment by beurdouche** [comment]
Closing as we are not going to fix this in stratified mode.
