### ISSUE TITLE
Port examples and doc/tutorial to universes

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#565]
The compiler now has universes switched on by default. But a lot of the examples and doc/tutorial still use --stratified. They need to be updated to use the default universes. 

To find which files are still using the old mode, grep for "SFSTAR=", and for "-stratified". 

Could also port stuff from .old/to_be_ported.

**Comment by catalin-hritcu** [comment]
As I've already mentioned before, @beurdouche had already started porting the tutorial at some point. His work is in https://github.com/FStarLang/FStar/tree/master/doc/tutorial/code/solutions_universes

**Comment by s-zanella** [comment]
@beurdouche: so, all exercises in https://github.com/FStarLang/FStar/tree/master/doc/tutorial/code/solutions_universes already work with universes, and the ones in the `todo` folder need to be ported?

**Comment by beurdouche** [comment]
Yes, exactly.
In the `todo` folder, I attempted to split the original files into modules (no support for multiple modules anymore) but it seems I screwed up the order of modules. A suggestion would be to simply drop the `todo` folder and restart Ex9+ from the original files...

**Comment by sishtiaq** [comment]
@beurdouche Shall we leave porting the tutorial code in your hands?

**Comment by s-zanella** [comment]
@sishtiaq: I'll probably do it for the tutorial we'll have at MSR next week.
Help is welcome, of course.

**Comment by beurdouche** [comment]
@sishtiaq @s-zanella: not sure I'll have time to get back to this quickly, so feel free to pick it up if you wish...

**Comment by sishtiaq** [comment]
@beurdouche That's ok. And thanks for telling us!
@s-zanella You can take doc/tutorial, I'll take examples. Is that ok?

**Comment by markulf** [comment]
Let me know if I can help with this.

**Comment by s-zanella** [comment]
Closing this. We have a separate issue (#827) to track examples that have not yet been ported.
