### ISSUE TITLE
Non inductive types should be allowed in mutually inductive definitions

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#566]
This is a minor nuisance since there are simple workarounds.

This used to work:

``` F#
type value =
  | C: nat -> value
  | F: env value -> value
and env = nat -> Tot value
```

Now it fails with a `Mutually defined type contains a non-inductive element`.

The workaround is to define first `env` and then `value`:

``` F#
type env value = nat -> Tot value
type value =
  | C: nat -> value
  | F: env value -> value
```

See also #258 and #259.

**Comment by nikswamy** [comment]
FYI: I plan to support this relatively soon. It's needed for bootstrapping and rewriting the compiler code to avoid this is more than a minor nuisance. Jonathan and I have had some discussions about how to desugar such examples.

**Comment by tahina-pro** [comment]
Branch `taramana_mutrec_types` in progress. Currently being tested on some mutually recursive type definitions of the F* implementation itself.

**Comment by tahina-pro** [comment]
Just merged into `master`.
