### ISSUE TITLE
FStar.Comp and FStar.Relational are not ported to universes

### ISSUE THREAD

**Issue by vkanne-msft** [FStarLang/FStar#569]
FStar.Comp and FStar.Relational are not ported to universes

**Comment by beurdouche** [comment]
Hi ! Both seem to be in `ulib`:
`ulib\FStar.Relational.Comp.fst`
`ulib\FStar.Relational.Relational.fst`

**Comment by s-zanella** [comment]
Yes, they are there and they typecheck (since a couple of weeks).
Closing.
