### ISSUE TITLE
Recursive function, guarded type

### ISSUE THREAD

**Issue by MallabaevAzamat** [FStarLang/FStar#570]
Why F* don't verify recursive function.

> X(11,0-14,21): Z3 provided a counterexample, but, unfortunately, F* could not translate it back to something meaningful
> Error: 1 errors were reported (see above)

Code:

```
module X

val pred: list int -> Tot bool
let rec pred l =
    match l with
    | [] -> false
    | u :: o -> true

type ptype = g:list int {pred g}

val f: ptype -> Tot (list int)
let rec f xs =
    match xs with
    | [] -> []
    | _ :: ys -> f ys
```

when F* may successfully verify code where "ptype" replaced to "list int" (inside "val" of function)?

**Comment by aseemr** [comment]
Hello!

For the recursive call `f ys`, F* needs to prove that `pred` holds true for `ys`, as the type of `f` requires it. Rightly so, F* fails to prove it. For example, if `xs = [2]`, `ys = []`, and then `pred` is not true for `ys`.

**Comment by MallabaevAzamat** [comment]
Thank you!
