### ISSUE TITLE
OCaml extraction of constructor application without implicit parameters stalls

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#573]
I haven't had time to create a minimal example.
This shows up during extraction of `TestServer.fst` in https://github.com/mitls/mitls-fstar/commit/889753d4151e52dae6d925b7c92c0fdb62338f33. The problem appears to be in this line: 

`AEAD_GCM.State key iv () counter`

Providing the implicit arguments explicitly solves it:

`AEAD_GCM.State #id #Writer #r #r key iv () counter`

To reproduce, run 

`make test/TestServer.fst-lax OTHERFLAGS="--codegen OCaml --debug_level Extreme --debug TestServer`

It gets stuck at 

`mitls-fstar/src/tls/test/TestServer.fst(238,70-238,71) (Tm_constant)
Return comp type is PURE Prims.string`

**Comment by nikswamy** [comment]
Seems like it should be an easy fix, provided we can get a minimal repro

**Comment by s-zanella** [comment]
This has become too old to get a proper reproducible example. Closing.
