### ISSUE TITLE
Spurious patterns are incomplete error

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#576]
For some reason F* now has trouble proving the simplified `subst_closed` below does a complete pattern match:
```
type exp =
  | EVar   : exp
  | ELam   : exp -> exp

val appears_free_in : e:exp -> Tot bool
let rec appears_free_in e =
  match e with
  | EVar -> false
  | ELam e1 -> appears_free_in e1

let closed (e : exp) : Tot bool = not (appears_free_in e)

val subst_closed : e:exp -> Lemma (requires (closed e)) (ensures (True))
let rec subst_closed e =
  match e with
  | ELam e1 -> ()
```
```
[hritcu@detained bug-reports]$ fstar.exe bug576.fst
./bug576.fst(20,2-21,17): Patterns are incomplete
Error: 1 errors were reported (see above)
```
Adding a dummy `EVar` case or changing the definition of `not (is_EVar e)` makes this go away. This used to work as is in the past though, any reason it should't still work?

**Comment by s-zanella** [comment]
It seems you simplified the code too much. 
`closed` is extensionally equal to `fun e:exp -> true`, so F* complains rightly that you miss patterns. Can you fix the example to reproduce the error?

**Comment by catalin-hritcu** [comment]
Thanks for spotting this, this was indeed caused by a silly simplification. The real example involves a quantifier without a pattern, so it's not at all clear whether F* is at fault there.
