### ISSUE TITLE
Only functions may be defined recursively

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#58]
Hello,

Following the School 2014, I was trying to define a different version of fibonacci. 
At first this is the module I made:
```
module Fibonacci

(* Write the fibonacci function and several types for it. *)
val fibonacci: (x:int{x>=0}) -> Tot (y:int{y>=0})

let fibonacci x = 
   let rec sub_fibo =  fun n -> fun acc1 -> fun acc2 ->
     if n = x
     then (acc1 + acc2)
     else sub_fibo (n+1) acc2 (acc1 + acc2)
   in
  
  if x <= 1
  then 1
  else sub_fibo 2 1 1
```

But in this case, Fstar returned me an error: `Term has an unexpected non-trivial pre-condition`.

I thought it was because he did not get that the sub function `sub_fibo` will terminate. So I change the line:
```
let rec sub_fibo =  fun n -> fun acc1 -> fun acc2 ->
```
into 
```
let rec sub_fibo: n:int{n >0 /\ n <= x}  -> int -> int -> Tot int (decreases (x-n)) =  fun n -> fun acc1 -> fun acc2 ->
```
The good thing is that I don't have the previous error but I have a new kind of error: `Only functions may be defined recursively`

Could you tell me how to make it work ?

Best regards,
Vincent Cheval

**Comment by nikswamy** [comment]
See `bug-reports/bug058.fst`
