### ISSUE TITLE
Failed to verify implicit argument: Subtyping check failed

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#580]
Update summary: basically F* can't always type-check the types it infers, even if they are correct and everything works well when writing them explicitly.

Some proofs in `LambdaOmega.fst` are failing when switching to universes with `Failed to verify implicit argument: Subtyping check failed` error messages like this:

```
Failed to verify implicit argument: Subtyping check failed; expected type (uu___#3285:LambdaOmega.typ{(Prims.b2t (LambdaOmega.is_TLam uu___@0))}); got type LambdaOmega.typ
```

The error messages seem at first sight to have little to do with the context where they occur. It's also very hard for me to assess what's really happening, in particular whether F\* is now inferring the implicits wrongly or whether it's inferring them correctly, but then for some reason still failing to type check them (it seems that in all cases this is about preconditions of functions applied within the inferred arguments that are reported as failing for no apparent reason). In one case where this problem occurred (`let rec substitution`) I went into the trouble of figuring out the implicits and passing them explicitly and then everything worked fine, but figuring out all the implicits is very painful in general, so I'm still admitting a proof in `LambdaOmega.fst` where this problem is pervasive (`let rec tred_diamond`).

@nikswamy: Any chance to improve this error message so that it shows what F\* inferred for the offending implicit? This would help me greatly in better diagnosing such problems.

@nikswamy: Is there any way I can see what F\* used to infer for implicits in the `--stratified` mode so that I don't need to infer that information myself?

In both cases, I've tried `--dump_module LambdaOmega --print_implicits`, but this doesn't seem to display the implicits in the code it dumps.

**Comment by catalin-hritcu** [comment]
This problem seems to have appeared in `StlcCbvDbParSubst.fst` too, which should explain Nik's commit message for fd55545d ("a couple of more STLC examples ... the main trouble seems to be the more restrictive implicit parameter semantics") and code like this:
```
val preservation : #e:exp -> #t:typ -> h:typing empty e t{is_Some (step e)} ->
      Tot (typing empty (Some.v (step e)) t) (decreases e)
let rec preservation #e #t h =
  let TyApp #g #e1 #e2 #t11 #t12 h1 h2 = h in
     if is_value e1
     then (if is_value e2
           then let TyLam t_x hbody = h1 in
                (extend_gen_0 t_x empty;
                 substitution_preserves_typing 0 h2 hbody)
           else TyApp #_ #_ #(Some.v (step e2)) #_ #_ h1 (preservation h2))
     else TyApp #_ #(Some.v (step e1)) #_ #_ #_ (preservation h1) h2
```
I'm going to give this `#_` a try, wasn't aware of this syntax.

**Comment by nikswamy** [comment]
See point 2 here: https://github.com/FStarLang/FStar/wiki/Migrating-code-to-use-the---universes-mode-(particularly,-as-related-to-mitls-fstar)

**Comment by nikswamy** [comment]
There's a improvement I've discussed with @protz of re-checking a term when implicits fail...perhaps it's time to implement it

**Comment by nikswamy** [comment]
Not sure if it's correct to tag this a bug. It was recorded from the start as a known design constraint in the universes branch. Enhancement, perhaps?

**Comment by catalin-hritcu** [comment]
This is the main blocker for porting the remaining large metatheory examples to universes. The solution we discussed involves a big revamp of the type-checker, splitting it into 2 different passes.

**Comment by aseemr** [comment]
Closing this issue. With two phases, the implicit annotations in `LambdaOmega` are no longer required.
