### ISSUE TITLE
Relax restriction on namespaces syntax

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#587]
It is currently impossible to name a module `module Bug.123` because there is a restriction on the namespace syntax that must apparently start with a capital letter. 
Such naming don't go through parsing. It might be convenient to allow this to be able to name things the following way `module Crypto.AES.256` `module Crypto.AES.128` ...

**Comment by beurdouche** [comment]
A more accurate example would be `module SHA2.256` `module SHA3.512`

**Comment by catalin-hritcu** [comment]
I would say pick your favorite letter of the alphabet and add it before the number, for instance `SHA2.L256` (length) or `SHA2.S256` (size). Or use an underscore instead of a `.`?

Anyway, it seems silly to make syntax less uniform just to allow a couple of particular names where that fits well.

**Comment by nikswamy** [comment]
I agree with Catalin. Unlikely to change this. closing.
