### ISSUE TITLE
List of things to improve w.r.t. parsing

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#596]
Here's a copy/paste from my earlier comments on slack.
## Syntax bugs

The relative precedence of ! and field selection is not right, i.e. it's inconsistent with OCaml's rule.

> [8:47]  
> the parser needs more cleanups
> 
> [8:47]  
> consider
> 
> [8:48]  
> 
> ```
> # type t = { r: int ref };;
> type t = { r : int ref; }
> # let r' = ref { r = ref 0 };;
> val r' : t ref = {contents = {r = {contents = 0}}}
> # !r'.r;;
> - : int ref = {contents = 0}
> ```
> 
> [8:48]  
> F\* does not order the relative precedence of unary operators and field assignment properly
> 
> [8:48]  
> because:
> 
> [8:48]  
> 
> ```
>  type t' = { r: ref int }
> 
> let r' = alloc ({ r = alloc 0 })
> 
> let test5 = !r'.r
> ```
> 
> [8:48]  
> this doesn't type-check

The conflicts on DOT should be resolved. OCaml manages to parse long identifiers (M.x) and field selection (M.x.f) properly; we should be able to do it too.
## Switch to Menhir

From my comments in parse.fsy:

>  (\* This parser should be switched to Menhir for the following reasons:
> - spurious conflict reported by fsyacc (Menhir & Ocamlyacc only report 6
>    conflicts)
> - there's a lot of copy/paste of identical productions for all the operators,
>    that would be solved with a %inline directive
> - a lot of the productions would be simplified by the optional and
>    separated_list parameterized productions... *)

I'd also add that error reporting (François had something going on) might be significantly improved.

Likely, a bunch of engineering. Either:
1) write an F# code backend for Menhir, or
2) re-implement the MenhirLib in F# in the event that the code generated by `menhir --table` falls within the F# and OCaml intersection.

**Comment by msprotz** [comment]
- Problems with Some.v vs FStar.List.append, possible conflict once we add syntax for `expression.ModuleName.field`...

**Comment by kyoDralliam** [comment]
Switch to menhir mostly done, waiting for tahina's fixes on DOT to close

**Comment by tahina-pro** [comment]
No more conflicts on DOT.
When projecting a record, fields can be qualified by their module name, as in OCaml.
