### ISSUE TITLE
"please file a bug report" on an example from the tutorial

### ISSUE THREAD

**Issue by Rotsor** [FStarLang/FStar#598]
The following example from the tutorial fails to compile:

```
module Bad

val new_counter : int -> ST (unit -> ST int)
let new_counter init =
  let c = ST.alloc init in
  fun () -> c := !c + 1; !c
```

The error messages go like this:

```
Bad(2,40-2,43): Expected type "Effect";
got type "(pre:FStar.ST.st_pre -> post:(_:FStar.Heap.heap -> Tot (FStar.ST.st_post Prims.int)) -> Tot Effect)"
Bad(2,28-2,44): Expected type "Effect";
got type "(pre:FStar.ST.st_pre -> post:(_:FStar.Heap.heap -> Tot (FStar.ST.st_post (_:Prims.unit -> ST (Prims.int)))) -> Tot Effect)"
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
The lists had different lengths.
Parameter name: xs2
Error: 2 errors were reported (see above)
```

I don't know whether this is supposed to work (maybe the tutorial is outdated), but the error messages could be better.

**Comment by nikswamy** [comment]
Thanks for the report ... looking into it. 

At the least, the tutorial should have said `int -> St (int -> St int)` as a candidate type for the program---this variant of the state monad expects no pre/post-condition arguments. 

However, even that type is rejected by F* at the moment. Not exactly sure why yet. Will report back once I understand it better.

**Comment by mrakgr** [comment]
```
module Fact

val factorial: n:int{n>=0} -> Tot int
let rec factorial n = 
    if n = 0 then 1 else n * factorial (n - 1)
```

This is another example in the tutorial that does not work. I changed the variable name in the `val` from `x` to `n` so it matches the one in the function, but there is no difference. I get the same error:

```
Fact(4,25-4,26) : Error
Expected expression of type "Type";
got expression "n" of type "(n#6:Prims.int{(Prims.b2t (Prims.op_GreaterThanOrEqual n@0 0))})"
```

**Comment by mrakgr** [comment]
Actually, type checking just this:
`let rec factorial n = if n = 0 then 1 else n * factorial (n - 1)`

Gives me this error:
```
Fact(7,58-7,59) : Error
Expected expression of type "Prims.int";
got expression "n" of type "Type"
```

**Comment by s-zanella** [comment]
A consequence of switching to the new type checker with universes is that the tuple type constructor `*` and  the integer multiplication operator cannot be disambiguated by the kind. 
Try opening `FStar.Mul` or defining `let op_Star = op_Multiply`.

**Comment by nikswamy** [comment]
Ugh. Sorry about that. FYI, updating the tutorial is very much on our TODO list. 
https://github.com/FStarLang/FStar/issues/565
Thanks for your patience.

**Comment by erdeszt** [comment]
Two more case where the example code from the tutorial doesn't compile.
This one is from http://rise4fun.com/fstar/tutorial
```fsharp
module Welcome

    type ilist : int => S => S = 
        | INil  : ilist 0 'a
        | ICons : x:'a -> n:int -> ilist n 'a -> ilist (n + 1) 'a
```
The error is:
```
Welcome(2,22-2,24) : Error
Syntax error
```
The second one is from https://fstar-lang.org/tutorial/
```fsharp
module Welcome

    type vector : Type -> nat -> Type =
        | Nil :  vector 'a 0
        | Cons : hd:'a -> n:nat -> tl:vector 'a n -> vector 'a (n + 1)
```
The error i get is:
```
Welcome(3,24-3,26): Failed to prove that the type '(Welcome.vector uu___ uu___)' supports decidable equality because of this argument; add the 'noeq' qualifier
Error: 1 errors were reported (see above)
```

**Comment by aseemr** [comment]
Hello, the tutorial on rise4fun is deprecated. And for the second issue, this type does not have decidable equality, and so F* gives the error. If you prefix the type definition with `noeq`, i.e. `noeq type vector ...`, it should work then. We need to update the tutorial with `noeq`, but you can read more about it here: https://github.com/FStarLang/FStar/wiki/Deriving-hasEq-predicate-for-inductive-types,-and-types-of-equalities-in-F*.

**Comment by erdeszt** [comment]
Thanks for the quick help, `noeq` worked.

**Comment by nikswamy** [comment]
Alternatively, you might define 

```
    type vector (a:Type) :nat -> Type =
        | Nil :  vector a 0
        | Cons : hd:a -> n:nat -> tl:vector a n -> vector a (n + 1)
```

using `a` as a parameter rather than an index. 

In this style, you will actually also have decidable equality for `vector t n` so long as you have decidable equality for `t`.

It's usually preferable to use a parameter rather than an index, wherever possible. We should update the tutorial to not use the index for `a`

**Comment by erdeszt** [comment]
Thank you @nikswamy, this form does look nicer. Is there any way I can help with updating the tutorial(given my _very_ limited F* knowledge)? I couldn't find a contribution guide.

**Comment by nikswamy** [comment]
You should be able to submit a pull request with updates to 
https://github.com/FStarLang/FStar/blob/master/doc/tutorial/tutorial.mdk

The tutorial is formatted using  http://madoko.net/

**Comment by nikswamy** [comment]
The old tutorial is defunct and we've moved to a new one.
