### ISSUE TITLE
UntrustedClientCode Module: No error when I call functions with un-secure file name 

### ISSUE THREAD

**Issue by Tizpaz** [FStarLang/FStar#599]
Hi All,
I write following F* Module: 

module FileName
  type filename = string

module ACLs
  open FileName

  (* canWrite is a function specifying whether or not a file f can be written *)
  let canWrite (f:filename) = 
    match f with 
      | "demo/tempfile" -> true
      | _ -> false

  (* canRead is also a function ... *)
  let canRead (f:filename) = 
    canWrite f               (* writeable files are also readable *)
    || f="demo/README"       (* and so is this file *)
    
module FileIO
  open ACLs
  open FileName
  assume val read  : f:filename{canRead f}  -> string
  assume val write : f:filename{canWrite f} -> string -> unit

module UntrustedClientCode
  open FileIO
  open FileName
  let passwd  = "demo/password"
  let readme  = "demo/README"
  let tmp     = "demo/tempfile"

  let staticChecking () =
    let v1 = read tmp in
    let v2 = read readme in
    let v3 = read passwd in 
    write tmp "hello!";
    write passwd "junk"

I use online editor. I should see the error we I call **read passwd** and **write passwd "junk"**. But, none of them give me any error in type-checking. Could anyone help me regarding this problem?

Thanks

**Comment by Rotsor** [comment]
I got confused by this as well.

Looks like adding a type signature solves the problem, which I propose here:
https://github.com/FStarLang/FStar/pull/597

Be prepared for more problems with online editor and tutorial. For example, I found the factorial example to not work (apparently (*) doesn't mean multiplication??).

**Comment by s-zanella** [comment]
The default type and effect inferred for `staticChecking` changed since this example was written. See #581 for an ongoing discussion of this issue. 

A fix for this example (thanks @Rotsor) is now checked in, but other parts of the tutorial need to be updated.
