### ISSUE TITLE
Type checking question

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#60]
Hello,

I would like to know the important of the structure `let x = blabla in` when you do the type checking. For instance, it seems there are some difference in term of type check between 
```
let a:good_symbol = { name = "enc" ; arity = 2; cat = Constructor [n;n] n }
```
and 
```
let a:good_symbol = 
  let x = { name = "enc" ; arity = 2; cat = Constructor [n;n] n } in
  x
```
My type `good_symbol` is a refinement of an other type symbol that just check that the size of the arity is the same as the size of the list in the Constructor. But with the first line of code, it does not type check. I have the error `Expected type "good_symbol"; got type "symbol"`. However, with the second way, Fstar succeeds to type check. So I was wondering how important is the 'let' for type checking. Wouldn't it possible that he manages to type check even without it so that the first line of code (the most natural one in my opinion) works ?

The full code is below.

Best regards,
Vincent Cheval

```
(************************
***       Types       ***
*************************)

module Term

type symbol_cat = 
  | Tuple : symbol_cat
  | Constructor : list term -> term -> symbol_cat
  | Destructor : list term -> term -> symbol_cat

and symbol = 
  {
    name : string;
    arity : nat;
    cat : symbol_cat 
  }
  
and term = 
  | Func : (symbol * list term) -> term 
  | Name : string -> term
  
(******* List ******)

val length: list 'a -> Tot nat
let rec length l = match l with
  | [] -> 0
  | _::q -> 1 + (length q)
 
(*********************************
***        Predicates          ***
**********************************) 

(** Arity and arguments **)

type good_symbol = s:symbol{ match s.cat with 
  | Tuple  -> true
  | Constructor list_arg _ -> length list_arg = s.arity
  | Destructor list_arg _ -> length list_arg = s.arity
  }
  
let n:term = Name "n"

(* Does type check *)
let a:good_symbol = 
  let x = { name = "enc" ; arity = 2; cat = Constructor [n;n] n } in
  x

(** Does not type check
let a:good_symbol = { name = "enc" ; arity = 2; cat = Constructor [n;n] n }
*)
```

**Comment by nikswamy** [comment]
FYI, type inference is no longer bidirectional. So, both my pair examples work well now ... I've added this to our regression suite.
