### ISSUE TITLE
Not resolving with implicit values 

### ISSUE THREAD

**Issue by KitFreddura** [FStarLang/FStar#600]
Using an example exactly from examples/vectors.fst, the following code does not type check.
```
type vector 'a: nat -> Type = 
  | VNil -> vector 'a 0
  | VCons -> hd:'a -> #n:nat -> tl:vector a n -> vector a (n+1)

val append: #a:Type -> #n:nat -> #m:nat -> v1:vector a n -> v2:vector a m -> Tot (vector a (n+m))
let rec append #a #n #m v1 v2 = match v1 with
  | VNil -> v2
  | VCons hd tl -> VCons hd (append tl v2)
```

This errors with the following message when using --print_implicits
```
Error
Expected a term of type "(vector a (n + m))";
got a function "(fun #a:<UNKNOWN> #n:<UNKNOWN> #m:<UNKNOWN> v1:<UNKNOWN> v2:<UNKNOWN> -> (match v1 with (VNil )  -> v2
        (VCons hd tl)  -> (VCons hd (append tl v2))))" (More arguments than annotated type (Typ_app(Typ_const Higher.vector, [2 args])))
```

Anyone encounter this kind of error? Thanks

**Comment by nikswamy** [comment]
I had to edit your example a little to make it parse. This version below verified for me without any problems.

I'm closing this issue. Please feel free to re-open if you find implicit argument inference working incorrectly/unexpectedly.

```
module Test

type vector (a:Type) : nat -> Type = 
  | VNil : vector a 0
  | VCons : hd:a -> #n:nat -> tl:vector a n -> vector a (n+1)

val append: #a:Type -> #n:nat -> #m:nat -> v1:vector a n -> v2:vector a m -> Tot (vector a (n+m))
let rec append #a #n #m v1 v2 = match v1 with
  | VNil -> v2
  | VCons hd tl -> VCons hd (append tl v2)
```

**Comment by KitFreddura** [comment]
Trying to verify the same code (I copy and pasted it), I am still getting an error?
'''
 Error
Expected a term of type "(vector a (n + m))";
got a function "(fun v1 v2 -> (match v1 with (VNil )  -> v2
        (VCons hd tl)  -> (VCons hd (append tl v2))))" (More arguments than annotated type (Typ_app(Typ_const Test.vector, [2 args])))
```
I've installed F* via opam on ubuntu, it works fine with other things, I've tried reinstalling it, and the same error continues to occur.

**Comment by nikswamy** [comment]
F* moves very quickly, for better or worse. As far as I know, the version on opam is probably a couple of thousand commits behind master, @protz? If you're looking to work with an F* installation on your local machine, then I would strongly suggest trying to build from the master branch. It should be relatively painless if you already have ocaml and opam on Ubuntu, cf. INSTALL.md

**Comment by msprotz** [comment]
I can try to refresh the OPAM package... shouldn't be too hard... it's just that it'll point to a non-official releas

**Comment by catalin-hritcu** [comment]
@msprotz Can we do the same as for the Hombrew formula (https://github.com/FStarLang/FStar/blob/master/INSTALL.md#homebrew-formula-for-mac-os-x) and have both a way to install the latest release and another to install the master branch via OPAM.

**Comment by msprotz** [comment]
The OPAM people are not going to be super happy with their CI is we make a package point to fstar-master, as it may break from time to time... or we commit to not breaking this package, but then this is more CI work for us. I'm already pretty busy, so I'm kind of reluctant to take the responsibility of not breaking the OPAM package.
