### ISSUE TITLE
Exercise 4b's answer is not thorough enough

### ISSUE THREAD

**Issue by mrakgr** [FStarLang/FStar#602]
[The answer](https://www.fstar-lang.org/tutorial/tutorial.html#sec-basic-lists) on the page:
```
val append_len: l1:list 'a -> l2:list 'a 
         -> Lemma (requires True)
                  (ensures (length (append l1 l2) = length l1 + length l2))
let rec append_len l1 l2 =
    match l1 with
    | x::xs -> append_len xs l2
    | [] -> ()
```
My answer:
```
val append_len: l1:list 'a -> l2:list 'a 
         -> Lemma (requires True)
                  (ensures (length (append l1 l2) = length l1 + length l2))
let rec append_len l1 l2 =
    match l1 with
    | x::xs -> append_len xs l2
    | [] ->
        match l2 with
        | x::xs -> append_len l1 xs
        | [] -> ()
```
The extent of my knowledge of math proofs is the Maththink Coursera course that I've taken last year, but it does not seem to me that answer for exercise 4b is thorough enough even though it discharges successfully.

**Comment by s-zanella** [comment]
I'm not sure I understand your concern. 
Is it that you think that the proof in the tutorial shouldn't go through without applying the inductive hypothesis in case `l1` is `[]`?

In the tutorial `append` is defined by induction on `l1`:
```F#
let rec append l1 l2 = match l1 with
  | [] -> l2
  | hd :: tl -> hd :: append tl l2
```
If `l1` is `[]`, then from the definitions of `append` and `length`,

1. `length (append l1 l2)` = `length (append [] l2)` = `length l2` 
2. `length l1 + length l2` = `length [] + length l2` = `0 + length l2` = `length l2`

Thus, both sides of the equation in the conclusion of the lemma are equal, and we're done. In particular, it's not necessary to apply the inductive hypothesis (i.e. call `append_len l1 xs`).

**Comment by mrakgr** [comment]
Ah, I see. That clarifies things for me. I guess the answer is thorough after all.
