### ISSUE TITLE
Function type in records

### ISSUE THREAD

**Issue by GKerfImf** [FStarLang/FStar#608]
Why I can't use function type in records?

```fs
type my_type = {
    x: int; 
    f: int -> int
}
```
```
Z3 provided a counterexample, but, unfortunately, F* could not translate it back to something meaningful
Error: 1 errors were reported (see above)
```

**Comment by aseemr** [comment]
Hello: F* tries to generate an equality axiom for `my_type`, and fails, since equality on functions is not decidable. If you prefix it with `noeq`:

```
noeq my_type
```

It should work then. Sorry for the error message, it could be more helpful.

**Comment by GKerfImf** [comment]
Thanks!

**Comment by nikswamy** [comment]
the error message has now been fixed. It now says:

```
.\test.fst(4,7-4,17): Failed to prove that the type 'Test.my_type' supports decidable equality because of this argument; add the 'noeq' qualifier
Error: 1 errors were reported (see above)
```
The location points to the `int -> int` type of the field `f`.
