### ISSUE TITLE
SMT encoding: equalities between partially applied functions apparently not used

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#613]
Today I was working with @markulf on porting the mac example to universes, and one thing I noticed in the debug process that follows is that F* can't reason properly about equalities between partially applied functions. That seems crucial though for the way the mac example is currently set up: the assumption `key_prop k == reqresp` has to allow us to move from `reqresp m` to `key_prop k m`, but F* can't prove these two things equal (actually on stratified either, so I bet there's some shady stuff happening there, but I'm not sure whether it's worth finding out).

Anyway, here's a self-contained instance of this problem:
```
module Bug613

assume val f : int -> int -> Tot int
assume val g : int -> int -> Tot int

val l : unit -> Lemma (requires (f == g))
                      (ensures (f 0 1 == g 0 1))
let l () = () (* this works *)

val l' : unit -> Lemma (requires (f 0 == g 0))
                       (ensures (f 0 1 == g 0 1))
let l' () = () (* this fails *)

(* closer to mac.fst *)
assume val h : int -> Tot int
val l'' : unit -> Lemma (requires (f 0 == h))
                       (ensures (f 0 1 == h 1))
let l'' () = () (* this fails too *)
```

**Comment by nikswamy** [comment]
The solution that was originally applied in 2016 is rather heavy handed.

Essentially, in 6133106 we added an axiom that allows rewriting in both directions
  `f x1...xn = ApplyTT (ApplyTT ftok x1) ... xn)`
This means that every full application is immediately converted into curried form and SMT then tried to reason about each partial application etc. all rather needlessly in most cases. I noticed these redundant instantiations popping up in some Z3 profiles recently.

In dcd5327, I tried a slightly different approach.

1. SMT can always rewrite `ApplyTT (ApplyTT ftok x1) ... xn)` to the full application `f x1...xn`

2. The axiom to rewrite in the other direction is guarded by a pattern that checks whether any partial application of `f` (i.e., whether `ftok`) is in the current context. If it is not, then rewriting `f x1..xn` to `ApplyTT ftok ... xn` is not permissible.
