### ISSUE TITLE
Effect abbreviation fails with "polymorphic in 2 universes" with --lax flag

### ISSUE THREAD

**Issue by danelahman** [FStarLang/FStar#615]
The example at [examples/preorders/IST.fst](https://github.com/FStarLang/FStar/blob/07310164b8523b3c85a036192e4a499d1cde0461/examples/preorders/IST.fst) fails to typecheck with the --lax flag turned on, but typechecks with it turned off.

When running

`fstar --lax IST.fst`

I get 

`Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Unexpected effect abbreviation IST.IST; polymorphic in 2 universes")`

When running 

`fstar IST.fst`

the file typechecks fine.

The problematic line is [examples/preorders/IST.fst#L31](https://github.com/FStarLang/FStar/blob/07310164b8523b3c85a036192e4a499d1cde0461/examples/preorders/IST.fst#L31). The lax typechecker is happy when we fix the universe of the argument to ISTATE called state:

`new_effect  ISTATE (state:Type0) (rel:relation state{preorder rel}) = STATE_h state`

**Comment by aseemr** [comment]
The example doesn't parse for me anymore. In addition, (a) `--lax` is an internal flag that users should not really use (may be we should work on deprecating it), (b) effects have undergone several enhancements in the last couple of years. Since it is an old issue, I am marking it closed.
