### ISSUE TITLE
Use HACL in crypto examples

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#617]
It would be nice to use HACL instead of CoreCrypto in `examples/crypto` to remove dependency on OpenSSL.

**Comment by beurdouche** [comment]
Can we list which primitives we need from HaCl ?

**Comment by markulf** [comment]
SHA1 and HMAC would be the first. I just talked with @jkzinzindohoue and one issue is that `HST` might rely on `HyperHeap` while many of the examples and tutorials use a plane heap.

**Comment by jkzinzindohoue** [comment]
Maybe. The plan for the core of Hacl is to be ready soon enough with some proofs at least, so the timing should be about right.
But in terms of code-size and complexity however I wonder. In particular it implies some understanding of the low-level libraries, which may be out of scope for what you want to do. I do not think they could replace as-is the current CoreCrypto interfaces.
What do you think ?

**Comment by ad-l** [comment]
I think it is possible to abstract many of the low-level details by wrapping Hacl in a high-level interface that deals with the memory management. Generally speaking I think everyone would prefer not to depend on OpenSSL.

**Comment by markulf** [comment]
I agree. Not having to rely on OpenSSL would be nice.

**Comment by markulf** [comment]
Should we reassign a different milestone for this?

**Comment by nikswamy** [comment]
This would be nice, but such example may belong in a separate repo rather than the F* repo depending on HACL.
