### ISSUE TITLE
Clean up `doc/tutorial/code` and improve CI

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#618]
- [x] The `day2` folder does not seem to be used. Delete.
- [x] Add RPC example to the tutorial. 
- [x] Clean up ACLs example
- [x] Is code in the tutorial part of any continuous integration? Add it.
- [x] Split files with multiple modules
- [x] Rename files whose filename does not match its module name
- [x] Create `exercises_universes`, and add it to CI
- [x] Switch tutorial's `fstar` to universes
- [x] Finally move `*_universes` to `*`

**Comment by markulf** [comment]
The Makefile in `doc/tutorial/code/solutions` is part of what is build on `make -C examples`

**Comment by markulf** [comment]
We are using different version of ACLs, can we use the same for all examples?

**Comment by sishtiaq** [comment]
@markulf Where did you add `doc/tutorial/code/exercises' to CI? In which script or Makefile?
