### ISSUE TITLE
Polymorphism problem?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#62]
Francois Pottier was having a problem when adding a type definition in STLC. Unfortunately, I don't know the precise details for reproducing this. We had such problems in the past, but they seemed fixed.

**Comment by nikswamy** [comment]
This is a bug in desugaring. I'm fixing it now. FYI, if you had written it like this, it would also have checked. 
```
val empty: a:Type -> Tot (env a)
let empty _ = None
```
