### ISSUE TITLE
Check that all {exercises,solutions} work in universes mode.

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#620]

**Comment by markulf** [comment]
How do we turn on universe mode in the tutorial. Should we do this globally, or selectively for a subset of the tutorial examples?

**Comment by beurdouche** [comment]
I think we could simply doing progressively from the beginning. 
Maybe we can simply have a big red line saying: "WIP : From that point the tutorial hasn't been updated to the Universes syntax and is likely to change..." ?
