### ISSUE TITLE
How to say path-to-fstar in .emacs

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#622]
Especially if you're on Windows/Cygwin, and your FStar bin is in E:\FStar\bin.

**Comment by beurdouche** [comment]
`(setq-default fstar-executable "/opt/fstar/bin/fstar.exe")` is that what you are looking for ?

**Comment by sishtiaq** [comment]
I had that but it didn't work with my (non-cygwin) Emacs. 
I've now got cygwin's emacs-w32, and 
```
(setq-default fstar-executable "/cygdrive/e/FStar/bin/fstar.exe")
```
seems to work. ```E:/FStar/bin``` doesn't.

**Comment by msprotz** [comment]
You have to know whether you're using a native emacs or a cygwin emacs... people have been known to use both.

@sishtiaq one way to make usability better is, if `cygpath` is in scope, to run the arguments passed to `fstar` through `cygpath -m`
