### ISSUE TITLE
Enable multi-file exercises in online editor

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#624]
This should be relatively easy technically. The challenge may be in the presentation to the user.

**Comment by catalin-hritcu** [comment]
You mean splitting an exercise over multiple files or something else?

**Comment by markulf** [comment]
Yes, probably we would only make one of the files editable, and only present the other files to the user.

**Comment by markulf** [comment]
We should also consider the web security aspects of it.

**Comment by markulf** [comment]
@catalin-hritcu We might want to move this issue off this milestone.

**Comment by sishtiaq** [comment]
I vote for moving this issue out of this milestone.

**Comment by markulf** [comment]
Moving it out.

**Comment by markulf** [comment]
@ad-l I would need an additional feature. It would be nice if users could edit files further down in the dependency graph, but the FStar type checking would happen on the whole of some development, e.g. in Encrypt-then-MAC, I would like to change idealization and show the sequence of games, by changing idealization flags.

**Comment by catalin-hritcu** [comment]
One thing the online editor does support currently is multiple modules per edit buffer. Via some hacks these modules are split into separate files. Not sure this is the right way of doing it, but wanted to mention its existance.

**Comment by nikswamy** [comment]
I made a choice in the new tutorial to specifically have all examples and exercises use single files only (with dependences in ulib)
