### ISSUE TITLE
Bring back explicit names for tutorial code files, remove numbers

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#629]
... and also use sub-folders for each chapter, so that we can keep maintaining this (e.g. add and remove chapters or exercises). For each exercise in the tutorial HTML we could list the file name (change import macro to display it).

Nit: could make the file name shorter by getting rid of the `code` folder and moving things 1 level up.

New idea: How about splitting the tutorial into chapters too, then could potentially put the exercises in the folder of the chapter?

**Comment by markulf** [comment]
I did the opposite. There are explicit names in 'multi-file' tutorials. Does it work?

**Comment by markulf** [comment]
@catalin-hritcu should we close this issue?

**Comment by sishtiaq** [comment]
@markulf Close this issue, or move it off this milestone. Things are working "good enough" for now.

**Comment by catalin-hritcu** [comment]
Things are only good enough as long as nobody adds or removes anything to the tutorial. Counters in file names are a maintenance nightmare. Reopening.

**Comment by nikswamy** [comment]
Old tutorial is defunct. This issue is obsolete.
