### ISSUE TITLE
mv doc/notes.txt to Issues

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#631]
doc/notes.txt seems to contain a list of bugs. Move these to github Issues, if they are still bugs. 
Then delete the file.

**Comment by catalin-hritcu** [comment]
That file was last edited in Oct 15, 2014, so I would be surprised if there is still anything useful in there, but @nikswamy should confirm.

**Comment by markulf** [comment]
@nikswamy to be deleted?

**Comment by nikswamy** [comment]
Yep
