### ISSUE TITLE
Will F* ever support Objects or Structs? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#632]

**Comment by nikswamy** [comment]
These are two quite different beasts. 

For objects: you can encode many kinds of them using existential types, which F* already provides.

For structs: cf. github.com/FStarLang/Kremlin We do plan to compile things to C structs. @protz can say more, if necessary.

**Comment by msprotz** [comment]
We already have records so you'd have to tell us what exactly you'd want in addition to that.

Object-style encodings are already possible using records and subtyping, as Nik mentions. Hoping that they will compile to C as well eventually.

**Comment by catalin-hritcu** [comment]
F* already has records, and KreMLin now supports structs. Closing.
