### ISSUE TITLE
Extend support for hints to F#-compiled version of F*

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#633]

**Comment by nikswamy** [comment]
no particularly deep reason. hints are a very new feature. it should be supported in F\# soon. @sishtiaq

**Comment by nikswamy** [comment]
We need to add JSON parsing for hint databases. See the end of src/basic/util.fs

**Comment by sishtiaq** [comment]
The OCaml implementation is in src/basic/ml/FStar_Util.ml.

**Comment by catalin-hritcu** [comment]
Just for the record, the error here is
```
[record_hints_json]: not implemented
```

**Comment by catalin-hritcu** [comment]
Fixed by @wintersteiger in #840
