### ISSUE TITLE
Implement fsdoc

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#634]
https://github.com/FStarLang/FStar/wiki/Generating-documentation-with-fsdoc-comments

Work items:
- [X]  write out an index.mk. Done with 9f0cfb7def1e112331a40c4fc1c775039fe4ffcc.
- [X] Comments: on empty line
- [X] Comments: top-level declarations: type
- [X] Comments: top-level declarations: val
- [X] Comments: top-level declarations: let
- [x] Comments: top-level declarations: module decl
- [X] Comments: finer than top-level declarations: {fields, algerbraic type variants, mutually rec decls} 
- [ ] Implement keywords: inline,
- [ ] Implement keywords: omit
- [ ] Implement keywords:  summary
- [ ] x-ref

**Comment by markulf** [comment]
Could we add an example .md to the wiki? If it looks nice more people might pick it up.

**Comment by msprotz** [comment]
Just chatted with @vkanne-msft and the plan is to generate documentation nightly and put it up on fstarlang.github.io/doc ... will motive people more I think!

**Comment by markulf** [comment]
+1

**Comment by sishtiaq** [comment]
Commit 33e14b941db6b97d1116eae1a7ae21807787683b implements 
- [X]  write out an index.md. 
- [X] Comments: on empty line
- [X] Comments: top-level declarations: type
- [X] Comments: top-level declarations: val
- [X] Comments: top-level declarations: let
- [x] Comments: top-level declarations: module decl
- [X] Comments: finer than top-level declarations: {fields, algerbraic type variants, mutually rec decls}.

**Comment by msprotz** [comment]
Additional feature requests:
- [ ] run `pandoc --standalone --css=style.css`

Thanks,

Jonathan

**Comment by sishtiaq** [comment]
Fixed -s and --css in 81aa0d28532e98db8b0e4199665ddf1865505426.

**Comment by sishtiaq** [comment]
I intend to close this issue soon, and replace it with a new one to track the last four items of work:
- [] Implement keywords: inline,
- [] Implement keywords: omit
- [] Implement keywords: summary
- [] x-ref

The first three will be quick; the last might take longer (especially if we don;'t want to build yet another dependency analyzer inside the F* compiler).

**Comment by markulf** [comment]
We need some push to convert normal comments to `fsdoc` comments. Currently 
https://fstarlang.github.io/docs/ is quite sad, with only `FStar.List` being properly documented.

**Comment by aseemr** [comment]
Since fsdoc is removed in favor of fstardoc (#1939 ), closing this issue.
