### ISSUE TITLE
Tutorial is verifying anything!

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#641]
```

module Welcome

let a = assert (1 = 2)
```

outputs 
```

Verifying module: Welcome
All verification conditions discharged successfully
```

**Comment by markulf** [comment]
We just recently deployed a new version of the tutorial to make use of new features of F*. 

Thanks for the feedback! Great reminder to do more testing despite verification. I suspect its not even passing the right file to F*, as I can even verify syntax errors. We are looking into it.

**Comment by ad-l** [comment]
Sorry for that, it was caused by the recent update to the tutorial
