### ISSUE TITLE
Add working Encrypt-then-MAC example to tutorial

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#643]
We had for some time sketches of Encrypt-then-MAC (EtM) in [`examples/crypto`](https://github.com/FStarLang/FStar/tree/master/examples/crypto). 

Its a simple example for composing an integrity `MAC` and a confidentiality primitive `CPA` secure encryption.

Some of our experiments were quite ambitious, using higher order, [Encrypt_EtM](https://github.com/FStarLang/FStar/blob/master/examples/crypto/Encrypt_EtM.fst), further experiments not moved to `universes` are `examples/crypto/encrypt2` and `encrypt3`.

Out latest attempt is a simplified version of this development using a style and technology adapted from `miTLS`: [EtM.AE.fst](https://github.com/FStarLang/FStar/blob/master/examples/crypto/EtM.AE.fst). It uses `HyperHeap` and monotonic sequences. We could have used a view mechanism but opted for proving invariants over logs first. This would be a good place to experiment with and compare both styles.

**Comment by markulf** [comment]
See also https://github.com/FStarLang/FStar/issues/611

**Comment by dckc** [comment]
I look forward to such examples -- preferably with plenty of comments.

I'm struggling to find the equivalent in the new F* of this succinct explanation of the `cpa` type:

> Recall that non-interference means that public results do not
> depend on secrets. If an expression `e` with base type `a` that computes
> over some secret information can be given the type
> 
> ```
> type eq a = x:a{|L x = R x|}
> ```
> then its result can be safely published, since the execution of `e`
> reveals no information about the secrets.
> ...
> In cryptography, confidentiality is usually stated
> as resistance against chosen-plaintext attacks (CPA) ... Instead of reasoning about
> two messages selected by `b`, we just need to show that the function
> `let cpa’ p = encrypt (sample n) p` has the type `block → eq block` .

 - [Probabilistic relational verification types](http://research.microsoft.com/en-us/um/people/fournet/papers/probabilistic-relational-verification-for-cryptographic-implementations-draft.pdf)

**Comment by nikswamy** [comment]
I will add examples of mac then encrypt etc. soon. We're preparing a new paper for the new style of relational verification supported by F* probably for the end of October. @ngrimm

**Comment by markulf** [comment]
For encrypt-then-mac a simpler modeling of plaintext secrecy using parametricity should suffice. `encrypt (k:key) (p:plain)` is secure, if it is parametric in the plaintext type, i.e. the ciphertext does not depend on the plaintext. 

@dckc as with your example this models perfect secrecy. While using relational reasoning one can capture things like one-time-pad, the parametric style primarily uses idealization where the ciphertext is replaced by the encryption of a constant.

**Comment by markulf** [comment]
I made some progress, please have a look in the tutorial.

**Comment by s-zanella** [comment]
Closing this in favour of #656.

@dckc: See https://arxiv.org/abs/1703.00055 and the examples in `examples/rel`.
