### ISSUE TITLE
Remove examples that are no longer useful

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#645]
Some examples are quite outdated and would need to be updated (https://github.com/FStarLang/FStar/issues/565), deleting may sometimes be a better option.

Candidates:

We often have several variants of examples and should converge on one, unless there is a clear reason to keep on experimenting:
- [ ] [`encrypt2.fst`](https://github.com/FStarLang/FStar/blob/master/examples/crypto/encrypt2.fst) and `encrypt3.fst`.

We might not want to maintain examples from the tutorial also in `examples`. In some cases there may be a rational like didactic simplifications in `tutorial/code` or experiments in `examples`, but not always:
- [ ] [`Padding.MAC2`](https://github.com/FStarLang/FStar/blob/master/examples/crypto/Padding.MAC2.fst) and its siblings. They are still in `stratified` while its counterparts in `tutorial` have been ported to `universes`. These files are of a tutorial nature and its not clear we want to extend or build on them.
- [ ] [`CCA.CCA1`](https://github.com/FStarLang/FStar/blob/master/examples/crypto/CCA2.CCA2.fst) and `hybrid.fst`, `hybrid2.fst`, `pke.fst` contain similar developments.

**Comment by markulf** [comment]
Adding samin for his ruthless qualities. :)

**Comment by markulf** [comment]
@fournet wrote the `encrypt.fst` examples originally. Removing the issue from the crypto tutorial milestone.

**Comment by wintersteiger** [comment]
@markulf @sishtiaq Have the examples been updated and can we close this issue?
