### ISSUE TITLE
Do we want a Docker image for doing the tutorial outside of web interface?

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#646]
#Maybe a general F* image would suffice? (see https://github.com/FStarLang/FStar/issues/584 and https://github.com/FStarLang/FStar/pull/592)

**Comment by beurdouche** [comment]
The current F* docker file packages all the F* repository. I am not sure what you would gain in having a separate image, in particular if you don't want a web interface.

**Comment by sishtiaq** [comment]
I agree with @beurdouche, and vote for closing this issue. 
I was thinking we could add some text to the tutorial to say how to follow the tutorial using docker. But the whole point of the madoko tutorial is to let you work in your browser.

**Comment by markulf** [comment]
making it easy through the tutorial to make the next step from doing it in your browser to doing it in emacs would be valuable, it might be just a question of linking a wikipage.

**Comment by sishtiaq** [comment]
The online tutorial is very interactive. That's the really nice thing about it! 
How do you plan to replicate the whole "load exercise", "peek at solution", etc experience in docker or emacs+docker? I think we should de-prioritize this issue for the CryptoTutorial release; mv it to another milestone.

**Comment by beurdouche** [comment]
Ok, when offline, having the webpage, exercice files and a local instance of F* seems fine to me.
We maybe can do something cleaver, but I agree with Samin, probably not for this milestone ?!

**Comment by markulf** [comment]
We have something now anyway: https://github.com/FStarLang/FStar/wiki/Running-F%2A-from-a-docker-image

**Comment by markulf** [comment]
Interactive mode on the web interface would be amazing. So large files are more easy to work with in emacs.

**Comment by vkanne-msft** [comment]
Thanks for the instructions. this is good.

**Comment by markulf** [comment]
I think they need to be cleaned up, maybe once we actually understand what all the docker options are for. One thing that isn't obvious for me yet is how to persist state across calls to `docker run`.

**Comment by vkanne-msft** [comment]
persistence across docker images can be done by mounting host volumes. See this page for an example. https://github.com/mitls/mitls-fstar/wiki/Setting-up-a-Docker-based-Development-environment#run-docker-image

**Comment by markulf** [comment]
another option is to just exit from the VM and use `docker ps -a` to learn the stopped container ID, and use `docker start -i <container ID>` to start it again.

**Comment by markulf** [comment]
Closing this issue, https://github.com/FStarLang/FStar/wiki/Running-F%2A-from-a-docker-image documents how to get F* running on docker.
