### ISSUE TITLE
Update capabilities based access control example

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#647]
https://github.com/FStarLang/FStar/blob/master/doc/tutorial/code/solutions/Ex12a.Cap.fst
- [ ] Add a main function demonstrating that it actually works. 
- [x] Decide what to do with version in `examples`.

**Comment by markulf** [comment]
version in examples got deleted

**Comment by wintersteiger** [comment]
@markulf: does your comment mean that this example will not be completed and can we close this issue?
