### ISSUE TITLE
Invalid identifer 'EqTyp'; expected a symbol that begins with a lower-case character

### ISSUE THREAD

**Issue by talex5** [FStarLang/FStar#648]
The on-line tutorial was giving me confusing errors, like:

    /var/fstar/ulib/prims.fst(211,42-211,45) : Error Expected expression of type "Type"; got expression "Prims.int" of type "Type"

so I tried installing locally instead. That gives:

```
$ make PREFIX=/tmp/fstar -C src/ocaml-output install
$ cat test.fst
module Welcome
let x = 1
$ /tmp/fstar/bin/fstar.exe test.fst 
/tmp/fstar/bin/../lib/fstar/prims.fst(21,18-21,23) : Error
Invalid identifer 'EqTyp'; expected a symbol that begins with a lower-case character
```

Are these the correct installation instructions?

**Comment by sishtiaq** [comment]
eqtype. Ex04d, for instance.

**Comment by s-zanella** [comment]
The `install` target in `src/ocaml-output` was outdated. It should have copied the `ulib` and `ucontrib` directories rather than`lib` and `contrib`.
Please try now, it should be fixed now in master.

**Comment by talex5** [comment]
Works now - thanks!
