### ISSUE TITLE
How does one type a function that may return different types? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#649]
I can create the following refinement types; 

```
type odd = x:int{x%2 = 1}
type even = x:int{x%2 = 0}
```

How would I write a function that takes an integer and returns it's refinement? 

something like 

```
let parity x = 
    | Odd x when x%2 = 1
    | Even x when x%2 = 0
```

How would I write the function? And what would the Val declaration look like?

**Comment by s-zanella** [comment]
I don't know if this is what you had in mind:

```F#
type odd = x:int{x%2 = 1}
type even = x:int{x%2 = 0}

type parity_t =
  | Odd of odd
  | Even of even

let value = function
  | Odd x 
  | Even x -> x

// parity returns a parity_t element with value x 
val parity: x:int -> y:parity_t{ value y == x }
let parity x = 
  if x%2 = 1 then Odd x else Even x
```

**Comment by sishtiaq** [comment]
Dependent types. Make type T_{i+1} depend upon a previous T_i type. See @s-zanella answer above.

**Comment by A-Manning** [comment]
@ s_zanella in 
```
let value = function
  | Odd x 
  | Even x -> x
```

Why is Even a function but Odd is not?

**Comment by sishtiaq** [comment]
It's ML short hand syntax for:
let value = function
  | Odd x -> x
  | Even x -> x

parity_t is one word, read it as "type of parity".

**Comment by msprotz** [comment]
and `let value = function` is syntactic sugar for `let value x = match x with`... feel free to reopen if other questions pop up.

**Comment by nikswamy** [comment]
To really return different types in each branch, you can go really dependent:

```
module Test
type odd = x:int{x%2 = 1}
type even = x:int{x%2 = 0}

type odd_or_even_or_bool =
  | Odd of odd
  | Even of even
  | Bool of bool

let project_t (x:odd_or_even_or_bool) : Type = 
  match x with 
  | Odd _ -> odd
  | Even _ -> even
  | Bool _ -> bool
  
val project : x:odd_or_even_or_bool -> Tot (project_t x)
let project = function
  | Odd x 
  | Even x -> x
  | Bool b -> b
```

**Comment by nikswamy** [comment]
The general style here is to describe the type of a function `f` that may return different types based on its argument `x` by another function `f_t` which computes the type of `f x` as `f_t x`.
