### ISSUE TITLE
Polarities: subtyping for datatypes

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#65]
`(x:int{x>1} * y:int{y>1})` is not a subtype of `(int * int)`

**Comment by catalin-hritcu** [comment]
Was thinking with @victor-dumitrescu the other day that polarities can be seen as a form of relational refinements. For instance, a positive type constructor like `list` could have type:
```
list: a:Type -> Tot (b:Type{L a <: R a => L b <: R b})
```
where `<:` is an internalization of the subtyping judgment. Would doing polarities this way be a crazy idea? :)

**Comment by catalin-hritcu** [comment]
#593 has some good examples where polarities are really needed.

**Comment by catalin-hritcu** [comment]
Was discussing with @alejandroag the other day that internalizing subtyping (or any other judgment) is tricky, since the logical encoding is sound but incomplete. It seems that for the negative positions in a formula (like `L a <: R a` above) we would need an unsound but complete encoding. Such encodings that are "sound for counterexamples" exist (e.g. in Nitpick and Nunchaku), but it's very unclear how well one can mix the two kind of encodings. And anyway, there are better reasons to implement "sound for counterexamples" encodings ... if we ever do that, we do further experiment with mixing things.

**Comment by catalin-hritcu** [comment]
@aseemr Wondering whether we will also get this from your polarities check for inductives.

**Comment by catalin-hritcu** [comment]
@kyoDralliam has discovered a counterexample/paradox in the literature showing that enabling subtyping for datatypes would currently be unsound. He knows about this for a while, still it would be good to write this all down somewhere (e.g. here). From what I understand, a potential solution for this would be to remove type arguments to datatype constructors.

**Comment by danelahman** [comment]
@catalin-hritcu @kyoDralliam Is that the counterexample from Luo's note about Russell-style universes (http://www.cs.rhul.ac.uk/~zhaohui/universes.pdf)?

**Comment by kyoDralliam** [comment]
It's that same counterexample. Here's is what it looks like for F* + subtyping for pairs.

```
type a * b : Type = | MkPair : #a:Type -> #b:Type -> a * b 

let elim (a b : Type) (c : a * b -> Type) (f: x:a -> y:b -> C (MkPair #a #b x y)) (p: a * b) : C p 
= match p with | MkPair #a #b x y -> f x y

let subject_reduction_failure (x y:nat) (c:int * int -> Type) (f : x:int -> y : int -> c (MkPair #int #int x y)) : c (MkPair #nat #nat x y) = elim int int c f (x,y)
```
this is well typed because `(x,y) <: int * int` but reduces to `f x y` which is of type `c (MkPair #int #int x y)` and *not* `c (MkPair #nat #nat x y)`

**Comment by catalin-hritcu** [comment]
The current fix proposal discussed with @theolaurent and @kyoDralliam is to prevent matching inductive parameters. In Kenji's counterexample this will make it impossible to write `(function (MkPair #a #b x y) -> a)`.

**Comment by catalin-hritcu** [comment]
Discussed this again with @kyoDralliam and @mtzguido, and the main challenge for adding datatype subtyping is that now constraints such as `a * b <: c * d` will no longer reduce to equalities `a = c` and `b = d` but to subtyping `a <: c` and `b <: d`, which might be less efficient. I vaguely remember discussions with @nikswamy in Redmond in fall 2016, but I'm not sure what the conclusion was on this.

**Comment by catalin-hritcu** [comment]
I'm now getting errors on `(function (MkPair #a #b x y)`:
```
This pattern (_) binds an inaccesible argument; use a wildcard ('_') pattern
```
It seems a recent change from July by @nikswamy : https://github.com/FStarLang/FStar/commit/8939c3e9c6896a0ba9ecf0d7372d4c1c12edd483#diff-9a12b72662f95654a4c5ab46f41257b3R99
Does this completely prevent matching on inductive parameters, as we would need for fixing this issue? :)

**Comment by nikswamy** [comment]
@catalin-hritcu Confused by your last remark. Projecting the parameters of a datatype is exactly what we want to *prevent*. Why do you want to write it?

**Comment by catalin-hritcu** [comment]
@nikswamy Sorry if this was unclear. *Completely preventing* matches on inductive parameters is indeed what we need for fixing this issue. And the question is whether your change *completely* prevents such matches already.

**Comment by catalin-hritcu** [comment]
Status update on this issue:
- As required for soundly implementing subtyping for datatype parameters, pattern matching on parameters is now disallowed ([see comment above](https://github.com/FStarLang/FStar/issues/65#issuecomment-461982606)) and [a fix by Nik](https://github.com/FStarLang/FStar/pull/1649) changed the SMT encoding to forbid injectivity for _some_ parameters of inductive type. The current issue would require extending this to all parameters, which Nik tried but that lead to regressions.
- There has been no work so far on implementing subtyping for datatypes, and one worry Nik had is that this could impact typechecking performance, since subtyping constraints on the type parameters are harder to solve than the current equality constraints.

**Comment by catalin-hritcu** [comment]
Just for the record, wanted to mention that @kyoDralliam and @theolaurent are doing that research. For instance, the French readers can see this: https://kenji.maillard.blue/Writings/mettons-de-l-ordre-dans-cic-171220.pdf

**Comment by catalin-hritcu** [comment]
... and a more recent extended in English: https://types22.inria.fr/files/2022/06/TYPES_2022_paper_62.pdf

**Comment by catalin-hritcu** [comment]
Let me mention that there is a now paper about the research above that will appear at ESOP'24:
[Definitional Functoriality for Dependent (Sub)Types](https://laas.hal.science/EC-NANTES/hal-04160858v1). Théo Laurent, Meven Lennon-Bertrand, Kenji Maillard.
