### ISSUE TITLE
Where are floating point types in the library?

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#651]
`FStar.Float` is a valid import in the tutorial - 
I looked in /lib/ and /ulib/, and the only declaration in either is 
`type double = float`. I'm sure there must be further resources as the online tutorial is able to infer, for example, that 4.3 is a float, which means that the syntax for floats must be defined somewhere.

**Comment by jkzinzindohoue** [comment]
There is a file called `FStar.Float.fsti` in ulib, which defines the types `float` and `double`.
However there are no functions defined to do any computation with that type.
Also while there is support in the lexer and parser for the `float` type constant, those are not handled by the encoding to the SMT solver as far as I can tell (see [encode.fs](https://github.com/FStarLang/FStar/blob/master/src/tosmt/encode.fs#L412)).

@nikswamy can certainly tell you more about the status of floating point types, but for now I think that you should consider them as not available.
