### ISSUE TITLE
Update tutorial image on Website 

### ISSUE THREAD

**Issue by vkanne-msft** [FStarLang/FStar#653]

**Comment by s-zanella** [comment]
What's wrong with the current image? 
Is it that the file in the editor suggests that one can have more than one module per file?

**Comment by catalin-hritcu** [comment]
> What's wrong with the current image? 

It's just old? :-)

**Comment by s-zanella** [comment]
Done. 
It doesn't look much newer.

**Comment by markulf** [comment]
:) thanks. It was just showing files that didn't exist anymore. Superficial indeed.
