### ISSUE TITLE
Point to github wiki on Website 

### ISSUE THREAD

**Issue by vkanne-msft** [FStarLang/FStar#654]

**Comment by markulf** [comment]
We should also point to the blog.

**Comment by s-zanella** [comment]
Done. Pointed to the mailing list too.

**Comment by markulf** [comment]
@protz maybe I was jumping the gun with the blog

**Comment by msprotz** [comment]
no, no worries... I've been lazy but I wanted to write something on Dijkstra monads for Frere

**Comment by msprotz** [comment]
if you have anything worth mentioning, really -- like an updated tutorial that people can look at to get familiar with universes, or some neat crypto example, really, by all means, write a short blog post!
