### ISSUE TITLE
What is the default string encoding in F*? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#657]
Whilst going through the Crypto tutorial, I noticed that we _assume_ a function which encodes strings to bytes. Does F\* actually not have such a function?

**Comment by s-zanella** [comment]
There is `assume val string_as_utf8_bytes : string -> bytes` in `ulib/FStar.Bytes.fst`, which I think it's used only for bootstrapping. It isn't assumed to be pure, so it cannot replace the function assumed in the tutorial.

The example in the tutorial uses `Platform.Bytes` in `ucontrib`, which itself assumes a `utf8` function with the same type. So assuming again the function in the tutorial isn't necessary.

**Comment by A-Manning** [comment]
To ask a deeper question - what *are* strings in F*? Char Lists/Arrays?  
It seems lacking that to manipulate strings one has to rely on impure functions.

**Comment by msprotz** [comment]
Not a lot of work has been done in F*; I'm pretty sure that you'll get different results for String.length for utf8 strings depending whether you're running the OCaml build or the F# build. `string` is modeled as an abstract type in `prims.ml`; a few functions exist, but not much is revealed about them, in `FStar.String.fsti`.

We could model strings as lists of *int*s (not char!), i.e. lists of code points, and a couple functions such as `codepoint_of_char: char -> int` and `char_of_codepoint: int -> option char`... and then realize them "properly", i.e. as OCaml strings with utf8-aware functions for splitting and such, or regular .NET strings for the F# build of F*.

**Comment by cpitclaudel** [comment]
Antoine fixed most of this recently (@ad-l, correct me if I'm wrong :)
F* strings are now sequences of codepoints; F* files are required to be UTF-8 encoded.  The doc is here: https://github.com/FStarLang/FStar/wiki/Unicode-Support-in-F%E2%98%85
