### ISSUE TITLE
Installation problems from school

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#66]
Here is Karthik's list:
- we need a 32-bit package for linux
- Win.NET complains about missing FSharp.Core package
- cygwin release (for some people) works with “--lax” but with “--verify” it silently dies (no output)

**Comment by catalin-hritcu** [comment]
Were some of these solved for the POPL tutorial?

**Comment by ad-l** [comment]
We still don't have a 32-bit linux package, but the Windows problems are in fact fixed.
