### ISSUE TITLE
Would a bit primitive or module be useful?

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#660]
Whereas direct manipulation of bits is often desirable, particularly for cryptographic protocols, and at the moment(to my understanding) there is no 'bit' type in the standard library, Perhaps this could be implemented? 

Furthermore, it may be desirable to base `bytes` off of a bit type, and then chars off of bytes, strings off of chars, and so forth. It seems awkward to depend on the bootstrap language for string behaviour/encoding, as well as integer behaviour(Arbitrary precision has different implementation in F# and OCaml). 

I've written a draft module here

```
module Bits

// Nat could be changed to bool if preferred. 
type bit = b:nat{b=0 \/ b=1}

val bit_NOT: bit -> Tot bit
let bit_NOT b0 = 
    if b0 = 0 then 1
    else 0
    
val bit_AND: bit -> bit -> Tot bit
let bit_AND b0 b1 = 
    if b0 = 1 && b1 = 1 then 1
    else 0

val bit_NAND : bit -> bit -> Tot bit
let bit_NAND b0 b1 = 
    if b0 = 1 && b1 = 1 then 0
    else 1

val bit_OR: bit -> bit -> Tot bit
let bit_OR b0 b1 = 
    if b0 = 0 && b1 = 0 then 0
    else 1

val bit_NOR: bit -> bit -> Tot bit
let bit_NOR b0 b1 = 
    if b0 = 0 && b1 = 0 then 1
    else 0 

val bit_XOR: bit -> bit ->Tot bit
let bit_XOR b0 b1 = 
    if b0 = b1 then 0
    else 1

val bit_XNOR: bit -> bit -> Tot bit
let bit_XNOR b0 b1 = 
    if b0 = b1 then 1
    else 0
```

**Comment by jkzinzindohoue** [comment]
My opinion on the matter is that we do need to base the definition of the bitwise operators in machine integers library on such a type. But it is more than just a bit type as you need to map those "bits" to the machine types somehow, a full bitvector theory.
There is already some work going on there, maybe @ProjectYoung can say a word about its current status.

Regarding a "Bit" module or a "bit" type however, it is no more than the native F* boolean type in my opinion, so I do not think it is necessary.

**Comment by jkzinzindohoue** [comment]
Also I recall from a discussing with @nikswamy that Z3 has a bitvector theory which F* is not currently encoding anything to.
Would a "BitVector" module with bijective mappings to machine integers and encoded to Z3 bit vectors be something that could be added in the future ?

**Comment by A-Manning** [comment]
can you point me in the direction of the code detailing how F* interacts with Z3?

**Comment by s-zanella** [comment]
Do you mean `fstar/src/smtencoding/`?

You may want to have a look at https://hatt2016.inria.fr/files/2016/06/HaTT_2016_paper_1-5.pdf, which roughly describes the encoding to Z3.

**Comment by markulf** [comment]
This is a very useful paper, we should point to it more from the Wiki and the Tutorial.
