### ISSUE TITLE
Strange error when declaring records in Tutorial

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#661]
I was attempting to construct a Red-Black Tree module using records; 

```
type colour = 
    | R
    | B
//Excluding left and right for simplicity here
type node = {key:int; col:colour;}

let x = {node.key = 4; col = B;}
```

The error I receive is 

```
no warning handler installed
����^"��8FStar_Absyn_Syntax.Errory�	/Record field names must be constant identifiers_j�@�Interleaving iface+module: /var/fstar/ulib/FStar.Squash.fsti
no warning handler installed
����^"��8FStar_Absyn_Syntax.Errory�	/Record field names must be constant identifiers_j�@�Test(10,9-10,21) : Error
Field Test.Mknode.key is missing
```

Perhaps my syntax in declaring a record is incorrect? That's how it's done in F#, and I can't seem to find documentation suggesting another method.

**Comment by aseemr** [comment]
Hello, this works fine for me:

```
let x = { key = 4; col = B; }
```

**Comment by A-Manning** [comment]
To quote the F# documentation, 

```
type Point = { x : float; y: float; z: float; }
type Point3D = { x: float; y: float; z: float }
// Ambiguity: Point or Point3D?
let mypoint3D = { x = 1.0; y = 1.0; z = 0.0; }
```

It's good practice to be able to declare the type explicitly.

**Comment by A-Manning** [comment]
Wow, Silly mistake on my part. 

Solution was 

`let x:node = { key = 4; col = B; }`

**Comment by jkzinzindohoue** [comment]
Note that it is not completely silly.
Take the following example:
```F#
type point = { x: int; y:int}
type point2 = { x: int; y:int}

let x:point = { x = 2; y = 3}
```
It fails with `Expected type point`.
In F* it is currently the case that if you use the same field names for several records, only the last one will be visible, and type annotations will not solve that.
It is a good thing to know.

**Comment by A-Manning** [comment]
Wow that's a serious issue.... is there a reason for that design choice?

**Comment by markulf** [comment]
I am curious too. How could one overcome this limitation.

Could one write

```
let x:point = {point.x = 2; point.y = 3}
```

That's not more silly than writing 

```
let x:point = {p_x = 2; p_y = 3}
```
