### ISSUE TITLE
Why does this give an error message? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#662]
```
module RedBLackTree

// A node is either Red or Black
type colour = 
  | R // Red
  | B // Black

// A node is either a Tree or Empty
type node =
  | Tree of tree
  | E // Empty
// A tree has a key, colour, a left child and a right child
and tree = {key:int; col:colour;
	  left: node; right: node;}
	  
// try to declare a root
let myRoot :tree = {key=4;col=R;left=E;right=E}
let y:node = myRoot
```

Gives me the error

`Expected expression of type "node";`

In the last line, at 'myRoot'.

Why does it do this? Am I doing my declaration wrong?

**Comment by s-zanella** [comment]
`let y:node = Tree myRoot`

**Comment by A-Manning** [comment]
Cheers! what does the `Tree` there do? I'm still shaky on syntax, I've just seen a lot of 

```
type foo = 
  | Uppercase of uppercase
```
What is the meaning of Uppercase there?

**Comment by s-zanella** [comment]
`Uppercase` is a constructor of the type `foo`. What you wrote is equivalent to
```F#
type foo = 
  | Uppercase: uppercase -> foo
```

**Comment by A-Manning** [comment]
Okay! So Uppercase is a function that takes an uppercase and returns a foo. 

So why can't I do something like 

`let y:node = Tree {key=4;col=R;left=E;right=E}:tree ` ?

**Comment by s-zanella** [comment]
You need to enclose the record within parentheses. 
Also `:tree` isn't valid syntax in definitions. You can use `<:tree` if you must.

```F# 
let y:node = Tree ({key=4;col=R;left=E;right=E}<:tree)
```

**Comment by A-Manning** [comment]
what does the `<:` operator do?

**Comment by s-zanella** [comment]
It checks the value on the left-hand-side can be given the type on the right-hand-side.
