### ISSUE TITLE
Formulas not rendered in part of the tutorial

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#666]
The rendering of formulas in part 13 of the tutorial (crypto) looks strange.
![screen shot 2016-09-04 at 18 15 29](https://cloud.githubusercontent.com/assets/1193431/18232248/fcaf9218-72cb-11e6-89ee-e97443c04e52.jpg)

**Comment by catalin-hritcu** [comment]
Unclear what's happening here, but there are LaTeX formulas earlier in the tutorial that are displayed well (screenshots below).

@ad-l  Could you look in the server logs what's going on?

I have problems with LaTeX formulas on my machine (already reported to @daanx ), but those are appearing all the time, not for particular documents or parts of them.

![screenshot from 2016-09-04 19-20-01](https://cloud.githubusercontent.com/assets/5850655/18232661/e6d0da3e-72d4-11e6-828b-9bebd2f09c05.png)
![screenshot from 2016-09-04 19-20-08](https://cloud.githubusercontent.com/assets/5850655/18232660/e6d07e7c-72d4-11e6-8b5f-fe90af8ec3ab.png)

**Comment by catalin-hritcu** [comment]
Ah, and I should have asked this right away: can anyone reproduce this locally?

**Comment by sishtiaq** [comment]
I can see the raw latex too.

**Comment by catalin-hritcu** [comment]
@sishtiaq Locally? Only in *part* of the file like this? Can you please post the output of madoko and your LeTeX .log file?

**Comment by ad-l** [comment]
There seems to be a latex problem
```
latex: ../../../texk/kpathsea/progname.c:316: remove_dots: Assertion `ret' failed.
Aborted
```

**Comment by markulf** [comment]
I added the text. It rendered in the madoko cloud editor.
