### ISSUE TITLE
Build+Run F* on BashOnWindows

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#667]
There should be no difference to what we do on BashForWindows from what we do on Linux. 

Currently blocked by timer_create bug https://github.com/Microsoft/BashOnWindows/issues/307

**Comment by s-zanella** [comment]
The latest master of Z3 doesn't have this timer problem. Some adjustments may be necessary (e.g. Z3 now has its own String sort, which clashes with the primitive String sort in F*). The nightly binary for the master version of Z3 is available from:

https://github.com/Z3Prover/bin/tree/master/nightly

**Comment by sishtiaq** [comment]
I'll have a look at this.

**Comment by s-zanella** [comment]
With the latest changes by @protz in master (`String` -> `FString` renaming), I could finally build and run F* on BashOnWindows.

This is what I did:

- Installed OPAM using `wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin`
- Run
```
$ opam switch 4.03.0
$ eval `opam config env`
$ opam install depext
$ opam depext conf-gmp.1
$ opam depext conf-m4.1
$ opam install batteries stdint zarith yojson
```
- Installed Z3 nightly from https://github.com/Z3Prover/bin/raw/master/nightly/z3-4.4.2.e7ae60893c90-x64-ubuntu-14.04.zip

**Comment by wintersteiger** [comment]
All issues have been resolved, all tools have run as expected in BashOnWindows/WSL for quite some time now, so I'm closing this issue.
