### ISSUE TITLE
Studying Fstar 

### ISSUE THREAD

**Issue by jeb2239** [FStarLang/FStar#669]
When studying Fstar and using it to solve problems does it make sense to use the master branch version or the binary on the website. I have been using master so far. Also I was wondering what universes are? It seems like there is a stricter syntax, based on what the wiki has shown.  Is it better to write code using universes?

**Comment by catalin-hritcu** [comment]
@jeb2239  Using the `master` branch and universes seems like a good idea. The binary releases are very old given the current development pace of F*.

As for universes, they are a way to stratify types to prevent logical paradoxes. Most of the time you will not care about them, but if you're migrating code to universes there are [several (mostly syntactic) changes you will need to take care of])https://github.com/FStarLang/FStar/wiki/Migrating-code-to-universes). Migrating code aside, universes are the new default and they are already more stable than the old binaries.

**Comment by markulf** [comment]
We did a new binary release, so now our recommendations in increasing order of difficulty are:

* You can already play with the fstar tutorial on https://www.fstar-lang.org/tutorial/

* We did a binary beta release and may still update it before the school.

   See https://github.com/FStarLang/FStar/releases


* One way to get the full fstar experience is to use docker. It requires an installation of docker, and an X server, plus some experience in configuring it to get a graphical user interface.

   See https://github.com/FStarLang/FStar/wiki/Running-F%2A-from-a-docker-image


* To compile and install F* locally its best to do the OCaml build. 

   See https://github.com/FStarLang/FStar/blob/master/INSTALL.md


Any feedback to improving the installation instructions online is welcome.
