### ISSUE TITLE
Suggestion: Allow elif statements

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#670]
consider the following code: 

```
module Test
open Prims

let myTuple = (5,7)

//matches integer tuple to it's product
val matchTuple: t:(int*int) -> Tot int
let matchTuple t = match t with
    | (a,b) -> 
        if a = 1 &&b = 1 then 1
        else 
            if a = 1 && b = 2 then 2
            else
                if a = 2 && b = 1 then 2
                else Prims.op_Multiply a b
```

Not having an `elif` leads to a nasty triangle indent. 

Is there a design reason for not having an `elif` statement?

**Comment by sishtiaq** [comment]
You could write out the table in a tabular style instead:

```
let matchTuple (a,b) = 
     match (a,b) with 
     | (1,1) -> 1
     | (1,2) -> 2
     | (2,1) -> 2
     | (_,_) -> Prims.op_Multiply a b 
```

**Comment by A-Manning** [comment]
In this particular case, yes, but the utility of an `elif` statement is clear

**Comment by beurdouche** [comment]
Do you mean: 
```
if condition then 
   b1 
else if condition2 then
   b2
else b3
``` ?

**Comment by beurdouche** [comment]
That said, I agree that if we can do better it would actually be a good idea. There is a discussion on switching to an F# like syntax to avoid scoping issues https://github.com/FStarLang/FStar/pull/652

**Comment by cpitclaudel** [comment]
Is `elif` intended to differ from `else if`? If so, I'm afraid of potential confusion. If not, I'm not sure it's a big gain over the regular `else if` :)
