### ISSUE TITLE
`FStar.Monotonic.Seq` currently does not support reasoning about abstract values that are not `eqtype`s

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#674]
As far as I can tell this creates a hole in our modelling of secrecy using parametricity. 

See https://github.com/FStarLang/FStar/blob/master/examples/crypto/EtM.Plain.fst. 

This issue should also reappear analogously in a crypto code review of mitls-fstar.

**Comment by s-zanella** [comment]
Fixed by eed9cb6 and 2356ecf
