### ISSUE TITLE
Hello world no longer working in F#: The namespace or module 'Obj' is not defined

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#675]
```
[hritcu@detained hello]$ make fs 
../../bin/fstar.exe   --odir out --codegen FSharp hello.fst
Extracting module FStar.PredicateExtensionality
Extracting module FStar.TSet
Extracting module FStar.Heap
Extracting module FStar.ST
Extracting module FStar.All
Extracting module Hello
Verifying module: Hello
All verification conditions discharged successfully
cp ../../bin/FSharp.PowerPack.dll out
fsharpc --mlcompatibility -r ../../bin/FSharp.PowerPack.dll --nowarn:0086 -o out/hello.exe ../../lib/fs/prims.fs ../../lib/fs/io.fs out/Hello.fs
F# Compiler for F# 4.1
Freely distributed under the Apache 2.0 Open Source License

/home/hritcu/Projects/fstar/pub/lib/fs/prims.fs(84,25): error FS0039: The namespace or module 'Obj' is not defined
make: *** [Makefile:44: fs] Error 1
```

**Comment by beurdouche** [comment]
Not surprising :(

**Comment by thinkyfish** [comment]
I can confirm this bug.

I managed a workaround by commenting out and changing the relevant lines in `prims.fs`:
` (*let Obj.magic () = failwith "no magic"*) `
 `   let unsafe_coerce x = failwith "no magic" `

Although I have no idea what consequences this would have.
`Obj.magic` doesn't seem to be used in any other .fs files and seems to be a hangover from ocaml.

**Comment by catalin-hritcu** [comment]
@thinkyfish Thank you for the fix. I applied it, although it's to a file that we shouldn't be using in the first place. So I also changed `examples/hello/Makefile` to use `ulib/fs/prims.fs` instead of `lib/fs/prims.fs`.

It's depressing that we 4(!) `prims.fs` versions lying around at various levels of obsoleteness:
```
./lib/fs/native_int/prims.fs
./lib/fs/prims.fs
./ulib/fs/native_int/prims.fs
./ulib/fs/prims.fs
```

I've also noticed that in the same `examples/hello/Makefile` file there are two other targets that don't work, although they are using OCaml not F#:
```
[hritcu@detained hello]$ make testseq
[...]
unrecognized option '--use_native_int'
[...]
Error: I/O error: out/FStar_Seq.ml: No such file or directory
[...]
[hritcu@detained hello]$ make bat_testseq                                                                                (git)-[catalin_private] 
../../bin/fstar.exe --use_native_int --odir out --codegen OCaml testseq.fst
unrecognized option '--use_native_int'
cp ../../ulib/ml/native_int/prims.ml ../../ulib/ml/FStar_IO.ml FStar_Seq.ml out
cp: cannot stat '../../ulib/ml/native_int/prims.ml': No such file or directory
cp: cannot stat 'FStar_Seq.ml': No such file or directory
```
@nikswamy @msprotz  Does the feature these tests are supposed to illustrate still exist? If not let's remove them!

**Comment by nikswamy** [comment]
We should either make a concerted effort to fix and maintain the F# code generator, or else officially not support F# code generation any more. At the moment, it is in a sad, half-baked state.

**Comment by nikswamy** [comment]
@polubelova @prosecco : is supporting an F# backend something that you're also thinking about?
