### ISSUE TITLE
https://www.fstar-lang.org/ is down

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#685]

**Comment by catalin-hritcu** [comment]
We've set up a temporary mirror at http://fstar.gforge.inria.fr/
This includes a static copy of the website and tutorial http://fstar.gforge.inria.fr/tutorial/tutorial.html
This way people can at least get information on F* and try the tutorial locally on their machine (there is no way to run F* online at the moment)

**Comment by A-Manning** [comment]
Cheers !

**Comment by catalin-hritcu** [comment]
@sishtiaq  www.fstar-lang.org is still down. What I provided above is just a temporary workaround.

**Comment by s-zanella** [comment]
Looks like the server is up again.

**Comment by A-Manning** [comment]
Can we reopen this? fstar-lang.org is down again.

**Comment by catalin-hritcu** [comment]
Not sure what happened, but it works for me now.
