### ISSUE TITLE
`Identifier Not Found` when giving a function a dependent type and tuple argument

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#688]
Consider the following code:

```
module Scratch

val addTuple: a:nat * b:nat -> Tot (c:nat{c >= a})
let addTuple (a,b) = a + b
```

The error message is 
```
C:\Dev\Scratch.fst(3,47-3,48) : Error
Identifier not found: [a]
[Finished in 1.212s]
```

**Comment by nikswamy** [comment]
These variables are indeed not in scope, by design.

Curry the function using an -> instead of *.

**Comment by A-Manning** [comment]
What was the reason behind the design choice?

**Comment by nikswamy** [comment]
Tuples receive no special treatment, aside from the fact that you can write `t * s` instead of `tuple2 t s`

For what you seem to want to express, write:

`x:(nat * nat) -> Tot (y:nat{y=fst x + snd x})`

**Comment by A-Manning** [comment]
Fair enough, thanks.
