### ISSUE TITLE
Precedes vs <<

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#69]
Hello,

It seems that the symbol "<<" does not work. The following code returns an error:

``````
module Multi_Set

assume type multiset: a:Type -> Type

assume val contains: multiset 'a -> 'a -> Tot bool

assume val order : multiset 'a -> ('a -> Tot lex_t) -> Tot lex_t

assume val smallest : multiset 'a -> ('a -> Tot lex_t) -> Tot 'a
assume val biggest : multiset 'a -> ('a -> Tot lex_t) -> Tot 'a

assume Lemma_smallest: forall (a:Type) (x:a) (f:(a -> Tot lex_t)) (m:multiset a).
                       (contains m x) ==> ((f (smallest m f)) << (f x))
``````

The error:
```````
ERROR: Syntax error near line 13, character 64 in file test.fst
``````

On the other hand the following code type check:
```````
module Multi_Set

assume type multiset: a:Type -> Type

assume val contains: multiset 'a -> 'a -> Tot bool

assume val order : multiset 'a -> ('a -> Tot lex_t) -> Tot lex_t

assume val smallest : multiset 'a -> ('a -> Tot lex_t) -> Tot 'a
assume val biggest : multiset 'a -> ('a -> Tot lex_t) -> Tot 'a

assume Lemma_smallest: forall (a:Type) (x:a) (f:(a -> Tot lex_t)) (m:multiset a).
                       (contains m x) ==> (Precedes (f (smallest m f)) (f x))
```````

**Comment by nikswamy** [comment]
Ok, added support for this in the parser.
