### ISSUE TITLE
Request: Add support for unicode symbols {𝔹, →, etc.} to F*, rather than through editor support 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#694]
Whilst displaying keywords in Emacs as unicode symbols is nice, it would be easier to extend editor support if F\* itself supported the use of those symbols as an alternative.

**Comment by msprotz** [comment]
Yes, we've been discussing this for a while and this is a long-standing issue. It mostly revolves around switching to sedlex for the OCaml version.

**Comment by A-Manning** [comment]
Do you have any idea when this might be implemented? I'm wondering if it's worth adding unicode pretty-printing to atom at the moment.

**Comment by cpitclaudel** [comment]
I think @ad-l is working on this.

**Comment by A-Manning** [comment]
Might be worth mentioning here that the [Iosevka](https://be5invis.github.io/Iosevka/) font has a feature tag `XFST` specifically for F*.

**Comment by cpitclaudel** [comment]
Done by @ad-l :) see https://github.com/FStarLang/FStar/wiki/Unicode-Support-in-F%E2%98%85
But these symbols remains a pain, so I'm against actually using them in source files (typing them isn't easy for everyone; support is spotty without extra fonts; and some fstar-mode user actually disable prettification)
