### ISSUE TITLE
Can't define prefix operator

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#697]
`let (!^)` doesn't work but `let op_Bang_Hat` does (with @fournet)

**Comment by nikswamy** [comment]
I've never had much luck in defining operators this way. For example, this fails too:

```
module Test
val (+) : int -> int -> Tot int
```

**Comment by kyoDralliam** [comment]
Looking at the parser it seems tyo just be forbidden. I think it should be easy to patch it (just need to create a new syntactic category accepting either an ident or an operator) but I need to understand how operators are handled afterward (are they kept in the compiler in their literal form (e.g. `!^`) or expanded form (`op_Bang_Hat`) ?

**Comment by kyoDralliam** [comment]
Should be patched in the `kyod_parser` branch but at the price of duplicating some (already-duplicated) code : I put a copy of `compile_op` in `parser.mly` coming from `tosyntax.fs` (and there is a slightly different version of this function in `desugar.fs`). How should this be cleaned up ?

**Comment by catalin-hritcu** [comment]
Fixed by Kenji's new parser
