### ISSUE TITLE
Property support empty inductive types

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#70]
Santiago suggested that the following code seems natural to Coq or Agda users:
```
type empty =
val test : x:empty -> Lemma (False)
let test x = match x with _ -> ()
```
but it raises an "unknown assertion" error.

Does it make sense to make this work?

**Comment by catalin-hritcu** [comment]
+1 for properly supporting empty inductives; they are needed for constructive proofs (see `cfalse` in `lib/constr.fst`)

**Comment by s-zanella** [comment]
For the record, this has been fixed. To eliminate an empty type one uses a `match` without any branches:
```
type empty =
val test : x:empty -> Lemma (False)
let test x = match x with
```
