### ISSUE TITLE
Do not include tests in lib files

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#704]
We discussed moving away from the current style where we put a bunch of tests at the end of library files, or worse, we intersperse them with library functions. The majority of these tests are not marked as `private` and end up polluting the namespace and the Z3 context. Tests should go to a separate module in a separate folder.

Some examples:
- [ ] https://github.com/FStarLang/FStar/blob/master/ulib/FStar.List.Tot.fst#L244 
  (which should use `assert_norm` btw)
- [ ] https://github.com/FStarLang/FStar/blob/master/ulib/FStar.Monotonic.Seq.fst#L182
- [ ] https://github.com/FStarLang/FStar/blob/master/ulib/FStar.HST.fst#L210
- [ ] https://github.com/FStarLang/FStar/blob/master/ulib/FStar.HyperHeap.fst#L146
- [ ] https://github.com/FStarLang/FStar/blob/master/ulib/FStar.HyperStack.fst#L44

**Comment by s-zanella** [comment]
Note that marking tests as `private` does not solve the problem because they are still encoded to Z3.

**Comment by cpitclaudel** [comment]
There seems to be relatively few such tests at this point:

```
ag --literal let\ test_ .
hyperstack/FStar.ST.fst:252:1:let test_do_nothing x =
hyperstack/FStar.ST.fst:260:1:let test_do_something x =
hyperstack/FStar.ST.fst:269:1:let test_do_something_else x v =
hyperstack/FStar.ST.fst:275:1:let test_allocate () =
hyperstack/FStar.ST.fst:282:1:let test_nested_stl () =
hyperstack/FStar.ST.fst:286:1:let test_nested_stl2 () =
hyperstack/FStar.ST.fst:295:1:let test_stack x =
hyperstack/FStar.ST.fst:306:1:let test_stack_with_long_lived s =
hyperstack/FStar.ST.fst:315:1:let test_heap_code_with_stack_calls () =
hyperstack/FStar.ST.fst:327:1:let test_heap_code_with_stack_calls_and_regions () =
hyperstack/FStar.ST.fst:340:1:let test_lax_code_with_stack_calls_and_regions () =
hyperstack/FStar.ST.fst:352:1:let test_lax_code_with_stack_calls_and_regions_2 () =
hyperstack/FStar.ST.fst:365:1:let test_to_be_stack_inlined () =
hyperstack/FStar.ST.fst:373:1:let test_stack_function_with_inline () =
hyperstack/FStar.ST.fst:383:1:let test_st_function_with_inline () =
hyperstack/FStar.ST.fst:393:1:let test_to_be_inlined () =
hyperstack/FStar.ST.fst:405:1:let test_st_function_with_inline_2 () =
hyperstack/FStar.ST.fst:426:1:let test_with_frame (x:stackref int) (v:int)
FStar.Monotonic.Seq.fst:193:9:private let test_alloc (#a:Type0) (p:seq a -> Type) (r:rid) (init:seq a{p init})
FStar.List.Tot.Base.fst:443:18:private abstract let test_sort = assert (sortWith (compare_of_bool (<)) [3; 2; 1] = [1; 2; 3])
20 matches
3 files contained matches
236 files searched
```

**Comment by s-zanella** [comment]
It's tedious but easy to identify all tests in `ulib` and move them to standalone modules in the `examples` directory. Given that some of them are in pervasive files like `FStar.Monotonic.Heap` it seems worth the while doing it to reduce the Z3 context.
Would marking them as `[@"opaque_to_smt"]` would be enough?

**Comment by aseemr** [comment]
Thanks for reviving this discussion @s-zanella.

I agree with the idea of moving tests to `examples`. I did that for `HyperStack` some time back (see `examples/micro-benchmarks/Test.HyperStack.fst`).

About `FStar.Monotonic.Heap`, the tests are in `.fst` which is not in the context in non-friend cases.

And even if it is, the tests are all lemmas without patterns. F* does not encode them to Z3 (it generates a symbol, but even their spec is not encoded). So, they are already `opaque_to_smt` (except a symbol encoding).

This is different for effectful function tests (like those in `HyperStack`) as their specs are precisely encoded.

**Comment by aseemr** [comment]
I moved tests from lists and printf to examples. Closing this issue.
