### ISSUE TITLE
Change the default effect to be Tot and namespace insensitive

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#705]
The following code

```
module Bug

let st (h:Type) (a:Type) =
  h -> M (a * h)

val return_st : (h:Type) -> (a:Type) -> a -> st h a
let return_st h a x = fun s -> x, s
```

fails with

```
./Bug.fst(6,51-7,35) : Error
Expected a term of type "(h:Type -> a:Type -> uu___:a@0 -> (Bug.st h@2 a@1))";
got a function "(fun h a x s -> (Prims.Mktuple2 x@1 s@0))" (Function definition takes more arguments than expected from its annotated type)
```

However, if the module is renamed to start with `FStar.`, the error does not occur and it verifies.

**Comment by nikswamy** [comment]
This is known behavior and is related to us planning on changing the default effects. 

You can write `... a -> Tot (st h a)`

**Comment by mtzguido** [comment]
Ah, thanks! Should I close this then?

**Comment by catalin-hritcu** [comment]
Previous discussions of this also happened in https://github.com/FStarLang/FStar/issues/581#issuecomment-233161328

**Comment by catalin-hritcu** [comment]
And here is one more instance of problems with out current defaults #623

**Comment by catalin-hritcu** [comment]
@nikswamy just fixed this
