### ISSUE TITLE
Refinement failure

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#712]
The following code

```
module Bug712

inline let s = int -> Tot int
let r (a:Type0) = f:s{True}

let app0 (m : r unit) = m 0
```

Fails with

```
./bug712.fst(6,24-6,25) : Error
Expected a function;
got an expression of type "(f#18:Bug712.s{Prims.l_True})"
```

Note that `s` is even declared `inline`. If one removes the `a` argument (which is unused) from the `r` type, verification succeeds.

**Comment by catalin-hritcu** [comment]
There is an easy workaround for this, which is to add a type annotation on `m`. Until recently I would have done it with
```
let app0 (m : r unit) = let m' : int -> Tot int = m in m' 0
```
but now I know better :)
```
let app0 (m : r unit) = (m <: int -> Tot int) 0
```
Anyway, I agree this annotation shouldn't be needed.

**Comment by mtzguido** [comment]
This is a bad recursive call in `check_function_app` ([here](https://github.com/FStarLang/FStar/blob/master/src/typechecker/FStar.TypeChecker.TcTerm.fs#L1255)). Pushing a fix soon.

**Comment by msprotz** [comment]
deferring review to @nikswamy who knows this code better than I do... thanks Guido!

**Comment by nikswamy** [comment]
Guido and I discussed this at length already

**Comment by mtzguido** [comment]
Fix merged to master.
