### ISSUE TITLE
Dockerfiles: add support for multiple editors

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#716]
Per discussion on having multiple editor support for Docker builds
@beurdouche @DanielFabian @sishtiaq  @A-Manning

**Comment by beurdouche** [comment]
The real question here is who is interested in having a Dockerfile with atom and vim support ?
Who would maintain it ?

**Comment by DanielFabian** [comment]
IMO, the person who actually has a usecase for the other versions is welcome to set it up, I am happy to help out with an advice as to how to set it up, but I have even less experience with vim or atom than with emacs, so I don't see maintaining the other editors myself.

**Comment by markulf** [comment]
If this were the official way to do CI for editor modes and to test installation instructions, then this might be more generally useful.

**Comment by DanielFabian** [comment]
well, that's easy, though

take the fstar baseline without editors. And `FROM` that do the builds for the editor modes. Then the CI for those will be super quick, as it can just download the binaries of fstar and doesn't build anything but the editor modes.

**Comment by sishtiaq** [comment]
I agree with @DanielFabian here: If someone wants/needs a Docker+F*+EditorThatIsNotEmacs, they should file an issue on it to track that work, and lead/push an implementation. 
In the meantime, unless there's something specific to discuss here, I suggest we close this issue.

**Comment by wintersteiger** [comment]
Closing as suggested by @sishtiaq
