### ISSUE TITLE
dm4f: generate lift from Pure to all DM4F effects

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#719]
It's actually just the return.

**Comment by kyoDralliam** [comment]
Implemented on https://github.com/FStarLang/FStar/commit/70329e0fbf7272c96b740192356f43587c470bf4 but it is still only the wp part.

@nikswamy The term part of the lifting is invalid as soon as the defined effect is reifiable since PURE is not reifiable. Should it really be the case ?

**Comment by kyoDralliam** [comment]
The reification of a lift from pure is now automagically replaced by the corresponding return in the mormalizer.
