### ISSUE TITLE
Run fsdoc nightly

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#722]
Generate F* docs nightly on VSTF machine. Publish so all can see.

**Comment by sishtiaq** [comment]
Quetions for @vkanne-msft: 

- fsdoc will only run on F* files (*.fst, *.fsti). I assume we only want to run fsdoc on FSTAR/ulib, maybe FSTAR/examples? 
- Where do we want to publish the results?

**Comment by msprotz** [comment]
1. Yes, only `ulib/*.fst*` for the moment.
2. fstarlang.github.io/docs -- the machine should just just checkout the corresponding repository, do something along the lines of `cd fstarlang.github.io/docs && pandoc path/to/the/generated/*.md && git add * && git commit -am "Automated doc refresh" && git push`

**Comment by sishtiaq** [comment]
Changed the 
![image](https://cloud.githubusercontent.com/assets/4727977/19687699/6f102cea-9abe-11e6-87e6-2c7ed96b0013.png)
definition to do this. Output written to https://fstarlang.github.io/docs/.
