### ISSUE TITLE
F* build should be clean, output minimal.

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#724]
F\* should build cleanly, with minimal output to stdout/stderr.

**Comment by cpitclaudel** [comment]
We've both progressed and regressed on this recently.  I've fixed some warnings in the OCaml build recently, and @kyoDralliam and I silenced a one that was issued a lot when extracting (about implicit assumes).

**Comment by cpitclaudel** [comment]
Now tracked as #1273
