### ISSUE TITLE
How to make a simple GADT work?

### ISSUE THREAD

**Issue by mrakgr** [FStarLang/FStar#727]
```
module GadtTest

type expr (t: Type): Type =
    | C : t -> expr t
    | Add : expr int -> expr int -> expr int
    | Eq : expr int -> expr int -> expr bool
```
I've only just recently figured out how GADTs work in Haskell, tried to emulate them using phantom types in F# and then in Fstar once that failed. But I am not sure how to get the above example to type check. Am I doing something wrong here?

**Comment by nikswamy** [comment]
```
module GadtTest

noeq type expr : Type -> Type =
    | C   : #t:Type -> t -> expr t
    | Add : expr int -> expr int -> expr int
    | Eq  : expr int -> expr int -> expr bool

let mk_17 : expr int = Add (C 1) (C 16)

let rec eval (#a:Type) (e:expr a) : Tot a = 
  match e with 
  | C i -> i
  | Add e1 e2 -> eval e1 + eval e2
  | Eq e1 e2 -> eval e1 = eval e2
```

**Comment by mrakgr** [comment]
Ok, I see now, thanks. I am not sure what these implicits parameters are for or why they are needed there in the first place though.

**Comment by nikswamy** [comment]
Disregarding implicits for the moment, the type of `C` is `t:Type -> t -> expr t`. What this means is that for any type `t`, you can apply `C` to `t` and a value of that type. e.g., `C int 0` or `C bool true`. Now, as you can see, explicitly writing `int` or `bool` is a bit painful. So, by marking the `t` argument implicit, you can just write `C 0` or `C true` and the compiler will figure out what the missing `t` argument is. The same thing applies to `eval`. Hope that helps
