### ISSUE TITLE
build fails at step 3

### ISSUE THREAD

**Issue by hasufell** [FStarLang/FStar#735]
```sh
$ make -C src/ocaml-output
make: Entering directory '/home/hasufell/git/FStar/src/ocaml-output'
make -j 1 -C ../../lib/ml
make[1]: Entering directory '/home/hasufell/git/FStar/lib/ml'
ocamlfind opt -thread -package zarith,batteries -linkpkg -g   -c MkPrims.ml
File "MkPrims.ml", line 18, characters 14-18:
Error: Syntax error
make[1]: *** [Makefile:34: MkPrims.o] Error 2
make[1]: Leaving directory '/home/hasufell/git/FStar/lib/ml'
make: *** [Makefile:60: all] Error 2
make: Leaving directory '/home/hasufell/git/FStar/src/ocaml-output'
```

Ocaml-4.02.1
findlib-1.5.3
zarith-1.4.1
batteries-2.5.0
fsharp from git master
mono-4.2.2.30

**Comment by catalin-hritcu** [comment]
My guess is that your OCaml version is slightly too old. `INSTALL.md` only mentions OCaml version from 4.02.2 to 4.03.0, and I think it's for a good reason. On my machine I have lots of version of OCaml and can reproduce your problem with 4.02.1:
```
[hritcu@detained ml]$ opam switch 4.02.1
...
[hritcu@detained ml]$ ocamlfind opt -thread -package zarith,batteries -linkpkg -g   -c MkPrims.ml
File "MkPrims.ml", line 17, characters 14-18:
Error: Syntax error
```
However, everything works fine with newer OCaml versions:
```
[hritcu@detained ml]$ opam switch 4.03.0
...
[hritcu@detained ml]$ ocamlfind opt -thread -package zarith,batteries -linkpkg -g   -c MkPrims.ml
< -package zarith,batteries -linkpkg -g   -c MkPrims.ml
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Z, and its interface was not compiled with -opaque
```
So I think the easiest fix is for you to just upgrate your OCaml.

**Comment by hasufell** [comment]
That is correct, the build works with 4.03.0. Would it be possible that the Makefile warns about it?

**Comment by catalin-hritcu** [comment]
If we find a portable way of doing this sure, we could just fail early if the OCaml version is not large enough. Can people check whether the following script (taken from [here](http://stackoverflow.com/a/24067243/340297)) does the right thing on their machines:
```
function version_gt() {
  test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1";
}

too_low=4.02.1
current=`ocamlc -version`
if version_gt $current $too_low; then
     echo "Installed OCaml version ($current) recent enough (version strictly larger than $too_low)"
else
    echo "Installed OCaml version ($current) too old (need version strictly larger than $too_low)"
    exit 1
fi
```
@beurdouche @s-zanella  I'm particularly worried about macs, which usually come with old and awkward versions of unix tools, but hopefully that's not the case for `sort -V`.

**Comment by msprotz** [comment]
@catalin-hritcu : `echo if Sys.ocaml_version >= 4.02.2 then exit 0 else exit 1 | ocaml`

**Comment by catalin-hritcu** [comment]
Fix should be reaching master any time soon.
