### ISSUE TITLE
One more problem with projections for inductives

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#736]
The type of Mtac2 tactics is currently rejected by F*

```
noeq type goal : Type =
| Goal : #a:Type -> a -> goal
| AHyp : #a:Type -> option a -> (a -> Tot goal) -> goal
```

with the following error message:

```
Expected expression of type "(uu___:(MetaCoq.AHyp.a projectee) -> Tot MetaCoq.goal)";
got expression "_2" of type "(uu___:a -> Tot MetaCoq.goal)"
```

This error goes away if passing `--__temp_no_proj MetaCoq` or if changing the `Type`s to `Type0`s, although the later is not really a solution in this case.

The error looks as follows once showing universes:

```
Expected expression of type "(uu___:(Bug736.AHyp.a<n1883> projectee) -> Tot Bug736.goal<n1882>)"; 
got expression "_2" of type "(uu___:a -> Tot Bug736.goal<n1883>)"
```

**Comment by catalin-hritcu** [comment]
@kyoDralliam Is there maybe a way to work around this using the new explicit universe syntax? :)

**Comment by kyoDralliam** [comment]
Seems to have been solved with the elaboration of projectors after typechecking
