### ISSUE TITLE
Kremlin request

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#738]
@jkzinzindohoue and I would love to see the following get inline:

```
module Blah
open FStar.Int32
open FStar.ST

open TestLib

let test' (): ST.Stack Int32.t (fun _ -> true) (fun _ _ _ -> true) =
  0l

inline_for_extraction let test = test'

val main: Int32.t -> FStar.Buffer.buffer (FStar.Buffer.buffer C.char) ->
  ST.Stack Int32.t (fun _ -> true) (fun _ _ _ -> true)
let main argc argv =
  push_frame ();
  let x = test () in
  pop_frame ();
  C.exit_success
```

(bug reported by jk, testcase by myself)

Thanks,

Jonathan

**Comment by msprotz** [comment]
Note to self: this is important to remove the special case for `op_Array_Assignment` and others in `src/extraction/kremlin.fs`

**Comment by nikswamy** [comment]
`test` will indeed be inlined to `test'` in this example.
