### ISSUE TITLE
Some questions about FStar

### ISSUE THREAD

**Issue by adnelson** [FStarLang/FStar#74]
Hello F* team! I'm interested in learning F* and I had some questions about the language. Not being sure where to post these (perhaps that could be considered one of my questions), I figured I would post them here:

* Is there any plan to support Haskell as an output language of F*?
* Does F* have:
  * type classes?
  * anything akin to `do`-syntax for monadic computation (which of course, it probably doesn't if it doesn't have type classes)
  * anonymous records like SML?
  * record-level computation, for example functions which take a record and create a new record with a new attribute (such as in Ur or Ermine)?
  * lazy evaluation (or at least awareness thereof when outputting code)?
  * tactics for expedition of proofs?
  * a REPL? Especially for interactive theorem proving
* For any of the above, if they don't exist now, are they planned? Have they already been considered and rejected?

**Comment by catalin-hritcu** [comment]
This discussion seems to have died down, and I'll close the issue. If there are any immediately actionable items here (e.g. on purity and evaluation order in our back-ends) please file separate issues for them.
