### ISSUE TITLE
Subtyping check fails where it shouldn't

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#747]
Consider the following snippet: 
```
open FStar.List.Tot

val append_hd: l:list int -> r:list int ->
  Lemma(requires is_Cons l /\ is_Cons r)
  (ensures hd (l@r) = hd l)
```

This gives an error 
```
Subtyping check failed; expected type (l#434:(Prims.list Prims.int){(Prims.b2t (Prims.is_Cons l@0))}); got type (Prims.list Prims.int)
Error: 1 errors were reported (see above)
```

specifying the condition as `requires is_Cons l /\ is_Cons r /\ is_Cons (l@r)` has no effect.

**Comment by catalin-hritcu** [comment]
This doesn't parse as you think it does. You're missing a parenthesis around the arguments of `requires` and `ensures`, which are really treated as a functions. The following works
```
val append_hd: l:list int -> r:list int ->
  Lemma (requires (is_Cons l /\ is_Cons r))
        (ensures (is_Cons l /\ is_Cons r /\ (hd (l@r) = hd l)))
```
Please note that I needed to manually duplicate the precondition in the postcondition to convince F\* that the preconditions of `hd` are satisfied. That's a well-known issue in F\* (#57).

**Comment by s-zanella** [comment]
You don't really need parentheses for this to parse corretly. This works fine:
```F#
val append_hd: l:list int -> r:list int ->
  Lemma(requires is_Cons l /\ is_Cons r)
  (ensures is_Cons l /\ hd (l@r) = hd l)
```

**Comment by catalin-hritcu** [comment]
@s-zanella  My bad, maybe this was parsing correctly in this case, my confusion. However, this is a big source of confusion including bizare context dependent parsing bugs (#252), so I wouldn't recommend to anyone relying on this parsing right.

**Comment by s-zanella** [comment]
It's been a while since I haven't hit #252. I think it only occurs with the F# build now.
Anyways, adding parentheses is good practice and makes it more readable.
