### ISSUE TITLE
Semantics of ST

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#75]
Hello,

I looked at the tutorial for the school 2014 but the part on the management of reference does not contain a lot of explanation (only the two examples).

Would it be possible to have the syntax and semantics of the effects ML and ST (from example of section 8 typically). What does it mean to create an "effect" like in example 8.2 
``````
effect InvST (t:Type) (inv:(heap -> Type)) (fp:set aref) (post:(heap -> t -> heap -> Type)) =
             ST t (fun h -> On fp inv h)
                  (fun h i h' -> post h i h' /\ On fp inv h')
                  (SomeRefs fp)
``````

On this example, what does `On fp inv h` mean ?

Thank you 

Best,
Vincent

**Comment by catalin-hritcu** [comment]
Nik documented state in Sections 9, 10, and 11 of the F* tutorial (https://www.fstar-lang.org/tutorial/). Closing.
