### ISSUE TITLE
Are refinement types supposed to be erased at extraction? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#751]
When I write functions with a restricted domain, eg. `val my_function: x:nat{x>=2} -> Tot nat` , the extracted code gives `let my_function : Prims.nat  ->  Prims.nat` , which would allow the cases that should not occur. 

Is this intended? If so, it should probably be mentioned somewhere, possibly in the tutorial or wiki. 

This seems to be related to #432, although this occurs in OCaml as well, despite nikswamy's assertion that 'this problem is very .NET specific.'

**Comment by nikswamy** [comment]
My assertion was in reference to a specific paper i cited on that thread.

Refinement types are intentionally erased.

Checking them dynamically at the boundaries may be nice, but so far, no concrete plans.

Closing this. Let's continue any further discussion in #432

**Comment by A-Manning** [comment]
My apologies, I seem to have misunderstood you.
