### ISSUE TITLE
Support for loops and mutable variables

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#752]
OCaml-style loops and mutable variables are not supported at the moment, but they would be nice to have at some point.

**Comment by kyoDralliam** [comment]
That seems like a new syntax/design for FStar. Is there some proposal anywhere for such things ?

I would argue that the design of loops in Ocaml is pretty poor : for-loops are pretty restricted in their use compared to the one you can find in python/rust/... where you can iterate on an arbitrary iterator. I think we could come up with a design of "proof-safe iterators" which would come with a proof of termination and a "nice" way for proving inductive properties.

There were also interesting discussions during rust design process about having a while loop or not. They finally settled with a loop-loop which unconditionally loops plus a break statement. I don't know how relevant that would be when proving correctness properties I still think it's an interresting design choice.

**Comment by catalin-hritcu** [comment]
Our main use case for loops is Low*, a subset of F* that enjoys a direct translation to C. For non-Low* code, I think recursion is just fine :)

**Comment by nikswamy** [comment]
We have C.Loops in Kremlin, Lib.Loops in HACL, stack allocated mutable variables used pervasively in Low*.
