### ISSUE TITLE
inline_for_extraction not normalizing under a match

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#755]
```
module Test

inline_for_extraction let foo = false

let test () =
  let x, y = 1, 3 in
  if foo then
    IO.print_string "hello"
  else
    IO.print_string "hella"
```

**Comment by msprotz** [comment]
Also I'm seeing this (Kremlin's pretty-printing):

```
    if (&&,bool) false false then
```

**Comment by msprotz** [comment]
```
module Test

inline_for_extraction let foo = false
inline_for_extraction let bar x = false

let test () =
  let x, y = 1, 3 in
  if foo && bar () then
    IO.print_string "hello"
  else
    IO.print_string "hella"
```

I can confirm that your commit fixes the earlier test case, but here's a new one...

**Comment by nikswamy** [comment]
This is quite delicate and implementing it is simple but is a big conceptual change.

In summary, you're asking for `bind (return e) f` to be simplified used the monad laws to `f e`. Rewriting by the monad laws is not a definitional equivalence in F*. I can add it as an optimization for extraction only but this will be the first instance of it. Heads up all the dm4f folks.

**Comment by msprotz** [comment]
oh but I just realized that the let-bindings in Flag.fsti were not annotated with `Tot`... and I just remembered the default effect is ML. Let me check if adding a `Tot` annotation would help.

**Comment by msprotz** [comment]
Ok the example above also doesn't work if `bar` is `Tot`. Would it simplify things conceptually to allow this optimization to take place only for `Tot` terms?

**Comment by nikswamy** [comment]
the point really is that this term is of the form `bind_ML (lift_Pure_ML (foo && bar())) (fun x -> if x then IO.print_string "hello" else IO.print_string "hella")`

**Comment by msprotz** [comment]
indeed... I'd be most happy to see it happen for extraction... what would be the drawbacks of allowing that more generally?

**Comment by nikswamy** [comment]
actually, i stand corrected: we are already doing some of these rewrites using the monad and monad morphism laws. Just not everywhere. I can add it in this case.

**Comment by nikswamy** [comment]
The normalizer is also not yet reducing boolean primitive operators &&, || etc. @msprotz you've already added support for some primitive operators. If you add support for the boolean operators then I think your example will just work. I can work on making sure that the monadic rewrites that we do currently are done uniformly.

**Comment by msprotz** [comment]
Yes, I can do that. Thanks for looking into it!
