### ISSUE TITLE
Type inference bug when comparing refinement types after unfolding

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#760]
Shockingly, this program fails to type-check:

```
module Test
unfold let buf (a:Type0) = l:list a { l == [] }
val test : a:Type0 -> Tot (buf a)
let test a = admit #(buf a) ()
```

The problem is that we get a sub-typing check to `l:list a{l == []} <: buf a`. 
This turns into  `l:list a{l == []} <: b:buf a{True}`.
And then just `list a <: buf a` and `l==[] ==> True` ... which is clearly invalid.

**Comment by msprotz** [comment]
Do you not have a phase that expands all type abbreviations before checking subtyping?

**Comment by nikswamy** [comment]
the unfolding is done lazily, to avoid generating huge, redundant implications. e.g., when comparing `nat <: nat` you don't want to generate `forall x. x >=0 ==> x >= 0`. In this case, this lazy unfolding is not doing the right thing ... it's unfolding one side not enough before comparing stuff and forgetting some useful refinement information

**Comment by aseemr** [comment]
This works fine in master. Adding a testcase and closing the issue.
