### ISSUE TITLE
How to match types correctly? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#768]
I'm trying to write a function that matches the implicit type of the argument that it's called on; 

```
val matchtype: #t:Type -> e:t -> Tot nat
let matchtype #t e = match t with
  | bool -> 2
  | int -> 1
  | _ -> 3
```

here, `matchtype 2 = 2` , implying that the type int matches with bool. 

indeed, it seems that whatever order I place the matches in, the type always matches the first; 

```
val matchtype: #t:Type -> e:t -> Tot nat
let matchtype #t e = match t with
  | int -> 1
  | bool -> 2
  | _ -> 3
```

`matchtype "hello" = 1`

edit: changing the match statement to `match e with...` gives the same result!

**Comment by catalin-hritcu** [comment]
This is super dangerous stuff and is not possible in F\* without extra axioms. In particular, this breaks parametricity, and some of the security reasoning we do in F\* crucially relies on parametricity. It's also something that you won't be able to extract and execute in OCaml or whatever.

Now, if you don't care and want to do this with axioms, here is how to do it:
```
val matchtype: #t:Type0 -> e:t -> GTot nat
let matchtype #t e =
  if strong_excluded_middle (eq2 #Type0 t int) then 1
  else if strong_excluded_middle (eq2 #Type0 t bool) then 2
       else 3
```

As for why the code you wrote does what it does, that's really to be expected, since `int` and `bool` in that position are treated as variables. They start with lowercase and they are not the constructors of an inductive type (those start with upercase anyway), so there is no other way to interpret them in this context other than as variables.

**Comment by A-Manning** [comment]
Is there a better way to achieve ad-hoc polymorphism then?

**Comment by kyoDralliam** [comment]
Well there is the usual technique of having type witnesses using gadts, but it has the limitation to work only for a predefined finite set of types.

For example :
````
type witness_int_or_bool_or_unit : Type -> Type = 
  | IntWitness : witness_int_or_bool_or_unit  int
  | BoolWitness : witness_int_or_bool_or_unit bool
  | UnitWitness : witness_int_or_bool_or_unit unit

let matchtype (#t:Type) (e:t) (#w: witness_int_or_bool_or_unit t) =
    match w with
     | IntWitness -> 1 (* t = int*)
     |  BoolWitness -> 2 (* t = bool *)
     | _ -> 3 (* t is neither int nor bool (which means that it is unit...) *)
````

**Comment by catalin-hritcu** [comment]
> it's been stated explicitly that F* will have no haskell-style type classes.

That was a long time ago though and probably I phrased that too strongly. At this point, type classes are on our radar, but with no precise milestone. Probably won't happen in the next 6 months.

**Comment by nikswamy** [comment]
See `FStar/ulib/FStar.Integers.fst` for an example of ad hoc polymorphism.

**Comment by A-Manning** [comment]
@kyoDralliam I tried writing a type witness to achieve this, but I get an error when I try to evaluate a matchtype expression; 

```
type witness: Type -> Type =
  | Wint: witness int
  | Wbool: witness bool
  | Wunit: witness unit
  
val matchtype: #t:Type -> el:t -> #w:(witness t) -> Tot nat
let matchtype #t el #w = match w with
  | Wint -> 1
  | Wbool -> 2
  | _ -> 3


let x = matchtype 7
let y = x+2
```

I get an error on y 
`Failed to resolve implicit argument of type '(Mymodule.witness Prims.int)' introduced in ?39661 because Instantiation of implicit argument`

**Comment by nikswamy** [comment]
Hi, 

The type inferred for `x` is `#w:witness int -> Tot nat`

When defining `y = x+ 2`,  we need to find an instantiation of  the implicit `w` argument of `x`.  F\* will not find such an instantiation automatically. 

One way to understand why is to consider that, in general, there is no unique value to chose for the instantiation of `w`. In your particular example, it so happens that `Wint` is the only term of the expected type `witness int`, but it need not be the case, e.g., you might also have defined `Wint2: witness int`. 

I would write the program as:

```
val matchtype: #t:Type -> el:t -> w:witness t -> Tot nat
let matchtype #t el w = match w with
  | Wint -> 1
  | Wbool -> 2
  | _ -> 3


let x = matchtype 7 Wint
let y = x+2
```

**Comment by kyoDralliam** [comment]
@nikswamy I'm not exactly surprised that what I proposed does not work but is there anyway to activate some kind of proof search with the SMT ? I mean in the previous example, the SMT is able to prove without any problem that there is only one element inhabiting `witness int` e.g.
```
let invert_witness_int u : Lemma (requires (true)) (ensures (forall (w : witness int). w == Wint)) [SMTPat (witness int)] = ()
```

I had somewhat understood from a discussion in another issue that it was the role of `_` inside terms but it does the exact same thing as leaving the parameter implicit.

**Comment by nikswamy** [comment]
What you seem to be asking for is some kind of type-class mechanism. That's on our roadmap, but it's likely to take a few months.

**Comment by catalin-hritcu** [comment]
Started separate issue for adding type classes (#852).
