### ISSUE TITLE
Typechecking fails when combining pairs and options

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#77]
In the context
```
assume type a
assume type b
assume type q : a -> b -> Type
```

the following does not typecheck:
```
val bug : x:a -> y:b{q x y} -> option (r:(a * b){q (fst r) (snd r)})
let bug x y = Some (x, y)
```

This variant typechecks:
```
val ok : x:a -> y:b{q x y} -> r:(option (a * b)){is_Some r ==> q (fst (Some.v r)) (snd (Some.v r))}
let ok x y = Some (x, y)
```
but it seems less natural to me.

Without the option or without a pair, everything works as expected.

**Comment by nikswamy** [comment]
Seems to be resolved now. Closing it and adding bug77.fst to the test suite.
