### ISSUE TITLE
Poor error location

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#774]
```
let prf_extended_with_counterblocks (#i:id) (prf:PRF.state i) (x_1:PRF.domain_otp i)
				    (#len:nat) (plain:plainBuffer i len) (cipher:lbuffer len) 
				    (h0:mem) (h1:mem) = 
   safelen i len x_1
```

This reports an error at the binding site of `x_1` on the first line, rather than at its use. 

The actual edit needed is

```
let prf_extended_with_counterblocks (#i:id) (prf:PRF.state i) (x_1:PRF.domain_otp i)
				    (#len:nat) (plain:plainBuffer i len) (cipher:lbuffer len) 
				    (h0:mem) (h1:mem) = 
   safelen i len x_1.ctr
```

**Comment by nikswamy** [comment]
A simpler example:

```
module Test
let g (x:bool) = x
let f (x:int) = g x
```

A recent change to master causes an error to be reported at the binding occurrence of `x`, i.e., among the parameters to `f`, rather than at its use

**Comment by tahina-pro** [comment]
I think it is due to the new name resolution. I'm on it.

**Comment by tahina-pro** [comment]
I claim I have a solution. Please test using branch `taramana_774`

**Comment by tahina-pro** [comment]
Some other poor reporting problems may be due to range bugs in the parser (`rhs2` out of bounds, etc., after a short discussion with @kyoDralliam.)
I'm on it.

**Comment by tahina-pro** [comment]
Just pushed updates to `taramana_774`, fixing some parser bugs related to ranges out of bounds. Not merged into `master` yet.

**Comment by tahina-pro** [comment]
Now merged into `master`.
