### ISSUE TITLE
Produce Emacs-friendly error messages

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#78]
Emacs can help users navigate through error messages if they are in a certain format. I think it would be nice to support this format when a special flag is set, provided the current format is also useful for something, or just switch to the Emacs error format if that's not the case.

An alternative is to just ask everyone to tweak their Emacs by providing a command they can use:
http://www.emacswiki.org/emacs/CreatingYourOwnCompileErrorRegexp

**Comment by catalin-hritcu** [comment]
Managed to crop something up quickly for the current error format:
```
(add-to-list 'compilation-error-regexp-alist
 '("\\([a-zA-Z_-]*\\).fst(\\([0-9]+\\)\\,\\([0-9]+\\)-[0-9]+\\,[0-9]+)" 1 2 3))
```
There is still the problem that I get a file open dialog the first time I click on a certain file, but after I select the file things work well. Screenshots attached.
![screenshot from 2015-03-12 18 15 45](https://cloud.githubusercontent.com/assets/5850655/6623479/916eb9b8-c8e3-11e4-869a-95f063b8227a.png)
![screenshot from 2015-03-12 18 15 50](https://cloud.githubusercontent.com/assets/5850655/6623480/9170c730-c8e3-11e4-9f14-f97341213a6b.png)

**Comment by catalin-hritcu** [comment]
Edited the previous comment to fix the previous grouping error so that the extension is now also included. No more pesky dialogs.

**Comment by nikswamy** [comment]
i also changed the way in which we format the output ... removed the grouping

**Comment by catalin-hritcu** [comment]
Cool. The output is much more readable now.
![screenshot from 2015-03-13 07 59 09](https://cloud.githubusercontent.com/assets/5850655/6634304/7fe6bcae-c956-11e4-9db8-776b684e1208.png)
