### ISSUE TITLE
Improve the performance of extraction

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/FStar#780]
Out of memory reported by people at MSR Cambridge. More details to follow.

Need to profile the extraction with OCaml Spacetime.

**Comment by ad-l** [comment]
This has to be done on Linux as I haven't been able to build a mingw64 OCaml with Spacetime enabled.

Furthermore, libunwind is required to debug the zarith allocations

**Comment by tahina-pro** [comment]
Overhead for Spacetime makes extraction of even such simple examples as aesgcm crash and get out of memory (16Gb does not seem to be enough.)
Switching to Jacques-Henri Jourdan's statistical memory profiler, which is available only for OCaml 4.03.0
More info: https://github.com/jhjourdan/ocaml/tree/memprof

**Comment by nikswamy** [comment]
this was improved a lot at the end of December. The main fix was a better check to determine the stratum of a term during extraction.
