### ISSUE TITLE
Mutually defined inductive (and Projectors) are not correctly resolved

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#783]
Well this is no surprise since projectors are elaborated but the following code does not verify : 
```
noeq type u = | K : a:Type -> u
and v = | KK : t:u -> x:(K?.a t) -> v
```
The more problematic part is that it fails with an error `(Error) Data constructor or effect K not found` which is not understandable for anybody who does not have a knowledge of the current implementation of discriminators.

Multiple fixes are possible depending on whether we want to allow this syntax or not.
In all cases we should track the mutually defined constructors to either give ameaningful error or resolve correctly the discriminator/projector.

More surprisingly, inlining the discriminator does not help and fails with the same error : 
```
noeq type u = | K : a:Type -> u
and v = | KK : t:u -> x:(match t with | K a -> a) -> v
```

The situation of the projectors is a little particular but I wonder if it wouldn't be nice to include them in the same bundle as the inductive type they are defined for.

**Comment by tahina-pro** [comment]
Coq (8.5pl2) does the same thing:
```
Inductive list' (a: Type): Type :=
| Nil'
| Cons' (hd: a) (tl: list' a) (_0: tl = Nil')
.
```
Error: The reference Nil' was not found in the current environment.

**Comment by kyoDralliam** [comment]
After some discussion with @tahina-pro  it seems reasonable to forbid a single inductive from having access to the previously defined  constructors and the case of mutually defined inductives can be elaborated to the case of a single inductive. So leaving things as is.

**Comment by nikswamy** [comment]
This is not a bug. adding this would require support for some form of induction/recursion
