### ISSUE TITLE
Dependency analysis confused by effect name

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#784]
When having an unrelated file named `M.fst` in the working directory, I got a spurious circular dependency error:

`The cycle is: fstar.functionalextensionality -> fstar.predicateextensionality -> fstar.tset -> fstar.heap -> fstar.st -> fstar.all -> m -> prims -> fstar.mul`

It seems that the analysis is confused because of `effect M` defined in `ulib/prims.fst` and thinks that `M.fst` in the working directory is a dependency of `prims`. Same happens when files named `Tot.fst`, etc. Easiest way to reproduce is to `touch M.fst` and then run F* in any other file in the same directory.

**Comment by tahina-pro** [comment]
Fixed: data constructors no longer generate any such spurious dependencies on modules with the same name, thanks to the new syntaxes `?.` and `.(` 
Merged into master and pushed.

**Comment by msprotz** [comment]
Funny, I just had this issue this very morning with Kenji
