### ISSUE TITLE
Write effects in UF1CMA are not usable

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#788]
I find this part of the post-condition of UF1CMA.mac to be
unusable.

```let modifies_bufs_and_ref (#a:Type) (#b:Type) (#c:Type)
  (buf1:Buffer.buffer a) (buf2:Buffer.buffer b) (ref:reference c) h h' : GTot Type0 =
  (forall rid. Set.mem rid (Map.domain h.h) ==>
    HH.modifies_rref rid !{Buffer.as_ref buf1, Buffer.as_ref buf2, HS.as_ref ref} h.h h'.h
    /\ (forall (#a:Type) (b:Buffer.buffer a).
      (frameOf b == rid /\ live h b /\ disjoint_2 b buf1 buf2
      /\ disjoint_ref_1 b (HS.as_aref ref)) ==> equal h b h' b))
```

I think you may have been relying on the intuition that the
domain of references of each heap region is disjoint from other
heap regions. As we discussed the other day, this is not the way
it is setup.

As such, the first part of the `modifies_bufs_and_ref` predicate
essentialy says that every region in the memory may have changed,
since `!{Buffer.as_ref buf1, Buffer.as_ref buf2, HS.as_ref ref}`
can actually be part of the domain of every region.

The second part of the predicate seems to be trying to recover
that buffers that do not overlap with buf1, buf2 and ref remain
unchanged, which may help for buffers, but it does not help for
other non-buffer references.

Looking into the library, I find that `Buffer.modifies_bufs_and_refs`
is also stated in a similar style and hence is similarly unusable.

How about instead stating the write-effect of UF1CMA.mac like so

```
let modifies_bufs_and_ref (#a:Type) (#b:Type) (#c:Type)
    (buf1:Buffer.buffer a)
    (buf2:Buffer.buffer b)
    (reff:HS.reference c{pairwise_distinct (Buffer.frameOf buf1) (Buffer.frameOf buf2) HS.(reff.id)})
    (h0 h1:mem) : GTot Type0 =
 let open FStar.HyperStack in
 let open FStar.Buffer in
 HS.modifies (Set.as_set [frameOf buf1; frameOf buf2; reff.id]) h0 h1 /\
 HS.modifies_ref reff.id !{HS.as_ref reff} h0 h1 /\
 Buffer.modifies_buf_1 (frameOf buf1) buf1 h0 h1 /\
 Buffer.modifies_buf_1 (frameOf buf2) buf2 h0 h1
```

**Comment by nikswamy** [comment]
Note, in branch c_relational-ci_r3 we have a regression in Crytpo.AEAD.Encoding line 463 (      assert(Buffer.modifies_buf_0 h.tip h h5);
)

This is since bc7494001caf3cfa83737aafac1e08eae51ebad6

**Comment by s-zanella** [comment]
The above modifies clause works for `UF1CMA.mac`.
`UF1CMA.update` modifies a buffer and a reference that live in the same region, so I used this variant:

```F#
let modifies_buf_and_ref (#a:Type) (#b:Type)
  (buf:Buffer.buffer a)
  (ref:reference b{frameOf buf == ref.id}) h0 h1 : GTot Type0 =
  HS.modifies_one ref.id h0 h1 /\
  HS.modifies_ref ref.id !{HS.as_ref ref, Buffer.as_ref buf} h0 h1 /\
  (forall (#t:Type) (buf':Buffer.buffer t).
    (frameOf buf' == ref.id /\ Buffer.live h0 buf' /\
    Buffer.disjoint buf buf' /\ Buffer.disjoint_ref_1 buf' (HS.as_aref ref)) ==>
    equal h0 buf' h1 buf')
```
I confirmed this worked before merging `c_relational-r3_ci`.
Waiting for a green on my branch before pushing (we will only notice any regressions from merging `c_relational-r3_ci` once CI re-runs full verification).
These changes should be ported to HaCl*.
