### ISSUE TITLE
opam installer installs too-old version of ocaml

### ISSUE THREAD

**Issue by greenrd** [FStarLang/FStar#795]
I followed the instructions at http://opam.ocaml.org/doc/Install.html to install opam, i.e.

    wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin

but this installs ocaml 4.02.1 which is slightly too old, and fails to compile F*.

I actually have a suitable version of ocaml installed via my system's package manager (I'm on Fedora Linux) but it doesn't get used because opam puts its own directory first on the `PATH`.

I tried reordering the `PATH` to put the opam directory last, but then I get this error instead:

```
File "lib/ml/FStar_Char.ml", line 1:
Error: The files /usr/lib64/ocaml/pervasives.cmi
       and /home/robin/.opam/4.02.1/lib/batteries/batChar.cmi
       make inconsistent assumptions over interface CamlinternalFormatBasics
Command exited with code 2.
Compilation unsuccessful after building 22 targets (6 cached) in 00:00:00.
Makefile:93: recipe for target 'fstar.exe' failed
```

**Comment by catalin-hritcu** [comment]
OCaml 4.02.1 is indeed too old to compile F*. For the second error you can try cleaning up `src/ocaml-output` with `git clean -fdx`.
