### ISSUE TITLE
Allow .fst to implement .fsti with `include`

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/FStar#798]
We would like to make the following work:

A.fsti
```
module A
val i: int
```

B.fst
```
module B
let i = 18
```

A.fst
```
module A
include B
```

This will allow one implementation (here B) to implement several interfaces at the same time.

**Comment by tahina-pro** [comment]
There is a conceptual leap forward here: so far, `include` has been thought as a namespace rewriting scheme rather than textual inclusion. Thus, consider the following case:
* B.fst: `module B  let x = 18`
* A1.fst: `module A1  include B`
* A2.fst: `module A2  include B`
* C.fst: `module C  let y = A1.x`
Then, wherever `A1.x` and `A2.x` are requested in client code (e.g. C), they will actually be replaced with `B.x`. Then, if we add the following interfaces:
* A1.fsti: `module A1  val x: int {x > 10}`
* A2.fsti: `module A2  val x: int {x > 5}`
Then, it is not clear whether we should still perform the replacement before type-checking the client code, i.e. whether `A1.x` in C should be replaced with `B.x` or not. (Replacement should have been performed before extraction, of course, but how early is not clear.)

FWIW: currently, adding the interfaces fail because interleaving is performed even before name resolution; `include` declarations are not recognized as declarations of terms that should be interleaved with their type declarations in the interface.

Similarly, it is not clear how to treat `include` in interface files, but this is another story.

**Comment by nikswamy** [comment]
This feature request is a significant redesign. Marking it wontfix
