### ISSUE TITLE
Problem parsing less-than (<) (resolved by --fs_typ_app); infix operator support

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#80]
We discussed hiding the `f<t>` syntax for type instantiation under a flag so that the less-than operator (`<`) can parse properly.

**Comment by nikswamy** [comment]
Added a --fs_typ_app flag. You need to provide that if you want to write t<t1, t2> etc.
Otherwise, < is just the less than operator, by default.

**Comment by catalin-hritcu** [comment]
So can this be closed now?
