### ISSUE TITLE
Support dependent records (with better syntax)

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#801]
kyod [1:36 PM] 
I guess it must have been discussed at some point but are there any plans to implement *dependent* records ?

karthik [1:39 PM] 
ah, an old request.

[1:40]  
Indeed, having dependent constructors with named projections is very close to having dependent records.

[1:41]  
We could ask that F* compile some of these constructors to records in ML/ structs in C, if that’s what you want.

[1:41]  
If the question is one of expressiveness/proofs, what would you like to do with dependent records that you cannot do with constructors?

kyod [1:45 PM] 
Well in fact I just realised after writing the request that we already have them as single constructor datatypes (which is also the way record are implemented under the hood)

[1:46]  
so we are only lacking the syntax or over-restricting the syntax of records

new messages
nik [11:35 PM] 
yes, they are single constructor datatypes

[11:36]  
the syntax for records is anyway a bit weak in F*

[11:36]  
e.g., you cannot write `f {x=0; y=1}` (edited)

[11:38]  
instead we require `f ({x=0; y=1})`

**Comment by catalin-hritcu** [comment]
This is a frequently occurring feature request, for instance:
https://lists.gforge.inria.fr/pipermail/fstar-club/2017/000103.html

**Comment by mtzguido** [comment]
Done now, see discussion in #1184.
