### ISSUE TITLE
Is F*'s prop type the same as Coq's Prop type?

### ISSUE THREAD

**Issue by HarmlessVolcano** [FStarLang/FStar#802]

**Comment by kyoDralliam** [comment]
Not exactly even though they are intended for the same kind of use. Coq's Prop is an impredicative universe whereas F*'s prop is defined as a subtype of a predicative universe : 
```type prop = a:Type0{ forall (x:a). x === () }```

The `===` is (extensional) heterogeneous equality which means that an F* prop type is a subsingleton (it has at most one element) . Typical F* prop are True (aka unit), False or a squashed type (a refinement of unit).

**Comment by catalin-hritcu** [comment]
Don't see how `True` and `False` defined as inductives could be props with respect to this definition though. On the `catalin_prop` branch I have already switched to your better definition of `prop` that would allow this (while also not relying on heterogenous equality):
https://github.com/FStarLang/FStar/blob/catalin_prop/ulib/prims.fst#L127
