### ISSUE TITLE
Have some automated tests for the interactive mode in CI

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#805]
That is not very hard, and this would
1) document the protocol, and
2) prevent me from breaking things because I forgot that I also had to try out the interactive mode :).

Not sure who would like to test this. @sishtiaq perhaps?

**Comment by nikswamy** [comment]
It could be as simple as `cat transcript | fstar --in`, for some saved transcript

**Comment by sishtiaq** [comment]
Yes, can take it on. Priority: High, Med, Low?

**Comment by msprotz** [comment]
It is just a matter of adding this somewhere in a Makefile, in a directory that contains "test.fst"

(where test.fst contains just "module Test")

```
echo "#push 1 0
module Test
#end #done-ok #done-no" | fstar --in test.fst
```

So, high -- I'd love to see this under CI as we start experimenting more with the interactive mode.
