### ISSUE TITLE
Wish list for the standard library

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#816]
This aims at establishing a wish-list for functionalities that are expected from the standard library.

For starters:

- [ ] `map2` on lists (for `FStar.List.Tot.fst`, already in `FStar.List.fst`)
- [ ] Implement all functions from `FStar.List.fst` in `FStar.List.Tot.fst`
- [ ] No fold for sequences?
- [ ] unique on lists containing some eqtype

**Comment by msprotz** [comment]
Does any verification code use List? It seems to me like List is a compiler-only module that shouldn't be in ulib/, and List.Tot is the one we want for verification purposes (possibly "stealing" functions from List).

**Comment by catalin-hritcu** [comment]
There are plenty of related issues: #695, #637, #551

**Comment by aseemr** [comment]
I added these to #551, closing this issue.
