### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by olleharstedt** [FStarLang/FStar#817]
Got this error message:

    Error: Unexpected error; please file a bug report, ideally with a 
    minimized version of the source program that triggered the error.
    Invalid_argument("map2: Different_list_size")

My version:

```
~/kod/fstar$ ./bin/fstar.exe --version
F* 0.9.3.0-beta1
platform=Linux_x86_64
compiler=OCaml 4.03.0
date=2016-09-07T19:58:05+02:00
commit=9572684
```

The program:
```
module Typestate2

type state = 
  | Open
  | Closed

type file =
  | File : name:string -> state:ref state -> file

val newFile : name:string -> ST file
let newFile name =
  let c = ST.alloc Closed in
  File name c
```

Complete error message:

```
~/kod/fstar$ ./bin/fstar.exe examples/typestate2.fst
./examples/typestate2.fst(10,32-10,36): Expected type "Effect";
got type "(pre:FStar.ST.st_pre -> post:(uu___:FStar.Heap.heap -> Tot (FStar.ST.st_post Typestate2.file)) -> Tot Effect)"
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Invalid_argument("map2: Different_list_size")
Error: 1 errors were reported (see above)
```

**Comment by kyoDralliam** [comment]
I don't get the same error as you have on master but a more informative one : 
```
(Error) Expected type "Effect"; but "(ST file)" has type "(pre:st_pre -> post:(uu___:heap -> Tot (st_post file)) -> Tot Effect)"
 (Error) Effect constructor is not fully applied; expected 3 args, got 1 args, i.e., ST (file)
1 error was reported (see above)
```

And indeed you forgot to put a pre- and post-condition  after `ST file`. I guess what you want to use is `St` (which does not have any condition on the computation) and not `ST`.

**Comment by olleharstedt** [comment]
Thank you. Yes, I know it's an error in the code.

**Comment by olleharstedt** [comment]
I guess this can be closed if it's fixed in master.

**Comment by olleharstedt** [comment]
Forgive me a question, but if I use `St` I cannot use refinement types? Like `f : St file{isClosed f}`?

**Comment by jkzinzindohoue** [comment]
Hi,

You could use refinements on the result, you would have to write it `St f:file{isClosed f}`.
However I don't know which ST memory model you are using, but note that `St type` stands for `ST type (requires (fun h -> true)) (ensures (fun h r h' -> true))` which is often not very useful. If you have any memory-related condition you will not be able to express it. Which may make your code impossible to typecheck.

**Comment by olleharstedt** [comment]
Hm, I still get Parser error by this: 

    val newFile : name:string -> St f:file{isClosed f}

    Syntax error: Parsing.Parse_error

Same version of F* as above.

**Comment by olleharstedt** [comment]
Maybe you can also explain this error message for me?

```
type file =
  | File : name:string -> state:ref state -> file

val newFile : name:string -> St (file (requires (fun h -> true)) (ensures (fun h r h' -> true)))

Expected a function;
got an expression of type "Type"

```

**Comment by beurdouche** [comment]
In the "single heap" ST memory model, the following code typechecks:
```
module Test

type state = 
  | Open
  | Closed

type file =
  | File : name:string -> state:ref state -> file

val newFile : name:string 
-> ST file 
  (requires (fun h -> true)) 
  (ensures (fun h r h' -> true))

let newFile name =
  let c = ST.alloc Closed in
  File name c
```

Note the fact the effect is `ST` and not `St`, and that the parenthesis do not contain the type `file` . 
As @jkzinzindohoue mentioned
```
-> ST file 
  (requires (fun h -> true)) 
  (ensures (fun h r h' -> true))
```
and `St file` are equivalent.

**Comment by beurdouche** [comment]
And to answer your second question:
You might want to add a refinement over the type `file` like this:
```
-> ST (f:file{isClosed f})
  (requires (fun h -> true)) 
  (ensures (fun h r h' -> true))

```

**Comment by olleharstedt** [comment]
Thanks for your help! I get this error message from your last tip:
```
Expected a ghost expression;
got an expression "(Prims.b2t (Typestate2.isClosed f))" with effect "FStar.ST.STATE"
```

**Comment by beurdouche** [comment]
What is your definition of `isClosed`, the error message suggest you are trying to use a function defined in the ST monad while functions in refinements should be either in Ghost or Pure

**Comment by olleharstedt** [comment]
Ah! Yes, `isClosed` reads from state in file:

```
let isClosed file = !file.state = Closed
```
