### ISSUE TITLE
The OPAM package of F* does not remove fstar.exe from bin/

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#819]
Likely to cause very high confusion for students who move from OPAM-F* to source-F*.

**Comment by msprotz** [comment]
@beurdouche if you're interested... happy to help while I'm around

**Comment by kyoDralliam** [comment]
Do you mean when removing the opam package ?

**Comment by msprotz** [comment]
yes

**Comment by beurdouche** [comment]
I'll try to look at that early next week

**Comment by catalin-hritcu** [comment]
This seems to be doing the right thing now:
https://github.com/ocaml/opam-repository/blob/master/packages/fstar/fstar.0.9.7.0-alpha1/opam#L38
