### ISSUE TITLE
Tutorial: use Madoku file fragments + some scripts to make things maintainable

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#82]
Madoku supports fragments, as explained in the documentation:
http://research.microsoft.com/en-us/um/people/daan/madoko/doc/reference.html#sec-includefrag
so we should import all our code from executable files.

We will need a bit of scripting for automatically producing the exercise files from the solution files.

**Comment by markulf** [comment]
This seems to work well.

**Comment by catalin-hritcu** [comment]
Yes, importing file fragments works OK if you use C-style line comments ("//"). Longer term I plan to go the other way around and export the code for both exercises and solutions from Madoko, as discussed in the "Literate programming in Madoko" thread (http://lists.gforge.inria.fr/cgi-bin/mailman/private/fstar-priv-club/2015/000344.html)

**Comment by catalin-hritcu** [comment]
Closing this since now I have other ideas about how to do this better (explained in the mailing list thread linked above).
