### ISSUE TITLE
Wish list: F*'s normalizer supported operator

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/FStar#822]
This thread records operators/features that we wish the normalizer to support.

- [ ] shift operators for machine integers
- [ ] logical operators (`/\, \/, ==>` etc.)
- [ ] `FStar.Seq` ?

**Comment by kyoDralliam** [comment]
I would say that rather than having support (which kind ?) for logical operators in the normalizer, we would like to have support for arbitrary squashed value in the SMT encoding.

**Comment by jkzinzindohoue** [comment]
- [ ] bitwise operator (&, |, ^, ~) on mathematical and machine integers

**Comment by nikswamy** [comment]
machine integer ops and logical operators are supported in the normalizer. Seq is not---it is intentionally abstract.
