### ISSUE TITLE
Explicit universes do not work well with signatures/interfaces

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#826]
Using explicit universes both in the interface and implementation leads to some errors for example :
```F#
val raise_t : Type 'ua -> Type u#(max 'ua ('ub + 1))
let raise_t (a:Type 'ua) : Type u#(max 'ua ('ub + 1)) = x:raise0 'ua 'ub a{Ret? x}
```
 
`(Error) Expected type "Type('uu___2040)"; got type "Type('ua)"`

Current solution is to drop the annotations in the implementation and hope that the signature will contain enough information for typechecking.

**Comment by catalin-hritcu** [comment]
Is this maybe an instance of #604?

**Comment by mtzguido** [comment]
I think this works now. This is my current repro (I took `raise0` from `FStar.Universe`)


The original example
```fstar
noeq type raise0 (a : Type u#a) : Type u#(max a b) =
| Ret : a -> raise0 a

val raise_t2 : Type u#ua -> Type u#(max ua (ub + 1))
let raise_t2 (a:Type u#ua) : Type u#(max ua (ub + 1)) = x:(raise0 u#ua u#ub a){Ret? x}
```
gives
```
Poly2.fst(7,56-7,86): (Error 54) Type u#(max ua ub) is not a subtype of the expected type Type u#(max ua (1 + ub))
```
Which makes sense, since the application of `raise0 u#ua u#ub` is returning a `Type u#(max ua ub)`, which does not match the ascripted `Type u#(max ua (ub + 1))`.

One can fix the `ub`:
```fstar
let raise_t2 (a:Type u#ua) : Type u#(max ua (ub + 1)) = x:(raise0 u#ua u#(1+ub) a){Ret? x}
```
or leave them up to inference:
```fstar
let raise_t2 (a:Type u#ua) : Type u#(max ua (ub + 1)) = x:(raise0 a){Ret? x}
```

**Comment by aseemr** [comment]
This is working as Guido has mentioned, closing the issue.
