### ISSUE TITLE
Needed to add an assumption in Crypto.AEAD.Wrappers.CMA to pass a regression test

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#834]
```
let mac #i st #aadlen aad #txtlen plain cipher_tagged ak acc h_init =   
   let tag = Buffer.sub cipher_tagged txtlen MAC.taglen in
   let h0 = get () in
   recall_aead_liveness st;
   mac_wrapper ak acc tag; 
   let h1 = get () in
   assume (enc_dec_liveness st aad plain cipher_tagged h1);
   intro_mac_is_set st aad plain cipher_tagged ak acc h_init h0 h1
```

Added the assumption here to pass regressions in nik_default_effects

**Comment by nikswamy** [comment]
something for us to investigate ... bizarre failure

**Comment by nikswamy** [comment]
commit c545db407fa16a2a1a533717abb1438c58e793b0

**Comment by s-zanella** [comment]
This code typechecks for me without the added `assume` clause in `master` (commit 782cb8f) with Z3 4.5.0. Can someone else try and confirm there is no regression?

**Comment by s-zanella** [comment]
This regression is now fixed in hacl-star (https://github.com/mitls/hacl-star/blob/master/secure_api/aead/Crypto.AEAD.Wrappers.CMA.fst#L277).

Most code in `examples/low-level` is now stale. We'll remove it in favour of `hacl-star` (see #928).
