### ISSUE TITLE
Issues with the surface printer

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#835]
- [ ] strings are not correctly printed
- [ ] fsdoc insert more lines than needed
- [ ] comments are not correctly inserted between mutually recursive type declarations

The string issue also depends on the behaviour of the lexer.
The 2 next issues need more range information in the surface AST to be fixed.

**Comment by victor-dumitrescu** [comment]
It has been superseded. A more up to date status for the printer is indeed tracked in #1298. Closing.
