### ISSUE TITLE
remove the date from FStar_Version.ml

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#837]
this causes the entire dependency graph to be invalidated, and then ocamlbuild doesn't buy us any time

**Comment by catalin-hritcu** [comment]
the commit hash is a similar business though?

**Comment by msprotz** [comment]
pretty similar, although across a single development cycle the commit hash doesn't change

**Comment by msprotz** [comment]
from slack: it's weird that FStar_Version is at the leaf of the dependency graph. I suspect it's called from Fstar_Util instead of being called from Fstar_Fstar

**Comment by msprotz** [comment]
https://github.com/FStarLang/FStar/commit/e43fa6af
