### ISSUE TITLE
Parsing: what's the harm in naming function type results even when they are not refined?

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#84]
Some people in the school were confused by not being able to name results even when they don't have a refinement. They were getting incomprehensible error messages referencing the next tine. I don't think it would be any harm to allow: `a:int -> b:int` as a valid type; in fact it seems very natural, and it often occurs when evolving programs (e.g. the user removed a refinement to see if at least the basic type goes through, or the refinement is now in a type definition, like `nat`).

**Comment by nikswamy** [comment]
This is now permitted a465a241a90e064faa347f9deacde8eec12a1c70
