### ISSUE TITLE
Bad Z3 encoding for FStar.SquashProperties: unknown constant

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#844]
I'm filing this separately since it seems distinct from #836. Although the Z3 error is `unknown constant` in both cases, the problem in `FStar.SquashProperties` seems to be in the encoding of typing (while #836 seems caused by `hasEq`)
```
[hritcu@detained ulib]$ fstar.exe --log_queries FStar.SquashProperties.fst                                                        (git)-[master] 
unknown(0,0-0,0): (Warning) FStar.SquashProperties: Unexpected output from Z3: (error "line 61387 column 43: unknown constant @x8")
```
Causes a query containing this (at a slightly different line number #843)
```
;;;;;;;;;;;;;;;;typing_Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5
(assert (!
         (forall ((@x0 Term) (@x1 Term) (@x2 Term))
                 (! (HasType (Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5 @x0
                                                                      @x1
                                                                      @x2)
                             (Tm_arrow_b8db595f71cb8a3c4a9f6444e8605917 @x8
                                                                        @x7
                                                                        @x1
                                                                        @x2))
                    
                    :pattern ((Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5 @x0
                                                                       @x1
                                                                       @x2))))
         :named typing_Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5))
;;;;;;;;;;;;;;;;interpretation_Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5
(assert (!
         (forall ((@x0 Term) (@x1 Term) (@x2 Term) (@x3 Term))
                 (! (= (ApplyTT (Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5 @x1
                                                                         @x2
                                                                         @x3)
                                @x0)
                       @x1)
                    
                    :pattern ((ApplyTT (Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5 @x1
                                                                                @x2
                                                                                @x3)
                                       @x0))))
         :named interpretation_Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5))
```

**Comment by catalin-hritcu** [comment]
Minimized this a bit and discovered that the problem is in the typing for the following innocuous constant lambda `(fun _ -> e)` in the following context:
```
val l1: (a:Type0) -> (b:Type0) -> GTot (squash (retract_cond (pow a) (pow b)))
let l1 (a:Type) (b:Type) =
   bind_squash (excluded_middle_squash (retract (pow a) (pow b)))
	      (fun (x:c_or (retract (pow a) (pow b)) (~ (retract (pow a) (pow b)))) ->
	         match x with
		 | Left (MkR f0 g0 e) ->
		   return_squash (MkC f0 g0 (fun _ -> e) (* <- this lambda causes the problem *))
		 | Right nr ->
                   magic())
```
Minimized code is in `examples/bug-reports/bug844.fst` for further investigation

**Comment by catalin-hritcu** [comment]
The funny part is that in the assert above (typing) the arity of `Tm_abs_f4641a48822d163aa42ca0a2d86ce0b5` is wrong, but in the assert below (interpretation) it's not.

**Comment by aseemr** [comment]
Verifying ulib/FStar.Struct.fst gives a similar error message: STDERR: unknown(0,0-0,0): (Warning) FStar.Struct: Unexpected output from Z3: (error "line 138962 column 43: unknown constant @x26").

**Comment by aseemr** [comment]
IfcDelimitedRelease.reify also gives an SMT encoding error when verified without hints.

**Comment by aseemr** [comment]
Similar error in List.Tot.Properties (I am just noting these errors down, when we resolve them, they may turn out to be different issues, in which case we could file separate issues).

**Comment by aseemr** [comment]
All errors except IfcDelimitedReleaseReify are fixed in the commit: https://github.com/FStarLang/FStar/commit/2aeae34841f0723d0fb7c04f5e8d64940fa8ec95.

The problem was in the encoding of abstractions. The encoding was not taking into account the free variables of the return type, because of which the typing axiom had unbound variables.

Closing this issue. Will track IfcDelimitedReleaseReify using #969.
