### ISSUE TITLE
Dependencies between SMT obligations

### ISSUE THREAD

**Issue by shaolintl** [FStarLang/FStar#846]
@nikswamy @protz @catalin-hritcu 

When trying to execute fstar, some of the obligations which are asked to be discharged depend on a declaration in a previous obligation. 

When running with single-core, the Z3 scheduler accumulates all declarations and therefore, the problem does not exist.
When running with multi-core>1, the (full) theory given to Z# sometimes miss declarations generated earlier.

These declarations appear in the theory of some obligations but not in all. Maybe it is because of backtracking?

To reproduce, try it on fstar/examples/algorithms/MergeSort.fst

It works (still has some error but irrelevant I think) without the n_cores flag and with n_cores > 1, it reports errors like:
unknown(0,0-0,0): (Warning) MergeSort: Unexpected output from Z3: (error "line 61433 column 33: unknown constant x_9a691d092aa1033ae30e6c0e5e60237c_0")

Note that this constant is declared in several previous obligations.

**Comment by shaolintl** [comment]
After experimenting a bit, it seems that such errors are raised when previous obligations fail to be discharged. It may be that the facts fail and therefore are not added to the theory but that newer obligations depend on definitions in these obligations? I will test it a bit more.

**Comment by shaolintl** [comment]
Attached are two Z3 input files. The first, no. 11 declares label_15. Running z3 on this file returns unknown. The second, no. 14 returns unknown and also raise an error that it could not find the declaration of label_15. When adding this declaration to no. 14, Z3 returns unsat. 

[z.zip](https://github.com/FStarLang/FStar/files/783439/z.zip)

The problem generating these files is:
fstar/examples/low-level/crypto$ fstar --fstar_home ../../.. --n_cores 4 --max_fuel 4 --initial_fuel 0 --max_ifuel 2 --initial_ifuel 0 --z3rlimit 20  --use_hints --include ../../../ulib/hyperstack --include hacl --__temp_no_proj Crypto.Symmetric.MAC Crypto.Indexing.fst

It seems that the problem is with adding label declaration to some SMT obligations and using them in others, without declaring them. Probably, because the obligation in which we stated the declaration was not discharged (returned with unknown), the declaration was not added to the theory.

Will keep checking.

**Comment by shaolintl** [comment]
Still could not find the problem but confirmed it by shutting off the labels completely. With no labeling mechanism, it seems that multi core works fine.

I will come back to this problem later when I understand the encoding better.

**Comment by wintersteiger** [comment]
The problem here is that, when a query fails, the result callback schedules new queries with alternative configurations (try_alt_configs in FStar.SMTEncoding.Solver.fs). At the point in time at which the callback is executed however, the background theory has changed and the old state/theory/query can not be reconstructed anymore (not cheaply anyways). The solution to this problem is either to disable try_alt_configs altogether, or to remember the old background theory/scopes (see fix in https://github.com/FStarLang/FStar/commit/82fc9cd52a278c940c2c87c15bf6bd61fa214d06).

**Comment by wintersteiger** [comment]
Actually, overwriting Z3.fresh_scope wasn't a particularly bright idea; better fix in https://github.com/FStarLang/FStar/commit/c88bcef3860b0f0921af877da64d6e2d9a0dc50f.
