### ISSUE TITLE
Revive fsdoc overnight run

### ISSUE THREAD

**Issue by sishtiaq** [FStarLang/FStar#847]
Last run a month ago.

**Comment by beurdouche** [comment]
@sishtiaq ! Nice ! The doc just got generated, thanks ;)

FWI, I just noticed the following "Unidentified product" in the generated documentation...
```
val uint8_to_uint64:Unidentified product: [a:U8.t] (Tot (b:U64.t:{=(U64.v b, U8.v a)}))
```

**Comment by sishtiaq** [comment]
I did that by hand. Well, I ran the script manually. It's still not running on the build-machine. Investigating...

The "Unidentified product" is #831. I plan to rewrite fsdoc to use the new, proper pretty-printer. It'll go away then.

**Comment by beurdouche** [comment]
Ok. please feel free to tell me if you need to beta-test or anything...

**Comment by sishtiaq** [comment]
Thanks! Could you do that, please? Just run .ci/fsdoc.sh. You'll need to provide a value for PAT (generate a throw-away PAT from your GitHub settings). At least it'll prove that it works for not-just-me. The problem is probably with the Linux container the script runs in.

**Comment by beurdouche** [comment]
```chmod +x fsdoc.sh 
bbeurdouche@bmpi:/opt/fstar/.ci$ ./fsdoc.sh 
Running fsdoc in /opt/fstar/.ci
./fsdoc.sh: line 21: pushd: ulib: No such file or directory```
There is probably already a problem of rights on linux, looking at line 21...

**Comment by beurdouche** [comment]
Ok, `pushd` and `popd` don't run on my machine, what are those ?

**Comment by sishtiaq** [comment]
It's meant to be run from the repo top-level:
```
FStar> chmod u+x .ci/fsdoc.sh
FStar> .ci/fsdoc.sh
```

**Comment by beurdouche** [comment]
Ok, my bad, I mistakenly interpreted `pushd` `popd` as valid command outside a bash script
`sed: 1: "index.md": command i expects \ followed by text`

**Comment by beurdouche** [comment]
Ok this was the classic `GNU sed` vs `BSD sed` on OSX. (on OSX gsed works instead)

**Comment by beurdouche** [comment]
Well, seems to work for me, the only thing was to use `gsed` instead of `make`. I can update the script to check for the first on OSX as we do for F* if you want

**Comment by s-zanella** [comment]
You can use `sed -i.bak`, which works both in GNU and BSD sed.

**Comment by sishtiaq** [comment]
Currently stuck 'cos, on the docker container, these files:
```
root@355bf985d524#: ls /LinuxAgent/_work/5/s/fstarlang.github.io/.git/objects/pack
cifsc19  cifsc1e
```
can't be rm-ed (not even `sudo rm -f`!) by the nightly build job.

**Comment by msprotz** [comment]
Can we close this one @sishtiaq ?

**Comment by sishtiaq** [comment]
Closed.
