### ISSUE TITLE
Error: Unbound module Prims

### ISSUE THREAD

**Issue by Rallemus** [FStarLang/FStar#856]
I'm trying to generate OCaml code from the file RPC.fst in /examples/crypto/ and I get the following error:

`Error: Unbound module Prims`

Here's the relevant  snippet from the makefile I've written:
```makefile
ocaml: out RPC.fst
  $(FSTAR) --odir out --codegen OCaml --codegen-lib FStar RPC.fst --include $(LIB)
  ocamlopt out/RPC.ml $(LIB)/ml/prims.ml -o RPC.exe
  ./out/rpc.exe
```

Am I missing something obvious?

**Comment by s-zanella** [comment]
Looks like this was broken for a while.

There was an `RPC.exe` target in the Makefile in the `/examples/crypto/` folder, but it hadn't been ported to the _universes_ release of F*.

Should be fixed by 122aebc37d7d259efdbd4d33087cd953fd7cc8d4, once I get green to merge it into master.

**Comment by catalin-hritcu** [comment]
@s-zanella  Please add this to the Makefile? Code that's not in the Makefile will get out of date and in fact should be removed from the repo if it can't be easily fixed.

**Comment by s-zanella** [comment]
Good idea. 
I will clean up the mess in `examples/crypto` and add everything I can to the target that CI uses.

**Comment by s-zanella** [comment]
Running the tests would require to build OpenSSL from source in CI, which is prohibitively expensive. I modified the Makefile to run everything up to extraction.
