### ISSUE TITLE
Inconsistent extraction of Prims.int (should extract to bigint)

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#86]
The tutorial mentions that we have "A well-founded partial order on all terms". What exactly is this order on integers? I'm completely sick of our equivocation about the nature of integers. This is just wrong and undermines the credibility of what we're doing!

**Comment by nikswamy** [comment]
We now have `lib/int32.fst` and `examples/unit-tests/testint32.fst`. The `Int32` library soundly models integer overflow semantics. The `Prims.int` type is for mathematical integers. We will eventually compile programs using it to use `bigint`.

**Comment by markulf** [comment]
We also ran into this problem in `contrib/Platform/fst/Bytes.fst` and when compiling `examples/crypto/rpc.fst`. See also https://github.com/FStarLang/FStar/issues/314 .

The following function in `Bytes.fst` demonstrates the problem nicely:

```
val repr_bytes : nat -> Tot nat
 let repr_bytes n =
     if n < 256 then 1
     else if n < 65536 then 2
-    else if n < 16777216 then 3
+    (*else if n < 16777216 then 3
     else if n < 4294967296 then 4
     else if n < 1099511627776 then 5
     else if n < 281474976710656 then 6
-    else if n < 72057594037927936 then 7
+    else if n < 72057594037927936 then 7    *)
     else 8
```

1. Should it have a refinement that restricts it to `nat`'s representable as 8 bytes?
2. We need 64 bit integers to verify sequence numbers in the TLS record layer
3. Extraction of RPC currently works only if constants are small. the + patch/hack.

**Comment by s-zanella** [comment]
Just to document that we rolled back to an assumed `repr_bytes`, with a partial specification for integers up to 2^64-1.

I'm curious about what's a good solution for writing a logical function that uses literals that overflow OCaml integers, so that it is erased during extraction and doesn't break code generation.

**Comment by jkzinzindohoue** [comment]
Such functions would be either GTot functions or produce an `erased` result.
Both should be erased at extraction. If you are only using the function in specifications, GTot is nice because it is transparent, you do not have to handle `hide` and `reveal` everywhere.

**Comment by s-zanella** [comment]
What I meant is that a definition like `let f: unit -> GTot int = fun () -> 1073741824` will get extracted and fail (on Windows) because the literal is too large, while `let f: unit -> GTot int = fun () -> 1073741823` would extract fine.

**Comment by nikswamy** [comment]
We've had several proposals for addressing this, but we haven't really converged on a solution. 

The simplest approach, I think, is to just translate int to BigInt/System.Numerics.BigInteger for OCaml/F#.

This means that if you're using int, you should be aware that you'll be paying the cost of bigints.

**Comment by s-zanella** [comment]
That sounds very reasonable. I think that's the expectation because int is translated to Z3 as the type of mathematical integers.

**Comment by s-zanella** [comment]
Regarding functions with GTot effect, like `let f: unit -> GTot int = fun () -> 1073741824` above, I expected them to be erased during extraction anyways. Why are they extracted at all?

**Comment by markulf** [comment]
Just to recap, so we should implement int using BigInt/System.Numerics.BigInteger for OCaml/F#. 

What about not extracting GTot functions?

**Comment by vkanne-msft** [comment]
Fixed using ZARITH
