### ISSUE TITLE
More issues with fsdoc

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#861]
Here's a few items I've noticed while trying to use the docs to actually figure things out about the F* library modules:
- https://fstarlang.github.io/docs/ should have the top-level description of a file next to the module name
- https://fstarlang.github.io/docs/FStar.Set.html I don't understand why we have "fsdoc: no summary-found" even though the module has a one-liner description
- https://fstarlang.github.io/docs/FStar.Set.html the page is empty, even though the module has plenty of functions; the functions should be printed without any description, but their signatures should still be printed

The last bit is the most important in my opinion. Can we fix that soon, now that regeneration of docs is back online?

Thanks,

Jonathan

**Comment by aseemr** [comment]
Closing since `fsdoc` is no longer part of the F* codebase.
