### ISSUE TITLE
try .. with is desugared as match .. with instead of try .. with

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#863]

**Comment by nikswamy** [comment]
`FStar.All.try_with` should be emitted as a `try...with` in OCaml.

This used to be the case, at least until 0.9.4 release. See, for example, https://github.com/FStarLang/FStar/blob/7631c53eb7cf9195360879197226dea1a3d90536/src/ocaml-output/FStar_SMTEncoding_Encode.ml#L3765

And FStar.Extraction.ML.Code.fs, around line 387

This appears to no longer be the case. See 
src/ocaml-output/FStar_SMTEncoding_Encode.ml line 5830, characters 17-22: Pattern matching failed

**Comment by nikswamy** [comment]
Marking as priority 1 because this actually emits a program with the wrong semantics. Consider:

This F* program should return `1`

```try (try raise Foo with Bar -> 0) with Foo -> 1```

But it is compiled to

```FStar.All.try_with (fun () -> FStar.All.try_with (fun () -> raise Foo) (function Bar -> 0)) (function Foo -> 1)```

which fails with a "Pattern matching failed"

**Comment by victor-dumitrescu** [comment]
I pushed a fix for this in `vdum_pprint_ocaml`, which solves the issue with `FStar_SMTEncoding_Encode.ml` and correctly handles the case @nikswamy describes.

However, it seems that the desugaring to `FStar.All.try_with` has some bugs. For example, `let _ = try (raise Foo) with Foo -> ()` is wrongly emitted as:

```
let uu___4 : Prims.unit =
  FStar_All.try_with
    (fun uu___6_211  -> match () with | () -> Prims.raise Foo)
    (fun uu___5_212  -> ())
```

I imagine that for the second argument to `try_with` something like `(fun uu___5_212 -> match uu___5_212 with | Foo -> ())` would be expected instead. 

It is also not clear to me why the first function is emitted as a match on `()`, but since that seems to be the case, my fix assumes this form when resugaring `try_with`.

**Comment by catalin-hritcu** [comment]
@victor-dumitrescu  Can your fix already be merged to master even if it's not perfect? This problem seems to affect F* itself when bootstrapped in OCaml (#865).

**Comment by victor-dumitrescu** [comment]
The fix for this issue (in 8c61540) can be merged. I've just fixed another issue related with the way module names are printed, which (if it passes all the tests) I will also push in the next few minutes.

**Comment by catalin-hritcu** [comment]
Merged, and it indeed fixed my problem, thanks. Closing.

**Comment by msprotz** [comment]
Excellent @victor-dumitrescu thanks very much for the fast response time

**Comment by msprotz** [comment]
Two questions:
> It is also not clear to me why the first function is emitted as a match on (), but since that seems to be the case, my fix assumes this form when resugaring try_with.
Can you not special-case? We have plenty of places where we generate extra `match () with ()`... it's ok to generate `try (match () with () -> ...) with`, right? In any case, the removal of extraneous matches should happen *before* pretty-printing... (I'm afraid your match is going to be too restrictive and we'll miss other instances of try/catch in the future.)

> However, it seems that the desugaring to FStar.All.try_with has some bugs. For example, let _ = try (raise Foo) with Foo -> () is wrongly emitted as:
If that issue still happens, can we file a separate bug?

Thanks!
