### ISSUE TITLE
Why must top-level let-bindings be total?

### ISSUE THREAD

**Issue by olleharstedt** [FStarLang/FStar#864]
It makes it harder to program example modules with stateful proving. Any other solution? Wrapping everything in a main function weakens the proving mechanisms (see my other issues: #853).

**Comment by nikswamy** [comment]
We have a proposal for top-level effects, but have not yet got around to implementing it.
https://github.com/FStarLang/FStar/wiki/Top-level-effects

Consider it bumped up the priority list.

**Comment by catalin-hritcu** [comment]
As you know, beyond the wiki, this is already tracked in other places (#143 and #853). Closing.
