### ISSUE TITLE
Tutorial executor gets accidentally broken by \r\n

### ISSUE THREAD

**Issue by ForNeVeR** [FStarLang/FStar#867]
While trying to play with the [tutorial area](https://fstar-lang.org/tutorial/) I've accidentally broken it :(

Here's the reproduction steps (I'm using Windows and that's obviously relevant in this case):

1. Enter the [tutorial area](https://fstar-lang.org/tutorial/) with your browser.
2. Write absolutely simple F* program in Windows `notepad.exe` (or any other text editor that's able to use `\r\n` as line ending). For example, I've used the following sample:

    ```fstar
    module Foobar
    // hello
    ```
3. Copy the program from the Notepad window and paste it to the page.
4. Press "Run" button on the bottom.

**Expected output:** 
```
Verified module: Foobar (3 milliseconds)
All verification conditions discharged successfully
```

**Actual output:** `no file provided`

![image](https://cloud.githubusercontent.com/assets/92793/23103593/d30ee884-f6ef-11e6-9b6e-06f9819071ae.png)

**Workaround:** somehow replace `\r\n` with `\n` in your source, and copy-paste it again.

**Comment by ForNeVeR** [comment]
I'd like to help with the fix, but I'm a newbie in F* and don't know where's the code powering the tutorial area. If someone point me to the code, I think I'll be able to provide a simple fix for the issue.

**Comment by sishtiaq** [comment]
@ForNeVeR: the tutorial is powered by madoko. More details in https://www.fstar-lang.org/tutorial/'s Section 14. 
Solution is probably to not use \10\13 as a line-ending. dos2unix is your friend.

**Comment by ForNeVeR** [comment]
@sishtiaq well, as far as I can currently see, madoko is powering the left part of the turorial area (markdown document). The backend it uses is placed at https://www.fstar-lang.org/run.php

Are the sources of that `run.php` script available?

Re dos2unix: yep, I'm aware of the option and have no problems with that, but I think that would just be much more convenient for the user if www.fstar-lang.org UI could convert the line endings itself. After all, we know for sure that `\r\n` won't work on the online editor. Why don't we make the stuff slightly better for the user?

And, anyways, it'd be good to at least document the behavior. I bet any normal user who haven't been solving xplat issues for several years will be able to tell that he observes the line endings issue. For them, F* just "don't work", and that's definitely not a good user experience!

**Comment by s-zanella** [comment]
We haven't open sourced the backend powering the online tutorial.
The error is quite puzzling and it's an easy fix, so I don't see why we shouldn't convert the input to use LF line endings automatically and improve the user experience.

**Comment by s-zanella** [comment]
I tried setting the newline mode of the ACE editor to "unix" in a browser JavaScript console (`editor.getSession().setNewLineMode("unix");`) and it worked for me. I pushed a fix to `run.php`; it should be in the web server by now. @ForNeVeR: could you please try and confirm it works for you too?

**Comment by ForNeVeR** [comment]
@s-zanella currently I can confirm that the editor on https://fstar-lang.org/run.php is working for me, no matter what line endings I'm using.

I can see that you've probably included the line `editor.getSession().setNewLineMode("unix");`

Thanks! Hereby I declare the bug as fixed.
