### ISSUE TITLE
FStarDoc: documentation support

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#88]
Build a simple tool that can produce HTML/Madoko from a file annotated with special comments. The comments could include Madoko markup. Could stick to the F# syntax for the special comments so that the common F*/F# subset can benefit for all the VS goodness for these things.

**Comment by catalin-hritcu** [comment]
@sishtiaq Can we close this now? :)

**Comment by markulf** [comment]
Shall we close it once we have something useful on https://fstarlang.github.io/docs/?

**Comment by sishtiaq** [comment]
@catalin-hritcu I think we can!
@Markulf https://fstarlang.github.io/docs is not useful because people aren't annotating their code.

**Comment by aseemr** [comment]
Some wip here: https://github.com/FStarLang/FStar/wiki/Documenting-the-library

**Comment by nikswamy** [comment]
Cited this from a more recent issue regarding documentation. Closing this one.
