### ISSUE TITLE
Example: normalization for the STLC via hereditary substitutions

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#89]

**Comment by catalin-hritcu** [comment]
So what's the status of this now that rel2 is the default?

**Comment by ckeller** [comment]
It goes through, I am making progress (see examples/hereditary-substitutions/hs.fst).
I now have to find good solutions to prove totally of mutually-recursive defined functions.

**Comment by ckeller** [comment]
Thanks to the nice trick in bug138, I now have proved the main theorem.
The next step would be to make the code more readable by using implicit arguments, but I am currently stuck by bug139.

**Comment by catalin-hritcu** [comment]
Closing since the main theorem is proved, and the rest seems just about beauty.
