### ISSUE TITLE
Change of behavior in normalization after the merge of c_relational-ci_r3

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#892]
Before the merge:

`protz@Joprotze-Z420:~/Code/fstar/examples/low-level ((d3ff269...)) $ make ocaml-test-extract`

In `tmp/Crypto_AEAD_Decrypt.ml`:

```
  98                    let popt =
  99                      Crypto_AEAD_Wrappers_CMA.verify i
 100                        x_0.Crypto_Symmetric_PRF.iv st aadlen aad plainlen
 101                        plain cipher_tagged ak acc h1
 102                       in
 113                    FStar_ST.pop_frame (); verified)
```

On the current `master`, after the merge:

```
  93                    let popt =
  94                      Crypto_AEAD_Wrappers_CMA.verify i
  95                        {
  96                          Crypto_Symmetric_PRF.iv = iv;
  97                          Crypto_Symmetric_PRF.ctr =
  98                            (Crypto_Symmetric_PRF.ctr_0 i)
  99                        }.Crypto_Symmetric_PRF.iv st aadlen aad plainlen plain
 100                        cipher_tagged ak acc h1
 101                       in
```

The field access really needs to be normalized here.

CC @nikswamy who may know off the top of his head where this normalization bug comes from.

Thanks!

**Comment by msprotz** [comment]
Good file:
[Crypto_AEAD_Decrypt-good.txt](https://github.com/FStarLang/FStar/files/835139/Crypto_AEAD_Decrypt-good.txt)
Bad file:
[Crypto_AEAD_Decrypt-bad.txt](https://github.com/FStarLang/FStar/files/835140/Crypto_AEAD_Decrypt-bad.txt)

**Comment by nikswamy** [comment]
It actually looks like more normalization took place after the merge. For example, x_0 was substituted. Although I agree it should have normalized even further to remove the projection, is it really the cause of a regression?

Also, was the rest of it OK? I.e., the verified and pop_frame part

**Comment by msprotz** [comment]
This one is fixed via FStarLang/kremlin@05cad69... looking into it, most errors seem to be bad consequences of F* now normalizing more stuff... as an example:

```
-  uint32_t aadlen3 = (uint32_t )0;
-  uint8_t aad3[aadlen3];
-  memset(aad3, 0, aadlen3 * sizeof aad3[0]);
+  uint8_t aad3[0] = { 0 };
```

The old form, where `addlen` is not normalized, is legal C, but since `aadlen` is now normalized, the latter form is not legal.

There's a couple more instances too:

```
-  bool scrut0 = Crypto_Symmetric_UF1CMA_skeyed(Prims_fst(macId));
+  bool
+  scrut0 =
+    Crypto_Symmetric_UF1CMA_skeyed(Prims_fst((K___Crypto_Indexing_id_FStar_UInt128_t ){
+          .fst = i,
+          .snd = x9.iv
+        }));
```

The latter is legal (`Prims_fst` is a hand-written macro, because even though polymorphism is not supported, everyone loves using `fst`), but the former is not (need to figure out why).

**Comment by msprotz** [comment]
Alright, I successfully updated kremlin to deal with these two new situations -- these were bugs that I would've had to fix in any case, but that only surfaced because the modified normalizer generated code with a different structure.

The looping bug when extracting hacl-star remains but this one isn't filed anywhere.

**Comment by msprotz** [comment]
The latter issue with the C99 compound literal being parsed as an n-ary function call seems to be GCC parsing this as case 7 of http://en.cppreference.com/w/cpp/language/list_initialization even though this is technically C++. I haven't skimmed the standard to figure out whether this is legal or not, but always adding parentheses around C99 compound literals in the kreMLin pretty-printer solves it.
