### ISSUE TITLE
Lax type checking more lax than expected

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#894]
I'm documenting this behaviour which may come across as surprising:
```F#
module M

type u (n:int) =
  (match n with
  | 0 -> bool
  | _ -> bool)

val f: n:int -> u n
let f _ = ()
```
```
$ fstar.exe --lax --debug_level Extreme --debug M  M.fst
...
Computed return type unit; expected type (u uu___)
check_and_ascribe: type is unit<:(u uu___) 	guard is 
	{guard_f=(has_type () (u uu___));
	 deferred={
};
	 univ_ineqs={Solving for {}; inequalities are {}};
	 implicits={}}
, {}
...
All verification conditions discharged successfully
```

What's happening is that F* queries Z3 to decide whether `()` has type `u n`, but in `--lax` mode Z3 queries are admitted. Without `--lax`, the query is emitted and fails as expected:
```
Encoding query formula: (l_Forall (fun uu___ -> (has_type () (u uu___@0))))
Encoding binders uu___
Z3 says: unknown
```

**Comment by aseemr** [comment]
I don't think we are going to address `lax` mode improvements or removing surprises from it. Closing this as wontfix, thanks Santiago for documenting it!
