### ISSUE TITLE
Having universe variables begin with u# instead 'u

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#896]
Proposition of @nikswamy after using explicit universe : we could have `u#a` instead of `'ua` and `u#(max a b)` instead of `u#(max 'ua 'ub)`.

**Comment by kyoDralliam** [comment]
done !

**Comment by nikswamy** [comment]
Thanks for doing this so quickly!

**Comment by nikswamy** [comment]
Would be great to update: https://github.com/FStarLang/FStar/wiki/Explicit-universes

**Comment by kyoDralliam** [comment]
re-done :)
