### ISSUE TITLE
Infinite allocation loop in the normalizer

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#899]
Pro tip: you want to hit `Ctrl-Shift-Esc` then keep your finger on the "End Process" button for this one.

Using the following revision of F*: 513b775 -- that is, WITHOUT the bugfix that makes sure we don't inline `let x = Buffer.sub ... in e` (total let-bindings), and using aa571cf8b1 for hacl-star, then this sends F*'s normalizer off the rails

```
protz@Joprotze-Z420:~/Code/hacl-star/code/curve25519 (master) $ fstar.exe --odir x25519-c --codegen OCaml --lax --no_extract FStar.Math.Lib --no_extract FStar.HyperHeap --no_extract FStar.HyperStack --no_extract FStar.ST --no_extract FStar.Seq.Base --no_extract FStar.UInt128 --no_extract FStar.Int128 --no_extract FStar.UInt64 --no_extract FStar.Int64 --no_extract FStar.UInt63 --no_extract FStar.Int63 --no_extract FStar.UInt32 --no_extract FStar.Int32 --no_extract FStar.UInt31 --no_extract FStar.Int31 --no_extract FStar.UInt16 --no_extract FStar.Int16 --no_extract FStar.UInt8 --no_extract FStar.Int8 --trace_error --include D:/cygwin/home/protz/Code/fstar/ulib//hyperstack --include ../bignum --include ../lib/kremlin --include D:/cygwin/home/protz/Code/kremlin/kremlib Hacl.Test.X25519.fst Curve25519.fst
```
@kyoDralliam and I narrowed it down to the `fmonty__2` function in `Hacl.EC.AddAndDouble.fst` -- replacing the body with `assume False; ()` makes the bug go away.

CC @nikswamy

**Comment by mtzguido** [comment]
Don't think we can repro this anymore (I tried, but it's pretty stale). Closing.
