### ISSUE TITLE
More examples for the tutorial and regressions

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#90]
For instance, extending STLC with some of these:
- Sums, Lists, General Recursion, Records
  http://www.cis.upenn.edu/~bcpierce/sf/current/MoreStlc.html
  http://www.cis.upenn.edu/~bcpierce/sf/current/Records.html
- Subtyping
  http://www.cis.upenn.edu/~bcpierce/sf/current/Sub.html
- References
  http://www.cis.upenn.edu/~bcpierce/sf/current/References.html

Some more interesting things we could show at POPL:
- Normalization of STLC (the most complex proof in SF; also see #89)
  http://www.cis.upenn.edu/~bcpierce/sf/current/Norm.html
  https://github.com/yforster/stlc-norm
- Subject-reduction of System F-sub (POPLMark challenge)
  http://www.seas.upenn.edu/~plclub/poplmark/
  (We now have System F omega, but we're still missing the sub part)

**Comment by catalin-hritcu** [comment]
For the purpose of teaching, porting While + Hoare and then switching to Predicate Transformers would be great.

**Comment by catalin-hritcu** [comment]
A lot of these were done for the SB course and need to be ported back here (for some after some serious cleanup https://github.com/yforster/stlc-norm).

**Comment by nikswamy** [comment]
-- While stuff from SF would be nice to have, more urgent is to port examples to use the new universal type-checker.

-- Additionally, in the nice to have category, let's port stuff from .old/to_be_ported

**Comment by sishtiaq** [comment]
re Nik's first comment: a lot of the examples and doc/tutorial use --stratified. They need to be updated to use the default universes. 

To find which files are still using the old mode, grep for "SFSTAR=", and for "\-stratified".

**Comment by catalin-hritcu** [comment]
@nikswamy Is this really a Milestone 1 thing? When is that planned?

**Comment by markulf** [comment]
@nikswamy, we did port the tutorial to universes. What is likely still missing are explanations of universes. We also got some user questions on this. Porting or removing old stratified examples, so we can delete the stratified libraries is also important in terms of usability and avoiding confusion.

**Comment by nikswamy** [comment]
I've cited this from a more recent issue that tracks work items on the tutorial. Closing this one.
