### ISSUE TITLE
Possible improvements to make build systems easier to write

### ISSUE THREAD

**Issue by andreasdotorg** [FStarLang/FStar#908]
I've looked at the "hello world" example, and found that four lines of F* source come with 60 lines of Makefile, not counting the three other Makefile snippets included from different paths. I tried to make things easier, but found out that the way extraction works and the standard library is handled make that a bit difficult.

The main stumbling block to me seems to be that extraction will extract all the modules that are not explicitly excluded, and that there is a brittle list of modules that are part of the standard library you're supposed to include by means of a Makefile handling the exclusion.

(There are more problems in that only relative pathnames work on Windows, due to missing calls to cygpath, but I digress).

What I think would be best would be to generate one output file per input file, i.e., only extract the module currently under compilation.

Now I see that there is the --extract_module flag to the compiler, which already does the right thing. Almost, because it takes a module name as an argument, and what I have in my hand in my build system is a file name. The two are related, but there is that pesky capitalization issue... so I have to keep track of both a module name and a file name per file I want to compile. Of course, we have to live with the fact that file systems might screw with capitalization, otherwise my instinct would be to change things to require the file name to always be the module name, capitalization and all.

So what I think should happen is the following default behaviour:

- Generate one output file for every input file.
- Make the name of that output file the same as the input file, with the suffix changed.
- Make extra sure capitalization is maintained (or enforce file name capitalization matches module name exactly).
- Just put all of the standard library into one file, and don't bother with that list of not-to-be-extracted files.

Added bonus:

- Have a mode that records dependencies on the F* level.
- Have a mode that records dependencies on the generated code level

Mhh. The more I think about it, the more I'd like to make the file base name match the module name, including capitalization, a strict requirement. Makes lots of stuff so much easier, and doesn't really break anything either.

**Comment by aseemr** [comment]
We have significantly revised the build system that is used pervasively in projects like HACL*, plus some of the suggestions from this report are already incorporated. Closing this issue, we should track more enhancements separately.
