### ISSUE TITLE
Non-terminating normalization during ML extraction

### ISSUE THREAD

**Issue by ad-l** [FStarLang/FStar#910]
I think I may have seem similar bugs in the past but I can't find them.

I am still running into instances of the normalization diverging during extraction.
Here is a minimized example:

```
val g: #n:nat -> x:nat -> Tot nat (decreases x)
let rec g #n x =
 if x = 0 then 0
 else 1 + g (x-1)
```

I think the problem is that the normalizer is trying to reduce g (x-1) despite the omitted implicit argument.

fstar test.fst succeeds: Verified module: Test (400 milliseconds)
All verification conditions discharged successfully
fstar --codegen OCaml test.fst --odir . diverges

**Comment by aseemr** [comment]
This code now fails to verify, and I think rightly so, since F* is unable to instantiate the implicit in the recursive call to `g`. If we provide the implicit argument as `g #n (x - 1)`, then extraction works as expected.

Closing the issue, please reopen if required.
