### ISSUE TITLE
Online editor completely broken

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#918]
Running the following in the online tutorial prints a surprising message :

```
module Welcome

open FStar.List
```

```
Warning: recursive dependency on module fstar.list.tot.properties The cycle is: fstar.list.tot -> fstar.list.tot.properties A DOT-format graph has been dumped in the current directory as dep.graph With GraphViz installed, try: fdp -Tpng -odep.png dep.graph Hint: cat dep.graph | grep -v _ | grep -v prims 
```

**Comment by catalin-hritcu** [comment]
@ad-l This seems like a regression in hacks of the online editor. I encountered it today as well.

**Comment by catalin-hritcu** [comment]
Actually the tutorial editor seems completely botched up. As someone posted on slack (and I can easily reproduce) even an empty file causes errors:
```
/var/fstar/ulib/FStar.PredicateExtensionality.fst(13,2-13,45) : (Error) Too many arguments to function of type (p:Type -> Pure (unit)); got 2 arguments
```

**Comment by seako** [comment]
I just installed 0.9.4.0 via homebrew and am getting the same error when trying to compile the hello world example

**Comment by catalin-hritcu** [comment]
@seako Homebrew can also [install the latest git version of F*](https://github.com/FStarLang/FStar/blob/master/INSTALL.md#homebrew-formula-for-mac-os-x), can you also try that please and report back?

**Comment by seako** [comment]
Hurrah, I can compile the Hello world example after installing fstar --HEAD!

**Comment by tchajed** [comment]
The editor on the tutorial is still broken, though the error message I'm seeing now is:

```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Method 'FStar.Syntax.Syntax/sigelt.NewSig_pragma' not found.
```

**Comment by markulf** [comment]
I did some detective work.

* This is still a problem.
* We should put more information here: https://github.com/FStarLang/FStar/wiki/Compiling-the-tutorial-using-madoko
* The madoko site seems to be down: https://madoko.net/, hopefully temporal. The madoko file can be edited locally.

**Comment by ad-l** [comment]
As discussed on the F* call, the update hook was changed to only build the OCaml snapshot.
