### ISSUE TITLE
Problem when defining and using type representing functions

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#92]
Hello,

I have some difficulties understanding why Fstar does not type check in the following example:

``````
module Test

type t (a:Type) = a -> a -> Tot a

type f_type (a:Type) = r:t a{ forall x y. r x y = r y x }

assume val f : a:Type -> Tot (f_type a)

val f2 : a:Type -> a -> Tot a
let f2 x = f x x
```````
It produces the following error message:
``````
test2.fst(10,178-10,178) : Error
Too many arguments to function of type (a:Type -> Tot (f_type a))
``````
But when i replace `Tot (f_type a)` by `Tot (r:t a{ forall x y. r x y = r y x })`, it works...

What is the difference ? How Fstar behave here ?

Many thanks
Vincent

**Comment by nikswamy** [comment]
Seems to be fixed now. Closing it and adding bug92.fst to the test suite.
