### ISSUE TITLE
Misusing DIV crashes F*

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#920]
```
module Min

let test (t: unit) : DIV (unit) =
  ()
```

```
<input>(3,25-3,31): (Error) Expected type "Effect"; but "(DIV unit)" has type "(wp:(pure_wp unit) -> Tot Effect)"
<input>(3,25-3,31): (Error) Expected type "Effect"; but "(DIV unit)" has type "(wp:(pure_wp unit) -> Tot Effect)"
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Got effects PURE and DIV, expected normalized effects
```

**Comment by kyoDralliam** [comment]
Isn't it an error message problem rather than a bug ? The source code is incorrect as it stands, `DIV` needs a wp argument. The version without wp argument is `Dv`

**Comment by catalin-hritcu** [comment]
`Unexpected error; please file a bug report` should always be marked as bug, irrespective of whether the triggering file should succeed or fail. If it should fail it should do so without triggering an `Unexpected error`.

**Comment by kyoDralliam** [comment]
For reference the fix was to change the `failwith` with a `raise (Error ...)` since this is a legitimate error.

**Comment by cpitclaudel** [comment]
Thanks! With not much experience in F* I just took the approach of reporting it every time F* exits abruptly. Let me know if that's too much noise :)

**Comment by catalin-hritcu** [comment]
@cpitclaudel  This is great. I also file all F* explosions I see.
