### ISSUE TITLE
examples/preorders/MRefHeap.fst fails with --n_cores

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#926]
The only example in `uregressions` that fails with `--n_cores` is `examples/preorders/MRefHeap.fst`
```
[preorders]$ fstar.exe --n_cores 6 --use_hints --record_hints --verify_module MRefHeap MRefHeap.fst
./MRefHeap.fst(59,0-61,27): (Error) Unknown assertion failed
Verified module: MRefHeap (1443 milliseconds)
1 error was reported (see above)
[preorders]$ fstar.exe --use_hints --record_hints --verify_module MRefHeap MRefHeap.fst
Verified module: MRefHeap (2348 milliseconds)
All verification conditions discharged successfully
```

Will need to investigate the cause of this, since `MRefHeap.fst` doesn't seem particularly flaky.

**Comment by catalin-hritcu** [comment]
@wintersteiger @shaolintl @danelahman just a heads up on this issue.

**Comment by wintersteiger** [comment]
I'll take a closer look at this today, let me know if you're planning to do so too!

**Comment by wintersteiger** [comment]
So far I wasn't able to reproduce this; all of them verify just fine for me and I see one hint replay failure. @catalin-hritcu could you try again to see whether this is still a problem? (I'm also running --n_cores over everything atm to see whether anything else is broken.)

**Comment by catalin-hritcu** [comment]
I can indeed, no longer reproduce this either. Hope that someone fixed it and it's not a heisenbug.

**Comment by wintersteiger** [comment]
It's not a Heisenbug! It fails with Z3 4.5.0 but not with the latest Z3 master. I used the old code from just after the --n_cores bug were fixed, to dump the queries (with --z3refresh) and they were identical with and without --n_cores. However, when I do the same with the latest F* master then I do get different queries with --n_cores; the investigation continues.

**Comment by mtzguido** [comment]
`--n_cores` was removed.
