### ISSUE TITLE
`val` annotations yield ugly-looking signatures

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#929]
Contrast this:

```
val fold_left: ('a -> 'b -> ML 'a) -> 'a -> list 'b -> ML 'a
let rec fold_left f x y = match y with
  | [] -> x
  | hd::tl -> fold_left f (f x hd) tl
```

which yields this for `#info fold_left`:

```
fold_left: (uu___:(uu___:'a@1 -> uu___:'b@1 -> 'a@3) -> uu___:'a@2 -> uu___:(list 'b@2) -> 'a@4)
```

with this:

```
let rec fold_left (f: 'a -> 'b -> ML 'a) (x: 'a) (y: list 'b) : ML 'a = match y with
  | [] -> x
  | hd::tl -> fold_left f (f x hd) tl
```

which yields this for `#info fold_left`:

```
fold_left: (f:(uu___:'a@1 -> uu___:'b@1 -> 'a@3) -> x:'a@2 -> y:(list 'b@2) -> 'a@4)
```

It would be nice t preserve the names `f`, `x`, and `y` even when there is a `val`.

**Comment by nikswamy** [comment]
First, I would argue that we should not print bound names that being with the reserved prefix 'uu___' unless they are really used. 

As for preserving the names `f, x, y` ... it would be a nice feature, but not so easy to implement. What about 

```
val fold_left : g:('a -> 'b -> ML 'a) -> a:'a -> l:list 'b -> ML 'a
let fold_left f x y = ... 
```
?

It's not so hard to decorate the `val` with the names one wants for the parameters, is it?

**Comment by cpitclaudel** [comment]
> It's not so hard to decorate the val with the names one wants for the parameters, is it?

True, but then there's a bit of duplication between both.

> As for preserving the names f, x, y ... it would be a nice feature, but not so easy to implement. What about [...]

We already have the `Annotation from val declaration overrides inline type annotation` warning, but things should work the other way around in this case, right ? I'd expect the function's arguments to override the val.

**Comment by cpitclaudel** [comment]
> First, I would argue that we should not print bound names that being with the reserved prefix 'uu___' unless they are really used.

(I actually already strip them on the Emacs side)

**Comment by cpitclaudel** [comment]
> As for preserving the names f, x, y ... it would be a nice feature, but not so easy to implement.

Would something like https://github.com/FStarLang/FStar/compare/cpitclaudel_argnames be acceptable ?

> What about
> ```
> val fold_left : g:('a -> 'b -> ML 'a) -> a:'a -> l:list 'b -> ML 'a
> let fold_left f x y = ... 
> ```

The code above prints a warning in that case.
