### ISSUE TITLE
Codegen to F#

### ISSUE THREAD

**Issue by mikhail-makarov** [FStarLang/FStar#94]
I built F* from sources on Ubuntu.

The help message produced by running fstar.exe with the "--help" parameter documents the following parameter:
"--codegen OCaml|F#|JS  Generate code for execution".
Codegen to OCaml (running with the parameter "--codegen OCaml") works fine and produces a *.ml file in the output folder. However, running either with the parameter "--codegen F#" or with the parameter "--codegen JS" does not produce any output files. Also, running with the parameter "--codegen JavaScript" (which seems to be not documented anywhere) prints some javascript output to the console even though the output folder was specified with the "--odir" parameter.

What I am interested in is codegen to F#. Is it supported yet?

**Comment by larsw** [comment]
What's the status on the F# backend?

**Comment by nikswamy** [comment]
Still not yet fully supported, I'm afraid. We should prioritize it.

**Comment by catalin-hritcu** [comment]
FYI: Nik just committed an F# backend, please give it a go

**Comment by catalin-hritcu** [comment]
Separated out the "Codegen to JavaScript" part to a separate issue (#332)

**Comment by catalin-hritcu** [comment]
Was curious whether the extracted .fs files are any slower than the ones in the common subset and tey are not.

common subset:
```
make  1134.65s user 15.30s system 102% cpu 18:43.91 total
```

extracted F#:
```
make  1135.62s user 15.98s system 102% cpu 18:45.03 total
```

**Comment by catalin-hritcu** [comment]
Closing this issue since we now have a working F# backend. Improving it will be tracked on other issues.
