### ISSUE TITLE
Parse & recognize --extract Foo.*,Bar.Baz.*

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#941]
This would significantly improve the usability and we could replace the myriad of `--extract` options with a single one.

**Comment by msprotz** [comment]
This can be achieved by:
- copy/pasting the parser at https://github.com/FStarLang/kremlin/blob/master/parser/parser.mly#L40
- copy/pasting the first few lines of https://github.com/FStarLang/kremlin/blob/master/src/Bundle.ml#L4
- copy/pasting the first function o f https://github.com/FStarLang/kremlin/blob/master/src/Bundles.ml#L11

**Comment by s-zanella** [comment]
This is done now (and it also supports negative patterns!). Thanks @protz 
```
   --extract One or more space-separated occurrences of '[+|-]( * | namespace | module)'  
		Extract only those modules whose names or namespaces match the provided options.
			Modules can be extracted or not using the [+|-] qualifier. 
			For example --extract '* -FStar.Reflection +FStar.List -FStar.List.Tot' will 
				not extract FStar.List.Tot.*, 
				extract remaining modules from FStar.List.*, 
				not extract FStar.Reflection.*, 
				and extract all the rest.
		Note, the '+' is optional: --extract '+A' and --extract 'A' mean the same thing.
		Multiple uses of this option accumulate, e.g., --extract A --extract B is interpreted as --extract 'A B'.```
