### ISSUE TITLE
fsdoc keywords (like @summary) break line numbering

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#947]
The line number reported by `#info` is off by one for certain dependencies, but nor for the current file (concretely, pressing `M-.` goes to the right line for local definitions, but e.g. for `List.append` it goes one line too high).

**Comment by cpitclaudel** [comment]
Test case:

`a.fst`:

```fsharp
module A
(**
@summary XXX
*)
let b = 1 + "A"
```

```bash
$ fstar a.fst
./a.fst(4,12-4,15): (Error) Expected expression of type "Prims.int"; got expression ""A"" of type "Prims.string"
1 error was reported (see above)
```

Contrast this with:

`a.fst`:
```fsharp
module A
(**
// @summary XXX
*)
let b = 1 + "A"
```

```bash
$ fstar a.fst
./a.fst(5,12-5,15): (Error) Expected expression of type "Prims.int"; got expression ""A"" of type "Prims.string"
1 error was reported (see above)
```

**Comment by cpitclaudel** [comment]
I think the `@`-keyword handling code was written by @ad-l . Though @kyoDralliam maybe you can help too, since you're good with parsers :)

**Comment by ad-l** [comment]
The problem is in the `fsdoc_kw_arg` rule of the lexer
The `newline` handler does not call mknewline which throws the lc off

**Comment by cpitclaudel** [comment]
Thanks! Do you want to prepare a patch, or should I?

**Comment by ad-l** [comment]
I fixed it in the Unicode lexer... it can probably wait until the feature lands
