### ISSUE TITLE
#info database survives across backtracks

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#949]
The database used by the `#info` interactive command isn't saved and reset when backtracking; this causes F* to report outdated information when proving #info for a position in a retraced section of the buffer.

Test case:

```
>>> #push 1 0
>>> module Info
>>> let a : int = 1
>>> #end #done-ok #done-nok

#done-ok

>>> #info a <input> 2 5
(defined at <input>(2,4-2,5)) Info.a: int
#done-ok

>>> #pop
>>> #info  <input> 2 5
(defined at <input>(2,4-2,5)) Info.a: int
#done-ok
```

**Comment by nikswamy** [comment]
is this perhaps a feature rather than a bug? ; )
i.e., F* will show you the last known type information at that point. Better than showing you nothing at all.

**Comment by cpitclaudel** [comment]
Dubious: with this feature, if you write something different at the same location, you'll get the type of the old thing instead of the type of the new one (the type of the new one comes from the id that's also included in the "info" query)

**Comment by cpitclaudel** [comment]
Also, the info is never reset, so it just accumulates (with multiple overlapping and often contradictory info spans on the same point).

**Comment by nikswamy** [comment]
FYI, I found an fixed a bug in the #info database. The fix is in nik_tactics, which should land in master with guido_tactics
https://github.com/FStarLang/FStar/commit/a7d005ab8fe39831e3922aee578c5054e336fd6d#diff-eaba7bdeef6a7c1a39c0a4bfcd42b984L125

**Comment by cpitclaudel** [comment]
Thanks for the pointer.  I think I can make a fix for this bug, which is distinct from the one you fixed.
