### ISSUE TITLE
$FSTAR_HOME/stdlib is not in default include path, breaking Homebrew installation

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#951]
Installing F* on macOS with Homebrew results in `prims.fst` not being found.

The specific errors are, with `fstar-0.9.4.0`:
```
Warning: no modules in namespace FStar and no file with that name either
Warning: no modules in namespace Prims and no file with that name either
dependency analysis did not find prims.fst?!
```

and with `HEAD-cd507f2`:
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
FStar_Util.Failure("unable to find required file \"prims.fst\" in the module search path.\n")
```

This issue used to require running `fstar.exe` with an alias that adds the Homebrew installation directory to the include list. This was fixed (https://github.com/FStarLang/FStar/commit/fdb33907e0e4d18ba2f2b30031d9baaa0b831957), but it doesn't look like those directories are there any more: https://github.com/FStarLang/FStar/blob/master/src/basic/FStar.Options.fs#L862.

**Comment by msprotz** [comment]
This probably went unnoticed for a long while before we caught it. What is the directory structure of the Homebrew setup? I wonder if we at least could use the same as the opam setup (i.e. path/to/fstar.exe/../lib/fstar) so that the code breaks less often.

@beurdouche may have feedback

**Comment by tchajed** [comment]
Homebrew installs various parts of the F* install to `/usr/local/Cellar/fstar/$version/libexec` (that's where `stdlib` is). `fstar.exe` is in /usr/local/bin, but is a symlink to `/usr/local/Cellar/fstar/$version/bin/fstar.exe`. You could resolve the symlink and use that.

The [F* Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fstar.rb) has access to `prefix`, a (Ruby) variable with `"/usr/local/Cellar/fstar/$version"`. At least Coq embeds this by passing it to `./configure`, and I'm guessing F* should do the same by appropriately setting `fstar_home`. If somebody can tell me how to do that on the F* side, if it's even possible, then I could fix the Homebrew formula.

**Comment by s-zanella** [comment]
Wouldn't this command-line option do what you want?
`--fstar_home [dir]  Set the FSTAR_HOME variable to [dir]`

**Comment by tchajed** [comment]
Not quite, since that's only available when invoking `fstar.exe`. I want to do two things: set the default `FSTAR_HOME` at compile time during the Homebrew installation, and then make sure that the appropriate subdirectory of `FSTAR_HOME` is searched for the Homebrew layout. It's the former feature (configure `FSTAR_HOME` at install time) that I don't know how to do.

Currently, even `/usr/local/bin/fstar.exe --fstar_home /usr/local/Cellar/fstar/$version/libexec` doesn't work, presumably because the `stdlib` subdirectory isn't searched.

**Comment by beurdouche** [comment]
Maybe we can change the Homebrew formula to rename `stdlib` to `ulib` ?
Also, since the user needs to install OPAM/OCaml anyway for extraction, I really wonder if it is worth keeping an Homebrew formula alive while F* is already available in OPAM... @s-zanella @protz

**Comment by s-zanella** [comment]
I don't know how thorough are these stats (https://bintray.com/homebrew/bottles/fstar/view#statistics), but they show a few daily downloads with peaks whenever a new release is out. I think that the decision of maintaining the Homebrew formula depends on how much effort you (@beurdouche) want to put into it.

Using `ulib` rather than `stdlib` in the formula, plus defining an alias for `fstar.exe` that passes `-- fstar_home /usr/local/Cellar/fstar/$version` solves the issue for me.

**Comment by beurdouche** [comment]
> I don't know how thorough are these stats (https://bintray.com/homebrew/bottles/fstar/view#statistics <https://bintray.com/homebrew/bottles/fstar/view#statistics>), but they show a few daily downloads with peaks whenever a new release is out. I think that the decision of maintaining the Homebrew formula depends on how much effort you (@beurdouche <https://github.com/beurdouche>) want to put into it.
> 
I am fine with maintaining, I think those numbers are reasonable.
> Using ulib rather than stdlib in the formula, plus defining an alias for fstar.exe that passes -- fstar_home /usr/local/Cellar/fstar/$version solves the issue for me.
> 
Great, is the alias automated in the formula ?
Would you mind pushing the fix to the formula as you have it, or should I ?

Thanks ! ;) B.

**Comment by s-zanella** [comment]
The PR with the fix has been merged in homebrew-core.
Closing.
