### ISSUE TITLE
Parsing problem with forall and type declaration

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#97]
Hello,

I think there is an issue with the parsing of `forall` when defining a type. With both
`````
module Test

assume val f : list 'a -> Tot nat
  
type Equivalence (a:Type) = forall x. f x = f x
```
and
`````
module Test

assume val f : list 'a -> Tot nat
  
type Equivalence (a:Type) = forall x. (f x = f x)
`````
I obtain the error message:
`````
ERROR: Syntax error near line 5, character 34 in file test2.fst
`````
However, the following code type check:
`````
module Test

assume val f : list 'a -> Tot nat
  
type Equivalence (a:Type) = (forall x. f x = f x)
`````

Is it wanted ? 

I have an other example of code that does not really parse propertly but I think it is the same bug you were talking in #80 :
`````
module Test

assume val f : list 'a -> Tot nat

assume val g: l:list 'a -> n:int{n >= 0 /\ n < (f l)} -> Tot 'a
`````
from which I obtain the error message:
`````
ERROR: Syntax error near line 5, character 53 in file test2.fst
``````

Thanks

Vincent

**Comment by catalin-hritcu** [comment]
The second part of this is indeed already fixed. Let's use this issue to track progress on the first.
