### ISSUE TITLE
type abbreviations not allowed in signature when defining new datatypes

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#974]
The criterion for well-typedness when defining datatypes is too syntactic 

```
let x = Type
type t : x = | A
```

```
The type of t is x, but since this is the result type of a constructor its type should be Type
```

**Comment by mtzguido** [comment]
Pushing a fix to call the normalizer on the type before doing that check.

**Comment by kyoDralliam** [comment]
Thanks @mtzguido that was quick !

**Comment by kyoDralliam** [comment]
...Still too syntactic, the following fails

```
let f (a:Type) = a -> Type
type t : f unit = | A : t ()
```

**Comment by kyoDralliam** [comment]
Hopefully re-Fixed by `https://github.com/FStarLang/FStar/commit/ab3aaaf88999005603f870d92432a70e4d060b16`
