### ISSUE TITLE
Allow passing lists of modules in command-line options

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#982]
Many command-line options take as parameter a single module name, e.g. 

  `--verify_module [module name]  Name of the module to verify`. 

This leads to some bloating in Makefiles, see e.g. https://github.com/mitls/hacl-star/blob/master/code/poly1305/Makefile#L161 (easily avoidable using make functions) and command-line arguments.

These options could be extended to take a list of comma-separated module names.

See #908 and #395 for relevant discussions.

**Comment by msprotz** [comment]
#941?

**Comment by s-zanella** [comment]
Indeed, allowing patterns like in #941 will be even better. Not only for `--extract`, but most options currently accepting a single module name.

**Comment by s-zanella** [comment]
The `--verify_module` option is deprecated and `--extract` now accepts patterns (see #941).
Supporting patterns in other options taking a module name as argument (e.g. `--debug`, `--dump_module`) is not terribly useful.
Closing.
