### ISSUE TITLE
Broken invariant in `FStar.TypeChecker.Rel`

### ISSUE THREAD

**Issue by kyoDralliam** [FStarLang/FStar#985]
The following code break an assertion in `FStar.TypeChecker.Rel` in `force_quasi_pattern` 
```
let c (w:(z:(unit * unit) & unit) * unit) : unit =
  let w1, w2 = w in
  match w1, w2 with
  | (|(_,_), _|), _ -> ()
```
From the debug output : 
```
Trying flex-flex one pattern ((?61348 r w uu___ w1 w2 uu___ uu___)) with (?61336 r w uu___ w1 w2 (Mktuple2<?61345, ?61343> #((fun r w uu___ w1 w2 -> ((?61657 r@4 w@3 uu___@2 w1@1 w2@0) $$ Tot Type u#(?61343))) r w uu___ w1 w2) #((fun r w uu___ w1 w2 -> ((?61661 r@4 w@3 uu___@2 w1@1 w2@0) $$ Tot Type u#(?61345))) r w uu___ w1 w2) uu___ uu___))
```
The last 2 arguments of the lhs seems to be grouped in a pair in the rhs which may break some size invariant...

**Comment by shaolintl** [comment]
The current output is

```
Trying flex-flex one pattern (uu___unification_ 26544 w uu___166298 w1 w2 uu___167126 uu___167127) with uu___unification_ 26532 w
  uu___166298
  w1
  w2
  ((fun w uu___170711 w1 w2 -> uu___unification_ 26829 w uu___170711 w1 w2) w uu___166298 w1 w2,
    (fun w uu___170715 w1 w2 -> uu___unification_ 26833 w uu___170715 w1 w2) w uu___166298 w1 w2,
    uu___167126,
    uu___167127)
```

Indeed it fails in an assertion in force_quasi_pattern as the non-pattern term (rhs above since it contains a pair or quadruple) contains 5 arguments but the computation of expected arguments according to its type returns 4 (based on Syntax.Util.arrow_formals_comp). The argument given to this method is

```
typew:(z:Prims.unit * Prims.unit & Prims.unit) * Prims.unit ->
uu___170719:(z:Prims.unit * Prims.unit & Prims.unit) * Prims.unit ->
w1:
(fun w uu___170734 -> (fun w uu___170736 -> z:Prims.unit * Prims.unit & Prims.unit) w uu___170734) w
  uu___170719 ->
w2:(fun w uu___170739 w1 -> (fun w uu___170742 -> Prims.unit) w uu___170739) w uu___170719 w1 ->
Prims.Tot
((fun w uu___170723 w1 w2 ->
      uu___170726:
      (fun w uu___170728 w1 w2 ->
          uu___unification_ 26829 w uu___170728 w1 w2 * uu___unification_ 26833 w uu___170728 w1 w2) 
        w
        uu___170723
        w1
        w2 ->
      Prims.Tot Type) w
    uu___170719
    w1
    w2)
```
Which indeed seems to expect only 4 arguments.

**Comment by shaolintl** [comment]
From @kyoDralliam, the problem seems to be due to the fact the type above has a beta redex. Next step should be to wnhf normalize it somewhere in Rel.

**Comment by kyoDralliam** [comment]
One year later, the issue seems to have gone away. Adding this snippet to the repo (e3db2e45679db671cc22241abd6c114efce9b31b)

**Comment by nikswamy** [comment]
ha. Thanks for adding the test case. I noticed that the issue still exists in the new type inference algorithm in my branch
