### ISSUE TITLE
FStar does not build on up-to-date system (with OCaml 4.04.1)

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#991]
```
bbeurdouche@bmpi:/opt/fstar$ make -j -C src/ocaml-output/
cp "../extraction/ml/FStar_Extraction_ML_PrintML_4.04.1.ml" ../extraction/ml/FStar_Extraction_ML_PrintML.ml
cp: cannot stat '../extraction/ml/FStar_Extraction_ML_PrintML_4.04.1.ml': No such file or directory
# TODO : call menhir directly when positions are fixed instead of
make: *** [../extraction/ml/FStar_Extraction_ML_PrintML.ml] Error 1
make: *** Waiting for unfinished jobs....
# letting OCamlbuild go through ocamlyacc
menhir  --only-preprocess-for-ocamlyacc ../parser/parse.mly > parse.mly
Warning: you are using the standard library and/or the %inline keyword. We
recommend switching on --infer in order to avoid obscure type error messages.
# Save a copy of the dumb parse.mly for whoever doesn't have menhir.
true parse.mly
cp parse.mly ../parser/ml/
```

This also breaks the Homebrew formula when running with `--head`

**Comment by catalin-hritcu** [comment]
OCaml 4.04.1 is not even officially released, is it?
https://ocaml.org/releases/

**Comment by beurdouche** [comment]
It has been released on April 14th and is the default in opam already
http://caml.inria.fr/pub/distrib/ocaml-4.04/

**Comment by catalin-hritcu** [comment]
nope, not default on my machine

**Comment by catalin-hritcu** [comment]
In fact not showing at all in my list even after update:
```
[hritcu@resurrected relational]$ opam switch                                                                           (git)-[master] 
--                -- 3.07    Official 3.07 release
--                -- 3.08.0  Official 3.08.0 release
--                -- 3.08.1  Official 3.08.1 release
--                -- 3.08.2  Official 3.08.2 release
--                -- 3.08.3  Official 3.08.3 release
--                -- 3.08.4  Official 3.08.4 release
--                -- 3.09.0  Official 3.09.0 release
--                -- 3.09.1  Official 3.09.1 release
--                -- 3.09.2  Official 3.09.2 release
--                -- 3.09.3  Official 3.09.3 release
--                -- 3.10.0  Official 3.10.0 release
--                -- 3.10.1  Official 3.10.1 release
--                -- 3.10.2  Official 3.10.2 release
--                -- 3.11.0  Official 3.11.0 release
--                -- 3.11.1  Official 3.11.1 release
--                -- 3.11.2  Official 3.11.2 release
--                -- 3.12.0  Official 3.12.0 release
3.12.1-old-camlp5  I 3.12.1  Official 3.12.1 release
3.12.1             I 3.12.1  Official 3.12.1 release
--                -- 4.00.0  Official 4.00.0 release
4.00.1             I 4.00.1  Official 4.00.1 release
4.01.0             I 4.01.0  Official 4.01.0 release
--                -- 4.02.0  Official 4.02.0 release
4.02.1             I 4.02.1  Official 4.02.1 release
--                -- 4.02.2  Official 4.02.2 release
4.02.3             I 4.02.3  Official 4.02.3 release
4.03.0             I 4.03.0  Official 4.03.0 release
4.04.0             C 4.04.0  Official 4.04.0 release
system             I system  System compiler (4.04.0)
# 484 more patched or experimental compilers, use '--all' to show
```

**Comment by beurdouche** [comment]
```
4.04.0  I 4.04.0  Official 4.04.0 release
system  C system  System compiler (4.04.1)
```
Strange, I have it. Also when you install opam on a new machine, 4.04.1 is the default.

**Comment by beurdouche** [comment]
Ahah, it is not yet the default everywhere apparently...
But well, in all cases everyone will have this problem soon :(

**Comment by cpitclaudel** [comment]
@beurdouche Did you try just copying `src/extraction/ml/FStar_Extraction_ML_PrintML_4.04.0.ml` to `src/extraction/ml/FStar_Extraction_ML_PrintML_4.04.1.ml` and seeing what happens? Maybe it doesn't even need changes.

**Comment by kyoDralliam** [comment]
The simple fix is as @cpitclaudel said just to copy the latest printml and hope that it works. There is no default case for new ocaml version because I was scared of silently using an incompatible version of printMl. If anybody has a better idea to manage that situation please share.

**Comment by beurdouche** [comment]
https://www.reddit.com/r/ocaml/comments/65bnx5/ocaml_4041_released_dedicated_to_the_memory_of/

I think we can just copy-paste the file, we'll test with victor and push a fix today..

**Comment by beurdouche** [comment]
https://github.com/FStarLang/FStar/commit/a7ae77ea
@victor-dumitrescu, can you confirm that nothing more is needed and close ?! Thanks

**Comment by victor-dumitrescu** [comment]
@beurdouche Yes, this is the approach we took so far, having different versions of the printer for different versions of the OCaml compiler. So this works in principle, but I'm a bit concerned about the growing number of copies of this file (currently 4).

In particular, the prettyprinter for versions 4.03.0, 4.04.0 and now 4.04.1 is identical, so this issue only seems to be that the API of Pprintast is different for 4.02.3. I agree with @kyoDralliam 's concern about not defaulting to an OCaml version we haven't tested with, but I think we could use the same FStar_Extraction_PrintML for the 3 versions we know it currently works with.
