### ISSUE TITLE
Wrong internal qualifiers on identifiers when using interactive mode with interfaces / unified, new interleaving semantics for interactive and batch mode

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#993]
In `test.fsti`:

```
module Test
val t : Type0
type s = t
```

In `test.fst`:

```
module Test
let t = nat
assume val foo : t -> unit
let f (x:s) = foo x //<-- fails here with expected `t` got `s`
```

**Comment by nikswamy** [comment]
This is way more complex than I thought it would be to fix. The trouble is really that interactive mode for interfaces is trying to hack its way around trying to simulate the batch mode interleaving. But, the simulation doesn't really work and this messes up a bunch of internal invariants of the typechecker/name resolution mechanism.

Here's some context:

0. In batch mode, we find an interleaving of test.fsti and test.fst building a module that looks pretty much like:

``` 
module Test
val t : Type0
let t = nat

type s = t
assume val foo : t -> unit
let f (x:s) = foo x
```
The resulting module is very standard and everything works out without surprises.

1. In interactive mode, when we start checking `test.fst` and and find that it has a corresponding `test.fsti` the code load parses, desugars and type-checks the contents of `test.fsti` first (using the interface scoping rules for it, which implicitly `assume`s every `val`). And then proceeds to check the chunks of `test.fst` presented to it interactively. 

The trouble is that when desugaring `test.fsti` as an interface, 
  a. the identifier `t` is given delta qualifier `Delta_constant`, meaning that it can't be unfolded to its definition (since it's just a `val` and has no definition)
  b. the identifer `s` is given delta qualifier `Delta_defined_at_level 1`, since its definition can be unfolded once to  reach a constant

Now, as we then desugar and typecheck the module implementation, the occurrence of `s` in `let f (x:s) = ...` is also tagged as `Delta_defined_at_level 1`. However, in the context of the implementation, this is wrong. Since now `t` has a definition--in fact its defined at level 2, since it can be unfolded once to `nat`, and then to `int`. So, `s` should really have delta level 3 instead of 1. This incorrect level annotation confuses type inference which decides that `t` and `s` are not unifiable, since after (the maximum permissible) 2 unfoldings of `t` (to a refinement of `int`) and 1 unfolding of `s` (to `t`), they still have different head constructors. 

Rather than piling hack upon hack and trying to fix up these delta level qualifiers, we really should find a way to make the interactive mode compute exactly the same interleaving that the batch mode would compute.

**Comment by nikswamy** [comment]
@protz 

Here might be one way to do it:

Instead of feeding the entire interface as a prefix when starting the interactive mode on `test.fst`, we:

1. parse test.fsti into a `list AST.decl` and store these "interface decls" in the initial desugaring environment.

2. Then we parse chunks from `test.fst`. As we try to desugar a given `d:decl` in the implementation, we call `FStar.Parser.Interleave` giving it the current list of "interface decls" in the desugaring environment as well as `d:decl` from the implementation. The interleaving may consume some of the interface decls, returning `d` preceded by whatever interface decls it consumes. We proceed to desugar the returned decls, updating the desugaring environment with the interface decls that remain.

3. When we reach the end of the module we check that no more interface decls remain in the desugaring environment.

Note, we could follow exactly this process in batch mode too.

**Comment by nikswamy** [comment]
Started working on implementing this scheme in my branch ...

**Comment by fournet** [comment]
Thanks! I bumped into other instances, triggered e.g. by the need to alias abstract datatypes. I agree about the risk of duplicating code between the two modes. Getting different behaviours between the two will remain puzzling; conversely your proposal (do the interleaving early and incrementally in both modes) would yield e.g. a more similar ordering of errors. Maybe part of a broader discussion of interfaces?

**Comment by msprotz** [comment]
@nikswamy and I chatted about it this morning... mostly about how to come up with a declarative spec instead of an operational one. We came up with this:

The interleaving of *partial module* `A.fsti` and *incomplete module* `A.fst` is the union of the declarations from `A.fsti` and `A.fst` such that:
- any two declarations within the same file remain in the same order in the interleaving
- any `let` is preceded by the corresponding `val`, if any
- there are no `val`s without a corresponding `let`.

The interleaving algorithm, when it succeeds, returns an ordering of declarations that satisfies the criteria above. Thus, it is correct, but not necessarily complete. The interleaving is undefined when there is a `val` without a `let`.

Two interleavings that satisfy the criteria above are equivalent.

*Sketch:* Assume that they differ only by a swap. Then the environment is of the form `Γ = Γ₁; x = ...; y = ...; Γ₂` where `x` does not appear in `y` (otherwise they would've been ordered). Then swapping these two declarations yields the same program.

**Comment by nikswamy** [comment]
The behavior of interactive and batch mode verification of interfaces should now be the same.

The only difference is that in batch mode, we check that you have implemented everything claimed by the interface.

So far, in interactive mode, we don't yet have a way of indicating that the module being edited is complete, so we don't yet check that the interface implementation is complete. 

Should be easy to surface something in the UI to indicate this though.
